### ISSUE TITLE
Feldkontrollen

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#10]
Bitte zuerst Zähleineinheit, dann Anzahl

**Comment by barbalex** [comment]
Das wäre sehr einfach und wenig Aufwand.

Mir schien es logischer, die Felder in derselben Reihenfolge zu setzen, wie die Daten z.B. im Strukturbaum aufgelistet werden und man es mündlich am ehesten sagt.

Was meinst du?

**Comment by csalzmann** [comment]
Nein, lieber zuerst so wie in der Eingabe, also zuerst Zähleinheit, dann Anzahl

**Comment by barbalex** [comment]
Aber bei der Eingabe ist es ja zuerst Anzahl, dann Einheit, dann Methode - wie man es mündlich am ehesten sagt

**Comment by csalzmann** [comment]
Nein, Zähleinheit ist bei uns sehr wichtig weil zielrelevant, und so ist es auch in den Protokollblättern. Deshalb bitte zuerst Zähleinheit, dann Anzahl. Bitte :)!

**Comment by barbalex** [comment]
gemacht, bitte kontrolliere ob es so passt
