### ISSUE TITLE
EK, andere Zähleinheit

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#100]
Hier braucht es noch ein Kommentarfeld, um die andere Zähleinheit zu beschreiben.

**Comment by barbalex** [comment]
Aufwand: ca. 2 Stunden (das Feld müsste ja wohl auch in allen Exporten erscheinen)

**Comment by barbalex** [comment]
Duplikat von https://github.com/barbalex/apf2/issues/14
