### ISSUE TITLE
EK, Übereinstimmung mit Idealbiotop

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#101]
Selektion wird nicht gespeichert (Punkte sind nicht sichtbar, rsp. blitzen nur kurz auf)

**Comment by barbalex** [comment]
Wann passiert das? Bei mir funktioniert es

**Comment by csalzmann** [comment]
Mac Chrome und Firefox OK. Das hat bei mir zuhaus nicht funktioniert, weiss aber nicht, ob es jetzt auch wieder funktionieren würde. Ich schliesse mal.
