### ISSUE TITLE
Nach Pop-Löschen Blank (Absturz)

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#102]
Ist mir jetzt schon ein paar Mal passiert, dass ich aus einer Beobachtung heraus eine Pop gebildet habe. Anschliessendhab ich die TPop verschoben und die nun leere Pop gelöscht. Und dann krieg ich ein ganz gelbes Fenster ohne Inhalt. Muss dann jeweils Applikation neu starten. Passiert nicht jedes Mal, aber doch merklich.

**Comment by barbalex** [comment]
Passiert natürlich nicht, wenn ich es probiere :-|

**Comment by barbalex** [comment]
Ich schliesse diesen Issue weil schon alt und nicht nachvollziehbar. Falls das Problem wieder auftritt, bitte wieder öffnen
