### ISSUE TITLE
Blank nach Wechsel Layer in Karte

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#103]
Nach Wechsel TPop zu "nicht zuzuordnen". Passiert auch nicht immer (brauche aber diese Funktion auch nicht so oft).
Es hängt halt alles irgendwie mit der Karte zusammen.

**Comment by csalzmann** [comment]
Oder bei Klick auf die Selektierte TPop..

Diese Dinge passieren mir übrigens bei Firefox und Google (PC). Mac habe ich nicht probiert, weil ich diese Arbeiten im Moment zu Hause mache.

**Comment by csalzmann** [comment]
Oder bei Klick auf selektierte Beobachtung..

**Comment by barbalex** [comment]
> Nach Wechsel TPop zu "nicht zuzuordnen"

Was ist damit gemeint?

Heisst das: Wenn du eine zugeordnete Beobachtung auf "nicht zuzuordnen" setzt?

**Comment by barbalex** [comment]
> Oder bei Klick auf die Selektierte TPop.

Das verstehe ich nicht. Wie selektierst du eine TPop? In der Karte, im Strukturbaum oder im Filter? Und wie hängt das mit dem Wechsel von Layern zusammen?

Und was heisst "blank"? Verschwindet die Hintergrundkarte? Ist die Karten-Spalte leer? Ist die ganze Anwendung bzw. der Tab leer?

**Comment by barbalex** [comment]
Steht das alles im Zusammenhang mit bestimmten Tätigkeiten in der Karte?

Muss man z.B. zugeordnet haben, damit das passiert?

**Comment by csalzmann** [comment]
Also: Blank sieht so aus:
![bildschirmfoto 2017-11-07 um 11 31 32](https://user-images.githubusercontent.com/6047564/32489142-41bb08da-c3af-11e7-84cb-0d3c474a593c.png)

**Comment by csalzmann** [comment]
auf Mac.
![bildschirmfoto 2017-11-07 um 11 33 11](https://user-images.githubusercontent.com/6047564/32489283-b98f4dc6-c3af-11e7-8a20-aadffae65239.png)

Passieren kann es, wenn man auf "zoom" in der Karte drückt. zB. auf "Beobachtungen zugeordnet" (da ist es mir jetzt 4x hintereinander passiert).

Das ist zugegebenermassen nicht gerade die häufigste Wahl. Aber damit kann man wenigstens den Fehler zuverlässig reproduzieren.

Auf PC ist mir das eben regelmässig auch bei anderen "Zooms" passiert. Das scheint hier auf Mac stabiler.

**Comment by barbalex** [comment]
Ich verstehe immer noch nicht, was du genau machst.

Was ist

> "zoom" in der Karte?

- Sind das die Zoom-Schaltfläche oben links in der Karte?
- Oder ist das eine der Zoom-Funktionen im Layertool, dass auf eine oder alle Pop/TPop/Beob zoomt?

**Comment by barbalex** [comment]
Duplikat von https://github.com/barbalex/apf2/issues/116, sollte also gelöst sein
