### ISSUE TITLE
wollmilchsau

### ISSUE THREAD

**Issue by kmarti** [barbalex/apf2#104]
Lieber Alex

Weshalb kann ich die "Wollmilchsau" für einzelnen Arten nur bei "lokal installierter APFloraDB" herunterladen? und was heisst lokal installiert?

Herzliche Grüsse

Karin

**Comment by barbalex** [comment]
Die Version für einzelne Arten kannst du herunterladen. Gerade darum gibt es sie.

Die Version für alle > 500 Arten hat früher (vor dem Wechsel von MySQL nach PostgreSQL) den Server in die Knie gezwungen (er ist nicht sehr stark). Darum habe ich sie inaktiv gesetzt. Vorsichtshalber habe ich sie inaktiv gelassen. Aber vielleicht funktioniert es ja mit PostgreSQL. Wobei der Server schon beansprucht würde.

Wenn ich die Anwendung bei mir im Entwicklungsmodus laufen lasse, greift sie auf eine Kopie der Datenbank, die auf meinem Computer liegt (und nicht auf dem Web-Server). Mein Computer ist viel stärker als der apflora-Server.
