### ISSUE TITLE
Daten 2: zeigt Status AP nicht an, Daten 1 aber schon

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#106]
Hilft vielleicht zur Fehlersuche bei Nr. 30?
![unbenannt](https://user-images.githubusercontent.com/6047564/32049048-d5c55f34-ba4b-11e7-816d-709439b8ca9f.PNG)

**Comment by barbalex** [comment]
Leider nein, denn es werden alle Daten nicht angezeigt.

**Comment by barbalex** [comment]
Passiert natürlich nicht, wenn ich es probiere.

Wie machst du das?

**Comment by csalzmann** [comment]
Gute Frage!
Also beim ersten Versuch hat es grad wieder 2"geklappt", dh Daten 2 ohne Status.
Bei weiteren Versuchen hab ich nun gemerkt, dass die Daten 2 stehen bleiben. Ich navigiere also im Strukturbaum 2, aber die Daten 2 orientieren sich allein an Daten 1. Anbei 2 Beispiele.
Auf Mac, Chrome.
Da ich ja aber meistens innerhalb der gleichen Art arbeitete mit Daten 1 und 2, ist mir das bis anhin gar nicht aufgefallen. Es betrifft ja auch nur den Artnamen. Nachher stimmt es, wenn man Pop/TPop anklickt. Drum nicht mega schlimm. Ich dachte anfänglich ja nur, es hätte etwas mit dem Fehler 30 zu tun.

![bildschirmfoto 2017-11-07 um 10 49 50](https://user-images.githubusercontent.com/6047564/32487331-b69916fc-c3a9-11e7-955a-f8e5335fdc37.png)
![bildschirmfoto 2017-11-07 um 10 51 30](https://user-images.githubusercontent.com/6047564/32487345-be2db526-c3a9-11e7-9f7c-5c9c34e6a757.png)

**Comment by barbalex** [comment]
Ich schliesse diesen Issue weil schon alt und nicht nachvollziehbar. Falls das Problem wieder auftritt, bitte wieder öffnen
