### ISSUE TITLE
Qualitätskontrolle: falsche Meldung "keine TPop hat den Status der Pop"

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#107]
Bsp. O. palustris, Pop 51 und 80, beide Pops haben enstsprechende TPops.

Fehler auch schon bei Nr. 83 erwähnt, dort anderes Bsp

**Comment by barbalex** [comment]
Dieser Fehler stammt daher, dass "angesiedelt, aktuell" im Datenbankfeld "PopHerkunft" _zwei_ Sachen sein kann:
- angesiedelt vor Beginn AP, aktuell
- angesiedelt nach Beginn AP, aktuell

Bei der Population wurde _vor Beginn AP_ gesetzt. Bei der Teilpopulation 3 ist es _nach Beginn AP_. Wahrscheinlich wurde ein "bekannt Seit" Wert verändert.

Es ist wirklich dringend nötig, dass wir dieses Feld korrigieren. Aber eben: Der Aufwand wird sehr gross. Für mich ist das nächsten Frühling gesetzt.

Ich werde wohl schon wieder einen Flick programmieren müssen: nämlich dass die Qualitätskontrolle damit umgehen kann, dass diese verschiedenen Werte dasselbe sind. Das ist aufwändig, fehlerträchtig und wird den Aufwand um die Sache richtig zu stellen nur noch höher und fehlerträchtiger machen.

Aber es muss wohl sein :-(

**Comment by barbalex** [comment]
Korrigiert, aber ACHTUNG:

Die bisherige Abfrage enthielt eine Bedingung, die meines Wissens nicht beabsichtigt war: Sie lieferte nämlich nur Ergebnisse, wenn die Population den Status 210 ('angesiedelt vor Beginn AP, aktuell') hatte.

Ich habe diese Bedingung nun entfernt. Könnte also sein, dass die Kontrolle jetzt Fälle meldet, die ihr verpasst, wenn ihr diese Arten nicht nochmals kontrolliert.

Sorry!
