### ISSUE TITLE
Export Kontrollen - auch ohne Zählung 

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#108]
Ich habe letzte Woche einige wenige EK-Eingaben gemacht. Nun fehlen die Zählungen dazu. Ich kann einfach fast nicht glauben, dass ich die so oft vergessen haben sollte (zumal ich es eben immer noch unpraktisch finde, dass man für die Eingabe der Zählungen soviel mal klicken muss und mir das bei der Eingabe wieder bewusst wurde - vielleicht finden wir doch mal noch eine intuitievere Lösung?). Also konkret sind es bei Opalustris 3, bei Potamogeton 4 solcher Eingaben ohne Zählungen.

OK, sag niemals nie..., vielleicht habe ich es ja tatsächlich nicht eingegeben. Aber schon komisch. Dann wollte ich schauen, ob es noch mehr solche Fälle geben könnte. Diese werden in den Exporten aber gar nicht ausgegeben. 

Könntest Du deshalb bitte den Export Kontrollen mit denjenigen EKs ergänzen, die zwar eine Eingabe im allgemeinen Fenster haben, nicht aber in den Zählungen?

**Comment by csalzmann** [comment]
hier noch die fehlenden Zählungen. Werde diese morgen jedoch ergänzen:
![unbenannt](https://user-images.githubusercontent.com/6047564/32050959-21fa9fd4-ba53-11e7-8bb7-3a4469b298ee.PNG)
![unbenannt1](https://user-images.githubusercontent.com/6047564/32050961-22180632-ba53-11e7-9766-28c71d08ad1b.PNG)

**Comment by barbalex** [comment]
> Könntest Du deshalb bitte den Export Kontrollen mit denjenigen EKs ergänzen, die zwar eine Eingabe im allgemeinen Fenster haben, nicht aber in den Zählungen?

Ich bin nicht ganz sicher, was du meinst. Obiger Satz heisst glaube ich, dass ich im Export der Kontrollen weitere Kontrollen ergänzen soll (EKs sind doch Kontrollen, oder?). Das kann nicht gemeint sein, weil der Export ja alle Kontrollen liefert.

Hast du etwa gemeint, dass im Export neben den eigentlichen Daten ein ausgewertetes Feld erscheinen soll, das darauf hinweist, wenn eine Kontrolle keine Zählung hat?

Falls ja: Das macht den Export sehr viel anspruchsvoller. Das kriege ich zwar sicher hin. Aber ob der Server das erträgt?

**Comment by csalzmann** [comment]
Es ist so, dass wenn eine EK (Erfolgskontrolle) in der DB aufgenommen wird ohne Zählung, sie dann nicht im Export erscheint. Jetzt habe ich präzisierend gemerkt: sie erscheint nicht in "Kontrollen Anzahl pro Zähleinheit", aber sehr wohl in "Kontrollen".
Von daher ist ja mein Wunsch erfüllt:). Ich wollte einfach nach EKs ohne Zählung suchen können.

**Comment by barbalex** [comment]
Ich habe jetzt den View `apflora.v_kontrzaehl_anzproeinheit` so angepasst, dass er auch Kontrollen anzeigt, die keine Zählung haben.

Du kannst diesen Export nun nach leeren `TPopKontrZaehlId` filtern und erhältst alle Kontrollen ohne Zählung.

Ist das in eurem Sinn oder soll ich die Änderung wieder rückgängig machen?
