### ISSUE TITLE
Qualitätskontrolle - falsche Meldung "Pop urspr erloschen, es gibt TPop mit abw. Status"

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#109]
Bsp. Liparis, Pop 33. Da stimmt alles mit den Stati.

**Comment by barbalex** [comment]
Zwei der Teilpopulationen sind aber potentielle Wuchs-/Ansiedlungsorte.
Die Kontrolle meldet (wie ihr Name sagt), dass das nicht gleich "ursprünglich, erloschen" ist.

Ich glaube, es ist in eurem Sinn, wenn die Kontrolle so lautet:

> Population: Status ist "ursprünglich, erloschen". Es gibt Teil-Populationen (ausser potentiellen Wuchs-/Ansiedlungsorten) mit abweichendem Status:

...und die Kontrolle auch das prüft.

Einverstanden?

**Comment by barbalex** [comment]
umgesetzt
