### ISSUE TITLE
Feldkontrollen, Jungpflanzen

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#11]
Anzahl Jungpflanzen - sollte dort nicht einfach nur " auch Jungpflanzen vorhanden" stehen, wie bei den Freiwilligen-Kontrollen?

Wenn Jungpflanzen separat gezählt werden, dann gehörte das doch zu den Zählungen.

**Comment by barbalex** [comment]
Gute Frage.

Dieses Feld heisst "TPopKontrJungpfl" und war schon immer so implementiert. Es akzeptiert Werte vom Typ Integer, war also wohl schon immer für die Erfassung von Anzahlen konzipiert.

Das Feld bei den Freiwilligen-Kontrollen ("TPopKontrJungPflJN") akzeptiert Smallint, war also für Wahr/Falsch Werte konzipiert.

Ich stimme dir zu, dass TPopKontrJungpfl besser bei den Zählungen erfasst würde, indem dort "Jungpflanzen" ergänzt würden. Das wäre für alle Beteiligten besser verständlich und würde bei allfälligen Auswertungen von Zählungen Aufwand und Fehler reduzieren.

Da schon viele Daten erfasst wurden, müsste man:

- den neuen Typ von Einheit schaffen
- die bisherigen Daten aus TPopKontrJungpfl  zu den Zählungen migrieren
- das aktuelle Feld TPopKontrJungpfl  löschen (auch in allen Abfragen, Views etc.)
- wenn gewollt, TPopKontrJungPflJN bei den Feldkontrollen anbieten

Das wäre wohl ca. 2 Stunden Aufwand.

**Comment by csalzmann** [comment]
Lieber Alex
Wir haben in den alten Daten recherchiert. Die Zählungen beim Feld "Jungpflanzen" wurden eigentlich immer auch in die Zählung miteinbezogen. Falls nicht, wurden diese aber auch die ganze Zeit über nun nie ausgewertet, wie haben ja immer nur die Zähleinheiten angeschaut für die Berichte.
Dieses Feld ist einfach verwirrend und ich meine es verantworten zu können zu entscheiden, dass wir die bisherigen Einträge einfach weglassen statt migrieren. Dafür bieten wir neu ein Feld Jungpflanzen mit Ankreuz-Funktion an, so wie bei den Freiwilligen auch.

**Comment by barbalex** [comment]
Beschlossen als:

> altes Feld "TPopKontrJungpfl" ersatzlos entfernen.
> "TPopKontrJungPflJN" bei EK anzeigen.

**Comment by barbalex** [comment]
Ist umgesetzt
