### ISSUE TITLE
Qualitätskontrolle - falsche Meldung wegen Ansiedlung

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#110]
Bsp Liparis, TPop 92.1. Es gab hier gar nie eine Ansiedlung ??
![unbenannt](https://user-images.githubusercontent.com/6047564/32052632-2d85a4e2-ba59-11e7-8fb9-2e76c4bbe229.PNG)

**Comment by barbalex** [comment]
In diesem Fall war schlicht der Titel der Kontrolle falsch. Es sollte lauten:

> Teilpopulation mit Kontrolle (im Berichtjahr) aber ohne Teilpopulations-Bericht (im Berichtjahr):

Und das trifft in diesem Fall zu.

Danke für die Meldung.
