### ISSUE TITLE
Ziele nicht beständig

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#111]
Eine ganz merkwürdige Eigenschaft ist mir bei den Zielen aufgefallen.

Bsp. Ophrys araneola

Gestern auf PC Mozilla: Bei allen Zielen waren die Ziele jeweils 4-fach drin, dh, 4x Ziel 1, 4x Ziel 2 etc. Es waren dabei jedoch nicht einfach die Ziele von Ophrys araneola vervierfacht, es waren auch Ziele von anderen Arten dabei. Da das eine Ziel von Trieben handelte, dachte ich, es wird sich wohl um Potamogeton handeln. Es könnte aber auch eine andere Art gewesen sein, die mit Trieben gezählt wird. Habe leider keinen Screenshot gemacht, weil ich das erst mit Karin Marti heute anschauen wollte und natürlich nicht damit gerechnet habe, dass es heute anders ausschauen könnte.

Nun heute auf Mac, ChS:
Google Chrome: Ziele an sich richtig, werden aber nur bis 2016 (!) aufgelistet.
Mozilla: Ziele z.T. doppelt (also ähnlich wie gestern) den Jahren 2008-2016, danach normal. Aber: man kann keine Zielerreichung eingeben (bei Chrome schon).

![bildschirmfoto 2017-10-27 um 15 44 05](https://user-images.githubusercontent.com/6047564/32107340-948054fa-bb2e-11e7-9547-416ae6a01ebc.png)

![bildschirmfoto 2017-10-27 um 15 51 29](https://user-images.githubusercontent.com/6047564/32107461-efb2fe36-bb2e-11e7-9e22-89992a6ea216.png)

**Comment by barbalex** [comment]
Seufz. Die Ziele sind extrem schwierig in diese Struktur zu pressen. Das gibt Arbeit :-(

**Comment by barbalex** [comment]
Hm. Jetzt kann ich das nicht (mehr?) provozieren. Wie oft passiert es dir?

**Comment by barbalex** [comment]
Aha. Man provoziert es, in dem man nacheinander in mehreren Arten Ziele öffnet

**Comment by barbalex** [comment]
o.k., ich _glaube_ es ist gelöst
