### ISSUE TITLE
Kopieren Feldkontrolle - Zählung wird nicht mitkopiert

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#112]

**Comment by barbalex** [comment]
Das würde ich auch erwarten. Weil sie 1:n verbunden in einer separaten Tabelle enthalten sind.

Ihr möchtet also, dass sie mit kopiert werden?

**Comment by csalzmann** [comment]
ja, gerne.

**Comment by barbalex** [comment]
gemacht
