### ISSUE TITLE
Karte-Anzeige von verschiedenen Arten

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#114]
Wäre es möglich, dass auf der Karte die Populationen/Teilpopulationen von verschiedenen Arten angezeigt werden? Also wenn man z.B. die Daten 1 und 2 offen hat, dass dann nicht nur die aktiven Populationen von Daten 1 angezeigt werden, sondern auch die von Daten 2?

**Comment by rebeccakurz** [comment]
oder wäre es zumindest möglich, dass man die Populationen/Teilpopulationen in den Daten 2 aktivieren kann, so dass sie auf der Karte angezeigt werden? (evt. auch nicht gleichzeitig mit Daten 1, falls das nicht geht). Das geht meines Wissens nicht, oder gibt es da einen Trick?

**Comment by csalzmann** [comment]
Es wäre tatsächlich cool, wenn man je nach Wahl Daten 1 oder Daten 2 in der Karte anzeigen könnte. Evtl. könnte man dazu jeweils die einen oder anderen Daten irgendwie "aktivieren"? Weisst Du was ich mein? Für die Eingabe der Massnahmen wäre das sehr hilfreich.

**Comment by barbalex** [comment]
Ich bin nicht sicher, ob ich euch verstanden habe.

**Daher nachfolgend ein paar Verständnisfragen:**

Meint ihr mit "Daten 1" und "Daten 2": Populationen und/oder Teilpopulationen von "Art 1" und "Art 2"?

Was sind "aktive Populationen"? So wie ich den Begriff "aktiv" verwende, ist das immer höchstens eine Population, nämlich die im Strukturbaum aktive (sie ist auch "aktiv", wenn untergeordnete Daten aktiv sind)

> oder wäre es zumindest möglich, dass man die Populationen/Teilpopulationen in den Daten 2 aktivieren kann, so dass sie auf der Karte angezeigt werden?

Um die Populationen einer Art anzuzeigen, wählt man die Art im Strukturbaum. Aber das ist so klar, dass es vermutlich nicht gemeint war?

**Möglichkeiten:**

Grundsätzlich könnt ihr einfach die Art wechseln und die Karte zeigt sofort die Daten dieser Art an.
War es das, was ihr sucht?

Ihr könnt natürlich auch mehrere Tabs öffnen und in den jeweiligen Karten unterschiedliche Arten anzeigen.

NICHT implementiert ist es, auf derselben Karte gleichzeitig Daten von mehreren Arten anzuzeigen.

**Comment by rebeccakurz** [comment]
Daten 1 und Daten 2 bezieht sich auf die Überschriften oben rechts. Also Daten 1 gehört zu Strukturbaum 1 und Daten 2 zu Strukturbaum 2. 

aktive Pop sind genau das, also wenn sie im Strukturbaum und in der Karte gelb hinterlegt sind, wenn sie angeklickt werden. 

Doch es ist genau so gemeint, aber ich würde gerne auch die Populationen im Strukturbaum 2 aktivieren können, so dass diese auf der Karte angezeigt werden. Das ist ja im Moment nicht möglich oder?

**Comment by barbalex** [comment]
O.k., ihr habt also gemeint: Wenn man zwei Strukturbäume öffnet, zeigt die Karte nur die Daten des ersten Strukturbaums an.

Und ihr möchtet folgendes können:

1. abwechselnd die Daten der Strukturbäume in der einen Karte anzeigen
2. oder gleichzeitig
3. oder ev. für jeden Strukturbaum eine Karte öffnen

Grundsätzlich geht alles. Zu berücksichtigen ist:

1. Könnte am einfachsten umzusetzen sein. Aber wie sieht man, welche Daten angezeigt werden?
2. Keine Ahnung, wie ich die Benutzerführung machen sollte. Wie bestimmt man, ob die Daten eines Baums angezeigt werden? Und vor allem: wie unterscheidet man Daten der Bäume voneinander?
3. Die Benutzerführung ist einfach. Die Umsetzung dauert wohl ein paar Stunden. Und ob die Bildschirmfläche reicht, um 6 Spalten darzustellen? Kein Problem, wenn ihr die neuen krummen super-breiten Bildschirme kauft :-)

**Comment by csalzmann** [comment]
zu 3. Oder man klickt halt die nicht grad benötigte Karte weg.

zu 1. Könnte man bei den Layern anwählen in einer zusätzlichen Zeile, oberhalb von Populationen. Da gibst Du Strukturbaum 1 oder 2 zur Auswahl (könnte man dann ankreuzen). z.B. 
![bildschirmfoto 2017-11-22 um 16 49 51](https://user-images.githubusercontent.com/6047564/33136345-478b7658-cfa5-11e7-87bb-0c9c170455cd.png)
Vielleicht hat Rebecca morgen ja noch eine Idee :).

**Comment by rebeccakurz** [comment]
Fände Nummer 1 ausreichend. Finde auch Charlottes Vorschlag mit der zusätzlichen Zeile im Layer gut. Wenn man Strukturbaum 1 oder 2 auswählen kann, gibt es hoffentlich am wenigsten Verwirrung, welcher jetzt in der Karte gezeigt wird.

**Comment by barbalex** [comment]
Ich nehme Variante 3 auf die Liste möglicher Erweiterungen für 2018.

Ausser jemand von euch findet sie nicht zielführend.

**Comment by barbalex** [comment]
An der Sitzung vom 20.6.2018 wurde diskutiert, ob ev. mehrere Arten gewählt werden können, die gleichzeitig dargestellt würden. Wurde aber nicht beschlossen.

**Comment by barbalex** [comment]
schliesse, da kein aktuelles Bedürfnis mehr
