### ISSUE TITLE
Jahresbericht: Ergänzung Überschrift D

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#115]
Bitte in Klammern ergänzen beim letzten Abschnitt "Bemerkungen zum Aussagebereich D" : Einschätzung der Wirkung des Aktionsplans insgesamt auf die Art

**Comment by barbalex** [comment]
Leider habe ich keine Ahnung, was du meinst.

Es gibt keinen Abschnitt mit dem Titel "Bemerkungen zum Aussagebereich D". Es gibt aber einen mit dem Titel "D. Einschätzung der Wirkung des AP insgesamt auf die Art".

Und dein Formulierungsvorschlag sieht fast genau so aus.

Oder hast du mit "beim letzten Abschnitt" gar nicht den Titel, sondern zusätzlichen Text innerhalb dieses Bereichs gemeint?

Kann es sein, dass du eine alte Version des Berichts anschaust?

**Comment by csalzmann** [comment]
Entschuldige meine Ungenauigkeit. Ich meine in der Applikation. 
![bildschirmfoto 2017-11-23 um 15 23 42](https://user-images.githubusercontent.com/6047564/33177277-5715d808-d062-11e7-8865-cfa764cd3bfc.png)

**Comment by barbalex** [comment]
Es ist immer wieder interessant zu sehen, wie einfach man sich missverstehen kann :-|

Ist umgesetzt.

**Comment by csalzmann** [comment]
Und wie schön ist es, wenn es am Ende eine einfache Lösung gibt:). Danke.
