### ISSUE TITLE
Karte-Schwierigkeiten beim Zoomen

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#116]
Wenn ich mir in der Karte eine aktive Teilpopulation zeigen lassen will und die Karte dann aus einem grossen Massstab hineinzoomen muss, passiert es häufig, dass die ganze Karte/Seite abstürzt. Es erscheint dann das auf dem Bildschirm:
![bildschirmfoto 2017-11-16 um 12 58 55](https://user-images.githubusercontent.com/30288503/32890238-39b8efb4-cace-11e7-9146-cbd3f0d72a98.png)
und man muss die Karte neu laden...

**Comment by rebeccakurz** [comment]
Habe gemerkt, dass das passiert ist, weil die aktive Population noch keine Koordinaten hatte... sollte aber ja eigentlich trotzdem nicht gleich abstürzen...

**Comment by barbalex** [comment]
Verstehe ich das richtig: Es passiert, wenn:

- die aktive Teilpopulation Koordinaten hat
- ihre Population keine Koordinaten hat
- und man auf die aktive Teilpopulation zoomt?

**Comment by rebeccakurz** [comment]
Nein es passiert, wenn man auf eine aktive Population oder auch Teilpopulation zoomen will, die keine Koordinaten hat.

**Comment by barbalex** [comment]
O.k., das konnte ich nachvollziehen :-)

Sollte gelöst sein.
