### ISSUE TITLE
Kontrollen nach Datum aufsteigend auflisten (im selben Jahr)

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#118]

**Comment by barbalex** [comment]
Das habe ich beim Aufbau der letzen Version explizit gefragt.

Wenn das so ist, reicht es auch nicht mehr, im Strukturbaum nur das Jahr anzuzeigen. Oder?

Die Sortierung ist einfach und machbar.

Bei den Auswertungen gibt es aber echte Probleme. Bisher konnte man nach Rücksprache mit euich davon ausgehen, dass es pro Jahr nur eine Kontrolle gibt.

Welche Kontrolle soll denn ausgewertet werden, wenn es in einem Jahr mehrere gibt? Welche soll z.B. im Jahresbericht dargestellt werden?

Das ist tiefgreifend.

**Comment by csalzmann** [comment]
Das muss ein Missverständnis sein, weil wir haben schon sehr lange mehrere EKs pro Jahr. Nur schon EK-Freiwillige und Feldkontrollen.
Dann müssen wir das besprechen, auch mit Karin.
Mein Vorschlag: Prio Feldkontrolle, dann Prio höchste Anzahl.

**Comment by csalzmann** [comment]
Und nein, im Strukturbaum muss nicht mehr als das Jahr angezeigt werden. Aber wenn möglich wäre eine Sortierung nach Datum gut, wenn das möglich ist.

**Comment by barbalex** [comment]
Die Sortierung nach Datum habe ich umgesetzt. Fehlt ein Datum, wird 1.1. des Jahrs gewählt. Ohne Jahr und Datum wird zuunterst sortiert.

Das mit den Prioritäten unter Kontrollen gibt eine grössere Übung :-|

Es sind zig Abfragen für den Jahresbericht betroffen. Und alle müssen viel komplizierter werden. Und da das letztes Jahr nicht passierte, könnte das die Vergleiche mit früher beeinflussen.

**Comment by barbalex** [comment]
Ich schliesse dieses Issue: Prioritäten für Auswertungen von Kontrollen wäre ein neues Issue.
