### ISSUE TITLE
Kontrolle zuletzt geändert

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#119]
BearbeiterIn "undefined"

**Comment by barbalex** [comment]
Richtig. Aber es ist Geschichte:

Als Version 2 noch ganz neu war, hat es (nicht nur bei Kontrollen) nicht funktioniert und daher `undefined` erfasst. Das war zwischen März und Anfang September 2017. Seit Einführung der sicheren Anmeldung übernimmt das der Server.
