### ISSUE TITLE
Kopieren und einsetzen funktioniert nicht!

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#120]
Das Kopieren und Einsetzen einer Teilpop. in eine andere Population funktioniert manchmal einfach nicht (aber nicht immer). Dann muss ich die Seite neu laden, nachher geht es wieder. Ist aber mühsam, braucht Zeit und nachher lädt es die Strukturbäume 1 und 2 gleich, so dass ich im einen Strukturbaum wieder die Art suchen muss, an der ich gerade arbeite.
Vorher hat auch das Kopieren und wieder Einsetzen einer Population inkl. Teilpops. nicht funktioniert! (Pop. wurde kopiert, aber ohne Teilpop.)

**Comment by rebeccakurz** [comment]
Jetzt funktioniert das Kopieren und Einsetzen schon wieder nicht! Habe den ganzen Morgen mit der Datenbank gearbeitet und Massnahmen erstellt. Kopieren hat bis jetzt funktioniert, jetzt nicht mehr...

**Comment by rebeccakurz** [comment]
Funktioniert immer noch nicht. muss jedesmal die Seite wieder aktualisieren, dann funktioniert es ein paarmal, dann wieder nicht. Kopieren von Teilpopulationen und kopieren von Populationen inklusive Teilpopulationen. 
Habe am Montag und heute an verschiedenen Computern gearbeitet. MacOS auf Chrome.

**Comment by rebeccakurz** [comment]
Ich muss im Moment ziemlich viele Massnahmen eingeben! Wenn das Kopieren nicht funktioniert, kann ich nicht vorwärts machen! (Geht damit nämlich viel schneller, weil ich viele gleiche Massnahmen habe). Also wenn möglich bitte bald beheben!

**Comment by barbalex** [comment]
Ich habe soeben 15 Minuten lang:

- Teilpopulationen kopiert und eingesetzt
- Populationen inklusive Teilpopulationen kopiert und eingesetzt
- innerhalb desselben Strukturbaums, meist aber zwischen Strukturbäumen

Bei mir funktioniert es bisher lupenrein.

Ich glaube deine Meldungen natürlich. Bloss kann ich nichts machen, wenn ich den Fehler nicht selber provozieren kann.

**Comment by rebeccakurz** [comment]
Ist bis jetzt nur passiert, wenn ich sehr lange in der Datenbank gearbeitet habe. Also möglicherweise eine Überlastung? Werde mich melden falls es wieder passiert.

**Comment by barbalex** [comment]
Ich schliesse diesen Issue, weil nicht nachvollziehbar und alt. Falls das Verhalten wieder auftaucht, bitte wieder öffnen.
