### ISSUE TITLE
Jahresbericht, Anz. Zeilen dargestellt erhöhen

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#122]
Mich stört es, dass nur so wenige Zeilen im Text dargestellt werden. So muss ich in einem 2-zeiligen Text z.B. schon scrollen (im vorliegenden Bsp bei Analyse und bei "Bemerkungen zum Aussagebereich D". Bei Erfolgskontrolle werden von 4 Zeilen total 2 dargestellt. Könnten nicht standardmässig mind. 10 oder 15 Zeilen dargestellt werden (sofern es soviel Text gibt)? Ich scrolle lieber das ganze Formular herunter als in den einzelnen Textabschnitten.

![bildschirmfoto 2017-11-23 um 15 24 25](https://user-images.githubusercontent.com/6047564/33177558-4d37c674-d063-11e7-8617-7c1ba7cceaed.png)

**Comment by barbalex** [comment]
Hm. Ich kann das Verhalten ev. ein bisschen zuverlässiger machen, indem ich Updates der Formulare steuere. Zugrunde liegt aber ein Fehler in der verwendeten Software, die für einen grossen Teil der Layout-Elemente verwendet wird.

In den nächsten Wochen/Monaten sollte die neue Version dieser Software erscheinen. Es wird dann ziemlich viel Aufwand sein, zu aktualisieren. Aber gemäss Aussage des Entwicklers ist dieser Fehler darin nicht mehr enthalten.

**Comment by barbalex** [comment]
O.k., habe gemacht, was ich kann.

Besser wird's hoffentlich beim update von material-ui.

**Comment by barbalex** [comment]
Material-ui ist jetzt aktualisiert. Das Abschneiden geschieht jetzt glaube ich nur selten und es geht höchstens um eine Zeile. Ich schliesse daher den Issue. Falls wieder problematisch, bitte wieder öffnen
