### ISSUE TITLE
schon ausgefüllte Felder -> verschwindende Daten

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#123]
Wenn ich in derselben Teilpopulation zwei Massnahmen nacheinander erstelle (z.B. eine Anpflanzung und eine Ansaat), dann ist es mir schon zweimal passiert, dass bei der zweiten Massnahme die Bearbeiterin schon vorausgefüllt war. (also ich habe eine neue Massnahme erstellt und das Feld der Bearbeiterin war schon ausgefüllt mit dem Namen, den ich bei der ersten erstellten Massnahme eingefügt habe). Ich habe dann natürlich dieses Feld nicht nochmals angewählt, weil der richtige Name schon darin stand. 
ABER: der vorausgefüllte Name bleibt nicht gespeichert! Also wenn man später in die Massnahme zurückkehrt, ist er verschwunden!
Hatten wir glaube ich schon einmal...

**Comment by barbalex** [comment]
Richtig. Und ja, da war ein Flüchtigkeitsfehler drin :-(

Sorry, ist korrigiert.
