### ISSUE TITLE
AP-Ziele, Fehler bei Berichten

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#125]
Kann nicht allen Zielen einen Bericht hinzufügen. Statt dass das Menü für einen (Ziel-) Bericht mit Rechsklick kommt, bekomme ich die Option, ein neues Ziel hinzuzufügen.

Ausserdem kann ich die alten Zielberichte nicht anschauen, rsp. öffnen.

Habe nun aber den Eindruck, die sind irgendwie verrutscht (z.B. Saxifraga, 2016: Ziel 4 mit 4 Berichten, Ziele 1-3 ohne Bericht.

![bildschirmfoto 2017-11-29 um 14 57 59](https://user-images.githubusercontent.com/6047564/33378678-dd22efc8-d515-11e7-9eba-306f7a480f93.png)

**Comment by barbalex** [comment]
Du hast gezeigt, dass dies offenbar passieren kann.

Ich stelle die übliche Frage: Wie kann ich das provozieren?

Wenn ich dieselben Daten öffne, sind sie korrekt.

**Comment by csalzmann** [comment]
Ich glaube, es klemmt da einfach ein bisschen im Strukturbaum auch. 

Bin jetzt erleichtert aber, dass das doch nicht immer so ist (hab mich noch gewundert). Ich also wieder reload.

Gehe ich (auch bei Saxifraga) zu Zielen 2016 und sage alle öffnen, öffnen sich die Ziele 2013, Cursor springt auch dorthin, 2016 bleibt geschlossen.

Jetzt stimmts aber wenigstens mit den Berichten:)

**Comment by barbalex** [comment]
Passiert das immer noch (manchmal)? Ich schliesse mal. Falls es noch passiert: Bitte wieder öffnen
