### ISSUE TITLE
2 neue Felder in Jahresbericht

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#126]
Wir brauchen noch 2 zusätzliche Textfelder im Jahresbericht, und zwar im Abschnitt C, nach der Zusammenstellung der Massnahmen im Berichtsjahr:

Die Textfelder sollen heissen:

"Weitere Aktivitäten der Aktionsplan-Verantwortlichen" 
und
"Vergleich Ausführung/Planung"

**Comment by barbalex** [comment]
Das wird ziemlich aufwändig und ist ungeplant.

Ich kann es im Notfall schon nächste Woche machen, aber es erfordert Änderungen:

- in der Datenbank:
  - in der Tabellenstruktur
  - in allen Views, die den Jahresbericht verwenden
- in apflora.ch:
  - in der Benutzeroberfläche
  - ev. auch in Qualitätskontrollen?
- in Access:
  - alle Tabellen und Views neu einbinden
  - Jahresbericht anpassen

Das braucht schon ein paar Stunden (4 bis 8) und war nicht geplant bzw. budgetiert.

Ich kann mir vorstellen, dass es auch auf eurer Seite viel terminlichen Einsatz erfordert.

Ist ein bisschen unglücklich, wenn solche Wünsche so kurz vor Berichtabgabe auftauchen.

Ich brauche von euch:
- das o.k., dass ich den Mehraufwand tätigen soll und verrechnen kann
- allfällige Wünsche bezüglich Qualitätskontrollen

Dann kann ich das nächste Woche umsetzen.

**Comment by barbalex** [comment]
Braucht ihr Qualitätskontrollen, die melden, wenn in einem der beiden neuen Felder nichts erfasst wurde?
Es gibt solche Kontrollen für diese Felder:

- JBerBeurteilung
- JBerVergleichVorjahrGesamtziel
- JBerJahr

**Comment by barbalex** [comment]
O.k., habe gemacht:

- in der Datenbank:
  - [x] in der Tabellenstruktur
  - [x] in allen Views, die den Jahresbericht verwenden (inkl. Export)
- in apflora.ch:
  - [x] in der Benutzeroberfläche
  - [ ] ev. auch in Qualitätskontrollen? (Rückfrage offen)
- in Access:
  - [x] alle Tabellen und Views neu einbinden
  - [x] Jahresbericht anpassen
  Neue Datei: https://www.dropbox.com/s/x159kv90ir5hq19/ApFloraAdmin.zip?dl=0

Aufwand bisher: Bloss 2 Stunden. Die neue Architektur rentiert :-)

**Comment by barbalex** [comment]
Zu sagen ist: Ich habe die Felder alle genau so genannt, wie sie im Jahresbericht heissen. 

Mit der neuen Oberfläche haben wir mehr Platz für lange, besser beschreibende Feldnamen.

**Comment by csalzmann** [comment]
Wow Alex!! Das hast Du aber super gemacht!

Eine Bemerkung noch zum Layout (ich klage auf hohem Niveau): die Schrift der neuen Felder ist grösser als die der alten. Und: Wenn zweizeilig (das ist auch bei den "alten" Feldern so) reicht sie in den eingegebenen Text darunter, man kann den Titel dann nicht mehr gut lesen.

![bildschirmfoto 2017-12-01 um 16 05 10](https://user-images.githubusercontent.com/6047564/33488609-7a005b90-d6b1-11e7-841c-995698e8c4bd.png)

**Comment by barbalex** [comment]
> die Schrift der neuen Felder ist grösser als die der alten

Apflora.ch benutzt material-ui. Das ist das Layout, das Google entwickelt hat. Es gehört zum von Google bestimmten Standard, dass die Beschriftung eines Felds zunächst im Feld selbst erfolgt und erst über das Feld wechselt, wenn man Daten darin erfasst. Beim Wechsel darüber wird es kleiner.

Mit anderen Worten: Die anderen Felder sind kleiner beschriftet, weil sie schon Daten enthalten.

**Comment by barbalex** [comment]
Dass Beschriftung und Daten überschneiden ist vermutlich ein Fehler der verwendeten Version von material-ui. Und passiert auch nur, weil die Beschriftung nun so lange ist. Und weil offenbar dein Bildschirm schmal war (bzw. du viele Spalten geöffnet hast), was die Beschriftung zum Umbrechen provoziert.

Ich glaube mich zu erinnern, dass dieser Fehler gemeldet wurde und vermutlich in einem künftigen Update von material-ui korrigiert werden wird.

**Comment by barbalex** [comment]
Aber wenn du Vorschläge hast für gut verständliche kürzere Versionen von Beschriftungen ist ein Update wenig Aufwand.
