### ISSUE TITLE
Absturz, wenn zu viele Layer offen

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#127]
Ist mir jetzt zum zweiten Mal passiert: Hatte Strukturbaum 1, Daten 1, Strukturbaum 2 und die Karte offen und wollte noch die Daten 2 öffnen: Absturz!
Auch das erneute Laden der Seite hat nichts gebracht, die Seite flackerte nur kurz wieder auf und ist dann erneut abgestürzt. (mehrmals versucht)
musste dann die gesamte Seite schliessen und AP-Flora erneut starten.

**Comment by wunderli** [comment]
Heute Probleme mit Daten 2, gibt nach dem anklicken einer Pop/Tpop/Massnahme eine Fehlermeldung.
![bildschirmfoto 2018-04-04 um 15 36 09](https://user-images.githubusercontent.com/26789445/38311240-0020d082-381f-11e8-89e8-f71910375a11.png)

**Comment by barbalex** [comment]
Hoi Anna

Ich werden deinem Fehler nachgehen, da ich ihn gut nachvollziehen kann und er die Arbeit mit Daten2 verhindert.

Danke für die Meldung.

Eine Bitte für das nächste Mal:
Dieser Fehler hat keinen Zusammenhang mit dem Issue, in dem du ihn gemeldet hast. Öffne bitte künftig ein neues Issue, wenn du einen neuen Fehler meldest. Ich habe das hier gemacht: https://github.com/barbalex/apf2/issues/145

Klick bitte dort auf "subscribe" (Schaltfläche rechts), um zu erfahren, wenn ich etwas herausgefunden habe (Du must nur "subscriben", wenn ein Issue nicht von dir stammt. Bei eigenen Issues wirst bist du automatisch "subscribed").

LG, Alex

**Comment by barbalex** [comment]
Passieren die Abstürze noch? Ich schliesse mal. Falls das gelegentlich passiert: Bitte wieder öffnen
