### ISSUE TITLE
AP-Bericht, BearbeiterIn nicht beständig

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#128]
Ich hab den Mechanismus nicht raus, aber bei einigen Arten bleibt im Jahresbericht die BearbeiterIn nicht drin. Ist mir selber jetzt schon mehrmals aufgefallen (ich habs dann immer wieder ergänzt), anderen ist offenbar aber auch aufgefallen. Aktuell fehlt bei mir nun z.B. bei Cardamine dentata die Eingabe.

**Comment by barbalex** [comment]
oh je

Fehler korrigiert.

Falsche Daten wurden keine erfasst, aber es hat die falschen angezeigt.
