### ISSUE TITLE
Qualitätskontrolle: TPop Status erloschen aber Ansaat/Ansiedlung im Berichtsjahr

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#129]
Es fehlt noch diese Kontrolle:

Wenn TPopBericht "erloschen" ist aber im Berichtsjahr oder später eine Ansaat oder Ansiedlung erfolgt, dann muss TPopStatus von "erloschen" auf "Ansaat" oder "Ansiedlung, aktuell" gesetzt werden.

**Comment by barbalex** [comment]
Ist umgesetzt.

Hier die betroffenen pop/tpop (du musst wohl in github abholen, nicht im mail): 
[pop.xlsx](https://github.com/barbalex/apf2/files/1565084/pop.xlsx)
[tpop.xlsx](https://github.com/barbalex/apf2/files/1565085/tpop.xlsx)
