### ISSUE TITLE
Layout Massnahmen Länge Seite

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#13]
Die Infos sind zu fest in die Länge gezogen. Jetzt hat man die wichtigsten Infos nicht mehr auf einer Seite, sondern muss immer scrollen (z.B. um bei einer Massnahme auf die Anzahl Pflanzen zu kommen). Bitte wieder auf eine Seite bringen wie bis anhin.

**Comment by barbalex** [comment]
Einer der Gründe für die grössere Höhe ist, dass Label und Feld nicht mehr in einer Zeile enthalten sind. Das ist sehr bewusst, damit man auch bei kleinen Bildschirmen oder wenn viele Spalten offen sind (Strurkturbaum, ev. zweiter Strukturbaum, Karte, Export, Daten...) arbeiten kann. Diese Flexibilität (die ev. erst künftig an Bedeutung gewinnt) möchte ich nur ungern aufgeben.

Ich könnte generell die Abstände zwischen Feldern verkleinern. Dadurch würde aber vermutlich die Übersichtlichkeit verringert, weil die Trennung zwischen Feldern weniger klar wäre.

In diesem Fall wurde viel Höhe generiert, weil ich das ehemalige Dropdown-Feld für den Typ zu einem Optionen-Feld verwandelt habe. Mit der Absicht, dass die Benutzerin sofort den Überblick hat, ohne das Feld öffnen zu müssen. Und um den Typ zu setzen nur einen Klick benötigt.

Das könnte man natürlich ändern und wieder ein Dropdown-Feld schaffen. Auf meinen Bildschirmen wären danach alle Felder gleichzeitig sichtbar.

Ev. könnte ich irgend was schickes (?) versuchen, so dass man die Felder (ab einer gewissen Breite) in zwei Spalten darstellen kann. Ich weiss noch nicht wie, aber das wäre ev. am besten.

Was meinst du?

**Comment by barbalex** [comment]
Da jetzt ab genügend Breite zwei Spalten benutzt werden, passt das Formular auf meinen grossen Bildschirmen sehr schön rein. Daher schliesse ich dieses issue.
