### ISSUE TITLE
Jahresbericht Zahlen: erloschene TPops werden teilweise nicht erfasst

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#130]
Bsp Spiranthes spiralis.

TPops 101.1/5/6 und TPop 102.3 sind erloschen und für Bericht relevant, werden in den Zahlen vom Jahresbericht aber nicht aufgeführt ?

**Comment by barbalex** [comment]
Das sind alles solche, bei denen wegen der komplexen Abhängigkeit des Status von Daten auf Ebene Art der gewählte Status keinem der gültigen Möglichkeiten entspricht. Altes Problem (https://github.com/barbalex/apf2/issues/30#issuecomment-301299898), super wichtig aber auch sehr aufwändig richtig zu lösen.

Es gibt nur die sehr aufwändige permanente Lösung. Daher werde ich wieder Abfragen laufen lassen müssen, welche falsche Kombinationen korrigieren. Aber eine Sekunde später schon wieder unvollständig sein können. Und daher wohl kurz vor Erstellung des Jahresberichts wiederholt werden müssen.

Kann ich hoffentlich morgen machen.

**Comment by barbalex** [comment]
Wie hier (https://github.com/barbalex/apf2/issues/30#issuecomment-342104430) beschrieben, werden die Stati angepasst, wenn man die Qualitätskontrolle laufen lässt. Das habe ich bei Spiranthes gemacht. Die Stati sind jetzt wieder sichtbar.

Klappt es nun auch im Bericht?

**Comment by barbalex** [comment]
Scheint gelöst zu sein. Falls nicht: einfach wieder öffnen
