### ISSUE TITLE
Arten für Beobachtungen hinzufügen klappt nicht immer

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#131]
Ich habe gerade Arten für Beobachtungen bei verschiedenen Arten hinzugefügt. Das hat teilweise geklappt, teilweise nicht. 
Bei Cardamine dentata und bei Sedum rubens ist die gewählte Art wieder hinausgefallen, nachdem die Webseite aktualisiert wurde. Bei den anderen Arten (etwa 5) ist die gewählte Art allerdings dringeblieben. Ich habe die Webseite auch noch in einem neuen Tab aufgemacht und dort war es ebenfalls so...
![bildschirmfoto 2018-01-08 um 13 52 33](https://user-images.githubusercontent.com/30288503/34671848-62f5efee-f47c-11e7-956e-159b3b80a0c9.png)

**Comment by barbalex** [comment]
Kannst du bitte sagen, welche Arten sich bei welchen Arten _nicht_ hinzufügen liessen?

**Comment by rebeccakurz** [comment]
Bei Cardamine dentata liess sich **Cardamine palustris** nicht hinzufügen und bei Sedum rubens liess sich **Crassula rubens** nicht hinzufügen.

**Comment by barbalex** [comment]
Der Grund ist, dass die Tabellen so konzipiert waren, dass eine Art nur ein mal hinzugefügt werden konnte. Und diese zwei Arten existierten schon.

Ich habe diese Bedingung nun entfernt. Und testhalber Cardamine palustris zu Cardamine dentata hinzugefügt.
