### ISSUE TITLE
Abmelden

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#132]
Es kommt nicht bei allen bei uns im Büro nach dem Abmelden ein neues Anmeldungsfenster. Es kam nun in 2 Fällen (an unterschiedlichen Compis) auch vor, dass das Anmeldefenster nur ganz kurz aufgeblitzt ist, danach konnte man unter dem gleichen angemeldeten User weiterarbeiten.

**Comment by barbalex** [comment]
Das würde ich erwarten, wenn der Browser oder ein Login-Tool wie LastPass automatisch einloggt. In diesem Fall müsstet ihr das automatische Einloggen für apflora.ch ausschalten

**Comment by rebeccakurz** [comment]
Wieso geschieht es dann nur bei einigen Personen und nicht bei allen? Die Seite ist ja so eingestellt, dass man automatisch eingeloggt wird oder wie muss ich das verstehen?

**Comment by barbalex** [comment]
Ob man einen Login-Manager wie LastPass verwendet, ist individuell.

Ebenso individuell ist es, ob man dem Browser sagt, er soll Anmeldungen speichern und künftig auf dieser Seite automatisch anmelden.

Die Seite selbst kann das nicht beeinflussen.

Was apflora macht, um das Anmelden zu vereinfachen, ist: Es speichert eine einmal erfolgte Anmeldung so, dass das Fenster, welches die Anmeldung verlangt, erst wieder öffnet, wenn man explizit abgemeldet hat (oder den Cache geleert hat).

Login-Manager und automatische Anmeldung durch Browser kommen dann zum Zug, wenn das Anmelde-Fenster öffnet.

**Comment by barbalex** [comment]
In Chrome steuert man das automatische Einloggen hier: chrome://settings/passwords

**Comment by barbalex** [comment]
Für Firefox gibt es eine Anleitung hier: https://support.mozilla.org/de/kb/passworter-verwalten-speichern-loeschen-aendern#w_passwairter-ansehen-und-laischen

**Comment by rebeccakurz** [comment]
Okay, danke! Wenn man das automatische Anmelden entfernt, dann bleibt das Anmeldefenster und man muss sich erneut einloggen.

**Comment by barbalex** [comment]
:-)
