### ISSUE TITLE
Jahresbericht Ziele, Zielbericht an falscher Stelle

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#133]
Der jeweilige Zielbericht zu einem bestimmten Ziel erscheint meist nicht an der richtigen Stelle im Baum. Im Bsp unten z.B. ist der Bericht zu Ziel 1 bei Ziel 3 eingefügt. Oder im anderen Bsp werden alle Berichte unter Ziel 4 aufgelistet. Wenn man die Berichte dann anklickt, werden sie rot - und so weiss man dann immerhin, zu welchem Ziel sie gehören. 

![bildschirmfoto 2018-01-11 um 17 15 03](https://user-images.githubusercontent.com/6047564/34835697-dc0755b4-f6f5-11e7-9563-e8f2d34e9309.png)
![bildschirmfoto 2018-01-11 um 17 23 10](https://user-images.githubusercontent.com/6047564/34835709-e29d94a6-f6f5-11e7-9aee-0277c047942e.png)

**Comment by barbalex** [comment]
Passiert das noch? Ich schliesse mal, weil ich es nicht nachvollziehen kann

**Comment by barbalex** [comment]
Ich hab versucht, das zu provozieren. Bisher ist es mir nicht gelungen.

Könnt ihr eine Methode herausfinden, mit der sich das nachvollziehen lässt?

**Comment by barbalex** [comment]
Schliesse weil schon alt und nicht mehr gemeldet
