### ISSUE TITLE
Äste im Baum gehen oft nur nach mehrmaligem Klicken auf

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#134]
Wir bei topos haben uns da schon ein bisschen dran gewöhnt, ich glaub, wir habens noch gar nie gesagt und klicken einfach mehrmals - weil anderes einfach immer viel wichtiger war. Aber richtig ist es schon nicht. Und jetzt haben wir für kurze Zeit ja jemand hier, der die Zielberichte macht. Und ihr fällt es extrem auf. 

Es kann praktisch überall in allen Menüpunkten passieren. Das Dreieck links zeigt zwar nach unten, aber die unteren Äste werden einfach nicht angezeigt. Im Bsp unten: Ziele gehen nicht auf. Dann braucht es 2 weitere Klicks (einmal schliessen, dann nocheinmal öffnen) bis die Ziele dann wirklich sichtbar sind.

Es ist wieder ein Fall, der überall aber nicht regelmässig vorkommt. Ich denke, Du findest aber schon nach ein paar Klicks, was wir meinen...:).

![bildschirmfoto 2018-01-11 um 17 41 43](https://user-images.githubusercontent.com/6047564/34835960-b7d0aa0a-f6f6-11e7-8d53-cc7f2be81312.png)

**Comment by barbalex** [comment]
Richtig. Ist mir auch schon aufgefallen. Aber die Steuerung des Baums ist sooooooooooo kompliziert, dass ich es bisher ignoriert habe :-|

**Comment by barbalex** [comment]
Der Baum wurde bei der Umstellung zu GraphQL vollständig neu gebaut. Daher schliesse ich diesen Issue. Falls es wieder auftreten sollte: bitte einen neuen Issue schaffen
