### ISSUE TITLE
Zielbericht, Bemerkungen

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#135]
In den Bemerkungen zum Zielbericht beginnt der Text oft mit einer Zahl. Nach der Eingabe einer Zahl (die eben am Anfang des Textes steht) kann man aber nachfolgend keinen Leerschlag eingeben. Es ist aber möglich, im Nachhinein mit dem Cursor zur entsprechenden Stelle zu fahren und dann einen Leerschlag einzugeben.

**Comment by barbalex** [comment]
Dieses Problem trat grundsätzlich bei allen Textfeldern auf. Ist jetzt korrigiert

**Comment by kmarti** [comment]
Wenn die Bemerkungen nicht ausgefüllt werden, dann erscheint im Jahresbericht "null" als Text anstatt gar nichts. Ich habe nun jeweils "-" eingegeben, damit das nicht passiert.
