### ISSUE TITLE
Nach "verorte auf Karte" Blank screen

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#136]
![bildschirmfoto 2018-01-30 um 15 46 38](https://user-images.githubusercontent.com/6047564/35572527-176ced60-05d5-11e8-98a8-d7261b769505.png)

Ist mir nun grad 2x hintereinander passiert. Danach muss man reloaden, dann ist die TPop aber tatsächlich wo man sie hingesetzt hat.

**Comment by barbalex** [comment]
Bisher wurden die Koordinaten offenbar teilweise als Zeichen und nicht als Zahlen übermittelt. Offenbar schluckt das die dafür verwendete Software nicht mehr, daher dieser Fehler.

Sollte korrigiert sein.
