### ISSUE TITLE
Karte als Bild speichern funktioniert nicht

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#138]
Wenn man auf der Karte auf das Symbol: "Karte als png speichern" klickt, speichert es die Karte nicht und es verschwinden die Navigationszeichen von der Kartenoberfläche (z.B. Teilpop. einblenden, etc.)

**Comment by rebeccakurz** [comment]
Okay, also der Export des Bildes sollte nachher doch irgendwo sichtbar sein? Am unteren Rand wie bei den anderen Exporten oder so? Bei mir zeigt es das nirgends an und ich finde den Kartenausschnitt auch nicht auf dem Desktop oder in den Downloads. Bei Charlotte funktioniert es ebenfalls nicht, der Kartenausschnitt ist nachher nirgendwo zu finden. Habe es ein paar Mal probiert bei verschiedenen Arten und verschiedenen Teilpopulationen...
Auf Chrome, Mac OS

**Comment by barbalex** [comment]
Wenn ich dich richtig verstehen, verschwinden also die Navigations-Elemente auf der Karte nicht permanent?

Sonder das Problem ist, dass du danach keine .png-Datei hast?

Falls das zutrifft:
Was passiert, wenn man eine Datei herunterlädt, ist in deinem Browser eingestellt. Du musst bei Chrome diese url wählen: chrome://settings (oder: im Menu oben rechts die Einstellungen wählen). Dann musst du auf erweitert klicken. Und dort diese Einstellung setzen:
<img width="444" alt="download" src="https://user-images.githubusercontent.com/669783/35928064-84b0829e-0c2c-11e8-83a1-f2a6617684fc.png">

**Comment by rebeccakurz** [comment]
Okay, danke. Das hat funktioniert. Aber trotzdem komisch, dass es nicht wie bei den anderen Downloads automatisch geschieht. Das müsste man ja vorher wissen, dass man diese Einstellung machen muss...

**Comment by barbalex** [comment]
Das ist in allen Browsern so.

**Comment by barbalex** [comment]
Nur: was voreingestellt ist, ist nicht sicher in allen Browsern gleich

**Comment by csalzmann** [comment]
Aber Alex: Alle anderen Exporte der FloraDB (TPop etc) können wir automatisch in unseren Download-Folder downloaden, nur dieses JPG nicht. Das ist doch das komische, nicht?

**Comment by barbalex** [comment]
Für den Export der Daten wird ein anderes Tool verwendet. Das sich offenbar nicht an die Einstellung im Browser hält.

Was im Grunde genommen kein gutes Benehmen ist. Denn eine Benutzer, der im Browser ein Verhalten für Downloads einstellt, erwartet auch, dass dies klappt.

**Comment by csalzmann** [comment]
OK. Dann müssen wir von jetzt an wohl immer den Speicherort angeben. Aus unserer Sicht verhält sich eben nicht das Export-Tool nicht korrekt, sondern das Kartentool. Aber Hauptsache, wir verstehen es nun plusminus ;).

**Comment by barbalex** [comment]
Nein, ihr müsst nicht jedes mal den Speicherort angeben: So wie es tönt, wollt ihr immer an den selben Ort speichern: Das könnt ihr dort einstellen. Oder ihr könnt einstellen, dass ihr immer wählen wollt, wohin die Datei geht.

**Comment by csalzmann** [comment]
Das hatten wir eigentlich so eingestellt, dann kann man aber eben die Karte nicht runterladen. Sie wird einfach nicht im Download-Folder gespeichert.
![bildschirmfoto 2018-02-07 um 18 11 49](https://user-images.githubusercontent.com/6047564/35930626-b9f3ad22-0c32-11e8-9bba-c69fd91b4ae4.png)
Wenn Rebecca nun bei den Einstellungen auf "vor dem Download fragen..." klickt, dann klappts bei ihr. Ich bin davon ausgegangen, bei mir würde es automatisch auch gehen. Bei mir klappt das aber immer noch nicht, ich werd nicht gefragt, wohin ich das heruntergeladenen png speichern soll. Hauptsache, es geht im Moment bei Rebecca, sie braucht diese Funktion jetzt gerade. Also wegen dem bitte heute keine Nachtschicht:)!!

**Comment by barbalex** [comment]
:-|

**Comment by rebeccakurz** [comment]
Ich wollte gerade wieder einen Kartenausschnitt als Bild speichern und es hat wieder nicht funktioniert! Gestern, als ich es ausprobiert habe, habe ich einfach einen Ausschnitt aus der Standardkarte (Open Street Map farbig) gewählt und das hat auch geklappt. Aber jetzt wollte ich einen Kartenausschnitt mit eingeblendeten Teilpopulationen mit dem Hintergrund ZH Orthofoto Sommer RGB und überlagernd den ZH Übersichtsplan. **Das funktioniert aber nicht!**
Ich habe es dann nochmals mit der Standardkarte probiert, mit dieser hat es weiterhin funktioniert...

**Comment by barbalex** [comment]
Uhm, richtig. Der Server des Kantons Zürich liefert in diesem Moment die Daten nicht, weil er keine CORS-Anfragen erlaubt:
<img width="467" alt="cors" src="https://user-images.githubusercontent.com/669783/35964565-657ca614-0cb8-11e8-9b5d-d76be3b6ec2c.png">

Da kann ich nichts machen.

Somit funktioniert der Druck bei allen anderen Ressourcen, aber nicht, wenn sie vom Kanton Zürich sind.

**Comment by barbalex** [comment]
Ich schliesse diesen Issue, weil es sich um nicht beeinflussbares Verhalten von Drittsoftware handelt.
