### ISSUE TITLE
Kopieren von Tpop-Koord. in Pop

### ISSUE THREAD

**Issue by wunderli** [barbalex/apf2#139]
Kopieren von Tpop-Koord. in Pop. setzt in der Tpop. auf die alten Koordinaten/Koord. in Pop. zurück.
Evtl. Problem, wenn neue Koordinaten in Tpop. eingefüllt werden und diese nicht richtig im System gespeichert werden?
Nach ein paar Anläufen stimmt es in der Pop, aber muss in der Tpop nochmals angepasst werden!
Bsp. Potalb 5.1

**Comment by barbalex** [comment]
Sorry, ich verstehe nicht, was du meinst.

Kannst du mir bitte nochmals Schritt für Schritt erklären, was du machst, was passiert, und was daran falsch ist?

**Comment by wunderli** [comment]
1. Habe beim Digitalisieren von alten Pläne gesehen, dass bei Potentilla alba 5.1 (und Tpop anderer Arten) die Koordinaten falsch/ungenau sind.
2. Ich habe die Koordinaten in der Teilpopulation berichtigt.
3. Ich wollte die neuen Koordinaten aus der Teilpopulation in die Population kopieren.
4. Statt die neuen Koordinaten in die Population zu kopieren, wurden in der Teilpopulation die Koordinaten auf die alten zurückgesetzt.
5. Liegt das Problem daran, wenn das System die neuen Koordinaten nicht richtig schluckt? Klick in anderes Feld nötig?
6. Arbeitete wie meistens im Firefox...

**Comment by barbalex** [comment]
Gibst du die neuen Formate ein?

BITTE NICHT!!!

Wir haben noch nicht auf LV95 umgestellt. Ich habe ein paar mal nachgefragt, aber noch keinen Auftrag von Charlotte, umzustellen.

Und es müssen alle Koordinaten im selben Format sein.

Hoffentlich haben wir jetzt kein Puff :-(

**Comment by wunderli** [comment]
Nein Alex, mit "neuen" Koordinaten meine ich die "genaueren" Koordinaten nach meiner Digitalisierung.

Diese sind aber immer noch im "alten" Koordinatensystem.
So weit ich aus dem Massnahmen-Export für die Digitalisierung gesehen habe, sind einzig bei Nuphar pumila neue Koordinaten eingetragen.

Die Umstellung erfolgt erst, wenn wir die neuen Datengrundlagen fürs ArcGIS haben. Diese zu bestellen ist die Aufgabe von Jasmin, die frühestens wieder im April daran arbeiten wird...

**Comment by barbalex** [comment]
O.k., zurück zum möglichen Fehler.

Du hast also Koordinaten geändert und dann in die Population kopiert.
Dabei wurden die Koordinaten der Teilpopulation verändert (zurück zum alten Wert).
Ich kann das nicht provozieren. Das heisst: Wenn ich das mache, geschieht kein Fehler.

Gibt es eine Art, das zu provozieren?
