### ISSUE TITLE
Zählungen: mit Bemerkungsfeld

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#14]
Bitte einfügen.

**Comment by barbalex** [comment]
Das gab es bisher nicht.

Man müsste:

- neues Feld schaffen
- es im Formular ergänzen
- bestimmen, bei welchen Views und Exporten es mit kommen soll. Und dort ergänzen

Aufwand: ca. 2 Stunden.

**Comment by csalzmann** [comment]
Es gab es eigentlich schon, es war das allgemeine Bemerkungsfeld, in dem wir auch Angaben zu den Zähleinheiten verfasst haben (und die jetz natürlich fehlen).

**Comment by barbalex** [comment]
Fragen:

* Ihr wollt das auf Ebene Zählung statt Feldkontrolle?
* Ist das für normale Zählungen?
* Ist es für EKF-Zählungen?
* Falls für EKF-Zählungen: Soll es für Freiwillige sichtbar sein?
* Falls für EKF-Zählungen und es soll für Freiwillige sichtbar sein: Soll es auch in der Druckversion sichtbar sein?

**Comment by rebeccakurz** [comment]
@csalzmann @wunderli Alex wartet hier noch auf eine Rückmeldung von uns. Ich hätte jetzt gesagt:

- Ja, auf Ebene Zählung
- Für normale und EKF-Zählungen
- Für Freiwillige ebenfalls sichtbar
- Ja, auch in Druckversion

Was meint ihr?

**Comment by csalzmann** [comment]
Auf Ebene Kontrolle behalten (es soll eben ein neues, zusätzliches Feld geben), dieses 

* Für normale und EKF-Zählungen
* Für Freiwillige ebenfalls sichtbar
* Ja, auch in Druckversion

**Comment by barbalex** [comment]
Also, zusammengefasst:

- Auf Ebene Kontrolle, zusätzliche zum bisherigen Bemerkungsfeld
- Für Freiwilligen- und normale Kontrollen
- Für Freiwillige sichtbar
- Im Druck sichtbar, d.h. künftig Teil des Feld-Erhebungs-Formulars

Wie Soll das Feld heissen?

**Comment by barbalex** [comment]
Wenn ich weiss, wie das Feld heissen soll, kann ich es umsetzen.

**Comment by csalzmann** [comment]
Bemerkungen zur Zählung

**Comment by csalzmann** [comment]
Lieber Alex
Kannst Du Dich diesem Issue nochmals annehmen? Es ist nur ein Textfeld, was direkt Bemerkungen zur Kontrolle betrifft. Z.B. "wegen Trockenheit sind nur wenige blühende Pfl.", oder "Kontrolle zu früh/spät, nur wenige Pflanzen gesehen".
Diese Bemerkungen können dann auch ein wichtiger Hinweis für die Interpretation des Kontrollberichts sein.
Früher gab es das, mit der Umstellung der Datenbank und der Trennung von Kontrolle und Zählung ging es verloren.

**Comment by barbalex** [comment]
Ja, kann ich. Sollte in den nächsten zwei Wochen passieren. Falls nicht, erinnere mich wieder daran.

> Früher gab es das, mit der Umstellung der Datenbank und der Trennung von Kontrolle und Zählung ging es verloren

Das stimmt sicher nicht: Wenn ich jemals ein Feld gelöscht hatte, hätten wir darüber diskutieren müssen, was mit den darin enthaltenen Daten passiert. Daher wüsste ich es sicher.

**Comment by csalzmann** [comment]
Nein, natürlich ist es nicht gelöscht, das wollte ich Dir nicht unterstellen! Aber seit die Zählung von der Kontrolle abgehängt ist, ist das allgemeine Bemerkungsfeld jetzt nicht mehr für Bemerkungen, welche explizit die Zählung betreffen, "zugänglich". Ich hab mich unpräzise ausgedrückt.

**Comment by barbalex** [comment]
>  seit die Zählung von der Kontrolle abgehängt ist, ist das allgemeine Bemerkungsfeld jetzt nicht mehr für Bemerkungen, welche explizit die Zählung betreffen, "zugänglich"

Bloss verstehe ich nicht, wieso sie die Zugänglichkeit ändert, da wir uns oben auf folgendes geeinigt haben:

> Auf Ebene Kontrolle, zusätzlich zum bisherigen Bemerkungsfeld

Wenn es direkt neben dem anderen Bemerkungsfeld liegt, ist es doch genau so zugänglich bzw. unzugänglich wie das bisherige?

**Comment by rebeccakurz** [comment]
Ah da haben wir ein Missverständnis. Wir möchten dieses Bemerkungsfeld auf Ebene der Zählung.
Also gerne hier: 
<img width="664" alt="Bildschirmfoto 2019-09-09 um 11 45 14" src="https://user-images.githubusercontent.com/30288503/64520908-510be580-d2f7-11e9-87ee-9db3b7897bc3.png">

**Comment by barbalex** [comment]
Also, nochmals zusammengefasst:

- Neues Feld "Bemerkungen" auf Ebene Zählung
- Für EK und EKF
- Für Freiwillige sichtbar
- Im Druck sichtbar, d.h. künftig Teil des Feld-Erhebungs-Formulars

In den Feldkontrollen ist das einfach.

In den Freiwilligen-Kontrollen ist es aus Platzgründen wesentlich schwieriger. Denn das Formular soll auf eine Seite passen. Felder müssen gross genug sein, dass eine Person etwas rein schreiben kann. Und das Formular füllt heute schon eine ganze A4-Seite, siehe hier: 
[ekf-formular.pdf](https://github.com/barbalex/apf2/files/3591643/ekf-formular.pdf).

Wenn ich nun also bei den Zähleinheiten je eine Zeile ergänze. Wo soll ich den entsprechenden Platz einsparen?

Oder darf das Formular auf die zweite Seite umbrechen?

**Comment by rebeccakurz** [comment]
Also gerade weil das EKF-Formular ja auf einer Seite Platz hat, ist ja hier das allgemeine Bemerkungsfeld nicht von den Zählungen getrennt wie bei den Feldkontrollen. Meiner Meinung nach könnte es also bei den EKF-Formularen so bleiben wie es ist.
Was meinst du Charlotte?

**Comment by barbalex** [comment]
Die Diskussion ist noch nicht kompliziert und verzettelt genug. Darum bringe ich neue Aspekte ein ;-)

Ein neues Feld schaffen ist ein relativ grosser und im Prinzip unumkehrbarer Eingriff (umkehren wäre sehr aufwändig). V.a. wenn dasselbe nun in zwei unterschiedlichen Feldern erfasst würde bzw. wenn der Erfassungsort dabei ändert, wie das bei den bisherigen Vorschlägen der Fall ist.

Wenn es letztlich v.a. darum geht, dass das Bemerkungsfeld zur Kontrolle nahe an den Zählungen sichtbar ist, könnte es auch eine Lösung sein, die Zählungen wie bei den EKF in das Formular für die EK zu integrieren.

Das ist relativ viel Arbeit - aber das Schaffen eines neuen Felds ist auch Arbeit.

Grösstes Problem bei dieser Lösung wäre wohl der Platz: Die EK hat schon extrem viele Felder und soll offenbar noch mehr bekommen (Gefährdung). Daher gibt es heute schon drei Register in diesem Formular. Wenn das Bemerkungsfeld optisch neben den Zählungen liegen soll, müssten diese wohl unter den aktuellen Feldern oder dem Bemerkungsfeld angefügt werden. Das ginge wohl und wäre somit die Alternative. Aber ihr müsst euch bewusst sein, dass das Formular wohl in vielen Fällen höher wird als der Bildschirm.

**Comment by barbalex** [comment]
@csalzmann @rebeccakurz 

Ich warte noch auf eine Antwort zum Vorschlag, die Benutzer-Oberfläche anzupassen statt der Datenstruktur.

Wenn ich euch richtig verstanden habe, geht es primär darum, dass das Bemerkungsfeld der Kontrolle in der Nähe der Zählungen sichtbar ist.

Es geht _nicht_ darum, dass hier andere Informationen erfasst würden als im Bemerkungsfeld der Kontrolle. Nur das würde letztlich ein neues Feld (= die Anpassung der Datenstruktur) begründen.

Das Schaffen eines zusätzliches Feldes in der Zählung hätte zur Folge, dass Bemerkungen zur Zählung je nach Situation im einen oder anderen Bemerkungsfeld zu finden wären, d.h. sie würden verzettelt. Konkret: 
- Bisher wurden Bemerkungen zur Zählung im Bemerkungsfeld der Kontrolle erfasst
- Künftig würden Bemerkungen zur Zählung in EK meistens im Bemerkungsfeld einer der Zählungen erfasst (nur sichtbar in genau dieser Zählung - nicht sichtbar in Kontrolle und anderen Zählungen)
- Vermutlich würden Bemerkungen zur Zählung auch in EK künftig teilweise ins Bemerkungsfeld der Kontrolle erfasst (z.B. weil sie für alle Zählungen gelten oder weil die Benutzerin will, dass sie in der Kontrolle sichtbar sind)
- Nach Rebecca's Argumentation würden Bemerkungen zur Zählung in EKF auch künftig immer im Bemerkungsfeld der Kontrolle erfasst
- In Exporten von Kontrollen müssten Bemerkungen aus Zählungen ähnlich den Zählungen zusammengefasst werden. Was die Sache nicht klarer macht

Damit hätten wir die Datenstruktur aufgebläht und Unordnung geschaffen.

Daher gehe ich davon aus, dass ihr primär das Bemerkungsfeld möglichst nahe an den Zählungen sehen wollt. Und dass daher nicht die Datenstruktur sondern die Benutzeroberfläche angepasst werden muss. Dass wir also die Zählungen ähnlich wie bei den EKF in das EK-Formular integrieren. Mit dem Unterschied, dass beliebig viele Zählungen erfasst werden können (nicht wie im EKF-Formular).

Das gibt mehr Aufwand, als geplant (4 statt 2 Stunden). Aber ich habe den Eindruck, es ist das, was euch am meisten bringt.

Bleibt am Ende dann noch die Sache mit dem Strukturbaum, in dem ihr offenbar die Zählungen - entsprechend wie bei den EKF - doch noch separat sehen wollt.

Weil die Sache mehr Aufwand gibt als geplant und die Erfassung von Zählungen beeinflusst, warte ich auf eure Rückmeldungen, bevor ich das umsetze.

**Comment by rebeccakurz** [comment]
Planungssitzung vom 28.1.2020: Bemerkungsfeld wird im Moment nicht gebraucht.
