### ISSUE TITLE
LV95, auch für Beobachtungen!

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#140]
Ich bin mit meiner TPop gerade im Nirvana gelandet, weil ich die Koord. der Beobachtung auf die TPop übertragen habe..

**Comment by barbalex** [comment]
Na ja, früher (gute alte 68-er Generation) konnte man dem Nirvana durchaus etwas abgewinnen ;-)

Uff. Vergessen.

**Comment by barbalex** [comment]
Das update (in QGIS in 10 Sekunden gerechnet) hat via Access für 450'000 Datensätze 9 Stunden gebraucht !!!
