### ISSUE TITLE
Qualitätskontrolle: Bekannt seit

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#141]
Qualitätskontrolle ergänzen, so dass "bekannt seit" von

Pop = älteste TPop

TPop = mind. Jahr älteste zugeordnete Beobachtung

**Comment by barbalex** [comment]
Verstehe ich richtig: Du möchtest zwei neue Qualitätskontrollen:

1. "bekannt seit" von Pop soll der ältesten "bekannt seit" ihrer TPop entsprechen
2. TPop, welchen Beobachtungen zugeordnet wurden: "bekannt seit" muss gleich oder älter sein als das Jahr der ältesten zugeordneten Beobachtung

Stimmt das?

**Comment by csalzmann** [comment]
Ja genau so! Issue 181 nimmt das eigentlich nochmals auf. Das wäre sehr lässig, hätten wir dies für den Jahresbericht.

**Comment by csalzmann** [comment]
Lieber Alex. 
Ja, wir hätten das schon sehr gern. Karin hat mich auch grad drauf aufmerksam gemacht, dass Du diese 2 QK eigentlich auch schon für 2018 offeriert hast und dass diese gemäss Abrechnung noch hängig seien. Es muss aber nicht mehr vor Weihnachten sein..

**Comment by barbalex** [comment]
Ja, da hat Karin recht. Hab ich jetzt auch gemerkt.

Peinlich...

O.k., wird gemacht!

**Comment by barbalex** [comment]
ist umgesetzt

**Comment by wunderli** [comment]
Lieber Alex

Diese Qualitätskontrolle funktioniert gut- fast zu gut.
Bei Littorella und Typha minima haben wir soeben neue Beobachtungen zugeordnet.
Leider gab es viele Beobachtungen ohne gültiges Datum.
In allen Teilpopulationen, in welchen eine solche Beobachtung zugeordnet wurde, kam der Fehler, dass es Beobachtungen gibt, die "vor bekannt seit".

Gibt es eine Möglichkeit diese Beobachtungen mit "ungültigem" Datum aus dieser Qualitätskontrolle zu entfernen?

Liebe Grüsse

Anna

**Comment by kmarti** [comment]
haben wir nicht ein Datum definiert, das eingesetzt wird, wenn eben kein Datum vorhanden ist?

**Comment by barbalex** [comment]
Gebt mir das Datum des ??-Manuskripts durch, dann aktualisiere ich die Daten.

**Comment by csalzmann** [comment]
Könntest Du nicht alle Beobachtungen mit dem Datum 0001.01.01 von der Qualitätskontrolle ausschliessen? So wird die Beobachtung ohne Datum ja dargestellt.

**Comment by barbalex** [comment]
O.k., habe gerade gesehen, dass das Baumann-Manuskript offenbar selten Daten nennt und die Beobachtungen irgendwo zwischen 1880 und 1930 liegen. Quelle: http://www.floz.zbg.ch/wordpress/wp-content/uploads/2015-03-03-Anleitung-Aufarbeitung-historischer-Daten.pdf.

Ausschliessen wäre also wohl richtig.

**Comment by barbalex** [comment]
O.k., ist umgesetzt

**Comment by rebeccakurz** [comment]
Hoi Alex
Kann es sein, dass diese Beobachtungen ohne Datum doch wieder in den Qualitätskontrollen erscheinen?
Wie beim Beispiel im Screenshot: TPop bekannt seit 1901, älteste zugeordnete Beobachtung von 1901 (was ja noch keine Fehlermeldung geben würde) und dann noch 3 Beobachtungen aus dem Baumann-Manuskript, welche ja kein Datum haben und nur mit 0001.01.01 angegeben sind. Also muss die Fehlermeldung in der Qualitätskontrolle ja von diesen Einträgen stammen?

<img width="568" alt="Bildschirmfoto 2019-10-31 um 16 52 38" src="https://user-images.githubusercontent.com/30288503/67963898-a8e01200-fbff-11e9-8b59-12bdf496c670.png">
<img width="1661" alt="Bildschirmfoto 2019-10-31 um 16 50 44" src="https://user-images.githubusercontent.com/30288503/67963906-abdb0280-fbff-11e9-8620-1aedfca15b75.png">

**Comment by barbalex** [comment]
Die Bedingung, um die Baumann-Daten auszuschliessen, habe ich am falschen Ort eingefügt 🤦‍♂ 
Ist korrigiert.
Danke für die Meldung.
