### ISSUE TITLE
Idealbiotop: mit Foto(s) und Bemerkungen dazu ergänzen

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#142]
Bitte Zeit für Installation in Offerte aufnehmen

**Comment by barbalex** [comment]
Erste Gedanken:

https://cloudinary.com nutzen. U.a. darum:

- es braucht sowieso einen Cloud-Dienst, um die Bilder zu speichern
- es braucht sowieso eine CDN, um die Bilder rasch anzeigen zu können
- es braucht Funktionen für:
  - hoch-laden
  - in verschiedenen Grössen und Auflösungen zu nutzen
  - allenfalls: bearbeiten

Neue Tabelle `idealbiotop_img` oder `ib_img` mit Feldern:

- id
- ib_id (= 1:n)
- bemerkungen

**Comment by barbalex** [comment]
Ist umgesetzt
