### ISSUE TITLE
Fehler bei Qualitätskontrolle: Kontrolle ohne Zaehlung

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#143]
Bei O. araneola gibt es eine Fehlermeldung betr. fehlender Zählung, obwohl es Zählungen gibt. Siehe Screenshot.

![bildschirmfoto 2018-04-03 um 13 56 54](https://user-images.githubusercontent.com/6047564/38248151-bc983b84-3747-11e8-977e-15b1260ca922.png)

**Comment by barbalex** [comment]
Die Meldung ist richtig: Denn es gibt eine zweite Freiwilligen-Kontrolle für das Jahr 2017: https://apflora.ch/Projekte/1/Arten/278300/Populationen/1176904983/Teil-Populationen/2146451002/Freiwilligen-Kontrollen/11592?feldkontrTab=entwicklung&projekteTabs=tree&projekteTabs=daten. Und diese hat keine Zählung.
<img width="433" alt="2018-04-04_12h02_40" src="https://user-images.githubusercontent.com/669783/38301574-3f215c76-3800-11e8-9ccc-0e40b7b1db17.png">
Wenn du diese Kontrolle löscht, sollte die Meldung verschwinden.

**Comment by csalzmann** [comment]
Danke, habs nicht gesehen!
