### ISSUE TITLE
Falsche Koordinaten bei einigen Tops!!!!

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#144]
Einige Teilpopulationen haben falsche Koordinaten! 
Zum Beispiel Thesium rostratum, TPop 42.1, hat in der Flora DB die Koordinaten: 2709030/1280322. Beim Export vom 13.12.2017 waren die Koordinaten noch 675487/268893. Laut den jetzt angegebenen Koordinaten würde die TPop sogar ausserhalb des Kantons liegen. Die restlichen TPops sind noch am richtigen Ort verortet.
Anderes Beispiel: Gagea villosa, Top 17.1. Dort sind die jetzigen Koordinaten: 2700782/1268232. Beim Export vom 13.12.2017 lauteten die Koordinaten noch: 698810/232510.

Auf diese TPops mit falschen Koordinaten sind wir zufällig gestossen, gut möglich, dass es noch weitere gibt. 
Ich habe ein paar Stichproben-Kontrollen gemacht, aber auf die Schnelle keine weiteren falschen Koordinaten gefunden.

**Comment by csalzmann** [comment]
Gibt es eine Möglichkeit zu kontrollieren, ob diese falschen Koordinaten irgendwie mit der Koordinatenumwandlung zu tun haben? Dh, hast Du noch ein Backup vor der Umwandlung gemacht, wo man die alten Koordinaten noch einsehen könnte? Für uns ist es einfach unverständlich, wieso die Koordinaten sonst nach dem 13.12. noch so verfälscht worden wären - deshalb kommen wir jetzt auf die Koordinaten-Umwandlung, auch wenn das nicht wirklich viel Sinn macht.

**Comment by csalzmann** [comment]
Bevor klar ist, ob wir ein generelles Koordinatenproblem haben, können wir die Exporte für Infoflora und WebGISBUN nicht abgeben.

**Comment by barbalex** [comment]
Sicher kein Fehler der Transformation, siehe email
