### ISSUE TITLE
Nicht-Anzeigen von Auswahlmöglichkeiten

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#146]
In der Flora-DB zeigt es mir die Auswahlmöglichkeiten zum Anklicken nicht an. Also z.B. bei den Freiwilligen-Kontrollen kann man ja ankreuzen ob auch junge Pflanzen vorhanden sind. Die Auswahlmöglichkeiten sind "kein Wert" "ja" und "nein". Nun zeigt es mir zwar den Text an, aber das Feld zum Anklicken nicht. Wenn ich mit der Maus darüber fahre, kann ich es auch anklicken, der Kreis erscheint kurz und verschwindet dann wieder. Man kann also nicht überprüfen, was alles angeklickt ist und was nicht. Ist nicht nur bei den Freiwilligen-Kontrollen so, sondern auch bei den Feld-Kontrollen und bei den Massnahmen.
![bildschirmfoto 2018-04-16 um 13 19 17](https://user-images.githubusercontent.com/30288503/38806579-fcfb9126-4179-11e8-8b99-b9e73e55b4e8.png)
![bildschirmfoto 2018-04-16 um 13 19 37](https://user-images.githubusercontent.com/30288503/38806593-05fd11c8-417a-11e8-8721-83bc8150a540.png)

**Comment by rebeccakurz** [comment]
Ah ja und ich arbeite auf MacOS mit Chrome

**Comment by barbalex** [comment]
Das liegt an material-ui, das diese Werkzeuge bereit stellt: es kommt nicht immer mit mehrspaltiger Darstellung zurecht.

Umgehung 1: du machst das Formular so schmal, das es einspaltig wird.

Umgehung 2: neu laden. Klappt manchmal.

Lösung (hoffentlich): Update auf material-ui v1. Ist in den nächsten Wochen vorgesehen.

Andere Lösung: ich verhindere mehrspaltige Darstellung.

Sagt mir bitte, falls letzteres dringend wäre.

**Comment by rebeccakurz** [comment]
Okay, vielen Dank!
Glaube nicht, dass es nötig ist die mehrspaltige Darstellung zu verhindern.

**Comment by barbalex** [comment]
material-ui wurde soeben aktualisiert
