### ISSUE TITLE
Anmeldung nicht möglich!!

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#147]
Karin Marti, Regula Langenauer und Anna Wunderli haben alle das Problem, dass sie sich nicht mehr anmelden können in der Flora DB. Alle haben das Passwort "hieracium". Sie haben es auf unterschiedlichen Browsern versucht (Chrome, Safari) im Büro und zu Hause.
Bei mir funktioniert das Anmelden, aber ich habe ein anderes Passwort (dianthus). 
Könntest du bitte schauen, was da falsch läuft?

**Comment by barbalex** [comment]
scheint gelöst
