### ISSUE TITLE
Admin Tool funktioniert nicht

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#149]
Leider funktioniert das Admin Tool nicht und wir müssten unsere Praktikantin Aline Meyer als neue Bearbeiterin hinzufügen können, damit sie Einträge machen kann.
![bildschirmfoto 2018-06-07 um 08 14 24](https://user-images.githubusercontent.com/30288503/41081686-19d43ebc-6a2c-11e8-8804-35794cef28bc.png)

**Comment by barbalex** [comment]
ist nun direkt in apflora.ch möglich
