### ISSUE TITLE
Verortung von Teilpopulationen nicht möglich

### ISSUE THREAD

**Issue by jmenzi** [barbalex/apf2#150]
Wenn ich eine Teilpopulation verorten möchte, zoomt die Karte immer direkt auf den ganzen Kanton. Danach kann ich nicht mehr auf meinen Detailausschnitt zoomen, ohne dass die Population im Nirgendwo verortet wird.

**Comment by barbalex** [comment]
Das mit dem Zoomen ist wohl nicht so toll. Mal schauen, was ich machen kann. Aber was heisst:

> Danach kann ich nicht mehr auf meinen Detailausschnitt zoomen, ohne dass die Population im Nirgendwo verortet wird.

Wenn ich nämlich an einen Ort reinzoome und dort zum Verorten klicke, zoomt die Karte zwar lästigerweise wieder raus, aber verortet hat es richtig.

**Comment by barbalex** [comment]
Von Jasmin:

Sorry, dass meine Antwort solange auf sich warten liess. Wenn ich bei der Teilpopulation bin (hereingezoomt) und diese nur wenig verorten möchte, dann klicke ich auf die Teilpopulation und auf „verorte auf Karte“, dann springt die Ansicht auf den ganzen Kanton. Nun kann ich aber nicht mehr detailliert verorten. Dann versuche ich die Karte zu verschieben und beim Klick auf die Karte (mit der Absicht zu verschieben und anschliessend hineinzukommen) wird bereits verortet.

**Comment by barbalex** [comment]
Ja, das ist unangenehm und ich sollte das Springen verhindern.

Aber solange das noch nicht passiert ist, kannst du statt mit Klicken durch Drehen des Mausrads, während der Mauszeiger am ungefähr richtigen Ort liegt, gezielt wieder in die Karte hineinzoomen, ohne dass du klicken (und damit verorten) musst.

**Comment by jmenzi** [comment]
Danke Danke! Das war mir nicht bewusst, ist ja super praktisch!

**Comment by rebeccakurz** [comment]
Das mit dem Verorten einer Teilpopulation funktioniert noch immer nicht. Auch bei mir springt die Karte auf den ganzen Kanton, wenn ich bei einer Teilpopulation auf "verorte auf Karte" klicke. Da ich aber eine Population in Deutschland verorten möchte, kann ich nicht das Klicken vermeiden und nur mit der Maus zoomen, da der Kartenausschnitt, der angezeigt wird, nur den Kanton Zürich beinhaltet. Um auf den richtigen Kartenausschnitt zu kommen, müsste ich Klicken und an der Karte ziehen-> sobald ich klicke wird die Population verortet-> ich kann die Population nicht verorten!

**Comment by rebeccakurz** [comment]
Lieber Alex
Ich wollte soeben eine neue Teilpopulation auf der Karte verorten. Da die Karte ja immer noch auf den gesamten Kanton zoomt sobald man "verorten auf Karte" anklickt, habe ich es mit dem Reinzoomen versucht, wie du es oben beschrieben hast. Das Zoomen hat auch geklappt, ich bin am richtigen Ort gelandet, aber als ich dann die Population verorten wollte und dazu auf den entsprechenden Standort geklickt habe, hat es die Population an einem völlig anderen Ort verortet! (Die Karte ist wieder auf den gesamten Kanton gesprungen und da die TPop, die ich verorten wollte, noch immer aktiv war, habe ich gleich gesehen, dass sie nicht am richtigen Ort ist.)
Ich habe es mehrmals probiert und es hat nie geklappt.

**Comment by jmenzi** [comment]
Habe das selbe Problem bereits mehrmals festgestellt.

**Comment by barbalex** [comment]
@rebeccakurz @jmenzi 

> aber als ich dann die Population verorten wollte und dazu auf den entsprechenden Standort geklickt habe, hat es die Population an einem völlig anderen Ort verortet!

bitte macht daraus einen neuen issue (ist ein anderes Problem und ziemlich schlimm)

**Comment by barbalex** [comment]
Das ursprüngliche Issue (Zoomen wenn lokalisiert wird) ist in der Entwicklungsversion gelöst
