### ISSUE TITLE
AP Flora Datenbank allgemein extrem langsam

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#151]
Seit dem letzten Update hat die Datenbank sehr lange, bis sie die Daten geladen hat. Jedes Mal wenn man auf etwas neues klickt muss man zuerst warten.

**Comment by barbalex** [comment]
Ich selber hätte das Tempo nicht als _extrem_ langsam bezeichnet. Aber definitiv spürbar langsamer als vor der Einführung von GraphQL.

Es gibt zwei Faktoren, die hoffentlich dazu führen, dass dies mit der Zeit bessert:

- GraphQL und die darauf beruhenden Werkzeuge: Sind immer noch sehr neu und werden laufend verbessert. Bei solchen Werkzeugen ist der Fokus zuerst immer auf Features und korrektes Funktionieren. Erst danach wird das Tempo optimiert. Da können wir also auf Verbesserungen hoffen.
- Die Art, wie ich GraphQL in apflora.ch umgesetzt habe: Bestimmt lässt sich hier noch das eine oder andere verbessern. Ähnlich, wie oben für die verwendeten Werkzeuge beschrieben. Ev. könnte das entscheidend sein. Werde ein Auge darauf behalten und versuchen, das künftig zu optimieren.

Übrigens: Vor und nach der Einführung der zuvor verwendeten Technologie hatten wir ähnliche Probleme. Auch direkt nach deren Einführung. Sie liessen sich dann mit Optimierungen apflora-seitig so stark verbessern, dass wir den aktuellen Rückschritt deutlich spüren. Obwohl das Tempo gegenüber der Situation zuvor eher gestiegen ist. Nicht zu vergessen ist, dass die Anforderungen an verfügbare Daten-Mengen in apflora stetig steigen.

Ich bin zuversichtlich, dass sich das Tempo mittelfristig deutlich verbessern lässt.

**Comment by jmenzi** [comment]
Aufgrund der Langsamkeit der Datenbank kam es heute zu folgender Situation: Wir haben eine EKF-Kontrolle gelöscht. Dies wurde aber nicht direkt sichtbar, es schien also, dass die Kontrolllöschung nicht funktioniert hat. In dieser Situation ist man verlockt die Löschung nochmals zu machen. Könnte es sein, dass man so eine weitere Kontrolle löscht? Ich habe Angst, dass man dadurch mehrere Kontrollen aus versehen löschen kann. Beim Neuladen der FloraDB war die Kontrolle aber gelöscht. I

**Comment by barbalex** [comment]
Weil ich heute Exporte verändert habe (https://github.com/barbalex/apf2/issues/172), habe ich Teile der Anwendung mehrere Male neu gestartet, was jeweils zu ein paar Dutzend Sekunden Ausfall führt. Diese spezifische Situation ist vermutlich darum entstanden.

Denn die "normale" Langsamkeit entsteht dadurch, dass beim Aufbau des Strukturbaums sehr viele Daten vom Server an die Anwendung übermittelt und dann von der Anwendung verarbeitet werden müssen. Das passiert nicht, wenn man einen einzelnen Datensatz löscht.

Wenn ihr einen Datensatz löscht, wird der Datenbank der Auftrag übermittelt, den Datensatz mit einer bestimmten ID zu löschen. Es wäre völlig egal, wenn dieser Auftrag mehrmals an die Datenbank übermittelt würde.

**Comment by ksartori** [comment]
Die Performance lässt allgemein zu wünschen übrig. Ich arbeite mittlerweile in zwei Fenstern an zwei verschiedenen Arten zur gleichen Zeit.. 
Ich gebe Feldkontrollen ein: oft muss ich zweimal Kontrollen/Zählungen rechtsklicken, bis überhaupt etwas passiert (danach muss ich wieder eine löschen, weil dann gleich zwei aufpoppen).

**Comment by barbalex** [comment]
Ich will mal nicht sagen, das Problem sei behoben. Das müsst ihr entscheiden. Aber soeben habe ich eine Version live geschaltet, bei der das Daten-Holen ganz anders gelöst ist. Und ich glaube, es hat genützt.

Ich schliesse mal den Issue aber bin froh, wenn ihr eure Meinung meldet.

Übrigens: Das war eine Riesen-Anpassung (3 Tage Arbeit), die überall Code-Änderungen verursachte. Weil wir keine Tests haben, ist es durchaus möglich, dass nun an willkürlichen Stellen neue Fehler passieren :-(

**Comment by barbalex** [comment]
@csalzmann @kmarti
