### ISSUE TITLE
neue Feldkontrolle nicht richtig geordnet (nach Jahr)

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#152]
Eine neue Feldkontrolle ist nach der Erstellung nicht nach dem Jahr geordnet worden. Auch nachdem ich die ganze Seite neu geladen habe.
![bildschirmfoto 2018-07-02 um 13 24 09](https://user-images.githubusercontent.com/30288503/42161718-50f43c2e-7dfc-11e8-98a6-05eba912ebbb.png)

**Comment by rebeccakurz** [comment]
Liparis loeselii, TPop 63.1

**Comment by barbalex** [comment]
Danke für die Meldung und das Beispiel. Habe soeben eine neue Version live gestellt, in der diese behoben sein sollte.
