### ISSUE TITLE
Arten filtern

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#153]
Nicht korrekt angezeigt, beim 2. Mal filtern nach Öffnen der DB wird nicht mehr Auswahl angezeigt, man weiss gar nicht, welche Art nun gefiltert ist (beim 1. Mal war es OK).

![bildschirmfoto 2018-07-19 um 07 33 47](https://user-images.githubusercontent.com/6047564/42923552-4d120cbc-8b26-11e8-90e9-c9fa56fe0286.png)

**Comment by barbalex** [comment]
Sorry: ich verstehe nicht, was falsch läuft. Was wird nicht korrekt angezeigt? Was muss ich machen, um das nach zu vollziehen?

**Comment by csalzmann** [comment]
Es fehlt die Anzeige der Art beim Filtern. Nicht beim 1. Mal filtern. Evtl hat es auch mit der Dauer zu tun, mit der man mit einer Art beschäftigt ist. Als ich es nämlich ausprobieren wollte um Dir nochmals zu zeigen, hat es etwa 5x hintereinander tipptopp funktioniert. Dann hab ich mich wieder in die Sacharbeit vertieft, und beim gewollten Artenwechsel nach 30min ging es dann nicht mehr.  Wenn ich beginne, einen Artnamen einzugeben, z.B. "Pot", dann kommen offenbar 12 Arten in Frage. Die werden aber nicht angezeigt, sondern direkt Populationen. Und die sind von der letzten selektierten Art. Man kann wieder Reload machen, dann gehts wieder. Aber ist halt trotzdem ein Fehler.

![bildschirmfoto 2018-07-26 um 15 48 46](https://user-images.githubusercontent.com/6047564/43266365-8ab33436-90eb-11e8-99a2-45b12da47eab.png)

**Comment by csalzmann** [comment]
Es ist auch verwirrlich, dass wenn ich auf "Art" klicke um zu selektieren die Selektion oben dann auf Projekte schaltet

![bildschirmfoto 2018-07-26 um 15 54 52](https://user-images.githubusercontent.com/6047564/43266665-40c60230-90ec-11e8-96ca-4c82b3ca6f8c.png)

im Moment nützt jetzt nicht mal mehr Reload etwas. Ich denk, ich mach morgen weiter. Aber etwas stimmt hier einfach nicht. Du musst ein paar Mal probieren, ich bin da jetzt schon sehr häufig drüber gestolpert.

**Comment by rebeccakurz** [comment]
Ich habe heute auch Probleme nach den Arten zu filtern. Zuerst funktionierte das Filtern noch, aber es hat mir nicht angezeigt bei welcher Art ich mich befinde (wie bei Charlotte), dann wollte ich die Art wechseln, also auf Art klicken und dann den Artnamen eingeben (auch hier wie bei Charlotte hat es aber auf Projekte geschaltet). Zuerst ging das Filtern nicht, dann habe ich auf den "nur AP" Button geklickt, dann hat es zur richtigen Art gewechselt (aber auch hier ohne anzuzeigen bei welcher Art ich mich befinde). Dann wollte ich wieder zu einer anderen Art, diesmal ging gar nichts mehr. Wenn ich nach "Thalictrum galioides" filtern will, zeigt es mir diese Art gar nicht mehr an, auch nach Aktualisieren nicht.
![bildschirmfoto 2018-08-02 um 15 13 40](https://user-images.githubusercontent.com/30288503/43586284-84a7afdc-9667-11e8-8100-5f0a6f8cfd71.png)

**Comment by alinemeyer** [comment]
Leider wird zusätzlich beim Arten filtern auch keine Auswahlliste angezeigt

**Comment by rebeccakurz** [comment]
Und die Art, nach der man gefiltert hat, wird auch nicht zuoberst angezeigt, sondern zuunterst, also unter der Art, mit der man vorher gearbeitet hat. 
![bildschirmfoto 2018-08-15 um 14 59 56](https://user-images.githubusercontent.com/30288503/44149335-058f2f60-a09c-11e8-9cee-c31677899af6.png)

**Comment by csalzmann** [comment]
Danke Rebecca, jetzt weiss ich wenigstens, wo ich die gefilterte Art finden kann..! Habe vorher immer alles geschlossen und von vorne neu begonnen.

@ Alex: Das wird der Normal-User aber nicht finden. Könntest Du das bitte noch anpassen, Alex? Das ist wirklich ein grosser Stolperstein für alle, die mit der FloraDB arbeiten.

**Comment by ksartori** [comment]
Eventuell geht dies in das gleiche Thema. Auf jeden Fall kann ich oft nicht bis ganz nach unten scrollen. Vergrössere ich das Browser-Fenster wird mehr angezeigt, jedoch ist mein Bildschirm in der Ausdehnung begrenzt..
/Users/karin/Desktop/Scrollbar begrenzt.png

**Comment by ksartori** [comment]
Eventuell geht dies in das gleiche Thema. Auf jeden Fall kann ich oft nicht bis ganz nach unten scrollen. Vergrössere ich das Browser-Fenster wird mehr angezeigt, jedoch ist mein Bildschirm in der Ausdehnung begrenzt..

**Comment by csalzmann** [comment]
Es ist ja auch verwirrend, dass wenn man auf eine Art klickt und "Arten filtern" will, die Filteranzeige dann auf "Projekte filtern" wechselt. Das ist für mich nicht ganz logisch. Man muss also auf "Aktionspläne" im Baum klicken um eine Art zu filtern.

**Comment by barbalex** [comment]
Irgendwie war die Filtering völlig zerstört. Da hat sich wiedermal das Fehlen von Tests schmerzhaft gemeldet :-(

Habe soeben die Reparatur live geschaltet. Falls immer noch Sachen nicht funktionieren: Bitte ein neues Issue öffnen. Dieses hier würde sonst unübersichtlich, da aufgrund des starken Umbaus künftige Fehler nichts mehr mit dem oben diskutierten zu tun hätten.
