### ISSUE TITLE
Beobachter verschwunden

### ISSUE THREAD

**Issue by ksartori** [barbalex/apf2#154]
In Feldkontrollen und EKF ist der Beobachter verschwunden, teilweise auch die Zählungen. siehe Printscreen.
LG; Karin
[Bildschirmfoto 2018-07-23 um 09.50.59.pdf](https://github.com/barbalex/apf2/files/2218391/Bildschirmfoto.2018-07-23.um.09.50.59.pdf)

**Comment by barbalex** [comment]
O.k., endlich habe ich den Grund gefunden: Als ich für die EKF-Zähleinheiten die Rechte gesetzt habe (Freiwillige können sie nicht verändern), habe ich einen Fehler gemacht. Und dabei die Rechte für Adressen entzogen :-(
