### ISSUE TITLE
Neue Kontrolle erfassen

### ISSUE THREAD

**Issue by wunderli** [barbalex/apf2#155]
Lieber Alex

Im Moment können weder Karin Sartori noch ich neue Kontrollen erfassen.
Vermutlich hängt das irgendwie mit dem Umbau zusammen...

Liebe Grüsse

Anna

Anbei die Fehlermeldung:
![bildschirmfoto 2018-07-23 um 09 19 24](https://user-images.githubusercontent.com/26789445/43064642-ce9a636a-8e5f-11e8-938b-70d81b58d60b.png)

**Comment by barbalex** [comment]
Sorry, blöder Fehler von mir. Ist repariert. Danke für die Meldung.
