### ISSUE TITLE
Datum nur mit Kalender möglich

### ISSUE THREAD

**Issue by alinemeyer** [barbalex/apf2#156]
Das Datum der Aufnahme lässt sich momentan nur mit dem grünen Kalenderbutton rechts neben der Zeile eintragen. Man kann es wohl mit Zahlen eingeben, aber es wird nicht gespeichert.

**Comment by barbalex** [comment]
Ich kann das nicht nachvollziehen. Wenn ich ein Datum in das Feld eintrage, passiert das:

- Das Datum wird zum Format DD.MM.YYYY ergänzt. Aus "2" wird z.B. "02.08.2018", aus "2.8.18" auch
- Dieses Datum ist auch nach neu laden vorhanden. Wurde also gespeichert

Wie kannst du das Nicht-Speichern provozieren?

**Comment by csalzmann** [comment]
Bei mir funktioniert das speichern auch ohne Kalender, und die Eingabe ist dauerhaft

**Comment by barbalex** [comment]
@alinemeyer hast du versucht, apflora.ch neu zu laden? Es ist ein bisschen frustrierend, aber leider gibt es in Web-Anwendungen sporadisch komisches Verhalten, das sich aber häufig durch Neu-Laden beheben lässt.

Als Steigerung der Massnahme bzw. wenn Neu-Laden nicht reicht, kann man auch den Browser-Cache leeren. Man kann das allgemein machen oder auch nur für apflora.ch.

Bitte probier das das nächste mal und melde hier wieder, falls es nicht reicht.

Ich schliesse den Issue um auf die wesentlichen und nachvollziehbaren Probleme fokussieren zu können.

**Comment by rebeccakurz** [comment]
Bei mir funktioniert das Eingeben des Datums über die Tastatur im Moment auch nicht! Vor einer halben Stunde hat es aber noch funktioniert. Wenn ich das Datum über die Tastatur eingebe, wird die Linie auf der ich schreibe rot und sobald ich aus dem Feld herausgehe, verschwindet das Datum. Es wird auch kein Jahr angezeigt im Strukturbaum (ich bin am neue Freiwilligen-Erfolgskontrollen eingeben bei Liparis loeselii, z.B. TPop 82.1)
Das Eintragen des Datums über den Kalender funktioniert.

**Comment by rebeccakurz** [comment]
![bildschirmfoto 2018-08-23 um 14 40 10](https://user-images.githubusercontent.com/30288503/44525820-79bc3f80-a6e2-11e8-88e7-be572875081b.png)

**Comment by rebeccakurz** [comment]
auch nachdem ich die Seite neu geladen habe geht es nicht und auch nachdem ich mich ausgeloggt und wieder eingeloggt habe

**Comment by barbalex** [comment]
Ich kann das nicht nachvollziehen.

Erinnert mich irgendwie an das Problem mit den Dropdownlisten, die eine Weile nicht funktionierten, nach dem Server-Neustart wieder und dann später wieder nicht.

**Comment by ksartori** [comment]
Wenn ich das Datum so eingebe "2.8.2018" wird es nicht geschluckt. Ich muss es wie folgt eingeben: "02.08.2018". Dann ist es ok. Oder über Kalender.

**Comment by barbalex** [comment]
Auf der lokalen Entwicklungsversion und in mehreren anderen von mir gebauten Anwendungen funktioniert es so wie oben beschrieben (https://github.com/barbalex/apf2/issues/156#issuecomment-415345852).

Auf der Live-Version hingegen kann ich den oben gemeldeten Fehler von @ksartori nachvollziehen.

Die Anwendung meldet aber keinerlei Fehler.

Muss also irgendwas mit Leistung/Belastung zu tun haben. Und da wir das beide sehen, muss es wohl am Server liegen. Ist aber überhaupt nicht klar, wie das passieren kann. Ausserdem ist der Server nicht sonderlich stark belastet.

Werde den Server diese Nacht neu starten.

**Comment by barbalex** [comment]
Schliesse weil alt, schon lange nicht mehr gemeldet und die Performance-Probleme weitgehend behoben wurden
