### ISSUE TITLE
Bemerkungsfeld erstellen

### ISSUE THREAD

**Issue by alinemeyer** [barbalex/apf2#157]
Wäre es möglich bei den EKFs ein zusätzliches Bemerkungsfeld einzufügen, welches nur für uns topos Mitarbeiterinnen sichtbar wäre?

**Comment by barbalex** [comment]
Wozu genau würde es benutzt? Bzw: wie soll es heissen, damit klar ist, wofür es gedacht ist?

Würde es am besten im roten Bereich (Verifikation) ergänzt?

@csalzmann möchtest du das auch?

**Comment by barbalex** [comment]
@kmarti was meinst du?

**Comment by csalzmann** [comment]
Wir haben das Bemerkungsfeld gerade nochmals diskutiert. Es wäre gut, ein separates Bemerkungsfeld für Einträge von topos/den AV zu haben. Die EKFs dürfen dieses Feld aber sehen. Bemerkungen sollten dann jeweils mit Kürzel von uns und Datum erfolgen. Bemerkungen wären z.B.: "ChS, 23.08.2018: Zählung nicht nachvollziehbar/evtl. falsche TPop gezählt". Oder wenn die Bemerkung für die anstehende Kontrolle sein soll, z.B. "Bitte Abgrenzung zu TPop XY beachten", "letzte Zählung 0, TPop tatsächlich erloschen?" usw.

**Comment by barbalex** [comment]
Ich versuche, was hier und in Mails gesagt wurde, zu einer Lösung zusammenzufassen:

- Das Feld ist für Artverantwortliche und Freiwillige sichtbar
- Es dient zur Kommunikation/Dokumentation _über_ die Kontrolle, nicht um Daten zu erfassen, welche Teil der Kontrolle sind
- Daher soll es wohl _nicht_ im Ausdruck erscheinen

Ich werd das mal so umsetzen

**Comment by barbalex** [comment]
umgesetzt
