### ISSUE TITLE
Was passiert, wenn ich die EKF-Zähleinheiten bei der AP-Art ändere?

### ISSUE THREAD

**Issue by jmenzi** [barbalex/apf2#158]
Lieber Alex, 

Die EKF-Zähleinheiten können ja für jede Art festgelegt werden. 

![zahleinheiten](https://user-images.githubusercontent.com/6448181/44470341-b8da8a00-a629-11e8-83d1-50925736fad4.png)

Sind diese Felder mit den Eingaben (Feldkontrollen, Kontrollen) verknüpft? Was passiert, wenn ich diese Felder verändere? Können dann die Zähleinheiten in den Feld- und Freiwilligenkontrollen geändert werden? Das wäre rückwirkend sehr ungünstig, da es Fehler produzieren würde. Es kommt doch immer wieder mal vor, dass die Zähleinheiten geändert werden müssen. 

Besten Dank für eine kurze Aufklärung.

**Comment by barbalex** [comment]
Gute Frage.

Wenn du sie änderst, können künftig nur noch die geänderten erfasst werden.

Bestehende betrifft das nicht.

Du kannst also ohne Angst ändern.
