### ISSUE TITLE
EKF-Formulare: Zählungen geschätzt und gezählt müssen beide gleichzeitig möglich sein

### ISSUE THREAD

**Issue by jmenzi** [barbalex/apf2#159]
Bei den EKF-Zähleinheiten müssen die beiden Felder "geschätzt" und "gezählt" gleichzeitig ausgefüllt werden können. Es kommt manchmal vor, dass man einen Teil der Pflanzen zählt, danach aber nur noch schätzt.

**Comment by barbalex** [comment]
Das ist nicht möglich: Wenn du bei der Feldkontrolle schaust, siehst du, dass gezählt und geschätzt zwei unterschiedliche mögliche Einträge im selben Feld (Methode) sind.

Technisch gesehen könnte man nur zwei Zählungen erfassen: die eine gezählt, die andere geschätzt.

Macht es aus fachlicher Sicht Sinn, wenn man das Zählen abbricht und danach schätzt, die gezählte Zahl zu erfassen?

@csalzmann was meinst du?

**Comment by kmarti** [comment]
Es macht tatsächlich keinen Sinn eine Zahl aus der Zählung festzuhalten und anschliessend eine neue Zahl aus der Schätzung. Dann reicht die Summe mit der Angabe, dass es eine Schätzung ist.

**Comment by barbalex** [comment]
Ich schliesse. Soll niemanden davon abhalten, doch noch Argumente zu bringen.

**Comment by csalzmann** [comment]
OK. Der Grund für unser Wunsch war eben, dass man früher in der DB die Wahl hatte bei der Eingabe der Anzahl zwischen gezählt, geschätzt und gezählt/geschätzt. Es wurde von den Kontrolleuren auch tatsächlich so gehandhabt, dass manchmal ein Teil der Pflanzen ausgezählt wurde und dann, wenn es viele waren, eine Gesamtschätzung gemacht wurde.
Ohne diese Historie und mit dem jetzigen Protokollblatt bin ich nun aber auch einverstanden, dass man entweder alles auszählt oder dann alles unter "geschätzt" eingibt.
