### ISSUE TITLE
Bei Erstellung neuer Freiwilligen-Kontrolle ist die Kontrolle 2017 verschwunden

### ISSUE THREAD

**Issue by jmenzi** [barbalex/apf2#160]
Lieber Alex

Charlotte und ich haben am gleichen Compi gesessen, da ist Folgendes passiert: Bei der Erstellung einer neuen Freiwilligen-Kontrolle in der Population "Filipendula vulgaris - 117.1 Volketswil, Grossenacher Nord" ist die Kontrolle 2017 verschwunden, als wir eine neue Freiwilligen-kontrolle erstellt haben. Die Kontrolle ist seither nicht mehr aufgetaucht. Könntest du die Kontrolle wieder herstellen und klären, warum dieser Fehler aufgetreten ist. Herzlichen Dank.

**Comment by csalzmann** [comment]
Eigentlich ist uns das ja nur passiert, weil wir bei Abies alba nicht testen können (EKF ergibt bei uns allen Fehlermeldung). Da sind wir faulerweise kurz bei dieser bestehenden TPop mit einer bestehenden EKF gelandet (sorry Karin!!!).
Das wäre aber eigentlich eine zweite Meldung für den Fehler bei Abies alba. Aber vielleicht ists ja auch gut, haben wir diesen Fehler jetzt schon gefunden..

**Comment by barbalex** [comment]
Aha, das erklärt, warum ich selber immer nur Fehler erhalten habe, ihr aber trotzdem arbeiten konntet. Muss also an der Art liegen. Ich werde mich ab morgen wieder apflora widmen können.

**Comment by barbalex** [comment]
Ich bin nicht ganz sicher, ob ich euch richtig verstehe: Meldet ihr

- dass es in apflora.ch einen Fehler gibt, bei dem Kontrollen verschwinden, wenn man neue anlegt, oder
- dass ich bitte Daten retten soll, weil euch ein Fehler passiert ist?

Beim Löschen kann man relativ einfach verrutschen und beim falschen klicken.
Wenn ihr das sofort merkt, könnt ihr es allerdings im "Mehr"-Menu wieder herstellen.

**Comment by csalzmann** [comment]
Zur Info: Habe die verschwundene EKF Kontrolle manuell wieder ergänzt.

**Comment by barbalex** [comment]
Ich kann das weder nachvollziehen noch erklären, da Löschen und neue Schaffen völlig andere Vorgänge sind. Vermutlich bin ich auf weitere Meldungen von euch angewiesen, oder darauf, dass mir - mit dieser Info im Hinterkopf - irgendwann etwas am Code auffällt.

Einzige Möglichkeit wäre, dass ein Klick passierte, als gerade ein anderes Menü aufflackerte. Und daher eine Löschung statt einer Neu-Schaffung ausgelöst wurde. Das hatten wir schon mal, allerdings mit völlig anderen Werkzeugen.

**Comment by barbalex** [comment]
Schliesse, weil schon lange nicht bestätigt
