### ISSUE TITLE
EKF-Formulare: Löschbutton bei Zähleinheiten

### ISSUE THREAD

**Issue by jmenzi** [barbalex/apf2#161]
![loschbutton](https://user-images.githubusercontent.com/6448181/44471071-7023d080-a62b-11e8-99d3-0e50ee5183e6.png)

Wozu ist dieser Button bei Zähleinheit 2 gedacht? Er ist etwas verwirrend, da nur bei einer Zähleinheit steht und die Resultate ja auch manuell gelöscht werden können.

**Comment by barbalex** [comment]
Tja, ist wirklich kompliziert. Das geht so:

EKF machen ohne Zählung keinen Sinn. Darum kann die erste Zählung nicht gelöscht werden. Aber geändert.

Zählungen 2 und 3 können gelöscht werden. Falls jemand fälschlicherweise eine neue Zählung erfasst.

Nur die Werte leeren macht keinen Sinn, weil dann ein leerer Datensatz zurück bleibt.
