### ISSUE TITLE
EKF-Beobachter: Fehlermeldung

### ISSUE THREAD

**Issue by jmenzi** [barbalex/apf2#162]
![verknufpungsfehler](https://user-images.githubusercontent.com/6448181/44471286-dd376600-a62b-11e8-823b-8d5f8dcda345.png)

Bei mir wird weiterhin bei allen EKF-Bearbeitern die obige Fehlermeldung angezeigt, obwohl Tom Häussermann von Rebecca verknüpft wurde. Bei Rebecca tritt diese Meldung nicht auf.

**Comment by barbalex** [comment]
Bei mir tritt diese Meldung auch nicht auf. Hast du apflora.ch seither neu geladen?

**Comment by ksartori** [comment]
Diese Fehlermeldung erscheint bei mir auch bei Tom Häussermann.

**Comment by csalzmann** [comment]
Diese Fehlermeldung ist bei mir gestern auch erschienen, heute aber alles iO.

**Comment by barbalex** [comment]
Ist mir momentan unklar und nicht nachvollziehbar. Bitte weiterhin melden, ob es klappt oder nicht

**Comment by rebeccakurz** [comment]
Bei mir erscheint diese Meldung bei den Kontrolleuren, die ich verknüpft habe, nicht. Müsste vielleicht noch jemand anders ausprobieren, der die Verknüpfung nicht gemacht hat.

**Comment by barbalex** [comment]
@rebeccakurz Du hast recht. Sie erscheint erst, wenn man die Anwendung neu lädt oder den Datensatz wechselt und wieder zurück. Muss ich anschauen

**Comment by barbalex** [comment]
@rebeccakurz Ist in der Entwicklungsversion korrigiert. Wenn ich es nicht vergesse, stelle ich es heute Abend live

**Comment by barbalex** [comment]
Ich schliesse diesen Issue, weil die Implementation geändert wurde. Wenn ähnliche Probleme wieder erscheinen sollten: Bitte neuen Issue öffnen und ev. auf diesen hier verweisen (Link einfügen).
