### ISSUE TITLE
EKF-Formulare: Feld "Im Jahresbericht nicht berücksichtigen"

### ISSUE THREAD

**Issue by jmenzi** [barbalex/apf2#163]
Das Feld: "Im Jahresbericht nicht berücksichtigen“ wird beim meinem Accout und „sehen als:Tom Häussermann“ angezeigt, wenn ich mich aber als Tom Häussermann einlogge, ist es zum Glück nicht sichtbar. Sollte dieses Feld bei der „sehen als“- Funktion nicht auch weg sein?

**Comment by barbalex** [comment]
@csalzmann was meinst du?

**Comment by kmarti** [comment]
Wenn der Freiwillige das nicht sehen kann, ist es sicher besser.

**Comment by barbalex** [comment]
"sehen als" steht nur Artverantwortlichen und Managern zur Verfügung. 

Das Feld muss ev. doch versteckt werden: Wenn ihr aus dieser Ansicht heraus drucken wollt. Wovon ich ausgehe.

**Comment by kmarti** [comment]
ja, genau

**Comment by barbalex** [comment]
O.k., in der Entwicklungs-Version angepasst.

Ausserdem: Knopf `GUID kopieren` ist auch nur noch für Artverantwortliche in der Normal-Ansicht sichtbar.
