### ISSUE TITLE
"EKF sehen als" - Auswahlliste funktioniert nicht

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#164]
Im Moment funktioniert die Auswahlliste unter "mehr" und dann "EKF sehen als" nicht. Ich kann dann für die Auswahlliste den Leerschlag tippen und dann auch den gewünschten Namen schreiben, aber es erscheint keine reduzierte Auswahl. Die gesamte Auswahlliste wird angezeigt und ich kann auch hinunterscrollen bis zu dem gewünschten Namen, aber ich kann nicht danach suchen.

**Comment by barbalex** [comment]
Habt ihr die Anwendung neu geladen?

Falls das nicht reicht, den Cache geleert?

**Comment by barbalex** [comment]
O.k., kann ich leider nachvollziehen. Ich habe seit Wochen nichts an der produktiven Version von apflora.ch geändert. Trotzdem diese Verhaltens-Änderung. Das ist theoretisch unmöglich. Praktisch offenbar doch.

:-(

Suche eine Lösung.

**Comment by barbalex** [comment]
O.k., scheint dass der Server - obwohl er nicht überlastet war und keine fremde Software (=Malware) darauf läuft - schuld war. Der Neustart hat das Problem behoben.

**Comment by rebeccakurz** [comment]
Die Auswahllisten funktionieren aber leider immer noch nicht, weder bei "EKF sehen als" noch bei der Feldkontrolle oder der Eingabe der EKF im Feld "Bearbeiter".

**Comment by barbalex** [comment]
Uff. Es könnte länger dauern, bis ich dafür eine Lösung habe. Sorry :-(
Arbeite daran.

**Comment by barbalex** [comment]
Hm. Habe glaube ich eine Lösung. Ist erst umgesetzt im Formular AP. Ersetze alle Auswahl-Listen mit diesem neuen Werkzeug.

**Comment by barbalex** [comment]
Habe mittlerweile die meisten Auswahllisten ersetzt. Letzte  Ausnahme: Art-Wahl in Exporten, eierlegende Wollmilchsau

**Comment by barbalex** [comment]
Alle Auswahllisten sind ersetzt. Bin gespannt, was ihr dazu mein. Ich finde sie viel besser als bisher.
