### ISSUE TITLE
Koordinaten, Ausschnitt

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#166]
Alex, könntest Du uns einen grafischen Ausschnitt geben, wo wir sehen, bis wohin die Schweizer Koordinaten gelten?

**Comment by barbalex** [comment]
Ich habe schon mehrmals gesucht und bin nicht fündig geworden. Swisstopo interessiert das scheinbar nicht, weil es nur um die Schweiz geht.

Am ehesten kannst du wohl in dieser Publikation hier Hinweise finden: file:///C:/Users/alexa/Downloads/factsheetsiblocktransformation.pdf, z.B. bei Abbild 3

**Comment by csalzmann** [comment]
Ich kann leider nicht auf das File zugreifen..

**Comment by barbalex** [comment]
Zum Glück! Hier die richtige Version: https://www.swisstopo.admin.ch/content/swisstopo-internet/de/home/products/images/ortho/swissimage/_jcr_content/contentPar/tabs/items/dokumente/tabPar/downloadlist/downloadItems/591_1464190676645.download/factsheetsiblocktransformation.pdf
