### ISSUE TITLE
Qualitätskontrolle/Koordinaten ausserhalb Bezugssystem

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#167]
Wir möchten Pops in der DB behalten, auch wenn sie sich ausserhalb des Bezugssystems befinden - auch wenn wir bei diesen TPops keine Koordinaten mehr eingeben können. Damit es nicht immer einen Fehler gibt, wäre es wünschenswert, man könnte bei der Qualitätskontrolle angeben, dass Fehler erkannt wurde aber nicht lösbar ist.
Siehst Du eine Möglichkeit, so etwas einzurichten? Käme evtl auch noch bei anderen Fehlermeldungen zum Einsatz.

**Comment by barbalex** [comment]
Das ist nicht einfach. Man kann nicht einfach auf irgendeiner Struktur-Ebene sagen, dass Fehler ignoriert werden sollen. Die verwendeten Abfragen sind komplex und "virtuell", d.h. die Ergebnis-Zeilen verschwinden danach wieder. Es gibt keine ID, welche eine Zeile identifizieren kann. Man kann sich daher keine Zeile für künftiges Ignorieren merken.

Selbst wenn mir irgendwann eine mögliche Lösung einfallen sollte: Sie wird bestimmt nicht mit wenig Aufwand umzusetzen sein.

Auch wenn Qualitätskontrollen viele Vorteile bringen: Sie können nicht alles lösen. Vor allem sollten sie grundsätzlich nur Ergebnisse liefern, die in 99% der Fälle eine Korrektur auslösen.

Daher sollten wir keine QK bauen, die das nicht erfüllen. Oder wenn: Sie separat anbieten. Bzw. eine Option bieten, zu wählen, welche QK ausgeführt werden. Was auch aufwändig ist, aber gut lösbar.

Im vorliegenden Fall wäre die offensichtliche Lösung: Als Koordinatensystem WGS84 verwenden (geodätisch, Welt-umspannend). Und bei Exporten wo möglich, da innerhalb des LV95-Rahmens LV95 Koordinaten mit exportieren.

Die Qualitätskontrollen würden WGS84 testen und daher nicht reklamieren.

Ist einfach unglücklich, dass Swisstopo beim Bezugsrahmen-Wechsel weniger grosszügige Grenz-Überschreitungen zulässt.

**Comment by csalzmann** [comment]
WGS84 geht nicht, weil wir dieses Koordinatensystem in unserem Arbeitsalltag sonst nie brauchen. Das Umrechnen wäre ein viel zu grosser Aufwand.
Hoffen wir, es bleibt bei so wenigen Pops ausserhalb des Bezugsrahmens!
Andere Frage, an alle: wie wichtig ist die Qualitätskontrolle, dass Koordinaten innerhalb des Bezugsrahmen liegen?

**Comment by barbalex** [comment]
Das Umrechnen könnte apflora machen, z.B. so:

- Im Formular wird ein Feld `Koordinaten WGS84` dargestellt. Darin ist der im Datensatz gespeicherte Wert enthalten. Der Wert kann direkt verändert werden, was sozusagen nie passieren wird (höchstens bei TPop in D, bei denen von Hand erfasst wird).
- Darunter wird `Koordinaten LV95` dargestellt (Text, kein Feld, um deutlich zu machen, das dies nur ein aus WGS84 berechneter Wert ist). Klickt man auf den Text, wird daraus ein Feld, worin man manuell LV95 erfassen kann. Daraus rechnet apflora den neuen WGS84-Wert und speichert diesen
- Verortet man auf der Karte, wird WGS84 gespeichert. Und im Formular sofort auch LV95 dargestellt

**Comment by csalzmann** [comment]
Aha. Es ist für uns eben wichtig, dass wir LV95 eingeben können. Das können wir ja offenbar. Also ich fände das schon eine interessante Option, va wenn der Bezugsrahmen so scharf um die Schweiz herum geht. Ich denke, es hat nicht 1. Prio, aber wenn das Budget reicht fände ich es gut.
In der Karte müsste aber auch weiterhin LV95 dargestellt werden.

**Comment by barbalex** [comment]
> In der Karte müsste aber auch weiterhin LV95 dargestellt werden

Das geht natürlich nur, soweit der LV95-Bezugsrahmen reicht. Ausserhalb würde WGS84 angezeigt.

**Comment by csalzmann** [comment]
Bitte für 2019 vormerken.

**Comment by barbalex** [comment]
Ist umgesetzt
