### ISSUE TITLE
Diskussion Status für AP-Bericht relevant, wenn unsicher

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#168]
Es gibt doch bei einigen Arten den Fall, wo gewisse TPop unsicher sind. Unsicher in dem Sinne, dass man zB nicht sicher weiss, ob es sich um die richtige Art handelt (z.B. Gladiolus palustris/communis) oder ob es sich um Gartenformen statt Wildformen handelt (Rosa gallica, Pulsatilla vulgaris). Diese TPops möchten wir eigentlich nicht unbedingt im AP als aktuelle ursprüngliche Populationen handeln. Die Stati historisch/ausserkantonal/kein Vorkommen passen aber nicht zu den Fällen. Eine Möglichkeit wäre allenfalls noch: TPop-Status potenzieller Wuchsort, für AP-Bericht relevant. Ich könnte mir aber vorstellen, dass die Qualitätskontrolle bei positiven EKs eine Fehlermeldung ergibt, wenn TPop-Status nicht aktuell ist.
Hättest Du dafür eine Lösung, Alex? Sprengt es die Struktur der Datenbank, wenn wir bei "für AP-Bericht relevant" eine neue Kategorie einführen?

**Comment by barbalex** [comment]
> Sprengt es die Struktur der Datenbank, wenn wir bei "für AP-Bericht relevant" eine neue Kategorie einführen?

Nein. Das ist möglich. Aber verhältnismässig aufwändig, weil dieses Feld neben dem Grund, der in diesem Fall anders wäre, auch den Faktor "nicht AP-Relevant" enthält und daher an vielen Orten in wichtiger Funktion verwendet wird.

Schläuer wäre daher ev. diese Änderung zu nutzen, um "Für AP-Bericht relevant" auf ein reines ja/nein-Feld zu reduzieren. Und daneben ein Begründungs-Feld (Text oder Listen-Auswahl).

Frage: Was ist die Beziehung zwischen `Status unklar` und `Für AP-Bericht relevant`?

Und: Wäre es nicht einfacher, einfach diesen neuen Eintrag zu ergänzen:

- Nein (Status ist unklar)

...und dann im Begründungs-Feld für den unklaren Status zu schreiben, dass z.B. die Art unsicher ist?

**Comment by csalzmann** [comment]
Status unklar: bezieht sich auf aktuell/nicht aktuell oder ursprünglich/angesiedelt (Begründung muss man angeben). In jedem Fall sollte aber die TPop im Bericht erscheinen.
In den oben geschilderten Beispielen steht der AP aber unter Umständen zu gut da, wenn die TPops miteinbezogen werden.

Ich fände ein ja/nein-Feld für AP-Bericht relevant gut mit anschliessender Listen-Auswahl. Da müsste dann noch eine 4. Begründung hinzukommen "Nein (anderer Grund)", mit Begründung, die man in ein Textfeld schreiben sollte.

**Comment by barbalex** [comment]
Alles klar.

Das sind ein paar Stunden Arbeit, die ich nächstes Jahr offeriere oder im diesjährigen Auftrag woanders kürzen müsste.

**Comment by barbalex** [comment]
Ist in der Entwicklungsversion umgesetzt. Werde ich nachts live schalten (bedingt Anpassungen an der Datenstruktur)
