### ISSUE TITLE
Ansicht TPop in Karte, Absturz beim 1. Mal nach Öffnen der DB

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#169]
Ist mir gestern und nun heute auch wieder aufgefallen: Wenn man zum 1. Mal nach Öffnen der DB eine TPop auf der Karte anschauen will (auf aktive TPop zoomen), stürzt es ab und man muss neu laden. Danach geht es aber immer. Schliesse ich die DB und zoome wieder auf eine TPop, wieder der gleiche Absturz. Konnte den Fehler also reproduzieren.

![bildschirmfoto 2018-08-24 um 09 13 24](https://user-images.githubusercontent.com/6047564/44570473-4a5b1080-a77e-11e8-86f1-4bd8ed70954a.png)

**Comment by barbalex** [comment]
Kann ich leider nicht nachvollziehen. Bei mir klappts.

**Comment by wunderli** [comment]
Lieber Alex

Bei mir dasselbe Problem.
Auch beim Zoomen auf die Beobachtung gibts einen Absturz mit dieser Fehlermeldung.
Nur bim Klick auf die gelben "angewählten" Tpops oder Beobachtungen.
Ist ziemlich ärgerlich, weil man dann Einstellungen und Ausschnitt auf der Karte verliert und alles neu einrichten muss!

Habe jetzt noch ein wenig gepröbelt.
z.B. gehts mit Pop/Tpop rel. gut, dort könnte der Fehler sein, dass gar keine Tpop markiert ist und das Programm daher nicht weiss wohin hüpfen?

Bei den Beobachtungen gibts ja 3 Kategorien.
Da habe ich jetzt auch gemerkt, dass es halt nur funktioniert, wenn eine Beobachtung der entsprechenden Kategorie markiert ist.
D.h. man müsste noch viel mehr aufpassen, wo man drauf klickt und kontrollieren, ob diese Tpop/Beobachtung wirklich markiert ist.

Eleganter wäre natürlich, wenn es einfach eine Medlung gäbe, dass es keine derartigen Daten gibt, zum Zoomen und nicht gleich ein Absturz produziert wird.

Ich teste nochmals, ob so beim Beobachtungen zuordnen alles funktioniert.

Liebe Grüsse

Anna


![bildschirmfoto 2018-08-31 um 09 41 01](https://user-images.githubusercontent.com/26789445/44899667-a7b50b80-ad02-11e8-87eb-dc3b5989fd6f.png)

**Comment by csalzmann** [comment]
Bei mir liegts nicht dran, dass ich TPop nicht markiert hätte. Bei mir stürzt jetzt grad Kartentool permanent ab, wenn ich auf eine markierte TPop zoomen will. Auch neu laden (nicht nur in der Karte, sondern oben links im Browser (Chrome) nützt nichts.

![bildschirmfoto 2018-08-31 um 15 03 03](https://user-images.githubusercontent.com/6047564/44913972-0ee8b500-ad2f-11e8-8e54-71eb1cb11f60.png)

**Comment by csalzmann** [comment]
Auch Neustart und Browserdaten löschen nützt nichts mehr, kann nicht auf Pop/TPop zoomen

**Comment by barbalex** [comment]
Damit ich das hoffentlich nachvollziehen kann:

- welche Art ist aktiv, wenn es bei euch abstürzt?
- passiert das immer, das heisst bei allen Arten und allen TPops?

**Comment by ksartori** [comment]
Habe dieses Problem auch oft. Bei allen meinen drei Arten: Rosa gallica, Trifolium ochroleucon, Filipendula vulgaris. Es ist gerade nicht erquickend.

**Comment by csalzmann** [comment]
Das passiert wirklich immer wieder. Manchmal ist es so, dass man keine TPop im Baum ausgewählt hat, dann gibt es Absturz beim Zoomen auf TPop. Aber oft hat man eine TPop ausgewählt, zoomt darauf (so eine praktische Funktion!), und es stürzt trotzdem ab.

**Comment by csalzmann** [comment]
Hmm, oder eben doch nicht, und ich war auf der Zusammenfassung der TPops und nicht in einer TPop. Könnte man denn nicht Absturz mit einer Meldung verhindern, dass man zuerst etwas anwählen soll, um darauf zoomen zu können?

**Comment by barbalex** [comment]
Ihr habt recht gehabt: Ich hatte bisher den Fall nicht abgefangen, wenn es gar keine Objekte gab, auf die man zoomen konnte.

Ist in der Entwicklungsversion behoben.
