### ISSUE TITLE
Wollmilchsau: letzte EK, wenn mehrere pro Jahr dann diejenige mit der höchsten Anzahl

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#171]
Bei Orchideen, manchmal auch bei anderen Arten, gibt es mehrere Kontrollen pro Jahr. Z.B werden zuerst die Rosetten gezählt, dann die blühenden Pflanzen. Abhängig vom Zeitpunkt ändert sich die Anzahl beobachteter Pflanzen. Es kann auch passieren, dass die letzte EK einen Nuller ergibt (z.B. gibt es keine blühenden Pflanzen und auch die Rosetten sind schon eingezogen), zuvor wurden aber Pflanzen (Rosetten) gesichtet.
Nun wäre es für die Zielerreichung wichtig, dass man jeweils die höchste Anzahl nimmt und nicht einfach die letzte Zählung im Jahr.
Es ist bestimmt mega kompliziert das umzusetzen. Ich möchte es aber trotzdem mal anmelden und fragen, ob es möglich ist?

**Comment by barbalex** [comment]
Ja, das ist nicht ganz trivial.

Wo sollte das passieren? Im Jahresbericht wird nicht gezählt.

**Comment by barbalex** [comment]
Bisher haben wir ausdrücklich die Daten der _letzten_ Kontrolle benutzt. Das soll also ändern?

**Comment by barbalex** [comment]
Es kann mehrere Kontrollen pro Jahr geben.
Eine Kontrolle kann selber mehrere Zählungen haben.
Es kann also mehrere Kontrollen mit jeweils mehreren Zählungen geben.

Bisher wurden alle Zählungen der letzten Kontrolle aufgelistet.
Künftig würden also alle Zählungen derjenigen Kontrolle aufgelistet, bei der die höchste Zahl gezählt wurde.

Könnte das nicht täuschen bzw. verwirren?
Müssten ev. alle Zählungen aller Kontrollen erscheinen?

Zusatzfrage: Ein Kontrolle enthält nicht nur Zählungen. Sondern sehr viel mehr, z.B. Deckungen.
Gabe es mehrere Kontrollen pro Jahr, sollen also die Informationen inkl. Deckungen derjenigen Kontrolle mit der Zählung mit der höchsten Anzahl dargestellt werden?

Könnte das ev. auch etwas willkürlich sein?
Müssten ev. alle Infos aller Kontrollen erscheinen?

Ich habe den Eindruck, dass die eierlegende Wollmilchsau zuviel machen will und darum schwer verständlich wird. Und es besser wäre, für spezifische Fragen, eigene Auswertungen zu schaffen. Ev. eine, welche pro TPop und Jahr die höchste Zählung liefert? Ohne den letzten TPop-Bericht und ohne willkürlich gewählte Infos z.B. zu Deckungen?

**Comment by jmenzi** [comment]
Wir werden das noch intern besprechen und melden uns wieder.

**Comment by rebeccakurz** [comment]
Lieber Alex

Wir haben das nochmals besprochen und uns wie folgt geeinigt:

Wir möchten gerne eine eierlegende Wollmilchsau mit **allen** Zählungen vom **letzten** EK-Jahr und **allen** Zählungen vom **ersten** EK-Jahr. 
Jetzt wird ja "nur" die letzte Zählung im letzten EK-Jahr abgefragt. Der restliche Inhalt der Abfrage sollte gleich bleiben (TPop-Bericht etc.).

Dies wäre eine wichtige Abfrage für den Jahresbericht (->Zielauswertung) und sollte deshalb möglichst rasch umgesetzt werden.
(wenn es überhaupt möglich ist).

LG

**Comment by csalzmann** [comment]
Wie sieht das denn nun aus, schaffst Du das?

**Comment by csalzmann** [comment]
Du hast völlig recht, zwei Sachen vermischt.

Und was die letzte Zählung betrifft: auch da hattest Du recht, es ist unter Umständen nicht immer die beste Wahl, die höchste Anzahl zu nehmen. Für uns am praktischsten wäre es demnach tatsächlich, wenn im letzten EK-Jahr alle Zählungen aufgelistet wären. Kann auch mit Komma getrennt als Textfeld sein.

**Comment by barbalex** [comment]
Die eierlegende Wollmilchsau ist umgesetzt. Sie produziert jetzt sozusagen auch noch Seide ;-)
