### ISSUE TITLE
Exporte: Erfolgskontrollen funktionieren nicht

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#172]
![bildschirmfoto 2018-08-28 um 14 11 55](https://user-images.githubusercontent.com/6047564/44722139-6b986580-aacc-11e8-9523-cc281816dddf.png)

**Comment by barbalex** [comment]
Der Fehler hat sich mit der Ergänzung des neuen Bemerkungsfelds eingeschlichen.
Danke für die Meldung.
Ist behoben.
