### ISSUE TITLE
Beobachtungen zuordnen Sortierung Distanzen Tpops

### ISSUE THREAD

**Issue by wunderli** [barbalex/apf2#174]
Lieber Alex

Beim Dropdown für die Zuordnung von Tpops stimmt teilweise die Reihenfolge nicht mehr.
D.h. es ist nicht nach den Distanzen sortiert und die nahsten Tpops sind nicht zu oberst.
Es kann jedoch mit dem Wissen der Nr. die Tpop. gefiltert werden.

![image](https://user-images.githubusercontent.com/26789445/44914410-75ba9e00-ad30-11e8-8b97-f39373fa92f7.png)

**Comment by barbalex** [comment]
Danke für die Meldung.
Ist in der Entwicklungsversion behoben.
