### ISSUE TITLE
Selektion und zuordnen der Beobachtungen auf der Karte

### ISSUE THREAD

**Issue by wunderli** [barbalex/apf2#176]
Lieber Alex

Leider können die Beobachtungen auf der Karte nicht mehr selektioniert (gelbe Umrandung) werden.
Es kann nur der Infotext angezeigt werden.
Es wäre aber sinnvoll, wenn mit einem Klick auf die Beobachtung die zugehörige Beobachtung im Strukturbaum markiert würde, damit die zugehörigen Infos angefragt werden können.

Ebenfalls ist es nicht mehr möglich, die Beobachtungen mit Drag and Drop auf die zugehörige Tpop zu ziehen. Offenbar war das früher noch möglich.
Wäre für uns super und sehr effizient, wenn wir diese Funktion wieder hätten.

**Comment by csalzmann** [comment]
@ Alex/Anna: Das sind 2 Issues. In der Karte selektieren und auch im Baum selektiert haben konnten wir meines Wissens noch nie. Wäre aber sehr nützlich.

**Comment by barbalex** [comment]
> Leider können die Beobachtungen auf der Karte nicht mehr selektioniert (gelbe Umrandung) werden.
Das war so direkt noch nie möglich.
Es geht aber mit dem Werkzeug "Kartenfilter": Einfach ein Quadrat um die auszuwählenden Pop/TPop ziehen. Wenn du das mit TPop's machst, sieht du einfach nicht alle gewählten, solange der Baum nicht offen ist.

**Comment by barbalex** [comment]
> Es wäre aber sinnvoll, wenn mit einem Klick auf die Beobachtung die zugehörige Beobachtung im Strukturbaum markiert würde, damit die zugehörigen Infos angefragt werden können.

Das kannst du auch mit Klick auf den Link im sich öffnenden Info-Fenster. Allerdings in einem neuen Fenster (diese Einschränkung liesse sich möglicherweise in ein paar Wochen wegen Weiterentwicklung der verwendeten Werkzeuge ändern)

**Comment by barbalex** [comment]
> Ebenfalls ist es nicht mehr möglich, die Beobachtungen mit Drag and Drop auf die zugehörige Tpop zu ziehen. Offenbar war das früher noch möglich.

Das geht, wenn du TPop und Beobachtungen nicht beurteilt anzeigst. Und dann auf das > Symbol neben den Beobachtungen klickst.

**Comment by barbalex** [comment]
Ich schliesse mal, weil ich glaube, es besteht kein Handlungsbedarf und auf die wesentlichen Issues fokussieren will

**Comment by jmenzi** [comment]
Habe das heute alles ausprobiert. Einfach genial, so können wir Beobachtungen viel schneller zuordnen als in der alten Version - man muss einfach wissen wie. :-) Vielen Dank Alex.

**Comment by barbalex** [comment]
:-)

**Comment by rebeccakurz** [comment]
Lieber Alex

Ich wollte vorher eine nicht beurteilte Beobachtung (die ich zuvor einer anderen Art zugeordet habe) mittels Drag & Drop einer Teilpopulation zuordnen. Das hat nicht geklappt. Mit der Zuordnungsliste "einer Teilpopulation zuordnen" hat es dann geklappt.
Dann habe ich nochmals eine Beobachtung zuordnen wollen (wiederum eine, die ich einer anderen Art zugeordnet habe) um das Drag & Drop nochmals zu testen: Diesmal zeigt es mir nicht mal mehr die Beobachtung auf der Karte an (an den richtigen Ort zoomen hat geklappt mit "auf aktive TPop zoomen".
Also habe ich nochmals einen Versuch gestartet, auch diesmal zeigt es die nicht beurteilte Beobachtung nicht auf der Karte. Im Strukturbaum ist sie zwar aktiv, aber ich kann nicht in der Karte "auf aktive TPop zoomen" anklicken. Die Zuordnung über die Liste hat aber problemlos geklappt.
Das Ganze passiert auf MacOS, Chrome. Bin schon den ganzen Tag mal wieder auf der Flora-Website, habe den Cache nach dem Mittag geleert.
Die Beobachtungen habe ich von Gladiolus palustris nach Gladiolus communis verschoben, die zuzuordnende TPop ist 5.1
