### ISSUE TITLE
EKF Zähleinheit wechseln

### ISSUE THREAD

**Issue by alinemeyer** [barbalex/apf2#177]
![bildschirmfoto 2018-08-31 um 16 11 04](https://user-images.githubusercontent.com/42208152/44917630-35135280-ad39-11e8-924f-6bd3e8b64773.png)
![bildschirmfoto 2018-08-31 um 16 11 22](https://user-images.githubusercontent.com/42208152/44917642-39d80680-ad39-11e8-840a-1abaf8881707.png)

Die Zähleinheit im Jahr 2017 war ursprünglich "davon blühende Pflanzen". Die Zähleinheit wurde entsprechend rückwirkend verändert.

**Comment by barbalex** [comment]
Wann hast du die Zähleinheiten beeinflusst? Ich werde aus einer Sicherung möglichst kurz davor nachschauen, welcher Wert zuvor drin war.

**Comment by alinemeyer** [comment]
Ich denke das war ca. um 15 Uhr. Vielen Dank!

**Comment by barbalex** [comment]
O.k., ich habe die Daten vom 30.8.2018 geladen. Damals war die Zähleinheit schon "Fertile Pflanzen":
<img width="784" alt="2018-09-04_12h08_13" src="https://user-images.githubusercontent.com/669783/45025291-5b880500-b03b-11e8-8228-835e4fb76640.png">

**Comment by jmenzi** [comment]
Lieber Alex
Das ist leider nicht so. Zuvor war es blühende Pflanzen (siehe altes Protokollblatt, welches Aline angehängt hat). Das macht mir jetzt aber echt Sorgen... wenn die Zähleinheiten sogar in den alten Daten verändert wurden. Kling jetzt gar nicht gut! Gibt es irgend eine Möglichkeit dies wieder rückgängig zu machen? Bei Fragen kannst du mich sonst auch im Büro erreichen. 

Grüsse, Jasmin

**Comment by barbalex** [comment]
Es gibt 15'687 Zählungen in apflora.

Bei einer davon stimmt die Einheit nicht mit derjenigen im Papier-Formular überein.

Und nun meinst du, es sei etwas systematisch verändert worden und ich könne das ebenso systematisch rückgängig machen?

Aus meiner Erfahrung mit Daten-Erfassung ist es völlig normal, dass bei einem kleinen Prozentsatz der Eingaben Fehler passieren. Schliesslich sind wir (bloss) Menschen. Zwei Prozent Fehler zum Beispiel wären in diesem Fall 300 Zählungen.

Niemand weiss besser, wie of wir Fehler schreiben, als ich als Programmierer: apflora.ch schreit dich kaum je an, wenn du einen Fehler schreibst. Mein Code-Editor hingegen fast immer. Und das ist erschreckend oft :-(

Wir müssen schon etwas mehr Beweise haben, dass etwas systematisch verändert wurde, bevor wir überprüfen und danach ev. davon ausgehen können, dass das wirklich passierte.

Hast du andere Beispiele?

Das bisherige Beispiel wurde übrigens zuletzt am 12.4.2018 verändert.

**Comment by jmenzi** [comment]
Lieber Alex 
Ich habe nun bei der Testart Abies alba das Ganze nochmals angeschaut und es scheint tatsächlich nichts rückwirkend zu verändern. Danach habe ich das Ganze nochmals durchgespielt mit Himantoglossum und auch hier verändert sich nichts mehr. Wenn du also seit dem letzten Mal nichts geändert hast, dann scheint es also wirklich ein Fehler bei der Eingabe zu sein. Du verstehst hoffentlich, dass das schon ein recht gewaltiger Zufall ist, dass wir genau das Beispiel öffnen, bei dem dieser Fehler mit genau dieser Zähleinheit passiert ist. Aber ja, wir hätten auch noch andere Populationen anschauen sollen. Gruss

**Comment by barbalex** [comment]
Shit happens. Wie mir mein Editor täglich Dutzende Male spiegelt. Bleibt also kritisch

**Comment by barbalex** [comment]
Kleine Anekdote dazu: Ich war mal in GR für das Natur- und Landschaftsschutzinventar zuständig.

Man beschreibt in einer Datenbank Tausende Objekte. Beruhend auf Feld-Protokollen von erfahrenen Auftragnehmern. Möglichst zutreffend. Vor allem die Schutzbegründung.

An und für sich ist das eine super Aufgabe, um neue MitarbeiterInnen und PraktikantInnen einzuarbeiten: man lernt sehr gut kennen, wofür man sich einsetzt.

Bloss: Die Beschreibungen müssen differenziert, sorgfältig und sachlich korrekt sein.

Denn: Sie sind Grundlage für aufwändige und manchmal einschneidende rechtliche Massnahmen. Und werden gelegentlich sogar gerichtlich überprüft.

Und hier kommt das Problem: Es ist (bzw. war) sehr schwierig, jemanden zu finden, der solche vermeintliche "Massen-Datenbank-Arbeit" sorgfältig genug durchführt. Es war schlicht ernüchternd zu sehen, wie viele der Beschreibungen nachträglich korrigiert werden mussten (auch nachdem die Mitarbeiter eingehend eingearbeitet waren).

Diese Aufgabe war natürlich anspruchsvoller, als Zählungen zu Erfassen. Ich will keinen Zahlen nennen: aber es mussten wesentlich mehr als 2% der Datensätze korrigiert werden.
