### ISSUE TITLE
Legende in der Karte anzeigen

### ISSUE THREAD

**Issue by wunderli** [barbalex/apf2#178]
Lieber Alex 

Früher konnten wir für die Gemeinde-Info auf die Karte klicken, dann wurde jeweils auf der Seite die Legende dazu angezeigt.
Nun gibt es ja neu auch noch andere Infoklicks (z.B. Beobachtungen mit Details).
Wäre so etwas auch für den Layer "Gemeindegrenzen" wieder möglich?
Oder wie könnten wir effizient herausfinden, in welcher Gemeinde eine Beobachtung/Population liegt?

**Comment by barbalex** [comment]
Früher haben wir direkt einen Dienst der Swisstopo verwendet. Der gab uns massive Probleme, weil die Swisstopo damit die Version des verwendeten Werkzeugs (Open Layers) bestimmte. Und damit konnte sie über Nacht unsere Karten zum Erliegen bringen (ist mehrmals passiert). Ausserdem hinderte uns das daran, neuere/ältere Versionen zu verwenden, um neue Features zu entwickeln oder Fehler einer bestimmten Version zu verhindern.

Es war also essentiell davon weg zu kommen.

Diese Erweiterung kann ich nicht so auf die Schnelle machen.

**Comment by barbalex** [comment]
Ist in v1.36.0 umgesetzt
