### ISSUE TITLE
"Zwittergemeinden"

### ISSUE THREAD

**Issue by wunderli** [barbalex/apf2#179]
Lieber Alex

Wollten heute wieder mal eine "Zwittergemeinde" also mit 2 Gemeinden eingeben.
Leider wurde der Eintrag direkt wieder gelöscht.
Auch wenn die Gemeinde komplett richtig gemäss Liste eingegeben wurde und man nach der Eingabe statt Enter auf das Gemeindefeld klickt verschwindet der Eintrag.
Das sieht für mich so aus, als wären nur die Einträge aus der Liste zulässig.

![bildschirmfoto 2018-08-31 um 13 45 14](https://user-images.githubusercontent.com/26789445/44918384-0dbd8500-ad3b-11e8-9c37-42834fffe7e5.png)

**Comment by barbalex** [comment]
Ja, du hast recht.

Ich habe kürzlich das Tool für Auswahllisten ersetzt. Dabei hatte ich diese Anforderung vergessen.

Ist in der Entwicklungsversion korrigiert und in ein paar Minuten auf live.

Danke für den Hinweis!
