### ISSUE TITLE
untergeordnete Knoten öffnen

### ISSUE THREAD

**Issue by barbalex** [barbalex/apf2#18]
wie wichtig ist das?
für die Umsetzung brauche ich noch die richtige Idee...

**Comment by csalzmann** [comment]
Ich habe mich gerade mit Karin Marti besprochen. Wir finden es beide für die Übersicht schon recht wichtig. Bitte im Kopf behalten, vielleicht kommt auf einmal die zündende Idee!

**Comment by barbalex** [comment]
gleicher issue wie hier: https://github.com/barbalex/apf2/issues/29
daher schliesse ich diesen
