### ISSUE TITLE
EK/EKF: mit Fotos/PDF etc

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#182]
Bitte in Offerte 2019 integrieren

Wie ich es verstanden habe, kann man mit der Technologie unterschiedliche Dokumente anfügen, z.B. jpg oder auch PDF. Richtig?

Bei EK/EKF möchten wir einerseits gerne Fotos beifügen, evtl Anzahl beschränken, damit Freiwillige nicht 50 Fotos/EK einfügen (es gibt solche fotowütigen Freiwillige).

Andererseits möchten wir auch die Möglichkeit haben, weitere Dokumente anzufügen, z.B. ein PDF. Grund: Wunsch war seitens Artverantwortlichen, bei ausgewählten Pops eine Vegauf anzuhängen. Ich hätte das jetzt als PDF umgesetzt. Es geht da mehr um das Verständnis und den Beschrieb des Lebensraums, nicht um eine EVAB-Eingabe. Was meinst Du?

**Comment by barbalex** [comment]
Es gibt zwei Varianten:
- Fotos bequem verwalten
- Allgemeine Datei-Ablage (müssten also nicht nur pdf sein, auch .xlsx und evab files wären möglich)

Die sind auch kombinierbar.
Beide bedingen, dass ein Dienst oder Server im Internet verwendet wird, um die Dateien zu uploaden.
Werd für nächstes Jahr schauen, wie sich das kombinieren lässt.

**Comment by barbalex** [comment]
Verwandt mit https://github.com/barbalex/apf2/issues/142

**Comment by barbalex** [comment]
Ist umgesetzt
