### ISSUE TITLE
Verorten mittels manueller Erfassung von Koordinaten funktioniert nicht wie erwartet

### ISSUE THREAD

**Issue by alinemeyer** [barbalex/apf2#184]
Lieber Alex
Heute wollte ich eine neue Population erstellen und habe beim Koordinaten eingeben 2 Varianten versucht. Die erste mit dem Doppelklicken in die Karte funktioniert. Gebe ich aber die Koordinaten von Hand ein in die Felder Koordinaten x / y werden die Koordinaten zwar gespeichert, und ich kann den Standort auch über ZH GIS öffnen, aber es taucht kein "Blümchen" in der Karte auf. Vielen Dank für deine Hilfe!

**Comment by ksartori** [comment]
Salut Alex
Dafür funktioniert bei mir der Doppelklick in der Karte nicht. Ausprobiert in Chrom und Firefox.
LG, Karin

**Comment by barbalex** [comment]
Doppelklick funktioniert nachvollziehbar nicht mehr. Das Verhalten muss sich mit einem Update der verwendeten abhängigen Software geändert haben. Kümmere mich drum.

**Comment by barbalex** [comment]
Der Doppleklick-Fehler ist korrigiert

**Comment by ksartori** [comment]
Super, das ging schnell. Merci.
K
---------------------------------------------------------------
Umweltatelier Sartori
Karin Sartori
Gasometerstrasse 31
8005 Zürich

078 863 9116
www.umweltatelier.ch

**Comment by alinemeyer** [comment]
Lieber Alex
Leider treten beim Verorten noch Probleme auf. Wenn ich bei einer neuen Population die Koordinaten mit Zahlen eingebe erscheint kein Blümchen in der Karte, die Koordinaten werden aber gespeichert. Damit ein Blümchen erscheint, muss ich die DB neu laden. Dabei wird leider die eingestellte Hintergrundkarte rausgespickt und ich muss mich im Strukturbaum wieder neu orientieren und die vorherig eingestellte Population suchen. Vielen Dank für deine Hilfe!

**Comment by alinemeyer** [comment]
Lieber Alex
Die Koordinaten werden leider nicht mehr gespeichert wenn ich die Tpop in der Karte verorten möchte.

**Comment by alinemeyer** [comment]
Wenn ich die Koordinaten von Hand eingeben möchte, muss ich sie mehrmals eingeben bis sie angenommen werden. Sind sie dann einmal gespeichert, erscheint aber leider kein Blümchen in der Karte, auch nach Cache leeren und neu laden.

LG

**Comment by alinemeyer** [comment]
Dies geschieht allerdings nur wenn ich eine neue Population erstellen möchte, beim Erstellen einer Tpop werden die Koordinaten gespeichert und das Blümchen erscheint

**Comment by barbalex** [comment]
Grmpffff. Habe ziemlich viel Zeit damit verbracht und muss mich nun anderem widmen :-(

**Comment by barbalex** [comment]
Scheint jetzt nach dem Umbau der Koordinaten zu klappen
