### ISSUE TITLE
Geht zur Zeit schon ein bisschen langsam, gibt es einen Grund?

### ISSUE THREAD

**Issue by ksartori** [barbalex/apf2#185]
![bildschirmfoto 2018-11-02 um 16 01 39](https://user-images.githubusercontent.com/34021237/47923061-bc578080-deb8-11e8-8c01-2c0fa30b8e59.png)
![bildschirmfoto 2018-10-31 um 17 33 52](https://user-images.githubusercontent.com/34021237/47923095-ced1ba00-deb8-11e8-85f9-9369d5bdc0b8.png)

**Comment by barbalex** [comment]
Das liegt nicht am Server, siehe bild:
<img width="832" alt="2018-11-02_16h08_39" src="https://user-images.githubusercontent.com/669783/47923420-a7c7b800-deb9-11e8-85e9-bbfed8ecb12b.png">

Es muss Benutzerseitig sein, mögliche Gründe:

- die Anwendung im Browser is langsam (zu hoher Verbrauch von Arbeitsspeicher oder CPU)
- die Internet-Verbindung ist langsam

**Comment by ksartori** [comment]
Salut Alex

Was ist dann der Grund, wenn nicht der Server, kannst Du Dir einen Reim darauf machen? 
Die Wartezeit ist schon ungewöhnlich lang, dann kommt erst das verschnupfte File, manchmal dauert es dann noch ein bisschen und es geht wieder - oder es taucht schlussendlich dann das grienende File auf, siehe Anhang. Dann geht nichts mehr, neu laden. 
An meiner Down- und Uploadgeschwindigkeit kanns auf jeden Fall nicht liegen.

Liebe Grüsse
Karin

---------------------------------------------------------------
Umweltatelier Sartori
Karin Sartori
Gasometerstrasse 31
8005 Zürich

078 863 9116
www.umweltatelier.ch

**Comment by barbalex** [comment]
Hoi Karin

Der Anhang ("das grienende File") ist nicht angekommen. Vermutlich hast du die letzte Meldung als email geschrieben und das File dort angehängt. Man müsste auf github schreiben, damit das klappt.

Mit den verfügbaren Informationen ist es für mich schwierig, das Problem einzuschätzen. Ev. kommen wir etwas weiter mit folgenden Informationen:

- Das "grienende File"
- Dein Betriebssystem (Windows 10? MacOs? Virtuelles Windows auf Mac?)
- Dein Browser
- Angaben zum Ressourcenverbrauch deines Computers und speziell deines Browsers während das Problem auftritt (auf Windows hiesse das: im Task-Manager nachschauen)
- Wie regelmässig tritt das Problem auf?
- Wie bald tritt das Problem jeweils auf, nachdem du begonnen hast, mit apflora zu arbeiten?
- Hängt es davon ab, ob du mit Karten arbeitest? Daten exportierst? Mehrere Strukturbäume verwendest? apflora gleichzeitig in mehreren Tabs offen hast? Anderes?

Du kannst übrigens apflora.ch auch lokal installieren. Hier der Auszug aus der Projekt-Dokumentation (https://docs.apflora.ch):

> Wer keinen modernen Browser einsetzen darf (wie z.B. die Fachstelle Naturschutz Kt. Zürich) oder aus einem anderen Grund lieber will, kann [hier](https://www.dropbox.com/sh/5ar4f0fu5uqvhar/AADJmUo_9pakOnjL_U27EpQMa?dl=0) die lokal installierbare Version beziehen. Für die Installation auf Windows den aktuellsten apflora-win32-x64-Ordner in den eigenen Benutzer-Ordner kopieren (oder irgendwo sonst, wo Sie über die Rechte verfügen, eine .exe-Datei auszuführen). Dann die darin enthaltene apflora.exe starten

Die lokal installierbare Version verwendet den genau gleichen Code. Sie _könnte_ aber leistungsmässig potentiell in gewissen Szenarien besser abschneiden.

Herzliche Grüsse, Alex

**Comment by alinemeyer** [comment]
Lieber Alex
Ich habe das selbe Problem, Einträge sind zur Zeit fast nicht möglich da die Datenbank ständig abstürzt oder sehr lange braucht zum laden. Bei mir zeigt es dieselbe Fehlermeldung wie bei Karin. Vielen Dank für deine Hilfe!

**Comment by barbalex** [comment]
Hoi Aline

Das Problem ist schwierig anzugehen. Ich habe oben (direkt über deinem comment) ein paar Fragen aufgelistet. Wenn du sie mir beantwortest, kommen wir vielleicht weiter.

LG, Alex

**Comment by barbalex** [comment]
Regula Dickenmann scheint dieselben Probleme zu haben, sie schrieb heute per email:

> Die AP-Floradatei stürzt im Google Chrome dauernd ab. Wenn ich ab und zu eine Eingabe machen kann, geht das extrem langsam und wird meist erst beim dritten oder 4. Versuch überhaupt angenommen. In Firefox kann ich die datei gar nicht mehr starten.

**Comment by barbalex** [comment]
Leider kann ich keine der Beschriebenen Verhalten nachvollziehen.

Wie [oben](https://github.com/barbalex/apf2/issues/185#issuecomment-435793543) beschrieben, bin ich auf genauere Informationen von euch angewiesen, um das Problem gezielter anzugehen.

Was ich soeben gemacht habe:
- Alle Abhängigkeiten aktualisiert und die neue Version live geschaltet (falls irgend eine verwendete Fremd-Software Probleme verursacht haben sollte und dieser Fehler in der Zwischenzeit gelöst worden sein sollte)
- Eine neue Version der lokal installierbaren Version von apflora gebaut. Bin froh, wenn jemand, der Probleme hat, einmal damit ausprobiert ob dieselben Probleme auftreten. Unter [diesem Link](https://www.dropbox.com/sh/y2sv03kvu9h7zst/AABD7oIsH6LZsFXRjVGgKYw6a?dl=0) findet ihr je eine Version für Windows und MacOS. Zum Installieren einfach den Ordner auf dem Desktop speichern und darin die apflora.exe bzw. apflora.app Datei doppelklicken

**Comment by rebeccakurz** [comment]
Lieber Alex
Auch bei mir treten die Probleme mit der APFlora-Datenbank auf. 
Zuerst ist sie einfach sehr langsam (so langsam, dass arbeiten fast nicht möglich ist). Relativ schnell bleibt die Website dann einfach stecken. Dann ist diese Meldung gekommen:
![bildschirmfoto 2018-11-12 um 12 50 10](https://user-images.githubusercontent.com/30288503/48346078-443c4800-e67a-11e8-89d7-34c1edaf1a45.png)
Dann konnte ich nach einiger Wartezeit nochmals ein paar Klicks machen. Dann ist die Website ganz abgestürzt:
![bildschirmfoto 2018-11-12 um 12 53 36](https://user-images.githubusercontent.com/30288503/48346101-5f0ebc80-e67a-11e8-8ddc-ead2e8a23e58.png)
Ich arbeite auf MacOS mit dem Browser Chrome.
Ich hatte nur einen Strukturbaum offen, keine Karten etc., nichts exportiert, nur den Tab mit der Datenbank offen. Ich wollte eine neue Feldkontrolle hinzufügen.

**Comment by barbalex** [comment]
@rebeccakurz wie lange hast du vorher gearbeitet?

**Comment by rebeccakurz** [comment]
Ich habe vorher gar nicht in der FloraDB gearbeitet. Auf dem Mac seit dem Morgen (ca. 7.30).

**Comment by barbalex** [comment]
O.k., ich kann jetzt nachvollziehbar beobachten, dass apflora.ch bei jeder Datenänderung Dutzende Megabytes zusätzlichen Arbeitsspeicher beansprucht. Das kann nicht lange gut gehen :-(

Schwieriges Problem, es kann eine Weile dauern, bis ich es lösen kann.

**Comment by barbalex** [comment]
Provisorisch - und nicht befriedigend - könnt ihr immer wieder den Cache leeren und danach apflora neu laden. Das setzt den Arbeitsspeicher auf null zurück. Aber es geht wohl nicht lange, bis er zu hoch ist und ihr das wiederholen müsst.

**Comment by barbalex** [comment]
Soeben habe ich ein Update hochgeladen, dass dieses Problem zumindest stark reduzieren sollte.

Noch bin ich nicht ganz sicher, ob das Problem ganz gelöst ist oder bloss um ca. einen Faktor 10 reduziert.

Bitte löscht euren Cache für apflora.ch und probiert es aus.

Warnung: Es wurde *sehr viel* geändert (drei Tage Arbeit...). Gut möglich, dass nun neue Fehler auftauchen :-(

Ursache ist ein Fehlverhalten der verwendeten (Fremd-)Software, welche den Zwischenspeicher verwaltet: Bei jedem Speichervorgang hat sie den Zwischenspeicher stark anschwellen lassen.

**Comment by barbalex** [comment]
Meinst du den Filter im Strukturbaum oder den Formular-Filter?

**Comment by csalzmann** [comment]
Im Strukturbaum, z.B. Wenn ich nach einer Population etc filtern will

**Comment by alinemeyer** [comment]
Ich habe das selbe Problem. 
Ausserdem wird bei mir oft der Filter im Strukturbaum rausgeworfen wenn ich das dropdown Fenster apflora öffnen will um eine Population in der Karte zu suchen. 
![bildschirmfoto 2018-11-28 um 09 50 11](https://user-images.githubusercontent.com/42208152/49143122-a3e15700-f2fa-11e8-9b91-e66ff61fa4c7.png)

**Comment by barbalex** [comment]
@alinemeyer Ja, dieser Fehler ist in der Entwicklungsversion behoben

**Comment by barbalex** [comment]
@alinemeyer nicht nur der Filter, v.a. der aktive Knoten im Strukturbaum wird deaktiviert. Üble Sache. Aber in der Entwicklungsversion behoben

**Comment by barbalex** [comment]
@alinemeyer Knoten im Strukturbaum werden seit dem Update gestern nicht mehr deaktiviert. Danke für die Meldung. Bitte mach in solchen Fällen künftig ein neues issue, da es nichts mit diesem issue zu tun hatte.

**Comment by barbalex** [comment]
Ich schliesse diesen Issue, da das Verhalten momentan nicht beobachtet werden kann
