### ISSUE TITLE
Löschen der Zähleinheiten funktioniert auch gerade nicht.

### ISSUE THREAD

**Issue by ksartori** [barbalex/apf2#186]
![bildschirmfoto 2018-11-02 um 15 26 27](https://user-images.githubusercontent.com/34021237/47923122-dee99980-deb8-11e8-8bf3-d39471166be9.png)

**Comment by barbalex** [comment]
Ist nachvollziehbar. Ich kümmere mich drum

**Comment by barbalex** [comment]
Sollte jetzt repariert sein. Danke für die Meldung
