### ISSUE TITLE
Beobachter nicht immer in Auswahlliste

### ISSUE THREAD

**Issue by wunderli** [barbalex/apf2#187]
Lieber Alex

Heute Morgen versucht mit Compi von RL (Dom) im Google Drive mit Login von Karin Marti in der DB Erfolgskontrolle von Jonas Brännhage einzugeben.
Jonas Brännhage erschien aber nicht in der Auswahlliste, obwohl in der Adress-Liste vorhanden.
Darum zeigte es diesen Eintrag nicht an, bzw. fiel die Eingabe wieder raus.

Gleiches getestet am Compi von Charlotte Salzmann (Bernina) im Google Drive mit dem Login von mir.
Liste "hüpft": Mal ist Jonas Brännhage in der Liste, mal wieder nicht.
Auch mehrmals die Seite neugeladen.

Gleiches getestet am Compi von Karin Marti (Pizol) mit Login von Karin Marti: Trotz wiederholtem Laden wird Jonas Brännhage nie in der Auswahl-Liste angezeigt.

Gleiches getestet an meinem Compi (Clariden) mit meinem Login: Mit wiederholtem Laden wird Jonas Brännhage ab und an in der Auswahl-Liste angezeigt.

PS: Aus irgend einem Grund, wurde eine falsche "Adresse" erstellt.
Es sollte eigentlich "Jonas Brännhage" heissen und nicht "Jonas Brännege". Evtl. könntest du das auch noch in allen Einträgen + Adresse anpassen? Jetzt sollten es noch nicht viele Einträge sein, aber wenn ich es ändern würde, gingen die bestehenden wohl verloren?!?

Liebe Grüsse

Anna

![bildschirmfoto 2018-11-19 um 09 28 43](https://user-images.githubusercontent.com/26789445/48696020-093d9580-ebe1-11e8-8402-63a86461db94.png)
![bildschirmfoto 2018-11-19 um 09 29 39](https://user-images.githubusercontent.com/26789445/48696024-0b9fef80-ebe1-11e8-9f08-55bb8d2a2ed0.png)

![bildschirmfoto 2018-11-19 um 09 30 04](https://user-images.githubusercontent.com/26789445/48696055-1c506580-ebe1-11e8-9749-70c5c3859aba.png)
![bildschirmfoto 2018-11-19 um 09 30 20](https://user-images.githubusercontent.com/26789445/48696059-1f4b5600-ebe1-11e8-966c-cc4fe791dc44.png)

**Comment by barbalex** [comment]
Hoi Anna

Habe soeben:

- In apflora eingeloggt
- Die Adresse korrigiert
- In eine Feldkontrolle gewechselt
- Die Adresse gewählt. _Es war aber noch die alte Version in der falschen Schreibweise_.
- Daher habe ich apflora neu geladen
- Die gewählte Adresse war nun richtig geschrieben
- Auch wenn ich sie neu wähle, erscheint sie immer und richtig geschrieben in der Liste.

Bemerkungen:

- Keine Ahnung, wieso es bei dir/euch offenbar gar nicht geklappt hat
- Ich müsste nachbessern, damit man nach einer Änderung/Neuerfassung einer Adresse apflora nicht neu laden muss, um die Bearbeiterliste aktuell zu haben. _Das war aber bis vor wenigen Tagen implementiert: Das ist genau die Funktion, die ich abschalten musste, um das Anwachsen des Zwischenspeichers zu stoppen_. Es stimmt etwas nicht im verwendeten Werkzeug. Leider konnte ich den Fehler nicht nachvollziehbar isolieren um den Entwicklern dieses Werkzeugs zu helfen, das Problem zu lösen. Wir müssen daher darauf warten, dass dieser Fehler bei einem künftigen Update gelöst wird (Updates gibt es alle paar Wochen aber ich muss aufwändig testen um zu merken, ob dieses Problem gelöst wurde). In der Zwischenzeit müssen wir uns damit behelfen, apflora neu zu laden, wenn eine Liste, die soeben geändert wurde, in der vorigen Version angezeigt wird.

>  Evtl. könntest du das auch noch in allen Einträgen + Adresse anpassen?

Das ist nicht nötig. Gespeichert wird die ID der Adresse. So bald du neu lädst und die BearbeiterInnen-Liste bei dir aktualisiert ist, sollte sie richtig angezeigt werden.

**Comment by barbalex** [comment]
Nur zur Erklärung: Wenn du apflora.ch neu lädst, werden alle Daten nochmals beim Server abgeholt.

Sollte aus unerfindlichem Grund eine Liste danach nicht aktualisiert sein, müsstest du den Cache (=Zwischenspeicher) im Browser löschen und danach apflora.ch neu laden, um die Daten wieder zu holen.

**Comment by barbalex** [comment]
Ich gehe davon aus, dass die Ursache dieser Issue war: https://github.com/barbalex/apf2/issues/204#issuecomment-445176630

...und schliesse daher
