### ISSUE TITLE
EKF-Formular - Benachrichtigungen Eingaben

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#188]
Lieber Alex

Für nächstes Jahr ist ja geplant, dass noch mehr Freiwillige ihre Kontrollen über das EKF-Formular direkt in die Datenbank eingeben. 
Wäre es möglich, dass sobald ein Freiwilliger ein Formular ausgefüllt hat, eine Benachrichtigung an den Artverantwortlichen und an die Koordinationsstelle (z.B. JM) gehen würde? Dann könnten die Eingaben überprüft und z.B. allfällige Bewirtschaftungsmeldungen etc. weitergegeben werden.
Die Benachrichtigung könnte in Form einer E-Mail, z.B. von einem speziellen Absender (EKF-Flora-DB?) kommen, so dass sie direkt in einem Ordner gesammelt und dann bearbeitet werden können.
Das müsste erst für 2019 umgesetzt werden.

LG

**Comment by barbalex** [comment]
An der letzten Sitzung haben wir beschlossen, vorläufig nur bzw. erst einen Export zu schaffen der zeigt, wie viele der geplanten Kontrollen durchgeführt wurden.
