### ISSUE TITLE
Qualitätskontrolle: wird nicht neu gerechnet

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#189]
Wenn man Qualitätskontrolle aufruft und anschliessend Korrekturen vornimmt, wird bei erneutem Klick auf die Qualitätskontrolle diese nicht wieder neu gerechnet. Eine neue Qualitätskontrolle bekommt man erst mit "neu laden". Da fliegen aber wieder alle Selektionen raus. 
Bei Klick auf die Qualitätskontrolle sollte diese also jedes Mal neu gerechnet werden.

**Comment by barbalex** [comment]
Ist korrigiert. Danke für die Meldung

**Comment by csalzmann** [comment]
Qualitätskontrolle wird nur gerechnet, wenn man zwischendurch auf eine Pop klickt und wieder zurück zur Qualitätskontrolle gelangt. Dann sieht man zuerst die alten Resultate und man bemerkt nicht, dass die Qualitätskontrolle im Hintergrund gerechnet wird. Wenn man da schnell drüber geht, könnte man etwas verpassen (z.B. wenn neue Fehler auftauchen, und vorher alles iO war. Früher war das doch so, dass es immer eine Meldung gab, wenn die Qualitätskontrolle am rechnen war?

**Comment by barbalex** [comment]
> wird nur gerechnet, wenn man zwischendurch auf eine Pop klickt und wieder zurück zur Qualitätskontrolle gelangt

Wann soll sie denn neu gerechnet werden? Offenbar ohne, dass man die Qualitätskontrolle verlässt?

**Comment by barbalex** [comment]
> Früher war das doch so, dass es immer eine Meldung gab, wenn die Qualitätskontrolle am rechnen war?

Das ist mit der aktuellen Lösung leider viel schwieriger zu realisieren. Weil sie - entgegen der Dokumentation des verwendeten Werkzeugs - nicht korrekt mitteilt, wenn sie die Daten neu holt. Ich hab's probiert, weil ich das auch erreichen wollte.

**Comment by csalzmann** [comment]
Also das kann sicher eine Fehlerquelle sein, wenn man da zu ungeduldig ist. 

Wie kann ich denn eine neue Qualitätskontrolle erzwingen? Ich hab gemerkt, nicht mal nach neu laden ist die Qualitätskontrolle "leer", dh, es steht immer noch das alte Resultat drin. 

Das Hauptproblem ist dann doch wohl eher immer noch, dass die nicht gerechnet wird, wenn man draufklickt?

**Comment by barbalex** [comment]
Ich hab's endlich richtig hingekriegt. Die neue Lösung kann es schon, es ist nur nicht richtig dokumentiert...

Deine Hartnäckigkeit hat sich gelohnt :-)

**Comment by csalzmann** [comment]
und Du bist ein Held :)!
