### ISSUE TITLE
Karte: Anzeige Teilpopulationen, Populationsnummer nicht mehr sichtbar

### ISSUE THREAD

**Issue by jmenzi** [barbalex/apf2#19]
Häufig nutze ich die Kartenfunktion zur Erstellung von Übersichtsplänen, auf welchen alle Teilpopulationen dargestellt werden. Auf der neuen Karte werden aber nur noch die Teilpopulationsnummern angezeigt. So kann ich die Karten aber nicht an externe verschicken, da nicht klar ist, welcher Population die jeweilige Teilpopulation angehört. Mein Vorschlag: Populationsnummer.Teilpopulationsnummer (wie in alter Version). Also z.B. 103.4 statt nur eine 4.

**Comment by barbalex** [comment]
In der Entwicklungsversion umgesetzt. Danke für den Input

**Comment by barbalex** [comment]
ist jetzt live
