### ISSUE TITLE
Qualitätskontrolle: zu unrecht Fehler bei TPop-Status wenn Kontroll-Bericht erloschen und im gleichen Jahr Ansiedlung

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#190]
Wir hatten so etwas schon mal (Nr. 83), ich beginne hier aber lieber wieder einen neuen Issue.

Bsp. Saxifraga, TPop 100.2

EK Frühjahr 2016: TPop erloschen -> Status TPop Frühjahr 2016: erloschen
Massnahme Herbst 2016: Ansiedlung -> Status TPop Herbst 2016: angesiedelt, aktuell

Die Qualiätskontrolle merkt aber offenbar nicht, dass es NACH dem Status TPop erloschen im selben Jahr wieder eine Ansiedlung gab.

**Comment by csalzmann** [comment]
![bildschirmfoto 2018-11-22 um 12 44 45](https://user-images.githubusercontent.com/6047564/48901849-0055f980-ee57-11e8-90f3-f25f91820a70.png)

![bildschirmfoto 2018-11-22 um 12 45 33](https://user-images.githubusercontent.com/6047564/48901857-05b34400-ee57-11e8-85c4-707359c461de.png)

**Comment by barbalex** [comment]
Es ist nicht möglich, das genauer zu vergleichen. Grund: Der Kontrollbericht hat kein Datum, sondern nur ein Jahr.

Es fragt sich auch, ob es sinnvoll wäre, pro Jahr mehrere Kontrollberichte zu erstellen: Ihr einziger Zweck ist es, die Entwicklung für den Jahresbericht zu beschreiben.

Ich schliesse daraus: Der Jahresbericht muss in diesem Fall angepasst werden. Und die Qualitätskontrolle erfüllt genau ihren Zweck, indem sie darauf hinweist, dass hier eine Korrektur nötig ist.

Siehst du das anders?

**Comment by csalzmann** [comment]
Hmm, ich bin nicht sicher, ob ich Dich richtig verstehe.

Der Kontrollbericht bezieht sich ja auf die EK des laufenden Jahres, ebenso der Massnahmenbericht. Wenn ich anschliessend an die EK im gleichen Jahr wieder eine Massnahme mache, kann diese erst im folgenden Jahr beurteilt werden. Möchtest Du dieses Vorgehen ändern und deshalb den Jahresbericht anpassen?

Mir scheint es einfacher, die Qualitätskontrolle anzupassen. Wieso sollte das denn nicht gehen? Es ist ja eine Regel wie andere auch, zu Fällen, die immer wieder auftreten. Es sind all diese Gelegenheiten, wo eine Ansiedlung im ersten Anlauf aus verschiedenen Gründen (Trockenheit etc) nicht geklappt hat, man aber nochmals einen Versuch macht. Das gibt es schon immer wieder.

Wenn Du den Jahresbericht nicht anpassen kannst, kann man wenigstens den Fehler "abstellen", so dass er nicht immer wieder auftaucht? ZB dass man sagt, man hat den Hinweis gesehen, aber belässt den "Fehler" willentlich?

**Comment by barbalex** [comment]
Was ich meine ist: Der Bericht weiss nicht, ob er vor oder nach der Massnahme erstellt wurde.

Beziehungsweise: Die Kontroll-Abfrage kann das nicht ermitteln, weil im Bericht nur das Jahr erfasst ist.

**Comment by barbalex** [comment]
Ich kann natürlich die Abfrage so ändern, das "seither" nicht heisst, "nach dem Bericht-Jahr", sondern "im selben Jahr oder danach".

**Comment by csalzmann** [comment]
Ja, das wäre die gute Lösung wohl!

**Comment by barbalex** [comment]
Es gibt 10 Kontrollen, mit `und es gab seither keine Ansiedlung`. Ich muss dafür:

* 10 Views suchen
* 10 Views anpassen
* 10 Views auf dem Server ersetzen
* testen

Das ist ca. eine gute Stunde Arbeit (Erweiterung).

**Comment by barbalex** [comment]
Übrigens, du hast oben gesagt:

> Wir hatten so etwas schon mal (Nr. 83), ich beginne hier aber lieber wieder einen neuen Issue

Finde ich super, das es nicht dasselbe ist. Wenn neue Issues in bestehenden unten angefügt werden, verliere ich mich völlig. Wenn hingegen aus Versehen ein neues erstellt wird, kann man sie verlinken, das ist nicht so schlimm.

**Comment by barbalex** [comment]
Hab's umgesetzt. War weniger Aufwand. Dein Beispiel (Saxifraga, TPop 100.2) wird jetzt nicht mehr aufgelistet.
