### ISSUE TITLE
Karte: unterscheidbare Symbole für unterschiedliche Stati

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#191]
Lieber Alex

Da ich die ursprünglichen Issues (Karten: neue Layer mit Pops/TPops nach Status symbolisiert, resp. Beobachtungen zuordnen: TPop-Status kenntlich machen) nicht mehr finden kann, eröffne ich jetzt einen neuen Issue.

Es geht darum, dass wir gerne möchten, dass die Pop/TPop je nach Status (ursprünglich aktuell/ursprünglich erloschen/angesiedelt aktuell/angesiedelt erloschen) unterschiedlich auf der Karte angezeigt werden. Dafür bräuchte es z.B. zwei verschiedene Symbole (ursprünglich oder angesiedelt) und zwei verschiedene Farben (aktuell oder erloschen). 

So könnte z. B. einfach verhindert werden, dass eine angesiedelte Beobachtung mittels Drag & Drop einer ursprünglichen TPop zugeordnet wird, da dann auf der Karte sofort sichtbar ist, ob es sich um eine ursprüngliche oder eine angesiedelte TPop handelt.

Wäre das möglich?
LG

**Comment by barbalex** [comment]
Bisher war das hier diskutiert: https://github.com/FNSKtZH/apflora/issues/149

**Comment by barbalex** [comment]
Soeben in der Entwicklungsversion implementiert: Status ist sichtbar, wenn man auf eine Beobachtung klickt. Weitere Massnahmen folgen.

**Comment by barbalex** [comment]
@csalzmann @alinemeyer @jmenzi
Soeben live geschaltet:

Pop und Tpop:

- Im Layertool kann man neu auf das Symbol (die Blume) für die Ebene klicken
- Es öffnet sich ein Menu
- Man kann hier wählen, die Symbole folgendermassen anzuzeigen:
   - normal (Blume)
   - nach Status-Gruppe, d.h.:
      - ursprünglich: U
      - angesät: A
      - potentiell: P
      - ohne Status: ?
- das funktioniert auch beim Zuordnen von Beobachtungen

Ich werde noch folgendes machen:

- Diese Funktionalität in der Dokumentation ergänzen
- Sie beim Aufstarten der Anwendung mitteilen
- Die Optionen, um die Beschriftung von Pop/Tpop zu ändern, hierhin (in dieses Menu) zügeln. Heute sind sie im Menu untergebracht, und zwar auf Ebene Aktionsplan, wo ich sie kürzlich erst nach langer Suche fand...

Ich hab das Gefühl, das ist so einigermassen funktional und logisch. Wenn man weiss, dass diese Funktionalität existiert. Danke für eure Inputs!

**Comment by barbalex** [comment]
Ist alles gemacht

**Comment by barbalex** [comment]
> Es müsste heissen: angesiedelt/ursprünglich/potentiell (nicht aktuell)

Ist in der Entwicklungsversion korrigiert

**Comment by rebeccakurz** [comment]
Danke!

**Comment by barbalex** [comment]
@rebeccakurz In diesem Issue: https://github.com/FNSKtZH/apflora/issues/149 habe ich umfangreiche, z.T. sehr ähnliche Vorschläge gemacht, wie du sie jetzt erwähnst. Aber auch klar gestellt, dass die Sache nicht einfach ist und wir daher genau wissen müssen, wofür genau die Darstellung genutzt wird. Und dass wir je nachdem 18 verschiedene Symbole bräuchten, was nicht funktionieren kann.

Darauf habe ich leider keine Antwort bekommen.

Oben in diesem Issue hast du die Massnahme begründet mit:

> So könnte z. B. einfach verhindert werden, dass eine angesiedelte Beobachtung mittels Drag & Drop einer ursprünglichen TPop zugeordnet wird, da dann auf der Karte sofort sichtbar ist, ob es sich um eine ursprüngliche oder eine angesiedelte TPop handelt.

Genau das wird vermutlich durch die Art, wie es jetzt implementiert ist, genau erreicht. Oder nicht?

Was macht ihr denn auf der Karte, wofür ihr anhand der Symbole _genau_ sehen müsstet, welcher Status es ist?

**Comment by barbalex** [comment]
Ich schliesse das, weil schon alt und weil es für das Budget 2019 kein Thema war

**Comment by csalzmann** [comment]
Ich öffne das wieder, weil das für uns eigentlich schon ein wichtiges Thema ist. Wir sind einfach noch nicht weitergekommen.

**Comment by barbalex** [comment]
O.k., ich warte auf Vorschläge von euch.

**Comment by rebeccakurz** [comment]
Hoi Alex

Damit dir auch ja nicht langweilig wird, komme ich wieder mal mit einem alten Issue...
Du erwähnst oben, dass es mindestens 18 Symbole brauchen würde, um die unterschiedlichen Stati darzustellen. 
Wie wäre es denn mit denselben Symbolen wie in den Karten des Jahresberichts? (siehe Screenshot)
<img width="330" alt="Bildschirmfoto 2019-09-19 um 15 17 19" src="https://user-images.githubusercontent.com/30288503/65248961-5afdc780-daf3-11e9-8049-d9fb3b337ed6.png">

So könnte man mit 5 Symbolen das Meiste abdecken. 
Für ursprünglich einen Kreis, ursprünglich erloschen einen durchgestrichenen Kreis
für angesiedelt ein Viereck, angesiedelt erloschen ein durchgestrichenes Viereck
für Ansaatversuch ein Dreieck (das ist ja der Fall, wenn Massnahme, aber noch keine Pflanzen)

für den potentiellen Wuchsort müsste man noch etwas suchen oder das P lassen.

Könntest du bei Gelegenheit schauen, ob das für dich umsetzbar wäre?

Vielen Dank und liebe Grüsse
Rebecca

**Comment by barbalex** [comment]
Habe soeben eine Stunde darin investiert.

Vorschläge inklusive Begründung: 
- Populationen und Teil-Populationen müssen unterschieden werden können. Das heisst: Es braucht doppelt so viele. Am Einfachsten wäre es, wenn wie bisher dieser Unterschied durch die Farbe ausgedrückt würde: Grün für TPop, Braun für Pop. Dann müssen aber die von euch vorgeschlagenen Farben (Gelb für erloschen, Blau für Ansaatversuche) aufgegeben werden
- Es muss sichtbar sein, welche Pop/TPop im Navigationsbaum aktiv ist. Am besten ginge das wieder wie bisher: Gelbe Farbe.
- Für potentielle Wuchsorte könnte z.B. ein Stern verwendet werden

Weil Symbole im Gegensatz zu Buchstaben von mir selber gebaut werden müssen und es neu viel mehr unterschiedliche Varianten geben wird, gibt diese Anpassung mehrere Stunden Arbeit (geschätzt: 6).

Was meinst du?

**Comment by barbalex** [comment]
Ist für TPop in Version 1.51.0 umgesetzt. Siehe das Menü, dass man öffnet, wenn man im Layer-Tool der Karte auf das Blumen-Symbol der Teil-Populationen klickt.
Neu gibt es bei den TPop übrigens auch die Option, keine Beschriftung anzuzeigen.

Ich schliesse den Issue aber bin offen für Verbesserungen.

**Comment by rebeccakurz** [comment]
Super, vielen Dank, das sieht gut aus!
