### ISSUE TITLE
Jahresberichte für frei wählbare Arten erstellen

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#193]
Lieber Alex

Gemäss Rechnung wurde dieser Issue bereits umgesetzt. Kannst du uns erklären wie es funktioniert?

LG

**Comment by barbalex** [comment]
Genau gleich, wie beim allgemeinen Jahresbericht: Im Strukturbaum gibt es ein pdf-Symbol, auf das man klickt.

Es ist einfach beim AP-Bericht der Art und nicht des Projekts.

**Comment by barbalex** [comment]
Hi hi, die nächste Anleitung verstecke ich in der nächsten Rechnung. Dann findet ihr sie besser...

**Comment by barbalex** [comment]
Kopier das bitte in einen neue Issue: Das ist ein Fehler. Das Problem ist wegen des grossen Problems, bei dem die Anwendung den Arbeitsspeicher wegfrass bin ich die Anwendung massiv am Umbauen. Wenn ich jetzt etwas aktualisiere funktioniert wahrscheinlich viel mehr nicht mehr als jetzt.

Ich werde also intensiv an den Anpassungen weiter arbeiten und ein Update liefern, sobald ich nach dem Umbau die übrigen Funktionen getestet habe. Oder wenn etwas mega-dringendes auftaucht, das unbedingt sofort repariert werden muss.
