### ISSUE TITLE
Jahresbericht abrufen

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#194]
Wenn ich den Jahresbericht abrufen möchte, erscheint eine Fehlermeldung:
![bildschirmfoto 2018-11-22 um 15 57 09](https://user-images.githubusercontent.com/30288503/48911159-5ab08380-ee72-11e8-984c-56e426056038.png)

**Comment by barbalex** [comment]
Momentan bin ich verhindert, werde es also in ein paar Wochen reparieren.

Solange kann man den Jahresbericht pro Art produzieren. Der funktioniert.

**Comment by barbalex** [comment]
Ist in der Entwicklungsversion behoben. Es dauert aber eine Weile, bis sie live geschaltet wird.

**Comment by barbalex** [comment]
Die korrigierte Version ist jetzt live
