### ISSUE TITLE
Qualitätskontrollen: Berichte nicht aus Berichtjahr

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#195]
Wenn ich eine Qualitätskontrolle durchführe erscheinen immer auch Berichte die nicht aus dem dem ausgewählten Berichtjahr stammen.
![bildschirmfoto 2018-11-22 um 16 21 31](https://user-images.githubusercontent.com/30288503/48911279-b0852b80-ee72-11e8-838e-b746a7209451.png)

**Comment by barbalex** [comment]
Ist nicht mehr so. Danke für die Meldung
