### ISSUE TITLE
Qualitätskontrollen: Fehlermeldungen von EKF

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#196]
Wenn ich eine Qualitätskontrolle z.B. bei Himantoglossum hircinum durchführe, erscheinen sehr viele Fehlerbericht von "Zählung ohne Anzahl (Freiwilligen-Kontrolle)" und "Zählung ohne Methode (Freiwilligen-Kontrolle)". Wenn man die Einträge aber ansieht, sind sowohl Zählungen als auch Methoden vorhanden. 
Könnte es etwas damit zu tun haben, dass jeweils nur eine oder zwei Zähleinheiten ausgefüllt sind, nicht aber alle drei? Also z.B. Pflanzen und blühende Pflanzen, aber keine Blüten?

**Comment by barbalex** [comment]
Es hat wirklich Zählungen ohne Anzahl.

Damit die Freiwilligen nur noch ausfüllen müssen, was von ihnen erwartet wird, werden für alle unter `EKF-Zähleinheiten` definierten Einzeiten Zählungen angelegt (sobald man die Freiwilligen-Kontroll öffnet und das zuvor noch nicht passiert ist). Aber natürlich ohne Anzahl, denn das sollen die Freiwilligen ausfüllen.

Hat ein Freiwilliger noch nicht gearbeitet oder nur für einen Teil der Zählungen die Anzahl erfasst, erscheinen diese Zählungen in der Qualitätskontrolle.

Und wenn ihr der Meinung seid, die Einheit habe in diesem Fall nicht erfasst werden müssen, könnt ihr die Zählung löschen. Dann erscheint sie auch nicht mehr in der Qualitätskontrolle.

Wenn ihr aber der Meinung seid, diese Einheit müsse generell nicht mehr gezählt werden, müsst ihr sie zusätzlich bei `EKF-Zähleinheiten` löschen, damit künftig keine Zählungen mehr für diese Einheit angelegt werden.

**Comment by csalzmann** [comment]
Das wird für uns sehr aufwändig, weil oft einzelne Zähleinheiten nicht erfasst werden. Die Zähleinheit an sich wollen wir aber nicht löschen.
Ich habe nun versucht, bei Himanto eine Zählung/Einheit zu löschen. Das geht aber gar nicht. Man kann zwar die Zählung löschen, aber wenn nichts drin ist, wirds auch nicht weniger. Die Einheit selber kann man nicht löschen für eine einzelne EK. Die Fehlermeldung bleibt bestehen.

**Comment by barbalex** [comment]
In welcher Kontrolle ist die Zählung gelöscht und es erscheint trotzdem eine Fehlermeldung?

**Comment by csalzmann** [comment]
Du hast recht, es funktioniert. Aber erst nach neu laden, vorher sieht man gar nicht, dass man etwas gemacht hat. Das ist nicht grad übersichtlich.
Grundsätzlich möcht ich das aber mit topos noch besprechen, ob diese Qualitätskontrolle wirklich nötig ist. Schau mal, wieviele Zählungen ich bei Himanto löschen müsste.. 
![bildschirmfoto 2018-12-04 um 17 33 59](https://user-images.githubusercontent.com/6047564/49457284-d99aaa00-f7ea-11e8-904f-3d3c7a8dd857.png)

**Comment by csalzmann** [comment]
Ausserdem hatte ich jetzt auch noch ein paar Mal den Fall, wo ich eine EK vermerkt habe, weil jemand vor Ort war, aber die EK konnte nicht durchgeführt werden, weil Fläche nicht zugänglich war. So ist es also richtig, dass es dort keine Zählung hat.

**Comment by barbalex** [comment]
Musst du sie wirklich löschen?

Müssten Sie den nicht Anzahlen enthalten, sobald die Freiwilligen ihre Daten erfasst haben?

Und die Kontrolle wäre _danach_ nützlich, um zu sehen, wo die Freiwilligen keine Anzahlen erfasst haben? 

Worauf man diese Kontrollen löscht, wenn auf ihre Erfassung verzichtet werden kann - oder die Freiwilligen bittet, nachzutragen?

**Comment by barbalex** [comment]
> Ausserdem hatte ich jetzt auch noch ein paar Mal den Fall, wo ich eine EK vermerkt habe, weil jemand vor Ort war, aber die EK konnte nicht durchgeführt werden, weil Fläche nicht zugänglich war. So ist es also richtig, dass es dort keine Zählung hat.

Würde man die EK dann nicht wieder löschen?

**Comment by csalzmann** [comment]
Nein, das geht nicht. Es ist eben so, dass man nicht zu jedem Zeitpunkt alle Einheiten erfassen kann. Es geht hauptsächlich hier um Orchideen, evtl gibts aber auch noch andere Anwendungen. Bei Orchideen hab ich im Winter/Frühjahr nur Pflanzen und Rosetten, im Sommer nur Pflanzen/blühende Pflanzen.

**Comment by barbalex** [comment]
Ich verstehe nicht. Nach meinem Verständnis:

- löscht man die EK, wenn gar nichts gezählt werden konnte - denn es fand keine statt
- löscht man die Zählung, wenn diese Einheit nicht gezählt wurde (aber eine andere schon)

**Comment by csalzmann** [comment]
Bei Himanto konnte ich nun Zähleinheiten individuell löschen. Aber das ist eben sehr aufwändig. Oder reden wir aneinander vorbei?

![bildschirmfoto 2018-12-04 um 17 43 10](https://user-images.githubusercontent.com/6047564/49458063-55e1bd00-f7ec-11e8-9eb1-99db68769ca0.png)
![Uploading Bildschirmfoto 2018-12-04 um 17.43.39.png…]()

**Comment by csalzmann** [comment]
So gibt es immerhin keine Fehlermeldung mehr, aber eben..

**Comment by barbalex** [comment]
Ein anderer Ansatz wäre, wenn die Einheiten gar nicht vorher erstellt würden, sondern erst beim erfassen. Aber dann kann das Formular nicht als Feld-Formular gedruckt werden.

**Comment by barbalex** [comment]
Man könnte einen Befehl bauen, mit dem alle Kontrollen ohne Anzahl eines Aktionsplans (und einer Freiwilligen?) gleichzeitig gelöscht werden. Den könnte man dann laufen lassen, wenn die Freiwilligen ihre Arbeit abgeschlossen haben.

**Comment by csalzmann** [comment]
Wofür brauchen wir denn noch diese Kontrolle, wenn wir nachher alle löschen? 

Ursprünglich brauchten wir diese Abfrage v.a., weil manchmal die FloraDB Zählungen nicht angenommen rsp. gespeichert hat. Das man beim Eingeben die Zählung vergisst, ist eher selten (aber kommt schon vor, hab es bei meinen eigenen Eingaben gemerkt).

Im Prinzip sollten wir aber spätestens bei den Kontrollberichten merken, ob da eine Anzahl drin steht oder nicht. Die Personen, welche die Eingaben machen, machen selber eigentlich keine Qualitätskontrollen. Zu dem Zeitpunkt gibt es dann ja noch so viele "Fehler", dass es kaum Sinn macht.

Wenn die Einheiten nicht voreingestellt sind, dann haben wir mit den Freiwilligen wohl wieder schwieriger, weil die dann irgendetwas erfassen. Drum ist die Voreinstellung schon gut.

Deshalb: sollten wir diese Qualitätskontrolle vielleicht streichen? Wäre das fahrlässig?

**Comment by csalzmann** [comment]
Habe gerade nochmals mit Karin Marti gesprochen.

Ideal wäre es so: 
die Kontrolle für EKF: mind. 1 Zähleinheit muss mit Zählung sein
die Kontrolle für Feldkontrollen: Jede Zähleinheit muss eine Zählung haben (weil wir hier die Zähleinheiten ja manuell eingeben)

Ginge das?

**Comment by barbalex** [comment]
Klar.

Ist aber eine wesentlich anspruchsvollere Abfrage, d.h. ich muss es anders lösen (QraphQL-Zugriff auf SQL-View anstatt direkt GraphQL-Abfrage).

Gibt schätzungsweise 30 bis 45 Minuten Aufwand.

**Comment by barbalex** [comment]
Ist umgesetzt. Wird soeben live gesetzt.

**Comment by csalzmann** [comment]
Sieht schon viiiel besser aus bei Himantoglossum, Danke! Jetzt bitte noch das gleiche für die Methode :)

![bildschirmfoto 2018-12-07 um 13 45 12](https://user-images.githubusercontent.com/6047564/49648509-5a91b580-fa26-11e8-8733-b8d2cb76f34a.png)

**Comment by barbalex** [comment]
Gemacht
