### ISSUE TITLE
Qualitätskontrolle: Fehlende Kontroll- und Massnahmenberichte werden NIE angezeigt

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#197]
Diese Qualitätskontrolle ist ziemlich wichtig, weil wir ohne sie die Berichte, die jetzt anstehen, eigentlich gar nicht machen können. Nur aus Exporten können wir noch herausfinden, wo überhaupt EKs stattgefunden haben. Und das ist ein viel mühseligeres Vorgehen als über die Qualitätskontrollen. 

Meinst Du, Du kannst die Qualitätskontrollen bis Ende Woche noch hinkriegen?

**Comment by barbalex** [comment]
Welche Kontrollen meinst du genau? Wir haben über 100. Viele davon zu Berichten. Meinst du ev.:

- Population mit angesiedelten Teilpopulationen (vor dem Berichtjahr), die (im Berichtjahr) kontrolliert wurden, aber ohne Populations-Bericht (im Berichtjahr): https://github.com/barbalex/apf2/blob/master/src/components/Projekte/Daten/Qk/qk.js#L258
- Populationen mit Bericht "zunehmend" ohne Teil-Population mit Bericht "zunehmend": https://github.com/barbalex/apf2/blob/master/src/components/Projekte/Daten/Qk/qk.js#L271
- Populationen mit Bericht "erloschen" ohne Teil-Population mit Bericht "erloschen": https://github.com/barbalex/apf2/blob/master/src/components/Projekte/Daten/Qk/qk.js#L293
- Populationen mit Bericht "erloschen" und mindestens einer gemäss Bericht nicht erloschenen Teil-Population: https://github.com/barbalex/apf2/blob/master/src/components/Projekte/Daten/Qk/qk.js#L304
- Population: Status ist "erloschen" (ursprünglich oder angesiedelt), Ansaatversuch oder potentieller Wuchsort; der letzte Populations-Bericht meldet aber "zunehmend" und es gab seither keine Ansiedlung:https://github.com/barbalex/apf2/blob/master/src/components/Projekte/Daten/Qk/qk.js#L385
- Population: Status ist "erloschen" (ursprünglich oder angesiedelt), Ansaatversuch oder potentieller Wuchsort; der letzte Populations-Bericht meldet aber "stabil" und es gab seither keine Ansiedlung: https://github.com/barbalex/apf2/blob/master/src/components/Projekte/Daten/Qk/qk.js#L396
- Population: Status ist "erloschen" (ursprünglich oder angesiedelt), Ansaatversuch oder potentieller Wuchsort; der letzte Populations-Bericht meldet aber "abnehmend" und es gab seither keine Ansiedlung:https://github.com/barbalex/apf2/blob/master/src/components/Projekte/Daten/Qk/qk.js#L407
- Population mit angesiedelten Teilpopulationen (vor dem Berichtjahr), die (im Berichtjahr) kontrolliert wurden, aber ohne Massnahmen-Bericht (im Berichtjahr): https://github.com/barbalex/apf2/blob/master/src/components/Projekte/Daten/Qk/qk.js#L431
- Population: Status ist "aktuell" (ursprünglich oder angesiedelt) oder potentieller Wuchsort; der letzte Populations-Bericht meldet aber "erloschen" und es gab seither keine Ansiedlung: https://github.com/barbalex/apf2/blob/master/src/components/Projekte/Daten/Qk/qk.js#L522
- Population: Status ist "erloschen", der letzte Populations-Bericht meldet aber "aktuell": https://github.com/barbalex/apf2/blob/master/src/components/Projekte/Daten/Qk/qk.js#L533
- Population: Status ist "erloschen" (ursprünglich oder angesiedelt); der letzte Populations-Bericht meldet "erloschen". Seither gab es aber eine Ansiedlung: https://github.com/barbalex/apf2/blob/master/src/components/Projekte/Daten/Qk/qk.js#L544
- Populations-Bericht ohne Jahr: https://github.com/barbalex/apf2/blob/master/src/components/Projekte/Daten/Qk/qk.js#L556
- Populations-Bericht ohne Entwicklung: https://github.com/barbalex/apf2/blob/master/src/components/Projekte/Daten/Qk/qk.js#L576
- Populations-Massnahmen-Bericht ohne Jahr: https://github.com/barbalex/apf2/blob/master/src/components/Projekte/Daten/Qk/qk.js#L596
- Populations-Massnahmen-Bericht ohne Entwicklung: https://github.com/barbalex/apf2/blob/master/src/components/Projekte/Daten/Qk/qk.js#L616
- Teilpopulation: Status ist "aktuell" (ursprünglich oder angesiedelt) oder potentieller Wuchsort; der letzte Teilpopulations-Bericht meldet aber "erloschen" und es gab seither keine Ansiedlung: https://github.com/barbalex/apf2/blob/master/src/components/Projekte/Daten/Qk/qk.js#L640
- Teilpopulation: Status ist "erloschen" (ursprünglich oder angesiedelt), Ansaatversuch oder potentieller Wuchsort; der letzte Teilpopulations-Bericht meldet aber "stabil" und es gab seither keine Ansiedlung: https://github.com/barbalex/apf2/blob/master/src/components/Projekte/Daten/Qk/qk.js#L651
- Teilpopulation: Status ist "erloschen" (ursprünglich oder angesiedelt), Ansaatversuch oder potentieller Wuchsort; der letzte Teilpopulations-Bericht meldet aber "abnehmend" und es gab seither keine Ansiedlung: https://github.com/barbalex/apf2/blob/master/src/components/Projekte/Daten/Qk/qk.js#L662
- Teilpopulation: Status ist "erloschen" (ursprünglich oder angesiedelt) oder potentieller Wuchsort; der letzte Teilpopulations-Bericht meldet aber "unsicher" und es gab seither keine Ansiedlung: https://github.com/barbalex/apf2/blob/master/src/components/Projekte/Daten/Qk/qk.js#L673
- Teilpopulation: Status ist "erloschen" (ursprünglich oder angesiedelt), Ansaatversuch oder potentieller Wuchsort; der letzte Teilpopulations-Bericht meldet aber "zunehmend" und es gab seither keine Ansiedlung: https://github.com/barbalex/apf2/blob/master/src/components/Projekte/Daten/Qk/qk.js#L684
- usw.

Hm. Vielleicht meinst du diesen hier:

- Teilpopulation mit Kontrolle (im Berichtjahr) aber ohne Teilpopulations-Bericht (im Berichtjahr): https://github.com/barbalex/apf2/blob/master/src/components/Projekte/Daten/Qk/qk.js#L913

...und/oder diesen hier:

- Teilpopulation mit Ansiedlung (vor dem Berichtjahr) und Kontrolle (im Berichtjahr) aber ohne Massnahmen-Bericht (im Berichtjahr): https://github.com/barbalex/apf2/blob/master/src/components/Projekte/Daten/Qk/qk.js#L926

Bitte schau dir die Liste der Kontrollen in https://github.com/barbalex/apf2/blob/master/src/components/Projekte/Daten/Qk/qk.js an und sag mir, welche nicht funktionieren.

**Comment by barbalex** [comment]
Und bitte: Wenn eine Kontrolle nicht funktioniert, sag mir auch, in welchem Fall sie scheitert, damit ich das konkret testen kann.

**Comment by barbalex** [comment]
Uups. Habe den Fehler gefunden. Lag am Umbau, den ich wegen des Speicher-Fehlers gemacht habe. Alles, was vom Berichtjahr abhängt, wird momentan nicht angezeigt. Ist in der Entwicklungs-Version korrigiert.

Die Entwicklungs-Version ist aber wegen eines grossen Umbaus momentan nicht stabil. Arbeite heftig daran. Kann aber noch ein paar Tage dauern.

**Comment by barbalex** [comment]
Die korrigierte Version ist jetzt live
