### ISSUE TITLE
Zu Population zoomen mithilfe gelbem Blümchen funktioniert nicht

### ISSUE THREAD

**Issue by alinemeyer** [barbalex/apf2#198]
Lieber Alex

Ich wollte zu einer angewählten Population zoomen mithilfe dem gelben Blümchen, leider funktioniert die Zoom-Funktion nicht mehr. Kannst du da helfen?
<img width="557" alt="bildschirmfoto 2018-11-30 um 09 12 17" src="https://user-images.githubusercontent.com/42208152/49276897-1760a100-f480-11e8-8e98-e447431612be.png">

**Comment by barbalex** [comment]
Danke für die Meldung. Ist behoben.

**Comment by alinemeyer** [comment]
Lieber Alex
Wenn ich eine Pop/Tpop im Strukturbaum anwähle erscheint leider kein gelbes Blümchen in der Karte. Vielen Dank für deine Hilfe! LG

**Comment by barbalex** [comment]
Ich hab's soeben für Pop und Tpop probiert und es klappt.

Mit welcher Pop bzw. Tpop klappt es nicht?

**Comment by alinemeyer** [comment]
Dies gilt nur wenn ich Beobachtungen zuordnen möchte. Wenn ich ganz normal eine neu Pop/Top erstellen möchte funktionierts. Habe ich aber auch noch Anderes angewählt wie z.B. Beobachtungen zugeordnet/nicht beurteilt etc klappte nicht mehr.

**Comment by barbalex** [comment]
Was ich nachvollziehen kann: Für Beobachtungen funktioniert es nicht. Lustigerweise aber für Zuordnungs-Linien. Das werde ich mal anschauen.

Für Tpop und Pop funktioniert es aber in meinen Tests immer. Auch wenn Beobachtungen angezeigt werden. Und wenn Zuordnen aktiviert ist.

Hast du allenfalls gemeint, dass man bei Beobachtungen nicht zur im Baum aktiven zoomen kann?

Oder funktioniert es für dich wirklich bei Pop/Tpop nicht? Falls ja, müsstest du mir beschreiben können, wie ich das provozieren kann. Sonst kann ich es nicht reparieren.

**Comment by barbalex** [comment]
Was verwirren könnte: Ist ein Karten-Filter erstellt, werden (nur) die von diesem erfassten Pop/Tpop/Beob gelb angezeigt und es kann auf sie gezoomt werden.

Solange ein Karten-Filter aktiv ist, werden die im Strukturbaum aktiven Objekte ignoriert.

**Comment by barbalex** [comment]
Aber ich nehme nicht an, dass du einen Karten-Filter gesetzt hattest.

**Comment by alinemeyer** [comment]
Das mit dem Karten-Filter ist ein guter Hinweis! Den hatte ich immer eingeschaltet. Wenn ich diesen rausnehme funktionierts
