### ISSUE TITLE
EK öffnen inkl Zählung

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#199]
Im Vergleich zu V1 müssen wir ja sehr viel mehr klicken, um an die Info einer EK zu kommen. Es wäre sehr praktisch, wenn beim Öffnen einer Kontrolle auch gleich die Zählung aufginge. Ich meine, wir hätten das eigentlich auch schon mal gewünscht?

Wir klicken halt schon sehr viel, und die Klicks gehen ja auch nicht so schnell auf (es dauert jeweils fast eine Sekunde - wenn man am Compi sitzt, dann ist das bei vielen Eingaben mit der Zeit schon seeehr langsam)

Oh, jetzt sehe ich gerade, dass mein gewünschtes Verhalten manchmal passiert, oft aber nicht. Weisst Du, an was es liegt?

**Comment by barbalex** [comment]
> dass mein gewünschtes Verhalten manchmal passiert, oft aber nicht

In meinen (kurzen) Tests hat es immer geklappt. Gibt es eine Methode, das nicht-Öffnen zu provozieren?

**Comment by csalzmann** [comment]
Lieber Alex
Der Issue hat sich erübrigt. Mittlerweile arbeite ich immer mit der Super-Funktion "alle öffnen", und dann ist auch alles paletti. 
Evtl ist der Fehler oben auch bei mir passiert, wenn ich manchmal auf den Pfeil statt auf den Text geklickt habe. Ich schliesse den Issue.
