### ISSUE TITLE
Layout - 3 Spalten aktiv Breite ändern?

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#20]
Wäre es möglich, dass man bei den 3 Spalten jeweils Breite selber einstellen kann? Kartenlayout ist mir z.B. im Verhältnis in der Breite oft zu klein. Oder könnte man jeweils auch Karte in separatem Fenster öffnen?

**Comment by barbalex** [comment]
Ziemlich sicher schon. Fehlt nur noch die Idee, wie machen

**Comment by barbalex** [comment]
Geeignetes Werkzeug: https://github.com/tomkp/react-split-pane

**Comment by barbalex** [comment]
Leider kann keines dieser Werkzeuge in einem Layout eingesetzt werden, in dem die verschiedenen Elemente dynamisch ein- und ausgeblendet werden können :-(

**Comment by barbalex** [comment]
...aber der Entwickler von https://github.com/leefsmp/re-flex arbeitet schon daran :-)

**Comment by barbalex** [comment]
Wow. Der Entwickler hat dieses Feature ergänzt. Es lebe open source :-)
Umgesetzt
