### ISSUE TITLE
Feldkontrolle kopieren funktioniert nicht

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#201]
Kontrolle wird zwar in Zwischenspeicher gelegt, einfügen geht aber nicht (es passiert einfach nichts).

![bildschirmfoto 2018-11-30 um 15 49 23](https://user-images.githubusercontent.com/6047564/49296070-93c2a680-f4b7-11e8-9187-96f87c8c9cf8.png)

**Comment by csalzmann** [comment]
OK. Habe gerade gemerkt, es funktioniert doch. Aber extrem verzögert. Beim obigen Bsp. hatte ich auf einmal 2 EKs von 2018 drin. Bei meinem nächsten Bsp. habe zuerst auch nichts gesehen, mit Reload wars dann da.
Dh, ohne Reload o.ä. geht die Funktion aktuell eigentlich nicht.

**Comment by barbalex** [comment]
Ist korrigiert. Danke für die Meldung
