### ISSUE TITLE
EKF Anzeige im Baum weiterhin mit Zählung

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#202]
Es wäre praktisch, wenn die EKFs im Baum links weiterhin, wie die Feldkontrollen, mit Zählung angezeigt werden. Dies zur Beurteilung der Entwicklung einer Population. 
![unbenannt](https://user-images.githubusercontent.com/6047564/49328329-06428d80-f56f-11e8-9ac5-c51c18b87459.JPG)

**Comment by barbalex** [comment]
Die Verwaltung von Kontrollen ist für EFK sehr kompliziert. Weil pro Aktionsplan vorgegeben wird, welche erfasst werden sollen. Und weil diese beim Öffnen des Formulars direkt neu geschaffen werden, damit die Freiwilligen nur noch das fertige Formular ausfüllen müssen.

Daher ist es nicht ratsam, die gleiche Funktionalität wie bei den Feldkontrollen zu bauen. Komplizierter als sehr kompliziert ist nur noch, wenn man das sehr komplizierte auf unterschiedliche Arten machen können soll...

Wenn es darum geht, eine Übersicht über alle Zählungen zu haben, würden wir die ev. besser anders bauen.

Z.B. ein Kontext-Menü, dass die dafür ideale Liste in einem Popup-Fenster öffnet? Oder ganz was anderes?

**Comment by csalzmann** [comment]
Vielleicht sollten wir das eh nochmals diskutieren. Für unsere Übersicht war das bisherige Layout viel angenehmer. Ich muss so viel zu viel scrollen, um die Infos von den EKs aus dem Formular zu erhalten.

**Comment by barbalex** [comment]
Ist beschlossen als:

> Knoten für EKF-Zählungen im Strukturbaum wieder anzeigen, ohne neu/löschen/bearbeiten

**Comment by barbalex** [comment]
ist implementiert

**Comment by csalzmann** [comment]
mega cool Alex, Danke!
