### ISSUE TITLE
Zoomen auf aktive TPop geht nicht mehr

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#203]
aktive TPop wird zwar im Kartenfenster angezeigt (gelb), aber man kann nicht drauf zoomen (es erscheint Verbotsschild beim Curser).

**Comment by barbalex** [comment]
Sorry, ich habe das Layertool massiv umgebaut, um Daten aller Ebenen erst zu laden, wenn sie eingeblendet werden...

Ist repariert.
