### ISSUE TITLE
BearbeiterIn setzen klappt nicht

### ISSUE THREAD

**Issue by barbalex** [barbalex/apf2#204]
Adrienne Frei hat gemeldet, dass es bei ihr nicht klappt:

> Auch mit allen Tricks, die du mir empfohlen hast, konnte ich mich nicht als Bearbeiterin in den Feldkontrollen eintragen

Sie benutzt Chrome.

Leider kann ich es nicht nachvollziehen.

**Comment by csalzmann** [comment]
Kann ich auch nicht nachvollziehen, klappt bei mir. Am besten am Montag mal mit Rebecca telefonieren.

**Comment by csalzmann** [comment]
Also Adrienne, nicht Du :)

**Comment by csalzmann** [comment]
Jetzt habe ich gerade auch diesen Fall!

Card. dentata, TPop 8.6. Ich wollte Bericht machen, da sah ich, dass bei 2008 kein Eintrag Bearbeiterin drin war. Ich dachte, das sei versehentlich gelöscht worden. Im Export bin ich aber als Bearbeiterin drin (obwohl in der Datenbank nichts angezeigt wird, das hab ich aber erst nachher geprüft). Ich also versucht, mich als Bearbeiterin zu setzen, und es klappt einfach nicht.

Zuerst werd ich nicht mal mehr aufgeführt in der Liste, dann je nachdem schon (es scheint wichtig zu sein, ob der Curser mal über die Scroll-Liste der Namen geht oder nicht). Dann erscheine ich wieder in der Liste, aber auch wenn ich mich anklicke, sieht man nachher keine Eintrag.

![bildschirmfoto 2018-12-07 um 09 42 57](https://user-images.githubusercontent.com/6047564/49637118-ca8f4400-fa04-11e8-9dda-036de78d7461.png)

Dann passiert auch noch folgendes. Ich wechsle zwischen den EKs 2008 und 2018, die EKs sind markiert, aber der Inhalt des Fensters wechselt nicht. 

![bildschirmfoto 2018-12-07 um 09 46 19](https://user-images.githubusercontent.com/6047564/49637237-18a44780-fa05-11e8-93b3-d2f822dc5f58.png)

Ich mach jetzt mal wieder Cache leeren, melde mich dann wieder.

**Comment by barbalex** [comment]
O.k.,  ich kann komisches Verhalten nachvollziehen. Ich schau das an.

**Comment by csalzmann** [comment]
Danke!!!

Noch meine Erfahrung nach dem Cache: ich bin immer noch nicht als Bearbeiterin drin.

Und im erneuten EK-Export bin ich auch nicht mehr drin! Das rumgeklicke hat mich also gelöscht, wenn ich nichts gemacht hätte, wär ich wahrscheinlich drin geblieben (im Export vom 30.11.2018 war das noch so).

Dafür konnte ich mich nach dem Cache jetzt wieder einfügen (immerhin). Aber  im anschliessenden Export bin ich aber immer noch nicht drin. ??

**Comment by barbalex** [comment]
Das Problem mit der Bearbeiterin ist vermutlich sekundär: Die Liste zeigt den im gerade aktiven Datensatz enthaltenen Bearbeiter nicht zur Auswahl an. Das Problem in diesem Fall: _der aktive Datensatz ist nicht der richtige!_

Ich kann das provozieren, indem ich:

* Feldkontrolle 1 wähle (der richtige Datensatz wird angezeigt)
* Feldkontrolle 2 wähle (der richtige Datensatz wird angezeigt)
* Feldkontrolle 1 wähle: _nun wird der Datensatz von Feldkontrolle 2 angezeigt_
* Feldkontrolle 2 wähle (der richtige Datensatz wird angezeigt)
* Feldkontrolle 1 wähle (der richtige Datensatz wird angezeigt)
* ...

Es wurde also jeweils beim erstmaligen zurückwechseln zum selben der falsche Datensatz angezeigt. Üble Sache :-(

Ursache scheint eine Änderung zu sein, die ich kürzlich wegen des Speicherproblems vollzogen habe (der davon ausgelöste Umbau war massiv).

Die gute Nachricht: Die verwendete Technologie wurde soeben weiter entwickelt. Ich bin daher sowieso gerade daran, diesen Aspekt in allen Formularen wieder anzupassen. Und die neue Methode hat den oben beschriebenen Fehler nicht.

Ich priorisiere nun diese Anpassung, damit in wenigen Stunden ein Update den Fehler in allen Formularen korrigieren kann.

**Comment by csalzmann** [comment]
Bei den TPops ist es jetzt auch so. Ich wähle eine TPop aus, aber im Fenster nebenan wird nicht unbedingt die angewählt TPop angezeigt. Das ist supertricky, weil wenn man das nicht bemerkt, macht man "Korrekturen" (habe ich gerade gemacht)..

**Comment by barbalex** [comment]
O.k., in den allermeisten Formularen ist der Fehler korrigiert (also auch Tpop). Neue Version soeben live gesetzt. Ich stelle jetzt noch sicher, dass nirgends mehr die alte Art verwendet wird.

**Comment by barbalex** [comment]
Alles korrigiert. Ich nehme an, der ursprüngliche Fehler (BearbeiterIn wählen) ist damit auch korrigiert und schliesse den Issue
