### ISSUE TITLE
Datum eingeben funktioniert nicht

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#205]
Lieber Alex

Ich habe gerade in der Test-Art Abies alba eine neue Feldkontrolle erstellt und das eingegebene Datum ist wieder verschwunden nachdem ich zuerst auf die Zählungen geklickt habe und danach zur Feldkontrolle zurückgekehrt bin. 
Auf MacOS, Chrome.

**Comment by barbalex** [comment]
Ich kann das nicht nachvollziehen. Bei mir funktioniert es.

Was mir aufgefallen ist: Nachdem man das Datum erfasst, wird nicht direkt das Jahr angezeigt. Das habe ich soeben korrigiert und live geschaltet. Aber sonst klappt es bei mir.

**Comment by rebeccakurz** [comment]
Nach etwa 5 Versuchen, wo das Datum immer wieder verschwunden ist, ist es jetzt dringeblieben. (bei zwei verschiedenen tpops innerhalb der gleichen pop, Testart abies alba). Dann habe ich  nochmals eine neue feldkontrolle erstellt, hier ging es wieder nicht. Das Datum ist nicht dringeblieben, das Jahr wurde nicht automatisch ausgefüllt.

**Comment by barbalex** [comment]
Wenn ich könnte, würde ich bei dir nachschauen, wie gross der Arbeitsspeicherverbrauch ist.

Verhalten, das nicht der Programmierung entspricht, könnte dadurch ausgelöst werden.

Leider ist uns das auf deinem Computer via Telefon mit keiner der Methoden geglückt, die auf meinem Windows PC und Mac PC funktionieren. Weil dein virtuelles Windows Tasten(-kombinationen) anders belegt und auch noch das Öffnen von Fenstern beeinflusst.

**Comment by barbalex** [comment]
Ich gehe mal davon aus, dass die Ursache dieser Issue war: https://github.com/barbalex/apf2/issues/204#issuecomment-445176630

...und schliesse daher
