### ISSUE TITLE
Export Kontrollen fehlt Bearbeiter

### ISSUE THREAD

**Issue by alinemeyer** [barbalex/apf2#206]
Hoi Alex
Gerne möchte ich meine Eingaben in der DB prüfen, ob ich nichts vergessen habe wie z.B die Gemeinde etc. Ich habe dazu die Excel Liste unter Exporte-Kontrollen heruntergeladen. Doch leider erkenne ich darin nicht wo ich Änderungen gemacht habe, bzw neue Pops/Tpops erstellt habe. Ist es möglich dies noch hinzuzufügen? Vielen Dank!

**Comment by barbalex** [comment]
Dafür ist das Feldpaar "changed" und "changed_by" nicht konzipiert. Ich nehme an, du beziehst dich darauf? Jedenfalls könnte es nicht zuverlässig dafür benutzt werden, weil es immer nur die letzte Änderung beinhalten sollte, egal was geändert wurde.

In apflora.ch gibt es keine echte Nachvollziehbarkeit von Änderungen.

Das wäre ein sehr komplexes und teures Feature. Banken leisten sich das zum Beispiel. Aber deren Budget ist ein bisschen höher...

Abgesehen davon: Wenn jede Änderung aufgezeichnet wird, ist es auch sehr aufwändig diese Zig-Tausenden von Datensätzen vernünftig auszuwerten, wenn man sich - wie du jetzt offenbar - eine Übersicht schaffen will.

**Comment by barbalex** [comment]
Artverantwortliche könnten Änderungen in Datensätzen ihrer Art auswerten. Das Problem bei dir ist wohl eher, dass du quer durch Arten hindurch arbeitest?

**Comment by barbalex** [comment]
Zusätzlich: in der neuen Version habe ich veranlasst, dass "changed" und "changed_by" serverseitig ausgefüllt werden.

Bei "changed_by" sollte der Server den Namen benutzen, der mit der Anmeldung hätte übermittelt werden sollen (extra für diesen Zweck, hat keine andere Bedeutung). Das hat aber offenbar nicht geklappt. Muss mich dem mal widmen, wenn ich Zeit habe.

**Comment by csalzmann** [comment]
Hoi Alex. Ich habe Aline da drauf gebracht. Während "changed" immer mit Datum ausgefüllt wird, ist völlig unklar, wenn "changed by" ausgefüllt wird. Ja, wäre lässig, Du könntest das wieder hinbringen. Wenn Du dann Zeit hast.

**Comment by barbalex** [comment]
Mir fällt nur auf, dass alle 6000 Populationen ein "changed" datum aus diesem Jahr haben. Das heisst, es gibt vermutlich Vorgänge, welche Speicherungen auslösen und damit die automatische Dokumentation, die ihr nicht willentlich auslöst. Ihr habt ja kaum alle Datensätze geändert.

Uhm. Offensichtlich wurden sie alle am 18.4.2018 geändert. Da habe ich offensichtlich etwas an der Datenstruktur angepasst, worauf alle Werte für "changed" und "changed_by" neu berechnet wurden.

Die server-seitige Lösung scheint sich also nicht zu bewähren :-(

**Comment by barbalex** [comment]
O.k., in der Entwicklungs-Version werden ab sofort bei allen Änderungen die Namen des Benutzers in der Anwendung (zusammen mit den übrigen geänderten Werten) in `changed_by` gespeichert.

Das wird euch leider erst ab nächstem Jahr wieder etwas nützen :-(

**Comment by csalzmann** [comment]
Und Du machst das überall, bei TPop, Massnahmen und EKs? Vielen Dank!

**Comment by barbalex** [comment]
Ihr könnt es so testen:

1. Daten ändern
2. Exportieren
3. Nachschauen bei den geänderten
