### ISSUE TITLE
2019: Alle EKF-Formulare direkt aus AP-Fora-DB drucken

### ISSUE THREAD

**Issue by jmenzi** [barbalex/apf2#207]
Lieber Alex

Damit wir unsere alte Filemaker-Datenbank mit den EKF-Protokollblättern aufheben können, brauchen wir in der Flora-DB die Möglichkeit alle EKF-Protokollblätter auf einmal drucken zu können (quasi mit einem Knopfdruck). Könntest du das Anfang 2019 anschauen und implementieren? Wir versenden die Protokollblätter in der Regel Anfang Februar. 

Herzlichen Dank. Gruss, Jasmin

**Comment by barbalex** [comment]
Klar, gerne, im Rahmen des Budgets 2019.

> alle EKF-Protokollblätter auf einmal drucken

Sind das alle EKF-Protokollblätter:

* pro Projekt (für alle Freiwilligen aller Aktionspläne von apflora)
* pro Aktionsplan
* pro Freiwillige und Aktionsplan
* pro Freiwillige (für alle Aktionspläne, bei denen sie mithilft)

...oder sonst etwas, an das ich nicht gedacht habe?

**Comment by csalzmann** [comment]
Ja, wir müssen sicher noch drüber reden, wie wir diejenigen Kontrollen kennzeichnen, für welche Protokollblätter ausgedruckt werden (es gibt ja auch noch die Frequenz, ist wahrscheinlich ein Teil der Lösung?). Und wie viele Expemplare, für manche tatsächlich 2.

Ist einfach schon mal zum Überlegen. Und gut zu wissen, dass es grundsätzlich möglich ist!

**Comment by barbalex** [comment]
> für welche Protokollblätter ausgedruckt werden (es gibt ja auch noch die Frequenz, ist wahrscheinlich ein Teil der Lösung?)

Das tönt, als ob ihr wollt, dass _automatisch oder per Knopfdruck_, aufgrund der Frequenz und dem Zeitpunkt der letzten Kontrolle Freiwilligen-Kontrollen geschaffen werden.

Denn gedruckt würden schlicht und einfach alle existierenden Freiwilligen-Kontrollen für das betreffende Jahr (bzw. diejenigen, die noch kein Jahr haben - denn das Datum wird ja eben von den Freiwilligen erfasst). Und wie oben bemerkt: pro Projekt, Aktionsplan, Freiwillige oder wie das eben geschehen soll.

Ich bin bisher davon ausgegangen, dass diese Kontrollen von euch vorbereitet, d.h. geschaffen werden.

Das automatische Schaffen von Freiwilligen-Kontrollen aufgrund der Frequenzen ist sicher möglich aber eine komplexe Funktion, die wohl ein paar Stunden Arbeit erfordert:

* U.a. ist sie darum komplex, weil schon EKF ohne Jahr existieren können und in diesem Fall sollten keine neuen geschaffen werden. (Wenn das aber vergessene ekf des Vorjahrs sind, könnte es durchaus sein, dass die  Zähleinheiten nicht mehr den aktuellen entsprechen - also müsste die Funktion dann ev. bewusst die Einheiten ändern?)
* Es könnte auch sein, dass eine Kontrolle des Vorjahrs erfasst wurde, d.h. alle übrigen Angaben erfasst, aber das Datum vergessen
* Ev. gibt es Fälle, in denen ihr die Zähleinheiten wechseln wollt?
* Es kann auch sein, dass keine Frequenz erfasst wurde
* Könnte auch sein, dass die letzte Kontrolle nicht stimmt, weil bei dieser Tpop etwas schief lief als die übrigen Tpop der Pop kontrolliert wurden. Und dass daher die automatische Funktion für diese Tpop eine EKF schaffen würde, die man nicht will, wenn man z.B. alle Tpop einer Pop im selben Jahr kontrollieren will? Bloss so Ideen

Ich bin daher nicht sicher, ob uns diese Funktion nicht (über-)fordern würde...

**Comment by barbalex** [comment]
Ist beschlossen als:
- neues Feld in tpop: "ekf_kontrolleur"
- Befehl, um alle im aktuellen Jahr benötigten ekf-Formulare einer Kontrolleurin neu zu schaffen (soweit noch nicht erfolgt) und zu drucken
- Diesen Befehl bei Benutzern platzieren. Nur aktiv, wenn es tpops gibt, in denen der Benutzer als "ekf_kontrolleur" erfasst ist und die im aktuellen Jahr kontrolliert werden sollen

**Comment by barbalex** [comment]
Ist umgesetzt

**Comment by rebeccakurz** [comment]
Hoi Alex
Vielen Dank für die Umsetzung. Ich habe das heute mal ausprobiert und das klappt ganz gut. 
Ich habe noch eine Anmerkung für das Layout: Die Angabe, ob der Plan ergänzt wurde, ist ja in der FloraDB voreingestellt auf "Nein". Und das erscheint dann halt auch so im Ausdruck. 
Kannst du das ändern, so dass für den Druck die Voreinstellung nicht drauf ist? Oder muss man die Voreinstellung ganz rausnehmen?

Dann ist mir noch aufgefallen, dass auf dem Ausdruck auch die Kopf- und Fusszeilen drauf sind. Aber das kann man dann bei den Druckeinstellungen ändern, habe ich gerade gemerkt

**Comment by barbalex** [comment]
In Version 1.19.33 wird "Plan ergänzt: nein" im Ausdruck nicht mehr angezeigt

**Comment by rebeccakurz** [comment]
Hoi Alex
Vielen Dank für diese Anpassungen. 
Nun habe ich noch gemerkt, dass leider das Bild der zu kontrollierenden Pflanze nicht gedruckt wird. 
(Auf dem Forlular ist es zu sehen, aber danach in der Druckvorschau und auf dem Ausdruck nicht mehr.)

**Comment by barbalex** [comment]
Hoi Rebecca

Bitte öffne dafür einen neuen Issue. Das hat mir dem ursprünglichen Zweck dieses Issues kaum mehr etwas zu tun (Möglichkeit, alle EKF-Formulare eines Kontrolleurs zu drucken). Es ist nicht einmal klar, ob es nur passiert, wenn man ALLE EKF-Formulare eines Kontrolleurs druck. Könnte ja sein, dass dieser Fehler auch auftritt, wenn man einzelne EKF-Formulare druckt.

LG, Alex
