### ISSUE TITLE
Beobachtungen - Neue Pop erstellen funktioniert nicht

### ISSUE THREAD

**Issue by alinemeyer** [barbalex/apf2#208]
Lieber Alex
Ich bin zurzeit daran die Beobachtungen zuzuordnen. Wenn ich bei den Beobachtungen rechts drauf klicke im Strukturbaum sollte ich eine neue Pop erstellen können. Dies funktioniert zur Zeit nicht. Kannst du da was machen? LG

**Comment by barbalex** [comment]
Hab's soeben probiert und es hat geklappt.

Mit welcher Beobachtung klappt es nicht?

**Comment by alinemeyer** [comment]
Habe es nochmals an einem anderen PC probiert, auch nach mehrmaligem Cache leeren und neu laden geht nichts (das selbe auch mit den gelben Blümchen). Zurzeit arbeite ich an den Beobachtungen von Aristolochia clematitis. Merkwürdigerweise hat es z.B. bei denen von Potentilla leucopolitana geklappt.

**Comment by rebeccakurz** [comment]
Habe es soeben nochmals versucht und dabei festgestellt: Es klappt nicht mit einer Beobachtung aus dem Baumann-Manuskript (0001.01.01: Baumann-Manuskript (FloZ); siehe Screenshot) aber es klappt ohne Probleme mit einer anderen Beobachtung (z.B. 1839.01.01 Jäggi (FloZ))
![bildschirmfoto 2018-12-06 um 08 34 58](https://user-images.githubusercontent.com/30288503/49568723-1fae5580-f932-11e8-8192-f916e0de7414.png)

Könnte es damit etwas zu tun haben?

**Comment by rebeccakurz** [comment]
Habe es bei Aristolochia clematits und Potentilla leucopolitana versucht und bei beiden war es gleich.

**Comment by barbalex** [comment]
Das lag daran, dass in diesen Fällen kein Datum für die Beobachtung existiert. Das Skript wollte die "bekannt Seit" Felder setzen, konnte es aber nicht. Und stoppte ohne Fehlermeldung.

Ist korrigiert. Danke für die Meldung.

**Comment by alinemeyer** [comment]
Vielen vielen Dank es funktioniert wieder !! :)
