### ISSUE TITLE
TPop Fenster, Feld Bemerkungen verschieben

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#210]
Bitte das Bemerkungsfeld oberhalb der Frequenzen plazieren. 

![bildschirmfoto 2018-12-06 um 13 37 34](https://user-images.githubusercontent.com/6047564/49584635-35387500-f95c-11e8-8b55-255c98fe5eb5.png)

**Comment by barbalex** [comment]
gemacht
