### ISSUE TITLE
Frage Sortierung Issues

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#212]
Kann man die Issues nach dem letzten Kommentar sortieren? 

Es ist sicher super, wenn die Issues grundsätzlich nach Nr. sortiert sind, dann findet man eine bestimmte Nr.

Aber wenn man am Arbeiten ist und es eigentlich wichtig wäre, schnell zu wissen, was wo bei den Issues wieder läuft, wäre es eigentlich angenehmer, man würde immer das Issue mit dem letzten Kommentar zuoberst sehen. Bei den emails verlieren wir eben fast den Überblick weil es so viele sind.

**Comment by barbalex** [comment]
Ja, das gibt es (folgendes bild ev. nur auf github sichtbar): 
<img width="896" alt="2018-12-07_12h14_22" src="https://user-images.githubusercontent.com/669783/49644755-b9046700-fa19-11e8-9805-ff936e30081a.png">

**Comment by csalzmann** [comment]
Danke!
