### ISSUE TITLE
Qualitätskontrolle, anpassen

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#213]
Cardamine, TPop 11.1

Status unsicher, Potenz. Wuchsort (Grund: Artansprache unsicher)

Die EK wurde trotzdem eingetragen: 2007 1 Pflanze, im Bemerkungsfeld vegetativ bestimmt

Das ist eigentlich alles richtig so, ergibt aber eine Fehlermeldung. 

![bildschirmfoto 2018-12-07 um 11 09 33](https://user-images.githubusercontent.com/6047564/49641514-a2a5dd80-fa10-11e8-8f36-c379885160d8.png)

Könntest Du bitte die Qualitätskontrolle anpassen?

Es darf eine pos. EK geben, wenn Status Pot. Wuchsort ist und zugleich Status unsicher angekreuzt ist

**Comment by barbalex** [comment]
Habe in der Abfrage `AND apflora.tpop.status_unklar = false` ergänzt
