### ISSUE TITLE
Qualitätskontrolle, hurra 

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#214]
Lieber Alex
Eine Anfrage, falls mal nichts mehr sonst zu tun ist.. Du hattest uns immer mit einem netten Spruch belohnt, wenn die Qualitätskontrolle ohne Fehler war. Schreibst Du wieder was Nettes rein? So ist man sicher, dass sie gerechnet hat und freut sich doch dann tatsächlich jedes Mal :)

**Comment by barbalex** [comment]
Das ist irgendwie verloren gegangen. 

Ist wieder da. Siehe hier: https://apflora.ch/Projekte/e57f56f4-4376-11e8-ab21-4314b6749d13/Aktionspl%C3%A4ne/6c52d1f6-4f62-11e7-aebe-dfe3eaf910cc/Qualitaetskontrollen?feldkontrTab=entwicklung&projekteTabs=tree&projekteTabs=daten

**Comment by csalzmann** [comment]
Danke:)!!
