### ISSUE TITLE
Probleme bei Beobachtungen zuordnen

### ISSUE THREAD

**Issue by alinemeyer** [barbalex/apf2#215]
Lieber Alex
Seit heute morgen treten verschiedene Probleme auf beim Beobachtungen zuordnen:
- Wähle ich im Strukturbaum eine Beobachtung an und möchte eine neue Pop erstellen, erscheint die neue Pop oben angefügt. Vorher wurde aktualisiert und man hatte direkt die geöffnete neue Pop vor sich im Strukturbaum
- Klicke ich in der Karte auf eine Beobachtung und möchte sie in einem neuen Tab öffnen, wird die Beobachtung nicht in jedem Fall im Strukturbaum angewählt, ich muss sie dann teilweise trotzdem im Strukturbaum suchen
- Habe ich eine neue Pop erstellt zu einer Beobachtung, kann ich keine 2. TPop mehr erstellen.

Vielen Dank für deine Hilfe, LG

**Comment by alinemeyer** [comment]
wenn ich im Strukturbaum eine neue Pop aus einer Beobachtung erstellen möchte, wird die neue Pop nicht nur nach oben gestellt, sondern die Koordinaten stimmen ebenfalls nicht. es nimmt die Koordinaten der Population welche ich vorher erstellt habe.

**Comment by alinemeyer** [comment]
wenn ich in der Karte eine Beobachtung mit dem Kartenfilter anwählen möchte, werden jetzt nur noch Pop/TPop angewählt, aber keine Beobachtungen mehr

**Comment by barbalex** [comment]
Hoi Aline

Bei der Schaffung neuer Pop und Tpop aus einer Beobachtung wurde plötzlich die Jahreszahl als Text erkannt, worauf die Daten-Anfüge-Abfrage scheiterte. Keine Ahnung, wieso das plötzlich änderte. Ist behoben.

LG, Alex

**Comment by barbalex** [comment]
> Wähle ich im Strukturbaum eine Beobachtung an und möchte eine neue Pop erstellen, erscheint die neue Pop oben angefügt. Vorher wurde aktualisiert und man hatte direkt die geöffnete neue Pop vor sich im Strukturbaum

Das kann ich so nicht nachvollziehen. Aufgrund oben beschriebenen Fehlers wurde einfach keine neue Pop und Tpop geschaffen, damit auch die Beobachtung nicht zugeordnet.

**Comment by barbalex** [comment]
> Klicke ich in der Karte auf eine Beobachtung und möchte sie in einem neuen Tab öffnen, wird die Beobachtung nicht in jedem Fall im Strukturbaum angewählt, ich muss sie dann teilweise trotzdem im Strukturbaum suchen

Das kann ich nicht nachvollziehen.

**Comment by barbalex** [comment]
> Habe ich eine neue Pop erstellt zu einer Beobachtung, kann ich keine 2. TPop mehr erstellen.

Das kann ich nicht nachvollziehen. 

Wie provoziert man das?

**Comment by barbalex** [comment]
> wenn ich im Strukturbaum eine neue Pop aus einer Beobachtung erstellen möchte, wird die neue Pop nicht nur nach oben gestellt, sondern die Koordinaten stimmen ebenfalls nicht. es nimmt die Koordinaten der Population welche ich vorher erstellt habe

Das kann ich nicht nachvollziehen. Wie oben beschrieben wurden gar keine neuen Pop und Tpop erstellt, damit hätte das nicht passieren können sollen.

**Comment by barbalex** [comment]
Du hast oben 5. Issues im selben Issue beschrieben. Ich verliere völlig die Übersicht. Sorry, bin nur ein simpler Mann, der nur ein Ding aufs Mal machen kann ;-)

Bitte mach jeweils pro Problem einen Issue. Dann kann ich die Issues systematisch durcharbeiten und jeder, der es anschaut, versteht, was passiert.

**Comment by barbalex** [comment]
> wenn ich in der Karte eine Beobachtung mit dem Kartenfilter anwählen möchte, werden jetzt nur noch Pop/TPop angewählt, aber keine Beobachtungen mehr

Ist repariert.

Diese Funktion war einer der Änderungen zum Opfer gefallen, um zu verhindern, dass das für den Daten-Zwischenspeicher verwendete Werkzeug den Zwischenspeicher wachsen lässt, was zu Langsamkeit und Abstürzen führte.

Danke für die Meldung.

**Comment by barbalex** [comment]
Ich schliesse den Issue, weil alles, was ich nachvollziehen kann repariert ist. Falls etwas nicht funktioniert: Bitte einen neuen Issue öffnen.
