### ISSUE TITLE
Beobachtungen - kein gelbes Blümchen nach zoomen

### ISSUE THREAD

**Issue by alinemeyer** [barbalex/apf2#216]
Lieber Alex
Ich danke dir ganz herzlich fürs Beheben der Probleme bei den Beobachtungen! Etwas Kleines ist mir eben noch aufgefallen:
- Wenn ich im Strukturbaum eine Beobachtung anwähle wird das Blümchen dort gelb. Zoome ich zu dieser Beobachtung erscheint diese auch im Kartenausschnitt, aber das Blümchen in der Karte ist nicht gelb markiert. Vielen Dank für deine Hilfe!!!
LG

**Comment by alinemeyer** [comment]
Dies geschieht nicht nur bei den Beobachtungen, sondern auch bei Tpops
![bildschirmfoto 2018-12-12 um 13 06 18](https://user-images.githubusercontent.com/42208152/49869495-d322b880-fe10-11e8-9259-e81a27d7cd17.png)

**Comment by barbalex** [comment]
Das geschah in allen Layers. Ist repariert. Danke für die Meldung
