### ISSUE TITLE
Flora Beobachtung, Verifikation

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#218]
Wäre es nicht noch gut, wenn man irgendwo festhalten könnte, ob man die Verifikation auch an Infoflora geschickt hat? Das sieht man den Meldungen jetzt ja nicht an.

**Comment by barbalex** [comment]
Muss das auswertbar sein oder reicht es, wenn ihr das ins Bemerkungsfeld schreibt?

**Comment by csalzmann** [comment]
Auswertbar fänd ich schon gut. Ist das mega kompliziert?

**Comment by barbalex** [comment]
Nein. Aber es bedingt ein Feld mehr.

Was genau sollte dokumentiert sein?

* Dass Infoflora informiert wurde (=> neues Feld "infoflora_informiert", Feldtyp: ja/nein)
* Wann Infoflora informiert wurde (=> neues Feld "infoflora_informiert", Feldtyp: Datum)
* anderes/mehr
* Sollte "infoflora_informiert" automatisch gesetzt werden, wenn ein Mail generiert wird? (ist relativ gut möglich)

**Comment by barbalex** [comment]
Ich warte mit der Umsetzung, bis meine obige Frage beantwortet wurde

**Comment by csalzmann** [comment]
Feld: infoflora informiert: ja/nein und Datum (nein ist Standard-Wert)

Bin nicht sicher, ob automatisch infoflora_informiert gesetzt werden soll. Das mail muss man ja auch noch abschicken.. :)

Es lohnt sich auf jeden Fall nicht, aus jeder Beobachtung eine mail zu machen, deshalb muss man auch manuell ja/nein wählen können. Ich hatte mehrere Beobachtungen vom gleichen Ort und Art zu melden, da wäre es sinnlos gewesen, x mal die gleiche mail zu verschicken.

**Comment by barbalex** [comment]
Ich glaube nicht, dass es sinnvoll ist, _beide_ Felder zu ergänzen:
- informiert ja/nein
- informiert Datum

Denn wenn ihr wissen wollt, _wann_ informiert wurde, muss ohnehin ein Datum erfasst werden. Und existiert ein Datum, ist klar, dass informiert wurde.

Existieren beide Felder, ist das bloss:
- mehr Arbeit
- Möglichkeit für widersprüchliche/unklare/unvollständige Aussagen (ja ohne Datum, nein mit Datum, Datum ohne Wert in ja/nein)

Ohne deinen Widerspruch werde ich daher nur das Datum ergänzen. Und werde es gemäss deiner Antwort nicht automatisch ausfüllen, wenn ein Mail generiert wird.

**Comment by barbalex** [comment]
in v1.15.0 umgesetzt
