### ISSUE TITLE
Eierlegende Wollmilchsau defekt

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#219]
Der Export/Art funktioniert nicht.

![bildschirmfoto 2018-12-12 um 10 48 48](https://user-images.githubusercontent.com/6047564/49861247-b8921480-fdfb-11e8-8fd3-c93529049f9c.png)

**Comment by barbalex** [comment]
Repariert.

Danke für die Meldung.

**Comment by rebeccakurz** [comment]
Lieber Alex

Ich wollte gerade den Export "Eier-legende Wollmilchsau" für eine Art ausprobieren und es hat wieder eine Fehlermeldung gegeben:
![bildschirmfoto 2018-12-13 um 07 34 23](https://user-images.githubusercontent.com/30288503/49920234-cd2ce600-fea9-11e8-9d49-b90fd0387a0c.png)
![bildschirmfoto 2018-12-13 um 07 36 02](https://user-images.githubusercontent.com/30288503/49920245-d28a3080-fea9-11e8-92dd-e193c694e839.png)
Ich habe es für zwei verschiedene Arten ausprobiert. 
Könntest du das nochmals anschauen?

Vielen Dank und liebe Grüsse
Rebecca

**Comment by barbalex** [comment]
Ich habe vergessen, den Daten-Server neu zu starten. Die Software war angepasst, aber ohne Neustart des Daten-Servers kennt er die neuen Abfragen noch nicht...

Ist korrigiert

**Comment by rebeccakurz** [comment]
Super, danke!
