### ISSUE TITLE
Kopieren von Erfolgskontrollen

### ISSUE THREAD

**Issue by jmenzi** [barbalex/apf2#22]
Es wird eine Fehlermeldung angezeigt: Code 404. Die Erfolgskontrolle wird zwar in der Zwischenablage gespeichert, kann aber nicht eingefügt werden.

**Comment by barbalex** [comment]
hm. Das passiert in der Entwicklungsversion nicht. Ich muss das nochmals testen:

- nach dem nächsten Update der api
- falls es dann immer noch passiert: Wenn v2 nicht mehr in einem Unterverzeichnis läuft

**Comment by barbalex** [comment]
juhui, scheint nach dem gestrigen Update auch auf dem Server zu funktionieren
