### ISSUE TITLE
Export Beobachtungen funktioniert nicht

### ISSUE THREAD

**Issue by alinemeyer** [barbalex/apf2#220]
Lieber Alex
Der Export " Alle Beobachtungen von Arten aus apflora.ch, Nutzungsbedingungen der FNS beachten" funktionert leider zur Zeit nicht.  Die DB stürzt ab, bevor sie den Export öffnen kann.

**Comment by barbalex** [comment]
Uhm ja, das sind auch 500'000 Datensätze. Zusätzlich: mit JSON-Daten, weil ihre Struktur unterschiedlich sein kann. Ist wohl wie bei der eierlegenden Wollmilchsau: klappt nur unter optimalen Bedingungen.

Ausserdem ist sie gerade wegen der JSON kaum nützlich. Ich hätte den Export besser nicht angeboten.

**Comment by barbalex** [comment]
...und die Sache mit den Nutzungsbedingungen macht diesen Export auch nicht weniger heikel...

**Comment by csalzmann** [comment]
Ui je! Vielleicht hilft es, wenn ich Dir sage, warum wir den Export möchten. 
Einerseits Übersicht, wieviele Beobachtungen noch zuzuordnen sind.
Andererseits Plausibilitätskontrolle bei den Zuordnungen in Tabellenform, da kann man natürlich viel schneller drüber gehen als wenn man alle TPops einzeln aufmachen muss. Vielleicht lässt sich ja das eine oder andere machen.

**Comment by barbalex** [comment]
> Einerseits Übersicht, wieviele Beobachtungen noch zuzuordnen sind

Das sieht man sehr gut im Strukturbaum. Was braucht ihr, das darüber hinaus geht?

> Andererseits Plausibilitätskontrolle bei den Zuordnungen in Tabellenform, da kann man natürlich viel schneller drüber gehen als wenn man alle TPops einzeln aufmachen muss

Das wären nur die zugeordneten. Diese Datenmenge lässt sich gut handhaben. Welche Felder/Informationen müsstet ihr haben?

**Comment by csalzmann** [comment]
Beobachter
Datum
Genauigkeitsangabe
Fundort
Fundortbeschreibung
Anz. Meter Entfernung von zugeordneter TPop

**Comment by csalzmann** [comment]
Dann bleiben wir mal bei den zugeordneten, oder?

**Comment by barbalex** [comment]
übrigens: jetzt weiss ich auch, wieso heute Morgen die CPU des Servers heiss liess. Diese Abfrage führte dazu, dass sie stundenlang auf 100% lief, biss ich die Datenbank neu gestartet habe. Muss wohl die existierende Abfrage entfernen.

**Comment by barbalex** [comment]
Ich habe umgesetzt:

* zugeordnete Beobachtungen
* nicht zuzuordnende Beobachtungen

Das kann der Server machen.

**Comment by barbalex** [comment]
Bei obigen Abfragen habe ich mitgeliefert, was ich kann. 

Nicht geliefert werden kann:

* Genauigkeitsangabe
* Fundort
* Fundortbeschreibung

Grund: Es gibt keinen anerkannten Standard (welche Informationen mit welchen Feldnamen geliefert werden müssen) für Beobachtungen, an den sich alle halten.

Damit apflora unkompliziert alle Beobachtungen verarbeiten kann, egal aus welcher Quelle, werden die Originaldaten im JSON-Format im Feld "data" gespeichert.

Beim Import werden ein paar grundlegende Informationen daraus extrahiert und in die Felder "datum", "autor", "x", "y" geschrieben.

Man könnte die Daten des Felds "data" exportieren, das würden dann z.B. so aussehen:

```json
{
    "A_NOTE": "2014",
    "ESPECE": "Aceras anthropophorum (L.) W. T. Aiton",
    "J_NOTE": "0",
    "M_NOTE": "0",
    "PH_SOL": null,
    "CO_PAYS": "",
    "MENACES": null,
    "MESURES": null,
    "NO_ISFS": 900,
    "NO_NOTE": null,
    "REM_NOM": null,
    "REM_SOL": null,
    "Raum_ZH": "Glattfelden",
    "STATION": null,
    "TY_NOTE": "O",
    "COUV_EAU": null,
    "COUV_TOT": null,
    "DeckBaum": null,
    "REM_NOTE": "knapp blühend (Blüten erst vereinzelt geöffnet)",
    "SUBSTRAT": null,
    "ABONDANCE": null,
    "CO_CANTON": "",
    "CO_MILIEU": null,
    "DeckKraut": null,
    "ID_TEMOIN": null,
    "LUTTE_REM": null,
    "PRESENCE_": null,
    "TY_TEMOIN": null,
    "AGREGATION": null,
    "COUV_CRYPT": null,
    "COUV_ROCHE": null,
    "COUV_SOLNU": null,
    "DEF_CUSTOM": null,
    "DeckKlasse": null,
    "EXPOSITION": null,
    "EX_HERBIER": null,
    "HERBIER_WS": null,
    "INTRODUIT_": "N",
    "LUMINOSITE": null,
    "LUTTE_DATE": null,
    "LUTTE_TYPE": null,
    "PHENOLOGIE": null,
    "Projekt_ZH": "Zürcher Unterland",
    "COUV_ALGUES": null,
    "COUV_ARBRES": null,
    "CO_MILIEU_2": null,
    "CO_MILIEU_3": null,
    "DeckStrauch": null,
    "HAUTEUR_MOU": null,
    "INCLINAISON": null,
    "NOM_COMMUNE": null,
    "ALTITUDE_INF": 0,
    "ALTITUDE_SUP": 0,
    "COUV_LICHENS": null,
    "COUV_MOUSSES": null,
    "DEPOT_TEMOIN": null,
    "DETERMINAVIT": null,
    "HAUTEUR_LICH": null,
    "NOM_ORIGINAL": null,
    "PERSONNE_SEC": null,
    "CAT_ABONDANCE": 2,
    "COUV_BUISSONS": null,
    "COUV_LITTIERE": null,
    "CUSTOM_TEXT_1": null,
    "CUSTOM_TEXT_2": null,
    "CUSTOM_TEXT_3": null,
    "CUSTOM_TEXT_4": null,
    "ENVIRO_MILIEU": null,
    "HAUTEUR_CRYPT": null,
    "LUTTE_SURFACE": null,
    "PRECISION_ALT": "I",
    "REM_INTRODUIT": null,
    "SOURCE_BIBLIO": null,
    "STRATE_RELEVE": null,
    "TAILLE_PLANTE": null,
    "ABS_COUVERTURE": null,
    "COUV_HERBACEES": null,
    "CUSTOM_TEXT_5_": null,
    "DEF_COUVERTURE": null,
    "DESC_LOCALITE_": "Zelgli/5",
    "GEOMORPHOLOGIE": null,
    "NO_NOTE_PROJET": "B74B7EFC-4996-4766-82D5-CA113A2D0FF2",
    "REM_COUVERTURE": null,
    "CAT_ABONDANCE_1": null,
    "CAT_ABONDANCE_2": null,
    "CAT_ABONDANCE_3": null,
    "CUSTOM_NUMBER_1": null,
    "CUSTOM_NUMBER_2": null,
    "CUSTOM_NUMBER_3": null,
    "CUSTOM_NUMBER_4": null,
    "CUSTOM_NUMBER_5": null,
    "ENVIRO_MILIEU_2": null,
    "ENVIRO_MILIEU_3": null,
    "ESTIMATION_DATE": "P",
    "HAUTEUR_ARB_MAX": null,
    "HAUTEUR_ARB_MIN": null,
    "HAUTEUR_ARB_MOY": null,
    "HAUTEUR_BUI_MAX": null,
    "HAUTEUR_BUI_MIN": null,
    "HAUTEUR_BUI_MOY": null,
    "LUTTE_NEOPHYTES": null,
    "TYPE_COUVERTURE": null,
    "VITALITE_PLANTE": null,
    "CAT_RECOUVREMENT": null,
    "COORDONNEE_FED_E": 681650,
    "COORDONNEE_FED_N": 267681,
    "DETERMINAVIT_CF_": "N",
    "HAUTEUR_HERB_MAX": null,
    "HAUTEUR_HERB_MIN": null,
    "HAUTEUR_HERB_MOY": null,
    "NOM_PERSONNE_OBS": "Schudel",
    "PRECISION_MAILLE": "B",
    "PREC_ABONDANCE_1": null,
    "PREC_ABONDANCE_2": null,
    "PREC_ABONDANCE_3": null,
    "STRUCTURE_MILIEU": null,
    "TYPE_ABONDANCE_1": null,
    "TYPE_ABONDANCE_2": null,
    "TYPE_ABONDANCE_3": null,
    "NO_SURFACE_WELTEN": null,
    "SOURCE_BIBLIO_CITE": null,
    "STRUCTURE_MILIEU_2": null,
    "STRUCTURE_MILIEU_3": null,
    "PRENOM_PERSONNE_OBS": "Hansruedi",
    "EXPERTISE_INTRODUIT_": "F",
    "HAUTEUR_VEGETATION_MAX": null,
    "HAUTEUR_VEGETATION_MIN": null,
    "HAUTEUR_VEGETATION_MOY": null
}
```

Aber das könnt ihr nicht einfach auswerten.
