### ISSUE TITLE
es erscheinen nur 1 TPop wo eigentlich 2 wären

### ISSUE THREAD

**Issue by alinemeyer** [barbalex/apf2#221]
Lieber Alex
An einem Standort befinden sich 2 TPopos am selben Standort (1 erloschen, 1 frisch angesät). Als ich heute eine Anpassung an einer der TPops machen wollte, war nur noch eine da.
![bildschirmfoto 2018-12-12 um 13 03 41](https://user-images.githubusercontent.com/42208152/49869241-26e0d200-fe10-11e8-9342-53c77cbc3510.png)

als ich dann den PC wechselte war sie plötzlich da
![bildschirmfoto 2018-12-12 um 13 05 58](https://user-images.githubusercontent.com/42208152/49869262-37914800-fe10-11e8-86ee-a909c53d5e9a.png)

Ich selber habe heute noch keine Änderungen an diesen TPops durchgeführt. Leider kann ich dies nur an diesem Beispiel zeigen

**Comment by barbalex** [comment]
> Als ich heute eine Anpassung an einer der TPops machen wollte, war nur noch eine da

Wo war nur noch eine der TPops? Ich kann an diese Möglichkeiten denken:

* auf der Karte
* im Strukturbaum
* an beiden Orten
* in einem Strukturbaum wenn zwei offen waren

Was hast du geändert?

**Comment by rebeccakurz** [comment]
Lieber Alex
Bei mir am Computer (kamor) hat es die neugegründete TPop 93.1 nicht angezeigt, sondern nur die ursprüngliche Population 5.1 (erster Screenshot). Ich dachte dann, dass Aline diese Ansaat vielleicht noch nicht eingetragen hat und habe sie gefragt. Sie konnte sich aber erinnern, dass sie eine neue Pop. gemacht hat. Als sie dann auf ihrem Computer (Rigi) nachgeschaut hat, hat es beide TPops angezeigt (Screenshot 2). Nicht angezeigt wurde die TPop sicher in der Karte und ich glaube sie wurde auch im Strukturbaum nicht angezeigt, bin mir aber nicht mehr ganz sicher. Es war nur ein Strukturbaum offen. 
Ich habe dann bei mir die Website nochmals neu geladen und danach hat es die TPops richtig angezeigt. Ich habe heute nochmals nachgeschaut und auch jetzt ist alles korrekt. War also vielleicht auch nur temporär...

**Comment by barbalex** [comment]
Schliesse weil alt und schon lange nicht mehr bestätigt
