### ISSUE TITLE
Eierlegende Wollmilchsau, TPopStatus verschlüsselt

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#222]
Der TPop-Status ist im Export verschlüsselt als Zahl. Könntest Du den bitte ausdeutschen?

**Comment by barbalex** [comment]
Gemacht

**Comment by csalzmann** [comment]
Wow, Du bist ja wieder mega schnell! Für heute ist jetzt aber genug von meiner Seite, Du kannst aufschnaufen;) 

Lieber Gruss!

**Comment by barbalex** [comment]
pfuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuhhhhhhhhhhhhhhhhhhh

;-)
