### ISSUE TITLE
Seidene Wollmilchsau, Anz. Kontrollen/TPop

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#223]
Ich kann nirgends die Anz. Kontrollen/TPop finden, das war jeweils noch eine interessante Info. Nun gibt es aber die Spalte "tpopber_anz". Ich bin davon ausgegangen, das sei die Anz. Kontrollberichte/TPop. Kann es aber nicht sein, zumindest nicht, was die Zahlen wiedergeben.

Kannst Du da weiterhelfen?

**Comment by barbalex** [comment]
Das ging in den übrigen 147 Feldern unter :-(

Ist wieder ergänzt
