### ISSUE TITLE
Suchen nach TPops

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#224]
Wie können wir nach einer best. TPop suchen, wenn wir nicht schon in der richtigen Pop sind?

**Comment by barbalex** [comment]
Das ist nicht implementiert.

Es bräuchte dazu ein zusätzliches Suchfeld. Das beim Tippen Listen anzeigt aller Strukturebenen, auf denen man suchen können will. Etwa so, wie die Suche auf https://arteigenschaften.ch umgesetzt ist.

Gibst du dort im Suchfeld oben links "trockenw" ein, siehst du, dass Resultate aus drei Ebenen angeboten werden: Arten, Eigenschaftensammlungen und Lebensräume. Und wenn man auf eine Resultat klickt, springt die Anwendung im Baum dorthin.

**Comment by csalzmann** [comment]
Dann ist das ein Wunsch für 2019.

**Comment by barbalex** [comment]
Duplikat von https://github.com/barbalex/apf2/issues/232
