### ISSUE TITLE
Qualitätskontrolle anpassen: anges. erloschen/pot Wuchsort

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#225]
Eine Anpassung unsererseits an die Qualitätskontrolle:

Folgende Kombi darf möglich sein:
Pop angesiedelt, erloschen
mind. 1 TPop angesiedelt, erloschen; weitere TPops dürfen auch nur pot. Wuchsort sein

Habe Dir die aktualisierte Matrix angehängt
[Qualitätskontrolle_Status_Kriterien_20181218.xlsx](https://github.com/barbalex/apf2/files/2690806/Qualitatskontrolle_Status_Kriterien_20181218.xlsx)

**Comment by barbalex** [comment]
Diese Matrix enthält nun in diesen zwei Positionen:

- angesiedelt, erloschen, vor AP / pot. Wuchsort
- angesiedelt, erloschen, nach AP / pot. Wuchsort

neu eine 1.

Das heisst gemäss Legende: mindestens 1 Tpop muss diesem Kriterium entsprechen. Das heisst in diesen Fällen: mindestens 1 Tpop muss den status "pot. Wuchsort" haben.

Ist das wirklich so gemeint?

Ist das nicht eher das "x" gemeint, d.h. pot. Wuchsort ist erlaubt?

**Comment by barbalex** [comment]
Analog zum anderen Fall - glaube ich
