### ISSUE TITLE
Tpop kopieren funktioniert nicht

### ISSUE THREAD

**Issue by alinemeyer** [barbalex/apf2#226]
Lieber Alex
Das Kopieren und Einfügen von Tpops funktioniert zurzeit nicht, das Verschieben hingegen schon. Habe es an Abies alba ausprobiert. Vielen Dank für deine Hilfe! LG

**Comment by barbalex** [comment]
Das war ein doofer Flüchtigkeits-Fehler :-(

Ist behoben. Danke für die Meldung.
