### ISSUE TITLE
Export "AP-Berichte (Jahresberichte)" funktioniert nicht

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#227]
Hallo Alex
Karin Marti wollte soeben einen Export "AP-Berichte (Jahresberichte)" machen und dann kam folgende Fehlermeldung:
![bildschirmfoto 2019-01-10 um 12 57 54](https://user-images.githubusercontent.com/30288503/50967267-ebe9c100-14d7-11e9-949f-cb96eb69f25c.png)
Könntest du das bitte anschauen? KM braucht diesen Export dringend!
Grüsse
Rebecca

**Comment by barbalex** [comment]
Ich kann das nicht nachvollziehen, weder in der Entwicklungs- noch in der live Version. Habe soeben einen Bericht erzeugt. Schick ihn dir per email.

**Comment by csalzmann** [comment]
Bei mir kommt die genau gleiche Fehlermeldung. Was könnte denn der Grund sein, dass das bei Dir anders ist?

**Comment by barbalex** [comment]
Du hast wohl der Chrome Engine Göttin heute noch keinen Tribut gezollt.

Versucht es mal mit Leeren des Cache, dann neu laden.

**Comment by csalzmann** [comment]
Also diesmal ist es nicht das. Habe grad nochmals gecached, es nützt nichts.

![bildschirmfoto 2019-01-10 um 15 44 10](https://user-images.githubusercontent.com/6047564/50975915-f19ed100-14ee-11e9-940f-07a18ab907ee.png)

**Comment by kmarti** [comment]
Lieber Alex

Hast Du das schon geschickt?

Herzliche Grüsse

Karin

------------------------------------------
Karin Marti
Dr.sc.nat.ETH
topos Marti & Müller AG
Idastrasse 24
8003 Zürich
marti@toposmm.ch
Tel. 044 451 52 55

**Comment by barbalex** [comment]
Ja, aber an Anna. Hab es dir weiter geleitet

**Comment by barbalex** [comment]
Schliesse weil alt und schon lange nicht mehr bestätigt
