### ISSUE TITLE
Feld beim Zielbericht

### ISSUE THREAD

**Issue by wunderli** [barbalex/apf2#228]
Lieber Alex

Das mittlere Feld im Zielbericht heisst zur Zeit „Entwicklung“.
Bitte ändern zu „Zielerreichung“.

Danke!

![bildschirmfoto 2019-01-08 um 11 17 04](https://user-images.githubusercontent.com/26789445/50971329-0fb30400-14e4-11e9-8d13-2c4c3c7e12de.png)

**Comment by barbalex** [comment]
gemacht
