### ISSUE TITLE
Berechtigung für "reopen issue"?

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#229]
Lieber Alex
Anna und ich haben soeben gemerkt, dass nur ich die Berechtigung habe, einen bestimmten Issue wieder zu öffnen. Bsp Issue 133. Wie können Anna/Rebecca oder andere einen Issue wieder öffnen?

**Comment by barbalex** [comment]
Wer mitarbeiten will muss freigeschaltet sein. Momentan sind das:
<img width="879" alt="2019-01-10_15h05_24" src="https://user-images.githubusercontent.com/669783/50973511-55be9680-14e9-11e9-9f5d-608ce94bda48.png">

Mit anderen Worten:

- Anna wurde von mir auf die Liste gesetzt. Danach bekommt sie offenbar von GitHub ein email, wo sie die Mitarbeit bestätigen kann. Offenbar hat sie das nie gemacht.
- Rebecca sollte mitarbeiten können

Ich schick Anna eine neue Einladung.

**Comment by barbalex** [comment]
Habe Jasmin ergänzt. marti@toposmm.ch habe keinen GitHub account? Was ist ihr Kürzel oder das für den Account verwendete email?

**Comment by kmarti** [comment]
Lieber Alex

Das für den GitHub verwendete Email ist marti@toposmm.ch

Herzliche Grüsse

Karin
---------------------------------------------------------------
Karin Marti
Dr.sc.nat.ETH
topos Marti & Müller AG
Idastr. 24
8003 Zürich
Tel. 044 451 52 55
marti@toposmm.ch



Am 11.01.2019 um 14:36 schrieb Alexander Gabriel <notifications@github.com>:

**Comment by barbalex** [comment]
<img width="651" alt="2019-01-11_15h07_30" src="https://user-images.githubusercontent.com/669783/51038159-aa7a1400-15b2-11e9-8ad9-7be124a2d173.png">

**Comment by barbalex** [comment]
Aber den musst du wohl mit einer anderen email-Adresse eröffnet haben. ODER: du hast eingestellt, dass die email geschützt ist (falls man das kann, keine Ahnung).

Aber egal: Obige Antwort zeigt deinen Twitter-Handle (kmarti) an. Damit geht es auch.

**Comment by barbalex** [comment]
schliesse, weil alle erwähnten als Mitarbeiter nun erfasst und bestätigt sind
