### ISSUE TITLE
Erfolgskontrolle mit Anzahl 0

### ISSUE THREAD

**Issue by jmenzi** [barbalex/apf2#23]
Bei der einer Zähleinheit mit Anzahl 0 wird im Strukturbaum "keine Anzahl" angezeigt.

**Comment by barbalex** [comment]
Ist in der Entwicklungsversion korrigiert. Es dauert aber eine Weile, bis die Live-Version aktualisiert wird,  da gerade die Beobachtungen umgebaut werden
