### ISSUE TITLE
Qualitätskontrolle: Fehler Status Ansaat/Kontrollbericht erloschen

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#231]
Lieber Alex

Folgende Kombi wird nicht als Fehler angezeigt, obwohl so in der Matrix drin (2. Reiter):
Pop/TPop-Status=Ansaat; Kontrollbericht=erloschen

Wir brauchen die funktionierenden Qualitätskontrollen für den Jahresbericht, es werden sonst falsche Zahlen angezeigt. Könntest Du dem Priorität einräumen? Es gibt auch noch den Fall 225, der ebenfalls die Qualitätskontrolle betrifft.

Vielen Dank!

[Qualitätskontrolle_Status_Kriterien_20181218.xlsx](https://github.com/barbalex/apf2/files/2758583/Qualitatskontrolle_Status_Kriterien_20181218.xlsx)

**Comment by barbalex** [comment]
> Folgende Kombi wird nicht als Fehler angezeigt, obwohl so in der Matrix drin (2. Reiter):
Pop/TPop-Status=Ansaat; Kontrollbericht=erloschen

Das kommt daher, dass in deinem Dokument, dass mit dem 2.3.2017 datiert ist und das als Grundlage für die Qualitätskontrollen diente, in diesem Feld nicht ein 0** war sondern ein x (=möglich). Mit der Bemerkung: "Nach einer missglückten Ansiedlung (Status erloschen) darf am gleichen Ort wieder eine neue Ansaat gemacht werden." Daher wurde diese spezifische Kontrolle nie gebaut.

Die nun von dir gewünschte Kontrolle ist viel aufwändiger, weil man dabei auch noch das Berichtjahr (dynamisch berechnet je nach dem Zeitpunkt, in dem die QK berechnet wird) mit dem Jahr der Ansaat vergleichen muss. Das sind zwei zusätzliche Unterabfragen, deren Ergebnisse in einer bereits komplexen Abfrage berücksichtigt werden müssen.

Ich sehe auch noch weitere Unterschiede zwischen dem damaligen Dokument und dem jetzt von dir verlinkten. Bei:

- angesiedelt, aktuell, vor AP / erloschen
- angesiedelt, aktuell, nach AP / erloschen

war ursprünglich ein 0 enthalten. Jetzt sind es 0* mit der Bemerkung "*ausser es wird im Berichtsjahr eine Ansiedlung gemacht, dann ist Status "aktuell" zwingend, obwohl Bericht = "erloschen"."

Folglich müsste man nun 6 Qualitätskontrollen anpassen. Das gibt wohl mindestens 3 bis 4 Stunden Aufwand, ev. bis zu 6 (solche Abfragen können aufwändig sein).

Ich bin mir auch nicht ganz sicher, ob sich aus deinem Dokument nicht noch zusätzliche Abfragen herleiten, aufgrund der folgenden (widersprüchlichen?) Aussagen im Bemerkungsfeld:

> Wenn im Berichtjahr eine Ansiedlung erfolgt _muss_ der Status "Ansaatversuch" sein
> Wenn im Berichtsjahr eine Ansiedlung erfolgt, _muss_ der Status "aktuell" sein

Hier das Dokument, mit dem ich die QK entwickelt habe: 
[Qualitätskontrolle_Status_Kriterien_20170302.xlsx](https://github.com/barbalex/apf2/files/2765012/Qualitatskontrolle_Status_Kriterien_20170302.xlsx)

**Comment by csalzmann** [comment]
Nach unserer Besprechung heute lösen wir diese Fälle so, dass wir in Zukunft nach Erlöschen einer Ansaat/Ansiedlung eine neue TPop gründen
