### ISSUE TITLE
Suche über alles

### ISSUE THREAD

**Issue by barbalex** [barbalex/apf2#232]
Tippt man, werden Vorschläge aus allen Struktur-Ebenen bzw. Daten-Tabellen aufgelistet, jeweils unter ihrem Titel. 

Klickt man auf einen Vorschlag, wird im Strukturbaum und Formular dorthin navigiert.

Ähnlich funktioniert die Suche auf arteigenschaften.ch. Hier wird die Suche in "Arten", "Lebensräume" und "Eigenschaften-Sammlungen" aufgegliedert. Innerhalb dieser Kategorien muss hier nur im Namen gesucht werden.

Ich könnte mir vorstellen, das Suchfeld oben in der grünen Titel-/Menü-Leiste unterzubringen. Das würde den alles umfassenden Aspekt dieser Suche betonen (im Gegensatz zu derjenigen im Strukturbaum).

Im Gegensatz zu arteigenschaften.ch wären es nicht drei Struktur-Ebenen, sondern ca. 27. Womit sich die Frage stellt, wie man es ermöglichen könnte, die Anzahl Ebenen einzuschränken. Das wäre z.B. möglich, indem eine Schaltfläche am Rand des Suchfelds nach ihrem öffnen alle Ebenen auflistet und die Benutzerin wählen kann, in welchen gesucht werden soll. Standardmässig wären alle ausgewählt.

Auch wäre es bei so vielen Ebenen hilfreich, wenn nur die Titel derjenigen angezeigt werden, in denen die Suche Treffer ergibt.

Es wäre auch zu bestimmen (ev. wählbar), ob die Inhalte aller Felder berücksichtigt werden sollen (= Volltextsuche), oder nur die Label gemäss Strukturbaum.

Diese Suche würde relativ viele Ressourcen beanspruchen. Damit sie effizient ist, müsste sie Server-seitig erfolgen und entsprechende Indizes müssten vorbereitet sein.

Damit wird ihre Umsetzung relativ aufwändig.

Lohnt sich also nur, wenn es viel benutzt würde.

Das Bedürfnis wurde eingebracht von Nina (Ackerflora-Projekt). Weil sie sich beim Arbeiten mehr an den Orten/Namen orientieren als an den Arten. Vermutlich wäre für sie die optimale Suche nach Strukturbaum-Label, wobei gewählt wird, in welchen Tabellen gesucht werden soll.

Siehe auch: https://github.com/barbalex/apf2/issues/224

**Comment by rebeccakurz** [comment]
Hallo Alex
Würde das nicht in die gleiche Richtung gehen, wie es mit der Filter-Funktion bereits teilweise umgesetzt ist? Da könnte man ja dann zum Beispiel auf Ebene der Populationen oder Teilpopulationen nach einem bestimmten Flurnamen suchen und würde dann theoretisch direkt dorthingeleitet? Leider funktioniert (bei mir jedenfalls) die Filter-Funktion noch nicht wunschgemäss.
Meiner Meinung nach müsste man entweder die Filter-Funktion weiter ausbauen, so dass sie einwandfrei funktioniert oder dann würde man eine "Suche über alles" aufbauen. 
<img width="1234" alt="bildschirmfoto 2019-01-16 um 09 35 00" src="https://user-images.githubusercontent.com/30288503/51236273-09a0a580-1972-11e9-9497-b862d5ac2398.png">

**Comment by barbalex** [comment]
> Würde das nicht in die gleiche Richtung gehen, wie es mit der Filter-Funktion bereits teilweise umgesetzt ist?

Nein:

- der Formular-Filter liefert als Resultat eine beliebige Anzahl von Datensätzen aus der gefilterten Ebene (alle, welche den Kriterien genügen).<br/>
Was dort im Grunde fehlt: Eine Ansicht, die alle Resultate auflistet.<br/>
Denn der Strukturbaum kann sie nicht darstellen, weil er höhere hierarchische Ebenen anzeigt.<br/>
In der Karte hingegen werden sie (Populationen und Teil-Populationen) dargestellt. Und bei Exporten könnte eine solche Option ergänzt werden. <br/>
Ev. müsste während der Eingabe im Formular-Filter links statt des Strukturbaums (oder zusätzlich dazu) eine Liste der Treffer aus der gefilterten Ebene gezeigt werden?<br/><br/>
- die Suche über alles liefert als Resultat der Suche genau einen Datensatz aus irgend einer Ebene. Dieser kann problemlos im Strukturbaum dargestellt werden. Aber: Es ist nur ein Datensatz, im Gegensatz zum Formular-Filter<br/><br/>
- der Formular-Filter filtert nach Feldern. Man sucht also nach einer Zeichenfolge _in einem Feld_<br/><br/>
- die Suche über alles wäre entweder eine Volltextsuche: man sucht also nach einer Zeichenfolge _in einem beliebigen Feld_. Oder sie würde nach den Labels suchen, d.h. nur in den für die Labels genutzten Feldern

**Comment by barbalex** [comment]
Der Sinn der Suche über alles: möglichst schnell und direkt zu irgend einem Datensatz aus irgend einer Ebene springen.

Der Sinn von Filtern: Eine Auswahl aus Datensätzen erstellen.

**Comment by rebeccakurz** [comment]
Okay, dann habe ich die Filter-Funktion falsch verstanden. Ich habe nämlich darauf gewartet, dass mir der Strukturbaum die gefilterten Ergebnisse anzeigen würde und hatte die Karte nicht einmal offen! Daher fände ich deinen Vorschlag mit einer Liste der Treffer sehr gut, ich glaube, dass würde es verständlicher machen. (noch eine Bemerkung zum Filtern: damit der Filter angewendet wird, muss ich zur Zeit in ein anderes Feld klicken. Könnte man auch machen, dass der Filter bei Betätigung der Return-Taste ausgelöst wird? Oder dass es vielleicht einen extra Button "Filter anwenden" oder etwas Ähnliches gäbe?)

Dann wäre in dem Fall die Suche über alles ergänzend zum Filtern, wenn ich dich richtig verstanden habe? Das würde demnach schon Sinn machen. 
Wie ist das denn wenn verschiedene Datensätze der Sucheingabe entsprechen würden? Gerade z.B. bei Flurnamen kommt es ja oft vor, dass diese mehrmals verwendet werden?

**Comment by csalzmann** [comment]
Ich bin auch ein bisschen verloren mit dem Unterschied Sucher über alles/Filtern.
Was das Filtern jetzt schon kann finde ich aber grandios! Ich glaube, es fehlt da gar nicht mehr viel.

Bitte Filter-Funktion nach Return auslösen (wie RK oben sagt).

Die Anzeige im Baum mit den Resultaten wäre sehr hilfreich. Funktioniert aber nicht in jedem Fall. 
Bsp. Oara. bekannt seit = 1800. Resultat: 2 Pops.

![bildschirmfoto 2019-02-15 um 14 41 39](https://user-images.githubusercontent.com/6047564/52861125-c59bee80-3131-11e9-8b50-eb3690ef22f1.png)

Auf jeden Fall haben wir das Bedürfnis von Nina auch, nach Ortsnamen zu suchen. Z.B., ich suche alle Pops mit Kloten im Namen (O. araneola).
Da komm ich aus dem Ergebnis nicht recht draus was gemacht wurde:

![bildschirmfoto 2019-02-15 um 14 59 11](https://user-images.githubusercontent.com/6047564/52861287-54107000-3132-11e9-87ba-e9029a72a116.png)

**Comment by barbalex** [comment]
> Bitte Filter-Funktion nach Return auslösen (wie RK oben sagt).
Dafür habe ich einen neuen Issue geschaffen: https://github.com/barbalex/apf2/issues/249

**Comment by barbalex** [comment]
> Die Anzeige im Baum mit den Resultaten wäre sehr hilfreich. Funktioniert aber nicht in jedem Fall.
Bsp. Oara. bekannt seit = 1800. Resultat: 2 Pops.`

Doch, das ist richtig so und erläutert, wieso wir dieses Jahr für die Filterung den Baum um die "Tabellen" erweitern sollten:

- In deinem Beispiel-Bild sieht man zwei gefilterte Populationen _von Ophrys araneola_
- Der Filter zeigt 102/6431 an, weil:
  - es 6431 Populationen gibt
  - 102 davon seit 1800 bekannt sind
  - _zwei davon bei Ophrys araneola_

Gäbe es eine Tabelle "Populationen", sähe man dort alle 102 gefilterten Populationen. In dieser Ansicht sieht man nur die zwei, weil man sich in einem Unter-Knoten von Ophrys befindet.

**Comment by barbalex** [comment]
> Da komm ich aus dem Ergebnis nicht recht draus was gemacht wurde

Da wird offenbar nach "Feldinhalt = Filterkriterium" gefiltert, anstatt: "Feldinhalt enthält Filterkriterium". Da muss ich wohl nachbessern

**Comment by barbalex** [comment]
Schliesse, da keine gute oder nützliche Idee von mir...
