### ISSUE TITLE
Text-Vorschläge bei Eingabe-Feldern

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#233]

**Comment by barbalex** [comment]
Wie macht ihr das?

Implementiert ist es nicht.

Könnte das eine Browser-Funktion sein, die euch beim Ausfüllen von Formularen helfen will?

**Comment by rebeccakurz** [comment]
Kann schon sein, dass es Vorschläge vom Browser sind. Es sind ja meist Einträge, die schon einmal in dieses Feld eingegeben worden sind (auf jeden Fall bei Charlotte und mir).
Wieso es bei Regula Dickenmann plötzlich ihre Adresse vorschlägt ist schon etwas suspekt!

**Comment by barbalex** [comment]
In einem der oben dargestellten Listen gibt es die Möglichkeit, Adressen zu verwalten.

Das kommt ganz sicher nicht aus apflora.

Ich kann mir nur vorstellen, dass Browser und Betriebssystem hier zusammenspannen und den Zugriff auf die Adressen von Kontakten ermöglichen. Das gibt es in Windows meines Wissens nicht. Passiert das (nur) auf MacOS?

**Comment by rebeccakurz** [comment]
Also ChS und ich haben auf MacOS, Chrome gearbeitet. RD weiss ich nicht...
Wenn man darauf klickt, wird es eingesetzt.
![bildschirmfoto 2019-01-17 um 07 33 22](https://user-images.githubusercontent.com/30288503/51299946-71b2c280-1a2a-11e9-9ae0-ed2dec429e7a.png)
![bildschirmfoto 2019-01-17 um 07 33 30](https://user-images.githubusercontent.com/30288503/51299949-74adb300-1a2a-11e9-918a-371f69481ce7.png)

**Comment by rebeccakurz** [comment]
Achso... Das kann ich leider nicht sagen, bei mir hat es das nie angezeigt (nur bei RD)

**Comment by csalzmann** [comment]
Aus Issue 256: "Das ist ein reines Textfeld. Dafür ist in apflora nichts solches implementiert. Hingegen gibt es Browser/Betriebssysteme, welche solche Funktionalitäten implementieren.

Du musst das also deinem Browser oder Mac abgewöhnen."

Wir benutzen extra Chrome für die FloraDB, ich persönlich einzig und allein nur für die FloraDB und für nichts anderes. Wir sind keine Browserspezialistinnen. Du hast ja auch einen Mac. Kannst Du uns bitte sagen, wo wir das abstellen? Wir können die User nicht so alleine stehen lassen. Und offensichtlich ist es ja kein Einzelfall.

**Comment by barbalex** [comment]
> Wir benutzen extra Chrome für die FloraDB, ich persönlich einzig und allein nur für die FloraDB und für nichts anderes. Wir sind keine Browserspezialistinnen. Du hast ja auch einen Mac. Kannst Du uns bitte sagen, wo wir das abstellen?

Das ist nicht einfach, weil es bei mir ja nicht passiert. Und ev. weil ich auch auf meinem Mac nicht dasselbe Umfeld verwende wie ihr. Aber versuchen wir's.

Was _genau_ verwendet ihr:

- Chrome auf Mac?
- Chrome auf virtuellem Windows auf Mac?
- Ist Chrome aktuell?
- Welche Version von MacOS verwendet ihr?

**Comment by barbalex** [comment]
O.k., ich habe soeben etwas gelernt.

Erstens: Man kann in Chrome einstellen, dass Adressen gespeichert und automatisch in "passende" (wie auch immer Chrome das entscheiden möge) Felder eingefüllt werden. Das könnt ihr machen, indem ihr die Url "chrome://settings/addresses" öffnet. Das scheint bei Regula Dickenmann eingestellt zu sein.

Zweitens: Chrome hat die Angewohnheit, euch das Leben erleichtern zu wollen. Indem es beobachtet, was ihr erfasst und euch das künftig wie von euch beschrieben vorschlägt. Leider ist nicht ganz klar, wann Chrome das macht. Bei mir z.B. ist das noch nie passiert. Aber: Indem ich die Felder um ein paar Eigenschaften ergänze, soll das dieses Verhalten verhindern können. Und das habe ich soeben gemacht und live geschaltet.

Ich schliesse diesen Issue in der Hoffnung, dass das nun nicht mehr passiert.
