### ISSUE TITLE
Strukturbaum, Population: Manchmal sind die Berichte nicht sichtbar

### ISSUE THREAD

**Issue by barbalex** [barbalex/apf2#234]
Regula Dickenmann hat das per email gemeldet.

Mir ist es auch schon passiert, aber ich kann es nicht provozieren.
Die Berichte erschienen dann nach Neu-Laden.

@csalzmann @jmenzi @wunderli @kmarti 
Falls es euch auch platziert und ihr gemerkt habt, wie man das einigermassen zuverlässig provozieren kann: Könnt ihr das bitte hier notieren?

**Comment by wunderli** [comment]
Lieber Alex

René Bertiller hat mir soeben den entsprechenden Hinweis gegeben:
Die Berichte sind da, solange der Filter "nur AP-Arten" nicht gesetzt ist.
Mit dem "Neuladen" haben wir eigentlich dasselbe gemacht, denn da fällt der Filter wieder raus...

Setzt man den Filter nach neuladen wieder, verschwinden die Berichte...

Ich hoffe mit diesem Hinweis kannst du den Fehler beheben!

Liebe Grüsse

Anna

**Comment by barbalex** [comment]
Das war der entscheidende Hinweis. Danke!

Auch die Ordner für AP-Arten und Pop-Massnahmen-Berichte verschwanden jeweils.

Ist jetzt repariert.
