### ISSUE TITLE
Im Jahresbericht fehlen Angaben zur Zielerreichung 

### ISSUE THREAD

**Issue by kmarti** [barbalex/apf2#235]
Lieber Alex

Wenn ich den Jahresbericht 2018 erstelle, dann erscheinen zwar bei den einzelnen Arten die Ziele 1-4, aber nicht die Bemerkungen dazu, ob diese Ziele erreicht worden sind (Zielbericht).

Herzliche Grüsse

Karin

**Comment by kmarti** [comment]
ist relativ dringend, da die Artverantwortlichen ab dem 20.1. den Jahresbericht anschauen sollten

**Comment by barbalex** [comment]
Gemacht
