### ISSUE TITLE
Strukturbaum zeigt nur Teilpops an (René Bertiller)

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#238]
Hallo Alex
René Bertiller hat soeben angerufen. Es zeigt ihm im Strukturbaum nur die Teilpopulationen an, keine Berichte, Qualitätskontrollen etc. 
Er benutzt als Browser Firefox.
Vielleicht kannst du helfen.
LG

**Comment by barbalex** [comment]
Ist repariert, dank seinem Hinweis
