### ISSUE TITLE
Qualitätskontrolle individuell durch AV anpassbar

### ISSUE THREAD

**Issue by wunderli** [barbalex/apf2#239]
Lieber Alex

Es gibt immer wieder Fälle, wo eine Qualitätskontrolle zwar korrekt ist, aber nicht korrogierbar ist.
z.B. fehlendes Jahr eine uralten EK/Ansiedlung.

Hier wäre es super, wenn der AV individuell QK "wegklicken" könnte, damit diese nicht mehr immer angezeigt werden.

Liebe Grüsse

Karin S. und Anna

**Comment by kmarti** [comment]
Ich denke nicht, dass das die Lösung ist. Wir müssen das topos-intern noch diskutieren.
Liebe Grüsse Karin

**Comment by barbalex** [comment]
Um zu beurteilen, ob, wie und wie aufwändig das umgesetzt werden kann, müsste ich ein bisschen recherchieren (ca. 0.5 Stunden). Bitte sagt mir hier, wenn ich das machen soll.

**Comment by kmarti** [comment]
Lieber Alex

nein, bitte nicht machen!!

Herzliche Grüsse

Karin

------------------------------------------
Karin Marti
Dr.sc.nat.ETH
topos Marti & Müller AG
Idastrasse 24
8003 Zürich
marti@toposmm.ch
Tel. 044 451 52 55

**Comment by barbalex** [comment]
Nur um das klar zu stellen:

- einzelne QK "wegklicken": Diese Funktionalität ist nicht möglich
- auswählen, welche Abfragen bzw. Kontrollen ausgeführt werden: Das ist möglich. Und auf Ebene Projekt sinnvoll

**Comment by barbalex** [comment]
Ist nun gemäss Offerte 2019 umgesetzt
