### ISSUE TITLE
Ziele: Zu viele Ziele angezeigt

### ISSUE THREAD

**Issue by jmenzi** [barbalex/apf2#24]
Für jedes Ziel werden noch weitere, offenbar willkürliche Ziele angezeigt. Ich sehe nicht genau warum, oder weshalb so viele verschiedene Ziele angezeigt werden. Immer nur ein Ziel  ist korrekt. Es handelt sich um einen Fehler.

**Comment by barbalex** [comment]
wo kann ich das nachvollziehen?

**Comment by jmenzi** [comment]
Siehe Bild im Anhang. Pro Jahr sollte nur ein Ziel 1,2,3 und 4 vorhanden sein. Total sind es hier aber z.B. 19 Ziele. Woher diese kommen ist mir nicht klar. 
![bildschirmfoto 2017-05-17 um 10 02 09](https://cloud.githubusercontent.com/assets/6448181/26144219/46895920-3ae8-11e7-8244-96943a896060.png)

**Comment by barbalex** [comment]
hm. Das sieht bei mir aber so aus:
![2017-05-18_09h06_06](https://cloud.githubusercontent.com/assets/669783/26190363/552f5260-3ba9-11e7-9d89-7138c5a312c9.png)

Das könnte ev. mit Veränderungen in der Datenbankstruktur zu tun haben, siehe hier: https://github.com/barbalex/apf2/issues/36

Probier doch, ob du dieses Problem immer noch hast.

**Comment by csalzmann** [comment]
Ist gut jetzt auch bei uns. Danke!

---------------------------------------------------------------
Charlotte Salzmann
Dr.sc.ETH
topos Marti & Müller AG
Idastr. 24
8003 Zürich
Tel. 044 451 52 55
salzmann@toposmm.ch

Di - Fr

**Comment by barbalex** [comment]
:-)
