### ISSUE TITLE
Gartenpflanzen als nicht relevant für AP-Bericht deklarieren

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#240]
Es gibt einige Teilpopulationen von Pulsatilla vulgaris, welche vermutlich Gartenpflanzen sind. Diese müssten unter "Für AP-Bericht relevant" als nicht relevant deklariert werden. Zur Zeit gibt es keine Auswahl, wo sie hineinpassen würden (historisch, ausserkantonal, kein Vorkommen). Man müsste eine neue Kategorie "Nein (Gartenpflanzen)" schaffen.

**Comment by barbalex** [comment]
Das löst sich mit der Anpassung dieses Jahr: Wir trennen die Feststellung "relevant" und den "grund". Grund wird eine Auswahl aus einer Liste. Diese wiederum kann in den Werte-Listen angepasst werden.

Wenn du willst, kann ich diese Änderung etwas vorziehen.

Wann brauchst du sie?

**Comment by csalzmann** [comment]
Das ist gut. Du musst den Task aber nicht vorziehen, der JB 2018 ist sozusagen fertig, da machen wir jetzt nichts mehr an den Beurteilungen dieses Jahr.

**Comment by barbalex** [comment]
Danke

**Comment by barbalex** [comment]
Hab das jetzt noch in die Werteliste aufgenommen, die schon seit einer Weile von euch selber angepasst werden kann
