### ISSUE TITLE
Neue Freiwilligen-Kontrolle erstellen funktioniert nicht

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#242]
Bei mir funktioniert es im Moment nicht, eine neue Freiwilligen-Kontrolle zu erstellen. Habe es bei Abies alba und zwei anderen Arten versucht. (Es geschieht gar nichts, auch nicht wenn man die Seite aktualisiert).
Auf MacOS, Browser Chrome, Cache erst gerade geleert. 
Bei Jasmin hat es in der Testart Abies alba auch nicht funktioniert.

**Comment by barbalex** [comment]
Aua. Böser Fehler. Passiert auch an anderen Orten. Ist in der Entwicklungsversion behoben. Versuche, die live-Version zu aktualisieren.

**Comment by barbalex** [comment]
O.k., sollte wieder klappen
