### ISSUE TITLE
Strukturbaum-Anzeige

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#243]
Es scheint gerade ein Problem mit der Anzeige des Strukturbaums zu geben. Wenn ich verschiedene Populationen hintereinander öffne, gibt es eine Vermischung der Teilpopulationen. Es werden dann z.B. obwohl nur eine TPop vorhanden sein sollte, drei TPops angezeigt und zwar immer die aus der Population, die ich zuvor geöffnet hatte. 
![bildschirmfoto 2019-02-11 um 07 48 42](https://user-images.githubusercontent.com/30288503/52549056-8851fc80-2dd1-11e9-926b-dcd59faef05f.png)
Wenn ich dann nochmals eine Pop im Strukturbaum öffne, zeigt es mir noch mehr TPops an, also hier z.B. dreimal eine 1. TPop.
![bildschirmfoto 2019-02-11 um 07 49 03](https://user-images.githubusercontent.com/30288503/52549092-a586cb00-2dd1-11e9-9180-7522b9d736d7.png)
Manchmal kann ich die Teilpopulationen auch nicht ausklappen.

**Comment by rebeccakurz** [comment]
Letzte Woche hatte ich mit dem Strukturbaum auch schon Probleme. Da hat es mir, wenn ich zuvor schon nach einer anderen Art gefiltert hatte, die gesuchte Art nicht mehr oben im Strukturbaum angezeigt, sondern erst unten und die zuvor gefilterte Art ist oben stehengeblieben (allerdings ohne Artname, nur die Populationen.)
![bildschirmfoto 2019-02-06 um 07 57 29](https://user-images.githubusercontent.com/30288503/52549175-2f369880-2dd2-11e9-87cd-aae32a8fcac8.png)
![bildschirmfoto 2019-02-06 um 08 19 44](https://user-images.githubusercontent.com/30288503/52549187-36f63d00-2dd2-11e9-9108-bf0a4f395ff8.png)

**Comment by wunderli** [comment]
Habe dieses Problem mit den Tpops in fremden Populationen soeben auch gehabt!

**Comment by barbalex** [comment]
Ich kann es nachvollziehen, aber noch nicht lösen. Hat 1. Priorität aber ist nicht ganz simpel :-)

**Comment by barbalex** [comment]
Hoffe, es ist nun gelöst

**Comment by rebeccakurz** [comment]
scheint leider doch noch nicht gelöst zu sein. Ist mir soeben wieder passiert. 
<img width="625" alt="bildschirmfoto 2019-02-13 um 12 42 25" src="https://user-images.githubusercontent.com/30288503/52709398-f989df00-2f8c-11e9-98bd-5f57d1c7beb7.png">

**Comment by barbalex** [comment]
Grmpppf!!!!

Nächster Versuch: Sollte wieder mal gelöst sein :-|
