### ISSUE TITLE
"EKF sehen als" funktioniert nicht

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#244]
Es kommt folgende Fehlermeldung:
![bildschirmfoto 2019-02-11 um 07 55 54](https://user-images.githubusercontent.com/30288503/52549300-c0a60a80-2dd2-11e9-9a57-8bee053b8a15.png)

**Comment by barbalex** [comment]
Sollte korrigiert sein. Das passierte, wenn für die betreffende Person noch keine EKF im gewählten Jahr existierten.
