### ISSUE TITLE
Beobachtungen werden in Ansicht falscher TPop zugeordnet

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#245]
Karin Sartori und ich hatten grad parallel am gleichen Beispiel eine sehr merkwürdige Beobachtung.

Filipendula vulgaris.
Habe zuerst bei Pop 10 die 2 vorhandenen Beobachtungen angeschaut.
Dann zu Pop 50, ebenfalls Beobachtungen (es gibt nur 1). Jetzt waren aber auf einmal die 2 Beobachtungen von Pop 10 auch bei der Pop 50 aufgeführt (also total 3). 

Das Bsp lässt sich wiederholen, ist jetzt beim Fehlerbeschrieb grad wieder passiert. Es ist "nur" eine Ansichtssache, aber so kann man natürlich nicht mit den Beobachtungen arbeiten.

Kannst Du das bitte prioritär anschauen?

**Comment by rebeccakurz** [comment]
Ist das eventuell etwas Ähliches wie die Strukturbaumanzeige mit den TPops, die plötzlich in einer anderen Pop angezeigt wurden? Das scheint jetzt ja wieder in Ordnung zu sein.

**Comment by barbalex** [comment]
Ja, ist ähnlich.

Nächster Versuch: Sollte jetzt gelöst sein :-|

**Comment by jmenzi** [comment]
Offenbar gibt es immer noch Anzeigefehler. So hat es mir gerade bei Campanula cervicaria diverse Populationen angezeigt, die gar nicht zu dieser Art gehören. 

![bildschirmfoto 2019-02-13 um 14 17 43](https://user-images.githubusercontent.com/6448181/52714628-a28b0680-2f9a-11e9-9b5b-25cd69ca2835.png)
…]()

**Comment by barbalex** [comment]
Und wie kann ich das nachvollziehen?

**Comment by jmenzi** [comment]
Ich kann es bei mir auch nicht reproduzieren. Jetzt stimmt es auch bei mir wieder. Möchte damit nur sagen, dass das Darstellungsproblem offenbar noch nicht ganz gelöst ist und die Anzeige in diversen Bereichen zufällig falsch sein kann.

**Comment by barbalex** [comment]
Ich schliesse den issue. Bitte öffnen, wenn es ein nachvollziehbares Beispiel gibt.
