### ISSUE TITLE
Neue Teilpopulation erstellen funktioniert nicht!!

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#246]
Ich habe gerade eine neue Population bei Listera ovata erstellt und wollte auch eine neue Teilpopulation erstellen. Das Erstellen der neuen Teilpopulation funktioniert aber nicht! Es passiert gar nichts. Habe die Seite neu geladen, den Cache geleert, mich aus- und wieder eingeloggt, das Browserfenster ganz geschlossen und alles neu gestartet, hat alles nichts genützt. 
Auf MacOS, Browser Chrome.
Auch bei der Testart Abies alba funktioniert das Erstellen einer neuen TPop nicht. Weder in einer bestehenden Pop, noch in einer soeben neu erstellten Pop.

**Comment by rebeccakurz** [comment]
Wäre super, wenn du dir das Anschauen könntest. (Evt. ist es etwas Ähnliches wie das Erstellen der EKF, was ja zuletzt auch nicht funktioniert hat und du ja wieder "geflickt" hast?)

**Comment by barbalex** [comment]
Leider kann ich das in der Entwicklungsversion und auf apflora.ch auf Abies alba nicht nachvollziehen.

Wo funktioniert es nicht?

**Comment by barbalex** [comment]
Oh, Listera ovata. Ich probier's

**Comment by barbalex** [comment]
Aua. Hoffe, es ist jetzt überall repariert.

Uns beisst wieder mal die Tatsache, dass wir keine automatisierten Tests haben :-)
