### ISSUE TITLE
Fehlermeldung beim Aufstarten

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#248]
Ich habe mich schon ziemlich dran gewöhnt, jetzt aber trotzdem mal an Dich die Meldung. Jeden Tag, wenn ich FloraDB aufstarten will, kriege ich als erstes diese Meldung: 

![bildschirmfoto 2019-02-15 um 08 00 30](https://user-images.githubusercontent.com/6047564/52839966-15f65a80-30f8-11e9-9973-f756b2a66e5d.png)

Neu laden hilft entgegen der Anweisung nichts. Ich muss dann immer Cache leeren. Wie gesagt, man gewöhnt sich dran, ist aber nicht schön. 

Ich arbeite gemäss Anweisung mit Mac Chrome. Nun habe ich gerade gemerkt, dass dieser Fehler auf Firefox nicht auftritt ?!

Könntest Du da auch mal schauen, was los ist? Ich denke, gerade für die neuen Artverantwortlichen dann sollte es nicht als erstes gerade eine Fehlermeldung beim Starten geben..:).

**Comment by csalzmann** [comment]
und das sieht man unten links:

![bildschirmfoto 2019-02-15 um 08 06 08](https://user-images.githubusercontent.com/6047564/52840114-91f0a280-30f8-11e9-92df-11e8ecbc5973.png)

**Comment by barbalex** [comment]
Der Fehler sagt, du hast keine Rechte. Daher reicht es, neu anzumelden - du musst nicht den cache leeren.

Ich werd's anschauen.

**Comment by csalzmann** [comment]
stimmt, mit ab- und anmelden komm ich auch wieder rein.

**Comment by barbalex** [comment]
Ich hab einen Entwurf für eine Korrektur. Ich kann das aber nur live testen. Und das traue ich mich nicht, während ihr arbeitet.

Wenn's geht werde ich das heute Nacht testen.

**Comment by csalzmann** [comment]
Danke:)!

**Comment by barbalex** [comment]
Update ist live. Bisher musste ich noch nicht neu anmelden. Mal schauen, wie es funktioniert :-|

**Comment by barbalex** [comment]
Nach etwas Nachbessern klappt es glaube ich. Zumindest nach dem nächsten Mal cache leeren.

**Comment by rebeccakurz** [comment]
Vielleicht noch als Ergänzung: Ich melde mich jeweils ab, wenn ich die FloraDB nicht mehr brauche. Bei mir erscheint diese Fehlermeldung aber auch, jeweils als Hintergrund mit dem Anmeldefenster im Vordergrund. Ich kann mich aber normal anmelden und es kommt auch nachher keine Fehlermeldung.
<img width="1327" alt="bildschirmfoto 2019-02-18 um 07 36 06" src="https://user-images.githubusercontent.com/30288503/52932490-29036780-3350-11e9-936d-2bcabd544a28.png">
(Das war übrigens gerade eben, daher fraglich ob das Update funktioniert hat?)

**Comment by csalzmann** [comment]
Also bei mir war heute alles wie immer. Dh, ich habe Fehlermeldung bekommen und musste mich neu anmelden.
Ich gebe aber zu, ich melde mich auch nie ab. Sollten wir das denn?

**Comment by barbalex** [comment]
> Ich gebe aber zu, ich melde mich auch nie ab. Sollten wir das denn?

Nein, das ist nicht nötig

**Comment by barbalex** [comment]
> Also bei mir war heute alles wie immer. Dh, ich habe Fehlermeldung bekommen und musste mich neu anmelden.

Zwei Fragen:

- Das Anmelde-Fenster hat sich also nicht selber geöffnet? Es ist nämlich normal, dass der Fehler sichtbar ist, neu ist nur, dass sich das Anmelde-Fenster automatisch öffnen sollte
- Hast du einen neuen Tab geöffnet oder einen bestehenden, der also nicht die URL "https://apflora.ch" darstellte, sondern irgendwas tieferes, z.B. eine Population?

**Comment by barbalex** [comment]
O.k., ist mir jetzt grad selber passiert, daher alles klar

**Comment by barbalex** [comment]
Lade soeben das nächste Update hoch, dass diesen Fehler korrigieren sollte
