### ISSUE TITLE
Filter-Funktion nach Return auslösen

### ISSUE THREAD

**Issue by barbalex** [barbalex/apf2#249]
Von Rebecca (https://github.com/barbalex/apf2/issues/232#issuecomment-454755185) und Charlotte (https://github.com/barbalex/apf2/issues/232#issuecomment-464060298) gewünscht

**Comment by csalzmann** [comment]
Das ist ja ein "Flick", damit es wenigstens wieder halbwegs geht mit Filtern. Die Frage ist aber schon, wieso das Filtern jetzt auch so langsam geht. Das war früher nicht so!
Ich habe jetzt auch gemerkt, dass der Flick eben nicht nur lässig ist. Jetzt muss man genau den richtigen Begriff eingeben - vorher schlug es doch schon beim Eintippen Resultate vor. Das war doch so, oder?

Das Thema gehört ja eigentlich zur allgemeinen Performance.

**Comment by barbalex** [comment]
> vorher schlug es doch schon beim Eintippen Resultate vor. Das war doch so, oder?

Also erst mal: hier sprichst du vom Strukturbaum-Filter. Ich sag das nur, weil ich diesen Issue eröffnet habe im Bezug auf den Formular-Filter.

Ja, das war so. Aber mir war von Anfang an klar, dass das gefährlich ist. Ich hab's nur so gebaut, weil es in meinen Versuchen ausreichend leistungsfähig war.

**Comment by barbalex** [comment]
Im Formularfilter wird der Filter in Text- und Datumsfeldern nun angewendet, wenn:

- man das Feld verlässt (wie bisher)
- man die Enter-Taste drückt (neu)

In Select- und Optionen-Feldern wird der Filter schon bisher direkt angewandt.
