### ISSUE TITLE
Scrollen in einem Zahlenfeld verändert Zahl

### ISSUE THREAD

**Issue by jmenzi** [barbalex/apf2#25]
Eher etwas anfällig für Fehler: Wenn ich in einem Zahlenfeld bin und scrolle ohne wegzuklicken, verändert sich die eingegebene Zahl. Ich finde dies riskant, da Zahlen unbemerkt verändert werden können.

**Comment by barbalex** [comment]
Ich hatte es extra schon direkt nach Implementierung ausprobiert, weil ich das von dir beschriebene Verhalten erwartet hatte und wir es in der letzten Anwendung extra relativ aufwändig verhindert haben.

Aber bei mir scheint es nicht zu passieren.

In welchem Feld passiert es bei dir zum Beispiel?

**Comment by barbalex** [comment]
Aha:

- Chrome auf Windows: passiert nicht
- Chrome auf macOs: passiert nicht
- Edge auf Windows: passiert nicht
- Firefox auf Windows: passiert
- Firefox auf macOs: passiert nicht

Arbeiten viele von euch mit Firefox auf Windows?

**Comment by barbalex** [comment]
Nun habe ich es doch geschafft, in einem Nummernfeld in Chrome auf Windows durch Scrollen die Zahlen zu verändern. Es geht nicht immer, keine Ahnung, was es auslöst.

Jedenfalls habe ich es jetzt generell verhindert.

Danke für die Meldung.

**Comment by csalzmann** [comment]
Es ist gerade wieder passiert: Bei Feldkontrolle, Anzahl Jungpflanzen.

Mac, mit Google Chrome

**Comment by barbalex** [comment]
Ich hab das ein bisschen recherchiert und ausprobiert. Dass man Zahlenfelder mit der Maus scrollen kann ist im HTML-Standard definiert.

Es gibt eine ziemlich grobschrötige Methode, das Verhalten zu unterdrücken. Die hatte ich schon in der alten Version angewendet und jetzt wieder implementiert. Leider scheint sie aber nicht immer zu funktionieren. Wieso ist nicht klar.

Theoretisch könnte ich das Feld gar nicht als Zahlenfeld definieren, sondern als Zeichenfeld. Das würde aber bestimmt andere Probleme nach sich ziehen, weil das definitiv nicht dem HTML-Standard entspricht. Und ich müsste alle Zahlenfelder neu bauen. Aber wenn ihr das wollt, würde ich es einmal probieren.

Ich habe mal im Projekt, dass die Felder-Vorlagen bereitstellt, dieses Anliegen eingebracht. Ich bin aber nicht sehr zuversichtlich, dass das erfolgreich sein wird.

**Comment by barbalex** [comment]
Ich schliesse dieses Issue, weil ich es auch mit wiederholten Versuchen nicht mehr provozieren kann. Falls es wieder auftritt: einfach wieder öffnen.

**Comment by rebeccakurz** [comment]
Also bei mir passiert das immer noch, wenn ich in einem Zahlenfeld bin und scrolle, ändert sich die Zahl. Habe es bei mehreren Zahlenfeldern ausprobiert, war bei jedem so...

**Comment by barbalex** [comment]
Immer? Bei mir nie :-(

Das ist mit Chrome auf macOS, richtig?

**Comment by rebeccakurz** [comment]
Ja, genau.

**Comment by csalzmann** [comment]
z.B. bei Feldkontrolle, Anzahl. Passiert immer. PC, Firefox 55.0.3 (32-Bit)
![screenshot 12](https://user-images.githubusercontent.com/6047564/30903768-2bd8a8ce-a370-11e7-8e0b-805ccc896f55.png)

**Comment by barbalex** [comment]
Ja, auf Firefox kann ich das jetzt auch nachvollziehen

**Comment by barbalex** [comment]
o.k., offenbar benutzt Firefox nicht dieselbe API wie Chrome.

Habe das jetzt korrigiert, worauf bei mir Chrome, Firefox und Edge funktionieren, d.h. sich die Zahl nicht verändert.

Ich schliesse weider mal dieses Issue...

**Comment by barbalex** [comment]
Übrigens: die Anpassung ist jetzt erst in der Entwicklungsversion vollzogen - hoffentlich kann ich heute Nacht die Live-Version aktualisieren

**Comment by csalzmann** [comment]
Es gibt immer noch einige Zahlenfelder, in denen man scrollen kann. Das ist sehr fehleranfällig. 

Aktuell bei EKF:
Deckung überprüfte Art
Flächenanteil nackter Boden
Überprüfte Fläche

**Comment by barbalex** [comment]
Wie gesagt: Das Verhalten ist im HTML-Standard implementiert. Jegliches Abweichen davon wäre ein Hack und funktioniert im besten Fall unzuverlässig.

Ich kann vieles, aber nicht die Grundlagen der Web-Technologie umgehen :-(

**Comment by barbalex** [comment]
Mein obiger Kommentar mag wirken, als ob ich nicht dagegen machen würde. Dem ist nicht so:

- Dieser Issue hat schon ca. 8 Stunden Aufwand verursacht
- Der beste mir nach umfangreichen Recherchen bekannte Hack, um den HTML-Standard zu umgehen, ist realisiert: https://github.com/barbalex/apf2/blob/master/src/components/shared/TextFieldFormik.js#L34-L42

Es ist typisch, dass Versuche, Standards zu umgehen, besonders viel Aufwand geben: Weil wir eben gerade NICHT den Standard wollen, erleben wir regelmässig und unverhersehbar, wie Änderungen von Browser-Entwicklern und Entwicklern benutzter Software unsere Umgehung zunichte machen. Darum sagt man einer solchen Lösung auch "Hack". Manchmal hat man Glück und ein solcher Hack funktioniert relativ lange und zuverlässig. In diesem Fall scheint sich der ganze Aufwand definitiv nicht zu lohnen.

**Comment by barbalex** [comment]
Ich _glaube_, dass klappt mittlerweilen 🙏

**Comment by rebeccakurz** [comment]
Der Vollständigkeit halber: in den EK-Freiwilligen-Formularen geschieht es leider immer noch. Aber du kannst ja sowieso nichts machen oder?

**Comment by barbalex** [comment]
Diese Felder verwenden nicht dieselbe Vorlage, wie die übrigen, weil sie anders gesteuert werden (dieses Formular ist leider sehr komplex).

In diesen Feldern wurde eine andere Variante verwendet, um das Scrollen zu verhindern. Eine, die früher funktionierte, aber seit einem Update von Chrome nicht mehr.

Ist jetzt gleich unterdrückt wie bei den anderen Feldern. Will heissen: Wird sich gleich verhalten. Aber es gibt leider nach wie vor keinerlei Garantie, dass es "richtig" funktioniert, weil das Scrollen den HTML-Standard darstellt.

Danke für den Hinweis.

**Comment by barbalex** [comment]
Ist in Version 1.51.1 korrigiert.
