### ISSUE TITLE
Berichte -URL

### ISSUE THREAD

**Issue by wunderli** [barbalex/apf2#251]
Lieber Alex

Bei einigen Arten (wohl diese mit offiziellem AP des Kantons) gibt es "Berichte".
![bildschirmfoto 2019-02-19 um 08 47 36](https://user-images.githubusercontent.com/26789445/52998424-903e1c00-3423-11e9-9449-5c9a6a8da8bf.png)

Dies sind Einträge mit URL, bisher wohl alles nur Aktionspläne.
Leider hat aber der Kanton in der Zwischenzeit die Berichte verschoben, sodass es eine Fehlermeldung gibt.
![bildschirmfoto 2019-02-19 um 08 47 20](https://user-images.githubusercontent.com/26789445/52998640-0fcbeb00-3424-11e9-9684-e21931024651.png)

Die Aktionspläne sind neu hier downloadbar:
https://aln.zh.ch/internet/baudirektion/aln/de/naturschutz/artenfoerderung/ap_fl.html
![bildschirmfoto 2019-02-19 um 08 48 22](https://user-images.githubusercontent.com/26789445/52998675-2d00b980-3424-11e9-9842-3ab78261a230.png)

Charlotte meinte aber, dass es super wäre, wenn diese Berichte lokal auf dem "FloraDB-Server" abrufbar wären. Und dass wir auch andere "Berichte" wie z.B. Doktorarbeiten, ect. als PDF hochladen könnten.

Was könntest du uns da anbieten?
Wichtig wäre auch, dass es sicher keine defekten URLs hat, dann lieber noch weglassen, bis eine definitive Lösung gefunden wurde.

Liebe Grüsse

Anna

**Comment by barbalex** [comment]
Wir könnten gleich wie die für 2019 angedachten Bilder lösen: Man würde einen Bericht hochladen. Diese Dateien würden dann auf einen eigenen Server hochgeladen. Die URL würde dann nie ändern. Wenn wir das mit den Bildern dieses Jahr machen, ist es vermutlich nur 45 Minuten Aufwand für mich.

**Comment by csalzmann** [comment]
Ja, das fände ich sehr gut!

**Comment by barbalex** [comment]
@wunderli @rebeccakurz 
Jetzt kann man beim AP Dateien hochladen.

Ihr könnt also bei allen AP's:
- die AP-Berichte hoch-laden
- den "Bericht" im Navigationsbaum unter "Berichte" löschen. Er ist jetzt nicht mehr nötig

Wenn ihr das gemacht habt, teilt mir das bitte mit. Ich werde anschliessend diese Struktur ganz entfernen (es wurden bisher nur AP-Berichte erfasst).

Ich kann diese Struktur auch sofort entfernen, wenn ihr sie jetzt schon nicht mehr brauchen solltet.

Dann wird der Navigationsbaum übersichtlicher 😃

**Comment by rebeccakurz** [comment]
Super, das klappt tiptop!
Ich denke, du kannst die Struktur sofort entfernen, wenn bisher nur AP-Berichte erfasst wurden und diese Links sowieso veraltet sind.
@wunderli was denkst du?

**Comment by barbalex** [comment]
O.k., hab's gleich gemacht. War effizienter so. Sorry, dich zu übergehen, Anna 😓
