### ISSUE TITLE
Benutzer erfassen

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#252]
Ich habe vorher einen neuen Benutzer (Freiwilliger) erfasst und ihn auch mit der Werte-Liste verknüpft. Dann habe ich mich ab und wieder angemeldet. Dann habe ich seine Kontrollen von 2019 erstellt. Dabei kam jeweils die Meldung, dass kein Benutzer mit dieser Adresse verbunden ist. 
Am Schluss wollte ich unter "EKF sehen als" überprüfen, ob alle Kontrollen drin sind. Es hat aber keine neuen Kontrollen angezeigt. 
Dann habe ich mich ausgeloggt und das Browserfenster geschlossen. Dann wieder geöffnet und versucht mich als Freiwilliger anzumelden, das ging aber nicht. 
Also habe ich mich wieder als mich angemeldet und in der Benutzerliste nachgeschaut. Alle Angaben beim neuerstellten Benutzer sind wieder rausgeflogen. Also kein Name, keine Verknüpfung, kein Status. 
<img width="665" alt="bildschirmfoto 2019-02-20 um 09 11 21" src="https://user-images.githubusercontent.com/30288503/53076498-13c53f00-34f0-11e9-8368-45cb6de4b129.png">
<img width="640" alt="bildschirmfoto 2019-02-20 um 09 14 33" src="https://user-images.githubusercontent.com/30288503/53076504-16279900-34f0-11e9-80ba-46bc0e895987.png">
Könntest du dir das bitte anschauen? Ich habe ein paar Freiwillige, die die Eingaben elektronisch machen möchten (und bei den Orchideen ist das schon bald der Fall) und wir müssen ja auch bald neue Artverantwortliche hinzufügen.

**Comment by barbalex** [comment]
Dass Änderungen am Benutzer nicht gespeichert werden, habe ich korrigiert.

Es gibt aber glaube ich bei der Erfassung von Benutzern noch andere Probleme. Muss morgen weiter schauen.

Du kannst aber gerne selber probieren und hier melden, was schief läuft.

**Comment by barbalex** [comment]
Momentan stelle ich folgendes Problem fest: Erstellt man einen neuen Benutzer und vergibt sofort ein Passwort, wird es falsch (nicht verschlüsselt) gespeichert. Danach scheitert die Anmeldung.

Erstellt man den neuen Benutzer und vergibt erst danach ein Passwort, wird es korrekt (verschlüsselt) gespeichert. Danach gelingt die Anmeldung.

Ich muss dieses Problem noch lösen aber wenn du Passwörter erst in einem zweiten Schritt vergibst, solltest du arbeiten können.

**Comment by barbalex** [comment]
Abgesehen davon werden Fehler, welche die Datenbank beim Vergeben von Passwörtern meldet nicht angezeigt. Das passiert z.B. wenn das Passwort weniger als 6 Zeichen lang ist oder aus Zahlen besteht.

**Comment by rebeccakurz** [comment]
Also ich konnte nun zuerst den Benutzer erstellen, ohne ein Passwort zu setzten. Das hat geklappt. Dann habe ich mich abgemeldet, Browser-Fenster geschlossen. Wieder neu angemeldet und dann ein Passwort gesetzt. Es gab dann auch die Meldung, dass das Passwort gespeichert worden sei. Ich konnte mich dann aber nicht mit diesem neuen Benutzernamen und Passwort anmelden. 
Das war heute morgen. Nun habe ich nochmals ein neues Passwort gesetzt und nun konnte ich mich anmelden.

**Comment by barbalex** [comment]
Komisch. Wenn ich einen neuen Benutzer erstelle, scheitert das Passwort, wenn ich es direkt beim Erstellen des neuen Nutzers setze. Ich muss aber nicht mal neu laden, es reicht, wenn ich erst nach Erstellen des neuen Nutzers das Passwort ändere. Ich grabe weiter.

**Comment by barbalex** [comment]
Ich werde dieses Jahr die Autorisierung neu aufbauen. Dann wird das alles anders.

**Comment by barbalex** [comment]
Nochmals zusammengefasst:

1. Erstellt man einen neuen Benutzer und vergibt sofort ein Passwort, wird es falsch (nicht verschlüsselt) gespeichert. Danach scheitert die Anmeldung, weil sie das verschlüsselte Passwort mit dem unverschlüsselten vergleicht
2. Um 1. zu korrigieren, muss man das Passwort nochmals ändern
3. Erstellt man den neuen Benutzer und vergibt erst danach ein Passwort, wird es von Anfang an korrekt (verschlüsselt) gespeichert

**Comment by rebeccakurz** [comment]
Was heisst bei 3. konkret: "vergibt erst danach ein Passwort"? Was muss in der Zwischenzeit gemacht werden?

**Comment by barbalex** [comment]
Nächster Versuch, das aktuelle, fehlerhafte Verhalten zu erklären:

1. Erstellt man einen neuen Benutzer und vergibt sofort ein Passwort, wird es falsch (nicht verschlüsselt) gespeichert. Danach scheitert die Anmeldung, weil sie das verschlüsselte Passwort mit dem unverschlüsselten vergleicht
2. Setzt man ein **neues** Passwort, wird es korrekt verschlüsselt. Danach gelingt die Anmeldung
3. Das **neue** Passwort muss anders sein, als das zuvor gesetzte. Sonst wird es nicht verschlüsselt (damit wird verhindert, dass bereits verschlüsselte Passwörter nochmals verschlüsselt werden)
4. Falls also im ersten Anlauf das gewünschte Passwort gesetzt (und nicht verschlüsselt wurde), muss es in zwei Schritten korrigiert werden:
   1. zu einem Zwischen-Passwort korrigieren
   2. nun wieder das gewünschte setzen

**Comment by rebeccakurz** [comment]
Okay, ja so habe ich es bis jetzt auch gemacht, danke

**Comment by barbalex** [comment]
Soeben habe ich eeeeeeeeeeeeeeendlich herausgefunden, wie ich obiges Verhalten korrigieren kann. Von jetzt an sollte das Passwort immer schon beim ersten Mal verschlüsselt werden.

**Comment by rebeccakurz** [comment]
Super, vielen Dank!!
