### ISSUE TITLE
EKF - neues Jahr ab Januar

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#253]
Bei den EKF werden neu erstellte Kontrollen noch im Jahr 2018 angezeigt. Da müsste das Stichdatum für das neue Jahr ab Januar gelten.
<img width="471" alt="bildschirmfoto 2019-02-21 um 10 40 37" src="https://user-images.githubusercontent.com/30288503/53158975-29f0ff00-35c5-11e9-8d57-585f36b38653.png">

**Comment by barbalex** [comment]
Ist in der Entwicklungsversion umgesetzt. Werde wegen der schlechten Internet-Verbindung erst heute Abend aktualisieren

**Comment by barbalex** [comment]
O.k., ist gemacht

**Comment by rebeccakurz** [comment]
Lieber Alex

Danke, jetzt wird bei dem Freiwilligen, wenn ich mich als diesen einlogge, direkt das Jahr 2019 angezeigt. 
Aber leider werden die Erfolgskontrollen, die ich neu erstellt habe (nur mit Benutzer, ohne Datum, als Vorbereitung für die Kontrollen 2019, die der Freiwillige selber eingeben möchte), immer noch unter dem Jahr 2018 angezeigt und für 2019 erscheint die Meldung, dass es dieses Jahr keine Kontrollen gibt. 
Muss ich alle Kontrollen nochmals neu erstellen, damit es klappt?

**Comment by rebeccakurz** [comment]
<img width="649" alt="bildschirmfoto 2019-02-25 um 08 01 07" src="https://user-images.githubusercontent.com/30288503/53319785-e0115d00-38d3-11e9-897e-1a39d0a6c737.png">
<img width="1957" alt="bildschirmfoto 2019-02-25 um 08 01 39" src="https://user-images.githubusercontent.com/30288503/53319791-e273b700-38d3-11e9-9161-c5e6ca1f1953.png">

**Comment by csalzmann** [comment]
Lieber Alex
Könntest Du mal schauen, was da los ist? Wir hoffen schon nicht, alle Kontrollen nochmals erstellen, oder?

**Comment by barbalex** [comment]
Das Referenz-Datum kam an drei Orten vor und war von mir nur an einem Ort korrigiert worden.

Sorry :-(

Ist repariert.

**Comment by rebeccakurz** [comment]
Danke!
