### ISSUE TITLE
Curser Position wenn auf Pop geklickt

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#254]
Neu wird nach Öffnen einer Population der Ausschnitt oberhalb angezeigt und nicht wie vorher unterhalb

**Comment by barbalex** [comment]
> der Ausschnitt oberhalb

Was ist damit gemeint? Mir fehlt vermutlich der Zusammenhang um zu verstehen, was du meinst.

**Comment by barbalex** [comment]
Schliesse mangels Rückmeldung, um die Übersicht zu behalten
