### ISSUE TITLE
EKF: Neben dem Datum auch ein Feld für das Jahr ergänzen, wie bei Feldkontrollen

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#255]
Ich habe gerade eine alte Erfolgskontrolle kontrolliert, da im Export das Datum der ersten Kontrolle aus dem Jahr 2018 stammt und das Datum der letzten Kontrolle von 2017. In der Datenbank ist die erste Kontrolle aus dem Jahr 2013 (im Strukturbaum), im Formular der Kontrolle ist jedoch kein Datum eingetragen. 
Kann es sein, dass der Export einfach ein Datum eingetragen hat?
<img width="1375" alt="bildschirmfoto 2019-02-25 um 10 55 38" src="https://user-images.githubusercontent.com/30288503/53329550-98e39600-38ec-11e9-963a-4a1e4e0e08c7.png">

**Comment by rebeccakurz** [comment]
![bildschirmfoto 2019-02-25 um 11 01 17](https://user-images.githubusercontent.com/30288503/53329598-b44ea100-38ec-11e9-9b0f-7bb8f9480e29.png)

**Comment by barbalex** [comment]
Welche Art ist das?

**Comment by rebeccakurz** [comment]
Himantoglossum hircinum, TPop 16.4

**Comment by barbalex** [comment]
In diesem Fall ist irgendwie ein Jahr erfasst, aber kein Datum. Das ist in der aktuellen Benutzeroberfläche nicht möglich, aber war es wohl früher. Muss mal schauen, wie oft das vorkommt.

**Comment by barbalex** [comment]
Das kommt in 362 Freiwilligen-Kontrollen vor. Eine aus 2017, der Rest von früher.

**Comment by barbalex** [comment]
Es gibt total 4499 Freiwilligen-Kontrollen

**Comment by barbalex** [comment]
Was ist genau das Problem, dass wir lösen sollten?

**Comment by csalzmann** [comment]
Zwischenfrage.
Wieso kann man nicht mehr nur Jahr erfassen? Das war früher tatsächlich so. Natürlich ist es schöner mit Datum. Aber weshalb die Einschränkung eingebaut wurde, verstehe ich nicht.

**Comment by rebeccakurz** [comment]
Ich habe nochmals im Export nachgeschaut, das Datum von 2018 war bei "erste Kontrolle changed" drin. Also hat wohl noch jemand nachträglich etwas geändert (ich nehme an für einen Bericht). Hat mich nur sehr irritiert und der Export ist halt recht unübersichtlich... 
Aber damit erledigt sich wohl der Issue, wenn es reicht, wenn ein Jahr vorhanden ist und nicht unbedingt ein Datum gesetzt werden muss (oder musste).

**Comment by barbalex** [comment]
> Wieso kann man nicht mehr nur Jahr erfassen? Das war früher tatsächlich so. Natürlich ist es schöner mit Datum. Aber weshalb die Einschränkung eingebaut wurde, verstehe ich nicht

Weil das für die EKF eure Vorgabe ist: Das Formular wurde genau nach eurer Vorlage designt

**Comment by csalzmann** [comment]
Gibt es da noch einen Ausweg, dass man im Ausnahmefall doch auch nur das Jahr erfassen kann?

**Comment by barbalex** [comment]
Klar. Fragt sich, nur, wie es sein soll.

Am Einfachsten wäre: Man zeigt im Formular wie bei den EK immer beide Felder an. Im Ausdruck aus Platzgründen nur das Datum (ist ja dann auch leer, oder?).

Das gibt wohl eine gute Stunde Aufwand.

**Comment by csalzmann** [comment]
Ja gerne. Könntest Du in Prio nach hinten schieben, machen wenn noch Budget vorhanden ist. Ausser es zeigt sich auf einmal doch Dringlichkeit, dann sehen wir es ja.

**Comment by barbalex** [comment]
Ich glaube das ist erledigt
