### ISSUE TITLE
Filtern, allg. Fehler

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#256]
Es ist schwierig genau zu beschreiben was nicht läuft, aber beim Filtern hapert es noch immer.

RD hat mir gemeldet, dass es sie stört, dass wenn sie nach Pops filtert, immer frühere Vorschläge kommen. Obwohl in der Zwischenzeit Cache geleert. Siehe hier:

![bildschirmfoto 2019-02-27 um 18 29 05](https://user-images.githubusercontent.com/6047564/53510828-2e368400-3abf-11e9-9c4e-f02030cd703a.png)

Ich konnte das jetzt auch nachvollziehen. Beim 1. Mal filtern hatte ich keinen Vorschlag. Auf einmal kamen Vorschläge, die ich aber nicht unmittelbar eingegeben hatte, sondern irgendwann einmal früher. Auf jeden Fall nicht heute. Und nicht bei dieser Art. Ich probiere aktuell bei Aldrovanda, weil da RD sagte, sie hätte Probleme gehabt. Interessant. Ich denke, meine Vorschläge kommen wahrscheinlich von Liparis.

![bildschirmfoto 2019-02-27 um 18 38 02](https://user-images.githubusercontent.com/6047564/53510852-3d1d3680-3abf-11e9-97ed-3bf1beac3be5.png)

Vielleicht hilft dies ja allgemein dem Problem beim Filtern. Da ist ein geheimer Cache irgendwo;)!

Zuvor, als ich RDs Fehler nachvollziehen wollte, ist mir das passiert (ich wollte Art filtern):

![bildschirmfoto 2019-02-27 um 18 25 04](https://user-images.githubusercontent.com/6047564/53510903-558d5100-3abf-11e9-9fbb-1527a615cfea.png)

**Comment by barbalex** [comment]
Das ist ein reines Textfeld. Dafür ist in apflora nichts solches implementiert. Hingegen gibt es Browser/Betriebssysteme, welche solche Funktionalitäten implementieren.

Du musst das also deinem Browser oder Mac abgewöhnen.

Ich schliesse den Issue als Duplikat von https://github.com/barbalex/apf2/issues/233
