### ISSUE TITLE
Alle Einträge verdoppelt

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#257]
Es ist ziemlich der Wurm drin.
Ich hatte heute die Übergabe meiner AP-Arten an die neue Artverantwortliche, und da haben sich 2x alle Eingaben innerhalb einer TPop verdoppelt. Ich kann Dir nicht sagen, wie ich das reproduzieren soll. Ich hab einfach nur auf die TPop geklickt und wollte sie öffnen. 

![bildschirmfoto 2019-02-28 um 15 11 16](https://user-images.githubusercontent.com/6047564/53577118-61d3e580-3b75-11e9-97c4-678a5f03e87c.png)

![bildschirmfoto 2019-02-28 um 15 49 26](https://user-images.githubusercontent.com/6047564/53577127-64ced600-3b75-11e9-9953-4278dc180b0b.png)

**Comment by csalzmann** [comment]
oben Potamogeton, unten Gladiolus palustris

**Comment by csalzmann** [comment]
OK, jetzt grad wieder passiert. Habe bei Potamogeton 107.5 als Methode bei EK als "gezählt" eingegeben, anschliessend auf 107 und alle TPop öffnen.
Methode gezählt ist nicht gespeichert, dafür wieder alles doppelt.

![bildschirmfoto 2019-02-28 um 16 29 31](https://user-images.githubusercontent.com/6047564/53577495-10782600-3b76-11e9-9b4e-6726c72f3858.png)

**Comment by csalzmann** [comment]
ups. nein, Methode ist ja gespeichert. Aber Zwischenbeurteilung nicht. Allerdings, will jetzt nicht meine Hand ins Feuer legen.. (ich glaube aber schon, dass ich die Zwischenbeurteilung vorher ergänzt habe)

**Comment by csalzmann** [comment]
Lieber Alex
Das Problem besteht immer noch. Kannst Du bitte mal schauen?
Danke!

**Comment by barbalex** [comment]
Bei mir passiert das bisher nicht :-(

**Comment by csalzmann** [comment]
Bei mir passiert das bei Chrome und Firefox, immer jetzt.

Du gehst mit dem Cursor auf eine TPop, re Maustaste, alle öffnen

![bildschirmfoto 2019-03-05 um 15 40 25](https://user-images.githubusercontent.com/6047564/53813340-b3a5b280-3f5d-11e9-8f06-670d52a250ee.png)

danach ist alles doppelt
![bildschirmfoto 2019-03-05 um 15 47 12](https://user-images.githubusercontent.com/6047564/53813456-fe272f00-3f5d-11e9-96a0-e524c879dfcc.png)

**Comment by barbalex** [comment]
Du hast in der ersten Meldung explizit gesagt:

> Ich hab einfach nur auf die TPop geklickt und wollte sie öffnen

Und das habe ich über und über versucht, nachzuvollziehen.

Passiert es also nur, wenn:

> Du gehst mit dem Cursor auf eine TPop, re Maustaste, alle öffnen

?

Es ist wichtig für mich, das zu wissen. Je nachdem muss ich den Fehler an ganz unterschiedlichen Orten suchen. Es nützt nichts, wenn ich die "alle öffnen" Funktion ändere, wenn der Fehler ganz grundsätzlich beim Aufbau des Baums liegt.

**Comment by barbalex** [comment]
Ich kann jedenfalls nachvollziehen, dass "alle öffnen" diesen Fehler provoziert.

**Comment by csalzmann** [comment]
ein Missverständnis! Ich hab in der zweiten Meldung präzisiert, dass ich "anschliessend auf 107 und alle TPop öffnen" gemacht habe.
Sorry, es ist halt auch nicht immer einfach, Fehler zu melden.. 

Es passiert nicht einfach bei auf TPop klicken, sondern wenn man "alle TPop öffnen"

**Comment by barbalex** [comment]
"und alle TPop öffnen" hatte ich nicht mit einem Menü in Verbindung gebracht.

Wie einfach man aneinander vorbei reden kann :-(

**Comment by barbalex** [comment]
Das mühsame an diesem Befehl ist, dass er alle Knoten _aller_ tieferen Ebenen öffnet. Das heisst, dass potentiell sehr viele Daten geladen werden.

Das sind potentiell sehr viele Daten und sehr viele Knoten im Baum.

Deshalb kann es sehr lange dauern, diese Daten alle zu laden und den neuen Baum aufzubauen.

Das ist dann auch nicht benutzerfreundlich, denn:

- es dauert lange
- es öffnet potentiell so viele Knoten im Baum, dass das Ergebnis den Benutzer überfordert
- je nach Datenmenge kann der Vorgang potentiell die Anwendung einfrieren und gar zum Absturz bringen.

Wäre es nicht besser, wenn einfach die nächste Ebene geladen und geöffnet würde?

Würde man den Befehl auf Ebene Population ausführen, würden dann alle Populationen geöffnet.

Man könnte auch noch die übernächste Ebene öffnen. Im Beispiel würden dann auch noch alle Teilpopulationen, Pop-Berichte und Pop-Massnahmen-Berichte aller Populationen geöffnet. Was vermutlich den Benutzer bereits überfordert.

Was meinst du?

**Comment by barbalex** [comment]
Na ja, die übernächste Ebene müsste es schon sein. Die nächste wird ja schon geöffnet, wenn man einfach den Ordner öffnet...

**Comment by barbalex** [comment]
O.k., der Fehler ist repariert. Bei den Pops werden nun nur noch die TPops selbst geöffnet, nicht deren unter-Knoten. Dadurch dauert es viel weniger lange und Abstürze durch zu viel Daten sind nun sehr unwahrscheinlich.

**Comment by barbalex** [comment]
...und das Ergebnis ist viel übersichtlicher

**Comment by barbalex** [comment]
Übrigens: ich nutze vermehrung.apflora.ch um:

- neue Sachen auszuprobieren
- bestehende Lösungen zu hinterdenken und wo möglich besser aufzubauen

Die Lösung zu diesem problem war genau, die Methode, die ich für vermehrung.apflora.ch neu erdacht hatte, anzuwenden.

**Comment by csalzmann** [comment]
also eigentlich fand ich es schon gut, wenn sich alle Knoten geöffnet haben. Dann hat man alle Zahlen von allen Kontrollen aufs Mal gesehen, das hat mich an der Sache meist interessiert.

Aber bevor ich reklamiere, wollte ich erst mal schauen, wie es a
usschaut. Musst du das denn zuerst live schalten? Bei mir wird immer noch alles verdoppelt..
Bsp. Ophrys araneola
![bildschirmfoto 2019-03-06 um 17 00 42](https://user-images.githubusercontent.com/6047564/53895034-6e52b500-4031-11e9-88ea-5eb77662e4be.png)

**Comment by csalzmann** [comment]
dass sich für Dich Synergien ergeben, finde ich natürlich super!!

**Comment by barbalex** [comment]
> Musst du das denn zuerst live schalten?

Jein.

Bei dieser Stufe hatte ich noch etwas vergessen. Auf der Entwicklungsversion ist das seit Stunden korrigiert. Aber noch nicht live geschaltet, weil ich vieles wegen der Performance änderer, was noch nicht getestet ist.

**Comment by barbalex** [comment]
> Dann hat man alle Zahlen von allen Kontrollen aufs Mal gesehen, das hat mich an der Sache meist interessiert.

Also bei den Arten, bei denen ich das getestet habe, hat sich das über ca. 10 Bildschirmhöhen meines 32-Zoll Bildschirms verteilt und für mich war das überhaupt nicht übersichtlich.

Ausserdem hat es die Anwendung beinahe zum Absturz gebraucht. Es ist nicht sinnvoll, funktionen einzubauen, die locker viel zuviele Datensätze laden und verarbeiten müssen, was zu Abstürzen führen kann.

**Comment by csalzmann** [comment]
Ja da hast du auch recht. Es ist deine Aufgabe uns zu sagen, wenn wir zu viel wollen und dadurch die Datenbank unstabil machen. Lieber weniger, dafür stabil.
Dann warten wir mal auf die live-Version:).

**Comment by barbalex** [comment]
Ist live geschaltet
