### ISSUE TITLE
Fehlermeldung bei Klicken auf TPop

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#258]
Ich bekomme eine Fehlermeldung, wenn ich auf eine Teilpopulation klicke. Die Angaben zu den TPops werden nicht angezeigt. Habe es bei verschiedenen Arten ausprobiert, auch bei der Testart.
<img width="1725" alt="bildschirmfoto 2019-03-07 um 07 36 22" src="https://user-images.githubusercontent.com/30288503/53937075-46ecfe00-40ac-11e9-850d-2215e468eab8.png">

**Comment by rebeccakurz** [comment]
neu laden der Seite, Cache leeren, abmelden, Browser schliessen hat nichts genützt

**Comment by barbalex** [comment]
Ist repariert

**Comment by barbalex** [comment]
Das war Kollateralschaden, verursacht durch die Versuche, die Performance zu erhöhen.

Dieser Fehler hätte sehr einfach durch einen geeigneten Test aufgefangen werden können.

Ich habe soeben angefangen, Test zu bauen.
