### ISSUE TITLE
Massnahmen: Ansiedlung und Ansaat im Menü nicht mehr anbieten

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#259]
In unserer internen Anleitung haben wir schon lange festgelegt, dass Ansiedlungen und Ansaaten als 2 Massnahmen zur gleichen TPop aufzunehmen sind. Du musst diese Auswahlmöglichkeit ja nicht löschen (sie wurde früher tatsächlich verwendet), aber einfach nicht mehr anbieten, so dass sie gar nicht gewählt werden kann.

**Comment by barbalex** [comment]
Das ist relativ aufwändig, weil das Auswahlfeld sein Auswahl anpassen muss, wenn ein Wert "historisch" ist aber in diesem Datensatz gewählt wurde. Sonst würde der existierende Wert nicht mehr angezeigt.

Es fragt sich auch, ob das nicht bei allen Dropdown-Listen passieren kann.

Die aufwändige Änderung würde sinnvollerweise gleich in allen Auswahl-Feldern vollzogen. Sonst gibt es grossen Mehraufwand, wenn weitere Felder nachträglich so angepasst werden. Und es wäre eine neue Fehlerquelle, wenn Werte-Listen nicht alle wie bisher genau gleich funktionieren.

**Comment by csalzmann** [comment]
Ich verstehe nicht genau. Müssen wir alle Dropdown-Listen kontrollieren, ob es da noch Anpassungen gibt?

**Comment by barbalex** [comment]
> Müssen wir alle Dropdown-Listen kontrollieren,

Nein. Es heisst:
- Dropdown-listen haben in apflora eigene Tabellen (z.B. tpopkontrzaehl_einheit_werte)
- Alle Dropdown-Listen haben die gleiche Struktur
- Das ermöglich, Benutzeroberflächen und Code für alle nur ein mal zu bauen
- Ändern wir also etwas an ihrer Struktur, müssen wir das also für alle machen
- Dafür können auch alle von der Neuerung profitieren
- Man könnte also künftig in jeder Dropdown-Liste werte auf "historisch" setzen, wodurch sie in neuen Datensätzen nicht mehr gewählt werden können, in alten aber immer noch angezeigt werden

**Comment by csalzmann** [comment]
Ja, ich fände das sehr sinnvoll.

**Comment by barbalex** [comment]
@rebeccakurz 

In v1.32.0 ist das umgesetzt.

Im Anhang noch die Liste aller Massnahmen, welche den Typ "Ansiedlung: Ansaat und Auspflanzung" haben. Das müsst ihr wohl vom Issue holen, im Mail wird der Anhang nicht ankommen.
[tpopmassn.xlsx](https://github.com/barbalex/apf2/files/4452187/tpopmassn.xlsx)
