### ISSUE TITLE
Funktion "rückgängig machen"

### ISSUE THREAD

**Issue by jmenzi** [barbalex/apf2#26]
Ich fände es schön, wenn auch in der neuen Version - wie bisher in der alten Version - die Funktion "rückgängig machen" erscheinen würde, wenn etwas gelöscht oder verschoben wird. Sofern ich dies bisher gesehen habe, ist das in der neuen AP-Flora-DB noch nicht implementiert.

**Comment by barbalex** [comment]
Das Problem ist folgendes:

Seit die Datenbank korrekt konfiguriert ist, wird jeder abhängige Datensatz mitgelöscht, wenn ein Datensatz gelöscht wird. Ohne diese Einstellung kann Datenintegrität nicht gewährleistet werden und das wäre bestimmt viel schlimmer als versehentliche Löschungen manuell wiederherstellen zu müssen.

Diese Löschung abhängiger Daten kann nur SEHR aufwändig, komplex und fehlerträchtig rückgängig gemacht werden. Es ist auch gut möglich, dass diese Daten benutzerseitig noch gar nicht alle geladen wurden, das heisst: diese Funktionalität müsste serverseitig implementiert werden. Das passiert in der alten Version auch nicht.

Weil der Server vorher ja nicht weiss, ob nachher rückgängig gemacht werden soll, und es nachher nicht mehr möglich ist, gelöschte Daten automatisch herzustellen, müsste der Server jede Löschung über alle Hierarchiestufen hinweg vollständig protokollieren. Vorläufig habe ich keine Ahnung, wie ich das machen soll. Bestimmt wird die Anwendung viel komplexer und bedeutend langsamer.

Möglicherweise könnte ich die Anwendung (also benutzerseitig) so programmieren, dass sie vor einer Löschung alle abhängigen Daten vom Server lädt und somit theoretisch wiederherstellen könnte. Das wäre aber eine SEHR aufwändige Programmierung, weil wir in apflora 40 Tabellen haben und Abhängigkeiten über bis zu 6 Stufen hinweg gehen können (Projekt > Art > Population > Teilpopulation > Feldkontrolle > Zählung). Löscht man z.B. ein Projekt, wären wohl beinahe alle 40 Tabellen betroffen! Die Anwendung müsste für jeden Knoten dieses Abhängigkeitsbaums genau wissen, wie sie Daten wiederherstellt.

Der Benutzer sieht heute, wie die unmittelbar gelöschte Ebene wieder hergestellt wird, ist zufrieden, und merkt gar nicht, dass tiefer liegende Ebenen gelöscht bleiben :-(

**Comment by barbalex** [comment]
Ich glaube, wir müssen zwei Fälle unterscheiden:

- den gelöschten Datensatz wiederherstellen
- alle abhängigen Daten des gelöschten Datensatzes wiederherstellen

Wie oben gesagt, kann die aktuelle Anwendung ersteres. Und das zweite automatisch zu lösen wäre SEHR aufwändig. Es ist auch manuell ziemlich aufwändig... Aber: wenn man das braucht, müsst ihr mir mailen. Dann mache ich das mit Hilfe der letzten Datensicherung.

Ich notiere mal, wie es funktionieren könnte, nur den gelöschten Datensatz wiederherzustellen:

- im "state" gibt es ein Array "deletedRows"
- vor jeder Löschung wird hier der zu löschende Datensatz eingefügt (Objekt mit: table, row)
- im Menü oben rechts in der Anwendung gibt es einen neuen Punkt: "Löschungen wiederherstellen"
- klickt man darauf, öffnet sich die Liste der während der aktuellen Sitzung (seit die Benutzerin die Anwendung geöffnet hat) zuletzt gelöschten Datensätze
- die Benutzerin kann jeden dieser Datensätze wiederherstellen lassen

Das ist leistungsfähiger als heute.

@jmenzi @csalzmann: was meint ihr dazu?

**Comment by barbalex** [comment]
@jmenzi @csalzmann

Sollten automatische Wiederherstellungen inklusive abhängigen Datensätzen dringlich sein, könnte die obige Methode ausgeweitet werden:

- die Objekte im state deletedRows, können auch ein Feld "children" enthalten
- wird ein Datensatz gelöscht, _für den die Löschung inklusive abhängigen Datensätzen implementiert ist_, werden zwei Objekte geschaffen: eine mit "children" und eine ohne
- in dieses Feld "children" werden beim löschen die abhängigen Datensätze geschrieben
- wählt die Benutzerin die Wiederherstellung mit "children", kann die Anwendung alles wiederherstellen

Diese Wiederherstellung muss aber für jeden Knoten im Strukturbaum relativ aufwändig programmiert werden.

Mit anderen Worten: das lohnt sich nur für Fälle

- die ihr unbedingt wollt
- wenn viele Daten erfasst wurden, die noch nicht in der letzten Datensicherung enthalten sind (und somit nicht manuell wiederhergestellt werden könnten)
- für häufige Fälle

**Comment by csalzmann** [comment]
Ich glaube, wir sprechen nur vom einfachen Fall.. Ich persönlich musste das auch noch nie in Anspruch nehmen, aber es gibt eine gewisse Sicherheit. 

Wie steht es denn mit den Backups genau? Könnte man etwas wieder holen oder wenigstens einen alten Stand nochmals anschauen? Wiederholen geht ja nur, wenn nicht andere Leute gleichzeitig oder danach an der Datenbank waren, stelle ich mir so vor.

**Comment by barbalex** [comment]
Backups werden automatisch jeden Tag um 23 Uhr erstellt. Das funktioniert 99% der Zeit. Nur sporadisch, wenn der Server neu aufgesetzt wurde oder grössere Änderungen daran durchgeführt wurden, kommt es vor, dass eine Sicherung ausfällt. Nach ein paar Monaten fange ich an, die Sicherungen auszudünnen, damit sie nicht zu viel Speicher beanspruchen.

Ich kann bei mir in wenigen Minuten eine Datenbank inklusive Benutzeroberfläche erstellen, welche den Stand einer beliebigen Sicherung darstellt.

Wenn ihr das bei euch machen können wollt, müsste ich dir das mal zeigen und gleich eine Anleitung schreiben. Es ist keine Hexerei, wenn auch nicht ganz simpel. Und ich kann dir die Ordner mit den Sicherungen auf der Dropbox freigeben. 

Aus einer solchen Wiederherstellung kann ich dann Exporte laufen lassen.

Oder nach eurem Wunsch Daten auf dem live Server beruhend auf der Sicherung ändern. Das allerdings würde ich niemandem anderem empfehlen - weil man dabei recht viel falsch machen kann.

**Comment by barbalex** [comment]
Rein theoretisch könnten wir einen zweiten Server betreiben (z.B. https://backup.apflora.ch), dessen Datenbank man jederzeit mit einer beliebigen Sicherung überschreiben kann. Ich glaube zwar nicht, dass sich dieser Aufwand lohnt. Aber falls ihr das wollt, wäre es möglich.

**Comment by barbalex** [comment]
Übrigens: Verschieben konnte man bisher nicht rückgängig machen.

Na ja, schon: indem man das Objekt einfach wieder zurückschiebt.

Ich gehe also nicht davon aus, dass das hier gemeint ist.

**Comment by barbalex** [comment]
Die Wiederherstellung ohne abhängige Daten ist umgesetzt: Solange man die Seite nicht neu lädt, kann man jederzeit alle Löschungen der aktuellen Sitzung unter dem Menu oben rechts auflisten und wiederherstellen.

Das funktioniert natürlich nur, wenn der strukturell höher liegende Datensatz nicht auch gelöscht wurde.
