### ISSUE TITLE
Kartentool: Klick auf Gemeinde zeigt deren Namen an

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#260]
2. Prio

**Comment by barbalex** [comment]
Bei mir werden die Gemeindegrenzen angezeigt. Sie erscheinen aber erst, wenn man etwas rein zoomt. Die Grenzen sind ein wms-Dienst des Kantons Zürich. Ich kann Farben und Zoom-Grenze nicht beeinflussen.

**Comment by barbalex** [comment]
Schliesse, weil es implementiert ist, bei mir funktioniert und niemand das Problem mehr gemeldet hat

**Comment by csalzmann** [comment]
So nützen uns die Gemeindegrenzen nicht viel. Ich sehe die Grenzen schon, weiss aber trotzdem nicht, in welcher Gemeinde ich mich befinde. Kann man die nicht mit einem Info-Tool anwählen?

**Comment by barbalex** [comment]
Aha, du willst also darauf klicken können und dann mitgeteilt erhalten, welche Gemeinde es ist. Das war nie implementiert. Werde bei Gelegenheit nachschauen, wie das realisiert werden kann. Hat aber wohl nicht oberste Prio.

**Comment by csalzmann** [comment]
Ja genau.

**Comment by barbalex** [comment]
Ist in v1.36.0 implementiert
