### ISSUE TITLE
Kontrollen: geschätzt/gezählt

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#261]
Mittelfristig: löschen, Zählungen zu "geschätzt" transferieren. Hat Auswirkungen auf Layout Protokollblätter.

**Comment by barbalex** [comment]
> Hat Auswirkungen auf Layout Protokollblätter

Auf welche? In EKF gibt es heute schon nur gezählt und geschätzt.

**Comment by csalzmann** [comment]
OK, hast recht. Aktuell gibt es keine Layout-Änderung mehr deswegen.

Kannst Du es so umsetzen?

**Comment by barbalex** [comment]
gemacht
