### ISSUE TITLE
Nach Filtern leeres Mittelfeld (Filteranzeige verschwunden)

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#264]
![Bildschirmfoto 2019-03-15 um 11 39 18](https://user-images.githubusercontent.com/6047564/54426010-1134be80-4717-11e9-9ea7-80677659fcb7.png)
Ich nehme an, es hat irgendwie mit Performance zu tun? Nach Reload auf jeden Fall wieder da.

**Comment by csalzmann** [comment]
OK, habe gerade gemerkt, es liegt tatsächlich an der Performance. Nach ca. 10 Sekunden ist die Filteranzeige wieder da.

**Comment by csalzmann** [comment]
Interessanterweise ist nachher das Filtersymbol bei "Daten" verschwunden

![Bildschirmfoto 2019-03-15 um 11 46 25](https://user-images.githubusercontent.com/6047564/54426657-b3a17180-4718-11e9-9f9c-1b24d5280438.png)

Nach Browsercache leeren jetzt wieder alles gut:)

**Comment by barbalex** [comment]
> Interessanterweise ist nachher das Filtersymbol bei "Daten" verschwunden

Das ist "by design": Ich habe angenommen, es wird nur gebraucht, wenn Daten angezeigt werden bzw. das Formular, in dem Daten angezeigt aber auch gefiltert werden kann. Das Symbol nützt an sich nichts, wenn das Formular nicht sichtbar ist: Man kann dann den Filter weder anzeigen noch ändern.

**Comment by barbalex** [comment]
> Nach ca. 10 Sekunden ist die Filteranzeige wieder da

apflora optimiert das Laden von Daten. Das heisst: Im Normalfall wird nur die Teilpopulation geladen, die gerade bearbeitet wird.

Willst du aber einen Filter setzen, müssen als Voraussetzung alle Teilpopulationen geladen werden. Daher dauert es einen Moment, bis das passiert ist und das Formular angezeigt wird.

Dass ich zum Filtern alle Daten lade und benutzerseitig filtere ist eine Umgehung eines Problems des für den Cache verwendeten Werkzeugs. Man könnte nämlich eigentlich den Filter der Datenbank überreichen und Server-seitig filtern lassen. Problem ist leider, dass die Cache-Implementation gefilterte Daten von den übrigen _separat_ speichert und dass Filtern darum den verwendeten Arbeitsspeicher viel mehr aufbläst als einfach alle Daten einmal zu laden. Da kann ich nichts dran ändern.

**Comment by csalzmann** [comment]
Ja. Wahrscheinlich ist das bei Dir alles viel schneller als bei uns. Und es ist wohl auch nicht jedes Mal gleich schnell/langsam, scheint mir.

**Comment by barbalex** [comment]
Ich schliesse diesen Issue, weil es ein Teil von https://github.com/barbalex/apf2/issues/200 ist. Womit dort jetzt auch auf diesen Issue verlinkt wurde

**Comment by barbalex** [comment]
> Ja. Wahrscheinlich ist das bei Dir alles viel schneller als bei uns. Und es ist wohl auch nicht jedes Mal gleich schnell/langsam, scheint mir.

Das hängt ab von:

- Geschwindigkeit, mit der der Server die Daten liefert. Sollte gemäss Überwachung stabil schnell sein
- Geschwindigkeit, mit der die Daten vom Server zum Benutzer übertragen werden. Das kann natürlich stark variieren. Vor allem, wenn sich viele Leute einen Internet-Anschluss teilen (ist das bei euch der Fall?)
- Leistungsfähigkeit und aktuelle Auslastung von Computer und Browser. Das kann stark variieren

Sicher ist, dass hier ca. 9000 Datensätze verarbeitet werden. Das ist nicht wenig.
