### ISSUE TITLE
Feldkontrollen, Zahlenfelder mit "Scroll-Funktion"

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#266]
Anz. Jungpflanzen, Überlebensrate

Ich bin mich gewohnt, mit der Maus zu scrollen, da kommen da auf einmal Zahlen rein.

**Comment by barbalex** [comment]
Tja, Chrome hat sein Verhalten geändert: https://www.chromestatus.com/features/6662647093133312

Ich muss herausfinden, wie ich das neu anders übersteuern kann. Denn: Dass es passiert entspricht dem Standard und den zu umgehen erweist sich als ziemlich aufwändig :-(

**Comment by barbalex** [comment]
Mögliche Lösung hier: https://codesandbox.io/s/n3scr

Aber: Momentan scheint es gar nicht zu passieren????

**Comment by csalzmann** [comment]
Nicht mehr! Umso besser! Ich close.
