### ISSUE TITLE
Feldkontrolle - automatisch Zählungsfeld generieren

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#267]
Wenn man eine Feldkontrolle macht, muss man ja immer 2x klicken, um erst eine Kontrolle und dann eine dazugehörige Zählung zu erstellen.
Könnte die Zählung nicht automatisch generiert werden? Hatten wir diesen Wunsch zu Beginn nicht auch schon mal?

**Comment by barbalex** [comment]
Duplikat von https://github.com/barbalex/apf2/issues/293
