### ISSUE TITLE
EK: Zählungen 0

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#27]
Wenn man bei EKs als Anzahl "0" eingibt, kommt als Text "keine Anzahl". Besser hier "0" einsetzen.

![bildschirmfoto 2017-04-28 um 13 47 25](https://cloud.githubusercontent.com/assets/6047564/25527517/5d96ddf0-2c19-11e7-9a9c-edb1ab467a91.png)

**Comment by barbalex** [comment]
in der Entwickungsversion gelöst, siehe https://github.com/barbalex/apf2/issues/23
