### ISSUE TITLE
Pro Kontrolle soll jede Einheit nur ein mal erfasst werden können

### ISSUE THREAD

**Issue by barbalex** [barbalex/apf2#273]
@csalzmann 

Im Auftrag für dieses Jahr ist enthalten:

> Überprüfung Zielerreichung: Mehrere Kontrollen mit Zählungen mit AP-Bericht-relevanter Einheit verhindern: Wählen können, welche ausgewertet wird, wenn mehrere erfasst wurden.

Als Teil dieser Massnahmen ist vorgesehen:

> Pro Kontrolle soll jede Einheit nur ein mal erfasst werden können

Um das durchzusetzen, muss ich in der Tabelle tpopkontrzaehl einen unique Index auf die ID der Kontrolle und die Einheit setzen.

Das ist aber erst möglich, wenn keine Datensätze existieren, die dem widersprechen. Und momentan gibt es 137 davon. Diese müssen also zuvor bereinigt werden. 

Ein kleiner Teil davon ist einfach, da Testarten. Aber der Rest sind echte Daten. Daher muss ich euch diese Aufgabe übergeben. Angefügt ist daher eine Datei mit allen 137 Zählungen. Um die angefügte Datei zu erhalten musst du diesen Issue wohl in GitHub öffnen.

Es drängt nicht wahnsinnig. Ich kann die übrigen Massnahmen unabhängig umsetzen.
[mehrfache_zaehlungen_mit_derselben_einheit.xlsx](https://github.com/barbalex/apf2/files/3265486/mehrfache_zaehlungen_mit_derselben_einheit.xlsx)

**Comment by csalzmann** [comment]
Ich habe kurz in die Daten geschaut. Es ist immer die grössere Anzahl zu nehmen, falls 2x gleich einfach eine auswählen. Sollen wir da durchgehen oder kannst Du das?

**Comment by barbalex** [comment]
Tja, das wäre sicher mit einer schlauen Abfrage machbar. Aber die ist ziemlich schwierig und aufwändig. Ich bitte euch, das zu machen.

**Comment by rebeccakurz** [comment]
Hoi Alex
Bevor ich die Liste durchgehe und die betroffenen Zählungen in der FloraDB anpasse wollten wir dich fragen, ob es nicht auch möglich und ausreichend wäre, wenn mit einer Qualitätskontrolle diejenigen Kontrollen aufgezeigt werden, in welchen eine Einheit mehrmals erfasst wurde?

**Comment by barbalex** [comment]
Ja, aber das ist aufwändiger, weil die Abfrage komplex ist und daher nicht direkt in der Benutzeroberfläche erfolgen kann. Ich musseinen serverseitigen View mit einer anwendungs-seitigen Abfrage kombinieren.

Nur den Index zu setzen braucht ca. 10 Minuten.

View plus Abfrage plus QK ca. 45 Minuten.

**Comment by rebeccakurz** [comment]
Okay, dann werde ich die Liste abarbeiten und die FloraDB entsprechend anpassen, so dass keine Zähleinheiten mehr doppelt in einer Kontrolle vorkommen. Ich werde dir dann Bescheid geben, sobald ich fertig bin. 
Dann ist also keine QK nötig, es ist ja vor allem bei älteren Einträgen der Fall, in neuerer Zeit ist es nicht mehr vorgekommen.

**Comment by rebeccakurz** [comment]
Hoi Alex

Ich bin gerade am Bearbeiten der Liste mit den doppelten Einträgen. Dabei ist mir aufgefallen, dass bei einigen Feldkontrollen bei den Zählungen im Strukturbaum korrekt dargestellt werden, im Formular aber die Zähleinheit nicht angezeigt wird (nur die Zählung und die Methode; siehe Screenshot). Ist das ein Darstellungsproblem?

Und dann ist mir auch noch aufgefallen, dass die doppelten Einträgen bei Abies alba alle bei einer TPop sind und dass ich sie dort nicht löschen kann! Ich habe die Einträge nun einfach verändert (das kann ich machen), so dass bei jedem Eintrag eine andere Zähleinheit ist. 

<img width="1009" alt="Bildschirmfoto 2019-10-23 um 08 23 45" src="https://user-images.githubusercontent.com/30288503/67387374-0d172c00-f597-11e9-9c54-aa1f058efd45.png">
<img width="923" alt="Bildschirmfoto 2019-10-23 um 08 23 58" src="https://user-images.githubusercontent.com/30288503/67387384-12747680-f597-11e9-8696-bec66f9adc26.png">

**Comment by rebeccakurz** [comment]
> Und dann ist mir auch noch aufgefallen, dass die doppelten Einträgen bei Abies alba alle bei einer TPop sind und dass ich sie dort nicht löschen kann! Ich habe die Einträge nun einfach verändert (das kann ich machen), so dass bei jedem Eintrag eine andere Zähleinheit ist.

Ich kann die Einträge doch löschen, aber nicht im Strukturbaum, sondern nur im EKF-Formular...

**Comment by rebeccakurz** [comment]
Ich wollte gerade: bei einer Teilpopulation bei einer Zwischenbeurteilung die Zählungen zusammenfassen, weil einmal "blühende Pflanzen geschätzt" und einmal "blühende Pflanzen gezählt" drin war. Als ich auf die eine Zählung geklickt habe hat es wie weiter oben beschrieben die Zähleinheit im Formular nicht angezeigt (nur im Strukturbaum). Also wollte ich diese nochmals einfüllen. In der Dropdown-Liste konnte ich aber die Zähleinheit "blühende Pflanzen" nicht auswählen, respektive es hat sie gar nicht als Möglichkeit angezeigt (siehe Screenshot)
<img width="1487" alt="Bildschirmfoto 2019-10-23 um 16 54 45" src="https://user-images.githubusercontent.com/30288503/67406655-a275e880-f5b6-11e9-9462-62e314aea4ba.png">
. 
Als ich dann auf die andere Zählung mit der gleichen Zähleinheit im Strukturbaum geklickt habe, erschien eine Fehlermeldung (siehe Screenshot)

<img width="1560" alt="Bildschirmfoto 2019-10-23 um 16 54 09" src="https://user-images.githubusercontent.com/30288503/67406611-92f69f80-f5b6-11e9-93f3-b1d5c772b392.png">

**Comment by rebeccakurz** [comment]
<img width="828" alt="Bildschirmfoto 2019-10-23 um 17 03 59" src="https://user-images.githubusercontent.com/30288503/67407006-229c4e00-f5b7-11e9-9e3c-f3d63678800b.png">
Nun habe ich etwas rumgeklickt und dann wieder in die gleiche Zählung, bei der ich vorher die Zähleinheit blühende Pflanzen nicht mehr auswählen konnte. Jetzt ist die Zähleinheit im Formular wieder vorhanden, dafür zeigt es sie im Strukturbaum nicht mehr an. Sie ist aber in diesem Fall immernoch irgendwo gespeichert, darum konnte ich sie wahrscheinlich auch nicht auswählen. 
Aber was bedeutet die Fehlermeldung?

**Comment by rebeccakurz** [comment]
<img width="794" alt="Bildschirmfoto 2019-10-23 um 17 07 39" src="https://user-images.githubusercontent.com/30288503/67407344-a3f3e080-f5b7-11e9-83e8-0a90967dc25a.png">

**Comment by barbalex** [comment]
Sorry Rebecca: mittlerweile ist das eine ganze Grosse Liste von Issues. Ich kann das nicht mehr effizient bearbeiten, denn wir verlieren völlig die Übersicht. Ich werde daraus mehrere machen und diese dann beantworten.

Bitte mach das künftig auch.

**Comment by barbalex** [comment]
> Nun habe ich etwas rumgeklickt und dann wieder in die gleiche Zählung, bei der ich vorher die Zähleinheit blühende Pflanzen nicht mehr auswählen konnte. Jetzt ist die Zähleinheit im Formular wieder vorhanden, dafür zeigt es sie im Strukturbaum nicht mehr an. Sie ist aber in diesem Fall immernoch irgendwo gespeichert, darum konnte ich sie wahrscheinlich auch nicht auswählen.

Was immer das war: Wir werden diese Situation mit Hilfe eines Index ausschliessen. Die Situation, die das jetzt ermöglicht hat, wird nicht mehr vorkommen können

**Comment by rebeccakurz** [comment]
Hoi Alex
Wir haben die Liste nun abgearbeitet und es sollte nun keine Doppelzählungen derselben Einheit in der gleichen Kontrolle geben.

**Comment by barbalex** [comment]
O.k., Index ist gesetzt :-)
