### ISSUE TITLE
Zählungen: keine erstellen oder löschen möglich

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#274]
Im Zug von Issue 273 wollte ich bei Camp. cervicaria TPop 101.2 eine doppelte Zählung löschen (ist hier sogar offensichtlich ein Fehler, wurde 2x "0" erfasst.
Dabei habe ich auch gemerkt, dass einfach das Kontextmenü zur Zählung nicht funktioniert, man kann weder löschen noch eine Zählung erfassen.

![Bildschirmfoto 2019-06-11 um 11 19 57](https://user-images.githubusercontent.com/6047564/59260149-5e9fc980-8c3b-11e9-999f-19b777a664fc.png)

**Comment by barbalex** [comment]
Wie hier beschrieben: https://github.com/barbalex/apf2/issues/202#issuecomment-443436050
- ist die implementierte Funktionalität bei den EKF extrem komplex
- ist sie im Formular implementiert, du kannst also dort löschen
- ist es nicht sinnvoll, diese komplexe Funktionalität doppelt zu implementieren, weil das
  1. sehr aufwändig ist
  2. sehr fehlerträchtig ist

...und genau deshalb habe ich diese Einträge ja damals entfernt.

**Comment by csalzmann** [comment]
OK, jetzt hab ichs auch gecheckt, dass ich im Formular löschen muss.
