### ISSUE TITLE
Nach Pop alle öffnen eingefroren

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#275]
Im Zusammenhang mit Issue 254 habe ich mal bei O. araneola auf Pop und mit Rechtsklick "alle öffnen" gewählt. Es sind zwar alle Pops erschienen, aber man konnte nichts mehr anwählen (FloraDB eingefroren). Auf weiteres klicken (man ist ja einfach so ungeduldig..) hat sich dann das Rechts-Klick-Menü verdoppelt. Die aufgelisteten Pops wieder verschwunden.

Ich gehe mal davon aus, es hat mit der Performance zu tun, dass ich das System überlastet hab? Müsste aber eigentlich schon gehen, oder? Musste neu laden, dabei ist Filter auf Art (natürlich) rausgefallen.

![Bildschirmfoto 2019-06-11 um 12 10 05](https://user-images.githubusercontent.com/6047564/59263866-31a2e500-8c42-11e9-9144-294b069ee9c3.png)

**Comment by barbalex** [comment]
Du hast recht. Das ist schlecht. Aber leider unausweichlich:

Nehmen wir an, du öffnest Ophrys araneola. Dann klickst du beim Populations-Ordner auf "alle öffnen". 

In diesem Moment hast du im Strukturbaum 3 Knoten offen (AP Flora KT. ZH, Aktionspläne, Ophrys araneola), 592 werden angezeigt.

apflora muss nun:
- den Populations-Ordner öffnen
- alle 119 Populationen öffnen
- alle 119 Ordner für Teil-Populationen öffnen
- alle 224 Teil-Populationen öffnen
- alle 119 Kontroll-Berichte-Ordner öffnen
- alle 119 Massnahmen-Berichte-Ordner öffnen

Am Ende dieses Vorgangs werden im Strukturbaum 2'810 Knoten angezeigt.

Nicht nur sind das 2'218 mehr als zuvor: Die meisten davon zeigen an, wieviele Datensätze eine Ebene tiefer liegen. Also musste im Hintergrund für ca. 2'000 Datensätze abgefragt werden, wieviele abhängige Datensätze eine Ebene tiefer liegen. Das sind rund 2'000 unabhängige, nacheinander ausgeführte Abfragen! Wenn du den Vorgang beobachtest, merkst du auch, dass die Anwendung den grössten Teil der Zeit für diesen Vorgang verwendet: Das ist die Zeit, während der in den Ordnern statt Zahlen in den Klammern nur Punkte angezeigt werden.

Was ich erstaunlich finde, ist dass diese riesige Menge an Informationen offenbar als nützlich empfunden wird. Es sind so viele Informationen, dass die frühere Version von apflora beim Versuch, sie anzuzeigen jedes mal abgestürzt wäre. Die aktuelle Version schafft es (bei mir), weil der Strukturbaum nur diejenigen Datensätze aufbaut, die sich im sichtbaren Bereich befinden.

Leider kann man diese Logik (momentan) nicht auf die Abfragen ausweiten. Und weil alle 2'000 Abfragen nacheinander ausgeführt werden, ist die Anwendung verständlicherwiese überfordert: die CPU deines Computers wird auf 100% beschleunigt und je nach deren Leistungsfähigkeit ist nach ein paar Sekunden alles i.O. Oder es passieren wundersame Dinge...

Diese Funktion ist also für Aktionspläne mit sehr vielen Populationen und Teil-Populationen schlicht nicht sinnvoll. Bloss kann die Anwendung das nicht zuvor selber herausfinden und den Benutzer informieren, wenn das so ist, denn:
1. Müsste die Anwendung alle Abfragen ausführen, um zu wissen, wieviele Abfragen sie ausführen muss. Aber das ist gerade der Vorgang, der die App zu Erliegen bringt
2. Ob die CPU belastet oder über-belastet wird, hängt von der Leistungsfähigkeit des PC's und dessen übrige Belastung ab. Was apflora nicht wissen kann

Die logische Schlussfolgerung müsste sein:
- Deutlich weniger Knoten zu öffnen (z.B. die Teil-Populationen selber nicht)
- Oder: die Funktion abzuschaffen

**Comment by barbalex** [comment]
Ich schliesse diesen Issue. Grund:
1. Ich kann ihn nicht weiter beeinflussen, ausser auf die Funktion ganz zu verzichten
2. Wer dem Problem begegnet, findet es hier dokumentiert, auch wenn der Issue geschlossen ist
