### ISSUE TITLE
TPop Exporte werden nicht exportiert

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#279]
obwohl Meldung kommt "Export wird vorbereitet.."

**Comment by barbalex** [comment]
Richtig. Mega komischer Fehler. Er passiert nur in der produktiven Version und nicht in der Entwicklungsversion. Und trifft alle Exporte.

Ich habe herausgefunden, dass es an einer verwendeten externen Software liegt (https://github.com/exceljs/exceljs/issues/871), und zwar an einer Änderung, die dort am 3. Mai vorgenommen wurde. Vermutlich funktionieren die Exporte schon seit wenig später nicht mehr.

Danke für die Meldung, ist nun korrigiert.

**Comment by rebeccakurz** [comment]
Okay, vielen Dank! Die Exporte haben nun geklappt!
