### ISSUE TITLE
Layer Pflegeplan GISBrowser

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#28]
Könntest Du evtl auch den Pflegeplan des GIS Browsers als Layer einblenden? Die Legende müsste da aber separat mitkommen, sonst kommt man nicht draus. Im Moment versuche ich gerade, TPops und Pflegeplan von Auge übereinanderzubringen..

**Comment by barbalex** [comment]
Ist in der Entwicklungsversion umgesetzt (na ja, mal ganz einfach). Es dauert aber eine Weile, bis die Live-Version aktualisiert wird, da gerade die Beobachtungen umgebaut werden
