### ISSUE TITLE
kml Exporte Koordinaten

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#280]
sind in Dschibuti lokalisiert

**Comment by barbalex** [comment]
Da hätten wohl nicht einmal unsere TWW-Arten Freude...

Ist korrigiert.

Bin überrascht, dass irgend jemand noch mit kml arbeitet: Mit dem TPop-File ist Google Earth auf meinem sehr leistungsstarken PC völlig überfordert...
