### ISSUE TITLE
Eierlegende Wollmilchsau ohne Vorschläge

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#281]
(Bitte tippen für Vorschläge) funktioniert nicht -> keine Artauswahl möglich

**Comment by barbalex** [comment]
Tja, da funktioniert Server-seitig ein Zusatz nicht, der das Filtern nach Eigenschaften in verbundenen Tabellen ermöglicht :-(

Das ermöglichte, dass nur diejenigen Arten mit AP angezeigt wurden. Ich habe eingestellt, dass alle Arten in der Liste erscheinen. Nun klappt es wieder.

**Comment by barbalex** [comment]
Unsere Datenbank (PostgreSQL) hat sich in den letzten zwei Jahren sehr stark weiterentwickelt. Auch bezüglich Leistungsfähigkeit.

Ich habe nun ausprobiert, wie stark der Server durch die Eierlegende Wollmilchsau belastet wird. Und siehe da: Die CPU wird nur noch zu 20% ausgelastet (sie ist auch doppelt so stark wie früher).

Daher habe ich nun auch die Eierlegende Wollmilchsau für alle Arten wieder freigeschaltet. Es dauer einfach ca. 2 bis 3 Minuten, bis das Resultat bereit ist.
