### ISSUE TITLE
Fehlermeldungen auf Startseite

### ISSUE THREAD

**Issue by wunderli** [barbalex/apf2#283]
Beim Öffnen der FloraDB werden folgende Fehlermeldungen angezeigt:

![claccchdddjopofc](https://user-images.githubusercontent.com/26789445/62603459-3d372300-b8f6-11e9-8801-ef1da99b12a7.jpg)

**Comment by barbalex** [comment]
...aber danach funktioniert es, richtig?

vom Handy

**Comment by wunderli** [comment]
Ja genau, also nicht dringend oder schlimm!

**Comment by barbalex** [comment]
Ich hoffe, das erfolgreich gelöst zu haben
