### ISSUE TITLE
Exporte funktionieren nicht!

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#284]
Lieber Alex

Anna und ich wollten heute den Export für das WebGISBun machen, aber leider funktioniert der Export aus der FloraDB nicht!
Wir haben dann verschiedene Browser, verschiedene Benutzer und verschiedene Exporte ausprobiert, aber es hat nicht funktioniert. Also auch die „normalen“ Exporte nicht. 
Der einzige Export, der geklappt hat, ist der kml-Export.

Da wir mit der Abgabe der Daten für das WebGISBun schon ziemlich hinterherhinken, wäre es super, wenn du dir das bald anschauen könntest.

Vielen Dank und liebe Grüsse
Rebecca

**Comment by barbalex** [comment]
Sorry, bin in den Ferien. Werde es nächste Woche prioritär angehen

**Comment by rebeccakurz** [comment]
Super, vielen Dank und noch weiterhin schöne Ferien!

**Comment by barbalex** [comment]
Das war wieder dasselbe wie in https://github.com/barbalex/apf2/issues/279. Ist in der soeben live gesetzten Version 1.9.5 repariert
