### ISSUE TITLE
Eingabe 0 nicht möglich

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#285]
Wenn man eine Zählung erfasst bei einer EKF ist die Anzahl 0 nicht möglich. (Im Strukturbaum wird es zwar richtig angezeigt, aber im Formular kann man keine 0 angeben.
Auch wenn man bei der Überlebensrate 0 angeben will, ist dies nicht möglich.

**Comment by barbalex** [comment]
Ist in v1.9.6 korrigiert
