### ISSUE TITLE
doppelte Einträge bei Zählungen

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#286]
![Bildschirmfoto 2019-08-05 um 15 15 20](https://user-images.githubusercontent.com/30288503/62612067-0ddce200-b907-11e9-9404-55eb097c83da.png)

**Comment by barbalex** [comment]
Wo ist das? Wie kann ich es provozieren?

**Comment by rebeccakurz** [comment]
Das passiert immer mal wieder, habe aber noch nicht herausgefunden, durch was es provoziert wird. Werde es wieder melden, wenn es passiert.

**Comment by barbalex** [comment]
Schliesse das. Nicht weil es nicht passiert, sondern weil diese Meldung mehr Infos enthält und ich diesen Issue von dort her verlinkt habe: https://github.com/barbalex/apf2/issues/298
