### ISSUE TITLE
Export für FloraDB mit zusätzlichen Feldern

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#288]
Hoi Alex
Wäre es möglich, dass in den Exporten für das WebGISBun (Teilpopulationen, Kontrollen und Massnahmen) auch die Felder "für AP-Bericht relevant" und "Grund für AP-Bericht (Nicht-)Relevanz" enthalten sind? Das würde das Reinigen der Exporte erheblich vereinfachen, da wir alle ausserkantonalen TPops aus dem Export löschen müssen.

Vielen Dank

**Comment by barbalex** [comment]
Ist in v1.9.7 umgesetzt.

Ihr solltet diese Felder vor der Auslieferung an die FNS entfernen. Daher habe ich sie klein geschrieben, damit sie auffallen.

Wäre es nicht besser, wenn die Abfrage filtern würde? (falls ja, bitte den Issue wieder öffnen)

**Comment by rebeccakurz** [comment]
Meinst du, dass die ausserkantonalen TPops gar nicht im Export enthalten sind? Wäre natürlich super, wenn das möglich wäre. 
Wir müssen auch die angesiedelt erloschenen TPops und die potentiellen Wuchsorte löschen. Vielleicht könnte man das dann auch schon vor dem Export machen?

Ich bin gerade noch an einem weiteren Issue dran, der den Export für das WebGISBun betrifft. Folgt in Kürze.
