### ISSUE TITLE
Feldtypen anpassen in Export für WebGISBun

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#289]
Wäre es auch noch möglich, die Feldtypen in den Exporten für das WebGISBun (Teilpopulationen, Kontrollen, Massnahmen) anzupassen, so dass die Quellfelder mit den Zielfeldern in der Abgabedatenbank übereinstimmen und wir die Daten mit einem einfachen Datenupload ins GIS laden können?

Folgende Felder müssten im Kontrollen-Export angepasst werden:
APARTID (Zeichenfolge) --> double
KONTRDAT (Zeichenfolge) --> Datum
KONTRAUFPLAN (short in) --> double
KONTRJUNGEPLANZEN (short in) --> double
KONTRCHANGEDAT (Zeichenfolge) --> Datum
POPNR (double) --> Zeichenfolge
TPOPNR (double) --> Zeichenfolge

Im Massnahmen-Export:
APARTID (Zeichenfolge) --> double
MASSNDAT (Zeichenfolge) --> Datum
MASSNPLAN (short in) --> double
MASSNCHANGEDAT (Zeichenfolge) --> Datum
POPNR (double) --> Zeichenfolge
TPOPNR (double) --> Zeichenfolge

Im Teilpopulationen-Export:
APARTID (Zeichenfolge) --> double
POPSTATUSUNKLAR (short int) --> Zeichenfolge
TPOPID (Zeichenfolge) --> double
TPOPSTATUSUNKLAR (short int) --> double
TPOPBERICHTSRELEVANZ (short int) --> double
TPOPCHANGEDAT (Zeichenfolge) --> Datum

Wäre das möglich und ein nicht so grosser Aufwand? Würde uns erheblich an Arbeit ersparen.

Vielen Dank für deine Rückmeldung!

**Comment by barbalex** [comment]
Formate existieren nur innerhalb von Software, welche sie sicherstellen kann. Ist ein Feld einmal exportiert, verliert es das Format.

Mit anderen Worten: Die Software, in die ihr offenbar importieren müsst, bestimmt, was sie will und unter welchen Bedingungen sie eine Zeichenfolge als ein bestimmtes Format erkennt.

Für `Datum` z.B. gibt es hunderte von Definitionen.

Wohin müsst ihr denn die Daten laden und wieso?

**Comment by rebeccakurz** [comment]
Wir müssen sie in ein Abgabe-File laden mit genau vorgegebenem Format (von Lieni), damit dass dann ins WebGISBun geladen werden kann (glaube ich).

**Comment by barbalex** [comment]
Kannst du mir so ein file schicken?

**Comment by rebeccakurz** [comment]
Kann ich machen. Musste jetzt allerdings dringend gehen, habe noch einen Termin. Bin am Mittwoch wieder im Büro...
Sorry und danke vielmals für deine Bemühungen!

**Comment by barbalex** [comment]
Bei euch besprochen
