### ISSUE TITLE
Untergeordnete Knoten öffnen

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#29]
Kann man diese Funktion wieder einführen?

**Comment by barbalex** [comment]
Im Prinzip schon.

Im Unterschied zu früher lädt die Anwendung nicht schon im Voraus alle Daten einer Art. Darum ist sie heute schneller.

Das heisst also: sollen alle untergeordneten Knoten geöffnet werden, muss die Anwendung

- auflisten, welche Daten geladen werden müssen, weil sie in untergeordneten Knoten vorkommen (können)
- alle diese Daten vom Server laden
- alle Knoten für diese Daten aufbauen und öffnen

Ist also ziemlich aufwändig :-(

Da dieses Feature in der aktuellen Version existiert, werde ich es kostenlos nachliefern. Es ist bei mir aber nicht oben auf der Prioritätenliste.

Bitte nachhaken, wenn es drängen sollte.

**Comment by barbalex** [comment]
Im Prinzip schon.

Im Unterschied zu früher lädt die Anwendung nicht schon im Voraus alle Daten einer Art. Darum ist sie heute schneller.

Das heisst also: sollen alle untergeordneten Knoten geöffnet werden, muss die Anwendung

- auflisten, welche Daten geladen werden müssen, weil sie in untergeordneten Knoten vorkommen (können)
- alle diese Daten vom Server laden
- alle Knoten für diese Daten aufbauen und öffnen

Ist also ziemlich aufwändig :-(

Da dieses Feature in der aktuellen Version existiert, werde ich es kostenlos nachliefern. Es ist bei mir aber nicht oben auf der Prioritätenliste.

Bitte nachhaken, wenn es drängen sollte.

**Comment by csalzmann** [comment]
Ich finde es schon ein angenehmes Feature. z.B. wenn ich nun TPop-Berichte machen muss. Da sehe ich dann auf einen Blick, welche TPops alle eine EK hatten und daraus, wo ich überall Berichte machen muss. Alternative: Alles von Hand selber öffnen oder über Qualitätskontrolle, die dann halt auch jedes mal wieder neu rechnet.

**Comment by barbalex** [comment]
o.k., ich hebe die Priorität etwas an ;-)

**Comment by csalzmann** [comment]
Danke :)

**Comment by barbalex** [comment]
Rückfrage:

> Darunterliegende Knoten öffnen

kann auf zwei Arten verstanden werden:

Beispiel: Du wählst diesen Befehl auf Ebene "Teil-Populationen":

Variante 1: Es werden alle Knoten der nächst tieferen Ebene geöffnet. In diesem Fall also alle Teil-Populationen. Du siehst eine Liste von:

- Anzahl Massnahmen
- Anzahl Massnahmen-Berichte
- Anzahl Feld-Kontrollen
- Anzahl Freiwilligen-Kontrollen
- Anzahl Kontroll-Berichte
- Anzahl zugeordnete Beobachtungen

Variante 2: Es werden _alle_ darunter liegenden Knoten geöffnet. Du siehst nun eine Liste von:

- alle Massnahmen
- alle Massnahmen-Berichte
- alle Feld-Kontrollen
  -  alle Zählungen
- alle Freiwilligen-Kontrollen
  - alle Zählungen
- alle Kontroll-Berichte
- alle zugeordnete Beobachtungen

Das Problem bei Variante 2 ist, dass - wenn es viele Daten gibt - die Sache unübersichtlich wird, weil sich die Daten potentiell über mehrere Bildschirmhöhen ausdehnen können. Nicht zu sprechen von den vielen Daten die geladen werden müssen.

Das Problem wird grösser, wenn du diesen Befehl auf Ebene Population, Art oder gar Projekt ausführst.

Spätestens beim Projekt dürfte die Anwendung _seeeehr_ lange laden und es könnte sein, dass der Server während einer Weile mit deiner Anfrage beschäftigt ist und daher andere auf ihre Anfrage warten müssen. Oder dass er gar hops geht. Immerhin würde er dann unter anderen diese Daten laden:

- 565 Arten
- 2'477 Ziele
- 5'690 Populationen
- 3'300 Populations-Berichte
- 2'600 Pop-Massn-Ber
- 10'320 TPop
- 6'800 TPopBer
- 4800 TPopMassnBer
- 10'600 TPopKontr
- 14'600 Zählungen
- 10'200 Massnahmen
- 5705 Beobzuordnungen

Das dürfte schlicht und einfach alles überfordern. Alles, ausser den Strukturbaum selbst, denn der dürfte selbst diesen Mengen gewachsen sein.

Es war früher eben so, dass beim Öffnen einer Art alle ihre Daten geladen wurden (ein Bruchteil der oben dargestellten). Und das dauerte bei datenreichen Arten nicht nur für diejenige Person lange, welche wartete. Sondern es überlastete teilweise während Sekunden den Server. Womit er für nichts Anders zur Verfügung stand. Darum lädt die aktuelle Anwendung immer nur die gerade nächste Ebene des Strukturbaums.

Darum plädiere ich dafür, dass ich die Variante 1 Umsetze.

Wer tiefer reinschauen will, müsste dann denselben Befehl jeweils eine Ebene tiefer nochmals ausführen.

Was meinst du?

**Comment by barbalex** [comment]
Ich habe jetzt Variante 1 umgesetzt und live geschaltet. Man kann bei folgenden Ebenen alle Knoten öffnen:

- Teilpopulationen
- Populationen
- AP-Ziele und AP-Zieljahre
- Arten (aber Vorsicht, wenn sie nicht gefiltert sind - die Anwendung lädt lange Daten und ist entsprechend nicht reaktiv)

Das sind glaube ich alle Ebenen, wo so was Sinn macht.

**Comment by barbalex** [comment]
Habe jetzt noch diesen Befehl in den Ordnern für Feldkontrollen und Freiwilligen-Kontrollen ergänzt.
