### ISSUE TITLE
Export WebGisBun: Filter ergänzen

### ISSUE THREAD

**Issue by barbalex** [barbalex/apf2#290]
Meinst du, dass die ausserkantonalen TPops gar nicht im Export enthalten sind? Wäre natürlich super, wenn das möglich wäre. 
Wir müssen auch die angesiedelt erloschenen TPops und die potentiellen Wuchsorte löschen. Vielleicht könnte man das dann auch schon vor dem Export machen?

Ich bin gerade noch an einem weiteren Issue dran, der den Export für das WebGISBun betrifft. Folgt in Kürze.

_Originally posted by @rebeccakurz in https://github.com/barbalex/apf2/issues/288#issuecomment-522635807_

**Comment by barbalex** [comment]
@rebeccakurz 
ist umgesetzt

**Comment by rebeccakurz** [comment]
Super, vielen Dank!
