### ISSUE TITLE
Fehlermeldung beim Erstellen von Freiwilligen-Kontrollen

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#291]
Wenn ich eine neue Freiwilligen-Kontrolle erstelle, erscheint folgende Fehlermeldung:
<img width="1057" alt="Bildschirmfoto 2019-09-02 um 17 17 29" src="https://user-images.githubusercontent.com/30288503/64124008-2d501900-cda6-11e9-8f6c-06c5926407d6.png">

Das Erstellen klappt aber anscheinend...
Vielleicht kannst du das bei Gelegenheit mal anschauen, wir werden in nächster Zeit vermehrt Freiwilligen- und Erfolgskontrollen erfassen müssen.

**Comment by rebeccakurz** [comment]
Kannst du das nachvollziehen? Diese Fehlermeldung erscheint bei mir auch, wenn ich auf eine bestehende EKF klicke. 
Verstehe nicht genau, was diese Fehlermeldung aussagt. Da wir in nächster Zeit viele EKF- (und Feldkontrollen-) Einträge machen müssen, wäre es super, wenn dabei kein Fehler auftritt.
Vielen Dank!

**Comment by barbalex** [comment]
Ja, ich hab das auch schon provoziert. Es hat aber für mich nicht oberste Prio gehabt und ich habe momentan alle Hände voll zu tun - in mehreren Projekten.

Aber: Nachhaken ist gut. Ich sollte künftig mindestens sichtbar machen, dass ich die Meldung gesehen aber nicht priorisiert habe.

**Comment by rebeccakurz** [comment]
Okay, alles klar. 
Ja solange die Kontrollen trotzdem korrekt gespeichert werden hat es nicht oberste Prio.

**Comment by barbalex** [comment]
O.k., sollte in v1.9.24 korrigiert sein (live in ca. 5 Minuten)
