### ISSUE TITLE
EKF Verifikation

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#292]
Frage zum Verständnis. Mich hat der Name irritiert und bin drum grad auf das nächste gekommen:

Das rot eingerahmte Kästchen ist ja eigentlich nicht eine komplette Verifikation, denn sie betrifft nur den Ausschluss vom Jahresbericht.

Korrekter wäre es, wenn man bei einer Verifikation auch ankreuzen müsste, ob die EKF für den JB verwendet werden soll oder ausgeschlossen wird. Da könnte ich mir mittels Export allenfalls auch noch eine Übersicht machen, wieviele der EKFs ich noch zu verifizieren habe.

Oder ist das doppelt gemoppelt, weil ich ja Kontrollbericht für alle nicht ausgeschlossenen EKFs machen muss?

Vielleicht dann "Verifikation" als Name präzisieren, z.B. "Ausschluss von Jahresbericht" oder so?

**Comment by barbalex** [comment]
> nicht eine komplette Verifikation, denn sie betrifft nur den Ausschluss vom Jahresbericht

Wie definierst du denn eine komplette Verifikation?

**Comment by barbalex** [comment]
> Korrekter wäre es, wenn man bei einer Verifikation auch ankreuzen müsste, ob die EKF für den JB verwendet werden soll oder ausgeschlossen wird.

Das Feld heisst (nach Rücksprache mit euch): "Im Jahresbericht nicht berücksichtigen". Ist das nicht eindeutig und unmissverständlich?

**Comment by rebeccakurz** [comment]
Charlotte meint, dass man für eine komplette Verifikation die Möglichkeit haben müsste, ja oder nein anzukreuzen. Denn wenn man jetzt nicht ja ankreuzt, weiss man nicht, ob die AV die Kontrolle nicht angeschaut haben oder ob sie okay ist und im Jahresbericht erscheinen soll.
"Im Jahresbericht nicht berücksichtigen" ist so schon gut, Charlotte meint den Begriff "Verifikation". Vielleicht könnte man das Feld umbenennen in z.B. "Ausschluss von Jahresbericht". Der Rest des Feldes würde gleich bleiben (also "im Jahresbericht nicht berücksichtigen" und "Wieso nicht?")
Oder man müsste eigentlich auch nicht unbedingt einen Titel setzen.

**Comment by barbalex** [comment]
> Oder man müsste eigentlich auch nicht unbedingt einen Titel setzen

Genau das habe ich jetzt auch gedacht. Und in v1.9.23 umgesetzt (ist in ca. 5 Minuten live).

Wenn ich euch richtig verstanden habe, ist damit die Sache klar und korrekt. Daher schliesse ich den Issue. Öffnet ihn wieder, wenn ich es falsch verstanden habe.
