### ISSUE TITLE
Neue Feldkontrolle, inkl neuer Zählung

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#293]
Es wäre super, dass wenn beim Erstellen einer neuen Feldkontrolle automatisch auch eine neue Zählung eröffnet wird. Das würde dem Benutzer einiges an Klicken reduzieren. Der Fall, dass man eine Feldkontrolle ohne Zählung will, gibt es ja praktisch nicht. Und falls doch, könnte man die erstellte leere Zählung immer noch löschen.

Ist das schwierig zu machen? Wäre wirklich sehr praktisch!

**Comment by barbalex** [comment]
Schwierig nicht. Aber es macht den Code kompliziert. 

Wieso? Es gibt ca. 50 Tabellen, in denen neue Datensätze erstellt werden. Das Schaffen neuer Datensätze ist an sich überraschend kompliziert. Denn es gibt viele Möglichkeiten, wie das schief gehen kann und die müssen alle abgefangen werden. Darum wurde dieser Code zusammengefasst.

Muss man nun für einige der 50 Tabelle spezielles Verhalten ergänzen, macht das diesen Code eben unübersichtlich und kompliziert. Entsprechend muss ich den Code sorgfältig strukturieren und kommentieren.

Nicht zu vergessen: Der Code, der neue Datensätze schafft, muss in diesem Fall sich selber nochmals aufrufen. Und wenn dann beim Schaffen der leeren Zählung etwas schief geht, muss das der Benutzerin auch verständlich erklärt werden - anders, als wenn die Feldkontrolle selbst nicht erstellt worden wäre.

Dann kommt noch hinzu, dass der Strukturbaum die neue Zählung gleich anzeigen soll.

Machbar ist es aber auf jeden Fall. Ich schätze es gibt inkl. Tests ca. 2.5 Stunden Aufwand.

**Comment by barbalex** [comment]
Ist in Version 1.52.0 umgesetzt

**Comment by rebeccakurz** [comment]
Super, vielen Dank!
