### ISSUE TITLE
Attribut "Gefährdung" auch für Feldkontrolle (nicht nur EKF)

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#294]
Bei den EKFs gibt es Felder, die auch für die Feldkontrolle sehr gut wären. Z.B. Gefährdung. Ich kann diese bei der Feldkontrolle nur ins allgemeine Bemerkungsfeld eintragen. Es wäre aber besser, ich könnte diese wichtige Bemerkung gleich dem richtigen Thema zuordnen, da kann man nachher auch danach suchen.

**Comment by barbalex** [comment]
Das gibt ein bisschen Aufwand, weil u.a. folgendes angepasst werden muss:
- Felddefinitionen für Cache (Zwischenspeicher)
- Felddefinitionen für GraphQL (die Abfragesprache)
- Alle App-internen Abfragen (das sind etliche)
- Filter-Formular
- Formular für Feldkontrolle
- Tests

Ich schätze eine Stunde Aufwand.

**Comment by barbalex** [comment]
Es gibt unwesentlich mehr Aufwand, mehrere Felder gleichzeitig so anzupassen. Überleg dir also bitte, ob das auch auf andere Felder zutrifft.

**Comment by barbalex** [comment]
Ist in v1.34.0 umgesetzt
