### ISSUE TITLE
Qualitätskontrolle führt zum Absturz

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#295]
Drücken auf die Qualitätskontrolle führt zu einem Totalabsturz (mit grossem roten Smiley). Nur Browserdaten löschen hilft da nachher wieder raus. Ich kann die Fehlermeldung nicht screenshotten, aber es heisst was mit "i ist not a function..".

**Comment by barbalex** [comment]
Ist in v1.9.21 korrigiert und live
