### ISSUE TITLE
Feld-Kontrollen: Jungpflanzen vorhanden kann nicht angekreuzt werden

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#296]
Habe gerade zwei neue Feldkontrollen erstellt und kann da das Feld "Jungpflanzen vorhanden" nicht ankreuzen. 
Zudem hat es mir das Jahr der Feldkontrolle nicht automatisch ausgefüllt (nachdem ich ein Datum eingegeben habe) bei der zweiten Feldkontrolle, die ich erstellt habe. Das hat bei der Feldkontrolle, die ich vorher erstellt habe, geklappt.

**Comment by barbalex** [comment]
Aua. Die für die Formular-Elemente verwendete Abhängigkeit hat offenbar bei einem kürzlichen Update undeklariert ihr Verhalten verändert.

Soeben wird v1.9.22 live gesetzt, worin das korrigiert ist.

Danke für die Meldung.

**Comment by barbalex** [comment]
Obiges bezog sich auf das Ankreuzen.

> Zudem hat es mir das Jahr der Feldkontrolle nicht automatisch ausgefüllt (nachdem ich ein Datum eingegeben habe) bei der zweiten Feldkontrolle, die ich erstellt habe. Das hat bei der Feldkontrolle, die ich vorher erstellt habe, geklappt.

Das kann ich nicht nachvollziehen und es funktioniert auch in den automatisierten Tests.

Wie kann ich es nachvollziehen?

Falls es nachvollziehbar ist: Bitte einen neuen Issue dafür öffnen. Es hat nichts mit dem Ankreuzen von ja/nein Feldern zu tun.

**Comment by rebeccakurz** [comment]
Ich kann es auch nicht mehr nachvollziehen. Wie gesagt, bei der ersten Kontrolle ging es automatisch, bei der zweiten nicht. Jetzt habe ich nochmals eine erstellt und es ging problemlos. 
Soll ich solche temporären Sachen nicht mehr melden?

**Comment by barbalex** [comment]
> Soll ich solche temporären Sachen nicht mehr melden?

Gute Frage. Ich würde sagen: Sobald es etwas ist, das mit einer gewissen Regelmässigkeit passiert, lohnt es sich darauf aufmerksam zu machen, dass es vorkommt - auch wenn ich ohne Nachvollziehbarkeit meistens nichts machen kann. Ich markier es dann mit dem Stichwort "kann nicht nachvollziehen".

Wenn es sehr selten bzw. sporadisch passiert, lohnt sich der Aufwand wohl nicht. Software und PC's verhalten sich aufgrund ihrer Komplexität grundsätzlich hin und wieder unerwartet.

**Comment by rebeccakurz** [comment]
Okay, dann machen wir das so.
