### ISSUE TITLE
Chrome Fehler roter Smiley

### ISSUE THREAD

**Issue by alinemeyer** [barbalex/apf2#297]
Beim Öffnen der APFlora DB in Google Chrome erscheint folgendes:

<img width="1923" alt="Bildschirmfoto 2019-09-11 um 13 15 51" src="https://user-images.githubusercontent.com/42208152/64697193-89025c80-d4a0-11e9-93f0-edec9b8c941b.png">

Auf Safari funktioniert die DB jedoch.

**Comment by barbalex** [comment]
War das nur einen Moment lang der Fall und du hast zufällig dann apflora auf Chrome geöffnet?

Ich habe vorhin ein Update live geschaltet, das offenbar beim Bauen des Projekts technische Probleme gehabt hat und daher gescheitert ist. Ev. hast du genau diesen Moment erwischt.

Funktioniert Chrome jetzt auch nicht?
Auch nicht nach Klicken auf "Mehr" > "Cache leeren und apflora neu laden"?

**Comment by barbalex** [comment]
Es kann auch mit einem Problem in der Fehlerbehandlung zusammenhängen. Das schaue ich an.

**Comment by barbalex** [comment]
Ich _glaube_ ich habe einen Fehler in der Fehlerbehandlung (sic!) korrigiert, der dies verursacht hat.

**Comment by alinemeyer** [comment]
Das Problem war einige Zeit lang (ca. 1 Stunde). Ich habe den Cache geleert und nun funktioniert es wieder. Danke!

**Comment by barbalex** [comment]
Das war wahrscheinlich die Zeit, bis ich den Fehler in der Fehlerbehandlung repariert habe. Sorry!
