### ISSUE TITLE
Doppelte Einträge

### ISSUE THREAD

**Issue by praktikatopos** [barbalex/apf2#298]
Folgende Einträge  (Ophrys araneola, 101 Weiach, KG Rüteren/Steinlochäcker) erscheinen doppelt:
<img width="436" alt="Bildschirmfoto 2019-09-11 um 13 59 18" src="https://user-images.githubusercontent.com/42208152/64697249-b18a5680-d4a0-11e9-91b3-59abe49e708c.png">
<img width="449" alt="Bildschirmfoto 2019-09-11 um 14 00 18" src="https://user-images.githubusercontent.com/42208152/64697258-b51ddd80-d4a0-11e9-8ab3-ad9a02eb5088.png">
<img width="438" alt="Bildschirmfoto 2019-09-11 um 14 08 07" src="https://user-images.githubusercontent.com/42208152/64697266-bc44eb80-d4a0-11e9-90a4-848cf98a3363.png">

**Comment by barbalex** [comment]
Danke, dass du zeigst, welche EK es sind.

Wenn ich sie öffne sind sie nicht doppelt.

Das heisst: 
1. Das Verdoppeln wurde durch etwas verursacht, das du zuvor gemacht hast. Es wäre mir sehr geholfen, wenn du beschreiben kannst, wie ich es provozieren kann, d.h. was man zuvor machen muss, damit man doppelte Objekte sieht
2. Du kannst die App neu starten, womit die Objekte nicht mehr doppelt angezeigt werden sollten. Wenn das nicht reicht, müsstest du den Menubefehl "Mehr" > "Cache leeren und apflora neu laden" wählen. Das ist nur eine Umgehung der Symptome. Viel lieber wäre mir wenn ich das provozieren und danach hoffentlich verhindern kann

**Comment by alinemeyer** [comment]
Wenn ich mich richtig erinnere dann sind jeweils die Einträge, die ich neu gemacht habe, doppelt erschienen (jedoch nicht alle!). Ich habe diverse Feldkontrollen hinzugefügt, bei einigen ist dann dieser Fehler passiert, bei den anderen nicht. Nach neu starten der App ist es aber wieder in Ordnung! Danke!

**Comment by barbalex** [comment]
Was du siehst ist entweder:
- ein Fehler im lokalen Zwischenspeicher, d.h. diese Objekte sind dort drin doppelt vorhanden. Falls es das ist, muss ich Abfragen überprüfen
- ein Fehler beim Bauen des Strukturbaums. Dann wäre es irgendwo im Code, der den Baum aufbaut

In beiden Fällen wäre ein Versuch, den Fehler (der zweifellos existiert) zu finden - ohne genauere Hinweise - viel Arbeit mit geringer Erfolgswahrscheinlichkeit.

Ich warte daher darauf, dass ich selber einen Hinweis entdecke oder von euch einer kommt, bevor ich mich da rein stürze.

> sind jeweils die Einträge, die ich neu gemacht habe, doppelt erschienen (jedoch nicht alle!)

Es passiert also wohl nur, wenn man Einträge neu erfasst. Aber dann nur unter bestimmten Umständen. Wäre also nützlich, wenn es Hinweise gäbe, unter welchen Umständen/Voraussetzungen beim Erstellen neuer Objekte diese im Strukturbaum verdoppelt werden.

**Comment by barbalex** [comment]
Sehr wahrscheinlich verwandte Meldung: https://github.com/barbalex/apf2/issues/286

**Comment by barbalex** [comment]
Schliesse das, weil schon lange nicht mehr gemeldet
