### ISSUE TITLE
Qualitätskontrolle, statt TPop-Nr. GUID

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#299]
Bei einigen Kontrollen steht der GUID statt TPop-Nr., z.B. 

Freiwilligen-Kontrolle ohne Jahr
TPop ohne für AP-Bericht relevant
TPop ohne Status
TPop: mind. 1 Koord. fehlt

evtl hats noch weitere

![Bildschirmfoto 2019-09-11 um 17 48 29](https://user-images.githubusercontent.com/6047564/64713051-8877bf00-d4bc-11e9-9079-857f0a63681b.png)

**Comment by barbalex** [comment]
Hast du kontrolliert, ob in diesen Fällen eine TPop-Nr existiert?

Der Bericht ist so programmiert, dass er die GUID zeigt, wenn keine TPop-Nr existiert.

**Comment by barbalex** [comment]
Welche AP ist das?

**Comment by barbalex** [comment]
O.k., danke.

Ich teste jeweils auf Abies alba. Dort ist das nicht einfach zu merken, weil sehr viele TPop keine Nummer haben.

Die Programmierung war an sich richtig: Der Code las die Nr aus dem Datensatz aus. Bloss: die Abfrage hatte die Nummer gar nicht abgefragt...

Danke für die Meldung. Sollte in v1.10.3 behoben sein. v1.10.3 sollte in ein paar Minuten live sein.
