### ISSUE TITLE
Strukturbaum: Aktive Zeile springt ans Ende des Fensters- bei Klick zwischen Arten, Populationen oder Teilpopulationen

### ISSUE THREAD

**Issue by jmenzi** [barbalex/apf2#3]
Wenn ich wild durcheinander klicke (anfangs nicht), springt der Strukturbaum mit der aktiven Zeile ans Ende des Fensters. Das ist etwas verwirrend, da ich jedes Mal die Orientierung wieder finden muss. Es wäre glaube ich einfacher, wenn der Strukturbaum fix bleibt und ich selbst scrollen muss.

**Comment by barbalex** [comment]
ja, das kann ziemlich nervig sein :-(

Die Lösung ist nicht ganz einfach, weil die Liste unendlich lang sein kann und der Sinn des Springens eigentlich darin besteht, dass das aktive Element immer im sichtbaren Bereich der Liste liegt. Nur ist mir nicht ganz klar, wieso es auch passiert, wenn es z.T. gar nicht nötig wäre.

Ich muss dem bei Gelegenheit ein bisschen Zeit widmen.

Danke für die Meldung!

**Comment by barbalex** [comment]
Juhui: Ich habe herausgefunden, was das Springen verursacht. Dieselbe Ursache führte dazu, dass die Karte wiederholt neu aufbaute. Man lernt nie aus :-)

Problem gelöst.
