### ISSUE TITLE
TPop ohne Status-Anzeige in Applikation, Export aber schon

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#30]
Wir hatten dies auch schon in V1. Im Export wird ein Status angezeigt, nicht aber in der Applikation. Bsp. Aceras, TPop 44.4
![bildschirmfoto 2017-04-28 um 17 48 07](https://cloud.githubusercontent.com/assets/6047564/25536402/016a3c94-2c3b-11e7-9c40-c9f674b03bbf.png)

**Comment by csalzmann** [comment]
noch ein Beispiel:
![bildschirmfoto 2017-05-13 um 09 48 31](https://cloud.githubusercontent.com/assets/6047564/26023640/5cbf49a4-37c1-11e7-90fa-d0da92e94e2a.png)

**Comment by barbalex** [comment]
grrrrrr!

Das Problem ist die Vergangenheit.

Wir haben früher für den Status in der Datenstruktur einen einzigen Wert geschaffen, der verschiedene Informationen vereint. Bzw. die Definition des Status wurde laufend erweitert. Unter anderem damit, ob eine Ansiedlung vor oder nach Beginn AP erfolgte.

Seither sind wir schlauer geworden und haben in der Benutzeroberfläche eine andere Struktur geschaffen, welche fast alle Informationen des Status-Felds darstellt. Fast alle, ausser, ob eine Ansiedlung vor oder nach Beginn AP erfolgte.

Das eigentliche Problem ist, dass nun der Wert des Status neu berechnet werden muss, wenn in einem dieser drei Felder etwas ändert:

- ap, start im Jahr
- tpop, bekannt seit
- tpop, status

Das kann aber nur funktionieren, wenn es direkt in der Datenbank passiert und das Resultat danach direkt in der Anwendung aktualisiert wird. Und das würde SEHR aufwändig.

Somit wäre es heute sinnvoll, wenn diese drei Werte unabhängig davon wären, ob eine Ansiedlung vor oder nach Beginn AP erfolgte. Un der "Status", wie er im Jahresbericht angezeigt wird, bei Bedarf dynamisch aus diesen drei Werten abgeleitet würde.

Heute kann also,  wann immer eines der drei Felder geändert wird, eine Inkonsistenz entstehen.

Am besten würde man das folgendermassen korrigieren:

- tpop, status enthält KEINE Information darüber, ob eine Ansiedlung vor oder nach Beginn AP erfolgte
- das wird bei Bedarf dynamisch berechnet
- was glaube ich nur im Jahresbericht benötigt wird

Bloss: Am Status hängt EXTREM VIEL:

- Abfragen
- views
- Jahresberichte im Admin-Tool

An der eigentlichen Datenstruktur etwas zu ändern wird daher SEHR aufwändig und fehlerträchtig.
Daher habe ich das gemieden.
Aber es beisst uns regelmässig.

In den von dir aufgezeigten Fällen ist der Grund:

- aceras hat keinen Wert im Feld "Start im Jahr" (wird aber bereits umgesetzt), der Status in tpop 44/4 ist 210, "angesiedelt vor Beginn AP, aktuell"
- spiranthes hat keinen Wert im Feld "Start im Jahr" (wird aber bereits umgesetzt), der Status in pop 11 ist 210, "angesiedelt vor Beginn AP, aktuell"

In meinen Augen müssen wir früher oder später in den sauren Apfel beissen und meinen obigen Vorschlag umsetzen.

Da aber extrem viel damit zusammenhängt, müssen wir sicher warten, bis v1 nicht mehr online ist.
Und mit grossem Vorteil auch warten, bis der Jahresbericht direkt aus der Anwendung heraus produziert wird.

Dann wird diese Änderung nämlich viel weniger aufwändig. Und dank der nun übersichtlicheren Programmierung viel weniger schmerzhaft. Hoffentlich.

**Comment by barbalex** [comment]
die kurzfristige Lösung dieses Problems: wählt in diesen Fällen den Status einfach nochmals

**Comment by barbalex** [comment]
diesen Umbau müssten wir wohl für nächsten Frühling/Frühsommer ins Auge fassen

**Comment by barbalex** [comment]
Ich habe bei den AP's ohne ApJahr die Stati der Pop und TPop so gesetzt, dass die Werte angezeigt werden. Das ist nur ein provisorischer Flick - das Grundproblem wird und ganz bestimmt immer wieder beissen. Aber ich ändere das Issue damit auf Erweiterung, weil der Umbau aufwändig werden wird und das aktuelle Problem hoffentlich gelöst ist

**Comment by csalzmann** [comment]
Super hast Du einen Flick gefunden!

**Comment by csalzmann** [comment]
Also wegen meiner letzten Meldung hab ich leider grad wieder ein paar TPops entdeckt, die auf der Applikation keinen Status-Wert haben:
Himantoglossum, TPops 105.2, 105.5, 105.6.

Das ist schon unangenehm. Kannst Du uns denn eine Abfrage generieren, wo Du diese Fälle auflistest? Damit wir sehen, um wieviele Fälle es sich überhaupt handelt?

**Comment by barbalex** [comment]
Ich schaue das nach den Ferien an

**Comment by csalzmann** [comment]
Ich frage mich, ob es wirklich nur die Vergangenheit ist? Ich habe nun einen Fall, wo ich 2016 einen Kontrollbericht machen musste und die TPop daraufhin auf erloschen gesetzt habe. Nun hat sie auch keinen Status angezeigt. Es handelt sich um O. palustris, TPop 79.1. Ist einfach merkwürdig. Vielleicht hilfts ja etwas.

**Comment by barbalex** [comment]
Um das Problem hoffentlich etwas nachhaltiger zu umgehen (das ist keine Lösung, die Lösung wäre die Strukturanpassung), habe ich folgendes gemacht:

Bei jedem Aufruf von Qualitätskontrollen läuft eine Funktion, welche für die jeweilige Art Stati korrigiert, bei denen ApJahr und/oder "bekannt seit" nicht mit dem Status übereinstimmen. Siehe hier: https://github.com/barbalex/apf2/blob/master/sql/apflora/functions/correctVorNachBeginnApStati.sql

Diese Abfrage habe ich ein mal über alle Arten laufen lassen. Dabei wurden in 35 Datensätzen (Populationen und Teilpopulationen) Stati verändert. Darunter auch die von dir gemeldeten Beispiele.

Hoffentlich gibt das vorübergehend etwas Ruhe und Vertrauen, bis wir die Struktur bereinigen können :-|

**Comment by barbalex** [comment]
Die Strukturbereinigung wird mit grossem Vorteil mit der Verlagerung des Berichts vom Admin-Tool nach apflora.ch kombiniert. Das wäre viel effizienter.

**Comment by rebeccakurz** [comment]
Karin Marti hat gerade festgestellt, dass wieder in vielen Pop/TPop die Stati fehlen: 
z.B. Aldrovanda Pop 2
trifolium Pop. 51, 50, 52, 54
Litorella Pop. 1
Ist da noch etwas passiert, dass die Stati nicht angezeigt werden? Kannst du da nochmals einen "Flick" machen?

**Comment by barbalex** [comment]
Oh je. Das liegt wohl an der Neu-Implementierung der Oberfläche.

Die Daten werden z.T. nicht angezeigt. Vorhanden sind sie. Und sie werden auch richtig gespeichert, wenn man etwas ändert.

Leider bin ich jetzt an einem langwierigen Umbau, der sich nicht unterbrechen lässt. Unmittelbar danach ist (sowieso) vorgesehen, dieses Problem ein für alle mal zu lösen.

Wenn ich das jetzt korrigieren muss, gibt es mehr als doppelten Aufwand.

Ist jetzt wirklich unglücklich aber ich hoffe, ihr könnt noch ca. zwei Wochen gedulden :-(

**Comment by barbalex** [comment]
ist umgesetzt
