### ISSUE TITLE
Qualitätskontrolle, 2. Baum zeigt nicht das gleiche wie 1. Baum

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#300]
Konnte im 2. Baum gar keine Eingabe machen um den Fehler zu beheben (Angabe QK kein Eintrag für AP-Bericht relevant, es nimmt es einfach nicht an.
Bsp. O. araneola, TPop 101.11 

Danach hab ich gesehen, dass sich aber im 1. Baum Eintrag gespeichert und richtig dargestellt ist. Das ist verwirrend und dürfte so nicht vorkommen. Siehe Screenshot.

![Bildschirmfoto 2019-09-11 um 17 56 26](https://user-images.githubusercontent.com/6047564/64713635-82361280-d4bd-11e9-8f47-46da41e99ea3.png)

**Comment by csalzmann** [comment]
der zweite Baum ist aufgrund der Qualitätskontrolle aufgegangen (habe dort auf den Issue geklickt)

**Comment by csalzmann** [comment]
Ja, es existiert eine TPop-Nr.

**Comment by barbalex** [comment]
> Das ist verwirrend und dürfte so nicht vorkommen

Finde ich auch. Bloss kann ich es nicht nachvollziehen :-(

**Comment by barbalex** [comment]
Ich habe versucht: 
1. QK in Ophr ara
2. 101/1 aus einer QK heraus im 2. Strukturbaum öffnen
3. Ein paar Felder ändern

Hat alles geklappt und war danach auch im parallel dazu direkt geöffneten Formular gleich, wie es sein sollte.

**Comment by barbalex** [comment]
Kann es sein, dass https://github.com/barbalex/apf2/issues/296 der Grund war? Das würde erklären, wieso du in dem Formular, in dem du den Wert gesehen hast, keine Änderung gesehen hast. Im anderen aber schon.

Wenn das der Grund war, sollte es nicht mehr passieren.

**Comment by barbalex** [comment]
Schliesse, da alt
