### ISSUE TITLE
Freiwilligen-Kontrolle EKF Eingabe Zahlen verschwinden

### ISSUE THREAD

**Issue by praktikatopos** [barbalex/apf2#301]
Lieber Alex

Wenn ich eine Freiwilligen-Kontrolle eingebe, dann muss ich der Eingabe der Zählungen jeweils zweimal die Zahl eintippen. Wenn ich z.B. Bei Pflanzen 126 eintippe, und dann in ein anderes Feld klicke, so verschwindet die Zahl. Erst wenn ich sie erneut eingebe, bleibt sie, auch wenn ich in ein anderes Feld klicke (passiert auch, wenn ich Enter drücke). Diesen Fall habe ich nun bei verschiedenen Arten angetroffen (Anacamptis pyramidalis, Ophrys apifera, Ophrys araneola). Ebenso verschwindet manchmal (aber eher selten) die Angabe, ob gezählt oder geschätzt (siehe Bild -> Fall Ophrys araneola Kloten Eigental Tpop 100.4 EFK 2019
![Bildschirmfoto 2019-09-13 um 13 48 32](https://user-images.githubusercontent.com/42208152/64860412-5c2f8000-d62d-11e9-90ed-78eefedbd1fb.png)

**Comment by barbalex** [comment]
Danke für die Meldung.

Dieses Formular ist sehr kompliziert. Die Komponente für die Zählungen wird 9 mal aufgerufen, je nach Umständen werden dabei unterschiedliche Variabeln übergeben. Bei diesen 9 Aufrufen wurden aber nicht immer die richtigen Variabeln übergeben :-(

Der Fehler sollte in v1.10.2 korrigiert sein. v1.10.2 ist live. Um zu aktualisieren musst du einfach apflora neu laden.

**Comment by praktikatopos** [comment]
Ich habe die APFlora DB neu geladen, doch das Problem besteht noch immer.

**Comment by barbalex** [comment]
Ich kann es nicht nachvollziehen. Hast du kontrolliert, ob du v1.10.2 oder (neuer) v1.10.3 hast?

**Comment by barbalex** [comment]
Falls das Problem immer noch existiert: Erklär mit bitte Schritt für Schritt, wie du es provozierst und bei welchem Datensatz.

**Comment by praktikatopos** [comment]
Ja ich habe die Version 1.10.3. Bei Überprüfung des Exports hat sich gezeigt, dass die Infos im Export auftauchen (sie scheinen also gespeichert zu sein), jedoch erscheinen die Infos bei mir in der DB-Ansicht nicht resp. die Anzahl erscheint erst wenn ich die Seite aktualisiere oder ich die Zahl zweimal eintippe, ebenso die Art der Erhebung (geschätzt/ gezählt). 

Desweiteren ist mir auch aufgefallen, dass der Knopf für "Werden junge neben alten Pflanzen beobachtet" für die Option "ja" nicht grün wird (selbes Problem: die Info ist gespeichert und wenn ich die Seite aktualisiere, erscheint sie auch, aber ohne aktualisieren ist dies nicht erkennbar und es sieht aus, als ob die Option "ja" nicht angewählt wäre).

**Comment by praktikatopos** [comment]
Das Problem taucht bei verschiedenen Arten auf (bis jetzt bei allen Arte, bei denen ich eine EKF hinzugefügt habe): Ophrys araneola Tpop 100.2 - 100.5, Himantoglossum Tpop 8.1 - 8.5, Filipendula vulgaris Tpop. 88.2 - 88.6. Vorgehen: Ich erstelle eine neue EKF, tippe die Daten ein. Wenn ich in das Feld der Zählungen klicke, weiter gehe (Enter oder durch klicken) dann verschwindet die eingegebene Zahl. Nach erneutem eintippen bleibt sie vorhanden. Dann gebe ich die restlichen Daten ein, aktualisiere die Seite um im Stammbaum zu sehen, ob die Zählungen richtig erfasst sind. Dabei verschwindet die Erhebungsart (gezählt/geschätzt). Diese tippe ich dann nochmals ein. Beim Export (vor zweiter Eingabe und Aktualisierung) sind aber Anzahl und Erhebungsart jeweils gespeichert. Es ist also wirklich nur ein Problem der "Anzeige"

**Comment by barbalex** [comment]
Abgesehen von

> Desweiteren ist mir auch aufgefallen, dass der Knopf für "Werden junge neben alten Pflanzen beobachtet" für die Option "ja" nicht grün wird (selbes Problem: die Info ist gespeichert und wenn ich die Seite aktualisiere, erscheint sie auch, aber ohne aktualisieren ist dies nicht erkennbar und es sieht aus, als ob die Option "ja" nicht angewählt wäre)

für das ich https://github.com/barbalex/apf2/issues/302 geöffnet habe, kann ich das einfach nicht nachvollziehen.

apflora verhält sich bei dir, als ob es die neue Version nicht richtig geladen hätte. Kannst du bitte einmal den Befehl "Mehr" > "Cache leeren und apflora neu laden" wählen und nochmals probieren?

**Comment by praktikatopos** [comment]
Wenn ich "Cache leere und apflora neu lade", dann scheint das Problem nicht mehr aufzutreten für die ersten 1-2 Eingaben von Zählungen. Bei der 2. oder 3. Eingabe einer Zählung passiert aber wieder das gleiche wie zuvor

**Comment by barbalex** [comment]
Nächster Versuch, das zu lösen in v1.10.6, wird in ein paar Minuten live sein

**Comment by rebeccakurz** [comment]
Ich habe gerade auch ein paar Freiwilligen-Kontrollen eingegeben und bei mir passiert das gleiche wie bei Simone: Wenn ich die Zählungen eingebe, verschwinden sie wieder wenn ich ins nächste Feld klicke, wenn ich sie nochmals eingebe bleiben sie dann aber.

**Comment by praktikatopos** [comment]
Auch bei mir ist das Problem immer noch vorhanden. Nun habe ich jedoch heraus gefunden, dass das Problem bei neu kreierten Zähleinheiten nicht auftritt (also bei solchen Zähleinheiten, bei denen man die Einheit noch eingeben muss). Vielleicht hilft das weiter?

**Comment by rebeccakurz** [comment]
Auch jetzt besteht dieses Problem noch immer. Ist bis jetzt bei jeder Freiwilligen-Kontrolle, die ich erstellt habe, der Fall gewesen. (verschiedene Arten).

**Comment by csalzmann** [comment]
Bei mir jetzt umgekehrt, im Strukturbaum ja, im EKF Formular nein

Allerdings fehlt im Strukturbaum die Methode, obwohl die ja auch offensichtlich eingegeben wurde, geht ja gar nicht anders.

![Bildschirmfoto 2019-09-18 um 10 05 38](https://user-images.githubusercontent.com/6047564/65129656-0cb9cd00-d9fc-11e9-8042-4daec57276ea.png)

**Comment by barbalex** [comment]
> bleiben sie im Formular drin, im Strukturbaum werden sie aber nicht angezeigt. So ist man sich nie sicher, ob die Zahlen jetzt gespeichert wurden oder nicht!

Das ist in der Entwicklungsversion korrigiert. Ab dem nächsten Update solltet ihr Änderungen in einer Zählung immer direkt im Strukturbaum sehen.

**Comment by barbalex** [comment]
Formulare aufzubauen, ist überraschend komplex. Daher gibt es dafür auch diverse Werkzeuge. Ich verwende für alle Formulare in apflora das Werkzeug, das sich bei anderen und auch in den letzten Monaten in apflora am meisten bewährt hat.

Bloss: Die Zählungen in diesem Formular weichen sehr stark vom Üblichen ab. So stark, dass nun offensichtlich wird, dass es keinen Sinn macht, das bewährte Werkzeug zu verwenden.

Ich muss die Zählungen von Grund auf neu aufbauen. Spezifisch für diesen Zweck und ohne Werkzeuge.

Ich hoffe, dass das bis morgen bereit ist. Leider muss ich daher alle anderen Projekte zurückstellen.

Man unterschätze nie die Komplexität eines für einen ganz spezifischen, untypischen Zweck aufzubauenden Formulars :-(

**Comment by rebeccakurz** [comment]
Oh dann hoffe ich das klappt mit dem neu aufbauen! Wirklich beachtlich, was man alles bedenken muss und wo unerwartet wieder Fehler auftauchen.:-(

**Comment by barbalex** [comment]
Sollte in v1.11.3 korrigiert sein. In ein paar Minuten live.

**Comment by rebeccakurz** [comment]
Super, das scheint geklappt zu haben, vielen Dank!!!
(Habe es nur kurz ausprobiert, werde nächste Woche noch mehr Eingaben machen und schauen ob es "verhebet")

**Comment by rebeccakurz** [comment]
Habe gerade eine Freiwilligen-Kontrolle eingegeben. Bei der ersten Zähleinheit ist die Eingabe wieder verschwunden, bei der 2. und 3. ist sie geblieben... Nachdem ich sie bei der ersten nochmals eingegeben habe, ist sie auch dort geblieben. 
Arbeite aber immer noch auf meinem Laptop...
<img width="881" alt="verschwindende Eingaben Pulvul" src="https://user-images.githubusercontent.com/30288503/65407988-706d3d00-dde4-11e9-9470-3ea7807eb844.PNG">

**Comment by rebeccakurz** [comment]
Habe auch noch ein paar Eingaben kontrolliert, die ich schon vor einiger Zeit gemacht habe. Dabei ist mir aufgefallen, dass bei einer Freiwilligenkontrolle die Eingabe im Formular verschwunden ist, im Strukturbaum aber noch drin ist (allerdings ohne Methode).
<img width="925" alt="Thagal1" src="https://user-images.githubusercontent.com/30288503/65408159-cd68f300-dde4-11e9-9342-d913ed3c1eab.PNG">
Bei der zweiten Freiwilligenkontrolle ist alles korrekt:
<img width="921" alt="Thagal2" src="https://user-images.githubusercontent.com/30288503/65408202-e96c9480-dde4-11e9-91f7-5b265304a5da.PNG">
Und bei der dritten Freiwilligenkontrolle ist es gleich wie bei der ersten:
<img width="934" alt="Thagal3" src="https://user-images.githubusercontent.com/30288503/65408228-f8ebdd80-dde4-11e9-9518-b556c5dc0683.PNG">

Ich habe diese 3 Freiwilligenkontrollen alle zur selben Zeit nacheinander eingegeben...

**Comment by rebeccakurz** [comment]
> 
> 
> Habe gerade eine Freiwilligen-Kontrolle eingegeben. Bei der ersten Zähleinheit ist die Eingabe wieder verschwunden, bei der 2. und 3. ist sie geblieben... Nachdem ich sie bei der ersten nochmals eingegeben habe, ist sie auch dort geblieben.
> Arbeite aber immer noch auf meinem Laptop...
> <img alt="verschwindende Eingaben Pulvul" width="881" src="https://user-images.githubusercontent.com/30288503/65407988-706d3d00-dde4-11e9-9470-3ea7807eb844.PNG">

Ist soeben nochmals passiert. Wieder nur die erste Zähleinheit, die wieder verschwunden ist...

**Comment by rebeccakurz** [comment]
<img width="918" alt="Strukturbaum" src="https://user-images.githubusercontent.com/30288503/65409694-ac0a0600-dde8-11e9-804e-b858aeb942d8.PNG">
Im Strukturbaum werden auch nur die 2. und 3. Zähleinheit angegeben

**Comment by csalzmann** [comment]
@rebeccakurz , @praktikatopos 
Habt Ihr probiert, als Workaround, ob es klappt, wenn Ihr die Zählungen statt im Formular direkt im Strukturbaum eingebt? Für "echte" Freiwillige ginge das ja nicht, aber für uns. Ich glaube, es lohnt sich nicht, weiterhin Eingaben von Zählungen im EKF Formular zu machen, wenn man nie weiss, ob die jetzt gespeichert sind oder nicht. Wenn noch EKF-Eingaben von Externen offen sind, müsste man denen dieses Verhalten kommunizieren und topos müsste die Eingaben selber machen.

**Comment by rebeccakurz** [comment]
Also bei mir klappen heute die Eingaben ohne Probleme, es sind noch keine Zahlen verschwunden. Eventuell hatte es gestern auch noch mit unserer IT-Umstellung zutun. Ich habe dann ja auch kurzzeitig auf meinem Laptop gearbeitet und das Netzwerk war nicht sehr stabil, vielleicht sind darum nochmals Fehler aufgetreten.

**Comment by barbalex** [comment]
Ich habe wieder ein Dutzend Mal probiert, das zu provozieren. Hat aber immer geklappt, wie es soll.

**Comment by rebeccakurz** [comment]
Okay, ja wie gesagt, ist es bei mir gestern auch nicht mehr vorgekommen...
Wir melden uns, falls es wieder passieren sollte!

**Comment by barbalex** [comment]
Nach über einem Jahr keine neuen Meldungen, hoffe ich, dass das nicht mehr auftritt und schliesse diesen Issue
