### ISSUE TITLE
Karte: als png speichern funktioniert nicht

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#303]
Wenn man auf das Symbol klickt, verschwindet gesamter Menübereich der Karte oben rechts. Einen Download gibt es nicht. Um den Menübereich wieder zu bekommen muss man auf Karte klicken (damit sie verschwindet) und ein 2. Mal Klicken damit sie wieder angezeigt wird (mit Menü).

**Comment by barbalex** [comment]
Das liegt daran, dass das Druck-Werkzeug bei gewissen Layers daran scheitert, die Hintergrundkarten zu laden.

Wieso passiert das? Wegen eines Sicherheits-Mechanismus namens "cors" (cross-origin-ressource-sharing). Es ist potentiell gefährlich, wenn eine Webseite von einer anderen Dateien verlangt - könnte ja sein, dass eine böse Seite Viren auf deinen PC laden will.

Damit es funktioniert, muss der Server, der die Daten (in diesem Fall die Kartenlayer) liefert, cors-Anfragen explizit unterstützen. Ich weiss nicht, wieso das Karten-Server allzu oft nicht machen.

Bisher war das bei diesem Vorgang offenbar kein Problem. Das heisst: Vermutlich hat Chrome bei einem Update den Umgang mit cors auf eine Art geändert, welche diesen Vorgang beeinflusst. Man sieht die Fehler, wenn man mit F12 die Chrome-Konsole öffnet und die Meldungen sieht.

Ich habe keine Mittel, das zu beeinflussen. Ebensowenig wie der Autor des Werkzeugs, das wir benutzen. Ausser: Die Karten-Layer selber zu hosten, was dieses Projekt finanziell sprengen würde. Ich kann z.B. im Fall der Open-Street-Map suchen, ob ich Karten-Server finde, welche cors unterstützen. Im Fall der Geo-Admin-Karten kann ich aber nichts machen, weil es für diese Daten keine alternativen Server gibt.

Dass das der Fehler ist, sieht man z.B. wenn man eine der vom Kanton Zürich geservten Layer als Hintergrund-Layer verwendet (alle ab ZH-Übersichtsplan). Diese funktionieren, weil deren Server cors-Anfragen akzeptieren.

**Comment by barbalex** [comment]
O.k., habe für Open Street Map einen Server gefunden, der cors akzeptiert. Wird im nächsten Update enthalten sein.

**Comment by barbalex** [comment]
Dass die Menüs verschwinden ist gewollt - während des Druckvorgangs. Sie sollten allerdings danach wieder erscheinen. Und das machen sie wohl nicht wegen des Fehlers. Werde diesbezüglich beim Autor des verwendeten Werkzeugs einen Issue öffnen.

**Comment by barbalex** [comment]
Mittlerweile bin ich total verwirrt. Nach etlichem Testen und Implementation der Möglichkeit, Layer für den Druck auszuschalten, werden die Swisstopo-Layer teilweise plötzlich wieder gedruckt. Ich habe langsam den Eindruck dass die Swisstopo viele verschiedene Server hat und nur ein Teil davon cors zulässt.

:-|

**Comment by barbalex** [comment]
Die Moral von der Geschichte:
- Open Street Map Layer sollten künftig zuverlässig drucken
- Swisstopo-Layer drucken unzuverlässig
- Kt. ZH Layer drucken zuverlässig. Und momentan kann ich darauf keinen Einfluss nehmen. Warten wir auf die Rückmeldung des Autors des verwendeten Werkzeugs
- Nach dem nächsten Update findet ihr neben dem "als png speichern" Knopf auch einen für den Druck, mit drei Formaten

**Comment by barbalex** [comment]
Umgesetzt:
- Version 1.11.0 mit neuem Karten-Druckwerkzeug und den cors-sendenden OSM-Layern
- Hinweis bei den "Aktuellen Fehlern", dass Hintergrund-Layer der Swisstopo beim Druck Probleme verursachen können
- Neue Benutzer-Dokumentation für das Drucken: https://apflora.ch/Dokumentation/Benutzer/Karte-Drucken/

**Comment by barbalex** [comment]
Ich schliesse diesen Issue. Grund: 
1. Ich kann den Fehler nicht mehr weiter beeinflussen
2. Wer diesem Fehler begegnet und ihn in den Issues sucht, findet ihn auch, wenn er geschlossen wurde
