### ISSUE TITLE
Anpassung EKF-Darstellung an Datenblätter

### ISSUE THREAD

**Issue by praktikatopos** [barbalex/apf2#304]
Bei folgenden Arten stimmt die DB-Ansicht nicht mit den Datenblättern überein und die DB-Ansicht soll wie folg angepasst werden:
- Daphne cneorum:
Reihenfolge Zähleinheiten: Triebe - blühende Triebe - Pflanzen
- Pulsatilla vulgaris:
Reihenfolge Zähleinheiten: Pflanzen total - davon blühende Pflanzen - davon Rosetten

**Comment by barbalex** [comment]
Was ist die "DB-Ansicht"?

**Comment by barbalex** [comment]
Falls du das Formular "Freiwilligen-Kontrolle" meinst: Die Reihenfolge wird durch die Zahl im AP unter dem Ast "EK-Zähleinzeiten" im Formular "EK-Zähleiheit" im Feld "Sortierung" zu erfassende Zahl bestimmt.

Ihr könnt das also selber bestimmen.

**Comment by rebeccakurz** [comment]
Ich habe am Montag bei Pulsatilla vulgaris die Sortierung der EK-Zähleinheiten geändert, respektive ich habe Zahlen eingesetzt bei der Sortierung, so dass eine andere Reihenfolge entstehen sollte. 
1. Pflanzen
2. blühende Pflanzen
3. Rosetten

Geschehen ist aber nichts. Jetzt habe ich nochmals nachgeschaut, im Formular ist immer noch die gleiche Reihenfolge wie vorher (Pflanzen, Rosetten, bl. Pflanzen).
Auch wenn ich eine neue Freiwilligen-Kontrolle öffne, haben die Zähleinheiten noch die "alte" Sortierung. 
Oder wie müssten wir das machen?
![Uploading Bildschirmfoto 2019-09-18 um 09.33.23.png…]()

**Comment by barbalex** [comment]
Sollte in v1.11.2 korrigiert sein. Ist in ein paar Minuten live.

**Comment by rebeccakurz** [comment]
Sehr schön, auch das hat geklappt und die Eingaben die ich gemacht habe sind jetzt richtig.
Danke!

**Comment by rebeccakurz** [comment]
Habe jetzt gerade noch festgestellt, dass das mit der Sortierung zwar im Formular geklappt hat, aber im Strukturbaum nicht... Hat die Sortierung, die man festlegen kann, keinen Einfluss auf die Anzeige im Strukturbaum?
![Uploading Sortierung.PNG…]()

**Comment by rebeccakurz** [comment]
Hmm hat mich vor allem irritiert, weil ich zuerst dachte die Sortierung habe doch nicht funktioniert... Ich werde mich mit @csalzmann beraten, ob es nötig ist, den Strukturbaum auch anzupassen.

**Comment by barbalex** [comment]
Ich schliesse diesen Issue wieder: Der eigentliche Issue ist behoben. Und was zuletzt dazu kam ist in https://github.com/barbalex/apf2/issues/322 Kern des Issues, daher besser dort weiter zu diskutieren.
