### ISSUE TITLE
Freiwilligen-Kontrollen: zusätzliche Zähleinheit erfassen (nur für 1 Formular)

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#305]
Ist es möglich, dass ich bei den Freiwilligen-Kontrollen eine zusätzliche Zähleinheit erfassen kann? Aber so, dass es nur für dieses Formular gilt und nicht gleich bei allen Formularen für diese Art angepasst wird?
So könnte ich, wenn ein Freiwilliger eine zusätzliche Zähleinheit aufgenommen hat, diese ergänzen (meist sind ja nicht alle 3 Zähleinheiten vorgegeben).

**Comment by rebeccakurz** [comment]
Okay, alles klar. Auch gut, dass zur Abwechslung mal ich etwas machen muss und nicht du;-)

**Comment by rebeccakurz** [comment]
Hoi Alex 
Ich habe gerade festgestellt, dass Simone in ein paar EKF-Formularen neue Zähleinheiten hinzugefügt hat. Also solche, die im Formular nicht vorgesehen waren und unter EK-Zähleinheiten nicht aufgeführt sind. Manchmal hat es ja nur eine oder zwei vorgegebene Zähleinheiten und die dritte Zähleinheit ist leer. 
Sie konnte dort dann einfach eine andere Zähleinheit einfügen bis letzte Woche. Aber seit letzter Woche klappt das nicht mehr und sie kann die neue Zähleinheit nur noch über den Strukturbaum eingeben. 
Bei mir hat das nie geklappt mit den zusätzlichen Zähleinheiten erfassen, darum auch meine obige Frage an dich. Über den Strukturbaum klappt es allerdings auch bei mir. 
Also ist das okay, wenn wir (wenn zb nur 2 Zähleinheiten vorgegeben sind) eine dritte Zähleinheit manuell über den Strukturbaum erfassen?

Verstehst du was ich meine? ;-) 
Liebe Grüsse

**Comment by barbalex** [comment]
Dass die Zählungen im Strukturbaum sichtbar sind, haben wir ad hoc wieder auf deinen Wunsch hin ermöglicht. Dabei war mir nicht aufgefallen, dass ein Klick auf einen solchen Eintrag das normale Zählungs-Formular öffnet. Worin man in der bestehenden Zählung die volle Freiheit hat.

Das istein Unfall und war nicht gewollt, denn so können die Regeln umgangen werden.
Allerdings: Freiwillige, die nur als Freiwillige Zugang haben, haben diese Ansicht nicht zur Verfügung. Und in ihrer Ansicht sollte es nicht möglich sein, die Regeln zu umgehen.

Wenn ihr also den "Fünfer und das Weggli" wünscht, nämlich: Regeln für die Freiwilligen und volle Freiheit für Artverantwortliche und MitarbeiterInnen von Topos, so könnten wir das ja ausnutzen. Das hat Simone ja schon gemerkt.

Man könnte aber einen Schritt weiter gehen und die Kontext-Befehle wieder einführen, welche das Schaffen von neuen und Löschen bestehender Zählungen ermöglichen, wie bei den Feldkontrollen.

Das gibt mir schätzungsweise eine Stunde ungeplanten (Mehr-)Aufwand.
