### ISSUE TITLE
Kurzzeitig keine TPops angezeigt, erst nach Cache leeren wieder

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#306]
Ich wollte es einfach melden, kann ja wieder vorkommen.
Habe mich bei Cardamine dentata eingeloggt und die Pop 8 hatte einfach keine TPops. Ich hatte natürlich einen RIESENschreck. Hab mich schon gefragt, wie wir die aus Backups wieder herstellen können. 
Bei Rebecca waren die TPops aber da. Und bei mir auch dann wieder. Nicht aber nach normalen Reload (oben links der Rundpfeil), sondern erst nach "Cache leeren und AP Flora neu starten".

Anbei der Screenshot zum Beweis, ich habe das nicht geträumt. Es ist einfach schräg.

![Bildschirmfoto 2019-09-18 um 09 14 21](https://user-images.githubusercontent.com/6047564/65124659-3ae7de80-d9f5-11e9-9fd4-7da0a4da4dc8.png)

**Comment by barbalex** [comment]
Jawohl, schräg. Wer das sonst auch noch erlebt, bitte hier dokumentieren. Wenn möglich mit Hinweisen, die helfen, dass ich es selber provozieren kann.

**Comment by barbalex** [comment]
Schliesse, da alt
