### ISSUE TITLE
EKF Formular: Deckung überprüfte Art

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#307]
Keine Eingabe möglich. Vermutlich fehlt Zahlenfeld?

![Bildschirmfoto 2019-09-18 um 09 46 04](https://user-images.githubusercontent.com/6047564/65128130-273e7700-d9f9-11e9-930c-4f3a42f9b4dd.png)

**Comment by csalzmann** [comment]
Interessant!
Als ich den nächsten Issue generierte und ich nochmals zurück zu obiger EKF kam, war auf einmal ein beschreibbares Zahlenfeld bei "Deckung überprüfte Art" vorhanden. Da ist etwas instabil.

**Comment by csalzmann** [comment]
Es handelte sich übrigens um Aldrovanda vesicularia, TPop 13.1.

**Comment by barbalex** [comment]
Was heisst "Keine Eingabe möglich. Vermutlich fehlt Zahlenfeld?"?
Ich verstehe es nicht, denn in deinem Bild sieht man ja das Feld.
Heisst es: "Man sieht zwar etwa, das wie ein Feld aussieht, aber wenn man hinein klickt, geschieht nichts"?

**Comment by barbalex** [comment]
Ein Problem in diesem Formular sind die engen und unflexiblen Platzverhältnisse. Der Druck sollte auf eine A4-Seite passen. Eine Anforderung, die es im Web nicht gibt und für die daher die Feld-Werkzeuge nicht ausgelegt sind.

Kombiniert man das mit der Tatsache, dass Bildschirme keine einheitliche Auflösung haben und Fenstergrössen in allen Dimensionen beliebig variieren können, ist es unmöglich, alle Varianten vorherzusehen und zu testen, wie ein Feld in engem Raum platziert wird.

Wegen der engen Platzverhältnisse muss ich die Felder enger setzen, als vorgesehen ist. Kombiniert man das mit den oben erwähnten Rahmenbedingungen, kann ich nicht ausschliessen, dass es Situationen gibt, in denen Unerwartetes passiert.

Wie gesagt: Das sind Probleme, die bei Ausdrucken in dieser Art nicht existieren. Denn dort ist der Platz fix A4.

Sollte das zu einem häufigen Problem werden, müssten wir wohl von der Idee abkommen, dass das Eingabe-Formular sich optisch eng am Druckformular angleicht. Und es anders gestalten, so dass die Felder wieder den vollen Platz erhalten, den sie erwarten.

**Comment by barbalex** [comment]
Ich hab dem Feld ein bisschen mehr Platz gegeben. Keine Ahnung, ob das nützt. In der schwachen Hoffnung dass es nicht mehr passiert schliesse ich den Issue.
