### ISSUE TITLE
Feldkontrolle: Jahr wird mit Datum nicht automatisch ausgefüllt

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#308]
Das war doch früher so?
Nach Eingabe des genauen Datums wird Jahr nicht automatisch nachgeführt.

![Bildschirmfoto 2019-09-18 um 12 07 13](https://user-images.githubusercontent.com/6047564/65139465-fc5e1e00-da0c-11e9-8a53-3071b526fecd.png)

**Comment by csalzmann** [comment]
Ups, und wenn ich dann von Hand das Jahr nachführen will, verschwindet die genaue Datums-Eingabe..

![Bildschirmfoto 2019-09-18 um 12 09 31](https://user-images.githubusercontent.com/6047564/65139591-35968e00-da0d-11e9-8116-7300de1b61f7.png)

Gebe ich dann Datum mit Kalenderfunktion ein, wird es endlich gespeichert.

Bei O. palustris, TPop 1.2 ; ich nehme aber an, es ist nicht nur dort so.

**Comment by csalzmann** [comment]
Es ist nicht stabil. Beim nächsten Versuch, O. palustris TPop 1.3, hat es auf Anhieb geklappt

**Comment by barbalex** [comment]
> Das war doch früher so?

Ja, das ist so programmiert. Und ich verstehe nicht, wie es sein können soll, dass das Datum _ohne_ das Jahr gesetzt wird, wenn du - auf welche Art auch immer - ein Datum setzt.

Ich kann es auch nicht provozieren.

Da fällt mir ein: Es gibt eine Routine, die hier herausfindet, welches Feld nun geändert wurde. Diese ist mir aufgefallen, als ich vorhin des EKF-Formular verändert habe. Denn es gibt offenbar Fälle, in denen die Daten, die diese Routine erhält, unerwartete Werte enthält. In diesen Fällen konnte die Routine nicht das richtige Feld zurückgeben. Das könnte in diesem Fall auch die Ursache sein. Diese Routine habe ich korrigiert, daher schliesse ich diesen Issue in der Hoffnung, dass das der Grund war.

> Ups, und wenn ich dann von Hand das Jahr nachführen will, verschwindet die genaue Datums-Eingabe

Das ist so "by design": Schliesslich muss das Datum neu gesetzt werden, wenn du im Feld Jahr den Eintrag änderst. Und weil apflora nicht wissen kann, welches Datum du meinst, löscht es das Datum immer, wenn du im Feld Jahr manuell etwas setzt.

**Comment by csalzmann** [comment]
Da man sich mit der Kalenderfunktion behelfen kann, gibt es ja einen Workaround. Aber das Problem existiert nach wie vor. Siehe Screenshot:
Datum gesetzt
Cursor in neuem Feld

(habe die EK als Test zur Kontrolle der mehrfachen Zählungen / pro mit Zieleinheit eingegeben, lösche sie jetzt wieder. War bei O. araneola, TPop 101.1)

![image](https://user-images.githubusercontent.com/6047564/65440542-2ce8f200-de29-11e9-89a3-38d81f71a932.png)

**Comment by barbalex** [comment]
Was hast du genau in das Datums-Feld eingegeben? Ich brauche die genaue Zeichenfolge. Vielleicht kann ich es damit nachvollziehen

**Comment by csalzmann** [comment]
Genau so wie es steht.

**Comment by barbalex** [comment]
O.k., meine Frage sieht nun etwas blöd aus. 

Aber ev. ist dir gar nicht bewusst, dass du nicht das ganze Datum tippen musst, sondern bloss "21.4" oder "21.04" oder "21.4.19"" oder "21.04.19" und den Rest macht dann apflora für dich.

Wenn Monat oder Jahr fehlt, ergänzt apflora mit dem aktuellen.

Ich hab das mit viel Aufwand vor zwei Jahren programmiert. Und mittlerweile plagt es mich, weil das verwendete Werkzeug es seit dem letzten grossen Update nicht mehr zulässt :-(

Wenn ihr das gar nicht benutzt, entferne ich es gerne wieder.

Übrigens: Ich habe jetzt ca. 30 mal versucht, ein Datum einzugeben oder zu ändern. Immer wird dabei, wie programmiert, das Jahr mit gesetzt. Ich kann es also nicht provozieren.

**Comment by csalzmann** [comment]
Ich habe wohl auch so blöd geantwortet. Meinte es aber auch ernst. Habe mit "0" und Punkt und allem eingegeben, genau so wie es steht. 

Ich habe nun herausgefunden, dass das Jahr trotzdem noch nachgetragen wird. Aber in zeitlichem Abstand (ca 5 Sek). Und nicht von alleine, sondern wenn man nochmals irgendwo hinklickt (kann auch ausserhalb Programm sein, z.B. Printscreen :) ). Beim ersten Klick nach der Datumseingabe (z.B. zu Bearbeiter) passiert aber noch nichts (wohl weil innerhalb 5 Sekunden). Wir haben hier nicht die schnellste Leitung, aber ansonsten wäre mir jetzt noch kein grosser Hänger in der FloraDB sonst aufgefallen - umso merkwürdiger dann bei so was Simplem wie der Jahreszahl. Also irgendwie macht die da einen grossen Umweg bis zum Ziel.. Es verunsichert halt, wenn keine Jahreszahl steht.

Wenn das Vereinfachungstool Schwierigkeiten beim Update macht, kannst Du es meiner Meinung nach schon wieder rausnehmen. Tut mir mega leid für den Aufwand!

**Comment by barbalex** [comment]
> Aber in zeitlichem Abstand (ca 5 Sek)

Die Daten werden nach dem Setzen nochmals geladen. Wenn das Netzwerk nicht schnell ist, kann das zu einer Verzögerung führen. Vermutlich ist hier weniger die Geschwindigkeit des Netzwerks das Problem, sondern die Latenz (= Zeit, bis es reagiert, wonach erst die Geschwindigkeit zum Zug kommt)

> Und nicht von alleine, sondern wenn man nochmals irgendwo hinklickt

Die Benutzeroberfläche wird mit den neuen Daten erst aufgefrischt, wenn der Benutzer etwas macht (öffnet, verlässt, klickt...). Das Verhalten ist also erwartet

> Wenn das Vereinfachungstool Schwierigkeiten beim Update macht, kannst Du es meiner Meinung nach schon wieder rausnehmen

O.k., werde das bei Gelegenheit machen. Du siehst übrigens die neue Version der Datenfelder in vermehrung.apflora.ch. Dort erscheint eine Eingabemaske, die einem anzeigt, in welchem Format man das Datum erfassen soll. Wobei man dann noch merken muss, dass man die Punkte nicht tippen muss...

> Tut mir mega leid für den Aufwand

Den Aufwand habe ich für ein anderes Projekt betrieben. Dort sind v.a. Sekretariats-MitarbeiterInnen am Werk, die viele Daten erfassen müssen. Da kommt es auf so was an. Muss dir also nicht leid tun

Nun, wenn das Problem die Latenz des Netzwerks ist, dann kann ich nichts machen und das Verhalten ist erwartet. Ich schliesse mal diesen Issue, in der Annahme, dass es das ist.

**Comment by csalzmann** [comment]
Stimmt doch nicht, war einfach ein Glückstreffer vorhin. Das Datum/das Jahr macht was es will, offenbar.

**Comment by barbalex** [comment]
Du bist ein "Glückspilz" ;-)

Ich leider nicht. Will heissen: Bei mir funktioniert es immer.

**Comment by barbalex** [comment]
Wie oft funktioniert es bei dir nicht? Verglichen mit wie oft es funktioniert?

**Comment by csalzmann** [comment]
Fehlerquote > 50%. Bei mir so schlecht, dass ich nur noch über das Kalendertool eingebe. Habe einfach keine Geduld mehr, solange das funktioniert, brauch ich halt das. Es ist aber sicher nicht gut so.

**Comment by rebeccakurz** [comment]
funktioniert bei mir auch in der Hälfte der Fälle nicht...

**Comment by barbalex** [comment]
Ich habe soeben auf apflora.ch (nicht in der Entwicklungs-Umgebung) 30 Mal in einer Feldkontrolle:

1. Jahr gelöscht > Datum wird auch gelöscht
2. Datum getippt > Datum wird gesetzt und anschliessend auch das Jahr

Es hat kein einziges Mal _nicht_ funktioniert.

Was muss ich machen, damit es nicht funktioniert?

**Comment by barbalex** [comment]
Habe im Code eine Eigenart gefunden, die dazu führte, dass der App-seitige Zustand der Daten nicht sofort aktualisiert wurde, sondern erst, nachdem die Server-seitig aktualisierten Daten neu abgerufen waren.

Der Unterschied sollte im Normalfall nur ein Bruchteil einer Sekunde sein. Aber was weiss ich... Ich hab's in v1.19.41 korrigiert.

Bitte meldet mir, falls sich etwas ändert.

**Comment by rebeccakurz** [comment]
Hoi Alex
Also das Problem besteht immer noch, dass das Jahr nicht automatisch ausgefüllt wird. Ich bin gerade am Massnahmen eingeben, es scheint also allgemein zu sein (nicht nur bei Feldkontrollen). Auch bei Simone funktioniert es nicht.

**Comment by barbalex** [comment]
In v0.19.14 habe ich bei der Speicherung nochmals etwas geändert. 

Konkret: Zuvor hat apflora beim Speichern die Daten häufig nochmals beim Server abgerufen. Bloss: Wenn kurz danach etwas geändert wurde, konnte das bei langsamer Internet-Verbindung dazu führen, dass _nach_ dieser Änderung eine Antwort auf einen Daten-Abruf eintraf, der _zuvor_ passierte und darum veraltete Daten enthielt (welche die neusten Änderungen noch nicht enthielten).

Die Änderungen gingen dadurch nicht verloren. Sie haben sich einfach auf dem Weg zum Server mit den zuvor abgerufenen Daten gekreuzt. Und darum hat apflora veraltete Daten angezeigt, _obwohl_ die Änderungen korrekt gespeichert wurden.

Dass das vor allem bei langsamer Internetverbindung auftrat, könnte erklären, wieso ich das Problem nie nachvollziehen konnte.

Bitte sagt mir, ob dieses Problem immer noch auftritt.

**Comment by barbalex** [comment]
In der Annahme bzw. Hoffnung, dass das Problem nun endlich gelöst wurde, schliesse ich diesen Issue wieder
