### ISSUE TITLE
Überlebensrate in %

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#309]
Bitte im Text angeben, dass Überlebensrate in % eingegeben werden muss, sonst gibts immer einen Fehler

![Bildschirmfoto 2019-09-18 um 12 12 46](https://user-images.githubusercontent.com/6047564/65139899-b9507a80-da0d-11e9-80ca-d44b99370dc1.png)

**Comment by barbalex** [comment]
Danke für den Hinweis.

In v1.11.3 gemacht. Wird in ein paar Minuten live sein.
