### ISSUE TITLE
Bei Artwechsel Filter wieder raus

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#31]
Es macht keinen Sinn, wenn Filter drinbleiben

**Comment by barbalex** [comment]
danke: Filter wird nun (in der Entwicklungsversion) geleert, wenn die Art wechselt

**Comment by csalzmann** [comment]
Filter bleibt bei Artwechsel immer noch drin (habe bei Abies alba gefiltert, war bei Ophrys araneola noch drin)

**Comment by barbalex** [comment]
Auf welcher Struktur-Ebene hast du gefiltert? Ich habe nach Pop gefiltert, die Art gewechselt und es war weg.

Hm. Du meinst ev. nicht den Strukturbaum-Filter sondern den Formular-Filter? Falls ja: Der wird (momentan) nicht automatisch geleert. Aber man kann ihn mit einem einzigen Klick selber leeren: Oben rechts in der Titel-Zeile des Formulars gibt es ein Symbol, um alle Formular-Filter zu entfernen.

**Comment by csalzmann** [comment]
Ja, jetzt seh ich auch kein Problem. Ich schliesse.
