### ISSUE TITLE
EKF - falsche Formulare werden angezeigt

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#310]
Hoi Alex

Ich habe mich gerade mit dem Benutzernamen und Passwort eines Freiwilligen eingeloggt (ich muss ihm das Passwort nochmals schicken und wollte sichergehen, dass es das Richtige ist). 

Nun zeigt mir die FloraDB aber die EKF-Formulare eines anderen Freiwilligen an!
Im Screenshot siehst du oben rechts den Benutzer (Tom Häussermann) und auf den Protokollblättern den Namen des anderen Freiwilligen (Jürg Luder), dessen Formulare angezeigt werden.

<img width="1921" alt="Bildschirmfoto 2019-09-19 um 13 25 28" src="https://user-images.githubusercontent.com/30288503/65240361-5a5c3580-dae1-11e9-93a4-30494155bdee.png">

Auch wenn ich das Jahr wechsle, zeigt es mir noch die Formulare von Jürg Luder an! (Welcher übrigens der Freiwillige ist, der seine Kontrollen online eingetragen hat und nun nicht mehr an seine Daten kommt, habe dir sein Mail weitergeleitet).

Dann habe ich auf "Cache leeren und apflora neu laden" gedrückt, mich neu angemeldet und jetzt zeigt es die richtigen Formulare...

**Comment by barbalex** [comment]
> Dann habe ich auf "Cache leeren und apflora neu laden" gedrückt, mich neu angemeldet und jetzt zeigt es die richtigen Formulare...

Das zeigt, was passiert ist: im Cache waren noch Informationen, die von deiner eigenen Anmeldung stammten. Was natürlich nicht sein sollte.

Was auch heisst: haeussermann hätte das nicht gesehen. Ausser du hättest davor auf seinem PC und im selben Browser angemeldet.

Beim Nachschauen habe ich gesehen, dass apflora nicht konsequent allen Cache löscht, wenn man abmeldet. Das habe ich jetzt angepasst: Beim Abmelden wird im Cache ALLES gelöscht. Damit garantiert nichts zurückbleibt, das der neue Benutzer nicht sehen sollte.

Weil es somit das nächsttiefere Menü nicht mehr braucht, habe ich jenes entfernt.

Ist in v1.11.5 korrigiert. Wird in ein paar Minuten live sein.
