### ISSUE TITLE
Fehlermeldung bei Filtern nach Art

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#311]
Bei mir kam vorher diese Fehlermeldung, als ich nach einer Art filtern wollte (Thalictrum).
Nachdem ich die Seite aktualisiert habe, ging es aber wieder... Ist das ein Problem mit dem Netzwerk oder mit der Datenbank? Hatten dieses Wochenende ja eine IT-Umstellung und bin im Moment an meinem Laptop am Arbeiten.

<img width="591" alt="Fehlermeldung" src="https://user-images.githubusercontent.com/30288503/65407025-7d3c6180-dde1-11e9-971f-21f7fc9a0412.PNG">

**Comment by barbalex** [comment]
Das ist der erste network error, den ich sehe. Hier ist definiert, was es ist: https://www.apollographql.com/docs/react/features/error-handling/#options

Es kann also sein:
- +- was du meinst und was die Meldung nahe legt: Die Anfrage oder deren Antwort schaffte es nicht hin bzw. zurück
- der Server hat auf eine unübliche Art falsch reagiert (normalerweise retourniert er eine Fehlermeldung, wenn etwas schief läuft)
- irgend etwas anderes im Code, der die Anfrage steuert (innerhalb des verwendeten Werkzeugs), das aus unerfindlichen Gründen in 99.999% aller Zeit rund läuft und diesmal schief

apflora spricht je nachdem was du machst einzelne bis hunderte Male pro Minute mit dem Server. Diese Art Fehler ist also ziemlich selten bzw. passiert nur in einem winzigen Bruchteil der Fälle. Und Computer sind nicht 100% stabil. Im Gegenteil zu Netzwerkverbindungen, wenn dort etwas nicht stimmt.

Ich gehe davon aus, dass dieser Fehler nicht wiederholt auftreten wird. Wenn ja, müssten wir klären:
- passiert er nur bei euch > könnte euer Netzwerk sein. Das ist wirklich der wahrscheinlichste Fall
- passiert er bei anderen ebenso oft > könnte ein Fehler im Server sein oder im Code des verwendeten Werkzeugs, das die Anfrage steuert

**Comment by barbalex** [comment]
Schliesse, da alt
