### ISSUE TITLE
Qualitätskontrolle: Anordnung Fehler nach Pop/TPop (statt TPop/Pop)

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#312]
Bitte die Fehler innerhalb eines Abschnittes nach Pop/TPop sortieren (und nicht nach TPop/Pop).

![image](https://user-images.githubusercontent.com/6047564/65409771-dfe52b80-dde8-11e9-965e-8f86301da737.png)

**Comment by barbalex** [comment]
Gemacht

**Comment by csalzmann** [comment]
Danke!!

**Comment by csalzmann** [comment]
Noch nicht überall umgesetzt, z.B.

![image](https://user-images.githubusercontent.com/6047564/65762438-4fc52000-e121-11e9-8bb2-0a1060eddcb2.png)


![image](https://user-images.githubusercontent.com/6047564/65762476-64a1b380-e121-11e9-86ee-29d132c382b0.png)

**Comment by barbalex** [comment]
Doch, das ist umgesetzt und bei mir als auch auf dem Server aktualisiert. Hab's zur Sicherheit nochmals aktualisiert.

Ich kann es aber nicht testen, weil ich nicht weiss, wo es auftritt.

**Comment by csalzmann** [comment]
Also bei obigen beiden Fällen war es heute morgen nicht nach Pop/TPop sortiert. Die eigentlichen Fehler habe ich in der Zwischenzeit aber behoben. War bei Saxifraga.  Ist aber auch bei Himantoglossum so. Aktueller Screenshot (v1.11.11):

![image](https://user-images.githubusercontent.com/6047564/65764828-cdd7f580-e126-11e9-92fb-9c426c6e06f5.png)

**Comment by barbalex** [comment]
O.k., ich renne momentan zu vielen Dingen nach. Statt nach PopNr und TPopNr zu sortieren, hab ich nach TPopNr und TPopNr sortiert :-(

Ist nun endlich richtig korrigiert. Sorry!
