### ISSUE TITLE
Exporte: Fenster nach unten abgeschnitten

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#313]
Mein Bildschirm ist offensichtlich zu klein für die Anzeige des gesamten Exportfensters. Nun kann aber leider auch nicht weiter nach ganz unten scrollen.

**Comment by barbalex** [comment]
Von welchem Fenster sprichst du? Kannst du bitte ein Bild machen?

**Comment by csalzmann** [comment]
Der Scrollbalken rechts sieht man nicht bis zum Ende, drum kann ich auch nicht weiter nach unten. Nach "Beobachtungen" scheint es ja noch weitere Exporte zu geben.

![image](https://user-images.githubusercontent.com/6047564/65504835-252c5a80-dec8-11e9-81e9-9717d8301482.png)

**Comment by barbalex** [comment]
Danke, jetzt hab ich's verstanden. Sollte in v1.11.11 behoben sein
