### ISSUE TITLE
Qualitätskontrollen, Export?

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#314]
Kann man Qualitätskontrollen exportieren? Müsste eigentlich nicht so schwierig sein, oder? Das wäre eine schöne Alternative, um die Fehler abzuarbeiten, wenn man die in Excel vor sich hätte. Manchmal ist halt das eine, manchmal das andere praktischer.

**Comment by barbalex** [comment]
Klar, könnte man. 

Ich müsste wohl etwas pröbeln, damit sie auch als funktionierende Links im Excel-Dokument landen. Nicht sicher, ob das klappt, aber wahrscheinlich schon.

Und die Gruppierung nach Kriterien klappt wohl nur, indem man den Titel in die erste Spalte schreibt und den Link in die zweite.

Bin aber nicht sicher, ob sich der Aufwand lohnt: Du kannst auch einfach in Chrome das Register duplizieren. Danach kannst du das Fenster mit den QK irgendwohin schieben. Ich würde es z.B. auf den einen Schirm schieben und im zweiten die Daten bearbeiten.

**Comment by csalzmann** [comment]
Ups, nein, ich meinte es auf einem viel tieferen Niveau. Einfach dass man ein statischer Überblick pro Art hat, wieviele Fehler grundsätzlich zu bearbeiten sind. 
Im Moment stört mich eben, dass ich keine Anzahl mehr sehe, deshalb bin ich überhaupt auf den Export gekommen.
Export ist nicht so wichtig, lassen wir den mal weg.

**Comment by barbalex** [comment]
Die Anzahl sieht man ja jetzt.
