### ISSUE TITLE
Qualitätskontrolle: Anzahl fehlt

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#315]
Früher gab es doch immer die Anzahl der Fehler an, das fehlt jetzt. Kannst Du das bitte wieder einfügen?

**Comment by barbalex** [comment]
Ist eben nicht so simpel:

Im Strukturbaum macht die Anzahl wenig Sinn. Denn: Sie ist nur bekannt, wenn die Daten analysiert wurden. Die Analyse ist zu aufwändig, um sie dauernd durchzuführen.

Im Formular könnte ich die Anzahl anzeigen. Willst du sie dort sehen?

**Comment by barbalex** [comment]
Ist ab v1.11.9 im Formular sichtbar

**Comment by csalzmann** [comment]
Ja gerne im Formular! Ich bin jetzt bei v1.11.9, wird aber noch nicht angezeigt ?

**Comment by csalzmann** [comment]
![image](https://user-images.githubusercontent.com/6047564/65502877-088e2380-dec4-11e9-81a4-9de312600725.png)

**Comment by barbalex** [comment]
Ich hab's halt gut versteckt: Schau mal die Zahl im Analysieren-Knopf oben rechts an.
