### ISSUE TITLE
Qualitätskontrolle: Verhalten im 2. Baum nach Schliessen Menüpunkt

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#316]
Wenn ich nach Qualitätskontrolle im 2. Baum die Fehler einer TPop bearbeite und den Baum dann in irgendeinem Menüpunkt (TPop, Massnahmen, irgendwas) wieder zusammenklappe für die Übersicht, springt die Ansicht zurück zu alle Arten. Ich möchte aber, dass die Ansicht einfach dort bleibt.

Jetzt ist es so, dass ich wieder runterscrollen muss zu derjenigen Art, die ich gerade am bearbeiten war. 

Ich arbeite folgendermassen mit der Qualitätskontrolle:
Für mich ist es immer eine Mischung zwischen von der Qualitätskontrolle mit Link zu einem Fehler zu kommen und dann, wenn ich gerade in einer Pop bin mit verschiedenen Fehlern, diese gleich im 2. Baum nacheinander zu erledigen (z.B. verschiedene TPops einer Pop nacheinander abarbeiten, dafür muss ich nicht jedes Mal wieder zurück in die Qualitätskontrolle und mich dort neu "einlinken"

![image](https://user-images.githubusercontent.com/6047564/65412056-bdeea780-ddee-11e9-996c-87e1cec519da.png)

**Comment by barbalex** [comment]
Die **Lösung** vorweg: 

Statt im Strukturbaum hierarchisch über dem aktuell offenen Formular durch Klick auf das Dreieck den aktiven Ast zu schliessen, klickst du besser auf das Objekt (= auf dessen Text), unter dem du danach wieder arbeiten willst. 

Damit ist dieser Knoten aktiv (und seine Daten werden im Formular angezeigt). Danach kannst du den Ast, in dem du zuvor aktiv warst, schliessen, ohne dass der Baum (weg) springt.

**Erklärung**

Wenn du über dem aktuell aktiven Knoten den Strukturbaum schliesst, indem du auf das Dreieck klickst, ist kein Knoten mehr aktiv. Denn den Ast, in dem sich ein aktiver Knoten befand, hast du geschlossen. Nun springt der Baum in die Ausgangsposition, die er immer einnimmt, wenn kein Knoten aktiv ist - nämlich nach ganz oben.

Wenn du nun aber auf den Text des Knoten klickst, der sich über dem befindet, den du schliessen willst, wird dieser Knoten aktiviert. Wenn du danach den Ast darunter schliesst, springt der Baum nicht in die Ausgangsposition, denn es existiert ein aktiver Knoten.

Im Prinzip weiss der Baum:
- Ist kein Knoten aktiv, bin ich in Ausgangsposition, nämlich zuoberst
- wird ein Knoten aktiv und ist er im sichtbaren Bereich des Bildschirms, bewege ich mich nicht
- wird ein Knoten aktiv und liegt er ausserhalb des sichtbaren Bereichs, bewege ich mich genau so weit wie nötig (aber nicht weiter), damit dieser Knoten nun auf dem Bildschirm sichtbar ist
- Ich habe offene Knoten. Ich weiss zwar, dass ich sie offen aufbauen muss, aber im Gegensatz zu aktiven Knoten kann ich ihnen keine spezielle Bedeutung für mein Scrollverhalten zumessen - es könnten hunderte von Knoten offen sein, wild verteilt über den ganzen Baum

Der Baum ist **Zustand-gesteuert**, nicht **Ereignis-gesteuert**. Ich kann ihm daher nicht sagen, dass er sich unterschiedlich verhalten soll, wenn bestimmte Ereignisse passierten. Zustand ist das Prinzip, auf dem die gesamte Steuerung von apflora.ch seit dem Umbau vor ein paar Jahren basiert. Nur so kann man die Komplexität der Benutzer-Steuerung, wie sie apflora enthält, zuverlässig managen. 

Wäre apflora Ereignis-gesteuert, würde die Komplexität der Steuerung mit jedem möglichen Zustand exponenziell steigen:
- 2 Zustände (a und b): 2 Mögliche Ereignisse (a > b, b > a)
- 3 Zustände (a, b, c): 9 Mögliche Ereignisse
- 4 Zustände: 16
...

Mittlerweile haben wir hunderte, vermutlich tausende von möglichen Zuständen. Klar kann nicht jeder in jeden anderen übergehen. Aber diese Komplexität wäre nicht zu bewältigen. Dauernd würde man Zustand-Änderungen begegnen, bei denen die Programmierung versagt, weil sie nicht an alles gedacht hat, was bei diesem spezifischen Zustands-Wechsel passieren kann bzw. muss.

Vielleicht gibt es eine Methode, um zu verhindern, dass der Baum springt, wenn er keinen aktiven Knoten mehr hat. Bestimmt würde das irgendwie die offenen Knoten berücksichtigen. Aber momentan fällt mir nicht ein, wie der Baum das machen würde, damit das Verhalten immer den Erwartungen der BenutzerInnen entsprechen würde.

Sagen wir es mal so: Das ist kein triviales Problem. Ich behalte es aber zumindest im Hinterkopf. Denn was du beschreibst ist sicher nicht optimal.

**Comment by barbalex** [comment]
Vor ein paar Monaten habe ich den Navigationsbaum neu gebaut (wegen Leistungs-Problemen). Ich glaube, er springt nun nicht mehr, wenn man einen Knoten schliesst
