### ISSUE TITLE
Karte: Pflegeplan

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#317]
Layer Pflegeplan funktioniert nicht (wird nicht angezeigt)

**Comment by barbalex** [comment]
Tja, der Kanton hat die Layer umbenannt ohne auf Rückwärtskompatibilität zu achten. Daher konnte es nicht mehr funktionieren.

Bei der Korrektur habe ich noch folgendes geändert:

- Pro Layer (wo die Legende von Bedeutung ist) gibt es jetzt einen Legenden-Link. Beispiel: Der Pflegeplan zeigt 4 Layer an: Pflegeplan, Überlagerung 1, Überlagerung 2 und die Teilflächen-Beschriftung. Nun werden für alle drei ersten Layer Legenden-Links angeboten
- Im Pflegeplan erscheint nun auch die Teilflächen-Beschriftung
- Bei anderen Layern Legenden ergänzt (was bei den LR zeigt, dass dort zuviele Kartierungen in einem Layer zusammengefasst sind - könnte man später einmal auseinandernehmen, wenn es wichtig ist)

Sollte in ein paar Minuten in v1.11.6 live sein
