### ISSUE TITLE
EKF: Kontrollen im gleichen Jahr nach Datum sortieren

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#318]
Bsp. EKF O. araneola, TPop 100.2

Habe ich 2 Kontrollen im gleichen Jahr. Die sollen im Baum chronologisch dargestellt werden.

**Comment by barbalex** [comment]
Wo sind diese zwei? Habe sie nicht gefunden. Dafür einen Fehler: jedes Mal, wenn man die Kontrolle öffnet, verdoppeln sich die Zählungen :-(

**Comment by barbalex** [comment]
Dass sich Knoten verdoppeln sollte nun in v1.11.7 behoben sein

**Comment by barbalex** [comment]
Im Prinzip ist ja das Vorhandensein mehrere Kontrollen pro Jahr problematisch, weil nicht per se klar ist, welche auszuwerten ist. Aber das lass ich mal eures Problem sein.

Darum sind sie auch nur mit dem Jahr und nicht mit dem Datum angeschrieben.

Denkt man also dein Anliegen durch, müsste im Strukturbaum das ganze Datum angezeigt werden, nicht nur das Jahr (und dann würde diese auch in der Sortierung berücksichtigt).

Was meinst du?

**Comment by csalzmann** [comment]
Bezüglich mehreren Kontrollen/Jahr hab ich ja noch eine Frage  an Dich offen in #320 .

Grundsätzlich stimme ich Dir zu. Aber was Du im Baum anzeigst und was Du rechnest muss ja nicht immer das gleiche sein. Ich frage mich eben, ob das Auge nicht abgelenkt wird vom ganzen Datum, und ob einfach eine Jahreszahl nicht einfacher zu erfassen ist. Je länger das Projekt dauert, je mehr Jahre müssen wir bei der Auswertung im Überblick haben.

Deshalb hätte ich eigentlich gerne die Sortierung nach Datum im Hintergrund, aber nur die Anzeige des Jahres wie bis anhin.

Was meinst Du?

**Comment by barbalex** [comment]
o.k., in v1.11.10 wird weiterhin Jahr angezeigt aber nach Datum sortiert. In:
- EK
- EKF
- Massnahmen

**Comment by csalzmann** [comment]
Reihenfolge im Jahr stimmt jetzt nicht immer. Könnte vielleicht da dran liegen, dass 2013 nur eine Jahreszahl und kein Datum erfasst wurde? 

Bsp. Himanto

![image](https://user-images.githubusercontent.com/6047564/65859285-1e8a6100-e368-11e9-8cb8-c5d413263a1c.png)

**Comment by barbalex** [comment]
Ja, denn es ist jetzt gar nicht mehr möglich, EKF nur mit Jahr zu erfassen

**Comment by barbalex** [comment]
O.k.: ich kann nach Jahr und erst danach nach Datum sortieren. Dann kommt es gut. Ist in v1.11.12 umgesetzt.
