### ISSUE TITLE
Freiwilligen-Kontrolle Datei hochladen 

### ISSUE THREAD

**Issue by praktikatopos** [barbalex/apf2#319]
Habe soeben versucht, bei Grationla officinalis, Tpop. 31.1, Freiwilligen-Kontrolle 2019, eine Datei hochzuladen. Die Datei konnte jedoch nicht hochgeladen werden

**Comment by barbalex** [comment]
Ich kann es nicht nachvollziehen.

Fragen:
- Bei welchem Schritt ging es nicht weiter?
- Gab es eine Fehlermeldung?
- Geschieht es bei dir immer?
- ...nur in dieser EKF?

**Comment by praktikatopos** [comment]
Ich konnte anwählen "Datei hochladen" - "Lokale Datei auswählen" - "Hinzufügen" und dann erscheint die Meldung "Kann nicht hochgeladen werden" (siehe Bild). Ist auch bei anderen EKFs der Fall
![Bildschirmfoto 2019-09-23 um 16 37 07](https://user-images.githubusercontent.com/42208152/65435210-69642000-de20-11e9-8469-26ed573abc3a.png)

**Comment by barbalex** [comment]
Kannst du mir die betreffende Datei schicken?

**Comment by barbalex** [comment]
Schliesse, da schon sehr alt
