### ISSUE TITLE
Zähleinheiten, Darstellung/Reihenfolge gemäss Eingabe

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#32]
Für uns wäre es angenehm, wenn die Darstellung der Einheiten entsprechend der Eingabe wäre. Also wenn 1. Zähleinheit Pflanzen, 2. Zähleinheit blühende Pflanzen so eingegeben wird, dann möchten wir diese Reihenfolge in der Ansicht im Stammbaum behalten. Das war auch schon bei V1 immer wieder ein Issue. Es fällt uns so einfacher, Äpfel mit Birnen zu vergleichen..:)

**Comment by barbalex** [comment]
Ist in der Entwicklungsversion korrigiert. Es dauert aber eine Weile, bis die Live-Version aktualisiert wird, da gerade die Beobachtungen umgebaut werden
