### ISSUE TITLE
Frage Mehrfach-Kontrollen / Jahr

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#320]
Die Qualitätskontrolle gibt einen Fehler aus bei Mehrfach-Kontrollen. Ich meinte, die solle darauf abzielen, dass wir am Ende nur 1 Kontrolle mit der Zieleinheit haben, damit die Zielberechnung automatisiert werden kann.
Nun irritiert mich aber die Überschrift, ich verstehe den Inhalt nicht:
![image](https://user-images.githubusercontent.com/6047564/65441106-227b2800-de2a-11e9-89d0-43d9e6cdaa7b.png)

Grundsätzlich meinte ich es so verstanden zu haben, dass ich bei Mehrfach-Kontrollen alle bis auf 1 Kontrolle  "im Jahresbericht nicht berücksichtigen" ankreuzen soll, damit dann eine mit passender Zieleinheit) und der höchsten Anzahl bleibt. Richtig?

**Comment by barbalex** [comment]
> Grundsätzlich meinte ich es so verstanden zu haben, dass ich bei Mehrfach-Kontrollen alle bis auf 1 Kontrolle "im Jahresbericht nicht berücksichtigen" ankreuzen soll, damit dann eine mit passender Zieleinheit) und der höchsten Anzahl bleibt. Richtig?

Ja, das sollte so sein. In der Abfrage werden ausdrücklich nur Zählungen derjenigen Kontrollen berücksichtigt, bei denen "im Jahresbericht nicht berücksichtigen" nicht gewählt wurde: https://github.com/barbalex/apf2/blob/a680d48354ea7272b2cedf561f8f741733cc36dc/sql/apflora/functions/qTpopCountedEinheitMultipleTimesInYear.sql#L20-L21

Wie würdest du den Sachverhalt in einem möglichst kurzen Titel erklären? Genau genommen wäre es: "und alle diese Zählungen sind im Jahresbericht nicht nicht zu berücksichtigen". Aber das tönt wegen der doppelten Verneinung sehr verwirrlich.

**Comment by csalzmann** [comment]
Zuerst noch eine Klärung. Es kommt drauf an, ob wir nur 1 Kontrolle gelten lassen wollen (mein Vorschlag) oder ob es um die Zähleinheiten geht. Wenn es explizit um die Zähleinheiten geht (wie die Fehlermeldung vermuten lässt), dann kann ich aktuell aber gar nicht selektiv etwas abwählen, dh von der einen Kontrolle die eine Einheit und von der anderen die andere Einheit nehmen. Wir arbeiten ja auf Ebene Kontrolle. Mein Vorschlag für die Fehlermeldung also wäre:

Es gab mehrere Kontrollen pro Jahr. Bitte die für den Jahrebericht die nicht relevanten ausschliessen ("im Jahresbericht nicht berücksichtigen"). 

Dazu kommt noch folgendes: Die Fehlermeldung gibt Mehrfachzählungen aus, die es gar nicht gab. Vermutlich, weil bei den EKF die Zähleinheiten schon vorgegeben wurden? Bsp. O. araneola, TPop 100.3. Rosetten wurden weder in der 1. noch in der 2. Zählung gezählt. 

![image](https://user-images.githubusercontent.com/6047564/65672289-0bfee780-e049-11e9-9869-250056332478.png)

**Comment by barbalex** [comment]
> Es gab mehrere Kontrollen pro Jahr. Bitte die für den Jahrebericht die nicht relevanten ausschliessen ("im Jahresbericht nicht berücksichtigen")

Im Moment kann die Datenbank nicht unterscheiden, ob die Tatsache, dass dieselbe Einheit mehrere Male verwendet wurde, daher kommt, dass:

- sie in mehreren Kontrollen gewählt wurde und alle sind nicht "nicht relevant"
- in einer Kontrolle zwei mal dieselbe Einheit erfasst wurde

Wenn der zweite Fall zutrifft, funktioniert dein Vorschlag nicht. Datum habe ich es nicht so formuliert.

Damit diese so wäre müssten wir einschränken, dass pro Kontrolle eine Einheit nur ein mal erfasst werden kann. Das ist möglich. Aber ein bisschen aufwändig:

- Kontrollieren, ob und wie viele Datensätze existieren, die dieser Einschränkung widersprechen
- Auflisten, welche Datensätze das sind
- Diese Datensätze korrigieren (das müsstet ihr machen)
- Nochmals kontrollieren, ob nun wirklich keine Datensätze mehr existieren, die dieser Einschränkung widersprechen
- Die neue Einschränkung einführen

Ich glaube, das wäre sinnvoll. Meinerseits rechne ich mit ca. 1.5 Stunden Aufwand.

**Comment by barbalex** [comment]
> Es kommt drauf an, ob wir nur 1 Kontrolle gelten lassen wollen (mein Vorschlag) oder ob es um die Zähleinheiten geht

Das war bisher nicht so abgemacht. Und es würde euch viel stärker einschränken, als es die bisherige Lösung tut. Denn wenn die eine Kontrolle nur einen Teil der wichtigen Einheiten gezählt hat und die nächste das nachholt, dann müsstet ihr das System umgehen und alles in einer Kontrolle erfassen, weil es sonst nicht möglich ist.

Ich glaube nicht, dass das zielführend ist.

**Comment by barbalex** [comment]
> Es gab mehrere Kontrollen pro Jahr. Bitte die für den Jahrebericht die nicht relevanten ausschliessen ("im Jahresbericht nicht berücksichtigen")

Ich hab grad gemerkt, dass obige Formulierung nur funktioniert, wenn maximal eine Kontrolle pro Jahr nicht "nicht relevant" sein darf. Was wie gesagt in meinen Augen nicht zielführend ist.

**Comment by barbalex** [comment]
> Dazu kommt noch folgendes: Die Fehlermeldung gibt Mehrfachzählungen aus, die es gar nicht gab. Vermutlich, weil bei den EKF die Zähleinheiten schon vorgegeben wurden? Bsp. O. araneola, TPop 100.3. Rosetten wurden weder in der 1. noch in der 2. Zählung gezählt.

Wieso taucht dieses Ergebnis in der QK nicht mehr auf?

Ich habe mit den Daten von Vorgestern verglichen. Offenbar wurde der Fehler korrigiert. Die Meldung war korrekt, denn es gab zwei EKF für das Jahr 2019. Beide mit vor-angelegten Zählungen, aber noch ohne Mengen. Wie das im EKF-Formular so ist.

**Comment by csalzmann** [comment]
Insgesamt ist dieser Punkt auch gemeinsam zu besprechen.

Was ich hier auch noch nicht verstehe: Finde es verwirrend, wenn vor-angelegte Zählungen als echte Zählungen ausgegeben werden, obwohl sie gar nicht gemacht wurden und es keine Eingabe dazu gibt. 

![image](https://user-images.githubusercontent.com/6047564/65814902-5d91a880-e1e8-11e9-8d76-ce3cfcf6c80c.png)

Betreffend Deinem Kommentar weiter oben: 
Es sollte sowieso nie vorkommen ,dass die gleiche Einheit in der gleichen Kontrolle mehrmals vorkommt. Das machte überhaupt keinen Sinn, deshalb müsste dieser Fall sowieso als Fehleintrag in der Qualitätskontrolle ausgeschlossen werden.

**Comment by rebeccakurz** [comment]
Karin und ich haben das noch zusammen angeschaut. 
Vielleicht könnte man die Qualitätskontrolle so nennen: "Dieselbe Einheit wurde im Berichtjahr mehrmals gezählt (Welche Kontrolle ist im Jahresbericht zu berücksichtigen?)"

> 
> Was ich hier auch noch nicht verstehe: Finde es verwirrend, wenn vor-angelegte Zählungen als echte Zählungen ausgegeben werden, obwohl sie gar nicht gemacht wurden und es keine Eingabe dazu gibt.
> 
> ![image](https://user-images.githubusercontent.com/6047564/65814902-5d91a880-e1e8-11e9-8d76-ce3cfcf6c80c.png)

Das sehen wir auch so, dass das nicht sein dürfte. Also bei den Erfolgskontrollen durch Freiwillige dürften die vorangelegten Zählungen noch nicht als Zählung gelten und somit auch nicht in der Qualitätskontrolle erscheinen. Kannst du das anpassen? Oder ist das jetzt sowieso nicht mehr der Fall? 
> 
> Betreffend Deinem Kommentar weiter oben:
> Es sollte sowieso nie vorkommen ,dass die gleiche Einheit in der gleichen Kontrolle mehrmals vorkommt. Das machte überhaupt keinen Sinn, deshalb müsste dieser Fall sowieso als Fehleintrag in der Qualitätskontrolle ausgeschlossen werden.

Auch da schliessen wir uns an. Zweimal die gleiche Einheit in einer Kontrolle sollte nicht vorkommen. Aber ich denke das ist höchstens in wenigen Fällen. Daher würde es vielleicht reichen, wenn das mit einer Qualitätskontrolle abgefangen wird und müsste nicht mit einer Einschränkung verhindert werden?

**Comment by rebeccakurz** [comment]
Können das ja auch dann persönlich besprechen.

**Comment by rebeccakurz** [comment]
Da in diesem Issue mehrere Fragen behandelt werden, schliesse ich diesen Issue und öffne mit den noch zu klärenden Fragen separate Issues.

--> 331: Nicht-ausgefüllte Zähleinheiten nicht im Strukturbaum anzeigen
--> 332: QK: Text ändern
--> 273: Pro Kontrolle soll jede Einheit nur einmal erfasst werden können
