### ISSUE TITLE
Qualitätskontrolle: Status Pop Text Qualitätskontrolle

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#321]
Diese Meldung zu diesem Fehler macht für mich nicht ganz Sinn. Der Fehler:

Pop Status Ansaatversuch
Letzter Kontrollbericht zunehmend
Lösung: Status muss angesiedelt, aktuell sein (statt Ansaatversuch)

Text QK "und es gab seither keine Ansiedlung", das verwirrt mich. Ist das relevant?

![image](https://user-images.githubusercontent.com/6047564/65442869-42601b00-de2d-11e9-9472-c9c3c8a728c2.png)

**Comment by rebeccakurz** [comment]
Heisst das nicht, dass wenn ein Kontrollbericht zunehmend ist, auch Pflanzen vorhanden sein müssen? Dann wäre es ja kein Ansaatversuch mehr, sondern eben eine angesiedelte, aktuelle TPop. Ausser wenn es seither eine Ansiedlung gegeben hätte, dann würden die Pflanzen aus dieser Ansiedlung stammen und eben nicht aus dem Ansaatversuch. Aber auch dann müsste der Status ja angesiedelt, aktuell sein?

**Comment by csalzmann** [comment]
Ja. Also im konkreten Bsp. oben gab es nach einer Ansaat eine positive EK und der TPop Bericht ist "zunehmend". Deshalb gab es auch korrekterweise eine Fehlermeldung weil der Status der TPop/Pop immer noch "Ansaatversuch" war, der musste auf "aktuell" gewechselt werden. Da bin ich mit der Lösung ja voll einverstanden, das ist die Ausgangslage.

Ich verstehe den Text der Qualitätskontrolle "und es gab seither keine Ansiedlung" nicht. Die Fehlermeldung müsste doch genau gleich kommen, auch rsp. umso mehr wenn es eine Ansiedlung gegeben hätte. ? Deshalb: ist das mit der Ansiedlung überhaupt relevant? Was für Fälle wären denn das?

**Comment by rebeccakurz** [comment]
Hm ja eigentlich ist das mit der Ansiedlung nicht relevant... Und es müsste in beiden Fällen eine Fehlermeldung geben.

**Comment by csalzmann** [comment]
@barbalex  Kannst Du helfen was gemeint ist?

**Comment by barbalex** [comment]
Diese QK ist aufgrund einer Excel-Liste von Charlotte entstanden. Vor einer Weile. Leider habe ich die Liste auch nach gründlicher Suche nicht gefunden. Daher bleibt mir auch nur, zu interpretieren, wieso Charlotte damals explizit wollte, dass diese Kontrolle nichts meldet, wenn seither neu angesiedelt wurde (denn sonst wäre es sicher nicht so umgesetzt worden - das ist _sehr_ aufwändig).

Ich kann mir vorstellen, dass es Fälle gibt, in denen nach der ersten Kontrolle nochmals nachgebessert wird (= nochmals ansiedelt). Vermutlich, weil man noch nicht sicher ist, dass es gelingt (sonst müsste man nicht nachbessern?). Und aus demselben Grund will man den Status noch nicht auf "etabliert" setzen.

**Comment by csalzmann** [comment]
Lieber Alex

Diese Fehlermeldung ist zu kompliziert, man versteht sie so nicht, wenn alle Fälle in der gleichen Meldung abgehandelt werden. Hat man nicht den Überblick über alle Fälle, verwirrt es sehr.

Der Fall, den Du oben erwähnst mit der Ansiedlung, müsste eine solche Fehlermeldung bekommen:

Teilpopulation: Status ist nicht aktuell (heisst "erloschen", "Ansaatversuch" oder "potenzieller Wuchsort"),  der letzte Kontrollbericht meldet "erloschen". Es gab aber seither eine Ansiedlung (Anm. EINE, nicht "keine". Das passiert relativ häufig, eine EK im Frühjahr, evtl Nachbessern im Herbst, wie Du es sagst :). )

Meiner Meinung nach ist die Meldung auf Pop-Stufe aber nicht nötig, das fängst Du mit Inkonsistenzen zwischen dem Status der Pop und der TPops ab. Oder? Die Meldung gibt es ja schon. 
Ob das mit dem "potenziellen Wuchsort"  rein soll, bin ich mir noch nicht sicher. Ich habe diese Matrix im Büro und aktuell keinen Zugriff drauf (schau ich mir nach den Ferien an).

Der von mir oben beschriebene Fehler liegt aber so:

Teilpopulation: Status ist nicht aktuell (heisst "erloschen", "Ansaatversuch" oder "potenzieller Wuchsort"), der letzte Kontrollbericht meldet aber "zunehmend".

Kannst Du die verschiedenen Fälle nicht auseinander nehmen? Es verwirrt, die gleiche Fehlermeldung für so viele verschiedene Fälle zu bekommen.

**Comment by barbalex** [comment]
Sorry, diese Sachen sind sehr aufwändig. Ich brauche Stunden, um solchen Fragen die nötige Aufmerksamkeit zu widmen, alle Ziele, Wünsche und Argumente zusammenzutragen, zu verstehen, wieso es heute so ist wie es ist und dann zu beurteilen, was möglich ist. Es gibt viel zu viel Potential nicht alles zu verstehen, aneinander vorbei zu schreiben oder zu verschlimmbessern.

Ich schlage vor: 

- Ihr sammelt alle Anliegen betreffend QK. Plus eure ursprüngliche Vorgabe. 
- Wir treffen uns, gehen die ganze Liste gemeinsam durch und diskutieren es durch. Dafür brauchen wir ein paar Stunden
- Dann budgetieren/planen wir die Anpassungen

Momentan werde ich durch diese Fragen völlig blockiert. Ich habe keine Chance, mich um die übrigen Pendenzen in apflora, vermehrung und anderen Projekten zu kümmern. Und so viel Aufwand war weder geplant noch budgetiert.

**Comment by csalzmann** [comment]
OK! Ich dokumentiere aber Fehler weiterhin hier. Ab dem 7. Okt. bespreche ich die Sache mit Karin M. , dann bin ich wieder in Zürich.

**Comment by barbalex** [comment]
Ja, dokumentieren ist immer gut

**Comment by barbalex** [comment]
Am 28.1.2020 an Sitzung in Topos bestimmt: Meldung und QK sind korrekt.
