### ISSUE TITLE
EKF: Reihenfolge Zähleinheiten Baum und Formular nicht gleich

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#322]
Obwohl ich bein den EKF-Einheiten Sortierung angegeben habe

![image](https://user-images.githubusercontent.com/6047564/65677437-e0ccc600-e051-11e9-9cb0-c86c736f8284.png)

**Comment by rebeccakurz** [comment]
siehe Issue #304 

Habe das auch schon festgestellt und Alex gefragt. Seine Antwort siehst du im anderen Issue. Habe dann befunden, dass es mir reicht, wenn es im Formular richtig ist. Wäre zu klären ob wir da was machen lassen wollen?

**Comment by rebeccakurz** [comment]
Momentan nicht nötig
