### ISSUE TITLE
EKF Zusätzliche Zähleinheit

### ISSUE THREAD

**Issue by praktikatopos** [barbalex/apf2#323]
Wenn ich bei einer Freiwilligenkontrolle eine zusätzliche Zähleinheit eingeben will, dann speichert es die Einheit nicht. Ablauf: Ich erstelle eine neue Freiwilligenkontrolle. Bei Zähleinheit 3 klicke ich auf NEU. Dann möchte ich die Einheit eintippen. Sobald ich in ein anderes Feld klicke, verschwindet die Einheit aber wieder. Erst wenn ich sie über den Strukturbaum eingebe, bleibt sie erhalten (dies ist nur der Fall beim Erfassen der Einheit (z.B. Rosette, Blüte) nicht aber beim Erfassen der Zählung (1, 2, ...). Das Problem hatte ich bei diversen Arten.

**Comment by barbalex** [comment]
@csalzmann Ich kopiere dich rein, damit du siehst, wie schwierig das System zur Erfassung von EKF zu verstehen ist. Und ihr vielleicht eher intern koordinieren könnt, bevor ihr Issues eröffnet - solche Erklärungen sind für mich sehr aufwändig und nicht budgetiert. Momentan werde ich überschwemmt und ich sollte in so vielen Projekten vorwärts machen :-(

Dieses Formular ist aufgrund eurer Vorgaben technisch extrem kompliziert. Ich kann gar nicht aufzählen, was hier alles berücksichtigt werden muss.

Unter anderem aber:

- Freiwillige sollen hier nicht einfach alles erfassen können was sie wollen
- Es gibt im Strukturbaum unter dem Aktionsplan den Ast "EK-Zähleinheiten". Dort ist definiert, welche Einheiten erfasst werden sollen und welche davon zielrelevant sind, also bei der EK-Planung und auch sonst im zeitlichen Verlauf dargestellt werden sollen
- Es dürfen maximal drei "EK-Zähleinheiten" pro Aktionsplan erfasst werden
- Es wird von den Freiwilligen erwartet, dass sie "EK-Zähleinheiten" erfassen
- Darum werden in neuen EKF genau die "EK-Zähleinheiten" eingefügt
- Freiwillige können weniger Einheiten erfassen, also keine Anzahl erfassen oder eine Zählung im Formular EKF löschen
- Weil sie eine gelöschte Zählung wieder herstellen können sollten (vielleicht war das Löschen ein Fehler?) gibt es dafür die "Neu"-Schaltfläche
- Freiwillige dürfen im Formular EKF aber keine Einheiten erfassen, die nicht "EK-Zähleinheiten" sind

O.k., das ist die Ausgangslage. Nun zu dem vermeintlichen Fehler: Leider hast du keine konkreten Beispiele genant. Darum muss ich raten. Aber ich kann das Verhalten erklären, WENN: du das bei einem AP gemacht hast, in dem weniger als 3 "EK-Zähleinheiten" erfasst wurden.

- In diesem Fall werden in einem neuen EKF-Formular weniger als drei Zählungen eingefügt
- Weil es wie oben erklärt, möglich sein muss, neue Zählungen erfassen zu können, erscheint die "Neu"-Schaltfläche
- Weil aber keine weiteren Zähleinheiten zur Verfügung stehen, kann man in der so geschaffenen Zählung keine Einheit auswählen: das Feld bietet in der Auswahlliste keine Zähleinheit an. Es wurden schon alle verfügbaren "verbraucht"
- Offenbar versuchst du die Zähleinheit zu tippen, weil sie dir nicht in der Liste angeboten wird. Das ist nicht vorgesehen. Es kann nicht funktionieren, denn es wird nicht der Text gespeichert sondern die ID der Zähleinheit (Zähleinheiten sind zentral definiert). Und das ist ein Dropdown-Feld, das keine Text-Eingabe akzeptiert, _wenn sie nicht einem Eintrag in der Auswahlliste entsprechen_
- Darum verschwindet der Text sofort wieder, wenn du das Feld verlässt
- Zum Verständniss: Du _kannst_ tippen und ist bei grossen Auswahllisten nützlich, weil es die Auswahlliste filtert, d.h. reduziert
- Man kann auch Tippen und sobald der gewünschte Eintrag grau markiert ist, die TAB-Taste drücken. Womit der Wert ausgewählt ist, ohne dass man zur Maus greifen musste
- Dafür ist es also möglich, in diesem Feld zu tippen. Und nicht, um Werte zu erfassen, die nicht in der Liste enthalten sind

Ich schliesse diesen Issue, weil es kein Fehler ist. Du hast versucht, das vorgegebene System zu umgehen, indem du Zählungen tippst, die nicht gewählt werden können sollen.
