### ISSUE TITLE
EK-Planung Kopfzeile fixiert

### ISSUE THREAD

**Issue by praktikatopos** [barbalex/apf2#324]
Ek-Planung: Wenn man nach rechts scrollt, verschieben sich alle Spalten ausser die Spalten der Kopfzeile. Die Kopfzeile schein festgefroren/fixiert (siehe Bild)
![Bildschirmfoto 2019-09-26 um 14 37 33](https://user-images.githubusercontent.com/42208152/65688335-3feb0480-e06b-11e9-8ada-62897a5dbf02.png)

**Comment by praktikatopos** [comment]
Ebenfalls ist mir aufgefallen: Wenn das Fenster nicht gross genug ist, sodass man nach rechts scrollen muss um die hinteren Spalten anzusehen, so werden die Spalten hinter "Ereignisse" nie angezeigt (also alle Spalten mit Jahreszahlen) (Siehe Bild oben -> Scroll-Balken geht nicht weiter nach rechts). Erst wenn man das Fenster genug gross macht, bis man eine der Zahlen sieht, kann man weiter nach rechts scrollen

**Comment by barbalex** [comment]
Danke für die Meldung. Dieses Verhalten war mir nicht aufgefallen.

Da gibt es bestimmt zu Verbessern. Ich muss aber auch erklären, wieso nicht alle Bedürfnisse gleichzeitig gedeckt werden können.

Das Formular _kann_ nur auf grossen bzw. hoch aufgelösten Bildschirmen und in grossen Fenstern funktionieren. Ansonsten macht es keinen Sinn. Denn der Zweck des Formulars ist es, einen Überblick über grosse Datenmengen zu erhalten bzw. effizient nacheinander viele TPop's zu beurteilen.

Wenn man wie in deinem Fall keine einzige Jahresspalte sieht (was dieses Verhalten auslöst), macht das Ganze eigentlich gar keinen Sinn: Du wirst so nie einen Überblick erhalten. Denn wenn du für die Jahresspalten scrollen musst, kannst du während des Scrollens eigentlich nur eine Zeile aufs Mal anschauen. Wozu dann das Formular? Dann hätte man diese Funktionen besser im Formular der Teil-Population integriert. Und nur um eine Liste der TPop zu sehen ist dieses Formular viel zu aufwändig.

Das ist so, als ob du dich in einer riesigen Excel-Tabelle bewegen müsstet, die viel breiter ist, als dein Bildschirm.

Darum habe ich diese Situation selber nie getestet. Ich bin nicht auf die Idee gekommen, dass jemand versuchen würde, unter diesen Umständen mit diesem Formular zu arbeiten.

Topos will viele Felder anzeigen können. Deshalb wird der Bereich links der Jahres-Felder sehr breit.

Darum gibt es auch die Option oben rechts, einen Teil der Felder auszublenden ("Felder wählen"). Wenn man auf nicht sehr grossen Bildschirmen arbeitet, wird man kaum darum herum kommen, diese Option zu nutzen.

Das kann helfen, um dieses Verhalten zu umgehen.

Denn diesen Issue zu korrigieren wird nicht ganz einfach: Das Formular ist extrem komplex, v.a. auch das Scroll-Verhalten. Keine Ahnung, wie lange ich brauche, um diese Verhalten zu verbessern.

Ich finde diesen Issue zwar berechtigt (es ist zweifellos ein Fehler) aber nicht sehr prioritär. Es gibt bestimmt wichtigere Probleme, die in diesem Formular zu lösen sind. Oder Verbesserungen, die mit demselben Aufwand erzielt werden können. Wenn ihr anderer Meinung seid, bitte widerspricht.

Kleine Bemerkung am Rand: Seit eurer EDV-Umstellung sind auch andere Fragen aufgetaucht, die mit Platz-Problemen zu tun haben. Habt ihr etwa neu Notebooks und daher kleinere Bildschirme?

**Comment by rebeccakurz** [comment]
Ich stimme dir zu, dass es nicht höchste Priorität hat, aber eben doch ein Fehler ist. Ich habe jetzt auch noch ein wenig herumgescrollt, mal mit grösserem, mal mit kleinerem Bildschirm und habe auch einen Teil der Felder ausgeblendet, um mehr Platz für die Jahresspalten zu bekommen. 
Dabei ist es auch immer wieder zu Verschiebungen der Kopfzeile gekommen (siehe Screenshot). Vor allem bei den Jahresspalten, die ja nicht sehr breit sind, könnte eine Verschiebung zu Problemen führen, wenn man dann aus Versehen in der falschen Spalte landet oder was denkst du? Das sollte also behoben werden, bevor die Artverantwortlichen dann ihre Planungen machen.

**Comment by rebeccakurz** [comment]
Ah und zur Frage wegen den kleineren Bildschirmen: Nein, wir arbeiten neu nicht mit Notebooks. Ich habe nur temporär einen benutzt, da nach der IT-Umstellung noch nicht alles wieder eingerichtet war und ich nicht am Mac arbeiten konnte. 
Wir arbeiten ja mit zwei Bildschirmen. Meistens habe ich ein Programm/eine Anwendung nur auf einem Bildschirm offen, also nicht über beide aufgezogen. Dann sehe ich so viel von der FloraDB wie auf dem Screenshot. Vielleicht wäre es daher möglich ein paar Felder noch etwas schlanker zu machen? Also eigentlich nur die Spalte "EK-Abrechnungstyp", die nimmt relativ viel Platz ein. Ist das sehr aufwändig?
<img width="2044" alt="Bildschirmfoto 2019-09-30 um 11 33 40" src="https://user-images.githubusercontent.com/30288503/65868099-f3a80900-e377-11e9-8f84-d12dc291c91d.png">

**Comment by rebeccakurz** [comment]
> Ich stimme dir zu, dass es nicht höchste Priorität hat, aber eben doch ein Fehler ist. Ich habe jetzt auch noch ein wenig herumgescrollt, mal mit grösserem, mal mit kleinerem Bildschirm und habe auch einen Teil der Felder ausgeblendet, um mehr Platz für die Jahresspalten zu bekommen.
> Dabei ist es auch immer wieder zu Verschiebungen der Kopfzeile gekommen (siehe Screenshot). Vor allem bei den Jahresspalten, die ja nicht sehr breit sind, könnte eine Verschiebung zu Problemen führen, wenn man dann aus Versehen in der falschen Spalte landet oder was denkst du? Das sollte also behoben werden, bevor die Artverantwortlichen dann ihre Planungen machen.

Hier noch der Screenshot:
<img width="1876" alt="Bildschirmfoto 2019-09-30 um 11 20 52" src="https://user-images.githubusercontent.com/30288503/65868205-24883e00-e378-11e9-8863-359222e4e0ce.png">

**Comment by barbalex** [comment]
> Also eigentlich nur die Spalte "EK-Abrechnungstyp", die nimmt relativ viel Platz ein. Ist das sehr aufwändig?

Da steht erst noch das Falsche drin.

Reicht die Abkürzung oder soll der volle Text des Abrechnungstyps sichtbar sein?
Beispiel: "B" oder "B (Umsetzungsbudget Überwachung ursprüngliche Pop)"?

**Comment by barbalex** [comment]
Zu den verschobenen Jahresspalten: Ja, das kann passieren, wenn man ganz ans Ende kommt. Wenn man ein bisschen hin und zurück scrollt, renkt sich das wieder ein. Aber es sollte nicht sein. Ist leider schwierig zu beheben. Werde wohl nochmals dahinter müssen.

**Comment by barbalex** [comment]
Hab für die sich verschiebenden Jahreszeilen einen eigenen Issue gemacht. Wenn wir dinge in einem Issue vermischen, gehen sie sonst unter: https://github.com/barbalex/apf2/issues/327

**Comment by rebeccakurz** [comment]
> > Also eigentlich nur die Spalte "EK-Abrechnungstyp", die nimmt relativ viel Platz ein. Ist das sehr aufwändig?
> 
> Da steht erst noch das Falsche drin.
> 
> Reicht die Abkürzung oder soll der volle Text des Abrechnungstyps sichtbar sein?
> Beispiel: "B" oder "B (Umsetzungsbudget Überwachung ursprüngliche Pop)"?

Achso! Nein dann macht das keinen Sinn. Wir hätten gerne den ganzen Text in diesem Feld, nicht nur die Abkürzung. Dann kann man es immer nochmals nachlesen.

**Comment by barbalex** [comment]
EK-Abrechnungstyp: in v1.11.13 steht das Richtige drin

**Comment by barbalex** [comment]
Ich schliesse mal diesen Issue, weil die Jahresspalten sich auf Chromium-Browsern nicht mehr verschieben sollten
