### ISSUE TITLE
Feldkontrolle - EK

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#325]
Ich habe grad den Reiter EK entdeckt . Mega cool!

Kann man da dann auch gleich eingeben, wenn z.B. für 2020 eine EK wiederholt werden muss (Bedingungen waren nicht gut, Resultat schlecht etc)? Kann man hier und in der Tabelle planen?

**Comment by barbalex** [comment]
Nein, das ist momentan eher eine Planungs-Leiche. Ich dachte urprünglich, es könnte nützlich sein und hab das begonnen, vor dem EK-Formular. Früher war auch noch der Abrechnungstyp drin, aber der wurde ja zur EK-Frequenz gezügelt. Daher ist es jetzt auch eher leer. 

Ich glaube aber jetzt nicht mehr, dass EK planen ohne Übersicht sinnvoll ist.

Ihr könnt besser sagen, was hier nützlich wäre.

**Comment by barbalex** [comment]
schliesse das, weil vermutlich nicht mehr aktuell
