### ISSUE TITLE
Jahreszahl Feldkontrolle Strukturbaum Reihenfolge falsch

### ISSUE THREAD

**Issue by praktikatopos** [barbalex/apf2#326]
Potentilla leucopolitana, Tpop. 1.1, Feld-Kontrollen: Die Kontrolle des Ausgangszustandes von 1998 wird im Strukturbaum nicht richtig sortiert und erscheint nach dem Jahr 2019. Nicht sicher, ob das auch bei anderen Tpops der Fall ist.

**Comment by barbalex** [comment]
Duplikat von https://github.com/barbalex/apf2/issues/318#issuecomment-536446977

Ich habe vor wenigen Stunden v1.11.12 publiziert, das diesen Fehler korrigiert. Vermutlich hat sich deine Version noch nicht aktualisiert: Bitte neu Starten und dann ein paar Sekunden warten, bis sich die App aktualisiert, bevor du etwas machst.
