### ISSUE TITLE
Ja/Nein-Felder: verständlicher gestalten

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#328]
Hoi Alex 
Du hast ja für uns auch in den Feldkontrollen ein Feld für die Angabe geschaffen, ob Jungpflanzen vorhanden sind. Nun habe ich aber gar nicht gemerkt, dass man mit einem zweiten Klick auf das Feld auch "Nein" angeben kann. Ich bin gar nie solange auf diesem Feld geblieben, dass ich die Erklärung gesehen hätte, die ja irgendwann aufpopt. 
Könntest du das noch anpassen, dass entweder wie in den Freiwilligen-Kontrollen zwei Felder (Ja und Nein) zum Ankreuzen vorhanden sind oder dass man wenigstens den Text zu diesem Feld auf Anhieb sieht? Vielleicht auch als Erklärungstext neben dem Feld, wenn die zwei Felder im Moment zu aufwändig sind?
So könnten wir Fehler vermeiden, wenn ja jetzt viele Feldkontrollen eingegeben werden...

**Comment by barbalex** [comment]
> So könnten wir Fehler vermeiden, wenn ja jetzt viele Feldkontrollen eingegeben werden...

Ich verstehe nicht, was hier ein Fehler wäre.

Ja/nein-Felder konnten bisher nur zwei Werte anzeigen: Ja oder Nein. In Wahrheit aber war der Wert bisher "null" (zu verstehen als: "unbestimmt"), bevor jemand "ja" oder "nein" setzte.

Bei den meisten Ja/Nein-Feldern hat es Sinn gemacht, in neuen Datensätzen einen Standardwert zu setzen. Bei diesem hier aber nicht: Ob Jungpflanzen vorhanden sind soll bestimmt nur von Mitarbeitern beurteilt werden. Es soll auch klar sein, ob eine solche Beurteilung stattfand. Daher macht "unbestimmt" in diesem Feld Sinn.

Vor meiner kürzlichen Anpassung konnte man aber zwischen "unbestimmt" und "nein" in der Benutzeroberfläche nicht unterscheiden. Eine normale Option kennt nur zwei Werte ja oder nein.

Nun kann man aber zwischen unbestimmt und nein unterscheiden.

Und das soll Fehler ermöglichen? Wieso?

Wenn schon ein "Fehler" möglich war, dann früher, als es sein konnte, dass die Mitarbeiterin "nein" erfassen wollte, das aber nicht machte, weil offenbar "nein" schon erfasst war (weil man "nein" nicht von "null" unterscheiden konnte).

Und ja: Doppelte Ja/nein-Options-Felder sind nicht Standard, aufwändig und fehlerträchtig. Das möchte ich wenn irgend möglich vermeiden. Ich hab mich da im EKF auf etwas eingelassen, was ich seither bereue.

Aber bezüglich Klarheit lässt sich definitiv etwas verbessern und deine Idee, daneben einen immer sichtbaren erklärenden Text zu platzieren finde ich gut. Ist in v1.11.14 umgesetzt.

**Comment by rebeccakurz** [comment]
"Wenn schon ein "Fehler" möglich war, dann früher, als es sein konnte, dass die Mitarbeiterin "nein" erfassen wollte, das aber nicht machte, weil offenbar "nein" schon erfasst war (weil man "nein" nicht von "null" unterscheiden konnte)."

Doch es ist eben genau dieser Fehler wieder passiert. Simone dachte, das durchgestrichene Feld (=unbestimmt) heisse "Nein" und einmal Klicken "Ja". Sie hat den Erklärungstext eben auch nicht gesehen. 

Aber mit dem sichtbaren Erklärungstext ist es jetzt sicher mal nicht schlecht, danke!

**Comment by barbalex** [comment]
> Simone dachte, das durchgestrichene Feld (=unbestimmt) heisse "Nein" und einmal Klicken "Ja"

O.k., danke für den Input

**Comment by csalzmann** [comment]
Lieber Alex
Jetzt komm ich auch noch mit dem Issue. Bin erst jetz darüber gestolpert. Ich finde die jetzige Lösung auch/immer noch fehleranfällig und für den Benutzer sehr ungewohnt. Man versteht das einfach nicht richtig.

Könntest Du nicht zwei Felder machen wie bei den EKF und wie ursprünglich im Issue von Rebecca vorgeschlagen?


![Bildschirmfoto 2019-10-09 um 15 03 52](https://user-images.githubusercontent.com/6047564/66484025-7894d000-eaa6-11e9-8a96-a46562907835.png)

**Comment by barbalex** [comment]
Wie oben erklärt entspricht das nicht dem HTML-Standard. 

Ich muss also dafür ein eigenes Werkzeug bauen. Und das hat sich bei der EKF als überraschend komplex herausgestellt. Ich war selber überrascht, was alles programmiert werden muss und wie viele Spezialfälle es gibt. Der Grund ist: Auswahlfelder sind nach HTML-Standard definiert. Ihr Verhalten kann nicht verändert werden. Man muss sie also "übersteuern" und ihr Verhalten verändern. Das betrifft:
- Darstellung
- Laden von Werten
- Verhalten beim Klicken
- Wann ein Wert aktualisiert wird (weil die Werte ja speziell geladen werden müssen)
- und bestimmt habe ich jetzt etwas vergessen

Und weil es so kompliziert und fehleranfällig ist, muss ich dafür und für alle denkbaren Fälle Tests bauen.

Ich schätzte, das gibt mir drei Stunden Aufwand. Mindestens. Leider.
Daher kann ich das nicht einfach auch noch machen. Wenn ihr es so wollt, müssen wir das ins Budget aufnehmen.

**Comment by barbalex** [comment]
Ist in Version 1.49.6 implementiert
