### ISSUE TITLE
Google Chrome Hinweis

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#329]
Hinweis gut sichtbar platzieren, dass Anwendung auf Google Chrome optimiert ist.

**Comment by barbalex** [comment]
Gute Idee.

Habe ein Werkzeug gefunden, dass mir dafür geeignet erscheint:

Wenn jemand apflora.ch besucht, prüft das Werkzeug den Browser. Falls der zwei oder mehr Versionen hinter der aktuellen Version ist, erscheint ein Hinweis am unteren Bildschirmrand:
<img width="852" alt="2019-10-09_13h37_23" src="https://user-images.githubusercontent.com/669783/66478236-349bce00-ea9a-11e9-9e1c-be56063eda94.png">

Klickt jemand auf "Browser aktualisieren", öffnet sich diese Seite, die bei alten Versionen weiterhilft: https://browser-update.org/update-browser.html?force_outdated=true#3.3.1npm:localhost

**Comment by barbalex** [comment]
Ist umgesetzt in v1.12.0

**Comment by barbalex** [comment]
Damit ist natürlich nicht abgefangen, dass Drucke nur in Chrome (und künftig in Edge) richtig funktionieren
