### ISSUE TITLE
EK-Eingabe, einfacher zum Ziel?

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#33]
Vielleicht gibts noch eine Abkürzung, wie man zu der Eingabe der Zähleinheiten kommt? Es ist mir klar, dass es so sehr logisch ist. Es braucht aber sehr viele Klicks, um zum Ziel zu kommen, also die Eingabe zu machen. Es ist einfach nicht sehr benutzerfreundlich, statt 1 Klick wie vorher braucht es 3.

**Comment by barbalex** [comment]
o.k., ab jetzt öffnet sich der Zählungen-Ordner immer von selbst

- damit sieht man die schon erfassten Zählungen sofort
- und für die Eingabe einer neuen Zählung braucht es zwei Klicks
