### ISSUE TITLE
Nicht-ausgefüllte Zähleinheiten nicht im Strukturbaum anzeigen

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#331]
Die vorangelegten Zähleinheiten aus den Freiwilligen-Erfolgskontrollen, die aber keine Zählung enthalten respektive nicht ausgefüllt werden (was es sehr häufig gibt), sollten im Strukturbaum nicht sichtbar sein, zwecks besserer Übersicht. Ist das möglich?

![](https://user-images.githubusercontent.com/6047564/65814902-5d91a880-e1e8-11e9-8d76-ce3cfcf6c80c.png)

**Comment by barbalex** [comment]
Ja, aber das ist eine Stunde Aufwand

**Comment by rebeccakurz** [comment]
Okay, falls noch Budget vorhanden ist, dann gerne umsetzen! Vielen Dank

**Comment by barbalex** [comment]
Ist in Version 1.49.1 implementiert. Es werden nur noch Zählungen mit Anzahl angezeigt
