### ISSUE TITLE
QK: Text ändern

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#332]
Könnte man bei dieser Qualitätskontrolle (siehe Screenshot) den Text anpassen zu:  "Dieselbe Einheit wurde im Berichtjahr mehrmals gezählt (Welche Kontrolle ist im Jahresbericht nicht zu berücksichtigen?)"

![Bildschirmfoto 2019-10-09 um 16 56 57](https://user-images.githubusercontent.com/30288503/66493155-d67ce400-eab5-11e9-9a85-e76c917625af.png)

**Comment by barbalex** [comment]
Gemäss Vorschlag in Wunschliste_APFlora_DB_20200204.xlsx angepasst
