### ISSUE TITLE
Wenn neue Version APFlora Blink

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#333]
Nichts schlimmes, aber:

Es ist ja extrem lässig, speichert apflora, wo man das letzte mal war.

Wenn man aber eine neue Version herunterladen sollte (man sich also neu anmelden muss), dann blinkt jetzt die ganze Website, anstatt dass man gleich zum Anmeldefenster kommt wie bisher. Jetzt muss man das blinkende Browser-Fenster schliessen, wieder neu auf apflora gehen, und erst wenn man dann auf "Aktionspläne bearbeiten" geht kommt das Anmeldefenster.

**Comment by barbalex** [comment]
Ja, das ärgert mich auch

**Comment by barbalex** [comment]
Leider weiss ich nicht, was das verursacht. Könnte etwas mit Prozessen zu tun haben, die während des App-Starts gleichzeitig passieren und eine Endlos-Schlaufe verursachen.

In Version 1.19.1 habe ich das Verhalten beim Vorliegen von Updates geändert: Statt einem sofortigen refresh wird die Benutzerin gefragt, ob sie aktualisieren will. Vielleicht nützt das.

**Comment by barbalex** [comment]
Hm. Das Problem liegt viel tiefer. Es ist ein Fehler mit dem service-worker. Er ist dafür zuständig, zu erkennen, wenn die Seite aktualisiert wurde und dann die neuen Dateien herunterzuladen.

Diesen Code habe ich nicht selber geschrieben. Ich kann nur hoffen, dass andere den Fehler finden.

Jemand anderes hat einen sehr ähnlichen Fehler dokumentiert und ich habe diesen hier ergänzt: https://github.com/gatsbyjs/gatsby/issues/18531#issuecomment-543905801

**Comment by barbalex** [comment]
5 Stunden harte Arbeit und 30 Versionen von apflora später habe ich leider immer noch keine Lösung 😞 

Der Fehler liegt eindeutig im service-worker. Ich konnte ihn recht genau eingrenzen: https://github.com/gatsbyjs/gatsby/issues/18531#issuecomment-543991259.

Nur ist es mir leider nicht gelungen, ihn zu umgehen.

Hoffen wir, dass der Autor des service-workers reagiert.

**Comment by csalzmann** [comment]
Oh jemine, Du armer. Also beim Aufstarten heute hat es leider immer noch geblinkt bei mir.

Wie wäre es denn, wenn Du es wieder so machst, dass man sich jedes Mal anmelden muss, nachdem man den Browser geschlossen hat?

**Comment by barbalex** [comment]
O.k., in v1.19.34 gemacht. Es löst das zugrundeliegende Problem nicht. Aber die Nachteile (Vergesslichkeit) sind kleiner als dieses grauenhafte Verhalten beim Start nach Update. Ich schliesse daher dieses Issue zugunsten eines neuen, um die Erinnerung wieder einzuschalten: https://github.com/barbalex/apf2/issues/334

**Comment by csalzmann** [comment]
Also leider nützt das gar nichts, bei mir blinkt es nach wie vor. Oder ist das, weil mein letzter Stand noch vor 19.34 war?

**Comment by barbalex** [comment]
> Oder ist das, weil mein letzter  Stand noch vor 19.34 war?

Ja, genau

**Comment by barbalex** [comment]
O.k., das Problem wurde von einem anderen Entwickler gelöst: https://github.com/gatsbyjs/gatsby/pull/19159. Es lebe open source!

Habe die Erinnerung wieder eingeschaltet.
