### ISSUE TITLE
Verorten auf Karte -> Blümchen erscheint nicht, Koordinaten werden aber gesetzt

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#335]
Habe eine neue TPop gegründet und wollte diese per Rechtsklick, "verorte auf Karte" auf der Karte verorten. Es hat dann auch die Koordinaten gesetzt, aber es ist kein Blümchen an diesem Ort erschienen. 
Erst nachdem ich die Seite neu geladen habe, ist das Blümchen erschienen.

**Comment by barbalex** [comment]
Hoi Rebecca

Bei mir funktioniert es.

Die Art, wie du es beschreibst, tönt nicht so, als ob das bei dir _immer_ passiert.
Ist das nur ein mal passiert und sonst klappt es auch bei dir?

Wenn du Fehler meldest, ist das Wichtigste, dass ich es nachvollziehen kann. Voraussetzung dafür ist, dass _du_ es nachvollziehen kannst. Und mir eine Methode beschreibst, mit der _du_ den Fehler einigermassen zuverlässig provozieren kannst.

Ansonsten können wir das nur als schlechte Laune des IT-Gottes abbuchen. Und konzentrieren uns besser auf Wichtigeres.

Ich werde diesen Issue schliessen, damit ich in den Issues den Überblick nicht verliere und mich auf Wichtiges konzentrieren kann. 

Wenn du eine Methode findest, wie man das einigermassen zuverlässig provozieren kann, dann öffnen ihn bitte wieder - oder einen neuen (egal).

**Comment by rebeccakurz** [comment]
Ja es ist wie du sagst, es passiert nicht immer. Aber eben doch ein paarmal, so dass ich es eine Meldung wert fand... Werde mich wieder melden, falls ich es zuverlässig provozieren kann.
