### ISSUE TITLE
Fehlermeldung Freiwilligen-Kontrolle Zähleinheit

### ISSUE THREAD

**Issue by praktikatopos** [barbalex/apf2#336]
Fehlermeldung bei folgender Tpop: Pulsatilla vulgaris, Tpop 36.1, Freiwilligen-Kontrolle 2010, Zähleiheiten "Blüten" und "Pflanzen". Bevor diese Meldung erschienen ist, habe ich die Anzahl dieser beiden Zähleinheiten in der Ansicht "Protokollblatt" geändert.

![Bildschirmfoto 2019-10-28 um 16 29 29](https://user-images.githubusercontent.com/42208152/67692287-3d4c3980-f9a0-11e9-84d0-8ede12403ab5.png)

![Bildschirmfoto 2019-10-28 um 16 32 13](https://user-images.githubusercontent.com/42208152/67692515-89977980-f9a0-11e9-9aab-b74dafb6ad0d.png)

**Comment by barbalex** [comment]
Wurde kurz zuvor von @rebeccakurz  gemeldet und mit https://github.com/barbalex/apf2/issues/339 verhindert.

Version 1.19.37, die das verhindert, wird soeben hochgeladen.

Danke für die Meldung!
