### ISSUE TITLE
Zählungen: Es gibt Fälle, in denen die Einheit nicht angezeigt wird

### ISSUE THREAD

**Issue by barbalex** [barbalex/apf2#337]
Siehe @rebeccakurz  https://github.com/barbalex/apf2/issues/273#issuecomment-545393967

> Ich bin gerade am Bearbeiten der Liste mit den doppelten Einträgen. Dabei ist mir aufgefallen, dass bei einigen Feldkontrollen bei den Zählungen im Strukturbaum korrekt dargestellt werden, im Formular aber die Zähleinheit nicht angezeigt wird (nur die Zählung und die Methode; siehe Screenshot). Ist das ein Darstellungsproblem?

**Comment by barbalex** [comment]
@rebeccakurz 
Das ist eher ein "feature" als ein "bug": In dem von dir beschriebenen Fall gibt es in derselben Kontrolle zwei Zählungen, welche dieselbe Einheit zählen. Das ist nicht vorgesehen, weil nicht sinnvoll. Denn: Welche Zahl ist nun richtig?

Gerade darum sind diese Datensätze in meiner Abfrage erschienen. Gerade darum musst du sie korrigieren. Damit dann künftig ein Index auf der Datenbank zusätzlich zu diesem Feature verhindert, dass dies passieren kann.

Und weil das nicht sinnvoll ist, wird eine Einheit nicht mehr zur Auswahl angeboten, wenn sie in derselben Kontrolle bereits gewählt wurde. Damit man sie gar nicht ein zweites Mal wählen kann.

Diese Funktion hat den von dir beschriebenen Nebeneffekt. 

In diesem Fall war es wohl möglich, zwei mal dieselbe Einheit zu wählen, weil das 2005 passierte, also bevor apflora eine bereits gewählte Einheit nicht mehr anbot.

Das ist heute nicht mehr möglich, weil man in der zweiten Zählung dank dieser Funktion dieselbe Einheit gar nicht mehr wählen kann.

In meinen Augen ist das also 
1. ein Feature, kein Bug
2. Gerade was wir verhindern wollen
3. Was mit dem Index erzwungen wird, der erst gesetzt werden kann, wenn du diese Datensätze korrigiert hast.

Darum schliesse ich diesen Issue gleich wieder.

**Comment by barbalex** [comment]
@rebeccakurz 
In https://github.com/barbalex/apf2/issues/273#issuecomment-545487544 schreibst du:
> Ich wollte gerade: bei einer Teilpopulation bei einer Zwischenbeurteilung die Zählungen zusammenfassen, weil einmal "blühende Pflanzen geschätzt" und einmal "blühende Pflanzen gezählt" drin war. Als ich auf die eine Zählung geklickt habe hat es wie weiter oben beschrieben die Zähleinheit im Formular nicht angezeigt (nur im Strukturbaum). Also wollte ich diese nochmals einfüllen. In der Dropdown-Liste konnte ich aber die Zähleinheit "blühende Pflanzen" nicht auswählen, respektive es hat sie gar nicht als Möglichkeit angezeigt (siehe Screenshot)

Das ist genau dieser Effekt. Damit du eine Einheit auswählen kannst, musst du sie aus allen Zählungen der Kontrolle entfernen.

**Comment by rebeccakurz** [comment]
okay, danke.
