### ISSUE TITLE
Zählungen von EKF sollen im Navigations-Baum gelöscht werden können

### ISSUE THREAD

**Issue by barbalex** [barbalex/apf2#338]
Siehe Meldung von @rebeccakurz  https://github.com/barbalex/apf2/issues/273#issuecomment-545393967

**Comment by barbalex** [comment]
@rebeccakurz 
Das ist "by design" bzw. von euch verursacht. Dazu muss man die Geschichte verstehen:

- Früher funktionierten EKF wie EK. Man konnte Zählungen also im Navigationsbaum neu schaffen und löschen
- Dann wurde mit viel Aufwand und sehr anspruchsvollen Regeln das neue EKF-Formular gebaut. Künftig sollten Zählungen nur noch nach ganz bestimmten Regeln erfasst werden können
- Folge davon war, dass die Zählungen in das EKF-Formular hinein verlagert wurden und im Navigationsbaum verschwanden (damit die Regeln durchgesetzt werden konnten und weil das Formular so von euch vorgegeben war). Sie können also nur noch dort neu geschaffen und gelöscht werden
- Nach Umsetzung des neuen EKF-Formulars habt ihr dann gewünscht, dass man die Zählungen doch noch im Navigationsbaum sieht, um bessere Übersicht zu haben. Das habe ich dann ergänzt. Allerdings ohne die aufwändigen Möglichkeiten, mit dem Kontext-Menu neue zu schaffen und bestehende zu löschen. Denn 1. damit könnte mann alle Regeln umgehen und 2. habe ich schon das wiederherstellen ohne Budget gemacht. Die Kontext-Menüs sind viel mehr Aufwand
- Mir scheint, ihr wollt je länger desto mehr die von euch vorgegebenen Regeln umgehen. Und dazu würdet ihr Löschen und neu schaffen im Kontext-Menu brauchen. Kombiniert mit der Tatsache, dass reine EKF-MitarbeiterInnen nur die EKF-Ansicht sehen, wo man den Navigationsbaum nicht sieht und daher die Regeln nicht umgehen kann. Was heisst, dass nur Artverantwortliche und Topos die Regeln umgehen könnten

Wenn ihr nun also wünscht, dass man die von euch vorgegebenen Regeln mit Hilfe des Kontext-Menüs im Navigationsbaum umgehen können soll, dann wäre das eine Erweiterung. Ich schätze, das kostet mich ca. 2 Stunden Arbeit.

**Comment by rebeccakurz** [comment]
Ok. Werde das mal als Wunsch für 2020 aufnehmen, dann können wir diskutieren, ob es umgesetzt werden soll. 
(Habe mich nur gefragt ob es möglich sein sollte. Aber eigentlich ist es ja schon gut, dass die Formulare so strikt sind!)

**Comment by rebeccakurz** [comment]
Momentan nicht nötig
