### ISSUE TITLE
FloraDB Export für WebGIS, für Jahresbericht 2017

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#34]
Anbei die Tabellen mit den Feldnamen. Exporte für TPop, Kontrollen, Massnahmen.
[Kontrollen_Abgleich_20170502.xlsx](https://github.com/barbalex/apf2/files/973120/Kontrollen_Abgleich_20170502.xlsx)
[Massnahmen_Abgleich_20170502.xlsx](https://github.com/barbalex/apf2/files/973119/Massnahmen_Abgleich_20170502.xlsx)
[TPops_Abgleich_20170502.xlsx](https://github.com/barbalex/apf2/files/973121/TPops_Abgleich_20170502.xlsx)

**Comment by barbalex** [comment]
Hoi Charlotte & @wunderli

Bei den Datumsfelder steht "Hier jeweils Datumsformat ändern!". Könnt ihr mir bitte ein Beispiel geben, wie das Datum von WegGisBun erwartet wird?

Vielleicht kann ich es beim Export entsprechend umwandeln.

LG, Alex

**Comment by barbalex** [comment]
Ist umgesetzt. Testet es bitte und meldet mir bitte das Datums-Format, damit ich das nachbessern kann

**Comment by csalzmann** [comment]
Das Datumsformat sollte sein: TT.MM.JJ

Vielen Dank für den prompten Export!

**Comment by barbalex** [comment]
Ist aktualisiert. Kommt per Update in einem der nächsten Nächte.
