### ISSUE TITLE
Qualitätskontrolle: Pop ursprünglich/angesiedelt, erloschen --> neue Massnahme --> neue Pop

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#340]
Wir haben in unserer Anleitung festgehalten, dass:
"Wird an einem erloschenen, ursprünglichen Wuchsort eine neue Massnahme ausgeführt, so ist für die aktuelle Massnahme unbedingt eine neue Population zu erstellen! Die erloschene, ursprüngliche Pop soll in der FloraDB weiterhin als "ursprünglich, erloschen" erkennbar bleiben."

Ebenfalls haben wir in unserer Anleitung festgehalten: 
"Sind alle angesiedelten TPops einer angesiedelten Pop erloschen und erfolgt an gleicher Stelle zu einem späteren Zeitpunkt eine neue Ansiedlung, muss für die neue Ansiedlung eine separate Population mit dem Status „angesiedelt, aktuell“ erstellt werden."

Könntest du dazu eine Qualitätskontrolle erstellen, die einen Fehler meldet, sobald in einer ursprünglich/angesiedelt, erloschenen Pop eine neue Massnahme erstellt wird?

Text z.B. wie folgt mit dem Hinweis, dass eine neue Pop erstellt werden muss. 
"Population: Status ist erloschen (ursprünglich oder angesiedelt), es gab aber eine Ansiedlung --> neue Pop erstellen"

Vielen Dank und es ist hoffentlich nicht ein so grosser Aufwand!

**Comment by barbalex** [comment]
Tja, das ist keine simple QK. Ich schätze eine bis zwei Stunden Aufwand. 

Man weiss vorher nie, was man alles merkt, wenn man die QK mit den anderen vergleicht und im Detail durch-denkt. Da hab ich mich schon mehrere Male verschätzt. Alleine sich klar werden, wie sie genau funktionieren muss kann eine bis zwei Stunden brauchen. Vor allem, wenn das mehrere Rücksprachen mit euch bedingt. Aber das weiss ich erst danach.

Daher möchte ich das nicht einfach so ungeplant zwischendurch machen. Sondern für nächstes Jahr budgetieren (und dann ev. früh im Jahr durchführen).

**Comment by rebeccakurz** [comment]
Okay, dann würden wir das gerne so in den Budget-Entwurf aufnehmen und dann früh im Jahr durchführen.

**Comment by barbalex** [comment]
> Die erloschene, ursprüngliche Pop soll in der FloraDB weiterhin als "ursprünglich, erloschen" erkennbar bleiben

Es ist jetzt einfach, dafür eine Qualitätskontrolle zu schaffen: Wir kontrollieren einfach, ob es Populationen gibt, die seit dem letzten Jahr von "ursprünglich, erloschen" auf einen anderen Status gewechselt haben. Das können wir nun mit Hilfe der Historisierung.

> Wird an einem erloschenen, ursprünglichen Wuchsort eine neue Massnahme ausgeführt, so ist für die aktuelle Massnahme unbedingt eine neue Population zu erstellen

Wenn ihr das schon im Moment der Neu-Erstellung verhindern wollt, muss ich dafür einen Trigger schreiben. Der geht so: Wenn eine neue Massnahme erstellt wird, kontrolliert die Datenbank den Status der Population. Ist er "ursprünglich, erloschen", verweigert sie die Neuschaffung der Massnahme.

Das wäre super wirksam und unmittelbar rückmeldend. ABER:
- der Trigger ist sehr aufwändig und verlangsamt jede Neuschaffung einer Massnahme
- weil die Datenbank kryptische Fehlermeldungen meldet, muss ich diesen Fall App-Seitig speziell abfangen und dem Benutzer melden. Das ist komplex und aufwändig

Darum würde ich empfehlen, nur die Qualitätskontrolle zu schaffen.

**Comment by barbalex** [comment]
> Sind alle angesiedelten TPops einer angesiedelten Pop erloschen und erfolgt an gleicher Stelle zu einem späteren Zeitpunkt eine neue Ansiedlung, muss für die neue Ansiedlung eine separate Population mit dem Status „angesiedelt, aktuell“ erstellt werden.

Das ist doch ziemlich dasselbe, wie:

"Wird an einer erloschenen, angesiedelten Population eine neue Ansiedlung ausgeführt, so ist für die aktuelle Massnahme unbedingt eine neue Population zu erstellen"

Also kann ich auch hier auf Ebene Population alle diejenigen in einer Qualitätskontrolle auflisten, welche im  Vorjahr erloschen waren aber jetzt einen anderen Status bekommen haben. Richtig?

Somit reicht wohl für beide Fälle eine einzige Qualitätskontrolle: "**Ehemals erloschene Population, deren Status verändert wurde**".

Gilt dieselbe Regel auch für Teilpopulationen? Dann könnte ich eine zusätzliche Qualitätskontrolle dafür bauen.

Und noch eine letzte Frage: Sollte die Qualitätskontrolle nur Wechsel vom letzten zum aktuellen Jahr auflisten oder alle, seit historisiert wird? Oder wollt ihr ev. für letzteres eine Liste von mir erhalten?

**Comment by barbalex** [comment]
@rebeccakurz @kmarti 
Heisst die Kombination von

> Wird an einem erloschenen, ursprünglichen Wuchsort eine neue Massnahme ausgeführt, so ist für die aktuelle Massnahme unbedingt eine neue Population zu erstellen

und

> Sind alle angesiedelten TPops einer angesiedelten Pop erloschen und erfolgt an gleicher Stelle zu einem späteren Zeitpunkt eine neue Ansiedlung, muss für die neue Ansiedlung eine separate Population mit dem Status „angesiedelt, aktuell“ erstellt werden.

nicht einfach:

**Der Status einmal erloschener Populationen wird nie mehr geändert**

Es wäre am einfachsten und verständlichsten, wenn ich die Qualitätskontrolle entsprechend nennen könnte: **Der Status einer zuvor erloschenen Population wurde verändert**.

Oder wollt ihr lieber, dass ich zwei unabhängige Qualitätskontrollen baue, welche sich an dem von euch in der Anleitung verwendeten Text ausrichten? Das würde allerdings viel komplizierter, denn der Status einer Population kann theoretisch auch ohne Ansiedlung verändert werden. Und das Prüfen nach Ansiedlungen ist aufwändig.

**Comment by kmarti** [comment]
Bei einer ursprünglich erloschenen Population gibt es zwei Fälle, dass diese wieder erweckt werden könnte:
1. Bei einer Begehung wird festgestellt, dass es nun doch wieder Pflanzen gibt. Das wäre das Resultat einer Feldkontrolle. In diesem Fall sollte der Status von "ursprünglich erloschen" wieder auf "ursprünglich aktuell" gestellt werden.
2. Bei einer ursprünglich erloschenen Population wird eine Ansiedlung gemacht. In diesem Fall sollte zwingend eine neue Population eingegeben werden (angesiedelt aktuell oder Ansaatversuch). Der Status der ursprünglich erloschenen Population wird nicht verändert.

Die Aussage "Der Status einmal erloschener Populationen wird nie mehr geändert" ist also falsch.

Bei den angesiedelten und erloschenen Populationen gibt es noch folgendes zu bedenken:
Wir haben in der Anleitung vorgegeben, dass auch in dem Fall, wenn bei einer angesiedelten erloschenen Population eine Wiederansiedlung gemacht wird, eine neue Population in die FloraDB eingegeben werden muss. Der Grund dafür war, dass dann die Entwicklung und die Geschichte dieser Populationen besser nachverfolgt werden kann. Es ist mir aber bewusst, dass dies sehr häufig nicht gemacht wurde. Ich denke, dass es ganz sicher keinen Sinn macht, dies rückwirkend anzupassen. Ich bin mir sogar am überlegen, ob wir diese Regel für die angesiedelten Populationen beibehalten wollen. Wenn ich mir jetzt die schönen Grafiken anschauen mit den Populationsentwicklungen (Pflanzen total nach Populationen), dann sieht man auch wenn eine angesiedelte Population erlischt und dann (nach einer Wiederansiedlung) auch wieder zunimmt. Bei einer Aufteilung der alten und neuen Population, wäre das nicht so schön ersichtlich. Wie gesagt, bin ich mir aber noch nicht sicher, was besser ist.

Die Qualitätskontrolle "Der Status einer zuvor erloschenen Population wurde verändert" wäre aber so oder so eine gute Lösung. 
Es wäre ersichtlich, wo in einer ursprünglich erloschene Populationen wieder Pflanzen entdeckt wurden. Und es könnten die Fehler nachverfolgt werden, wenn fälschlicherweise ursprünglich erloschene Populationen nach Ansiedlungen auf aktuell gesetzt wird. Ob dies bei angesiedelten erloschenen Populationen auch ein Fehler ist, müssen wir uns nochmals überlegen. Je nachdem ist die Qualitätskontrolle nur auf die ursprünglich erloschenen Populationen oder auf alle erloschenen Populationen anzuwenden.

**Comment by barbalex** [comment]
> Es wäre ersichtlich, wo in einer ursprünglich erloschene Populationen wieder Pflanzen entdeckt wurden

Diese Information würde ich eher Auswertung nennen als Qualitätskontrolle.
Der Sinn der Qualitätskontrollen, ist, Fehler zu finden. Sie funktionieren am besten, wenn die Liste eigentlich gar nichts enthalten sollte. Und das in aller Regel auch tut. Es ist eher ungünstig, wenn Fälle aufgelistet sind, welche keine Korrektur erfordern.

Ich denke daher, dass es für die **Qualitätskontrolle** doch sinnvoll ist, nur diejenigen Fälle zu melden, bei denen seit der Änderung des Status (inklusive dem Jahr zuvor?) eine Ansiedlung erfolgt ist. Wenn wir das zuverlässig greifen können.

Und für die andere Information eine Auswertung zu schaffen, wenn das erwünscht ist.

Bloss: Was genau muss passiert sein und wann?

1. Was

Rebecca hat geschrieben:

> Wird an einem erloschenen, ursprünglichen Wuchsort eine neue Massnahme ausgeführt

Sind nicht eher Ansiedlungen gemeint? (Anpflanzung oder Ansaat)

2. Wann

Wie ist das zeitliche Verhältnis von Massnahme und Status-Änderung? Wird der Status geändert, bevor angesiedelt wird? Ich vermute eher, dass angesiedelt wird und der Status erst geändert wird, wenn die Ansiedlung erfolgreich war. Das heisst: häufig frühestens im Jahr nach der Ansiedlung.

Die Qualitätskontrolle müsste also bei Statusänderungen innerhalb einer gewisse Zeitspanne kontrollieren, ob Ansiedlungen erfolgt sind (z.B. innerhalb der letzten 3 Jahre?). Oder ob es innerhalb dieser Frist einen positiven Massnahmenbericht gibt.

Was meinst du?

**Comment by kmarti** [comment]
Wir haben nun beschlossen, dass wir die Anleitung ändern, so dass der Status von angesiedelten erloschenen Populationen nach einer Anpflanzung wieder in eine angesiedelte aktuelle Population verändert werden darf (und nach einer Ansaat in einen Ansaatversuch), da dies häufig auch so gehandhabt wird. Wir passen also in diesem Fall die Anleitung der Praxis an.
Bei den ursprünglich erloschenen Populationen gilt aber weiterhin, dass diese nur in eine ursprünglich aktuelle Population umgewandelt werden darf, wenn wieder ursprüngliche Pflanzen gefunden wurden.

Wird bei einer ursprünglich erloschenen Population eine Anpflanzung/Ansaat vorgenommen, dann ist eine neue Population in der APFloraDB anzulegen. In der Regel wird zuerst die Massnahme ausgeführt und danach erfolgt die Eingabe in die DB und eine allfällige Statusänderung. D.h. mit einer Qualitätskontrolle müsste überprüft werden, ob bei einer im Vorjahr ursprünglich erloschenen Population im aktuellen Jahr eine Statusänderung erfolgt ist (ursprünglich aktuell, angesiedelt aktuell, Ansaatversuch) und eine Ansiedlungsmassnahme (Anpflanzung oder Ansaat). Das wäre dann eine Fehler.

**Comment by barbalex** [comment]
Ist in Version 1.50.0 implementiert.

Das einzige Resultat, das momentan gefunden wird, ist aus einem früheren Jahr:

ap | pop_nr | jahr
-- | -- | --
Typha shuttleworthii W. D. J. Koch &   Sond. (Shuttleworths Rohrkolben) | 6 | 2015

Du kannst das nachvollziehen, indem du bei diesem AP für das Berichtjahr 2015 die QK durchführst.


Übrigens: Es gibt diesen Fall hier:

ap | pop_nr | jahr
-- | -- | --
Thesium rostratum Mert. & W. D. J.   Koch (Schnabelfrüchtiger Bergflachs) | 45 | 2016

Dieser AP war im Jahr 2015 ursprünglich aktuell, angesiedelt aktuell oder Ansaatversuch. 2016 dann aber, nach einer Ansiedlung, erloschen.

(ist mir nur aufgefallen, weil ich zuerst die Kriterien vertauscht hatte)
