### ISSUE TITLE
Karte ladet nicht

### ISSUE THREAD

**Issue by praktikatopos** [barbalex/apf2#341]
Die Karte ladet bei mir nicht. Habe verschiedene Arten und Standorte ausprobiert. Ebenso hat es Rebecca auf ihrem Mac probiert und es hat auch nicht funktioniert.

**Comment by barbalex** [comment]
Sorry, bin unterwegs. Prüfe heute Abend

**Comment by barbalex** [comment]
Das war ein super blöder Unfall beim Unterhalt. Ist in v1.19.40 repariert
