### ISSUE TITLE
Karte Pop und Tpop werden nicht angezeigt

### ISSUE THREAD

**Issue by praktikatopos** [barbalex/apf2#342]
Wollte die Position einer Tpop auf der Karte anschauen: Scabiosa canescens, Pop 13, Weiach. Entsprechende Pop/Tpop wird auf der Karte jedoch nicht angezeigt. Mit klicken auf "auf aktive Population/Teilpopulation zoomen" wird zwar nach Weiach gezoomt, doch es erscheinen keine Blümchen auf der Karte (siehe Bild). Beim rauszoomen auf der Karte werden andere Pop auf der Karte angezeigt, jedoch nicht Pop Nr. 13. Habe die Karte auch nochmals neu geladen, keine Veränderung. Was habe ich vorher gemacht: Ich habe lediglich die Art und Pop-Nr. gefiltert und anschliessend wollte ich sie auf der Karte anzeigen lassen. Ich habe nichts neu erstellt (Feldkontrolle/Massnahme etc.), sondern lediglich gefiltert und die Karte geöffnet.

![Bildschirmfoto 2019-11-18 um 08 20 05](https://user-images.githubusercontent.com/42208152/69032281-675fad00-09dc-11ea-84c6-713ad640ba0c.png)

**Comment by barbalex** [comment]
Der Grund ist: Die Pop kat keine Koordinaten.

Die Abfrage berücksichtigt die Filterung auf Ebene Pop und Tpop. Damit sich Filterung auf Ebene Pop auf die Ebene Tpop auswirkt - das müsste eigentlich ein Feature sein. Und zur Ebene Pop gehört eben auch, dass Koordinaten existieren - ansonsten könnte die Pop nicht in der Karte dargestellt werden.

Die in diesem Fall spürbare (Neben-)Wirkung ist also, dass die TPop nicht erscheint, weil die Pop keine Koordinaten hat.

Es gibt eine Qualitätskontrolle, die aus diesem Grund diese Population auflistet.

Ich buch das mal als Fehler in der Daten-Erfassung ab und schliesse daher diesen Issue. Falls ihr meint, dass es Populationen ohne Koordinaten geben können sollte, müsstest du einen neuen Issue öffnen.
