### ISSUE TITLE
Arten filtern ladet erst nach zweimaligem Eintippen

### ISSUE THREAD

**Issue by praktikatopos** [barbalex/apf2#343]
Wenn ich nach einer Art filtere, kommt es ab und zu vor (ca. 50% der Zeit), dass es nach eintippen der Art anzeigt "laden". Lange passiert nichts. Wenn ich dann erneut in das Filter-Feld klicke und einen Buchstaben verändere (z.b. 1 Buchstabe anfügen/löschen), auf enter klicke, dann erscheint das Ergebnis sofort. Bsp. 1. Abfrage "Pulsatilla vul" + enter -> es zeigt an "laden", aber nichts passiert, 2. Abfrage "Pulsatilla vu" + enter -> Ergebnis erscheint sofort. Passiert auch, wenn ich zuerst nach "Pulsatilla" suche, und beim zweiten Mal noch ein Leerzeichen anfüge für zwischen Gattungsname und Artname -> 1. Abfrage "Pulsatilla", 2. Abfrage "Pulsatilla "

**Comment by barbalex** [comment]
Ich nehme an, du sprichst von der Filterung im Strukturbaum und nicht vom Formular-basierten Filter. Richtig?

**Comment by praktikatopos** [comment]
Korrekt, es betrifft das Filtern im Strukturbaum

**Comment by barbalex** [comment]
Ich weiss nicht, ob es das Problem löst, aber vielleicht schon:

@csalzmann @rebeccakurz 
Dass die Filterung erst nach Verlassen des Feldes bzw. nach Drücken der Enter-Taste ausgelöst wird, haben wir damals eingeführt, als wir grosse Probleme mit der Performance hatten. 

Da das nicht mehr der Fall ist, habe ich jetzt in v1.19.46 die Filterung im Navigationsbaum wieder so geändert, dass sie 0.3 Sekunden nach der letzten Eingabe automatisch erfolgt.

Die 0.3 Sekunden sind bewusst, damit nicht während des Tippens Dutzende von Abfragen ausgelöst werden, was potentiell wieder Leistungs-Probleme provozieren könnte.

Uhm. Habe jetzt gesehen, dass Filter löschen nicht mehr richtig klappt. Muss das später reparieren...

**Comment by praktikatopos** [comment]
Das Problem dass ich beschrieben habe hängt nicht mit dem Drücken von "enter" zusammen. Beim 1. Mal eintippen Art + enter -> es zeigt an "laden", aber nichts passiert. erst beim 2. Mal eintippen + enter kommt ein Ergebnis. Bei beiden Malen wurde die Enter-Taste gedrückt, doch erst beim zweiten mal wurde ein Ergebnis gezeigt.

Wie du gesagt hast, hast du nun etwas geändert, das scheint aber nicht zu funktioniere + ich denke nicht, dass man das ändern sollte mit dem Drücken der Enter-Taste. Für mich macht es Sinn, den Filter erst mit Drücken der Enter-Taste zu "aktivieren". Insbesondere wenn du das explizit eingeführt hast, weil ihr sonst Probleme mit der Performance hattet. Ich hoffe du kannst den vorherigen Zustand wieder herstellen. Momentan sieht es bei mir beim Filtern so aus: Wenn ich eine Art filtere, dann wird die eingetippte Art auch beim Populations-Filter eingefügt (was natürlich zu keinem Suchergebnis führt). Löscht man die Eingabe im Populations-Filter, so wird automatisch auch die Eingabe im Art-Filter gelöscht!

**Comment by barbalex** [comment]
In v1.19.47 funktioniert nun das Löschen der Filter wieder.

> Insbesondere wenn du das explizit eingeführt hast, weil ihr sonst Probleme mit der Performance hattet

Das sollte Geschichte sein. Die Arbeit wurde früher in der Anwendung gemacht. Dann habe ich sie via Abfrage an die Datenbank ausgelagert (weil die dafür verwendete Software das nach einem Update ermöglichte). Seither ist die Leistung viel besser. Falls sie wieder leiden würde, könnte ich das rückgängig machen.

> Wenn ich eine Art filtere, dann wird die eingetippte Art auch beim Populations-Filter eingefügt (was natürlich zu keinem Suchergebnis führt). Löscht man die Eingabe im Populations-Filter, so wird automatisch auch die Eingabe im Art-Filter gelöscht!

Sorry, das verstehe ich nicht. Kannst du mir das bitte nochmals erklären? Ev. war das Teil des Fehlers in der letzten Version. Passiert das immer noch in v1.19.47?

**Comment by praktikatopos** [comment]
Das Problem ist nicht mehr aufgetreten. Melde mich erneut, wenn es wieder passiert

**Comment by barbalex** [comment]
Ich schliess mal den issue
