### ISSUE TITLE
Blümchen erscheint erst nach Neu-Laden

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#344]
Wenn ich eine neue Population und eine dazugehörige Teilpopulation erstelle, dann in der TPop die Koordinaten eintrage und diese dann in die Population kopiere, erscheint das Blümchen auf der Karte erst, wenn ich die ganze Seite neu lade. Das ist auch der Fall, wenn ich die TPop mit Klicken auf der Karte verorte (die Koordinaten werden zwar eingetragen, aber es erscheint kein Blümchen). 
Dasselbe auch bei Simone

**Comment by barbalex** [comment]
Meinst du das Blümchen für die TPop oder für die Pop?

**Comment by barbalex** [comment]
Danke für den genauen Beschrieb. Es gab zwei Probleme:
- Das Symbol für eine TPop wurde nur angezeigt, wenn deren Pop Koordinaten besass. Ich hab das geändert und hoffe, dass das nicht ungewolltes Verhalten erzeugt
- Beim Kopieren der Koordinaten von der Tpop in die Pop wurden die Daten des Pop-Layers in der Karte nicht aktualisiert

Sollte in v1.19.48 korrigiert sein
