### ISSUE TITLE
Kopieren von Tpop -> Koordinaten werden nicht kopiert

### ISSUE THREAD

**Issue by praktikatopos** [barbalex/apf2#345]
Situation: Neue Pop erstellt + neue Tpop erstellt. Nun möchte ich die Tpop kopieren. Dabei werden jedoch die Koordinaten der Tpop nicht mitkopiert. Die Kopie hat dann keine Koordinaten mehr und man muss sie nochmals manuel eingeben

**Comment by barbalex** [comment]
Danke für die Meldung. Wird in ein paar Minuten in v1.21.2 behoben sein.
Der gleiche Fehler bestand bei den Pop.
