### ISSUE TITLE
Automatisiertes Erzeugen von EK-Plänen in TPop ohne EK-Frequenz

### ISSUE THREAD

**Issue by barbalex** [barbalex/apf2#346]
Auszug aus email von Alex vom 30.11.2019:

Nachdem ich mit der Umsetzung begonnen habe, bin ich zum Schluss gelangt: Vollautomatische Erstellung von EK-Plänen ist VIEL anspruchsvoller als die halb-automatische, die implementiert ist.

Bei der halb-automatischen wählt die Benutzerin die EK-Frequenz. Bei der voll-automatischen muss das die Software entscheiden.

Das heisst:
1. Alle für diesen Entscheid notwendigen Kriterien müssen existieren und abgefragt werden können
2. Diese Kriterien müssen in 100% der Fälle anwendbar sein
3. Diese Kriterien müssen also erfasst werden. Das wiederum sollte möglich sein und die Benutzerinnen nicht überfordern

Das Problem liegt nun bei den EK-Frequenzen GA, GB, GC und GD.
Der einzige Unterschied zwischen ihnen, der für die Wahl der Frequenz bedeutend ist, ist die "Gefährdung" der Pop und/oder (?) TPop.
GA zum Beispiel ist definiert als: "Pop und Tpop ursprünglich aktuell, stark gefährdet (< 20 Ind.)"
Das heisst, der Algorithmus sucht die letzte Kontrolle mit der ziel-relevanten Einheit und wertet deren Anzahl aus.

Hier gibt es ein paar Unklarheiten:
1. Beziehen sich die "20 Ind." auf die TPop oder die Pop? (beim Setzen der EK-Frequenzen wurde von der TPop ausgegangen - wenn das so korrekt ist, ist dieses Problem gelöst)
2. Aktuell gibt es 26 unterschiedliche Zähleinheiten. Alle könnten prinzipiell als ziel-relevant erklärt werden. Die meisten können aber nicht einmal von einem Menschen in Individuen übersetzt werden. Geschweige denn vom Algorithmus. Wie soll der Algorithmus nun rechnen? Beim automatischen Setzen haben die Abfragen einfach die Anzahl der ziel-relevanten Einheit verwendet. Das kann aber sehr einfach falsch sein. Vielleicht war es jetzt noch vertretbar, weil ihr informiert wart, mit diesem Wissen die ziel-relevanten Einheiten gesetzt habt und hoffentlich die gewählten ziel-relevanten Einheiten Individuen entsprechen. Aber prinzipiell kann bei jedem AP jederzeit die ziel-relevante Zähleinheit verändert werden zu einer Einheit, die nicht Individuen entspricht. Ich bin garantiert sicher, dass viele Benutzer sich dieses Zusammenhangs nicht bewusst sein werden und daher das voll-automatische Setzen von EK-Frequenzen viel zu oft zu oft unbewussten Problemen führen wird.
Im Gegensatz dazu ist es zwar auch für einen Menschen in den weniger eindeutigen Situationen nicht ganz einfach, die Gefährdung zu beurteilen. Aber er weiss wenigstens, was er macht.
3. Zusätzlich kommt noch das Problem, dass Gefährdung vermutlich nicht in 100% der aktuellen oder künftigen Fälle sinnvoll in Anzahl Individuen übersetzt werden kann. Beispielsweise dürfte die zeitliche Entwicklung eine Rolle spielen. Oder die Biologie der Art. Oder Vorgänge auf der Fläche (z.B. periodische Überschwemmungen).
4. Es könnten jederzeit neue EK-Frequenzen erfasst werden, die in irgend einer Weise von den impliziten Rahmenbedingungen abweichen und damit das automatisierte Setzen zum Fall bringen

Das Ganze würde also nur bewusst und algorithmisch korrekt ablaufen, wenn:
- Die Benutzerinnen der Pop oder TPop eine Gefährdung zuweisen (in Pop/TPop oder vermutlich besser in den Berichten)
- Die EK-Frequenz eine bestimmte Bedrohung voraussetzen kann
- Die automatische Generierung danach in den Fällen, in denen die EK-Frequenz eine Bedrohung voraussetzt, nur erfolgt, wenn der TPop eine Bedrohung zugewiesen wurde

Die Bedrohung von TPop könnte wiederum durch Qualitätskontrollen geprüft werden, welche dann etwas differenzierter erfolgen könnten, weil sie gezielt diese Frage angehen. Und weil sie von Menschen beurteilt werden.

Konkret müsste folgendes angepasst werden:
- Neue Tabelle tpop_gefaehrdung_werte: hier werden die Gefährdungs-Stufen erfasst: stark, mittel, wenig, erloschen?
- Neues Feld ekfrequenz.gefaehrdung: hier wählt man die zutreffende Gefährdungsstufe, wenn die EK-Frequenz von der Gefährdung abhängt. Und erfasst dann (wie bei GA - GD) für jede Gefährdungsstufe eine EK-Frequenz
- Neue Felder tpop.gefaehrdung oder popber.gefaehrdung bzw. tpopber.gefaehrdung: damit die Gefährdung beurteilt und erfasst wird
- Der Algorithmus um automatisiert Kontrollen zu planen berücksichtigt diese Daten

Aber letztlich ist das wiederum sehr viel Arbeit. Und es liegt an euch, zu beurteilen, ob das besser wäre, als einfach die entsprechende EK-Frequenz zu wählen und dabei diesen Entscheid zu treffen.

Um zu verhindern, dass Zähleinheiten als ziel-relevant gewählt werden, die nicht in Individuen übersetzt werden könnten, könnte bei den Zähleinheiten ein Felder ergänzt werden, dass heisst: "entspricht_individuen". Dann könnte man erzwingen, dass nur Zähleinheiten mit dieser Eigenschaft als ziel-relevant erklärt werden könnten. Das löst nicht alle oben genannten Probleme, aber ein wichtiges.

Beurteilung aus meiner Sicht:

Status quo:
- Gefahr, dass Benutzer sich nicht bewusst sind, was alles gegeben sein muss. Daher schwierig, die Ergebnisse der automatischen Zuordnung nachzuvollziehen
- Gefahr, dass ungeeignete ziel-relevante Zähleinheiten gewählt werden, welche nicht Individuen entsprechen
- Gefahr, dass neue EK-Frequenzen erzeugt werden, welche ähnlich wie GA bis GD von etwas ausgehen, dass der Algorithmus nicht aus den Daten lesen kann und daher zu Fehlern führen
- Gefahr, dass in einzelnen AP's in den EK-Frequenzen GA - GD im Text die Kriterien für die Gefährdung verändert werden. Und das vom Algorithmus nicht berücksichtigt wird
- Wegen letzterem müssten zusätzliche Felder ergänzt werden, um die minimale und maximale Anzahl Individuen zu erfassen, für die diese EK-Frequenz gilt

Wenn die Gefährdung explizit erfasst wird:
- Sehr bewusste Wahl des entscheidenden Kriteriums
- Alle Fälle, welche die Gefährdung nicht voraussetzen (nicht GA bis GD) können immer automatisch gesetzt werden
- Die Fälle GA bis GD werden nachvollziehbar und bewusst gesetzt. Oder (wenn die Gefährdung nicht beurteilt wurde) gar nicht

Vorteile EK-Frequenz manuell wählen und dabei die Gefährdung zu berücksichtigen:
- Einfach
- Keine weitere Programmierung nötig
- Die Gefährdung wird dort beurteilt, wo sie zur Geltung kommt
- Sind sich die Benutzer genügend bewusst, dass sie bei der Wahl der EK-Frequenz bei GA bis GD die Gefährdung beurteilen müssen?
- Viel Arbeit für die Benutzerinnen
- Man kann sich Zeit lassen, Erfahrungen sammeln und dann über Anpassungen entscheiden, wenn klar ist, wie es langfristig sinnvoll ist

Meine Schlussfolgerungen:
1. Für dieses eine mal kann ich die EK-Planung automatisiert setzen. Ich weiss nicht, wie viele Fälle dadurch erzeugt werden, die wenig oder keinen Sinn machen. Aber ich verlasse mich auf euch, dass sinnvolle ziel-relevante Zähleinheiten gewählt wurden und EK-Frequenzen nicht verändert wurden
2. Als jährlich zu wiederholende Massnahme ist das sehr gefährlich. Ob die gewünschte Qualität der Beurteilung erreicht wird, scheint mir fragwürdig. Ausserdem drohen dauernde Anpassungen der Anwendung, weil das Prozedere im Grundsatz problematisch ist. Diese Anpassungen sind aufwändig. Und für niemanden befriedigend
3. Wenn wir die automatische Zuweisung nachvollziehbar und zuverlässig gestalten wollen, bedingt es, dass die Gefährdung explizit erfasst wird. Das System ist dann aber immer noch komplex, könnte dauernde Weiter-Entwicklungen erfordern und BenutzerInnen überfordern. Aber im Grunde genommen ist jede Lösung komplex und diese entspricht wohl den fachlichen Ansprüchen am besten
4. Alternativ müssten wir die App so anpassen, dass nur Zähleinheiten, die Individuen entsprechen, als ziel-relevant erklärt werden können. Und dass in EK-Frequenzen für Fälle, in denen Anzahlen in der letzten Kontrolle bedeutend sind, eine minimale und maximale Anzahl erfasst wird. Zum Beispiel für GA: 1 - 19. Auch das ist komplex und löst in meinen Augen das grundlegende Problem aus fachlicher Sicht weniger befriedigend als Variante 3
5. Varianten 3 und 4 sind aufwändig und wären im nächsten Budget umzusetzen

Meine Fragen an euch:
1. Wollt ihr, dass ich die Start-Jahre und EK-Pläne dieses mal trotz allem automatisch zuordne? (ich nehme an, ja)
2. Wie seht ihr das in Zukunft?

**Comment by barbalex** [comment]
Antwort von @rebeccakurz am 2.12.2019:

Zu deinen Fragen an uns:

1. Ja, sehr gerne!
2. Wir würden das dann gerne mit dir besprechen und die beste Lösung suchen. Du hast da sicher schone ein paar gute Lösungsansätze. Wir könnten uns z.B. auch vorstellen, dass nur bei neu gegründeten TPops in Zukunft automatisch alles gesetzt wird und wenn bei den ursprünglichen eine Wechsel der EK-Frequenz nötig ist (aufgrund der Gefährdung), dies dann von Hand gemacht werden kann/muss (falls diese Unterscheidung möglich ist).

**Comment by barbalex** [comment]
@rebeccakurz 
In Wunschliste_APFlora_DB_20200204.xlsx steht:

EK-Planung | RK/KM:   Automatisiertes Erzeugen von EK-Plänen in Tpop ohne EK-Frequenz --> nich   1-2 Jahre halbautomatisch (mit Kontrolle)
-- | --

Für mich ist das unklar. Wie bezieht sich das auf das oben dargelegte? Z.B.: Welche Variante (2, 3 oder 4?) ist nun gemeint?

**Comment by rebeccakurz** [comment]
Wir haben uns an der Besprechung, also als du bei uns im Büro warst, darauf geeinigt, dass das Erzeugen von EK-Plänen in TPop ohne EK-Frequenz noch 1-2 Jahre halbautomatisch gemacht werden soll. Also so wie dieses Mal und dass wir das dann auch noch kontrollieren. Erst wenn es ohne Probleme funktioniert, können wir wieder darüber reden, ob es ganz automatisiert werden soll.

**Comment by rebeccakurz** [comment]
Also wir haben bei unserer Besprechung beschlossen, dass wir das Erzeugen von EK-Plänen in TPop ohne EK-Frequenz noch ein bis zwei Jahre lang so machen wollen, wie wir das im Dezember gemacht haben. Also das du die Zuteilung machst und wir es dann aber noch kontrollieren, darum halbautomatisch.

**Comment by barbalex** [comment]
Danke und sorry für meine Vergesslichkeit 🙄

**Comment by barbalex** [comment]
@rebeccakurz @kmarti 

Bisher hatte ich bei diesem Vorgang die EK-Pläne auf eine abschliessende Liste von AP-ID's beschränkt. Das hatte vermutlich einen Zusammenhang mit der ursprünglichen Implementierung, ist mir aber nicht mehr bekannt.

Es wäre ev. gefährlich, diese abschliessende Liste weiter zu verwenden: Kann ja sein, dass neue Arten dazu kommen.

Wie wollt ihr, dass ich auswähle, in welchen AP's EK-Pläne in TPops ohne EK-Frequenz eingefügt werden?
- Soll ich diese Liste weiter verwenden?
- Sind das einfach alle AP's bzw. Arten, bei denen ein AP: "vorgesehen", "in Bearbeitung" oder "erstellt" ist?
- Gibt es zusätzliche Arten, bei denen die EK geplant wird?
- Soll ich das in allen AP's machen, in denen irgendwo schon mindestens eine EK-Frequenz gesetzt wurde?

Hier die Liste:

- Aldrovanda vesiculosa L. (Aldrovande)
- Allium angulosum L. (Kantiger Lauch)
- Anagallis minima (L.) E. H. L. Krause (Kleinling)
- Aristolochia clematitis L. (Gewöhnliche Osterluzei)
- Blackstonia acuminata (W. D. J. Koch & Ziz) Domin (Spätblühender Bitterling)
- Campanula cervicaria L. (Borstige Glockenblume)
- Cardamine dentata Schult. (Sumpf-Schaumkraut)
- Carex chordorrhiza L. f. (Fadenwurzelige Segge)
- Carex hartmanii Cajander (Hartmans Segge)
- Carex heleonastes L. f. (Torf-Segge)
- Daphne cneorum L. (Flaumiger Seidelbast, Fluhröschen)
- Eriophorum gracile Roth (Schlankes Wollgras)
- Filipendula vulgaris Moench (Knollige Spierstaude)
- Gagea pratensis (Pers.) Dumort. (Wiesen-Gelbstern)
- Gagea villosa (M. Bieb.) Sweet (Acker-Gelbstern)
- Gentiana cruciata L. (Kreuzblättriger Enzian)
- Gladiolus communis L. (Garten-Gladiole)
- Gladiolus palustris Gaudin (Sumpf-Gladiole)
- Gratiola officinalis L. (Gnadenkraut)
- Himantoglossum hircinum (L.) Spreng. (Riemenzunge)
- Hypochaeris maculata L. (Geflecktes Ferkelkraut)
- Inula helvetica Weber (Schweizerischer Alant)
- Inula hirta L. (Rauher Alant)
- Liparis loeselii (L.) Rich. (Zwiebelorchis)
- Littorella uniflora (L.) Asch. (Strandling)
- Nuphar pumila (Timm) DC. (Kleine Teichrose)
- Oenanthe lachenalii C. C. Gmel. (Lachenals Rebendolde)
- Ophrys araneola Rchb. (Spinnen-Ragwurz)
- Orchis palustris Jacq. (Sumpf-Orchis)
- Pleurospermum austriacum (L.) Hoffm. (Rippensame)
- Potamogeton coloratus Hornem. (Gefärbtes Laichkraut)
- Potentilla alba L. (Weisses Fingerkraut)
- Potentilla inclinata Vill. (Graues Fingerkraut)
- Potentilla leucopolitana P. J. Müll. (Weissenburger Fingerkraut)
- Potentilla praecox F. W. Schultz (Frühzeitiges Fingerkraut)
- Pulsatilla vulgaris Mill. (Gewöhnliche Küchenschelle)
- Rosa gallica L. (Essig-Rose)
- Sagittaria sagittifolia L. (Gewöhnliches Pfeilkraut)
- Saxifraga granulata L. (Knöllchen-Steinbrech)
- Scorzonera humilis L. (Kleine Schwarzwurzel)
- Sedum rubens L. (Rötlicher Mauerpfeffer)
- Seseli libanotis (L.) W. D. J. Koch (Hirschheil)
- Spiranthes spiralis (L.) Chevall. (Herbst-Wendelähre)
- Teucrium scordium L. (Lauch-Gamander)
- Thalictrum simplex L. subsp. galioides (Pers.) Korsh.
- Thesium rostratum Mert. & W. D. J. Koch (Schnabelfrüchtiger Bergflachs)
- Trifolium ochroleucon Huds. (Gelblicher Klee)
- Tulipa sylvestris L. s.str. (Weinberg-Tulpe)
- Typha minima Hoppe (Kleiner Rohrkolben)
- Typha shuttleworthii W. D. J. Koch & Sond. (Shuttleworths Rohrkolben)
- Viola elatior Fr. (Hohes Veilchen)
- Viola persicifolia Schreb. (Moor-Veilchen)
- Viola pumila Chaix (Niedriges Veilchen)

**Comment by kmarti** [comment]
1. Es werden auf jeden Fall neue Arten dazu kommen, d.h. die Liste darf nicht abschliessend sein. Also diese Liste nicht mehr verwenden.
 2. Es sind dies alles Arten, bei welchen ein AP "vorgesehen", "in Bearbeitung" und "erstellt" ist.
 3. Es sind mir keine zusätzlichen Arten bekannt, die eine EK-Planung brauchen.
 4. Ja, bitte für alle diese AP-Arten mit mind. einer EK-Frequenz.
