### ISSUE TITLE
AP-Berichte Textfelder

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#347]
Wäre es möglich in den Textfeldern der AP-Berichte einzurichten, dass man mit der Return-Taste eine neue Zeile beginnen kann? Jetzt kommt man, wenn man die Return-Taste drückt, nur zum nächsten Feld. Das würde die Textfelder sehr viel übersichtlicher machen, v. a. da es z.T. relativ viel Text ist.

**Comment by barbalex** [comment]
Ja: Möglich ist fast alles.

Grundsätzlich können beliebige Rohdaten in ein Text-Feld der Datenbank gepackt werden. Leider verwenden unterschiedliche Betriebssysteme in Rohdaten unterschiedliche Zeichen, um Umbrüche darzustellen. Daher funktioniert es grundsätzlich nicht ohne weitere Hilfsmittel.

Das Feld wird für die Darstellung im Bericht mit HTML präsentiert. Und in HTML braucht man XML-Formatierungs-Zeichen, um zu formatieren. Für den Zeilenumbruch bräuchte es also z.B. `<br/>`.

Weil XML-Formatierung nicht jeder im Blut liegt, müsste das Feld ähnlich einer einfachen Version von Word Funktionen anbieten, um Formatieren zu können. Ausserdem: In HTML ist Text auch nicht einfach Text. Bei der Erfassung von Text müsste also ein geeignetes Werkzeug die ganze Eingabe interpretieren und in geeigneter Art speichern, nicht nur die Zeilen-Umbrüche. Solche Werkzeuge verwenden in der Regel eigene Formate (binär), um die Daten abzuspeichern. Das macht den Umgang mit den Daten viel komplexer. Und die Daten können nicht mehr ausgewertet werden.

Damit das `<br/>` als Formatierung erkannt wird, muss das Feld in der Präsentation dann ganz anders gebaut werden, als ein nur Daten enthaltendes Feld: Sein Inhalt muss als HTML übergeben werden, nicht als Text. Und es braucht ein Werkzeug, das aus den Daten das korrekte HTML baut.

Wir bräuchten also zwei Werkzeuge: eines für die Erfassung und Konvertierung in ein speicherbares Format. Und eines für die Präsentation.

Bis vor kurzem war das extrem aufwändig. Ich habe so was gebaut. Es macht in der traditionellen Form die Anwendung VIEL komplexer, technisch viel weniger zuverlässig und viel weniger schnell. So was möchte ich nicht in apflora einbauen.

Neuerdings gibt es Werkzeuge, welche mit Markdown arbeiten. Markdown ist ein reines Text-Format, dass daher auch roh in ein Textfeld einer Datenbank gespeichert werden kann und sogar noch auswertbar bleibt.

Markdown ist nicht so mächtig wie HTML oder Word. Aber du kennst es: Github Issues schreibt man nämlich mit Markdown. Du merkst nichts davon, weil Github ein paar Formatierungs-Schaltflächen anbietet und Zeilenumbrüche direkt akzeptiert.

Ich müsste einmal die verschiedenen Optionen beurteilen und testen um diese Möglichkeit in apflora anbieten zu können. Das wäre eine Erweiterung, die budgetiert werden muss.

**Comment by barbalex** [comment]
Option zu prüfen: https://github.com/react-page/react-page

**Comment by barbalex** [comment]
@rebeccakurz @kmarti 

In v1.35.0 ist ein sogenannter "markdown editor" implementiert.

Mit Markdown kann man Texte formatieren. Bei der Ausgabe des Textes braucht es allerdings ein Werkzeug, welches das Markdown in das gewünschte Format umwandelt. In unserem Fall in html.

Markdown ist ein reines Text-Format, dass daher auch roh in ein Textfeld einer Datenbank gespeichert werden kann und sogar noch auswertbar bleibt.

Markdown ist nicht so mächtig wie HTML oder Word. Aber ihr kennst es: Github Issues schreibt man nämlich mit Markdown.

Neustens können wir also in Textfeldern in apflora Markdown anbieten. Wo es Sinn macht.

Ich habe es vorerst erst im Formular "AP-Bericht", im Feld "Bemerkungen" integriert, also z.B. hier: https://apflora.ch/Daten/Projekte/e57f56f4-4376-11e8-ab21-4314b6749d13/AP-Berichte/fa163f8e-5217-11e8-ab23-3b478fb277b2

Für eures konkrete Anliegen (Zeilenumbrüche) ist Markdown im Prinzip ein Overkill. Es ist aber die einfachste Methode, die ich kenne, um Zeilenumbrüche in einer Datenbank zuverlässig zu speichern. Und vielleicht werdet ihr auch mal ein paar der übrigen Möglichkeiten nutzen, z.B. fett, kursiv, Titel...

Und es sollte für euch einigermassen einfach zu lernen sein.

In Markdown-Feldern seht ihr nun ein Menüband am oberen Rand des Feldes. Links sind die Formatierungs-Möglichkeiten. Rechts zwei Schaltflächen:
1. Die Linke wechselt von Editiermodus zum parallelen Editieren mit Vorschau, zur reinen Vorschau und dann wieder in den reinen Editiermodus
2. Die rechte ermöglicht euch, beim Schreiben den ganzen Bildschirm zu nutzen

Versucht das bitte mal aus. Und sagt mir dann, in welchen Feldern ihr Markdown verwenden wollt.

**Comment by barbalex** [comment]
@rebeccakurz @kmarti 
Ich hab noch etwas wichtiges vergessen: Das Markdown-Werkzeug passt seine Höhe im Editier-Modus leider nicht automatisch an den Inhalt an. Ihr könnt das Feld am unteren rechten Rand mit der Maus packen und grösser ziehen. Genau so wie hier in GitHub.

**Comment by kmarti** [comment]
Super!
Das wäre gut in AP-Berichte bei den einzelnen AP-Arten, möglichst in allen Textfeldern, zumindest aber in Bemerkungen und Analyse

**Comment by rebeccakurz** [comment]
Das fände ich auch super, wenn es in den AP-Berichten der einzelnen Arten in allen Textfeldern möglich wäre. 
Allenfalls wäre es auch möglich, in allen Bemerkungsfeldern Markdown zu verwenden? Also zum Beispiel auch bei den Teilpopulationen, den Massnahmen und den Feldkontrollen?

**Comment by barbalex** [comment]
Bei Feldern, die irgendwo gedruckt werden, ist der Aufwand etwas grösser. Weil die Daten für den Druck in HTML umgewandelt werden müssen.

Bei Feldern, die nicht gedruckt werden, ist der Aufwand klein.

Ich werde also:
- AP-Berichte alle Textfelder umwandeln (und Drucke anpassen)
- Bemerkungs-Felder in TPop, Massn, Feld-Kontrollen auch

Bei den Freiwilligen-Kontrollen wäre die Sache etwas problematischer: einerseits aufwändiger, weil sie gedruckt werden. Anderseits etwas problematisch, weil dann recht schnell das Formular nicht mehr auf eine Seite passen würde.

**Comment by rebeccakurz** [comment]
Diese Auswahl finde ich sinnvoll. In den Freiwilligen-Kontrollen braucht es das meiner Meinung nach auch nicht.
Danke!

**Comment by barbalex** [comment]
Ist implementiert

**Comment by rebeccakurz** [comment]
super vielen Dank!
