### ISSUE TITLE
Qualitätskontrolle Populationsberichte

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#349]
Hoi Alex 
Könntest du bitte die Qualitätskontrolle, die überprüft ob es einen Populations-Bericht gibt, wenn in einem Jahr eine Erfolgskontrolle stattgefunden hat, überprüfen?
Z. B. bei Potamogeton coloratus TPop 40.2 hat es eine Erfolgskontrolle im 2019 und eine Teilpopulations-Bericht aber keinen Populations-Bericht (siehe Screenshot). In der Qualitätskontrolle erscheint dies aber nicht... 
<img width="480" alt="Bildschirmfoto 2019-12-16 um 16 20 39" src="https://user-images.githubusercontent.com/30288503/70919511-42814880-2021-11ea-9088-82ae20d378ed.png">

**Comment by barbalex** [comment]
Kannst du mir bitte sagen, wie diese Kontrolle heisst?

**Comment by rebeccakurz** [comment]
Das müsste dieser sein: 
Population mit angesiedelten Teilpopulationen (vor dem Berichtjahr), die (im Berichtjahr) kontrolliert wurden, aber ohne Populations-Bericht (im Berichtjahr)

**Comment by barbalex** [comment]
Potamogeton coloratus TPop 40 ist ursprünglich, aktuell. Nicht angesiedelt. Es hat auch keine angesiedelte Teilpopulation. Daher ist es korrekt, dass diese Qualitätskontrolle diese Population nicht auflistet.

**Comment by barbalex** [comment]
Ich glaube, du willst sagen: Ihr wollt eine Qualitätskontrolle, welche immer auflistet, wenn eine Teil-Population kontrolliert wurde, aber auf Ebene Population kein Bericht erstellt wurde?

Das gibt es auf Ebene TPop: "Teilpopulation mit Kontrolle (im Berichtjahr) aber ohne Teilpopulations-Bericht (im Berichtjahr)".

Aber ist es auf Ebene Pop wirklich gewollt? Muss die Population wirklich immer beurteilt werden, wenn ev. nur eine von vielen TPop kontrolliert wurde?

**Comment by rebeccakurz** [comment]
Doch, laut unserer Anleitung muss ein Population immer dann beurteilt werden, wenn eine TPop kontrolliert wurde. Wenn nur eine von vielen kontrolliert wurde, kann der Status auf "unsicher" gestellt werden. Es können auch EKs aus verschiedenen Jahren für die Beurteilung herangezogen werden. 

Könntest du deshalb diese Qualitätskontrolle in den nächsten Budgetentwurf aufnehmen?

**Comment by barbalex** [comment]
Ja gerne :-)

**Comment by barbalex** [comment]
Ist umgesetzt
