### ISSUE TITLE
TPop: Gemeinde eingeben geht nicht

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#35]
Es können nur einige wenige Gemeinden eingegeben werden. Auch Löschen eines Gemeinde-Eintrags, den man mal aus der kurzen Liste ausgewählt hat, geht nicht mehr.

**Comment by barbalex** [comment]
Ich glaube, es gibt ein Missverständnis: Es handelt sich hier um ein "autocomplete" Feld, nicht ein "select":

- man kann also nicht aus einer vorgegebenen Liste wählen (und in dieser Liste beliebig weit runter scrollen)
- sondern man tippt ein paar Buchstaben, es erscheint eine Liste von passenden Vorschlägen und man kann dan einen Vorschlag übernehmen - muss aber nicht (letzteres ist konfigurierbar)

Es funktioniert genau gleich wie bisher - ausser, dass sich eine Liste öffnet, wenn das Feld fokussiert wird. Offensichtlich gibt einem das den Eindruck, es handle sich um ein "select" Feld. Daher habe ich das nun ausgeschaltet. Danke für die Rückmeldung.

Löschen geht auch gleich wie bisher und in jedem anderen Textfeld.
