### ISSUE TITLE
EKF-Formulare: Bild wird nicht gedruckt

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#350]
Bilder der zu kontrollierenden Pflanze werden nicht gedruckt.
(Auf dem Forlular sind sie zu sehen, aber danach in der Druckvorschau und auf dem Ausdruck nicht mehr.)

**Comment by barbalex** [comment]
O.k., ich hab's. Drucken ist leider kompliziert :-(

Beim Drucken gibt es eine Option, um "Hintergrundgrafiken" einzublenden. Wenn diese nicht gewählt ist, wird das Bild nicht gedruckt.

**Comment by barbalex** [comment]
Juhui, es gibt eine Möglichkeit, Chrome und Firefox vom Code aus dazu zu zwingen, Hintergrundbilder anzuzeigen. Wird im nächsten Update integriert sein.

**Comment by rebeccakurz** [comment]
tiptop, das scheint zu funktionieren, danke!
