### ISSUE TITLE
EKF-Formulare erzeugen

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#351]
Hoi Alex

Ich habe eine Frage zu den EKF-Formularen.
Ist es richtig, dass ich nun bei den einzelnen Teilpopulationen erfassen muss (von Hand), welcher Freiwillige sie kontrolliert?
Dann kann ich unter dem Benutzer die Formulare für dieses Jahr erzeugen und danach drucken. 
Korrekt?

**Comment by barbalex** [comment]
Ja. Nach dem nächsten Update wird die Dokumentation (https://apflora.ch/Dokumentation/Benutzer/Erfolgs-Kontrollen-Freiwillige) entsprechend aktualisiert sein.
