### ISSUE TITLE
Fehlermeldung

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#352]
Hoi Alex
Wollte mich gerade in die FloraDB einloggen. Dabei kam die Meldung, dass es eine neue Version gibt, die ich dann auch öffnen wollte. 
Dann kam die Meldung mit den letzten Anpassungen (siehe Screenshot). Bei diesen sind aber alle Anpassungen seit anfangs 2019 aufgelistet. 
Wenn ich auf alle okay klicken will, kommt eine Fehlermeldung (siehe Screenshot).
<img width="2006" alt="Bildschirmfoto 2020-01-15 um 15 48 15" src="https://user-images.githubusercontent.com/30288503/72443735-0de2e700-37af-11ea-9f05-e89e9b0574c4.png">
<img width="1314" alt="Bildschirmfoto 2020-01-15 um 15 48 26" src="https://user-images.githubusercontent.com/30288503/72443748-13403180-37af-11ea-9d80-817b73af7bc6.png">

**Comment by barbalex** [comment]
Hast du ein zweites Mal probiert? Hat es dann geklappt? Ich gehe davon aus.

Es macht den Eindruck, als ob die (automatische) Anwendung nicht gelungen ist: Wenn kein Benutzername oder ein nicht existierender erhalten wird, sieht apflora, dass dieser Benutzer noch keine Mitteilungen gelesen hat und listet diejenigen des letzten Jahrs auf.

Wenn nun in der Zwischenzeit (im Hintergrund?) die Anmeldung gelungen ist, versucht apflora in die Datenbank zu schreiben, dass du diese Mitteilungen jetzt gelesen hast. Dort steht das aber schon. Daher die Meldung.

Habe jetzt im Code sichergestellt, dass Meldungen nur angezeigt werden, wenn der Benutzer erfasst ist. Somit sollte das hoffentlich nicht mehr passieren.

Das sollte also ab v1.22.1 nicht mehr passieren.

Danke für die Meldung.
