### ISSUE TITLE
EK-Planung: Leerwerte bei EK-Frequenz filtern erzeugt Absturz

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#354]
Ich wollte gerade in der EK-Planung bei der EK-Frequenz die Leerwerte filtern. 
Dies führte jedoch zum Absturz und der riesengrosse rote Smiley ist erschienen. Wenn man die Maus dann bewegt hat, kam noch eine Meldung: " TypeError: Cannot read property 'jahr' of undefined" und dann eine Liste in was er sie nicht lesen konnte. (ging leider nicht zum die Meldung zu screenshoten).
Aktualisieren hat nichts gebracht, ich musste mich abmelden und wieder anmelden. Ich habe es noch zweimal versucht mit dem Leerwerte filtern, aber immer dasselbe Ergebnis erhalten.

**Comment by barbalex** [comment]
Wenn ich das z.B. bei Allium angulosum versuche, klappt es. Bei welchem AP hast du den Fehler ausgelöst?

**Comment by rebeccakurz** [comment]
Hmm nun scheint es bei mir auch ohne Probleme zu klappen. Weiss leider nicht mehr bei welcher Art es war... Würde mich melden, falls es nochmals auftreten würde.
