### ISSUE TITLE
Fehler Koordinaten

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#355]
Hoi Alex
Gerade hat mir Hanna Vydrzel geschrieben, dass in der Flora DB bei einer Teilpopulation (114.2) von Tulipa sylvestris falsche Koordinaten vorhanden sind. Die Teilpopulation befindet sich eigentlich in Eglisau, Viadukt (und heisst auch so), war aber in Glattfelden, Berg verortet. 
Ich habe in alten Exporten nachgesehen und die Koordinaten waren mindestens schon seit Oktober falsch. Wir hatten um diese Zeit schon mal das Problem, dass TPops am falschen Ort waren. Du hattest mir doch dann eine Sicherung geschickt und ich konnte die richtigen Koordinaten wieder einsetzen. Könnte es sein, dass das ebenfalls zu diesem Zeitpunkt passiert ist und einfach noch nicht bemerkt wurde? 
Ich habe nun auf jeden Fall bei der TPop 114.2 wieder die richtigen Koordinaten eingesetzt. 
Aber vielleicht muss man das im Auge behalten, dass so etwas nicht nochmals passiert.
<img width="1938" alt="Bildschirmfoto 2020-01-28 um 15 41 10" src="https://user-images.githubusercontent.com/30288503/73274864-949fb700-41e6-11ea-80ff-546967761154.png">

**Comment by barbalex** [comment]
> Könnte es sein, dass das ebenfalls zu diesem Zeitpunkt passiert ist und einfach noch nicht bemerkt wurde?

Keine Ahnung. Mit ist auch nichts bewusst, was dazu hätte führen können. Ausser: Irgendwann haben wir die Koordinaten in das neue Format umgewandelt (LV95) und danach in WGS84. Aber wenn dort ein Fehler passiert wäre, müsste er flächendeckend passiert sein (Umwandlung in WGS84) bzw. systematisch ausserhalb der Grenzen von LV95 (die nicht so klar sind, aber sicher nicht innerhalb der Schweiz). Und das ist ja nicht geschehen, oder?

**Comment by rebeccakurz** [comment]
Nein der Fehler ist nicht flächendeckend, sondern nur spezifisch. Und die TPops sind auch nicht irgendwo hin verschoben worden, sondern so viel ich weiss dort hin wo es auch andere TPop gibt. Also ist der Fehler wohl schon irgendwo manuell passiert...

**Comment by barbalex** [comment]
Ich schliesse das mal, weil keine weiteren ähnlichen Vorfälle gemeldet wurden
