### ISSUE TITLE
AP-Berichte: unterschiedliche Anzahlen

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#356]
Hoi Alex
Wir sind gerade noch an der Kontrolle ob die Karten zu den Vorkommen der einzelnen Arten mit den AP-Berichten in der FloraDB übereinstimmen. 
Dabei ist uns aufgefallen, dass im AP-Bericht von Inula hirta von 2019 bei der Bestandesentwicklung 3 nicht kontrollierte Populationen seit 2007 drin sind. Wenn ich einen Export der Populationen mit dem letzten Pop-Bericht mache, ist dort aber nur 1 nicht kontrollierte Pop drin. Auch zeigt es im AP-Bericht an, dass es  28 bekannte Populationen bei dieser Art gibt (unter A. Grundmengen). Wenn man bei B. Bestandesentwicklung aber die kontrollierten (27) und nicht kontrollierten (3) Pop seit 2007 zusammenzählt, kommt man auf 30 Pop. 

Dasselbe bei Allium angulosum. Dort sind es unter A. Grundmengen 31 bekannte Pop. Unter B Bestandesentwicklung aber 32 Pop. (kontrollierte und nicht kontrollierte zusammengezählt).

Hast du eine Erklärung dazu?
<img width="800" alt="Bildschirmfoto 2020-01-29 um 11 50 50" src="https://user-images.githubusercontent.com/30288503/73350607-a6886500-428d-11ea-82a1-292d941e036f.png">

**Comment by barbalex** [comment]
Zur Info: ich arbeite daran

**Comment by barbalex** [comment]
Ist in v1.22.10 korrigiert.

Ausserdem wurden die Abfragen für den Jahresbericht mit neuen Möglichkeiten verbessert. Vermutlich werden Jahresberichte jetzt schneller und weniger PC-belastend erzeugt. Das wird man wohl v.a. spüren, wenn der umfassende Bericht für alle Arten erzeugt wird.

**Comment by kmarti** [comment]
Super, vielen Dank!!

------------------------------------------
Karin Marti
Dr.sc.nat.ETH
topos Marti & Müller AG
Idastrasse 24
8003 Zürich
marti@toposmm.ch<mailto:marti@toposmm.ch>
Tel. 044 451 52 55


Von: Alexander Gabriel <notifications@github.com>
Antworten an: barbalex/apf2 <reply@reply.github.com>
Datum: Mittwoch, 29. Januar 2020 um 19:09
An: barbalex/apf2 <apf2@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [barbalex/apf2] AP-Berichte: unterschiedliche Anzahlen (#356)


Ist in v1.22.10 korrigiert.

Ausserdem wurden die Abfragen für den Jahresbericht mit neuen Möglichkeiten verbessert. Vermutlich werden Jahresberichte jetzt schneller und weniger PC-belastend erzeugt. Das wird man wohl v.a. spüren, wenn der umfassende Bericht für alle Arten erzeugt wird.
