### ISSUE TITLE
EK-Planung: Anzahlen werden zusammengezählt

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#357]
Hoi Alex

Bei der EK-Planung von Aldrovanda ist uns bei der Teilpopulation 10.6 bei der Ansiedlung von 2019 aufgefallen, dass für die Zahl, die neben dem Blitz angezeigt wird, die Anzahl Triebe und Anzahl Pflanzen zusammengezählt wurden. 
1. Eigentlich sollte hier nur die zielrelevante Zähleinheit angezeigt werden oder? (Habe nochmals nachgeschaut, bei Aldrovanda sind das "Triebe").
2. Falls hier zwei Anzahlen angezeigt werden, dürften diese nicht zusammengezählt werden.
<img width="282" alt="Bildschirmfoto 2020-01-29 um 11 53 19" src="https://user-images.githubusercontent.com/30288503/73351413-3844a200-428f-11ea-8219-4b893dfe20f0.png">
<img width="446" alt="Bildschirmfoto 2020-01-29 um 11 53 01" src="https://user-images.githubusercontent.com/30288503/73351417-3aa6fc00-428f-11ea-8861-b6ba8914ca92.png">

**Comment by barbalex** [comment]
Hoi Rebecca

Hier werden Daten von Massnahmen ausgewertet. Diese wurden nicht mit den Zähleinheiten erhoben sondern mit den dort verfügbaren Feldern: 
- anz_triebe
- anz_pflanzen
- anz_pflanzstellen

Die ziel-relevante Zähleinheit ist hier nicht relevant. Ich kann einfach generell wählen, welche dieser Felder summiert werden.

Wenn ihr wollt, dass in Ansiedlungen die Mengen wie in Kontrollen erhoben werden, dann wird das ein ziemlich grosser Umbau, der wohl mehrere Tage Arbeit gibt und Nebenwirkungen (v.a. Potential für neue Fehler) auf andere Funktionen der Anwendung haben wird.

Aber wie es scheint, merken wir nun, dass dies sinnvoll wäre, weil Ansiedlungen sowohl bei der EK-Planung wie später bei der Auswertung und Darstellung in Diagrammen gleichwertig wie Kontrollen verwendet bzw. dargestellt werden sollen. Und wenn wir nicht die ziel-relevante Einheit verwenden, wird das nie befriedigend möglich sein.

Und weil das für die Diagramme wichtig ist, wäre es auch wichtig, diese Änderung _vorher_ zu vollziehen. Schade, dass die EK-Planung schon existiert - wäre viel effizienter gewesen, wenn wir es vorher gemerkt hätten.

Was wir jetzt merken, ist dass bei apflora derselbe Fehler gemacht wurde, wie bei vielen wissenschaftlichen Arbeiten: Bei der Konzeption wurde nicht auf die Auswertung fokussiert, sondern einfach mal erfasst, was und wie man es sinnvoll fand. Wenn man das Endprodukt der Auswertung vorangestellt hätte, würden solche tiefgreifenden Fehler nicht passieren.

apflora ist aber selber übrigens ein seltenes und sehr gutes Beispiel, wie genau das gemacht werden sollte: Nämlich beim bisherigen Jahresbericht. Dort wurde zuerst das Endprodukt der Auswertung (der Jahresbericht) entwickelt. Und danach das Projekt und Anwendung, um diesen zu generieren.

Sagt mir bitte, ob ich überlegen soll, wie Zählungen in Massnahmen analog zu Kontrollen integriert werden könnten, wie aufwändig das wäre und was das für die bisherigen Daten heissen würde. 

Ihr müsstet mir aber auch sagen, ob es aus eurer Sicht bei der Zählung in Massnahmen aus eurer Sicht Unterschiede gibt zu den Kontrollen.

**Comment by rebeccakurz** [comment]
> Die ziel-relevante Zähleinheit ist hier nicht relevant. Ich kann einfach generell wählen, welche dieser Felder summiert werden.

Vielleicht könnten wir damit anfangen, dass diese Felder **NICHT** summiert werden sollten. Am Beispiel von Aldrovanda: Hier wurden insgesamt 10 Pflanzen oder eben 10 Triebe ausgebracht (Triebe sind hier gleichzusetzen mit Pflanzen). Diese beiden Zahlen dürften also nicht addiert werden. 
Oder ein weiteres Beispiel: Auspflanzung von Thalictrum galioides in den Geroldswiler Auen (z.B. TPop 45.5). Hier wurden 8 Pflanzen ausgebracht mit insgesamt 61 Trieben. Auch hier dürften die Zahlen nicht summiert werden, da es sich jeweils um andere Zähleinheiten handelt.
<img width="564" alt="Bildschirmfoto 2020-01-30 um 09 53 44" src="https://user-images.githubusercontent.com/30288503/73434343-dba4be00-4346-11ea-9af3-868def654627.png">
<img width="236" alt="Bildschirmfoto 2020-01-30 um 09 54 01" src="https://user-images.githubusercontent.com/30288503/73434348-dd6e8180-4346-11ea-91fa-89c48bf1af00.png">

**Comment by barbalex** [comment]
Ich bin etwas überrascht, dass dieselbe Sache doppelt erfasst wird.

Aber wenn das offenbar so ist: Woher soll apflora wissen, welche der Einheiten zu verwenden ist?

Wenn bei einer Art Triebe und Pflanzen nicht gleichzusetzen sind, kann es wohl ein grosser Unterschied sein, ob Triebe oder Pflanzen gezählt werden.

Plus: Wenn jemand entschieden hat, die Einheit, welche apflora summiert nicht zu erfassen, sondern die andere. Dann gibt es auch kein sinnvolles Ergebnis.

Ich sehe ehrlich gesagt keinen anderen Weg, als es gleich zu machen wie bei den Kontrollen. Dann weiss jede, die Daten erfasst, dass die ziel-relevante Einheit gefragt ist. Sonst werden wir bestimmt dauernd optimieren bzw. anpassen. Mit der Folge, dass extrem komplexe Formulare/Abläufe/Auswertungen/Abfragen dauernd angepasst werden müssen. Was sehr fehlerträchtig ist und ebenso ineffizient.

> Vielleicht könnten wir **damit anfangen**, dass diese Felder NICHT summiert werden sollten

Genau dieses Vorgehen möchte ich hier unbedingt vermeiden. Jede Anpassung wird schmerzhaft werden. Wir sollten uns überlegen, wie es _richtig_ ist und diesen Zustand anstreben.

**Comment by rebeccakurz** [comment]
Okay, dann werde ich das mit KM anschauen.

**Comment by rebeccakurz** [comment]
Lieber Alex 
Wir haben es zusammen angeschaut und es wäre gut, wenn du überlegen könntest, wie Zählungen in Massnahmen analog zu Kontrollen integriert werden könnten (so wie du vorgeschlagen hast).
Bei den Massnahmen braucht es aber weiterhin nur die Einheiten "Planzen", "Triebe", "Anzahl Pflanzstellen" (wobei diese nie zielrelevant sind).

Vielleicht noch als Erklärung: Man hat eigentlich nur gerade dort mehrere Zählungen (also Pflanzen und Triebe), wo die zielrelevante Einheit "Triebe" sind. Dort wird dann diese Einheit bereits bei den Auspflanzungen gezählt, aber eben auch noch angegeben, wie viele Pflanzen ausgebracht wurden, weil diese Einheit ebenfalls aussagekräftig ist. 

Vielen Dank und liebe Grüsse
Rebecca

**Comment by barbalex** [comment]
O.k., wird auf die TODO-Liste genommen

**Comment by barbalex** [comment]
Ab v1.28.4:
- wird in Massnahmen neben dem Massnahmen-Symbol die Anzahl gemäss ziel-relevanter Einheit angezeigt
- wird im Kontext-Menü bei der Ansiedlung zusätzlich die ziel-relevante Einheit und deren Anzahl angezeigt, wenn sie erfasst wurde
