### ISSUE TITLE
Jahresbericht Blackstonia acuminata - erloschene Pop.

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#358]
Hoi Alex
Kaspar Spörri hat sich die Karten/Jahresberichte auch noch angesehen und noch ein paar Unstimmigkeiten entdeckt.
Bei Blackstonia acuminata gibt es in der FloraDB 8 erloschene Populationen (6 angesiedelt erloschen, 2 ursprünglich erloschen). Diese werden auch auf der Karte, die wir erstellt haben, so angezeigt. Jedoch im Jahresbericht 2019 wird unter "A. Grundmengen" gar keine erloschen Population aufgeführt (nur 11 erloschene Teilpopulationen). 
Könntest du das mal überprüfen?
Danke!

**Comment by barbalex** [comment]
Ja, das gab es einen Fehler bei der Berechnung der erloschenen Populationen. Wird in v1.22.12 korrigiert sein.

Sorry und danke für die Meldung!
