### ISSUE TITLE
Drucken EKF Protokollblätter

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#359]
Hoi Alex
Etwas scheint nicht ganz zu funktionierern, wenn ich die EKF-Protokollblätter aus der FloraDB drucken möchte. Die Zähleinheiten werden nicht richtig angezeigt.
<img width="2006" alt="Bildschirmfoto 2020-02-10 um 10 54 51" src="https://user-images.githubusercontent.com/30288503/74139520-d0c61500-4bf3-11ea-94aa-a5c8dbf13cdc.png">

Wenn ich dann auf Abbrechen klicke, erscheint noch folgende Fehlermeldung:
<img width="405" alt="Bildschirmfoto 2020-02-10 um 10 51 58" src="https://user-images.githubusercontent.com/30288503/74139563-e50a1200-4bf3-11ea-944c-6c3455fca29d.png">

Könntest du dir das bitte (möglichst zeitnah) anschauen?
Vielen Dank!

**Comment by rebeccakurz** [comment]
Es scheint schon in dieser Ansicht nicht alle Formulare korrekt anzuzeigen:
<img width="2002" alt="Bildschirmfoto 2020-02-10 um 11 07 40" src="https://user-images.githubusercontent.com/30288503/74140631-bab95400-4bf5-11ea-8f5a-42fbeae9f9cc.png">
<img width="2002" alt="Bildschirmfoto 2020-02-10 um 11 07 49" src="https://user-images.githubusercontent.com/30288503/74140638-bd1bae00-4bf5-11ea-9403-bd246bd9f2b8.png">
(Beim zweiten Bild sind die Zähleinheiten falsch.)

**Comment by rebeccakurz** [comment]
[apflora v1.22.12.pdf](https://github.com/barbalex/apf2/files/4180229/apflora.v1.22.12.pdf)

**Comment by barbalex** [comment]
Wie kann man das provozieren? Wenn ich das Formular öffne und drucke stimmt alles.
Hast du die Seite einmal neu geladen?

**Comment by barbalex** [comment]
Wenn du den Effekt reproduzierbar provozieren kannst, beschreibe mir bitte, wie. Dann kann ich das Problem hoffentlich nachvollziehen und lösen.

**Comment by barbalex** [comment]
Ich bin in den Ferien - Reaktionszeiten können etwas höher sein, als üblich

**Comment by rebeccakurz** [comment]
Habe die Seite mehmals neu geladen, mich ausgeloggt und wieder eingeloggt. Habe es auch bei mehreren Freiwilligen probiert. 
Also ich gehe zum Benutzer, dann auf EKF-Formulare für 2020 öffnen. Wenn ich dann direkt auf das Symbol um alle zu drucken gehe, scheint es zwar die Formulare korrekt anzuzeigen, aber ohne das Bild der Pflanze. Also wieder abbrechen. Dann habe ich das erste Formular angegklickt und bin dann nochmals auf alle drucken. Nun zeigt es mir ein Bild an, aber für alle Formulare das Gleiche (also auch bei Pulsatilla das Bild von Himantoglossum).
[apflora_v1.22.12.pdf](https://github.com/barbalex/apf2/files/4180424/apflora_v1.22.12.pdf)

**Comment by rebeccakurz** [comment]
Kann es leider nicht reproduzierbar provozieren, es ist jedesmal wieder anders, aber nie ganz korrekt...

**Comment by rebeccakurz** [comment]
Okay, es scheint bei einigen zu funktionieren...
Kannst du es mal bei der Freiwilligen Sophie Baumann probieren? (Benutzername: sbaumann). Bei ihr hat es bis jetzt noch nicht geklappt. Vielleicht weil sie relativ viele EKFs hat?

**Comment by barbalex** [comment]
Diese Formulare sind ein kleines Kunstwerk und auch erst seit ca. einem Jahr überhaupt technisch im Browser möglich. Ein Nebeneffekt davon ist, dass sie relativ langsam aufgebaut werden. Und je nach Browser/Computer unterschiedlich langsam.

Leider habe ich nicht herausgefunden, wie der Code wissen kann, WANN alle Formulare fertig aufgebaut wurden. Vielleicht finde ich dafür irgendwann eine Lösung. Vorläufig hatte ich einfach 1.5 Sekunden Zeit gegeben. Was offenbar in diesen Fällen nicht reicht. Vermutlich sind viele der von dir erlebten Effekte darauf zurückzuführen, dass die Formulare zu früh gedruckt wurden, bevor sie fertig aufgebaut waren.

Ich habe das nun so angepasst, dass die Wartezeit 3 Sekunden beträgt, plus pro Seite zusätzliche 300 Millisekunden. Weil das eine Weil dauert, erscheint eine Meldung.

Das wird in v1.22.13 wirksam.

**Comment by barbalex** [comment]
Bloss: die nächste Version kann ich momentan nicht bauen, weil die Entwicklungs-Umgebung plötzlich ein Problem hat. Das wohl in irgend einer von tausenden von Abhängigkeiten gelöst werden muss 😞

**Comment by barbalex** [comment]
O.k., v1.22.13 ist live.

Das mit den Bildern kann daran liegen, dass sie z.T. nicht existieren. Ich habe nur die Bilder, die ihr mir letztes Jahr geliefert habt. Werde versuchen, eine Meldung anzuzeigen, wenn das Formular das Bild nicht findet.

**Comment by barbalex** [comment]
In v1.22.14 erscheint nun eine Meldung, wenn das Formular für die Art kein Bild findet.

Ich bin mal optimistisch und schliesse den Issue, in der Hoffnung, dass das Problem gelöst ist 🤞

**Comment by barbalex** [comment]
Wenn also das Bild fehlt, musst du mir eines schicken, das ich aufarbeiten und einfügen kann.

**Comment by barbalex** [comment]
Übrigens:

> Bei ihr hat es bis jetzt noch nicht geklappt. Vielleicht weil sie relativ viele EKFs hat?

Das war ein Volltreffer!

**Comment by rebeccakurz** [comment]
Okay, vielen Dank! Werde es mir heute anschauen und Rückmeldung geben.

**Comment by rebeccakurz** [comment]
[apflora v1.22.14.pdf](https://github.com/barbalex/apf2/files/4185060/apflora.v1.22.14.pdf)

Scheint leider noch nicht ganz geklappt zu haben... =(
Wenn du dir das PDF anschaust ist nun einerseits überall die Info "Der Druck wird vorbereitet..." drauf (und geht auch nicht weg, egal wie lange ich warte). 
Andererseits ist bei allen Formularen das selbe Bild eingefügt. Also hier das Bild von Gagea auch bei Pulsatilla, Ophrys und Himanto.

**Comment by barbalex** [comment]
Das scheint eine ziemliche Knacknuss zu sein. Ich brauche noch mehr Zeit, um das zu lösen.

**Comment by rebeccakurz** [comment]
Danke, dass du da dran bist!
Übrigens: Wenn ich die Protokollblätter einzeln drucke funktioniert es einwandfrei :-)
Und wenn ich nur Protokollblätter einer Art drucken muss, funktioniert es auch. Ich glaube das Hauptproblem ist, dass das gleiche Bild bei allen Arten eingesetzt wird, sobald man ein einzelnes Protokollblatt angeklickt hatte. Und bevor man ein Protokollblatt angeklickt hat, erscheint gar kein Bild auf dem Ausdruck. 

Dann hätte ich noch eine Bitte: Wenn man alle Protokollblätter miteinander druckt, ist die Reihenfolge der Blätter zufällig oder auf jeden Fall nicht der Reihe nach. Könnte man diese noch sortieren?

**Comment by barbalex** [comment]
> Wenn man alle Protokollblätter miteinander druckt, ist die Reihenfolge der Blätter zufällig oder auf jeden Fall nicht der Reihe nach. Könnte man diese noch sortieren?

Werd ich anschauen. Aber erst, wenn der Mehrfach-druck klappt.

**Comment by barbalex** [comment]
O.k., Druck ist in v1.22.18 korrigiert:
- Die Wartezeit wird jetzt anders angezeigt, erscheint nicht im Druck
- Bilder sollten wirklich laden

Bitte mach künftig für jeden Fehler ein eigenes Issue. Ich verliere in diesem Issue die Übersicht und wenn man ein Fehlverhalten sucht, findet man es nicht, ohne alle Issues durchzulesen. Der Fehler sollte im Titel klar sein.

Z.B.:
> Wenn man alle Protokollblätter miteinander druckt, ist die Reihenfolge der Blätter zufällig oder auf jeden Fall nicht der Reihe nach. Könnte man diese noch sortieren?
Sollte ein eigenes Issue sein. Das werde ich jetzt noch anschauen.

**Comment by barbalex** [comment]
In v1.22.19 ist der Druck gleich sortiert, wie die angezeigte Liste

**Comment by rebeccakurz** [comment]
super, das scheint geklappt zu haben, vielen Dank!
