### ISSUE TITLE
Beschränkung Zugang verschiedene Akteure

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#360]
Lieber Alex
Wir haben uns noch überlegt, dass wir gerne den Zugang für die verschiedenen Akteure weiter beschränken möchten. (So wie die Freiwilligen nur ihre eigenen Kontrollen sehen).
Konkret würde das heissen, dass die Artverantwortlichen nur noch ihre eigenen Sets sehen würden. (Seit 2019 sind die verschiedenen AP-Arten in 6 Sets aufgeteilt, ich hänge dir die aktuelle Liste an.)
[Artverantwortliche_nach Arten_neu_2020.xlsx](https://github.com/barbalex/apf2/files/4197343/Artverantwortliche_nach.Arten_neu_2020.xlsx)
Würde das gehen? (Jasmin hat gesagt, dass ihr bei der ZV-Datenbank auch verschiedene Zugriffsmöglichkeiten geschaffen habt, vielleicht geht das analog dazu?)
Vielen Dank und liebe Grüsse
Rebecca

**Comment by barbalex** [comment]
Bei vermehrung geht das. Weil für die API ein anderes Werkzeug verwendet wird, dass in dieser Beziehung toll ist: hasura.

Bei apflora auf das von vermehrung verwendete Werkzeug zu wechseln, würde heissen: alle GraphQL-Abfragen müssten neu geschrieben werden. Das sind tausende Zeilen funktions-kritischen Codes.

Ausserdem darf man nie vergessen: differenzierte Zugangsrechte geben VIEL Arbeit. Das ist eine sehr komplexe Funktionalität.

Vielleicht geht es auch mit dem aktuell verwendeten Werkzeug (PostGraphile). Ich muss mir mal ein paar Stunden nehmen, um das zu überlegen.

**Comment by barbalex** [comment]
@rebeccakurz @kmarti 

Ich überleg mir gerade, wie der Zugriff auf AP-Daten durch Benutzer mit der Rolle "artverantwortlich" beschränkt werden kann. Es scheint mir doch relativ wichtig zu sein. 

Und nach etwas Überlegung glaube ich, dass es ist mit der aktuell verwendeten Technologie gut möglich ist (wenn auch jede Form von Rechte-Steuerung immer sehr aufwändig ist).

**Nachfolgend meine Fragen:**

Wir würden also pro AP in einer Liste (z.B. Tabelle "ap_av") definieren, welche Benutzer mit der Rolle "artverantwortlich" die Daten sehen und bearbeiten dürfen. Richtig?

Benutzer mit der Rolle "manager" hätten nach wie vor Zugriff auf alle AP's. Richtig?

Benutzer mit der Rolle "reader" hätten nach wie vor Lese-Zugriff auf alle AP's. Richtig? Oder sollen sie auch in der Liste pro AP ausgewählt werden müssen? (der Mehraufwand dafür wäre klein)

Weil es Stellvertretungen und ev. Arbeitsteilung gibt, müssten pro AP mehrere Artverantwortliche in dieser Liste erfasst werden können. Richtig?

Wie ich aus eurer Excel-Liste entnehme, müssten die Zugriffsrechte auf eine Zeitspanne beschränkt werden können. Richtig? 
Oder wollt ihr einfach die Liste anpassen, wenn jemand neu Zugriff erhalten soll bzw. nicht mehr?

Das Feld "Verantwortlich" im Formular "Aktionsplan" bleibt erhalten, weil es immer noch nützlich ist, um zu wissen, welche(r) dieser Artverantwortlichen für diese Art letztlich verantwortlich ist. Richtig?

Ihr sprecht von Arten-**Sets**. Wofür genau würden künftig ev. in apflora.ch solche Sets verwendet? Inwiefern könnten sie in diesem Zusammenhang relevant sein?

Die Rolle "artverantwortlich" würde im Prinzip nach dieser Änderung eher "AP-mitarbeitend" bedeuten. Verstehe ich das Richtig?

**Comment by barbalex** [comment]
@rebeccakurz @kmarti 

Zur Implementation:

1. Ich würde zuerst die neue Tabelle schaffen, die Erfassung der AP-mitarbeitenden ermöglichen und die Einschränkung der Rechte vorbereiten
2. Dann müsstet ihr die AP-mitarbeitenden bei allen AP's ergänzen
3. Erst dann würde ich die Einschränkung der Rechte implementieren

**Comment by barbalex** [comment]
@rebeccakurz @kmarti 

Damit ihr euch bewusst seid: Sind einmal diese Rechte auf diese Weise eingeschränkt, gelten sie immer und überall.

Z.B. werden in Exporten diese Benutzer auch nur noch diese AP/Pop/TPop/Kontrollen etc. exportieren können.

Ich nehme an, dass ist auch genau was ihr wollt.

**Comment by barbalex** [comment]
@rebeccakurz @kmarti 

Vermutlich sollen Artverantwortliche auch _auf Ebene Projekt_ keine AP-Berichte sehen und bearbeiten können. Gemeint ist: Formular "AP-Bericht Jahresübersicht", wo nur das Jahr und die Bemerkungen (zu allen AP's) erfasst werden.

**Comment by barbalex** [comment]
Offenbar respektieren Views Policies (damit werden differenzierte Zugriffsrechte erstellt) nicht 😢 

Daher muss ich nun alles kontrollieren, was Views verwendet. Und diese so umbauen, dass es funktioniert. Das gibt sehr viel Arbeit...

**Comment by kmarti** [comment]
Zu Deinen Fragen (falls Du denn den Umbau wirklich machen kannst):
- Ja, Definition (Tabelle), welche Artverantwortlichen welche Arten sehen und bearbeiten dürfen
- Ja, Manager mit Zugriff auf alle Arten
- Reader mit Zugriff auf alle Arten und einzelne Reader mit Zugriff auf definierte Arten
- Ja, pro AP gibt es mehrere Artverantwortliche mit Zugriff (Stellvertretungen)
- Liste mit Zugriffsrechten soll von uns angepasst werden bei Bedarf (also keine Zeitspanne vorgeben)
- Ja, das Feld "verantwortlich" bleibt erhalten
- Arten-Sets: Z.B. für das Arten-Set Wasserpflanzen ist Tobias Liechti der Projektleiter. Regula Dickenmann, Agnes Schärer und er selber sind Artverantwortliche für die einzelnen Arten mit gegenseitiger Stellvertretung. Die Projektleitung eines Arten-Sets sollte Zugriff haben auf alle Arten dieses Sets (also wie eine Stellvertretung) und somit auch Exporte für ein Arten-Set machen können.
- AP-verantwortlich bleibt AP-verantwortlich (mitarbeitend ist die Stellvertretung; diese wird aber beim AP nicht aufgeführt)

Richtig, die Einschränkung der Zugriffsrechte sollen überall gelten.

Bei den AP-Berichten auf Projektebene ist ein Leserecht ok, denn am Schluss ist der ausgedruckte Jahresbericht sowieso für alle Artverantwortlichen einsehbar.

**Comment by barbalex** [comment]
Danke, scheint nun fast alles klar. Letze Präzisierung:

> Reader mit Zugriff auf alle Arten und einzelne Reader mit Zugriff auf definierte Arten

Das heisst: 
1. Reader erhalten alle eingeschränkten Zugriff. Und einigen gibt man in allen Arten Zugriff. Das ist für euch aufwändig
2. oder: Es gibt neu "reader" und "art-reader". "art-reader" sind wie "artverantwortlich" aber nur mit Leserechten. Das ist für mich aufwändiger aber machbar

Ich gehe mal davon aus, dass die neue Rolle "art-reader" am besten ist und ich sie implementiere.

> falls Du denn den Umbau wirklich machen kannst

Er scheint doch recht wichtig. Ich arbeite schon daran.

**Comment by kmarti** [comment]
art-reader ist gut!

**Comment by barbalex** [comment]
Ich habe die neuen Rechte implementiert und den Art-Verantwortlichen und ihren Stellvertretern gemäss eurer Liste in den jeweiligen Aktionsplänen den Zugriff erfasst.

(dabei musste ich die Rolle von Andreas Keel von "reader" auf "ap_writer" setzen)

Mir ist bewusst:
- das ganze ist tief greifend
- technisch ist der Eingriff gross
- vermutlich wird es daher technische Fehler geben, die ich in den nächsten Tagen/Wochen noch korrigieren muss
- ziemlich sicher werdet ihr merken, dass es dinge gibt, die jetzt nicht befriedigend gelöst sind: Benutzer, denen Rechte fehlen oder umgekehrt. Hoffentlich wird das nicht zu mühsam für alle Beteiligten
- Ich werde in den nächsten Wochen noch viele Views überprüfen. Views respektieren die differenzierten Rechte nicht. Z.B. ist es jetzt noch möglich, Populationen, Teil-Populationen und Kontrollen für alle Arten zu exportieren. Das werde ich in den nächsten Wochen anpassen. Auf Ebene AP sollten jetzt schon alle Exporte die Benutzerrechte respektieren

Um das Funktionieren zu testen, könnt ihr test-Benutzer verwenden, bei denen ihr als manager Rolle und Passwort ändern könnt.

Bitte meldet Wünsche/Fehler bezüglich Benutzer-Rechten nicht in diesem Issue sondern macht für jeden Fall einen eigenen.
