### ISSUE TITLE
Formular Freiwilligen-Kontrolle: Jahr ergänzen

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#361]
Hoi Alex
Ich hoffe du hattest schöne und erholsame Ferien?

Ich hätte noch einen (hoffentlich kleinen) Wunsch für die Formulare der Freiwilligen-Kontrollen: Könnten die Formulare mit dem jeweiligen Jahr ergänzt werden? Auf unseren alten Protokollblättern hatten wir das jeweils oben rechts neben dem Titel "Erfolgskontrolle Artenschutz Flora". Das würde es uns und den Freiwilligen erleichtern, die verschiedenen Protokollblätter den verschiedenen Jahren zuzuordnen. 
Vielen Dank und liebe Grüsse
Rebecca
[apflora v1.22.16.pdf](https://github.com/barbalex/apf2/files/4248789/apflora.v1.22.16.pdf)
[Beispiel 2019.pdf](https://github.com/barbalex/apf2/files/4248790/Beispiel.2019.pdf)

**Comment by barbalex** [comment]
Ich verstehe, dass das nützlich ist.

Aber: Wenn diese Anforderung von Anfang an eingebracht worden wäre, hätte es praktisch null zusätzlichen Aufwand erfordert. Vermutlich wäre die ganze Sache sogar einfacher gewesen, weil ich Aufwand treiben musste, um Kontrollen ohne Datum oder Jahr verarbeiten zu können bzw. Formulare verarbeiten zu können, die noch kein Datum hatten, weil es ja erst _nach_ der Erhebung durch die Freiwilligen erfasst würde. 

Weil sie aber jetzt nachträglich in ein extrem komplexes System hinein gepackt werden muss, wird das aufwändig und fehlerträchtig. Zum Beispiel baut darauf auf:

- die Möglichkeit, für eine Person alle Kontrollen eines Jahrs erstellen zu lassen
- die Auflistung aller EKF einer Person eines Jahrs, für diese Person aber auch für euch (zwei Implementationen)
- die EK-Planung

...die alle gebaut wurden, _nachdem_ klar schien, dass EKF zuerst mal ohne Datum existieren und das Datum erst später ergänzt wird.

**Nun ändert sich etwas Grundlegendes: EKF sollen ein Datum erhalten, _bevor_ die Freiwillige ihre Daten erfasst.**

Das wirkt zurück auf alle oben genannten Sachen, die darauf aufbauen. Und vermutlich auf mehr.

Ich muss das sehr sorgfältig angehen. Es gibt sicher minimal zwei Tage Aufwand. Je nachdem, wie es läuft auch mehr, falls ich Teile der oben genannten komplexen Systeme umbauen muss.

Es ist wahrscheinlich, dass eine solche Änderung jetzt bei aller Sorgfältigkeit meinerseits trotzdem zu neuen Fehlern in den oben genannten komplexen Abläufen führt, die wir dann anschliessend mühsam ausmerzen müssen.

Ich nehme das daher in die Jahresplanung auf. Es wäre viel zu riskant und aufwändig, dass rasch nebenher zu machen.

**Comment by barbalex** [comment]
Ich habe oben geschrieben:
> Es gibt sicher minimal zwei Tage Aufwand

@kmarti @rebeccakurz 
Rückfrage von mir: Soll ich diesen Aufwand jetzt leisten? Es ist wichtig genug, richtig?

**Comment by rebeccakurz** [comment]
Hoi Alex

Ja gerne, wenn du jetzt die Kapazität dazu hast (der Zeitpunkt wäre optimal, dann könnte ich es für die diesjährigen Kontrollen bereits brauchen).
Vielen Dank!

**Comment by barbalex** [comment]
Wann genau ist das?

**Comment by rebeccakurz** [comment]
Voraussichtlich komme ich ab nächster Woche dazu.

**Comment by barbalex** [comment]
Hm. Wie es scheint, geht es nicht primär darum, dass in der Kontrolle im Feld "Jahr" ein Wert enthalten ist. Sondern bloss, dass das Jahr auf dem Formular steht?

Letzteres ist einfach: Schau dir die neue Version 1.61.0 an.

Das Formular zeigt jetzt an:
- wenn noch kein Datum erfasst wurde: das aktuelle Jahr
- sobald ein Datum erfasst wurde: das Jahr gemäss erfasstem Datum

**Comment by rebeccakurz** [comment]
Ja genau so habe ich mir das vorgestellt.
Vielen Dank!
