### ISSUE TITLE
Massnahme: Felder für Projekt Ackerbegleitflora ergänzen

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#362]
Lieber Alex

Nina Lohri, welche das Projekt Ackerbegleitflora betreut, hätte gerne bei den Massnahmen zwei ergänzende Felder, damit sie ihre Angaben alle in der FloraDB zusammen hat. 
Dies wären:
"Anzahl besammelte Individuen"
"Grösse Herkunftspopulation"
Zu platzieren am besten nach "Herkunftspopulation" oder "Sammeldatum".
Ich habe es auch noch mit Karin Marti besprochen und es ist okay. =)

Liebe Grüsse
Rebecca

**Comment by barbalex** [comment]
Natürlich könnte ich jetzt einfach ein paar Felder ergänzen.

Aber: Strukturanpassungen sind grundlegend. Sie sollten gut durchdacht und dokumentiert sein. 

Sobald die Felder allen zur Verfügung stehen, kann niemand verhindern, dass beide Projekte diese Felder benutzen. Mit entsprechenden Folgen für beide Projekte.

Es ist schön, dass für das Projekt Ackerbegleitflora apflora bisher unverändert nutzbringend nutzen kann. Aber wenn wir anfangen, die Datenstruktur von apflora nach den Bedürfnissen des Projekts Ackerbegleitflora anzupassen, sollten wir vorgängig mit mehr Übersicht planen.

Für apflora wurde und wird viel Aufwand getrieben, um die Datenstruktur an die Bedürfnisse des Projekts anzupassen. Es wäre in meinen Augen falsch, die Datenstruktur zu ändern, ohne im Projekt Ackerbegleitflora denselben Aufwand zu treiben.

Meiner Meinung nach sollten wir vorgängig abklären und dokumentieren:
- Wofür das Projekt Ackerbegleitflora apflora benutzt (Ziele)
- Welche Datenstruktur für das Projekt Ackerbegleitflora heute korrekt wäre und
- Wie sich das Projekt künftig entwickeln könnte (Massnahmen)
- Ob mit diesem erweiterten Verständnis die Kombination der beiden Projekte sinnvoll ist und was das bedeuten würde (Synergien, Konflikte und Risiken)
- Falls der Aufwand relevant wird (was diese zwei Felder allein noch nicht wären): wie der Auftraggeber, die FNS, dazu steht (ich nehme an, sie ist auch Auftraggeber für die Ackerbegleitflora?)

Ich glaube, eine erste Übersicht, welche im optimalen Fall schon alles oben erwähnte abdecken könnte, könnten wir an einer Sitzung erstellen:
- Nina oder wer immer vom Projekt Ackerbegleitflora das machen soll erklärt mir Ziele und Massnahmen des Projekts sowie aktuelle Abläufe v.a. bezüglich Daten und Berichten
- Ich versuche, entsprechend diesem Modell die für mich für ihren Zweck optimale Datenstruktur zu skizzieren. Und Abläufe/Berichte. Und vergleiche mit apflora.
- Wir überlegen das weitere Vorgehen. Wobei die direkte unbürokratische Ergänzung dieser zwei Felder eine Möglichkeit ist, falls sich die Synergien als hoch und die Konflikte als klein erweisen. Aber jedenfalls mit einer Seite in der Dokumentation von apflora, welche die wichtigen Punkte erklärt und aus der man ableiten kann, was immer wir nun umsetzen
- Den Aufwand muss ich natürlich über den bestehenden Auftrag 2020 abwickeln

**Comment by kmarti** [comment]
Lieber Alex

Danke für Deine Ueberlegungen.

Wir können dies gerne zusammen mit weiteren zu besprechenden Punkten (Anpassung Jahresbericht, ..) bei einer nächsten Besprechung (Umsetzung Jahresplanung FloraDB) gemeinsam anschauen, aber vorerst ohne Vertretung des Projektes Ackerbegleitflora.

Herzliche Grüsse

Karin

--------------------------------
Karin Marti
Dr.sc.nat.ETH
topos Marti & Müller AG
Idastrasse 24
8003 Zürich
marti@toposmm.ch<mailto:marti@toposmm.ch>
Tel. 044 451 52 55


Von: Alexander Gabriel <notifications@github.com>
Antworten an: barbalex/apf2 <reply@reply.github.com>
Datum: Montag, 2. März 2020 um 13:16
An: barbalex/apf2 <apf2@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [barbalex/apf2] Massnahme: ergänzende Felder (#362)


Natürlich könnte ich jetzt einfach ein paar Felder ergänzen.

Aber: Strukturanpassungen sind grundlegend. Sie sollten gut durchdacht und dokumentiert sein.

Sobald die Felder allen zur Verfügung stehen, kann niemand verhindern, dass beide Projekte diese Felder benutzen. Mit entsprechenden Folgen für beide Projekte.

Es ist schön, dass für das Projekt Ackerbegleitflora apflora bisher unverändert nutzbringend nutzen kann. Aber wenn wir anfangen, die Datenstruktur von apflora nach den Bedürfnissen des Projekts Ackerbegleitflora anzupassen, sollten wir vorgängig mit mehr Übersicht planen.

Für apflora wurde und wird viel Aufwand getrieben, um die Datenstruktur an die Bedürfnisse des Projekts anzupassen. Es wäre in meinen Augen falsch, die Datenstruktur zu ändern, ohne im Projekt Ackerbegleitflora denselben Aufwand zu treiben.

Meiner Meinung nach sollten wir vorgängig abklären und dokumentieren:

  *   Wofür das Projekt Ackerbegleitflora apflora benutzt (Ziele)
  *   Welche Datenstruktur für das Projekt Ackerbegleitflora heute korrekt wäre und
  *   Wie sich das Projekt künftig entwickeln könnte (Massnahmen)
  *   Ob mit diesem erweiterten Verständnis die Kombination der beiden Projekte sinnvoll ist und was das bedeuten würde (Synergien, Konflikte und Risiken)
  *   Falls der Aufwand relevant wird (was diese zwei Felder allein noch nicht wären): wie der Auftraggeber, die FNS, dazu steht (ich nehme an, sie ist auch Auftraggeber für die Ackerbegleitflora?)

Ich glaube, eine erste Übersicht, welche im optimalen Fall schon alles oben erwähnte abdecken könnte, könnten wir an einer Sitzung erstellen:

  *   Nina oder wer immer vom Projekt Ackerbegleitflora das machen soll erklärt mir Ziele und Massnahmen des Projekts sowie aktuelle Abläufe v.a. bezüglich Daten und Berichten
  *   Ich versuche, entsprechend diesem Modell die für mich für ihren Zweck optimale Datenstruktur zu skizzieren. Und Abläufe/Berichte. Und vergleiche mit apflora.
  *   Wir überlegen das weitere Vorgehen. Wobei die direkte unbürokratische Ergänzung dieser zwei Felder eine Möglichkeit ist, falls sich die Synergien als hoch und die Konflikte als klein erweisen. Aber jedenfalls mit einer Seite in der Dokumentation von apflora, welche die wichtigen Punkte erklärt und aus der man ableiten kann, was immer wir nun umsetzen
  *   Den Aufwand muss ich natürlich über den bestehenden Auftrag 2020 abwickeln

**Comment by rebeccakurz** [comment]
Hallo Alex

Wir haben diesen Issue nochmals zusammen angeschaut (Karin, Jasmin und ich) und sind zu dem Schluss gekommen, dass ein ergänzendes Feld bei der Massnahme auch für das APFlora-Projekt (nicht nur für das Ackerbegleitflora-Projekt) Mehrwert bringt. Um die genetische Vielfalt der angesiedelten Populationen abschätzen zu können, ist es wichtig zu wissen, von wievielen Individuen das gesammelte Saatgut stammt.
Daher möchten wir gerne ein zusätzliches Feld bei den Massnahmen einfügen: "Anzahl besammelte Individuen der Herkunftspopulation"
Die Grösse der Herkunftspopulation soll nicht bei den Massnahmen eingefügt werden, diese Zahl kann aus den EKs entnommen werden. 
Könntest du dieses Feld erstellen? Danke!

**Comment by barbalex** [comment]
Ja, kann ich.

In vermehrung.ch haben wir dasselbe Anliegen.

Was ihr hier vorschlägt, entspricht dort dem Feld "von Anzahl Individuen" bei Sammlungen und Lieferungen.

Euer Ziel ist hier genau wie bei den Kulturen in vermehrung.ch:

> Um die genetische Vielfalt der angesiedelten Populationen abschätzen zu können, ist es wichtig zu wissen, von wievielen Individuen das gesammelte Saatgut stammt

Will man auf Ebene TPop oder Pop die Übersicht über die genetische Vielfalt haben, müsste man nun alle Massnahmen auswerten. Von Hand ist das aufwändig und unübersichtlich.

Es gibt noch ein zusätzliches Problem: Wenn es mehrere Ansiedlungen/Ansaaten gibt, gibt es dann Überschneidungen zwischen den Werten, welche im Feld "von Anzahl Individuen" erfasst wurden? Das wäre z.B. systematisch der Fall, wenn Pflanzen/Samen aus der Vermehrung verwendet würden. Weil dieselbe Kultur ihre genetische Grundlage mit der Zeit nicht oder nur teilweise ändert. Ob es solche Überschneidungen kann man nachträglich schlechter beurteilen. Am besten wäre es wohl, wenn es in dem Moment beurteilt wird, in dem die "von Anzahl Individuen" der Massnahme erfasst wird.

Aus diesem Grund gibt es in vermehrung.ch nicht nur in Sammlungen und Lieferungen das Feld "von Anzahl Individuen". Sondern auch in der Kultur.

Das Pendant dazu wäre, wenn in apflora.ch bei angesiedelten TPop und Pop solche Felder enthalten wären. 

Diese Felder nützen natürlich nur etwas, wenn sie konsequent nachgeführt werden.

Das einfach als Input. Ich ergänze jetzt das Feld in der Massnahme.

**Comment by barbalex** [comment]
Das neue Feld ist in Version 1.42.1 enthalten
