### ISSUE TITLE
Artenbild Tulipa sylvestris

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#363]
Hoi Alex 
Ich sende dir noch ein Bild von Tulipa sylvestris, dass du gerne als Artbild in der FloraDB einfügen könntest (bei den Frewilligen-Kontrollen).
Danke!
[tulipa_sylvestris.pdf](https://github.com/barbalex/apf2/files/4274944/tulipa_sylvestris.pdf)

**Comment by barbalex** [comment]
Ist in v1.22.20 enthalten
