### ISSUE TITLE
EK-Planung: Koordinaten hinzufügen

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#364]
Dieser Wunsch wurde von uns glaube ich schon einmal geäussert, aber er ist leider nicht auf unserer Wunschliste. 
Könntest du bitte die Koordinaten der Teilpopulationen in der EK-Planung ergänzen?
Wenn es möglich wäre, dann gerne möglichst zeitnah.
Vielen Dank!

**Comment by rebeccakurz** [comment]
Könntest du dich diesem Issue bitte noch annehmen? Vielen Dank!

**Comment by barbalex** [comment]
Kann ich. Aber: Es gibt auch einen Nachteil.

Dieses komplexe Formular besteht aus vier Teilen. Für die Diskussion sind zwei wesentlich:
- Der **TPop-Block**: das ist der linke Teil, der Infos von TPop, Pop und AP anzeigt
- Der **EK-Planungs-Block**: das ist rechte Teil, der die EK-Planung anzeigt und in dem man planen kann

Die grossen zwei Schwächen dieses Formulars sind: 
1. Wenn der TPop-Block zu breit ist, Fällt die ganze Funktionalität auseinander. Hat es keinen Platz mehr für den EK-Planungs-Block, funktioniert das Formular technisch nicht mehr
2. Es geht eigentlich um EK-Planung. Bloss: Selbst auf meinem riesigen 32-Zoll Bildschirm mit einer Auflösung von 3840x2160px nimmt der TPop-Block bei normaler 100% Bildschirm-Vergrösserung heute schon ca. 66% der Bildschirmbreite ein. 

Auf weniger grossen Bildschirmen besteht also eine grosse Gefahr, dass der TPop-Block dem EK-Planungs-Block _allen_ Platz wegnimmt. Mit der Folge, dass die Benutzerin nicht arbeiten kann. Ausser, sie reduziert die Anzahl im TPop-Block angezeigter Felder mit Hilfe der Schaltfläche "Felder wählen". Ist sie aber keine erfahrene Benutzerin, wird sie das nicht wissen und nicht arbeiten können.

Auch Benutzerinnen mit grossen, hoch aufgelösten Bildschirmen müssten im Grunde genommen die Anzahl angezeigter Felder aus dem TPop-Block reduzieren, um produktiv arbeiten zu können - denn nur so werden genug Jahres-Spalten im EK-Planungs-Block angezeigt.

Dieses Problem wird nochmals stark verschärft, wenn nochmals zwei Felder mehr angezeigt werden sollen. Dann wird der TPop-Block auf meinem riesigen Bildschirm schätzungsweise 80% der Bildschirmbreite einnehmen.

Ich muss also einen neuen Ansatz suchen, um das Formular für nicht sehr erfahrene Benutzerinnen brauchbar zu machen, ohne zu riskieren, dass sie gar nicht arbeiten können.

**Ich schlage vor, das Formular im Standard so zu konfigurieren, dass im TPop-Block nur ein Minimum an Felder angezeigt wird**. Erfahrene Benutzerinnen und solche, welche die Funktion finden, werden einfach mehr einblenden, wenn sie sie brauchen. apflora erinnert sich an diese Einstellung, d.h. die Benutzerin muss das nur ein mal machen. Niemand riskiert, gar nicht arbeiten zu können.

Daher werde ich - wenn von euch kein Protest kommt - die standardmässig angezeigten Felder im TPop-Block reduzieren auf:
- diejenigen, welche eine TPop eindeutig bezeichnen:
  - AP
  - Pop Nr
  - TPop Nr
- diejenigen, welche bearbeitet werden können:
  - EK Frequenz
  - EK Frequenz Startjahr
  - EK Frequenz abweichend

Selbst in dieser Einstellung werden bei mir im Fall von Allium angulosum (der erste Art, die ich jetzt zufällig gewählt habe) bei ihrem ersten Aufruf nur die Jahre bis 2030 angezeigt. Weil die erste EK schon 1994 stattfand.

**Comment by rebeccakurz** [comment]
Das finde ich einen sehr guten Vorschlag! Vielen Dank!

**Comment by barbalex** [comment]
Ist in v1.28.0 implementiert.

Wenn du die App zuvor schon benutzt hast, hat sie die angezeigten Felder gespeichert. Sie sollte also nicht plötzlich weniger Felder anzeigen.

Bei neuen Benutzern werden aber nur noch die minimalen Felder angezeigt.

**Comment by rebeccakurz** [comment]
Hoi Alex 

Vielen Dank! So ist die Anwendung viel übersichtlicher. 
Zu deiner Bemerkung, dass die App die angezeigten Felder gespeichert hat, wenn ich sie schon vorher benutzt habe: Das ist leider nicht so... Ich öffne dazu einen neuen Issue (#374 )
