### ISSUE TITLE
Artenbild Potamogeton coloratus

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#365]
Hoi Alex

Habe noch ein Bild von Potamogeton für die EKF- Formulare gefunden. 

Vielen Dank fürs Einfügen!
![potcol](https://user-images.githubusercontent.com/30288503/76532524-040bf600-6477-11ea-9307-9f351529e54c.png)

**Comment by barbalex** [comment]
Diese Art hat aber schon ein Bild
