### ISSUE TITLE
EKF-Formulare erzeugen: erzeugt ev. auch in nicht benötigten Jahren Formulare

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#366]
Hoi Alex
Bei der EK-Planung gibt es ja die EK-Frequenz "F2": EKF alle zwei Jahre. Je nach Startjahr das gesetzt ist, wird dann eine EKF in den geraden oder ungeraden Jahren geplant.
<img width="1986" alt="Bildschirmfoto 2020-03-18 um 11 25 56" src="https://user-images.githubusercontent.com/30288503/76951815-8cbde280-690c-11ea-8cd5-e5b6a2099f71.png">
Wenn ich nun aber der EK dieser Teilpopulation (Bsp: Thalictrum galioides, TPop 48.11) bereits einen EKF-Kontrolleur zugeordnet habe, dann zeigt es mir beim Benutzer an, dass ich "(Fehlende) EKF-Formulare für 2020 erzeugen" kann. Dann werden auch für die Teilpopulationen, die nur alle zwei Jahre eine Kontrolle geplant haben (und in diesem Beispiel wäre die Kontrolle erst 2021) EKF-Formulare erstellt. 
<img width="1614" alt="Bildschirmfoto 2020-03-18 um 11 36 12" src="https://user-images.githubusercontent.com/30288503/76952518-83814580-690d-11ea-8ccb-a65017c305fe.png">
<img width="1753" alt="Bildschirmfoto 2020-03-18 um 11 42 08" src="https://user-images.githubusercontent.com/30288503/76952527-867c3600-690d-11ea-834e-d4b6e79541d4.png">
Könntest du dir das bei Gelegenheit mal anschauen?

Vielen Dank und ich hoffe deiner Familie und dir geht es gut!
Liebe Grüsse
Rebecca

**Comment by barbalex** [comment]
Ich versuche, zu verstehen, wo der Fehler bzw. das Problem liegt: 

Ist es:

> Wenn ich nun aber der EK dieser Teilpopulation (Bsp: Thalictrum galioides, TPop 48.11) bereits einen EKF-Kontrolleur zugeordnet habe, dann zeigt es mir beim Benutzer an, dass ich "(Fehlende) EKF-Formulare für 2020 erzeugen" kann.

oder:

> Dann werden auch für die Teilpopulationen, die nur alle zwei Jahre eine Kontrolle geplant haben (und in diesem Beispiel wäre die Kontrolle erst 2021) EKF-Formulare erstellt

bzw. ist das eigentliche Problem, dass die Funktion "(Fehlende) EKF-Formulare für 2020 erzeugen" offenbar auch ein Formular erzeugt, wenn es in diesem Jahr nicht benötigt wird bzw. erst in einem späteren Jahr nötig wäre?

**Comment by rebeccakurz** [comment]
-bzw. ist das eigentliche Problem, dass die Funktion "(Fehlende) EKF-Formulare für 2020 erzeugen" offenbar auch ein Formular erzeugt, wenn es in diesem Jahr nicht benötigt wird bzw. erst in einem späteren Jahr nötig wäre?
Ich denke so könnte man es formulieren. Ist aber schon etwas lange her, kann sein, dass das Problem inzwischen nicht mehr nachvollziehbar ist.

**Comment by barbalex** [comment]
schliesse diesen Issue mangels Aktivität
