### ISSUE TITLE
Auswertung von Eigenschaften von AP, Pop und TPop mit der Zeit

### ISSUE THREAD

**Issue by barbalex** [barbalex/apf2#367]
## Wunsch

Die Daten in apflora werden je länger je intensiver ausgewertet. 

Beispiele:

- Unmittelbar bevor steht die grafische Darstellung der zeitlichen Änderung (von Jahr zu Jahr) der Anzahl Populationen und ihrer Grösse gemäss ziel-relevanter Zähleinheit, differenziert nach Status.
- Der Jahresbericht soll ergänzt werden um "Differenzen zum Vorjahr": "die Anzahl Populationen, die es gegenüber dem Vorjahr zusätzlich oder weniger hat (oder 0, falls stabil), bei den ursprünglichen, bei den angesiedelten Pop und im Total".
- Die Priorisierung von AP-Arten ist abhängig von der Zu- oder Abnahme der Anzahl ursprünglicher Populationen (Spalte K) und der Anzahl Populationen total (ursp. und angesiedelt, Spalte L) und der Zielerreichung (nicht erfolgreich bis sehr erfolgreich, Spalte G)

## Aktuelle Situation

Das Problem ist, dass die Daten von AP, Pop und TPop bei jeder Aktualisierung überschrieben werden. Die Veränderung mit der Zeit ist so nicht auswertbar.

Mit der aktuellen Datenstruktur ist es wohl möglich, nachzuvollziehen, in welchen Jahren Populationen geschaffen wurden. Das heisst: **In welchem Jahr gab es wie viele Populationen**. Wenn ihr es zuverlässig nachführt, kann das Feld "Bekannt seit" dafür verwendet werden. Davon gehe ich aus. Bloss: Wenn ihr eine Population entfernt, verschwindet sie dann auch in den Vorjahren aus der Statistik 🤔. Aber das sollte vermutlich nicht passieren?

Hingegen ist es nicht möglich, zu **wissen, wann Stati geändert wurden**. Bzw. in welchem Jahr eine Population welchen Status hatte.

### Variante 1: Minimal

Man könnte die Summen pro AP aufwändig von Hand aus den Berichten zusammentragen.
Damit das halb-automatisch möglich würde, müssten diese Informationen jedes Jahr zum Zeitpunkt der Berichterstellung in eine Tabelle geschrieben werden. Voll-automatisch ist das nicht möglich, weil ihr bestimmen müsst, wann diese Auswertung passieren soll.

Auch müsstet ihr definieren, wie es dargestellt wird, wenn 2 Populationen neu geschaffen werden und eine entfernt wird (bzw. wenn das auf Ebene Status geschieht). Ist das nun +1? Ich nehme es an.

Es bedingt also:
- eine neue Tabelle, welche die Summen pro AP pro Status-Kategorie und Jahr aufnimmt
- eine neue Anfüge-Abfrage
- einen Befehl irgendwo in der Benutzeroberfläche, mit dem man die Abfrage auslösen kann und das Jahr wählen kann, für welches die Daten gelten sollen (weil ja wohl meist das Vorjahr gewählt sein soll, die Abfrage aber im Folgejahr ausgeführt wird, wenn der Bericht verfasst wird). Alternative: Ich mache das jeweils für euch, wenn du es mir mitteilst
- Falls Daten für 2018 oder gar früher erscheinen sollten: Deren Import aus einer Excel-Vorlage, die ich euch gebe, in welche ihr die Daten für 2018 zuvor manuell eintragen müsst

Aber ich bin überzeugt, wenn wir jetzt beginnen, zeitliche Verläufe darzustellen, brauchen wir eine robuste Methode um die Daten dafür bereitzustellen. Deshalb zwei weitere Vorschläge:

### Variante 2: Daten historisieren und nachträglich auswerten

Wir könnten wichtige Tabellen historisieren, d.h.:
- Wenn eine Benutzerin ein Formular verlässt und der Datensatz geändert wurde, schreibt apflora den Datensatz in eine zusätzliche Tabelle mit derselben Struktur plus einem Zeitstempel, welcher den Zeitpunkt der Änderung dokumentiert (= Historie)
- Die Historien werden im Normalfall nicht geladen. Die Anwendung wird also nur beim Verlassen eines geänderten Formulars durch den zusätzlichen Schreibvorgang etwas gebremst
- Wenn das nützlich wäre, könnte im Formular die Möglichkeit geschaffen werden, die Historien anzuzeigen/aufzulisten. Dann würden nur die Historien des betreffenden Datensatzes geladen, was gut machbar ist
- Abfragen könnten Historien verwenden, um die Änderung wesentlicher Felder wie z.B. Status oder AP-Bearbeitungsstand auszulesen. Das ist anspruchsvoll und rechenintensiv (auf dem Server). Aber ich glaube, es sollte recht gut klappen. PostgreSQL hat enorme Fortschritte gemacht in den letzten drei Jahren
- Die Datenmenge und ev. auch CPU/RAM-Ansprüche von apflora werden Server-seitig langfristig deutlich ansteigen. Das wirkt sich auf die Betriebskosten aus (einige Dutzend bis mittelfristig maximal 200 Franken im Jahr)
- Um das für AP, Pop und TPop umzusetzen, brauche ich wohl (ohne spezielle Auswertungs-Abfragen) ca. drei Tage
- Wenn ich dann noch den Jahres-Bericht so anpasse, dass er die gewünschten Werte liefert, gibt das nochmals einen Tag Arbeit. Diese Werte erscheinen aber erst mit einem Jahr Verspätung, d.h. wenn wir das bald umsetzen ist es für 2018 noch nicht möglich, Daten anzuzeigen. Ab 2020 könnten Daten für 2019 angezeigt werden
- Historien früherer Jahre können aus Sicherungen importiert werden. Das kann wegen struktureller Änderungen etwas erschwert sein. Aber mit ein paar Stunden mehr Aufwand sollten Änderungen der Anzahl Population und ihres Status über mehrere Jahre zurück ausgewertet werden können 

Diese Lösung liefert Mehrwert gegenüber der minimalen Variante 1: 
1. Man kann Historien nachschauen
1. Aus diesen Historien können auch Datensätze bzw. unerwünschte Änderungen einzelner Felder wieder hergestellt werden. Wenn es dafür eine Benutzeroberfläche (z.B. eigenes Register) gibt, auch direkt von euch
1. Bei Bedarf könnten später auch Änderungen anderer Felder ausgewertet werden (detaillierte Änderungen von Stati, AP-Bearbeitungsstand, AP-Umsetzungsstand, Status-Änderungen in Zeit-Achsen für Aktionspläne, Populationen und Teilpopulationen, was immer euch oder der FNS einfällt). Und zwar mit viel weniger Aufwand und ohne die Komplexität der Anwendung zu erhöhen, verglichen mit der minimalen im letzten Mail beschriebenen Methode
1. Beim Benutzer und euch entsteht kein Mehraufwand bei der Erfassung und es muss niemand daran denken, zum Zeitpunkt X eine Anfüge-abfrage auszuführen. **Vermutlich sollten wir beim Jahresbericht erfassen, an welchem Datum er offiziell erstellt wurde**, damit die Zahlen in den Auswertungen mit denjenigen in den Berichten übereinstimmen
1. Sie ist erweiterbar auf weitere Tabellen, falls erwünscht (wobei Pop-Berichte, TPop-Berichte, Kontrollen und Massnahmen sowieso in dieser Struktur vorliegen, es dort also weniger nützt)
1. Aufgrund der Erweiterbarkeit könnten wir auch mit dem Minimum anfangen, d.h. mit den Populationen
1. Theoretisch wäre es möglich, diese Methode noch einen Schritt weiter auszubauen: Es könnten frühere Zustände gerechnet werden. Z.B. könnten Berichte für frühere Jahre erstellt werden, welche nicht durch Hinzufügen/Löschen von Populationen/Teilpopulationen beeinflusst werden. Das wäre dann so etwas wie eine Eier legende Wollmilchsau mit Zeitmaschine...

Nachteilig ist, dass der Erst-Aufwand grösser ist.

### Variante 3: Daten nur zum Zeitpunkt des Jahresberichts historisieren

Historisieren könnte man auch bloss ein mal im Jahr: Wenn der Jahresbericht erzeugt wird. 
- Das würde die Sache stark vereinfachen und auf den Punkt bringen
- Wenig komplex ist fast immer optimal
- Es würde vermutlich dem entsprechen, was man will: Den Zustand pro Jahr jeweils zum Zeitpunkt des Jahresberichts darstellen. Plus den aktuellen Zustand
- Man kann wiederum die Veränderung aller Felder auswerten...
- und die Daten für Vorjahre aus Sicherungen importieren

Man könnte keine Zeitpunkte zwischen Jahresberichten darstellen und die Daten nicht für die Wiederherstellung früherer Zustände benutzen. Dafür wäre diese Lösung vergleichbar simpel wie Variante 1.

### Wahl

Wenn 1 Zustand pro Jahr (beim Erstellen des Jahresberichts) ausgewertet werden soll, steht für mich ganz klar Variante 3 im Vordergrund. Die zusätzliche Komplexität von Variante 2 lohnt sich dann nicht.

Sollten Zustände zwischen den Jahresberichten ausgewertet werden können, müsste wohl Variante 2 gewählt werden.

Die alles entscheidende Frage ist: **Was soll wie oft ausgewertet werden?** 
Es ist wichtig, dass das jetzt möglichst gut überlegt wird.

**Comment by kmarti** [comment]
Eigentlich bin ich von einer Minimallösung wie Variante 1 ausgegangen. Variante 3 ist aber viel besser. Und Variante 2 ist nicht nötig. Die Auswertung ist wirklich nur 1x im Jahr notwendig, wenn der Jahresbericht fertig erstellt ist, so dass Veränderungen in Jahresabständen aufgezeigt werden können. 

Auswertungen dazwischen sollte es wirklich nicht geben. Höchstens weitere Eigenschaften, die in Jahresabständen ausgewertet werden sollen. Hier schon ein Zusatzwunsch: Es wäre wünschbar, dass neben der Anzahl ursprünglicher und angesiedelter Populationen und Teilpopulationen auch die Anzahl der Individuen ausgewertet werden könnte (insgesamt über alle Populationen einer Art oder pro Population) für die grafische Darstellung im Jahresbericht.

**Comment by kmarti** [comment]
Was mir aber nicht klar ist bei Variante 3, wie die Daten aus früheren Jahren (seit Beginn Umsetzung AP) mitausgewertet werden können, wenn im Jahresbericht die Zu/Abnahme der Pop/Teilpop grafisch dargestellt werden soll.

**Comment by barbalex** [comment]
> Die Auswertung ist wirklich nur 1x im Jahr notwendig, wenn der Jahresbericht fertig erstellt ist, so dass Veränderungen in Jahresabständen aufgezeigt werden können

Super, das ist ein wichtiger Eckpfeiler, der die Sache stark vereinfacht

> Höchstens weitere Eigenschaften, die in Jahresabständen ausgewertet werden sollen

Das schliesst Variante 1 aus und ist mit Variante 3 machbar, soweit diese Daten regelmässig erhoben wurden.

> Es wäre wünschbar, dass auch die **Anzahl der Individuen** ausgewertet werden könnte (insgesamt über alle Populationen einer Art oder pro Population)

Ich gehe davon aus, dass das die ziel-relevante Einheit sein wird. **Stimmt das?**

> Was mir aber nicht klar ist bei Variante 3, wie die Daten aus früheren Jahren (seit Beginn Umsetzung AP) mitausgewertet werden können, wenn im Jahresbericht die Zu/Abnahme der Pop/Teilpop grafisch dargestellt werden soll

Ich könnte die entsprechenden Daten aus Sicherungen importieren, die ungefähr zum Zeitpunkt des Jahresberichts erstellt wurden. Das wäre wohl ungefähr Ende Februar, **stimmt das**?

**Comment by kmarti** [comment]
- Ja die Anzahl Individuen sind die Anzahl ziel-relevante Einheiten
- Ja, Ende Februar ist ok

**Comment by barbalex** [comment]
Alles klar. Ich werde also umsetzen:

Variante 3: Daten nur zum Zeitpunkt des Jahresberichts historisieren

- Es gibt drei neue Tabellen:
  - `ap_history`
  - `pop_history`
  - `tpop_history`
- Diese Tabellen haben dieselbe Struktur wie die jeweilige "Mutter"-Tabelle. Plus ein Jahr
- Jahr und ap/pop/tpop-id sind zusammen eindeutig
- Es gibt eine Funktion, um:
  - alle aktuellen ap/pop/tpop in diese Tabellen zu kopieren
  - und mit dem **VOR**-Jahr zu ergänzen (weil man das wohl gegen Ende Februar des Folge-Jahrs macht)
- In der Tabelle `apberuebersicht` gibt es ein neues Feld: history_date. Es wird von apflora gesetzt, wenn obige Funktion ausgeführt wird
- Im Formular "AP-Berichte" > "AP-Bericht Jahresübersicht"
  - Gibt es einen neuen Befehl "AP, Pop und TPop des Vorjahrs für den Jahresbericht historisieren". Dort wird auch erklärt, dass dies für die Auswertungen der Veränderung von AP, Pop und TPop mit den Jahren essentiell ist
  - Dieser Befehl kann nur von Managern ausgeführt werden
  - Er kann nur ein Mal durchgeführt werden (sollte er ein mal zu früh ausgeführt worden sein und wiederholt werden müssen, müsstet ihr mich darum bitten)
  - Solltet ihr einmal vergessen, diesen Befehl im richtigen Moment auszuführen, müsste ich mit Daten aus Sicherungen dies nachträglich manuell machen
  - Sobald er ausgeführt wurde, sieht man die Daten dieses Jahresberichts in den Auswertungen
- Ich importiere Daten aus Sicherungen früherer Jahre, die gegen Ende Februar stattfanden, in die historien-Tabellen. Ich muss schauen, wie weit zurück das wie gut geht, weil z.T. ev. strukturelle Anpassungen stattfanden. Kann sein, dass ich da nochmals rückfrage. Je nach vertretbarem Aufwand, versuche ich das so weit zurück auszuführen, wie die Stati vernünftig mit den aktuell verwendeten verglichen werden können

Das Ganze hat _keine_ nachteiligen Wirkungen auf die Daten-Erfassung im Alltag, weil der entscheidende Vorgang nur ein mal im Jahr geschieht. Und es stresst den Server nicht besonders (die Daten aus den Historien werden im Rahmen der Auswertungen abgefragt, wo entsprechende Daten angezeigt werden. Die Abfragen sind nicht speziell aufwändig).

**Comment by barbalex** [comment]
@kmarti Die Schaltfläche, um zu historisieren ist geschaffen: https://apflora.ch/Daten/Projekte/e57f56f4-4376-11e8-ab21-4314b6749d13/AP-Berichte/35bf32ee-0bb1-11ea-848a-8f166cb917a3
Du kannst also jederzeit die Daten für 2019 historisieren.

Oder willst du lieber, dass ich sie aus einer Sicherung von Ende Februar nehme?

**Comment by barbalex** [comment]
Dokumentation Import:

- ID's haben 2017 geändert (Integer > GUID)
  Daher müssen alle ID's in allen Fremdschlüsseln nachgeführt werden?!
- Koordinaten-System hat 2019 geändert. Daher können Koordinaten nicht importiert werden

**Comment by barbalex** [comment]
@kmarti 
Die Daten aus früheren Jahren sind jetzt  importiert:

#### ap
| year | count |
| ---- | ----- |
| 2014 | 471   |
| 2015 | 524   |
| 2016 | 561   |
| 2017 | 572   |
| 2018 | 573   |

#### pop
| year | count |
| ---- | ----- |
| 2014 | 4557  |
| 2015 | 5208  |
| 2016 | 5610  |
| 2017 | 5932  |
| 2018 | 6414  |

#### tpop
| year | count  |
| ---- | ------ |
| 2014 |  7791  |
| 2015 |  9155  |
| 2016 | 10116  |
| 2017 | 10930  |
| 2018 | 11975  |

Ich schliesse diesen Issue. 

Es geht weiter mit der grafischen Darstellung 😃
