### ISSUE TITLE
Auswertung für Priorisierungsliste AP-Arten

### ISSUE THREAD

**Issue by barbalex** [barbalex/apf2#368]
@kmarti @rebeccakurz 

In `Wunschliste_APFlora_DB_20200204.xlsx` habt ihr notiert:

> Priorisierung ist abhängig von der Zu- oder Abnahme der Anzahl ursprünglicher Populationen (Spalte K) und der Anzahl Populationen total (ursp. und angesiedelt, Spalte L) und der Zielerreichung (nicht erfolgreich   bis sehr erfolgreich, Spalte G).

Für mich ist das noch nicht klar.

Ist es möglich, dass ihr skizziert, wie das Resultat einer solchen Auswertung aussehen könnte?

**Comment by kmarti** [comment]
Wie bei der Auswertung der Jahresberichte (issue 367) wird Ende Februar 2020 pro Art die Anzahl der ursprünglichen Populationen (und die Anzahl der angesiedelten Populationen) und die Anzahl der Populationen total (ursprünglich und angesiedelt) mit den Anzahlen von Februar 2019, also vom Vorjahr verglichen. In einer Tabelle sollen diese Anzahlen aufgezeigt werden und die Differenz zwischen diesen beiden Jahren von Anzahl ursprünglicher Pop resp. Pop total (ursprünglich und angesiedelt) berechnet werden.
In einer weiteren Spalte in dieser Auswertungstabelle soll die Zielerreichung 2020 aus dem Jahresbericht 2020 angegeben werden.
Mit dieser Auswertung kann ich für die Umsetzung 2020 Arten priorisieren, d.h. diese bekommen mehr oder weniger Budget für die Umsetzung. Dazu kann ich die Zahlen aus einer solchen Auswertungstabelle in meine Priorisierungstabelle kopieren. Die weitere Auswertung (Kategorisieren der Zahlen) kann ich dann gut selber machen.

Es geht also um den Vergleich der aktuellen Zahlen aus dem aktuellen Jahresbericht mit den Zahlen vom Vorjahr.

**Comment by barbalex** [comment]
O.k., das reicht glaube ich. Ich mach mal einen Entwurf.

**Comment by barbalex** [comment]
@kmarti Hier mein Entwurf: [v_ap_pop_ek_prio.xlsx](https://github.com/barbalex/apf2/files/4466380/v_ap_pop_ek_prio.xlsx)
Was meinst du?

**Comment by kmarti** [comment]
Im Prinzip ist das so ok. Lieber wäre mir, wenn nur die Aktionsplanarten aufgezeigt werden.

Was mir nicht klar ist, weshalb eine Art mehrfach erscheint. Wahrscheinlich für jedes Berichtsjahr mit den unterschiedlichen Beurteilungen. Aber wie ist die Reihenfolge der Beurteilung? z.B. Anagallis minima war 2019 wenig erfolgreich, 2018 nicht erfolgreich, 2017 nicht erfolgreich. Das stimmt in der Reihenfolge weder von oben nach unten, noch von unten nach oben. 

Dann komme ich zum Teil auf andere Zahlen, wenn ich die Jahresberichte von 2018 und von 2019 konsultiere. So waren die Zahlen bei Aldrovanda 2018: 0/15/15, ebenso 2019: 0/15/15
(und nicht 2/16/18 in beiden Jahren)

Bei Allium angulosum waren die Zahlen 2018: 3/17/20, 2019: 3/17/20 (und nicht 4/17/21 in beiden Jahren)

Bei Campanula cervicaria waren die Zahlen 2018: 4/14/18, 2019: 4/15/19 (und nicht 4/16/20)

Es ist mir nicht klar, woran das liegen könnte...

**Comment by barbalex** [comment]
> Lieber wäre mir, wenn nur die Aktionsplanarten aufgezeigt werden

Kein Problem

> Was mir nicht klar ist, weshalb eine Art mehrfach erscheint

Bloss ein dummer Fehler, der Entstand, als ich am Ende "beurteilung_zuletzt" ergänzt habe 😞 

> Dann komme ich zum Teil auf andere Zahlen, wenn ich die Jahresberichte von 2018 und von 2019 konsultiere. So waren die Zahlen bei Aldrovanda 2018: 0/15/15, ebenso 2019: 0/15/15 (und nicht 2/16/18 in beiden Jahren)

Danke für den konkreten Hinweis. Dem muss ich nachgehen

**Comment by barbalex** [comment]
> Dann komme ich zum Teil auf andere Zahlen

Ich habe vergessen, nur Populationen zu zählen, die mindestens eine Teil-Population haben, welche apber-relevant ist.

Hier die korrigierte Version: 
[ap_pop_ek_prio.xlsx](https://github.com/barbalex/apf2/files/4492975/ap_pop_ek_prio.xlsx)

> Bei Campanula cervicaria waren die Zahlen 2018: 4/14/18, 2019: 4/15/19 (und nicht 4/16/20)

Ich glaube, das war beide Male 4/15/19

**Comment by barbalex** [comment]
Habe diese Liste als Export ergänzt. Wird im nächsten Update vorhanden sein.
Sobald wir die den Zugang für AV einschränken, sehen sie in dieser Liste nur noch ihre Arten.

**Comment by kmarti** [comment]
In der Liste habe ich für das Jahr 2018 sehr viele Abweichungen gegenüber den Zahlen im Jahresbericht festgestellt:

im Jahr 2018 z.B.
Blackstonia acuminata 0/5/5 nicht 0/4/4
Campanula cervicaria 4/14/18 nicht 4/15/19 
Carex hartmanii 6/18/24 nicht 6/19/25
Filipendula vulgaris 1/57/58 nicht 1/61/62
Gagea pratensis 19/9/28 nicht 20/10/30
Gagea villosa 16/4/20 nicht 16/6/22
Gladiolus palustris 1/6/7 nicht 1/7/8
Gratiola officinalis 1/38/39 nicht 1/44/45
und weitere Abweichungen....

im Jahr 2019 gibt es nur drei Abweichungen gegenüber dem Jahresbericht, bei den übrigen Arten stimmen die Zahlen.
Gagea pratensis 18/10/28 und nicht 20/10/30
Ophrys araneola 0/9/9 und nicht 0/10/10
Pulsatilla vulgaris 10/55/65 und nicht 10/56/66

Die Zahlen aus dem Jahr 2019 sind zusammen mit den neuen Zahlen aus dem Jahr 2020 wichtig für die Priorisierung 2021. Die Zahlen von 2018 müssen also nicht unbedingt bereinigt werden.

**Comment by rebeccakurz** [comment]
Hoi Alex
Konntest du diese Abweichungen im Jahr 2019 korrigieren, bzw. den Grund herausfinden?
LG

**Comment by barbalex** [comment]
Bevor ich mich sehr aufwändig in den Code stürze, um darin Fehler zu suchen:

Daten können recht einfach abweichen, wenn sie seither geändert wurden. Das würde auch erklären, wieso es bei älteren Daten offenbar mehr Abweichungen gibt als bei neueren.

Ihr kennt die Daten und deren Bearbeitung besser. Darum meine Fragen an euch:

> gegenüber den Zahlen im Jahresbericht

- Ist das ein gleichzeitig mit der Auswertung erstellter Jahresbericht? 
- Oder meint ihr den bzw. einen Jahresbericht, der früher erstellt wurde?
- Habt ihr geprüft, ob die Zahlen der Auswertung stimmen? Könnt ihr das bitte machen?

**Comment by kmarti** [comment]
Ich werde mich demnächst nochmals genauer mit diesen Zahlen befassen.

**Comment by kmarti** [comment]
Es könnte sein, dass bei den drei Arten Gage pratensis, Ophrys araneola und Pulsatilla vulgaris für 2019 noch Änderungen gemacht wurden. Es sind ja nur kleine Abweichungen.

In der "Auswertung" in der Flora-Datenbank stimmen die Zahlen nicht so ganz:
Aldrovanda vesiculosa zeigt in der Auswertung für 2019 2 ursprüngliche Pop an und 16 angesiedelt aktuelle Pop,  es gibt aber keine ursprüngliche Pop., insgesamt sind es 2019 15 angesiedelte Pop (16 erloschene Pop ist korrekt)
Anagallis minima zeigt in der Auswertung für 2019 11 erloschene Pop an, es gibt aber gemäss Jahresbericht 2019 nur 4 erloschene (nach AP angesiedelt!!)
Allium angulosum hat nur 3 ursprüngliche Pop und nicht vier wie In der Auswertung für 2019 angezeigt, 14 angesiedelte aktuelle Pop und 4 Ansaatversuche ist korrekt, aber die Anzahl erloschene Pop stimmt nicht.
Aristolochia clematitis: Es gibt 1 ursprüngliche Pop und nicht drei wie in der Auswertung für 2019. 30 angesiedelte aktuelle Pop ist korrekt. Ursprünglich erloschen sind 3 (nach 1950) und nicht 21. Angesiedelt und erloschen sind 0 und nicht 3. Ansaatversuche 0 ist korrekt.
...

**Comment by barbalex** [comment]
Zoom vom 26.1.2021:
- Zahlen Vorjahr sind gleich wie aktuell
- Karin mailt zwei Excel-Tabellen: Wo sind Zahlen aktuell falsch, Zahlen aus Jahresberichten

**Comment by barbalex** [comment]
Ich schliesse mal diesen Issue, weil die Unterschiede nicht auf der Abfrage beruhen, sondern vermutlich auf veränderten Daten
