### ISSUE TITLE
Export EK-Planung + Auswertung

### ISSUE THREAD

**Issue by barbalex** [barbalex/apf2#369]
@kmarti @rebeccakurz

In Wunschliste_APFlora_DB_20200204.xlsx habt ihr notiert:

> Export über alle Arten (mind. Enthalten: Art, Tpop, EK-Abrechnungs-Typ (Budget), EK-Frequenz, Planung im aktuellen Jahr) + Auswertung: Anzahl geplante Eks im aktuellen Jahr pro Art und pro   EK-Abrechnungs-Typ

Das ist mir noch zuwenig klar.

Sind das zwei unterschiedliche Produkte?
- ein Export mit: 
  - einer Zeile pro Art?
  - eher einer Zeile pro TPop, wie im Formular "EK-Planung"?
  - was heisst dann "Planung im aktuellen Jahr"?
- ein zweiter Export (oder etwas Anderes?), mit
  - einer Zeile pro Kombination von Art und EK-Abrechnungstyp?
  - darin einer Spalte, welche die Anzahl geplante EKs im aktuellen Jahr darstellt?

Was ich wirklich brauche ist für das Produkt oder beide Produkte eine Skizze von euch, wie das Resultat aussehen könnte. Und am besten eine Erklärung dazu, wieso dieses Resultat für euch nützlich ist. Wenn ich verstehe, was wozu genutzt wird, kann ich im optimalen Fall weiter denken und sogar etwas Besseres liefern.

Mein Problem: Etwas aufbauen ist sehr aufwändig, kostet ev. Tage Arbeit. Und wenn danach herauskommt, dass es nicht das Gewünschte ist, wäre das nicht ideal.

**Comment by kmarti** [comment]
Wahrscheinlich ist es besser, wenn dies zwei separate Produkte sind.

1. Die EK-Planung wird gefiltert für ein bestimmtes Jahr (z.B. 2020): TPop mit EK-Plan in 2020 filtern. Diese Tabelle mit einer Zeile pro TPop soll exportiert werden, aber nicht für eine Art sondern für alle AP-Arten in einer Tabelle.

2. Die Daten der Tabelle unter Punkt 1 werden so ausgewertet (in separater Tabelle), dass pro Art die Anzahl der TPop mit EK-Plan in 2020 mit Abrechnungstyp A resp. Abrechnungstyp B berechnet wird.

Diese Auswertung brauche ich, damit ich das Gesamt-Budget für die Erfolgskontrolle im Auge behalten und die Offerten der Artverantwortlichen prüfen kann. In diesen Offerten müssen die Artverantwortlichen die Anzahl der im Jahr 2020 zu überprüfenden TPop mit Abrechnungstyp A resp B für ihre Arten angeben, gemäss ihrer EK-Planung. (Dieses Jahr habe ich für jede Art einzeln die EK-Planung 2020 angeschaut und die Anzahl der EK pro Abrechnungstyp berechnet).

**Comment by barbalex** [comment]
Super, ich _glaube_ dann ist es klar. Melde mich allenfalls wieder, wenn in der Umsetzung Fragen auftauchen.

**Comment by barbalex** [comment]
Nächste Fragen:

> wird gefiltert für ein bestimmtes Jahr (z.B. 2020)

Wie willst du das Jahr bestimmen können? Explizit wählen oder ist es immer das aktuelle/nächste...

Oder soll die Liste gar pro TPop _und Jahr_ eine Zeile erhalten und du kannst darin nach den Jahren filtern?

> aber nicht für eine Art sondern für alle AP-Arten in einer Tabelle

Wie sollen diese Arten gewählt werden können?

> Die Daten der Tabelle unter Punkt 1 werden so ausgewertet (in separater Tabelle), dass pro Art die Anzahl der TPop mit EK-Plan in 2020 mit Abrechnungstyp A resp. Abrechnungstyp B berechnet wird

Muss man hier wieder Arten wählen können? Wenn ja wie? Oder reicht einfach eine Liste über alle Arten?

**Comment by kmarti** [comment]
Eigentlich brauche ich gar keinen Export, sondern nur die  Auswertung in einer Excel-Tabelle für ein bestimmtes Jahr. Damit kann ich die Offerten der Artverantwortlichen überprüfen. Hier ein Beispiel für das Jahr 2020 (die Zahlen stimmen nicht überall). Ich brauche pro Art die Anzahl TP, die in dem bestimmten Jahr überprüft werden, aufgeteilt nach Abrechnungstyp. Eine Liste über alle Arten ist ok.

**Comment by kmarti** [comment]
Eigentlich brauche ich gar keinen Export, sondern nur die  Auswertung in einer Excel-Tabelle für ein bestimmtes Jahr. Damit kann ich die Offerten der Artverantwortlichen überprüfen. Hier ein Beispiel für das Jahr 2020 (die Zahlen stimmen nicht überall). Ich brauche pro Art die Anzahl TP, die in dem bestimmten Jahr überprüft werden, aufgeteilt nach Abrechnungstyp. Eine Liste über alle Arten ist ok.

**Comment by kmarti** [comment]
Eigentlich brauche ich gar keinen Export, sondern nur die  Auswertung in einer Excel-Tabelle für ein bestimmtes Jahr. Damit kann ich die Offerten der Artverantwortlichen überprüfen. Hier ein Beispiel für das Jahr 2020 (die Zahlen stimmen nicht überall). Ich brauche pro Art die Anzahl TP, die in dem bestimmten Jahr überprüft werden, aufgeteilt nach Abrechnungstyp. Eine Liste über alle Arten ist ok.

**Comment by kmarti** [comment]
Eigentlich brauche ich gar keinen Export, sondern nur die  Auswertung in einer Excel-Tabelle für ein bestimmtes Jahr. Damit kann ich die Offerten der Artverantwortlichen überprüfen. Hier ein Beispiel für das Jahr 2020 (die Zahlen stimmen nicht überall). Ich brauche pro Art die Anzahl TP, die in dem bestimmten Jahr überprüft werden, aufgeteilt nach Abrechnungstyp. Eine Liste über alle Arten ist ok.

**Comment by kmarti** [comment]
Eigentlich brauche ich gar keinen Export, sondern nur die  Auswertung in einer Excel-Tabelle für ein bestimmtes Jahr. Damit kann ich die Offerten der Artverantwortlichen überprüfen. Hier ein Beispiel für das Jahr 2020 (die Zahlen stimmen nicht überall). Ich brauche pro Art die Anzahl TP, die in dem bestimmten Jahr überprüft werden, aufgeteilt nach Abrechnungstyp. Eine Liste über alle Arten ist ok.

**Comment by kmarti** [comment]
Eigentlich brauche ich gar keinen Export, sondern nur die  Auswertung in einer Excel-Tabelle für ein bestimmtes Jahr. Damit kann ich die Offerten der Artverantwortlichen überprüfen. Hier ein Beispiel für das Jahr 2020 (die Zahlen stimmen nicht überall). Ich brauche pro Art die Anzahl TP, die in dem bestimmten Jahr überprüft werden, aufgeteilt nach Abrechnungstyp. Eine Liste über alle Arten ist ok.

**Comment by kmarti** [comment]
Eigentlich brauche ich gar keinen Export, sondern nur die  Auswertung in einer Excel-Tabelle für ein bestimmtes Jahr. Damit kann ich die Offerten der Artverantwortlichen überprüfen. Hier ein Beispiel für das Jahr 2020 (die Zahlen stimmen nicht überall). Ich brauche pro Art die Anzahl TP, die in dem bestimmten Jahr überprüft werden, aufgeteilt nach Abrechnungstyp. Eine Liste über alle Arten ist ok.

**Comment by kmarti** [comment]
Eigentlich brauche ich gar keinen Export, sondern nur die  Auswertung in einer Excel-Tabelle für ein bestimmtes Jahr. Damit kann ich die Offerten der Artverantwortlichen überprüfen. Hier ein Beispiel für das Jahr 2020 (die Zahlen stimmen nicht überall). Ich brauche pro Art die Anzahl TP, die in dem bestimmten Jahr überprüft werden, aufgeteilt nach Abrechnungstyp. Eine Liste über alle Arten ist ok.

**Comment by rebeccakurz** [comment]
Hoi Alex
Kann ich hier mal nachfragen, was hier der letzte Stand war? Konntest du eine solche Liste mit der Anzahl TP pro Art, die in dem bestimmten Jahr überprüft werden, aufgeteilt nach Abrechnungstyp erstellen?
Müssen wir diese bei uns suchen?
Liebe Grüsse 
Rebecca

**Comment by barbalex** [comment]
Ich habe angenommen, wenn Karin den Issue schliesst, dann sei die Sache erledigt. Ist sie es nicht?

**Comment by rebeccakurz** [comment]
Hmm ich glaube es hat hier einen Fehler/ein Missverständnis gegeben... Ich werde es nochmals mit Karin anschauen.

**Comment by rebeccakurz** [comment]
Hoi Alex
Habe das nochmals mit Karin besprochen: Hier scheint tatsächlich etwas schief gelaufen zu sein, sie hat den Issue nicht absichtlich geschlossen.

Könntest du dir dieses Anliegen daher nochmals anschauen?
Vielen Dank!

**Comment by barbalex** [comment]
Karin hat oben geschreiben:

> Hier ein Beispiel für das Jahr 2020 (die Zahlen stimmen nicht überall)

Aber das Beispiel ging wohl vergessen.

Könnt ihr das bitte noch geben?

**Comment by barbalex** [comment]
> Eigentlich brauche ich gar keinen Export, sondern nur die Auswertung in einer Excel-Tabelle

Ich werde es trotzdem als Export bauen. Denn dann kann Karin ihn ausführen, wann immer sie will. Und muss nicht von mir eine Abfrage ausführen lassen. Der Mehraufwand für einen Export ist ca. 0.5 Stunden.

**Comment by barbalex** [comment]
Wenn ich alle Kommentare oben lese, ist mir immer noch unklar, was ihr genau wollt. Ich hoffe, es wird durch das Beispiel klar. Ansonsten wäre es praktisch, wenn ihr es nochmals beschreiben könntet. Oder ich frage einfach wieder, wenn ich das Beispiel habe.

**Comment by rebeccakurz** [comment]
Hier das Beispiel, wie wir uns eine solche Auswertung vorstellen:
[Beispiel_Auswertung_EK_Planung_2020.xlsx](https://github.com/barbalex/apf2/files/5864932/Beispiel_Auswertung_EK_Planung_2020.xlsx)

**Comment by barbalex** [comment]
Super, das macht es VIEL klarer.

Könnt ihr mir bitte erklären, was der Unterschied ist zwischen Typ A und Typ B?
Welche EK-Frequenzen sind was?

Falls es sich auf das Feld "EK-Abrechnungstyp" bezieht: Wieso braucht ihr "D" nicht?

**Comment by barbalex** [comment]
Wollt ihr die Liste über alle Arten oder nur AP-Arten?

**Comment by rebeccakurz** [comment]
Also: Ja Typ A und B bezieht sich auf den Abrechnungstyp und wir bräuchten auch "D", das fehlt in dieser Tabelle. Und eine Liste nur von den AP-Arten reicht. 
Vielen Dank!

**Comment by barbalex** [comment]
Ist in Version 1.54.0 umgesetzt.

Schaut euch bei den Exporten für AP diesen an: "EK-Planung pro Jahr nach Abrechnungstyp"

**Comment by rebeccakurz** [comment]
Hoi Alex
Danke für den Export.
Aber ich glaube, er ist noch nicht ganz so, wie wir uns das vorgestellt haben. Wir brauchen den Export ja für die Überprüfung der Offerten, also jetzt zum Beispiel für das Jahr 2021, wo aufgelistet ist, wie viele EKs pro Abrechnungstyp und pro Art geplant sind. 
In dem Export in der jetzigen Form ist für jede Art ein anderes Jahr drin und ich kann auch das Jahr 2021 nicht auswählen. Oder habe ich da etwas nicht verstanden?
![Bildschirmfoto 2021-01-26 um 07 47 39](https://user-images.githubusercontent.com/30288503/105811244-9e502c00-5fac-11eb-8b8c-444be352bbca.png)

**Comment by rebeccakurz** [comment]
Ich öffne den Issue also nochmals.

**Comment by barbalex** [comment]
Uups. Sorry, werde es heute Abend korrigieren

**Comment by barbalex** [comment]
Uff. Das war eine Knacknuss.

Die Abfrage ist korrekt.

Das heisst: Die App erhält die richtigen Daten.

Aber sobald sie ankommen, wurden sie verändert 👿 

Das Abfragewerkzeug ist sehr eigenwillig. Es hat ein Feld namens "ID" gefunden und entschieden, dass diese ID eindeutig sein müsste. Es war aber die ID des Aktionsplans. Und weil dieser in dieser Liste mehrmals vorkommen sollte, hat das Abfragewerkzeug offenbar kurzerhand nur den jeweils ersten Wert für jedes Feld übernommen und gleich in allen Zeilen eingesetzt  - satt der übermittelten Werte 🙄 

Ich hasse es, wenn ich nicht der einzige in diesem Projekt bin, der eigenwillig ist 😆 

Ist in Version 1.54.1 korrigiert.

**Comment by rebeccakurz** [comment]
Super, danke, jetzt sieht es gut aus!
