### ISSUE TITLE
Export Kart

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#37]
Entspricht nicht dem sichtbaren Ausschnitt

**Comment by barbalex** [comment]
Ja, das ist mir auch aufgefallen.
Z.T. musste ich schauen, welcher Ausschnitt produziert wird, nochmals richten, nochmals drucken

Leider funktioniert der andere Export auch nicht richtig https://github.com/barbalex/apf2/issues/1

**Comment by barbalex** [comment]
ist mit dem neuen png export behoben
