### ISSUE TITLE
In Massnahmen die ziel-relevante Einheit zählen

### ISSUE THREAD

**Issue by barbalex** [barbalex/apf2#370]
@kmarti @rebeccakurz

Um Veränderungen der ziel-relevanten Einheit pro TPop/Pop/AP darstellen zu können, müssen auch in relevanten Massnahmen (Anpflanzungen) künftig die ziel-relevanten Einheiten erfasst werden. 

Und zwar so, dass sie genau gleich deklariert sind wie in Kontrollen. Weshalb nicht die bestehenden Felder ("Anzahl Triebe", "Anzahl Pflanzen", "Anzahl Pflanz-stellen") verwendet werden können.

Als wir in den Diskussion darauf gestossen sind, habe ich mir daher gedacht, dass wir das auch strukturell gleich wie bei Kontrollen machen sollten. Das hiesse: Neue Tabelle `tpopmassn_zaehlung`, in die pro Massnahme beliebig viele Zählungen mit Einheit, Methode und Anzahl erfasst werden könnten.

Bei den Kontrollen ~~ist das leider so~~😉 ist das sinnvoll, **weil es möglich sein soll, unterschiedlichste nicht ziel-relevante Einheiten zu erfassen**.

**Die grosse Frage ist nun: Ist das in Massnahmen auch so?**

Falls ja, wäre die Schaffung der zusätzlichen Tabelle `tpopmassn_zaehlung` sinnvoll.

Falls nein, würde ich vorschlagen, bloss zwei zusätzliche Felder zu schaffen:
- zieleinheit_einheit
- zieleinheit_anzahl

Das Feld `zieleinheit_einheit` scheint ev. zunächst einmal unnötig. Denn was die ziel-relevante Einheit ist, ist ja in den EK-Zähleinheiten definiert (diejenige, die als ziel-relevant markiert ist). Aber: Falls es einmal vorkommen sollte, dass diese Einheit verändert würde (was hoffentlich nie passiert aber sicher passieren wird), wäre es entscheidend, zu wissen, dass in einer Massnahme eben _nicht_ diese Einheit gezählt wurde.

Darum ist es sinnvoll, die Einheit zu setzen. Allerdings sollte sie wohl bei der Erzeugung einer neuen Massnahme von apflora automatisch auf den Wert der in den EK-Zähleinheiten definierten Einheit gesetzt werden.

Ich vermute, das es bei den Massnahmen nicht wichtig ist, die Methode ("gezählt" oder "geschätzt") zu wissen bzw. erfassen. Ebenso wenig, wie sie für die ziel-relevante Einheit bei den Zählungen in der Auswertung berücksichtigt werden kann (ausser ihr sagt, dass immer nur "gezählt" berücksichtigt werden soll).

Hingegen ist mir nicht völlig klar, wie sehr die bisher verfügbaren Anzahlen ("Anzahl Triebe", "Anzahl Pflanzen", "Anzahl Pflanz-stellen") noch sinnvoll sind, wenn künftig die ziel-relevante Einheit gezählt werden soll. Und ob man bisherige Felder aufheben könnte, um die Erfassung zu vereinfachen. Und ob dann allenfalls Daten aus diesen Feldern in die neuen geschrieben werden müssten.

**Konkrete Fragen an euch:**
- Macht das, was ich oben sage Sinn bzw. verstehe ich die dargestellten Sachverhalte richtig?
- Müssen künftig in Massnahmen beliebige Einheiten zusätzlich zur ziel-relevanten erfasst werden können?
- Werden weiterhin alle bisher enthaltenen Einheiten ("Anzahl Triebe", "Anzahl Pflanzen", "Anzahl Pflanz-stellen") erfasst?
- Müssen bei allen/bestimmten AP's Daten aus bisherigen Anzahlen (welchen?) in die neue ziel-relevante Anzahl kopiert werden, damit die Auswertung rückwirkend besser möglich ist?

**Comment by kmarti** [comment]
- Deine Überlegungen sind völlig richtig.
- Es müssen keine beliebigen Einheiten zusätzlich erfasst werden.
- Die bisher erfassten Einheiten (Anzahl Triebe, Anzahl Pflanzen und Anzahl Pflanzstellen) werden weiterhin erfasst.
- Wenn die zielrelevante Einheit "Triebe" ist, dann könnten die bisherigen "Anzahlen Triebe" dort hinein kopiert werden. Dasselbe bei "Pflanzen". Bei den anderen zielrelevanten Einheiten (z.B. blühende Pflanzen) macht dies keinen Sinn, da keine blühenden Pflanzen ausgepflanzt werden.

**Comment by barbalex** [comment]
Super, dann ist glaube ich alles klar. Melde mich nochmals falls bei der Umsetzung weitere Fragen auftauchen

**Comment by barbalex** [comment]
Ich werde also folgendes umsetzen: 

In der Tabelle `tpopmassn` zwei zusätzliche Felder:
- zieleinheit_einheit
- zieleinheit_anzahl

wobei `zieleinheit_einheit` bei der Wahl eines Massnahmen-Typs, der Anpflanzung beinhaltet, von apflora automatisch auf den Wert der in den EK-Zähleinheiten definierten Einheit gesetzt wird.

Plus eine neue Qualitätskontrolle, welche meldet, wenn bei einer Anpflanzung die ziel-relevante Einheit nicht erfasst wurde.

Und: die neuen Felder werden nur sichtbar, wenn der Massnahmen-Typ eine Anpflanzung beinhaltet.

**Comment by kmarti** [comment]
das ist prima

**Comment by barbalex** [comment]
Was ich vergessen habe: Ich muss diverse Views und Funktionen ergänzen. Zum Teil recht komplexe...

**Comment by barbalex** [comment]
...und Exporte

**Comment by barbalex** [comment]
...und Filter

**Comment by barbalex** [comment]
...und Tests

**Comment by barbalex** [comment]
...und Tabelle `tpopmassn_typ_werte` muss wissen, welche Massnahmen-Typen Anpflanzungen sind. Muss also im das Feld `anpflanzung` ergänzt werden.

**Comment by barbalex** [comment]
O.k., ist gemacht.

277 Massnahmen mit Trieben und 1446 Massnahmen mit Pflanzen und passenden zielrelevanten EK-Zähleinheiten haben jetzt eine zieleinheit_einheit und zieleinheit_anzahl.
