### ISSUE TITLE
EKF-Export der Kontrollen

### ISSUE THREAD

**Issue by barbalex** [barbalex/apf2#371]
In Wunschliste_APFlora_DB_20200204.xlsx schreibt ihr:

> EKF-Export für Gesamtliste von allen Freiwilligen-Kontrollen + Liste pro Kontrolleur (Export EK-Planung + zusätzliche Felder: Koordinaten und EKF-Kontrolleur)

Ich brauche einen genaueren Beschrieb plus eine Begründung (wozu wird es verwendet?), damit ich überlegen kann, wie ich das bestmögliche Produkt baue.

Meine Fragen:
- Sind das zwei Produkte?
  1. eine Gesamt-Liste sortiert nach AP/Pop/TPop aller Freiwilligen-Kontrollen?
  2. pro Kontrolleur eine Liste?

Angenommen ja:

#### Gesamt-Liste sortiert nach AP/Pop/TPop aller Freiwilligen-Kontrollen
- Wie genau soll sie gefiltert sein? TPop's, die im aktuellen Jahr gemäss Planung kontrolliert werden sollen?
- Welche Felder soll sie enthalten?

#### Liste pro Kontrolleur
- Wie soll sie erzeugt werden?
  Soll z.B. jeder Kontrolleur selbst sie erzeugen können?
  Oder alle aufs Mal zentral?
- Sind das so viele Exporte wie Kontrolleure oder ist das einfach eine einzige Liste, die nach den Kontrolleuren gruppiert und sortiert wird?
- Welche Felder sollen enthalten sein?

**Comment by rebeccakurz** [comment]
Hoi Alex
Also zu deinen Fragen: 

- Ja, das sind zwei Produkte, eine Gesamtliste und pro Kontrolleur eine Liste (wobei die Liste pro Kontrolleur aus der Gesamtliste hervorgeht).

Vielleicht ist es am einfachsten, wenn ich dir die Listen zeige, die ich bis jetzt verwendet habe. 
Gesamtliste:
[EKF_Gesamtliste_20200318.xlsx](https://github.com/barbalex/apf2/files/4367623/EKF_Gesamtliste_20200318.xlsx)
Liste pro Kontrolleur (Beispiel)
[Gämperle_René_EKF_2020.xlsx](https://github.com/barbalex/apf2/files/4367630/Gamperle_Rene_EKF_2020.xlsx)

Die Gesamtliste dient vor allem meiner Übersicht. Ich kann dort nachschauen, was alles von Freiwilligen kontrolliert wird und abhäkeln wann ich was verschickt habe, bzw. wann was zurückgekommen ist, etc. 
Es wäre also gut, wenn sie genau das enthalten würde, was du vorgeschlagen hast: TPops, die im aktuellen Jahr kontrolliert werden sollen. 
Felder, die sie mindestens enthalten soll: AP, Pop und TPop Nummer, TPop Gemeinde, TPop Flurname, TPop Status (angesiedelt oder ursprünglich), TPop X-Koordinaten, TPop Y-Koordinaten, Kontrolleur

Die Listen pro Kontrolleur habe ich dann jeweils aus der Gesamtliste rauskopiert. Ich brauche diese Listen um bei den Kontrolleuren anzufragen,  ob sie diese Kontrollen wieder übernehmen möchten und dann auch als Übersicht, wenn ich die Unterlagen verschicke. 
Die Listen sollten also von mir zentral erstellt werden können. Ich kann aber auch weiterhin die Gesamtliste nach Kontrolleuren filtern und so die Listen pro Kontrolleur erstellen. 
Enthaltene Felder: AP, Pop & TPop Nr, TPop Gemeinde, TPop Flurname, angesiedelt oder ursprünglich, TPop X-Koordinaten, TPop Y-Koordinaten, Kontrolleur/in

**Comment by barbalex** [comment]
O.k., dann würden wie wohl am besten erzeugt:
- Gesamtliste: klassischer Export, beim Export der TPop
- Liste pro Kontrolleur: Im Formular des Benutzers (= Kontrolleurs). Ev. neben der Schaltfläche, um die EKF-Formulare zu öffnen

> Ich kann dort nachschauen, was alles von Freiwilligen kontrolliert wird und abhäkeln wann ich was verschickt habe, bzw. wann was zurückgekommen ist, etc

Das heisst, die Listen sollen jeweils für das aktuelle Jahr sein? Oder gibt es den Fall, wo du ein abweichendes Jahr wählen müsstest?

**Comment by rebeccakurz** [comment]
Ja das fände ich gut so.
Ja die Listen sind jeweils für das aktuelle Jahr. 
Nein ich glaube ich müsste kein abweichendes Jahr wählen können. Ich habe die Listen der verschiedenen Jahre ja dann abgespeichert und könnte dort nachschauen.

**Comment by barbalex** [comment]
@rebeccakurz 

Ist das immer noch aktuell?

Ist ein Export wirklich ideal oder könnte ach das EK-Planungs-Formular geeignet sein, wenn es gezielt erweitert würde?

**Comment by rebeccakurz** [comment]
Ja das wäre immer noch aktuell. 
Ich glaube das Haupthindernis ist, dass das EK-Planungs-Formular jeweils nur für eine Art ist. Und ich habe zum Teil Freiwillige, die verschiedene Arten kontrollieren. 
Oder was würdest du als Erweiterung vorschlagen?

**Comment by barbalex** [comment]
> dass das EK-Planungs-Formular jeweils nur für eine Art ist

Stimmt nicht. Du kannst beliebig viele Arten wählen. Irgendwann wird einfach die Rechenlast etwas hoch...

> Oder was würdest du als Erweiterung vorschlagen?

Ich hab einfach gedacht: Wenn es mit vernünftigem Aufwand in apflora ginge, wäre das doch besser, als neben apflora in so grossen und unübersichtlichen Excel-Tabellen Daten nachzuführen, bei denen dann bald nicht mehr so klar ist, was aktuell bzw. nachgeführt ist.

**Comment by rebeccakurz** [comment]
Tatsächlich, das wusste ich gar nicht, dass man mehrere Arten auswählen kann!

Könnte denn in der EK-Planung der EKF-Kontrolleur ergänzt werden? Das wäre wahrscheinlich tatsächlich eine Möglichkeit, um ohne die Excel-Tabellen auszukommen.

**Comment by barbalex** [comment]
Klar, das geht. Brauchst du noch mehr?

**Comment by barbalex** [comment]
EKF-KontrolleurIn ist in Version 1.55.0 integriert

**Comment by rebeccakurz** [comment]
Danke! Ich habe gestern hin und her überlegt, ob das genügt oder ob ich noch mehr brauche. Aber dann kann ich es einfach mal ausprobieren und falls es das braucht noch mehr Wünsche anbringen.
