### ISSUE TITLE
Erinnerung apflora Einstellungen Karte/EK-Planung

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#374]
Eine Zeit lang war es so, dass apflora die Karte mit den gleichen Einstellungen wieder geöffnet hat, wie ich sie das letzte Mal hatte (also zum Beispiel mit dem Orthofoto als Hintergrund und dem ZH Übersichtsplan als Überlagerung) - was ungemein praktisch war. Aber seit einiger Zeit funktioniert das nicht mehr und ich muss die Karte immer wieder neu einstellen. 
Auch bei der EK-Planung hast du angemerkt, dass die Anwendung die Felder, die ich eingestellt hatte, sich merken sollte und dann wieder diese anzeigt bei der nächsten Verwendung. Auch hier muss ich es jeweils neu einstellen.

Würde das nur funktionieren, wenn ich mich jeweils nicht ausloggen würde?
Oder muss ich dazu die Anwendung als App heruntergeladen haben? (Ich benutze sie im Browser Chrome)

**Comment by barbalex** [comment]
Das sollte funktionieren.

Unabhängig davon, ob du sie als App benutzt oder im Browser. (auch das "App" benutzt den Browser - bloss versteckt er sich mehr oder weniger gut)

Die dafür benötigten Daten werden im "local cache" des Browsers gespeichert. Nur wenn du den leerst, gehen sie verloren.

Wenn du dich mit dem Befehl "<dein Name> abmelden (und Cache leeren)" abmeldest: Ja, dann verlierst du unter anderem auch den "local cache". Dieser Befehl ist dafür gedacht:
- wenn jemand anderes am selben Computer nach dir arbeitet, soll diese Person keinerlei Zugriff auf deine zwischengespeicherten Daten bekommen
- wenn es Fehler gibt, die nur durch Leeren des Caches zu beheben sind
Darum wird dann auch der Cache geleert.

An und für sich wäre Abmelden auch ohne Leeren des Caches möglich (wenn ich einen solchen Befehl anbieten würde).

Aber du musst dich eigentlich nur abmelden, wenn jemand anderes an deinem Computer mit einem anderen Login anmeldet. Sonst ist Abmelden unnötig.

**Comment by rebeccakurz** [comment]
Ah okay, ich habe mich jeweils abgemeldet, dann war das der "Fehler". 
Danke!
