### ISSUE TITLE
EK-Planung: Koordinaten auch in Export

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#375]
Hoi Alex

Bei der EK-Planung sind ja die Koordinaten nun ebenfalls anwählbar, das ist super!
Ich habe allerdings gerade einen Export ausprobiert und dabei festgestellt, dass die Koordinaten im Export nicht enthalten sind, auch wenn ich sie in der EK-Planung angewählt habe.
Könntest du dir das mal noch anschauen?
Danke

**Comment by keolan** [comment]
Lieber Alex, Rebecca
Oh ja, Koordinaten wären super! Aber ich kann die auch nicht in der Planung sehen. Was meint Rebecca mit "anwählbar"?
Ich bräuchte sie aber v.a. auch nicht in der Planung, sondern wie Rebecca im Export.
Lg, Charlotte

**Comment by barbalex** [comment]
@rebeccakurz muss ich noch machen

@keolan Schaltfläche "Felder wählen" (gemäss meinem Gedächtnis, bin unterwegs)

**Comment by barbalex** [comment]
Ab v1.28.5 werden jetzt Koordinaten auch exportiert, _wenn sie unter "Felder wählen" gewählt wurden_
