### ISSUE TITLE
EK Planung, Pop- und TPop-Namen fehlen

### ISSUE THREAD

**Issue by keolan** [barbalex/apf2#376]
Im Gegensatz zu früheren Exporten fehlen jetzt die Pop- und TPop-Namen im Export. Es ist dafür der GUID drin.
Bitte auch in der EK-Planung selber, nicht nur im Export, (wieder?) die Namen aufführen. Ich wüsste nicht, wie man sonst planen kann, den wenigsten sagt die Nr. ja etwas. 
Vielen Dank und Gruss, Charlotte

**Comment by barbalex** [comment]
Der Export berücksichtigt deine Einstellungen. Wenn du Pop-Namen willst, musst du sie einschalten.

**Comment by barbalex** [comment]
Das Prinzip des Export ist: **W**hat **Y**ou **S**ee **I**s **W**hat **Y**ou **G**et.

Wenn du Felder willst, kannst du sie unter "Felder wählen" ein- bzw. ausblenden.

**Comment by csalzmann** [comment]
Danke!! Hab die Schaltfläche voll übersehen.
