### ISSUE TITLE
Gemeinden, Detailpläne und Markierungen als PostGIS-Tabellen

### ISSUE THREAD

**Issue by barbalex** [barbalex/apf2#378]
@kmarti @wunderli @rebeccakurz 

Statt wie bisher aus einer Datei geladen, werden Gemeinden, Detailpläne und Markierungen neu in PostGIS-Tabellen innerhalb unserer Datenbank (PostgreSQL) importiert.

Vorteile:
- Bessere technische Integration ins Projekt
- Abfragen sind viel schneller und Ressourcen-schonender
- Datensätze können besser abgefragt werden (z.B. durch Klick auf Karte)
- Künftige Erweiterungen möglich

Mögliche künftige Erweiterungen:
- Topos und Artverantwortliche können die Daten direkt in ihr eigenes GIS einbinden
- Daten aus Detailplänen/Markierungen können z.B. mit Teil-Populationen verbunden werden. Z.B. um die Pläne/Markierungen einer TPop anzuzeigen
- Detailpläne und Markierungen könnten direkt in apflora.ch und/oder auf einem Desktop-GIS nachgeführt werden. Und zwar von jeder Artverantwortlichen selber (auch beim Desktop-GIS)
- Geografische Auswertungen sind möglich, zum Beispiel:
- Es können KML-Dateien pro Gemeinde erzeugt werden (aktueller Wunsch)

**Comment by barbalex** [comment]
@rebeccakurz 
Wenn ihr aktuellere Versionen von Markierungen und Detailplänen habt und in apflora sehen wollt, kannst du mir sie gerne senden

**Comment by rebeccakurz** [comment]
Hoi Alex 
Vielen Dank für diese Erweiterung, das tönt sehr vielseitig anwendbar!
Du schreibst einer der Vorteile sei, dass Datensätze besser abgefragt werden können, z.B. durch einen Klick auf die Karte. Wäre es denn zum Beispiel möglich, wenn man den Pflegeplan überlagernd eingeblendet hat, darauf zu klicken und so z.B. den Naturschutzbeauftragten für dieses Gebiet zu ermitteln (eigentlich analog zum GIS-Browser)? Ich muss nämlich zum Beispiel bei den Erfolgskontrollen durch Freiwillige die jeweiligen NBA über die Kontrollen informieren und habe jeweils ein rechtes Stück Arbeit bis ich die Pflegeplan-Nummern und die NBAs über den GIS-Browser herausgefunden habe... Wenn das alles in der FloraDB abrufbar wäre oder vielleicht sogar in einem Export (wie die Gemeinde, die über die Karte ermittelt wird), wäre das super!
Auch die Artverantwortlichen müssen die Naturschutzbeauftragten über ihre EKs und Auspflanzungen informieren, allenfalls fänden sie so etwas auch hilfreich.
Oder was für Abfragen wären möglich?

**Comment by barbalex** [comment]
> und so z.B. den Naturschutzbeauftragten für dieses Gebiet zu ermitteln

Wo sind diese Daten publiziert? Im Pflegeplan finde ich sie nicht: http://wms.zh.ch/FnsPflegeZHWMS?SERVICE=WMS&Request=GetCapabilities

Aha, hier sind sie: http://www.geolion.zh.ch/geodatensatz/3109. Ich könnte sie also problemlos integrieren. Gibt aber ein paar Stunden Aufwand.

Wenn wir diese Daten hätten und innerhalb von apflora als PostGIS-Tabelle integrieren würden, könnte man z.B. den Naturschutzbeauftragten Auswertungen aller Daten, welche sie betreffen generieren. Z.B. Listen/Karten/Kml-Exporte... (mit entsprechendem Aufwand)


**Allgemeines**

Daten als PostGIS integrieren hat auch Nachteile:
- Sie sind nicht automatisch aktuell wenn die zuständige Stelle sie nachführt, wie z.B. WMS/WFS. Ich muss dann jeweils von einer Nachführung erfahren und die Daten neu importieren. Was z.B. bei Gemeinden ein seltener Vorgang ist
- Sie belasten unser Gesamt-System. So sind z.B. Sicherungen um 30% gewachsen, seit ich diese drei PostGIS-Tabellen integriert habe

Es lohnt sich also nur, wenn der Vorteil grösser ist als der Aufwand.

Bei Markierungen und Detailplänen scheint mir die Sache klar. Diese Daten gehören schliesslich zum Projekt. Bei denen könnte man sogar so weit gehen, sie hier nachzuführen. Das wäre absolut möglich. Entweder direkt auf apflora.ch durch Erweiterung der Fähigkeiten der Karte. Oder durch Zugriff via GIS, was bei QGIS gut funktioniert. Ich kenne die PostGIS-Fähigkeiten von ArcGIS nicht. Weiss bloss, dass PostGIS sehr mächtig ist. Ev. in Teilbereichen sogar mächtiger als ArcGIS.

Bei Gemeinden ist der Nachführungs-Aufwand relativ klein.

Bei jährlich nachgeführten Daten wie z.B. die Pflegeplanung wäre der Aufwand vermutlich schnell grösser als der Nutzen. Ausser: Es gibt einen konkreten Anwendungsfall, d.h. der Nutzen wäre gross. Z.B. jährlich generierte Produkte (Listen, Karten, Kml-Exporte...).


> und habe jeweils ein rechtes Stück Arbeit bis ich die Pflegeplan-Nummern über den GIS-Browser herausgefunden habe

Das findest du heute schon auf der Karte in apflora: Im Layer "Pflegeplan". Vielleicht hast du es bloss nicht gemerkt, weil man stark rein-zoomen muss, bis die Nummern erscheinen (sonst würden sie alles verdecken).

**Comment by barbalex** [comment]
Oh je. Die Betreuungsgebiete Naturschutz enthalten zwar die Gebiete. Aber nicht die Betreuer...
Nützt also nichts.

**Comment by barbalex** [comment]
Wir müssten die Betreuungsgebiete kombinieren mit Daten, die uns die FNS separat liefert: Wer welches Gebiet betreut. Falls wir das bekommen.

**Comment by rebeccakurz** [comment]
Ja, die Pflegeplan-Nummern habe ich entdeckt, aber leider zu spät für die Info an die NBAs über die Erfolgskontrollen durch Freiwillige. Das ist aber sicher schon mal eine grosse Hilfe. 
Im GIS-Browser ist es so, dass wenn man den Layer "Pflegeplan Naturschutzteilflächen" eingeblendet hat und auf eine Teilfläche klickt, wird am Rand der Schnittzeitpunkt, NBA und weitere Infos eingeblendet.
Aber vielleicht übersteigt der Aufwand tatsächlich den Nutzen.

Vielleicht kann sich Anna das Ganze auch mal noch anschauen, sie kennt sich mit ArcGIS am Besten aus und kann vielleicht besser beurteilen ob man die Markierungen und Detailpläne mit ArcGIS nachführen kann.

**Comment by rebeccakurz** [comment]
[Betreuungsgebiete.pdf](https://github.com/barbalex/apf2/files/4544432/Betreuungsgebiete.pdf)
Es gibt dieses Dokument der FNS. Allerdings ist es nicht immer ganz klar, wer jetzt wo zuständig ist, vor allem, wenn sich der Zuständigkeitsbereich nicht mit den Gemeinden deckt. Dann muss man jeweils im GIS-Browser die entsprechende Naturschutzteilfläche anklicken.
Vielleicht könnte man bei der FNS noch eine genauere Aufteilung bekommen, nach Naturschutzteilfläche, das war glaub ich auch schon Wunsch der AV...

**Comment by barbalex** [comment]
> Vielleicht kann sich Anna das Ganze auch mal noch anschauen, sie kennt sich mit ArcGIS am Besten aus und kann vielleicht besser beurteilen ob man die Markierungen und Detailpläne mit ArcGIS nachführen kann

Wenn man das machen will, müsste man die Datenstruktur als erstes bestimmen. Und weil es finanziell bedeutend sein könnte, mit der FNS koordinieren. Das ist ein Bereich, in dem Andreas Lienhard bestimmt gut informiert sein will und sollte

**Comment by barbalex** [comment]
Zu Betreuungsgebiete.pdf:

Die Karte entspricht den Betreuungsgebieten im GeoLion.
Die Tabelle ist genau, was ich oben gemeint habe:

> Wir müssten die Betreuungsgebiete kombinieren mit Daten, die uns die FNS separat liefert: Wer welches Gebiet betreut

Wenn wir die Liste von der FNS regelmässig (bei Nachführungen) erhalten, kann ich die Daten in apflora.ch verfügbar und nutzbar machen.

**Comment by rebeccakurz** [comment]
Okay, dann werde ich mal versuchen eine solche Liste zu erhalten.

**Comment by rebeccakurz** [comment]
Hoi Alex
Also leider kann uns Kaspar Spörri eine solche Liste nicht zur Verfügung stellen, es ist von der FNS nicht erwünscht... Schade.

**Comment by rebeccakurz** [comment]
Hoi Alex
Bin gerade etwas unsicher: Hast du die zweite Seite in "Betreuungsgebiete.pdf" gesehen? Dort steht nämlich, wer für welches Gebiet zuständig ist... Würde das reichen für eine Kombination der Daten?

Oder bräuchten wir z.B. eine Excel-Tabelle, bei der jedes Naturschutzgebiet mit Betreuer aufgelistet ist? Oder wie müsste man sich diese Liste vorstellen?

**Comment by barbalex** [comment]
Wie ich [oben](https://github.com/barbalex/apf2/issues/378#issuecomment-620474897) gesagt habe:

Die Tabelle auf der zweiten Seite ist genau, was wir brauchen. Wir sollten aber neben der Erlaubnis, sie für diesen Zweck benutzen zu dürfen, von der FNS jeweils eine aktuelle Version erhalten, wenn sie geändert wird.

Es gab früher (als Andreas Keel noch in der FNS war) mit einer Regelmässigkeit immer wieder Diskussionen darüber, wie die Betreuer über die Massnahmen von apflora zweckdienlich informiert werden könnten. Andreas hat das immer gewollt, aber es gab kein gutes Werkzeug - ausser der Ebene von TPop, die im BUN eingeblendet werden kann (die aufgrund dieser Diskussionen entstand).

Wenn wir also mit Hilfe dieser Tabelle bessere Werkzeuge produzieren könnten, wäre das wohl ganz im Sinne der FNS. Es braucht einfach von euch einen entsprechenden Vorschlag. Der Technisch umgesetzt werden kann. 

Die Tabelle aus dem PDF kann ich vermutlich problemlos extrahieren und benutzen. Aber die FNS sollte darüber informiert und damit einverstanden sein. Denn immerhin gibt sie diese Tabelle ganz offensichtlich nicht einfach so raus.

Aufgrund des Aufwands und der Tatsache, dass die FNS diese Daten nicht offen streuen will, wäre der Anwendungszweck bzw. die Begründung zentral.

**Comment by rebeccakurz** [comment]
Lieber Alex

Achso, dann habe ich die Bemerkung oben falsch verstanden, ich dachte du bräuchtest noch mehr Informationen, um die NBAs mit den Gebieten zu verknüpfen. Dieses PDF ist öffentlich zugänglich auf der FNS-Website und Kaspar Spörri hat sie mir jetzt ebenfalls nochmals geschickt. 
Also, damit ich alles richtig verstehe: Dieses PDF wäre für dich ausreichend um die Daten auf apflora zugänglich und nutzbar zu machen? Dann müssten wir sie nur noch regelmässig bei Nachführungen erhalten und FNS über den Verwendungszweck informieren bzw. die Genehmigung dazu erhalten?

**Comment by barbalex** [comment]
Richtig

**Comment by barbalex** [comment]
Nun ja, wenn das Dokument auf der Webseite ist, müssen wir keine Einwilligung haben, solange wir damit mit Ihren Auftraggeldern etwas sinnvolles machen

**Comment by rebeccakurz** [comment]
Okay, super! 
Sorry, dass ich etwas auf der Leitung stand!

**Comment by barbalex** [comment]
Kein Problem. Sorry, dass ich mich zuwenig klar ausgedrückt habe!

**Comment by rebeccakurz** [comment]
Hoi Alex
Auf der Website der FNS wurde das Dokument "Betreuungsgebiete" aktualisiert (Stand 20.7.2020)
[betreuungsgebiete.pdf](https://github.com/barbalex/apf2/files/5134762/betreuungsgebiete.pdf)
Könntest du das neue Dokument in die FloraDB einbinden?
Danke!

**Comment by barbalex** [comment]
Da scheint sich aber nichts geändert zu haben?

**Comment by rebeccakurz** [comment]
Okay, habe es ehrlich gesagt nicht soo genau angesehen, habe nur gesehen, dass es eine neue Version ist. Dann muss du auch nichts aktualisieren :-)

**Comment by barbalex** [comment]
O.k., ab sofort werden meines Wissens überall nur noch die Änderungen gespeichert
