### ISSUE TITLE
Freiwilligenerfolgskontrollen: vervielfachte Zählungen

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#379]
Hoi Alex

Bin gerade am Erfolgskontrollen von Freiwilligen eingeben. Dabei hat es mir bei zwei verschiedenen Teilpopulationen von Gagea pratensis beim EKF-Formular von 2020 vervielfachte Zählungen sowohl im Strukturbaum als auch im Formular selber angezeigt (im Strukturbaum ist die Zähleinheit 1 und 2 jeweils 4x vorhanden, im Formular zeigt es nur die ersten 3x der Zähleinheit 1 an). 
Ich kann die überzähligen Zählungen zwar von Hand aus dem Formular löschen, ist aber etwas mühsam. 
Aktuell bin ich bei Gagea pratensis Teilpopulation 115.1, EKF 2020. Dort sind die Zähleinheiten noch vervielfacht, bei der anderen Teilpopulation, wo ich das angetroffen habe, habe ich sie gelöscht...
sieht das bei dir auch so aus? könntest du dir das mal anschauen?
![Bildschirmfoto 2020-04-30 um 13 35 42](https://user-images.githubusercontent.com/30288503/80706362-7ba9e900-8ae8-11ea-9005-fea54a703610.png)
![Bildschirmfoto 2020-04-30 um 13 36 38](https://user-images.githubusercontent.com/30288503/80706371-7f3d7000-8ae8-11ea-8408-443a0dedc29b.png)

**Comment by barbalex** [comment]
Hoi Rebecca

Bei mir sind sie auch sichtbar. Ist also kein Fehler des Navigations-Baums.
Aus irgend einem Grund wurden so viele Zählungen angelegt. Denn sie existieren wirklich alle in der Datenbank.

Die Frage ist jetzt, wie man es schafft, dass die Zähleinheiten 4-fach angelegt werden.

LG, Alex

**Comment by barbalex** [comment]
Ich hab nun auch versucht, in derselben TPop eine weitere EKF anzulegen. Es wurden genau für die zwei definierten Einheiten Zählungen angelegt.

**Comment by barbalex** [comment]
Ich schliess das mal, da es schon lange nicht mehr gemeldet wurde
