### ISSUE TITLE
Koord von Beob. in TPop kopieren - anschliessende Beschriftung TPop "0m"

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#38]
Daraufhin wird Distanz in TPop-Name aufgenommen:

![bildschirmfoto 2017-06-02 um 14 08 19](https://cloud.githubusercontent.com/assets/6047564/26725124/4bc70876-479d-11e7-9cf0-6268e025d70a.png)

Wollte schauen, ob das bei "Neu laden" wieder weggeht. Geht es, aber siehe Post "Neu laden"

**Comment by barbalex** [comment]
hab ich auch schon beobachtet - war mir aber noch nicht wichtig genug, um es zu lösen

**Comment by csalzmann** [comment]
Ich sehe grad, da steckt aber noch mehr dahinter. Ich klicke im Moment immer wieder verschiedene TPops an und schaue mir sie anschliessend in der Karte an. Offenbar hat die Distanz-Angabe in Meter gar nichts mit dem Koordinaten-kopieren zu tun! Nach Liparis, TPop 20.1 (Bsp. oben) war ich bei Liparis, 60.1. Nun ist die Distanz-Angabe bei 20.1 (obwohl ich in der Zwischenzeit nach dem Koordinaten-Kopieren neu in die FloraDB eingeloggt bin) bei 21'525m.
![Uploading Bildschirmfoto 2017-06-02 um 14.40.09.png…]()

**Comment by barbalex** [comment]
Ist in der Entwicklungsversion behoben
