### ISSUE TITLE
Produkt(e) für NBA (Naturschutz-Gebiets-Betreuer)

### ISSUE THREAD

**Issue by barbalex** [barbalex/apf2#380]
@rebeccakurz @kmarti @wunderli 

Hoi zäme

Die Liste der Aufgaben für 2020 enthält:

> Export: kml-Export nach Gemeinden: Produkt für NBA. Ein mal im Jahr erstellt topos für alle   beauftragten pro gemeinde kml-dateien. Überlegen, wie

Ich glaube, 

> pro Gemeinde 

war enthalten, damit die NBA nicht alle Daten des ganzen Kantons erhalten. Aber eigentlich sollen sie genau die Daten aus ihren Gebieten erhalten. Richtig? 

Das sollte möglich sein mithilfe von 
[Betreuungsgebiete.pdf](https://github.com/barbalex/apf2/files/4563908/Betreuungsgebiete.pdf) und der Umrisse hier: http://www.geolion.zh.ch/geodatensatz/3109.

Ich bin nochmals am überlegen, was das beste Produkt für diesen Zweck wäre. Das Thema liegt der FNS am Herzen. Eine so grundlegende Vorgehensweise wird die Umsetzung vermutlich verzögern, aber dafür kommt es langfristig hoffentlich besser.

**Ziele**

Es geht glaube ich darum, dass NBA 
1. sich möglichst einfach einen Überblick über Teil-Populationen in ihren Gebieten machen können
2. die Daten für ihre Zwecke verwenden können. Das heisst: Sie sollten sie mit geeigneten anderen Daten kombinieren können
z.B. Schutzgebiets-Zonen, Pflege-Planung...
3. die für sie interessanten Informationen sehen können
z.B. Massnahmen. Was sonst alles? Was nicht?

Bitte sagt mir, ob das den Zweck trifft bzw. wie diese Liste wirklich sein sollte. Denn das bestimmt, wie wir das beste oder die besten Produkte dafür liefern können.

**Mittel**

Das Mittel gemäss Aufgaben 2020 wäre eine kml-Datei pro Gemeinde. Problematisch ist bei ihr:
- sie kann schlecht mit anderen Daten kombiniert werden
- Betreuer erhalten TPops aller Arten. Das überfordert Google Earth (und ev. andere ähnliche Werkzeuge), zumindest wenn alle TPop des ganzen Kt. Zürich enthalten sind, deutlich. Und für jede Gemeinde eine Datei erzeugen bzw. zu laden ist für alle Beteiligten aufwändig und unbequem
- Es ist sehr schwierig bzw. schlecht möglich, weitere Daten gut zu kombinieren, z.B. Massnahmen
- Google Earth bzw. kml-Dateien haben in meinem Empfinden an Bedeutung verloren

Ich glaube, wir können bessere Produkte schaffen. Hier nur ein paar Ideen:
1. **kml oder gpx Dateien, die auch auf https://map.geo.admin.ch geöffnet werden können**. 
Vor- und Nachteile: 
   - Es können andere Layer kombiniert werden. 
   - sogar die via WMS verfügbaren Daten von z.B. Schutzverordnungen des Kt. ZH können kombiniert werden. Beispiel noch ohne apflora-Daten: https://s.geo.admin.ch/88fb41992e
   - Man muss es lernen. Aber dann geht es recht schnell und einfach (Anleitung: https://help.geo.admin.ch/?ids=62&lang=de)
   - Ev. kann eine art Vorlage erzeugt werden (ähnlich https://s.geo.admin.ch/88fb41992e), welche alle normalerweise wesentlichen Layer des Kt. Zürich enthält
   - Das aktuell produzierte kml-Format funktioniert leider nicht auf https://map.geo.admin.ch
   - Leider funktioniert das nicht auf https://maps.zh.ch
   - apflora-Daten müssen wiederholt exportiert und importiert werden
2. **Exporte in GIS-lesbaren Formaten** (z.B. GeoJSON), die z.B. in QGIS mit beliebigen anderen lokal oder via Internet verfügbaren Daten kombiniert werden können. 
Vor- und Nachteile:
   - Daten können beliebig mit eigenen oder im Internet verfügbaren verknüpft werden
   - grosse Datenmengen sind wenig problematisch
   - mehr Fachwissen nötig
   - für NBA aufwändiger
   - apflora-Daten müssen wiederholt exportiert und importiert werden
   - wir könnten eine QGIS-Vorlage erstellen für NBA, welche sich zwar QGIS zutrauen, nicht aber die Konfiguration oder einfach sehen wollen, wie Daten aus verschiedenen Quellen kombiniert werden können
   - ich weiss nicht, wie gut das für anderen GIS funktioniert und kann das mangels Lizenzen nicht testen
3. **Direkt-Zugriff auf die Daten:** NBA mit GIS (ev. auch anderen dazu fähigen Werkzeugen) erhalten Logins mit klar definierten Rechten für die Datenbank von apflora. Sie greifen also direkt von ihrem GIS auf sie zu. Und können für sie vorbereitete Views benutzen. 
Vor- und Nachteile:
   - Daten können beliebig mit eigenen oder im Internet verfügbaren verknüpft werden
   - grosse Datenmengen sind kein Problem
   - NBA verfügen immer über aktuelle Daten
   - In QGIS ist das sehr einfach und schnell möglich
   - Fachwissen nötig
   - für NBA aufwändiger
   - wir könnten eine QGIS-Vorlage erstellen für NBA, welche sich zwar QGIS zutrauen, nicht aber die Konfiguration oder einfach sehen wollen, wie Daten aus verschiedenen Quellen kombiniert werden können
   - ich weiss nicht, wie gut das für anderen GIS funktioniert und kann das mangels Lizenzen nicht testen
4. **Eigener Zugang auf apflora.ch**, der genau die benötigten Daten in geeigneter Art anbietet (nach dem Vorbild der EKF). Primär (oder auch) via die Karte. 
Vor- und Nachteile: 
   - apflora-Daten wie z.B. Massnahmen können sehr gut integriert werden
   - immer aktuell 
   - kleiner Aufwand für NBA
   - mit anderen Daten verknüpfbar, aber nicht durch NBA selbst
   - hoher Aufwand für mich
   - wenn keine andere Variante kombiniert wird, können NBA apflora-Daten nicht mit eigenen kombinieren

Variante 1. entspricht ungefähr der heutigen mit kml-Datei, wenn wir sie https://map.geo.admin.ch-fähig machen können. Wobei das Problem der Datenmengen bleibt.

Varianten 1. bis 3. sind für mich grob gesagt ähnlich aufwändig. Wobei es viel Aufwand gibt, wenn pro Gemeinde Dateien erzeugt werden müssen. 4. ist natürlich am aufwändigsten.

Varianten 2. und 3. sind ähnlich, wobei 3. vermutlich deutlich obenauf schwingt.

Was ich nicht weiss: **Gibt es unter den NBA solche, die viel mit GIS arbeiten? Und welche die für sie aufwändigeren Varianten (z.B. 3.) nutzen würden oder gar möchten?**

Wenn das für alle zutrifft, wäre wohl Variante 3. mit Abstand am besten und erst noch verhältnismässig wenig aufwändig umzusetzen.

Ansonsten müssen wir wohl Variante 1. oder 4. mit 3. kombinieren.

Was meint ihr?

**Comment by kmarti** [comment]
Sorry, für die späte Rückmeldung. Bei so ausführlichen Inputs von Dir, dauert es meist etwas länger, bis ich reagiere...

Ziele: 
1. Die NBA müssen wissen, in welchen ihrer Gebiete TP von AP-Arten sind.
2. sind die TP ursprünglich oder angesiedelt
3. bisherige Massnahmen
4. artspezifische generelle Schnittzeitpunkte (dazu gibt es eine Tabelle)
Der 1. Punkt ist der wichtigste, der 2. Punkt ist auch wichtig, die übrigen sind wünschbar.
Die NBA sollten diese Infos mit den Schutzgebietsplänen und den Pflegeplänen überlagern können.

Eigentlich können die NBA alle diese Infos (ausser Punkt 3 und 4) aus dem GIS-Browser herauslesen und dort auch mit den Schutzgebietsplänen und Pflegeplänen überlagern. Wir wissen aber, dass nicht alle NBA den GIS-Browser häufig/überhaupt für die AP-Arten konsultieren. Ausserdem ist es aufwändig, eine Uebersicht zu erhalten, da jeder Punkt (TP) einzeln angeklickt werden muss, um zu sehen, um was es sich handelt. Deshalb wollten wir den NBA einmal im Jahr die aktualisierten Infos zu den AP-Arten speziell für ihre Gebiete quasi auf dem Silbertablett liefern.

Ich denke, dass wir den Aufwand für diese Aufgabe nicht zu gross werden lassen sollten. Vielleicht genügt ein kml-Export (mit allen Arten), wo die TP mit Art-Name angeschrieben sind pro Gemeinde oder pro Gebiete eines/r NBA mit der Aufforderung, sich die detaillierten Angaben im GIS-Browser anzusehen.

**Comment by barbalex** [comment]
> Vielleicht genügt ein kml-Export (mit allen Arten), wo die TP mit Art-Name angeschrieben sind pro Gemeinde oder pro Gebiete eines/r NBA mit der Aufforderung, sich die detaillierten Angaben im GIS-Browser anzusehen

Pro Gemeinde wäre das sowohl für mich/uns wie auch für die NBA sehr aufwändig. Angesichts des begrenzten Nutzens glaube ich nicht, dass das sinnvoll wäre bzw. dass die NBA das auch genügend benutzen würden. Aber es liegt nicht an mir, das zu beurteilen.

Vielleicht bringt es etwas, wenn ein kml-Datei für alle Betreuungsgebiete einer NBA geliefert würde. Auch das ist aber etwas aufwändig. Und ich weiss nicht, ob Google-Earth das immer brauchbar präsentiert - immerhin ist es, wenn alle TPop des Kantons exportiert werden, sehr deutlich überfordert.

> Die NBA sollten diese Infos mit den Schutzgebietsplänen und den Pflegeplänen überlagern können

Das ermöglicht ein kml nicht. Aber alle anderen Lösungen.

So wie du es beschreibst, tönt es eher nach Lösung 4: Denn man muss offenbar die NBA dazu bringen, es zu machen. Und dann muss der Aufwand so kein wie möglich sein.

Trotzdem fände ich es nützlich, zusammen mit den NBA abzuklären, ob Lösung 3 für sie bzw. eine lohnende Teilmenge von ihnen nützlich wäre. Denn sollten sie klar definierte GIS-Arbeitsabläufe haben (was impliziert, dass sie GIS fast professionell einsetzen), dann wäre das für sie mit Abstand am nützlichsten.

**Comment by rebeccakurz** [comment]
Hoi Alex

Karin und ich haben diesen Issue gerade nochmals zusammen besprochen und sind zum Schluss gekommen, dass wir im Moment auf ein solches Produkt verzichten möchten, da der Aufwand ja relativ gross und der Nutzen vielleicht nicht so gross ist, je nachdem wie die NBAs es nutzen. 
Wir werden dafür jeweils eine Meldung an die NBAs machen, wenn die neuesten Daten auf dem GIS-Browser aufgeschaltet werden und dass sie sich das doch anschauen könnten. 
Aber vielen Dank für deine Vorschläge und vielleicht wird einer davon dann doch noch aktuell.
