### ISSUE TITLE
Fehlermeldung letzte Anpassungen

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#381]
Hoi Alex
Ich habe einen neuen Benutzer angelegt, um die Zugangsbeschränkungen zu testen. Bei einem neuen Benutzer erscheinen als erstes alle letzten Anpassungen, was eine ziemliche Liste ist. Wenn ich nun aber "alle ok" drücken will, erscheint eine Fehlermeldung (siehe Screenshot). Auch wenn ich bei den einzelnen "ok" drücken will, erscheint diese. Browser öffnen und wieder schliessen bringt nichts, Seite aktualisieren auch nicht...
![Bildschirmfoto 2020-05-05 um 10 21 05](https://user-images.githubusercontent.com/30288503/81047460-b631ce00-8eba-11ea-9f94-6bfe83129618.png)

**Comment by rebeccakurz** [comment]
Ich denke das hat sich erledigt.

**Comment by barbalex** [comment]
Hängt das ev. mit https://github.com/barbalex/apf2/issues/252#issuecomment-623987126 zu tun? (Ich muss immer noch eine Lösung für das zugrundeliegende Problem finden)

War das HeikoSchindler? Ich sehe in er Datenbank, dass sein Passwort unverschlüsselt ist. Man müsste es neu setzen, damit es verschlüsselt wird.

Welcher Benutzer ist das?

**Comment by rebeccakurz** [comment]
nein, ich hatte extra einen neuen Benutzer gemacht, damit ich den Status "apwriter" testen konnte. Ich habe ihn aber wieder gelöscht.

**Comment by rebeccakurz** [comment]
Nach ein paar mal öffnen und schliessen des Browsers hat es dann funktioniert, vielleicht war einfach der Browser überlastet

**Comment by barbalex** [comment]
Ich vermute, dein Benutzer hatte keine Rolle. Dann scheitert es
