### ISSUE TITLE
Fehlermeldungen/Performance beim Filtern

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#382]
Hoi Alex

Ich bin gerade am die einzelnen Aktionspläne in der FloraDB am Durchgehen, da es noch Anpassungen bei den Zugriffsrechten gibt. 
Nun ist mir aufgefallen, dass die Anwendung recht langsam ist. Es geht ziemlich lange, bis der gefilterte Aktionsplan erscheint. 
Zudem kommt immer mal wieder eine Fehlermeldung (siehe Screenshot). Kann man da evt. etwas machen?
(Kann es sein, dass es so langsam ist, weil ich auf Firefox arbeite und nicht auf Chrome? Kann das noch ausprobieren)
Danke!
![apflora v1 41 2 - Mozilla Firefox 05 05 2020 11_29_13 (2)](https://user-images.githubusercontent.com/30288503/81052874-85ef2d00-8ec4-11ea-9650-f60e135c3c82.png)

**Comment by rebeccakurz** [comment]
hmm auf Chrome ist es nicht wesentlich schneller. Zudem habe ich ebenfalls diese Fehlermeldung bekommen. 
![apflora v1 41 2 - Google Chrome 05 05 2020 11_46_21](https://user-images.githubusercontent.com/30288503/81053962-36116580-8ec6-11ea-9b39-616a0b16a291.png)

**Comment by barbalex** [comment]
Offenbar war der Server da gerade ausserordentlich stark belastet:
<img width="548" alt="6h" src="https://user-images.githubusercontent.com/669783/81072668-c495df00-8ee6-11ea-86a3-b2a946b6f676.png">

Als Gegensatz dazu die Belastung innerhalb der letzten 30 Tage:
<img width="547" alt="30t" src="https://user-images.githubusercontent.com/669783/81072729-daa39f80-8ee6-11ea-9c72-36ee2ebffaaf.png">

Zu sehen ist:
- Im 30-Tage-Fall wurde der heutige Tag (noch) nicht dargestellt
- In den letzten 30 Tagen war die Belastung ein einziges Mal so hoch wie heute
- Heute scheint die Belastung generell ausserordentlich hoch zu sein. Das könnte die von dir beobachtete Langsamkeit verursachen

Hast du eine Ahnung, ob heute spezielle Sachen gemacht werden? Z.B. belastende Exporte, häufiger Aufruf von Statistiken, Qualitätskontrollen...

Theoretisch könnte auch ein kürzliches Update oder sonstige Änderung das Problem verursachen.

**Comment by barbalex** [comment]
Ich habe versuchsweise mal die Eier-legende-Wollmilchsau exportiert. Das hat den Server während ca. 5 Minuten an den Anschlag gebracht. Es ist dann nicht so, dass _nichts_ mehr geht. Aber bestimmt läuft es langsamer.

Es war schon immer eine Idee, für Auswertungen einen "slave" auf einem unabhängigen Server zu benutzen. Also eine zweite Datenbank, welche mit der ersten synchronisiert ist. Einfach immer ein paar Sekunden hintendrein.

Belastende Abfragen würden dann dem slave geschickt. Der dann damit den Server, der die App beliefert, nicht belasten würde.

Wenn solche Probleme häufiger auftreten sollten, müssten wir das wohl machen.

**Comment by barbalex** [comment]
Hier die Belastung durch die Eier-legende Wollmilchsau:
<img width="549" alt="ewm" src="https://user-images.githubusercontent.com/669783/81075156-46d3d280-8eea-11ea-9c57-4414282d80eb.png">

**Comment by rebeccakurz** [comment]
Ich denke eine Erklärung wäre das heutige Regenwetter = alle sind an der Büroarbeit und nicht im Feld -> apflora wird häufiger genutzt. 
Wäre mal noch spannend ob das auch an anderen Tagen der Fall ist...
Das mit der Auslagerung von belastenden Anfragen wäre wahrscheinlich eine Überlegung wert.

**Comment by rebeccakurz** [comment]
Oh ja da ist apflora aber ganz schön am Anschlag mit der Eier-legenden Wollmilchsau!

**Comment by barbalex** [comment]
Hier die Belastung in den letzten zwei Wochen:
<img width="869" alt="2020-08-28_13h33_31" src="https://user-images.githubusercontent.com/669783/91556686-6bd5d080-e933-11ea-94c2-dc0a6a7423d6.png">
<img width="873" alt="memory" src="https://user-images.githubusercontent.com/669783/91556696-6d9f9400-e933-11ea-868d-898f13c63d91.png">

Es scheint, dass Arbeitsspeicher kein Problem ist. Die CPU hingegen wird an gewissen Tagen deutlich stärker ausgelastet.
Falls nun im Herbst die durchschnittliche Belastung der CPU spürbar steigen sollte, müssen wir uns ev. überlegen, einen Server mit mehr CPU zu benutzen.

**Comment by barbalex** [comment]
Schliesse das, weil seit über einem Jahr inaktiv
