### ISSUE TITLE
Dateien hochladen scheitert

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#383]
Hoi Alex
Ich wollte nun einen Aktionsplan bei einer Aktionsplanart in der FloraDB in die Dateien hochladen. Leider hat das nicht geklappt (siehe Screenshot). Habe es auch noch bei einer anderen Art ausprobiert und auch noch mit einem Foto, also mit einem anderen Dateiformat, das hat auch nicht geklappt.
Könntest du dir das mal anschauen? Danke!
<img width="478" alt="Bildschirmfoto 2020-05-20 um 07 37 55" src="https://user-images.githubusercontent.com/30288503/82409172-7697e400-9a6d-11ea-95e0-edd8034340f5.png">

**Comment by barbalex** [comment]
Was für eine Datei war das? Bei mir hat es soeben geklappt

**Comment by rebeccakurz** [comment]
Es war eine pdf-Datei. ich habe es soeben nochmals probiert, hat immer noch nicht geklappt.
Bei Aldrovanda vesiculosa, folgende Datei:
[Aldrovanda_vesiculosa_AP.pdf](https://github.com/barbalex/apf2/files/4655527/Aldrovanda_vesiculosa_AP.pdf)
Wir möchten ja alle Aktionspläne und ihre Anhänge in der FloraDB hochladen.

**Comment by barbalex** [comment]
Hat bei mir sofort geklappt. Siehe: https://apflora.ch/Daten/Projekte/e57f56f4-4376-11e8-ab21-4314b6749d13/Aktionspl%C3%A4ne/6c52d174-4f62-11e7-aebe-67a303eb0640?apTab=dateien&feldkontrTab=entwicklung&idealbiotopTab=idealbiotop&popTab=pop&projekteTabs=tree&projekteTabs=daten&qkTab=qk&tpopTab=tpop&tpopmassnTab=tpopmassn

**Comment by barbalex** [comment]
Bzw. https://apflora.ch/Daten/Projekte/e57f56f4-4376-11e8-ab21-4314b6749d13/Aktionspl%C3%A4ne/6c52d173-4f62-11e7-aebe-2bd3a2ea4576?apTab=dateien&feldkontrTab=entwicklung&idealbiotopTab=idealbiotop&popTab=pop&projekteTabs=tree&projekteTabs=daten&qkTab=qk&tpopTab=tpop&tpopmassnTab=tpopmassn

**Comment by rebeccakurz** [comment]
Tatsächlich... was mache ich falsch?

**Comment by barbalex** [comment]
Wenn du es machst und es wieder nicht klappt: Kannst du ev. mit der F12-Taste die Konsole öffnen und im Register "Console" schauen, ob dort ein Fehler gemeldet wird?

**Comment by barbalex** [comment]
Sorry, muss zum Coiffeur

**Comment by rebeccakurz** [comment]
übrigens, Kaspar Spörri hat mich vorher angerufen, er wollte eigentlich mit dir sprechen, aber hat dich nicht erreicht...

**Comment by rebeccakurz** [comment]
er wollte alle Teilpopulationen eines bestimmten Gebiets erhalten, du hättest ihm mal einen Link geschickt, aber der funktioniere nicht mehr... ich weiss leider nicht genau welche Funktion er meint...

**Comment by rebeccakurz** [comment]
Jetzt klappt es einwandfrei mit dem Hochladen! Danke

**Comment by barbalex** [comment]
Liegt das an der Internet Verbindung? Die Datei ist recht gross

**Comment by rebeccakurz** [comment]
Hm vielleicht... Aber ich habe nicht an der Verbindung geändert und jetzt klappt es...

**Comment by barbalex** [comment]
Gerade darum meine ich dass: Datei und Code sind gleich. Die Verbindung kann sekündlich ändern. Grosse Upload werden davon betroffen. Upload viel mehr als Downloads

**Comment by rebeccakurz** [comment]
Okay, aber ich habe extra noch versucht auch ein Bild (also jpg) hochzuladen, da ich dachte, es liege evt an der Grösse des pdfs, das hat aber auch nicht geklappt...

**Comment by rebeccakurz** [comment]
Es hat überall geklappt mit dem Hochladen der Aktionspläne ausser bei Saxifraga granulata. Dort habe ich vorgängig versucht ein Foto hochzuladen, (was zuerst ja nicht funktioniert hat, aber nachdem du den ersten Aktionsplan hochgeladen hast, hat auch das Hochladen des Fotos geklappt.)
Nun kann ich hier aber gar nichts mehr hochladen, aber es kommt auch nicht die Fehlermeldung wie zu Anfang. Habe F12 mal gedrückt, kann aber leider wenig mit den Angaben da anfangen...
https://apflora.ch/Daten/Projekte/e57f56f4-4376-11e8-ab21-4314b6749d13/Aktionspl%C3%A4ne/6c52d2f0-4f62-11e7-aebe-138e69662b58?apTab=dateien&feldkontrTab=entwicklung&idealbiotopTab=idealbiotop&popTab=pop&projekteTabs=tree&projekteTabs=daten&qkTab=qk&tpopTab=tpop&tpopmassnTab=tpopmassn

**Comment by rebeccakurz** [comment]
okay, hat jetzt doch geklappt. Vielleicht liegt es ja tatsächlich an meiner Internetverbindung...
