### ISSUE TITLE
Fehlermeldungen bei TPop Löschversuch

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#384]
Hoi Alex
Ich wollte soeben eine Teilpopulation löschen (die ich selbst angelegt hatte). Dabei kamen folgende Fehlermeldungen und ich konnte die TPop nicht löschen:
<img width="1895" alt="Bildschirmfoto 2020-05-25 um 15 05 19" src="https://user-images.githubusercontent.com/30288503/82815428-76e31580-9e99-11ea-93c7-985753027e61.png">

**Comment by barbalex** [comment]
Tja, da hab ich Mist gebaut. Werde ich heute noch korrigieren. Danke für die Meldung.

**Comment by barbalex** [comment]
Es müsste jetzt bei TPop klappen. Muss das noch bei den anderen Tabellen mit history korrigieren und schliessen danach den Issue.

**Comment by barbalex** [comment]
O.k., sollte jetzt überall klappen

**Comment by rebeccakurz** [comment]
okay, danke!
