### ISSUE TITLE
EKF-Formulare erstellen funktioniert nicht

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#387]
Hoi Alex

Ich habe heute morgen eine neue Freiwillige bei den Adressen (Angelika Müller) und als Benutzerin (amüller) erfasst. Danach habe ich drei Freiwilligen-Erfolgskontrollen (Oenanthe lachenalii 52.1, Teucrium scordium 81.1, Inula helvetica 112.1) erstellt und sie als Bearbeiterin eingesetzt. Nun erscheint aber unter den Benutzern bei ihrem Namen keine Schaltfläche um die Protokollblätter zu erstellt... Auch nach mehrmaligem Aktualisieren hat es nicht geklappt. 
Ich habe es jetzt auch noch mit anderen Benutzern und bei anderen Arten versucht, da klappt es jedoch auch nicht. 
Könntest du dir das bitte anschauen?

**Comment by barbalex** [comment]
Ich glaube, es gibt ein Missverständnis.

Beim Benutzer kann man:

- EKF-Formulare öffnen, die mit einem Datum oder Jahr erfasst wurden
- EKF-Formulare erzeugen, **wenn die Kontrolleurin in Teil-Populationen als EKF-Kontrolleurin erfasst ist** und es solche TPops gibt, die noch keine Kontrolle für dieses Jahr haben. Die so erzeugten EKF's erhalten ein Jahr und können somit danach über die erste Funktion geöffnet werden

In diesem Fall hast du offenbar die Kontrollen manuell erzeugt, ohne die Benutzerin in der TPop als EKF-Kontrolleurin zu erfassen. Wenn man eine solche Kontrolle manuell erfasst, kann man kein Jahr setzen - denn es gibt nur das Datum-Feld und das wird ja erst ausgefüllt, wenn die Kontrolleurin erfasst, wann sie kontrolliert hat. Darum erschien auch keine Schaltfläche, um die existierenden Kontrollen zu öffnen.

Du solltest also künftig besser:

- **in den betreffenden TPops die Kontrolleurin als Kontrolleurin erfassen**
- Bei der Benutzerin den jetzt sichtbaren Knopf benutzen, um für dieses Jahr die Kontrollen zu erstellen
- Bei der Benutzerin den jetzt sichtbaren Knopf benutzen, um die Kontrollen zu öffnen

Das ist in der Dokumentation beschrieben: https://apflora.ch/Dokumentation/Benutzer/Erfolgs-Kontrollen-Freiwillige/#1-artverantwortliche-oder-managerin-bereitet-freiwilligen-feldarbeit-vor

Du kannst aber auch im jetzigen Zustand die Kontrollen von Angelika Müller öffnen: Im "Mehr"-Menu oben rechts "EKF sehen als..." wählen.

Dort kannst du dann auch diese Kontrollen drucken: 
[apflora angelika müsser formulare.pdf](https://github.com/barbalex/apf2/files/4845801/apflora.angelika.musser.formulare.pdf)

**Comment by rebeccakurz** [comment]
Lieber Alex

Du hast natürlich recht, ich glaube ich bin etwas verwirrt... Ich habe auch in der Dokumentation nachgeschaut, aber irgendwie habe ich dort eine alte Version erwischt.
Unglaublich, habe das diesen Frühling ja x-mal schon gemacht! Entschuldige, dass ich dich damit belästigt habe und danke für deine Antwort!!

**Comment by barbalex** [comment]
In v1.41.5 kann man bald bei der Benutzerin auch EKF öffnen, wenn sie kein Datum haben (kein Datum wird als aktuelles Jahr interpretiert).

Voraussetzung bleibt aber, dass die Benutzerin in der TPop als EKF-Kontrolleurin erfasst ist.
