### ISSUE TITLE
"Biotop", Bereich Boden von der Feldkontrolle zur Teilpopulation zügeln

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#388]
Hoi Alex
Nach den Eingaben der Erfolgskontrollen hat Anna sich gefragt, ob es nicht mehr Sinn machen würde, das "Biotop" unter den Teilpopulationen zu haben und nicht bei den einzelnen Feldkontrollen? Denn zumindest der Teil mit dem Boden ändert ja eigentlich nicht mehr und die Vegetation könnte laufend angepasst werden, wenn sie sich über die Jahre verändert. 
Wäre das möglich und wie gross wäre der Aufwand? (Allenfalls könnte man es auch erst nächstes Jahr umsetzen, pressiert nicht).
<img width="980" alt="Bildschirmfoto 2020-07-09 um 08 04 11" src="https://user-images.githubusercontent.com/30288503/87002892-daf83980-c1ba-11ea-949f-813e08f89372.png">
Liebe Grüsse
Rebecca

----------------------------------

EDIT von Alex: Ich ergänze die Lösung hier, damit sie in der Übersicht erscheint

### Folgendes wird umgesetzt

Die Felder des Biotop-Bereichs "Boden" (also "Typ", "Kalkgehalt" etc.) werden zu den Teilpopulationen gezügelt und dort nach der "Hangneigung" eingesetzt.

Es gibt diese Teil-Schritte:
- [x] Neuen Code-Branch erstellen, falls andere Code-Anpassungen dazwischen kommen sollten
- [x] 7 neue Felder in der Tabelle tpop schaffen
- [x] 7 neue Felder im Formular tpop schaffen
- [x] 7 Abfragen erzeugen, welche die Daten aus den Feldkontrollen zusammenfassen und in diese Felder einfügen
- [x] Prüfen, ob die Abfragen wie gewünscht funktionieren
- [x] Alle Code-Bezüge auf die bisherigen Felder anpassen
- [x] Die 7 alten Felder in allen Views, Funktionen, GraphQL-Abfragen etc. entfernen
- [x] Die 7 neuen Felder in allen Views, Funktionen, GraphQL-Abfragen etc. ergänzen, welche alle Felder der TPop aufrufen
- [x] Die 7 alten Felder aus dem Formular Feldkontrolle entfernen
- [x] Die 7 alten Felder aus der Tabelle tpopfeldkontr entfernen
- [x] Alle Daten-Anpassungen in der Entwicklungs-Umgebung vorbereiten
- [x] Neue App live setzen und parallel alle Daten-Anpassungen in der produktiven Umgebung ausführen
- [x] Den GraphQL-Server neu starten, damit er die Änderungen aufnimmt
- [x] Den Code-Branch in den master überführen
- [x] Über die Anpassung informieren (Mitteilung in apflora, issue)
- [x] Historisierte TPop anpassen und deren Erzeugung

**Comment by barbalex** [comment]
Richtig, das habe ich vor Jahren Karin gefragt - damals, als sie ergänzt wurden.

Die Daten wären bei der TPop am richtigen Ort.

Es gibt aber eine unbekannte Anzahl von Datensätzen, die jetzt in eine TPop kombiniert werden müssen.

Wir müssen also nicht nur die Strukturen umbauen. Sondern auch irgendwie die Daten migrieren. Was mindesten ebenso viel Arbeit ist. Wenn nicht viel mehr.

Ich werde einmal versuchen, mit Abfragen herauszufinden, wie gross dieses Problem ist.

**Comment by kmarti** [comment]
Es gibt Teile, wie Lebensraum nach Delarze, Umgebung nach Delarze, Vegetationstyp, sowie das ganze Kapitel Boden, die zur Beschreibung der Teilpopulation gestellt werden könnten. Es war aber schon die Idee, dass bei der EK eben auch die Entwicklung des Biotopes angeschaut und festgehalten wird, insbesondere Konkurrenz, Deckungen der Moos-, Kraut- und Strauchschicht und v.a. der Handlungsbedarf. Diese Punkte müssen also bei der EK bleiben. Wenn diese bei der Teilpopulation sind und einfach angepasst werden, ist der Vergleich der TP-Entwicklung mit der Biotopentwicklung nicht mehr möglich. (Das bedingt natürlich, dass die Angaben zum Biotop überhaupt ausgefüllt werden).

**Comment by barbalex** [comment]
Heute habe ich die Daten ausgewertet. Hier das Ergebnis für die 4'155 EK's:

<img width="857" alt="tpop" src="https://user-images.githubusercontent.com/669783/87167012-a8d6fc80-c2cc-11ea-9b3a-44104beb6fc9.png">

Und hier für die 9'151 EK's:
<img width="962" alt="ek" src="https://user-images.githubusercontent.com/669783/87167396-30247000-c2cd-11ea-9fa6-b547a279a91c.png">

Man sieht:

- dieselbe Art Information wurde bis zu 8 mal pro TPop erhoben,
- ...meistens (in 56% aller TPop) aber gar nicht
- am häufigsten wurden Informationen zum Boden erhoben (39% aller TPop) und darin zum Wasserhaushalt (36% aller TPop)

Es war übrigens 3 Stunden Arbeit, diese Daten auszuwerten. Ich sag das nur, damit ihr einschätzen könnt, wie aufwändig es ist.

**Comment by rebeccakurz** [comment]
Hoi Alex

Ich habe es noch mit Karin besprochen. Und wir möchten gerne, dass der "Boden" (also "Typ", "Kalkgehalt" etc.) zu den Teilpopulationen gezügelt wird und dort nach der "Hangneigung" eingesetzt wird. Es gibt dann dort halt ein paar zusätzliche Zeilen. 
Den Rest würden wir gerne beim Biotop belassen. 
Vielleicht müsstet du das in den nächsten Budgetentwurf einnehmen, falls es aufwändiger ist.

Vielen Dank!

**Comment by barbalex** [comment]
> wir möchten gerne, dass der "Boden" (also "Typ", "Kalkgehalt" etc.) zu den Teilpopulationen gezügelt wird und dort nach der "Hangneigung" eingesetzt wird

Danke für die klare Vorgabe.

Bleibt nur noch zu regeln, was passiert, wenn ein Feld in mehreren Feldkontrollen beschrieben wurde.
Varianten:
1. den jüngsten Wert übernehmen
2. alle Werte kommagetrennt hintereinander schreiben und jeweils das Datum voranstellen
3. alle Werte kommagetrennt hintereinander schreiben und jeweils das Datum voranstellen
  aber wenn mehrmals der genau gleiche Text erhoben wurde: Diesen Wert nur ein mal aufführen, dafür mehrere Daten auflisten (falls ich das schaffe)

Was meinst du?

**Comment by rebeccakurz** [comment]
Der Vorschlag Nummer 3 wäre wohl am übersichtlichsten und doch vollständig. Falls du ihn umsetzen kannst. Sonst Vorschlag Nummer 2.

**Comment by barbalex** [comment]
Folgendes wird also umgesetzt:

Die Felder des Biotop-Bereichs "Boden" (also "Typ", "Kalkgehalt" etc.) werden zu den Teilpopulationen gezügelt und dort nach der "Hangneigung" eingesetzt.

Es gibt diese Teil-Schritte:
- [ ] Neuen Code-Branch erstellen, falls andere Code-Anpassungen dazwischen kommen sollten
- [ ] 7 neue Felder in der Tabelle tpop schaffen
- [ ] 7 neue Felder im Formular tpop schaffen
- [ ] 7 Abfragen erzeugen, welche die Daten aus den Feldkontrollen zusammenfassen und in diese Felder einfügen
- [ ] Prüfen, ob die Abfragen wie gewünscht funktionieren
- [ ] Alle Code-Bezüge auf die bisherigen Felder anpassen
- [ ] Die 7 alten Felder in allen Views, Funktionen, GraphQL-Abfragen etc. entfernen
- [ ] Die 7 neuen Felder in allen Views, Funktionen, GraphQL-Abfragen etc. ergänzen, welche alle Felder der TPop aufrufen
- [ ] Die 7 alten Felder aus dem Formular Feldkontrolle entfernen
- [ ] Die 7 alten Felder aus der Tabelle tpopfeldkontr entfernen
- [ ] Alle Daten-Anpassungen in der Entwicklungs-Umgebung vorbereiten
- [ ] Neue App live setzen und parallel alle Daten-Anpassungen in der produktiven Umgebung ausführen
- [ ] Den Code-Branch in den master überführen
- [ ] Über die Anpassung informieren (Mitteilung in apflora, issue)

**Comment by barbalex** [comment]
Ist umgesetzt.
