### ISSUE TITLE
Voreinstellung Strukturbaum: nur AP-Arten 

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#389]
Hoi Alex

Noch ein Wunsch der Artverantwortlichen: Sie möchten gerne, dass im Strukturbaum die Voreinstellung ist, dass nur AP-Arten angezeigt werden und dass man alle Arten aktiv anwählen muss. (Also genau umgekehrt als jetzt). Da meistens mit den AP-Arten gearbeitet wird, macht das durchaus Sinn. 
Falls es einfach/schnell umzusetzen ist, dann gerne umsetzen und sonst in nächsten Budget-Entwurf aufnehmen. 

Vielen Dank und liebe Grüsse
<img width="658" alt="Bildschirmfoto 2020-07-15 um 12 15 17" src="https://user-images.githubusercontent.com/30288503/87533796-6aa75780-c695-11ea-84b0-a176a969a834.png">

**Comment by barbalex** [comment]
Hoi Rebecca

Das wird in v1.41.6 so sein. ABER:

- Die Artverantwortlichen mussten diesen Wert nur ein mal ändern, weil apflora sich diese Einstellung pro Browser auf Computer merkt (siehe: https://apflora.ch/Dokumentation/Benutzer/Ged%C3%A4chtnis/)
- Genau deshalb wird sich diese Änderung erst bei Neu-Anmeldungen auswirken

Herzliche Grüsse
Alex
