### ISSUE TITLE
"Neu laden" mit Absturz

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#39]
Wollte "neu laden". Geht nur im rechten Fenster, links im Strukturbaum kann man diese Funktion nicht über rechte Maustaste haben.

Nach "neu laden" fliegt man aber aus der FloraDB raus. Neu anmelden auf diesem Fenster geht nicht (es passiert einfach nichts):

![bildschirmfoto 2017-06-02 um 14 08 58](https://cloud.githubusercontent.com/assets/6047564/26725174/938acde6-479d-11e7-967c-88e753b789c1.png)

**Comment by barbalex** [comment]
richtig - das ist eine Nebenwirkung davon, dass die neue Version noch unter v2 läuft.
Das gibt sich, sobald die alte Version abgeschaltet wird
