### ISSUE TITLE
Qualitätskontrollen: Voreinstellungen ändern

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#390]
Hoi Alex 
Als ich vor Kurzem die Qualitätskontrolle durchlaufen liess habe ich mich schon gefreut, da es offenbar nichts zu meckern gibt - bis ich dann gemerkt habe, dass gar keine Qualitätskontrolle angehäkelt war (also 0/100, siehe Screenshot).
Also habe ich noch bei anderen Arten nachgeschaut und anscheinend ist das bei allen so!
Könntest du das bitte ändern, so dass als Voreinstellung alle Qualitätskontrollen angehäkelt sind und man aktiv eine abwählen muss, wenn man das will? (Ich glaube es war vorher so). 
Danke!
<img width="1023" alt="Bildschirmfoto 2020-07-15 um 12 20 23" src="https://user-images.githubusercontent.com/30288503/87534243-09cc4f00-c696-11ea-947b-9d446a383f7a.png">

**Comment by barbalex** [comment]
Sorry. Weiss nicht, wie das gekommen ist. Jetzt sind bei allen Arten wieder alle QK gesetzt
