### ISSUE TITLE
Suche im Strukturbaum - Daten laden sehr langsam

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#392]
Hoi Alex

Ich habe mal wieder eine Meldung zur Performance der Flora DB. 
Wenn ich im Strukturbaum nach einer Art oder eine Ebene tiefer nach einer Population suchen möchte, ladet die Seite nach jedem Buchstaben, den ich eingebe, die Daten. Das braucht sehr viel Zeit und ich kann auch nur einen Buchstaben nach dem anderen eingeben. Wenn ich schneller schreibe, dann wird einfach ein Teil des Wortes nicht "geschluckt". 
Könntest du dir mal anschauen, was das für einen Grund haben könnte und ob es verbessert werden kann?

Vielen Dank und liebe Grüsse
Rebecca

**Comment by rebeccakurz** [comment]
Das ist übrigens sowohl im Büro so als auch bei mir zu Hause (und auch bei Anna zu Hause lädt es sehr langsam).

**Comment by barbalex** [comment]
Ja: Das Werkzeug, dass Daten lädt, wurde aktualisiert. Offenbar hat es undokumentiert sein Verhalten verändert 😢 

Das muss ich mal angehen, wenn ich ein paar Stunden frei schaufeln kann.

**Comment by rebeccakurz** [comment]
Okay, danke.

**Comment by rebeccakurz** [comment]
Hoi Alex
Konntest du dir das bereits ansehen? Wenn nicht: Könntest du diesen Issue bitte prioritär behandeln? Danke!

**Comment by barbalex** [comment]
Ja, das ist mühsam

**Comment by barbalex** [comment]
Das zugrundeliegende Problem (das sich auch anderswo zeigt) habe ich noch nicht angegangen.

Ich habe aber die Filterung so angepasst, dass sie erst 0.6 Sekunden nach der letzten Eingabe aktiv wird. Das reduziert diesen Issue schon stark.

Wurde soeben mit v1.41.7 live gesetzt. Du kannst apflora neu starten, um das Update zu provozieren.

Das zugrundeliegende Problem gehe ich noch an.

**Comment by rebeccakurz** [comment]
Okay, danke, so ist es schon um einiges besser.

**Comment by barbalex** [comment]
Schliesse diesen Issue, weil ich für das überlagernde einen neuen Issue geschaffen habe: https://github.com/barbalex/apf2/issues/398
