### ISSUE TITLE
Dateien hochladen geht schief

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#394]
Hoi Alex
Auch das mit dem Dateien hochladen klappt leider nicht zuverlässig. Bei mir kommt immer wieder die Meldung, dass während des Hochladens etwas schief gegangen ist (siehe Screenshot). Aktuelles Beispiel: Ich wollte bei Liparis loeselii, TPop 90.1 ein Bild (ich hänge es dir an) hochladen.
<img width="1051" alt="Bildschirmfoto 2020-08-10 um 14 32 54" src="https://user-images.githubusercontent.com/30288503/89783134-b9ba9e00-db16-11ea-97b1-6784c1700fd9.png">
![Rüti_Moos_Liparis](https://user-images.githubusercontent.com/30288503/89783139-bb846180-db16-11ea-9bec-0b981cedc625.jpeg)

Könntest du dir das mal anschauen?

**Comment by barbalex** [comment]
Das hat bei mir beim ersten Versuch problemlos geklappt

**Comment by barbalex** [comment]
Wenn es nächstes Mal bei dir misslingt: Drück bitte die F12-Taste (öffnet die Dev-Tools von Chrome). Dann schau im Tab "console" nach, ob ein Fehler gemeldet wird.

Auf einem Mac ist es ev. eher die Kombination dieser Tasten: Cmd, Apfel, i

**Comment by rebeccakurz** [comment]
Okay, jetzt klappt es bei mir auch. Ich werde mich melden, falls es wieder nicht funktionieren sollte.
(Das letzte Mal war es auch so, dass es bei mir nicht geklappt hat, dann hast du etwas problemlos hochgeladen und dann hat es bei mir auch funktioniert - für eine gewisse Zeit)

**Comment by rebeccakurz** [comment]
Habe gerade nochmals probiert ein Bild hochzuladen, ging wieder nicht.
Thalictrum galioides, TPop 56.3, Feldkontrolle "Zwischenbeurteilung 2020"
![IMG_0706](https://user-images.githubusercontent.com/30288503/91408380-11117b80-e844-11ea-8016-8a0cca67f3a5.JPG)

**Comment by barbalex** [comment]
Hat bei mir geklappt.

Fragen:
- Wie oft lädst du Bilder hoch?
- Wie oft davon hast du Probleme?
- Ist das dann ein Problem, dass sich im selben Datensatz hartnäckig wiederholt?
- Oder kannst du, sobald das Problem auftritt, generell nirgends mehr Bilder hochladen?
- Hast du mal wie [oben](https://github.com/barbalex/apf2/issues/394#issuecomment-672746055) beschrieben in den Dev-Tools - geschaut, ob eine Fehlermeldung erscheint?

**Comment by rebeccakurz** [comment]
Habe es gerade nochmals versucht, klappt bei mir immer noch nicht. 
Wenn ich F12 drücke erscheint unter console das:
![Bildschirmfoto 2020-08-27 um 14 46 28](https://user-images.githubusercontent.com/30288503/91443926-4e8dfd00-e874-11ea-95ae-a86c51d6323f.png)
![Bildschirmfoto 2020-08-27 um 14 48 35](https://user-images.githubusercontent.com/30288503/91444001-69f90800-e874-11ea-8da2-3a0cb24d6f2c.png)
Kannst du damit etwas anfangen?
Ich lade nicht oft Bilder hoch, eigentlich nur um zu sehen ob es funktioniert. Bis jetzt hat es glaube ich nicht oft funktioniert. Das letzte mal hat es auch erst geklappt, als du das Bild hochgeladen hast, dann ging es bei mir nachher auch.

**Comment by barbalex** [comment]
Da gibt es eine unerhebliche Warnung, die so oft erfolgt, dass die Fehlermeldung nicht sichtbar ist.

Kannst du bitte, dort, wo "default levels" steht, den Filter so anpassen, dass "Warnings" nicht ausgegeben werden:
<img width="423" alt="2020-08-27_14h52_03" src="https://user-images.githubusercontent.com/669783/91444506-1e932980-e875-11ea-89fa-93ffb60611e0.png">

**Comment by rebeccakurz** [comment]
Habe ich gemacht, jetzt hat es geklappt mit dem Hochladen!

**Comment by barbalex** [comment]
Also diese Einstellung war nur dazu da, dass wir einen allfälligen Fehler finden können. Dass es jetzt geklappt hat, sollte nicht davon beeinflusst worden sein 🙄

**Comment by barbalex** [comment]
Schliesse, weil seit einem Jahr keine Aktivität
