### ISSUE TITLE
Eingaben müssen doppelt gemacht werden, weil Zählmethode rausfällt

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#395]
Hoi Alex

Karin Sartori hat gemeldet, dass sie einige Eingaben doppelt machen musste, da die Zählmethode oft rausgefallen ist (oder das Jahr). Beispiele, die sie zweimal eingeben musste:
cid:C3136C56-9C7D-484A-9DE0-6C09C71CCD74@home
Könntest du dir das mal anschauen? Da jetzt dann viele Eingaben gemacht werden müssen (EKs und Massnahmen), wäre es gut, wenn die Eingabemethode "verhebet".

LG

**Comment by rebeccakurz** [comment]
Hier die Beispiele
![Unknown](https://user-images.githubusercontent.com/30288503/91010277-841bb780-e5e2-11ea-817c-37059cd4affc.png)
![Unknown-1](https://user-images.githubusercontent.com/30288503/91010290-8847d500-e5e2-11ea-84d9-01a7d99127b3.png)

**Comment by barbalex** [comment]
Kannst du mir bitte die Beispiele so genau mitteilen, dass ich sie auch finden kann?

Mir ist z.B. nicht klar, was `cid:C3136C56-9C7D-484A-9DE0-6C09C71CCD74@home` ist.
Und die Liste aus der Qualitätskontrolle: Von welcher Art ist das?

**Comment by rebeccakurz** [comment]
-Mir ist z.B. nicht klar, was cid:C3136C56-9C7D-484A-9DE0-6C09C71CCD74@home ist.
Ich wollte hier den Screenshot von Karin hochladen, hat aber nicht geklappt, darum habe ich dann einen neuen Eintrag gemacht. Hätte ich vielleicht noch dazuschreiben sollen.
-Und die Liste aus der Qualitätskontrolle: Von welcher Art ist das?
Der erste Screenshot scheint von Filipendula vulgaris zu sein, der zweite von Daphne cneorum.

**Comment by barbalex** [comment]
> darum habe ich dann einen neuen Eintrag gemacht

Und was ist "ein neuer Eintrag"?

**Comment by rebeccakurz** [comment]
Von mir auch ein neuer Kommentar, wo ich dann die Screenshots hochgeladen habe die du oben siehst! 
-Mir ist z.B. nicht klar, was cid:C3136C56-9C7D-484A-9DE0-6C09C71CCD74@home ist.
Dieses cid:... bedeutet also gar nichts, sondern ist eine Art Fehlermeldung, weil das Hochladen des Screenshots nicht geklappt hat und ich es erst gemerkt habe, als ich den Kommentar schon abgeschickt hatte. Also musste ich einen zweiten Kommentar mit den Screenshots machen. Sozusagen das Pendant zum Anhang vergessen beim E-mail.

**Comment by barbalex** [comment]
Danke. Sorry, dass ich das nicht kapiert habe.

Ich kämpfe momentan damit, diesen Issue provozieren zu können. Bei mir hat es bisher immer geklappt.

**Comment by rebeccakurz** [comment]
Die Meldung kam ja von Karin Sartori. Ich habe jetzt bei meinen Arten noch nachgeschaut. Bei Thalictrum scheint es okay zu sein, aber bei Saxifraga granulata hat es auch einige Zählungen ohne Methode (siehe Screenshot). Es hat auch 3 Feldkontrollen ohne Zählung, aber dort könnte es auch sein, dass ich die Zählung vergessen habe...
![Bildschirmfoto 2020-08-27 um 15 59 10](https://user-images.githubusercontent.com/30288503/91452563-01635880-e87f-11ea-9007-c8487ddaa43b.png)
Bei Ophrys araneola hat es einige wenige:

![Bildschirmfoto 2020-08-27 um 16 08 25](https://user-images.githubusercontent.com/30288503/91453792-77b48a80-e880-11ea-82ae-9abd9e304d9f.png)
Könnte es sein, das es eine Zeitlang ein Problem war und jetzt wieder geht? (Saxifraga und Ophrys Eingaben waren so im Mai, Thalictrum erst im Juli.
Die Eingaben von Karin waren wahrscheinlich auch so im Mai/Juni.
Allerdings habe ich auch bei Liparis einige Meldungen:
![Bildschirmfoto 2020-08-27 um 16 14 08](https://user-images.githubusercontent.com/30288503/91453876-8ef37800-e880-11ea-9515-50cc092effb8.png)
Diese Eingaben habe ich auch so im Juli gemacht...

**Comment by barbalex** [comment]
Keine Ahnung.

Jetzt ist mir etwas aufgefallen:

Die Methode kann man ganz schnell wählen - ein Klick (oder die "Tab"-Taste gefolgt von der "Enter"-Taste) reicht.

Das heisst: Theoretisch, wenn jemand ganz schnell arbeitet, _könnte eventuell_ die Änderung der Methode das "Rennen" von der App zur Daten-Schnittstelle gewinnen. Was bedeutet: Die zuvor gemachte Änderung (z.B. die Anzahl) kommt _nachher_ in der Datenschnittstelle an.

Wegen einer Eigenheit der verwendeten Technologie enthalten beide Speichervorgänge alle Daten der Zählung zum Zeitpunkt der Speicherung.

Käme also die Änderung des zuvor geänderten Feldes _nach_ der Änderung der Methode an, würde die zuvor erfolgte Anpassung (Methode ändern) überschrieben. Ohne Methode.

Bisher habe ich dies nicht für möglich gehalten. Aber vielleicht arbeitet ihr einfach zu schnell 😭 

Muss noch etwas hirnen 🤔

**Comment by barbalex** [comment]
O.k., habe glaube ich etwas gelernt.

Ich habe nun bei den Teilzählungen den Speichervorgang so angepasst, dass immer nur das aktuell geänderte Feld an die Daten-Schnittstelle übermittelt wird.

Damit sollten "race-conditions" zwischen Feldern grundsätzlich verhindert werden.

Möglich wären sie immer noch, wenn _dasselbe_ Feld mehrmals und sehr rasch unmittelbar nacheinander verändert wird. Wenn z.B. jemand sehr schnell und wiederholt die Methode ändert (was sehr schnell geht, weil klickbar), könnt ihr den letztlich gespeicherten Wert genauso gut würfeln. Aber das ist ein grundsätzliches Problem der App-Server-Architektur, das sehr viele Projekte betrifft. Und es sollte viel seltener geschehen, als das nun von euch beobachtete Problem.

Dieses verbleibende Problem ist in vermehrung.ch durch folgende zwei Massnahmen gelöst:

1. Konflikte werden sichtbar gemacht
2. Die App wird vom Server laufend live aktualisiert. Das heisst, sichtbar ist immer die zuletzt registrierte Änderung

Diese Lösungen würden auch für apflora wirksam, wenn wir apflora wie vermehrung.ch offline fähig machen würden. Das ist aber extrem aufwändig einzuführen.

In v1.41.8 ist nun die neue Lösung integriert. **Bitte melde mir in den nächsten Wochen, ob sich das Problem damit gelöst hat. Wenn sich diese Lösung bewährt, werde ich sie auf alle Formulare ausweiten.**

**Comment by barbalex** [comment]
Übrigens: Das Gemeine an diesen "race-conditions" ist, dass die App in der richtigen Reihenfolge die Daten aktualisiert und daher das anzeigt, was die Benutzerin erwartet. Beim Server aber sind die Daten anders, z.B. kann die Methode verloren gegangen sein.

Die Benutzerin sieht das also erst beim nächsten Laden des Datensatzes. Oder wenn die Qualitätskontrolle den Sachverhalt aufdeckt.

Live-Updates aus der Datenbank wären super, weil die Benutzerin dann sofort sieht, dass die Methode verloren ging.

**Comment by barbalex** [comment]
Öffne den Issue wieder, denn: Wenn sich das bewährt, muss ich es auf alle Formulare ausweiten.

**Comment by barbalex** [comment]
@rebeccakurz Habt ihr in den letzten 25 Tagen einige Zählungen bearbeitet? Wenn ja: Hat es gut funktioniert? Falls ja werde ich diese Änderung nach und nach auf alle Formulare übertragen.

**Comment by rebeccakurz** [comment]
Hoi Alex
Habe zwar ein paar Eingaben gemacht, aber leider nicht besonders darauf geachtet... Ich werde aber morgen oder am Donnerstag Eingaben machen und dir dann Rückmeldung geben.

**Comment by barbalex** [comment]
Ich schliesse diesen Issue: Habe vor zwei Wochen diese Art der Aktualisierung auf alle Formulare übertragen und es scheint gut zu klappen
