### ISSUE TITLE
QK: TPop auf erloschen setzen -> Fehlermeldung, weil noch EKs in Zukunft geplant

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#396]
Auch ein Anliegen von Karin Sartori: 
"Folgende DB-Eingabevereinfachung möchte ich beantragen (zur Sammlung von Anliegen aufnehmen, pressiert nicht):
Ich habe bei den Qualitätskontrollen bemerkt: wenn ich eine TPop auf gelöscht setze, kriege ich eine Fehlermeldung, weil noch EKs in der Zukunft geplant sind.
Lösung: sobald eine TPop auf gelöscht gesetzt wird, alle EKs und EKFs entfernen (irgendwie automatisieren?)"

Wäre hier eine Automatisierung möglich? (Bei der EK-Planung kann man das ja dann die EK-Frequenz auf "nie" stellen, aber das muss man von Hand machen.)

**Comment by rebeccakurz** [comment]
![Unknown-2](https://user-images.githubusercontent.com/30288503/91011450-9860b400-e5e4-11ea-910f-c2f37bb56e79.png)

**Comment by barbalex** [comment]
Ja, Automatisierung ist möglich aber ein paar Stunden Arbeit. Lass das mal als Erweiterung stehen

**Comment by barbalex** [comment]
Ich schliesse diesen Issue, weil wir gesehen haben, dass dieser Automatismus gefährlich sein kann
