### ISSUE TITLE
TPop über Karte öffnen funktioniert nicht

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#397]
Es gibt ja die Funktion, dass man eine Teilpopulation auf der Karte anklicken kann und dann sieht man einige Informationen dazu in einem Popup-Fenster, u.a. Art, Name, Status etc. Und man kann auch auf einen Link klicken, dass man das Formular in einem neuen Fenster öffnen kann oder das Formular in Strukturbaum 2 öffnen kann. 
![Bildschirmfoto 2020-08-27 um 13 33 31](https://user-images.githubusercontent.com/30288503/91438287-657c2180-e86b-11ea-96ca-cb3625565648.png)

Wenn man auf "Formular in neuem Fenster öffnen" klickt, wird man zwar auf eine neue Seite geführt, aber die FloraDB wird nicht richtig geladen und es kommen Fehlermeldungen.
![Bildschirmfoto 2020-08-27 um 13 47 29](https://user-images.githubusercontent.com/30288503/91438580-e2a79680-e86b-11ea-92c7-b4e620a4b691.png)
Dasselbe wenn man auf "Formular in Strukturbaum 2 öffnen" klickt: Es erscheint zwar der Strukturbaum 2 und die Daten 2, aber es wird nicht richtig geladen. 
![Bildschirmfoto 2020-08-27 um 13 36 59](https://user-images.githubusercontent.com/30288503/91438718-15ea2580-e86c-11ea-8255-6ea5e7362ed0.png)

Könntest du dir das mal ansehen?

P.S.: Habe mich gerade noch gefragt, ob es möglich wäre, das Formular im "normalen" Strukturbaum zu öffnen, also dass man im Strukturbaum 1 gleich zur richtigen Art und TPop geführt wird?

**Comment by barbalex** [comment]
Sorry, bei mir funktioniert das tip top 🙄 
Was muss man machen, um dieses Verhalten zu provozieren?

> Habe mich gerade noch gefragt, ob es möglich wäre, das Formular im "normalen" Strukturbaum zu öffnen, also dass man im Strukturbaum 1 gleich zur richtigen Art und TPop geführt wird?

Klar. Wenn ihr das wünscht, öffne dafür einen neuen Issue.

**Comment by barbalex** [comment]
Ich bin übrigens völlig erstaunt, _wie schnell_ das bei mir lädt 😄

**Comment by rebeccakurz** [comment]
Hm also ich weiss nicht recht, wie du das provozieren könntest... Habe es gerade nochmals probiert, bei mir funktioniert es also immer nicht. Kann es sein, dass mein Browser etwas blockiert, dass diese Fehlermeldungen entstehen?

**Comment by rebeccakurz** [comment]
Das andere werde ich mir nochmals überlegen ob es sinnvoll und hilfreich ist. 👍

**Comment by barbalex** [comment]
Ich bin der Fehlermeldung nachgegangen. Und habe etwas gefunden, was zu dieser Fehlermeldung führen könnte, wenn eine Situation eintritt, die unerwartet wäre und bei mir offenbar nicht eintritt. Aber vielleicht bei dir. In v1.41.9 habe ich diesen möglichen Fehler korrigiert. Bitte teste, ob es nützt.

**Comment by rebeccakurz** [comment]
Jetzt kommt nur noch eine Fehlermeldung (siehe Screenshot). Aber ich werde immer noch nicht zur richtigen TPop weitergeleitet...
![Bildschirmfoto 2020-08-31 um 14 17 28](https://user-images.githubusercontent.com/30288503/91719331-64adfd00-eb95-11ea-897e-b7e831fa1f38.png)

**Comment by barbalex** [comment]
Versuch's bitte mal mit der neuen Version 1.41.10

**Comment by rebeccakurz** [comment]
Jetzt scheint es zu funktionieren 👍 manchmal geht es noch etwas sehr lange, bis es geladen wird. Aber es geht mit dem zweiten Fenster und dem zweiten Strukturbaum.

**Comment by barbalex** [comment]
> manchmal geht es noch etwas sehr lange, bis es geladen wird

Das kommt daher, dass dieser Vorgang sehr aufwändige Abfragen durchführt, welche offenbar den Server an die CPU-Grenze bringen. Hier die CPU-Belastung von heute:
<img width="897" alt="2020-09-01_11h14_53" src="https://user-images.githubusercontent.com/669783/91831665-a5b11a80-ec44-11ea-8d2a-b2f52e5d4416.png">

**Comment by barbalex** [comment]
Ich schliesse diesen Issue. Das mit der Server-Belastung müssen wir weiter beobachten (https://github.com/barbalex/apf2/issues/400)

**Comment by rebeccakurz** [comment]
Oh ja, das stimmt glaube ich ziemlich gut mit den Zeiten überein, an denen ich es ausprobiert habe...
