### ISSUE TITLE
Ansicht EKF

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#399]
Es gibt ja die Funktion, dass ich die FloraDB so sehe, wie ein Freiwilliger, wenn er sich eingeloggt hat. 
In dieser Ansicht wird aber leider der untere Bildrand jeweils abgeschnitten (siehe Screenshot). Kannst du da etwas machen?
![Bildschirmfoto 2020-08-31 um 14 24 19](https://user-images.githubusercontent.com/30288503/91721174-9f656480-eb98-11ea-84c6-bc294c3ff19f.png)

**Comment by barbalex** [comment]
Uups, diese Meldung habe ich verpasst.

Wird in Version 1.42.2 korrigiert sein.

Danke für die Meldung.
