### ISSUE TITLE
Zoom auf TPop in Karte

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#40]
Hab ich das schon mal gewünscht? Wäre mega lässig!

**Comment by barbalex** [comment]
Du kannst auf die Teilpopulation zoomen, die im Strukturbaum gewählt ist: Klick auf das gelbe Symbol im Layertool des entsprechenden Layers, siehe Bild (das Bild ist im mail nicht sichtbar)
![tpopzoomen](https://cloud.githubusercontent.com/assets/669783/26726631/1769f438-47a4-11e7-9cf0-b0a27b2b5d16.png)

**Comment by csalzmann** [comment]
Danke!!
