### ISSUE TITLE
EK-Planung: Fehlermeldung, wenn EK auf "nie" gesetzt wird

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#401]
Hoi Alex

Du hast ja bei der EK-Planung die Frequenzen "nie (EK)" und "nie (EKF)" eingerichtet, die man wählen kann, wenn z.B. eine TPop erloschen ist oder nicht mehr kontrolliert werden kann. 
Nun hat mir Karin Sartori gemeldet, dass, wenn sie diese Frequenz wählt, eine Fehlermeldung erscheint, dass das Startjahr nicht berechnet werden konnte, da das Feld "Kontrolljahre ab" nicht erfasst wurde (siehe Screenshot). Diese Fehlermeldung erscheint aber auch, wenn zuvor ein Startjahr erfasst wurde.
Auch bei mir erscheint diese Fehlermeldung, wenn ich die Frequenz "nie" wähle.
Könntest du dir das mal anschauen? Danke.
![Bildschirmfoto 2020-09-22 um 10 53 19](https://user-images.githubusercontent.com/30288503/93863221-8d707080-fcc3-11ea-8962-525aa84a622a.png)

**Comment by barbalex** [comment]
Bei welchem AP passiert das?

**Comment by rebeccakurz** [comment]
Bei Karin war es bei Rosa gallica. Ich habe es bei Abies alba, Saxifraga granulata, Thalictrum galioides, Ophrys araneola und Liparis loeselii probiert, es kam überall die selbe Fehlermeldung.
Ich glaube ich habe bei Thalictrum galioides vor ein paar Wochen/Monaten die erloschenen TPops auf die Frequenz "nie" gesetzt und dort hat es glaube ich geklappt...

**Comment by barbalex** [comment]
In den EK-Frequenzen mit "nie" wurde das Feld "Kontrolljahre ab letzter" nicht gewählt. Dieses wird aber von apflora benutzt, um das Start-Jahr zu wählen, ab dem die Kontrollen gesetzt werden.

Bloss macht es gar keinen Sinn, ein Startjahr zu wählen, wenn ja keine Kontrolljahre definiert sind.

Das gleiche Problem müsste es auch in den Spezialfällen gegeben haben, wo die Kontrolljahre manuell gesetzt werden. 

Daher habe ich jetzt den Code, der das Startjahr setzt, so angepasst, dass er kein Startjahr zu setzten versucht, wenn die EK-Frequenz keine Kontrolljahre hat.

Das verhindert dann auch diese Meldung.

Wird ab Version 1.41.12 wirksam, welche nun live ist.

**Comment by rebeccakurz** [comment]
Danke!
