### ISSUE TITLE
EK-Planung

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#402]
Hoi Alex
Charlotte hat mich gerade darauf aufmerksam gemacht, dass bei ihr bei der Qualitätskontrolle eine Fehlermeldung erscheint
![Unknown-1](https://user-images.githubusercontent.com/30288503/98114101-08bd6880-1ea5-11eb-8768-870edb1d8fdc.png)
obwohl sie in der EK-Planung die Frequenz auf "nie" gestellt hat. 
![Unknown](https://user-images.githubusercontent.com/30288503/98114120-11ae3a00-1ea5-11eb-9b63-192c04ed8c09.png)

Zuerst dachte ich es liegt daran, dass sie "nie (EKF)" gewählt hat und es sich aber um eine geplante Feldkontrolle handelt. Aber als ich den Status in der FloraDB auf "nie (EK)" umgestellt habe, sind die geplanten EKs im 2021 trotzdem nicht gelöscht worden.
![Bildschirmfoto 2020-11-04 um 13 50 25](https://user-images.githubusercontent.com/30288503/98114045-f0e5e480-1ea4-11eb-8b30-bc4f2670fa4f.png)

Könntest du dir das mal anschauen? Sagittaria sagittifolia, TPop 3.2 und 3.4
Danke!

**Comment by rebeccakurz** [comment]
Habe gerade nochmals etwas getestet. Wenn man das Startjahr für die EK-Frequenz auf 2021 legt, dann verschwinden die geplanten EKs.

Man muss also immer sowohl die EK-Frequenz auf "nie" setzen und dann noch das Startjahr anpassen, damit die geplanten EKs verschwinden und es in der Qualitätskontrolle nicht mehr angezeigt wird, ist das richtig?

**Comment by barbalex** [comment]
Wie die Fehlermeldung besagt, wird nicht die gewählte EK-Frequenz geprüft, sondern, ob Kontrollen geplant sind.

Setzt man die EK-Frequenz also auf eine Form von "nie", muss man tatsächlich die zuvor geplanten Kontrollen löschen, damit diese Kontrolle nicht erscheint.

Es gibt keinen Automatismus, der bei Wahl einer Form von "nie" das automatisch macht.

Es gibt aber den Automatismus, der bei Änderung des Startjahrs **danach geplante** löscht und danach die passenden Kontrollen setzt - was bei "nie" keine sind.

In dem Sinne stimmt deine Aussage:

> Man muss also immer sowohl die EK-Frequenz auf "nie" setzen und dann noch das Startjahr anpassen, damit die geplanten EKs verschwinden und es in der Qualitätskontrolle nicht mehr angezeigt wird

Man hätte auch die Kontrollen direkt löschen können. Was allerdings mehr Arbeit ist.

**Sollte das automatisch gehen?**

Das Problem ist:
- "nie" ist nur Text. Automatismen müssen von den für die gewählte EK-Frequenz definierten Kontrolljahre ausgehen. Sie würden also alle EK-Frequenzen ohne Kontrolljahre gleich behandeln
- "nie" bzw. EK-Frequenzen ohne Kontrolljahre erfordern kein Startjahr
- Der Automatismus wüsste also nicht, ab wann geplante Kontrollen gelöscht werden sollten
- Er könnte also bloss alle geplanten Kontrollen löschen. Oder alle, die in der Zukunft liegen

Ein Automatismus wäre also soweit ich es sehe nur möglich, wenn klar wäre, dass bei der Wahl von EK-Frequenzen ohne Kontrolljahre immer alle geplanten Kontrollen gelöscht werden dürfen. Oder alle in der Zukunft liegenden.

Wenn ihr eine dieser beiden Varianten für sinnvoll erachtet, könnte ich sie als Erweiterung aufnehmen.

**Comment by rebeccakurz** [comment]
Ja um genau so eine Automatisierung würde es gehen. Ich denke, ich kann sagen, dass bei der Wahl der EK-Frequenz "nie" klar ist, dass alle in der Zukunft liegenden geplanten Kontrollen gelöscht werden können. 

Die Automatisierung würde aber noch weiter gehen im Sinne von dass wenn eine TPop auf "erloschen" gesetzt wird, die EK-Frequenz automatisch auch "nie" gestellt wird und somit alle in der Zukunft liegenden geplanten Kontrollen gelöscht werden sollten. 

Wir haben das bereits in diesem Issue #396 diskutiert und eine Erweiterung beschlossen.
Wäre das machbar?

**Comment by barbalex** [comment]
> Wäre das machbar?

Ja.

Ihr müsst euch aber bewusst sein: **Wenn wir Automatismen bauen, welche auf Ereignisse aufbauen, welche nicht im EK-Planungs-Formular passieren und trotzdem EK's planen, so könnte das auch relativ schnell unübersichtlich, verwirrlich und kaum mehr nachvollziehbar werden**. 

Beispiel: Jemand setzt den Status falsch, korrigiert ihn aber sogleich wieder: Kein Problem, dort, wo man gearbeitet hat. Aber: ganz woanders hat sich das stark ausgewirkt, nämlich in der EK-Planung.

Darum war das bisher bloss als Kontrollen implementiert. Scheint mir nach wie vor viel sicherer zu sein.

Dieses Argument trifft für Issue https://github.com/barbalex/apf2/issues/396 zu. Nicht aber für diesen Issue hier, weil dies passieren würde, während die dafür zuständige Person das EK-Planungs-Formular bearbeitet und die von der Aktion ausgelösten Änderungen daher direkt sieht.

**Comment by rebeccakurz** [comment]
Okay, dann werde ich das mit Karin noch anschauen, ob wir diesen Automatismus #396 einbauen möchten, der Auswirkungen an einem anderen Ort hat. 

Den Automatismus aus diesem Issue wäre aber sicher gut (also automatisch alle geplanten Kontrollen in der Zukunft löschen, wenn die Frequenz auf "nie" gestellt wird).

**Comment by rebeccakurz** [comment]
Hoi Alex
Wir haben noch eine Frage zu diesem Issue:
Nachdem die Artverantwortlichen alle Massnahmen eingegeben haben, müssen ja für die neu entstandenen Teilpopulationen die EK-Frequenzen gesetzt werden. Dies geschieht ja im Moment halbautomatisch, also du setzt provisorisch die passenden EK-Frequenzen, wir kontrollieren die Vorschläge und geben das Okay.
Wäre es möglich, dass gleichzeitig auch bei den dieses Jahr neu erloschenen Teilpopulationen die EK-Frequenz "nie" gesetzt wird?

**Comment by barbalex** [comment]
> Wäre es möglich, dass gleichzeitig auch bei den dieses Jahr neu erloschenen Teilpopulationen die EK-Frequenz "nie" gesetzt wird?

Ja, beruhend auf der Version der Daten, die historisiert wurde: Was damals noch nicht den Status erloschen hatte, aber jetzt schon, wird auf nie gesetzt.

**Comment by barbalex** [comment]
Bitte mach neue Issues für neue Fragen, ich verliere sonst die Übersicht.

**Comment by barbalex** [comment]
> Wäre es möglich, dass gleichzeitig auch bei den dieses Jahr neu erloschenen Teilpopulationen die EK-Frequenz "nie" gesetzt wird?

Welche Version von "nie" soll gesetzt werden? Es gibt:

- nie (EK)
- nie (EKF)

**Comment by kmarti** [comment]
Es soll "nie (EK)" gesetzt werden.
Beides geht ja wahrscheinlich nicht und die EKF-Planung machen wir besser manuell.

**Comment by barbalex** [comment]
Ist umgesetzt
