### ISSUE TITLE
Scrollbalken bei EK-Planung

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#404]
Lieber Alex

Einige AVs haben das Problem, dass bei der EK-Planung der Scrollbalken unten und auf der rechten Seite nicht immer angezeigt wird. Erst wenn man das Fenster vergrössert erscheint er wieder. Aber wenn die EK-Planung dann über zwei Fenster offen ist, ist die Übersichtlichkeit nicht mehr so gut. 
Kannst du da allenfalls etwas machen?

Gruss, Rebecca

**Comment by barbalex** [comment]
Das Problem ist, dass dieses Formular ganz viele Bedürfnisse erfüllen soll.

Daher werden sehr viele Daten angezeigt.

Daher braucht es viel Platz.

Reicht die verfügbare Breite nicht, erscheint der Scrollbalken nicht. Mindestens glaube ich, dass es das ist, was du beschreibst. Vielleicht musst du mir ein Bild schicken, falls das so nicht zutrifft.

Wenn der Platz nicht ausreicht, muss man entweder:
- mehr Platz schaffen , zum Beispiel:
  - Fenster verbreitern
  - Zoom-Stufe ändern. Das geht gleich, wie bei allen Webseiten. Bei mir auf Windows ist das:
    - Ctrl-Taste gedrückt halten und - drücken, um die Zoomstufe zu verkleinern (+ um sie wieder zu vergrössern)
    - Ctrl-Taste gedrückt halten und mit dem Mausrad scrollen
- Weniger Spalten anzeigen (Menu "Felder wählen"). Das könnt ihr selber wählen und apflora merkt sich das auch, d.h. ihr müsst es nur ein mal wählen [Link zur Anleitung](https://apflora.ch/Dokumentation/Benutzer/Erfolgs-Kontrollen-planen/#dargestellte-informationen-w%C3%A4hlen)

Ich schliesse mal diesen Issue, in der Annahme die Frage sei beantwortet.
