### ISSUE TITLE
EK-Planung: Jahre ausblenden 

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#405]
Lieber Alex

Ebenfalls eine Anregung der AVs: Wäre es möglich, dass bei der EK-Planung gewisse Jahresspalten ausgeblendet werden können? Das würde ebenfalls die Übersichtlichkeit erhöhen und die Planung erleichtern.
Wäre das möglich?

Gruss, Rebecca

**Comment by barbalex** [comment]
Ja

Welche? Mit welchen Regeln? Oder soll das manuell gehen?

Sag mir doch einfach, wie du dir das im Optimalfall vorstellst.

**Comment by rebeccakurz** [comment]
Also meiner Meinung nach wäre es am besten, wenn man die Spalten manuell ausblenden könnte.
Oder was für Regeln könnte man zum Beispiel anwenden? Evt. das nur das aktuelle Jahr und alle zukünftigen angezeigt werden? (das hätte Charlotte vorgeschlagen, aber ich denke für die Planung ist es schon hilfreich, wenn man auch die vorhergehenden Jahre bis zu einem gewissen Grad sieht). 
Oder wäre es möglich, dass z.B. die letzten 5 Jahre vor dem aktuellen Jahr und die zukünftigen Jahre angezeigt werden?
Vielleicht muss ich es noch mit Karin besprechen, was sie sinnvoll fände.
Evt. wäre auch eine Kombination mit manuell und Regeln anwenden möglich? Allerdings wird es dann wahrscheinlich wieder wahnsinnig kompliziert...

**Comment by rebeccakurz** [comment]
Vielleicht könntest du mir kurz darlegen, welche Regeln möglich wären und dann werde ich mit KM besprechen, was am sinnvollsten ist. 
Auf jeden Fall super, dass das möglich ist!

**Comment by barbalex** [comment]
> Also meiner Meinung nach wäre es am besten, wenn man die Spalten manuell ausblenden könnte.

Das Problem ist: Die Jahre sind nicht immer dieselben. Es kommt auf den Aktionsplan an, d.h. wie weit zurück Daten existieren, die hier angezeigt werden. Das Formular zeigt heute genau so weit zurück Daten, wie sie bei den angezeigten Aktionsplänen existieren. Darum ist manuell vermutlich keine gute Idee (sorry, dass ich sie aufgeworfen habe).

> Evt. das nur das aktuelle Jahr und alle zukünftigen
Das ist einfach umzusetzen. Aber wie du sagst, vermutlich nicht immer optimal

> Oder wäre es möglich, dass z.B. die letzten 5 Jahre vor dem aktuellen Jahr und die zukünftigen Jahre angezeigt werden?
Das ist einfach umzusetzen

Eine mit vernünftigem Aufwand machbare flexiblere Variante wäre: 

Es gibt oben rechts neben "anzeigen" ein Feld, in dem man wählen kann, wie viele Jahre zurück Daten angezeigt werden sollen (falls es sie denn so weit zurück gibt). Mögliche Beschriftung: "vergangene Jahre".

Voreinstellen könnten wir 0, 5 oder 10. Was immer du sinnvoll findest (5 schiene mir passend). Benutzer _könnten_ dann aber optimieren, je nach Daten, Bildschirmgrösse oder was auch immer, indem sie diesen Wert verändern. 

Diese Einstellung wird wie alle anderen auf dem betreffenden PC gespeichert, d.h. man muss normalerweise nur ein mal ändern.

**Comment by rebeccakurz** [comment]
Hoi Alex
Die von dir vorgeschlagene Variante mit dem Feld, in dem man wählen kann, finde ich sehr gut! Ich fände 5 Jahre auch passend und wenn man es dann auch anpassen kann ist das natürlich super.
Vielen Dank!

**Comment by barbalex** [comment]
Ist in Version 1.44.0 implementiert. Man kann sogar negative Werte eingeben...

**Comment by barbalex** [comment]
Ich schliesse das mal, da eine Lösung implementiert ist
