### ISSUE TITLE
EK-Planung: Filtern in allen Spalten

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#406]
Hoi Alex

Da ich mich gerade mit der EK-Planung beschäftige... In unserer Wunschliste von Anfang Jahr hatten wir den Task, dass bei der EK-Planung das Filtern in allen Spalten möglich gemacht werden sollte und dass bei der EK-Frequenz nicht nur Leerwerte wegfiltern möglich sein sollte. 

Hast du diese Erweiterung noch vorgesehen?

Gruss, Rebecca

**Comment by barbalex** [comment]
Hoi Rebecca

O.k., danke für die Erinnerung.

Ich packe das hoffentlich noch diese Woche an.

LG, Alex



***********************************************************



Alexander Gabriel
Wiesenstrasse 22
8800 Thalwil
079 372 51 64
alex@barbalex.ch
https://gabriel-software.ch

**Comment by barbalex** [comment]
Ist in Version 1.45.0 implementiert.

**Comment by rebeccakurz** [comment]
super, vielen Dank!
