### ISSUE TITLE
Massnahmen: Zieleinheit

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#407]
Hoi Alex
Wir haben ja bei den Massnahmen zwei neue Felder geschaffen "Zieleinheit: Einheit", das wird automatisch ausgefüllt und "Zieleinheit: Anzahl". 
Diese Angabe wird für die Auswertungen zum Jahresbericht gebraucht richtig?
Dann gibt es ja noch die Felder "Anzahl Pflanzen" und "Anzahl Triebe". Diese Angaben werden dann in der EK-Planung angezeigt oder?
Daher ist es also nötig, dass die AV beide Felder ausfüllen, ist das richtig?

**Comment by barbalex** [comment]
Bezüglich den Zieleinheit-Feldern: Das ist hier erklärt: https://github.com/barbalex/apf2/issues/370

> das wird automatisch ausgefüllt
- Die Felder sind nur sichtbar, wenn ein Massnahmentyp gewählt ist, der Anpflanzungen beinhaltet
- Beim Wählen dieses Typs setzt apflora gleich selber die Ziel-Einheit (sofern eine EK-Zähleinheit als zielrelevant gesetzt wurde)

> Diese Angabe wird für die Auswertungen zum Jahresbericht gebraucht richtig?

Nein. 

Die Felder wurden geschaffen, damit auf Ebene AP die Auswertungen bzw. Zeit-Achsen berechnet werden konnten. Siehe z.B. hier: https://apflora.ch/Daten/Projekte/e57f56f4-4376-11e8-ab21-4314b6749d13/Aktionspl%C3%A4ne/6c52d126-4f62-11e7-aebe-cbb8319e1712?apTab=auswertung&feldkontrTab=entwicklung&idealbiotopTab=idealbiotop&popTab=pop&projekteTabs=tree&projekteTabs=daten&qkTab=qk&tpopTab=tpop&tpopmassnTab=tpopmassn

Dort werden die Zahlen pro Jahr nach den ziel-relevanten Einheiten ausgewertet. Gibt es Anpflanzungen und seither keine Kontrolle, werden diese Werte verwendet.

Dokumentiert ist es hier: https://apflora.ch/Dokumentation/Benutzer/ap-auswertung-pop-menge/ und hier https://apflora.ch/Dokumentation/Benutzer/historisierung

> Dann gibt es ja noch die Felder "Anzahl Pflanzen" und "Anzahl Triebe". Diese Angaben werden dann in der EK-Planung angezeigt oder?

Richtig

> Daher ist es also nötig, dass die AV beide Felder ausfüllen, ist das richtig?

Richtig. Wobei das nur bei Anpflanzungen vorkommt.

Das ist leider so kompliziert, weil man bei den Kontrollen völlig frei ist, welche Einheiten man zählt.

**Comment by rebeccakurz** [comment]
Vielen Dank für deine Antwort!

**Comment by rebeccakurz** [comment]
Und gleich noch eine Nachfrage dazu: Gibt es für diese Ziel-Einheit in den Massnahmen bereits eine Qualitätskontrolle, so dass diese nicht vergessen wird?

**Comment by barbalex** [comment]
Ich muss auch nachschauen: https://apflora.ch/Daten/Projekte/e57f56f4-4376-11e8-ab21-4314b6749d13/Aktionspl%C3%A4ne/6c52d126-4f62-11e7-aebe-cbb8319e1712/Qualitaetskontrollen?apTab=ap&feldkontrTab=entwicklung&idealbiotopTab=idealbiotop&popTab=pop&projekteTabs=tree&projekteTabs=daten&qkTab=waehlen&tpopTab=tpop&tpopmassnTab=tpopmassn

Da gibt es:
- Teilpopulation mit Kontrollen im aktuellen Jahr. Aber die zielrelevante Einheit wurde nie erfasst
- AP mit Kontrollen im aktuellen Jahr. Aber eine Ziel-relevante Einheit fehlt

**Comment by rebeccakurz** [comment]
Dann bräuchte es noch die Ergänzung:
Teilpopulation mit Massnahmen im aktuellen Jahr. Aber die zielrelevante Einheit wurde nicht erfasst.
Oder so ähnlich?

**Comment by barbalex** [comment]
Oder noch ein bisschen präziser: "Teilpopulation mit Anpflanzungen im aktuellen Jahr. Aber die zielrelevante Einheit wurde nicht erfasst".

Stimmt, das fehlt.

**Comment by barbalex** [comment]
Mach doch bitte einen neuen Issue, um diese Kontrolle zu wünschen. Ich kann es jetzt nicht sofort machen.

**Comment by rebeccakurz** [comment]
Mach ich, danke!
