### ISSUE TITLE
neue Qualitätskontrolle: Zieleinheit in Massnahme

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#408]
Bitte neue Qualitätskontrolle erstellen:
"Teilpopulation mit Anpflanzungen im aktuellen Jahr. Aber die zielrelevante Einheit wurde nicht erfasst"

**Comment by barbalex** [comment]
Entsprechend: Teilpopulation mit Kontrollen im aktuellen Jahr. Aber die zielrelevante Einheit wurde nie erfasst

**Comment by barbalex** [comment]
Rückfrage: Du schreibst Anpflanzungen. Also diese zwei Massnahmentypen:
- "Ansiedlung: Anpflanzung"
- "Ansiedlung: Ansaat und Auspflanzung"

und explizit nicht:
- "Ansiedlung: Ansaat"

Korrekt?

**Comment by barbalex** [comment]
Logo, man kann ja nur bei "Ansiedlung: Anpflanzung" die zielrelevanten Einheiten erfassen 🙄

**Comment by barbalex** [comment]
Ist in Version 1.49.0 implementiert.

Für 2020 sind das:

ap | pop_nr | tpop_nr
-- | -- | --
Abies alba Mill. (Edel-Tanne,   Weiss-Tanne) | 101 | 2
Aldrovanda vesiculosa L. (Aldrovande) | 10 | 20
Aldrovanda vesiculosa L. (Aldrovande) | 11 | 2
Aldrovanda vesiculosa L. (Aldrovande) | 11 | 10
Aldrovanda vesiculosa L. (Aldrovande) | 22 | 2
Aldrovanda vesiculosa L. (Aldrovande) | 22 | 3
Campanula cervicaria L. (Borstige   Glockenblume) | 3 | 24
Campanula cervicaria L. (Borstige   Glockenblume) | 3 | 25
Campanula cervicaria L. (Borstige   Glockenblume) | 3 | 26
Campanula cervicaria L. (Borstige   Glockenblume) | 3 | 27
Campanula cervicaria L. (Borstige   Glockenblume) | 3 | 28
Campanula cervicaria L. (Borstige   Glockenblume) | 3 | 29
Campanula cervicaria L. (Borstige   Glockenblume) | 41 | 1
Campanula cervicaria L. (Borstige   Glockenblume) | 41 | 2
Campanula cervicaria L. (Borstige   Glockenblume) | 41 | 3
Carex chordorrhiza L. f. (Fadenwurzelige   Segge) | 3 | 1
Carex chordorrhiza L. f. (Fadenwurzelige   Segge) | 3 | 4
Carex chordorrhiza L. f. (Fadenwurzelige   Segge) | 3 | 5
Carex chordorrhiza L. f. (Fadenwurzelige   Segge) | 13 | 7
Carex chordorrhiza L. f. (Fadenwurzelige   Segge) | 18 | 2
Carex chordorrhiza L. f. (Fadenwurzelige   Segge) | 22 | 2
Carex hartmanii Cajander (Hartmans Segge) | 17 | 19
Carex hartmanii Cajander (Hartmans Segge) | 34 | 2
Carex hartmanii Cajander (Hartmans Segge) | 36 | 2
Carex hartmanii Cajander (Hartmans Segge) | 36 | 3
Carex heleonastes L. f. (Torf-Segge) | 1 | 1
Carex heleonastes L. f. (Torf-Segge) | 4 | 1
Carex heleonastes L. f. (Torf-Segge) | 5 | 1
Carex heleonastes L. f. (Torf-Segge) | 6 | 1
Carex heleonastes L. f. (Torf-Segge) | 6 | 2
Carex heleonastes L. f. (Torf-Segge) | 7 | 1
Daphne cneorum L. (Flaumiger Seidelbast,   Fluhröschen) | 114 | 5
Daphne cneorum L. (Flaumiger Seidelbast,   Fluhröschen) | 114 | 6
Daphne cneorum L. (Flaumiger Seidelbast,   Fluhröschen) | 114 | 7
Daphne cneorum L. (Flaumiger Seidelbast,   Fluhröschen) | 114 | 8
Daphne cneorum L. (Flaumiger Seidelbast,   Fluhröschen) | 114 | 9
Daphne cneorum L. (Flaumiger Seidelbast,   Fluhröschen) | 114 | 10
Daphne cneorum L. (Flaumiger Seidelbast,   Fluhröschen) | 130 | 3
Daphne cneorum L. (Flaumiger Seidelbast,   Fluhröschen) | 130 | 4
Daphne cneorum L. (Flaumiger Seidelbast,   Fluhröschen) | 130 | 5
Eriophorum gracile Roth (Schlankes   Wollgras) | 3 | 3
Eriophorum gracile Roth (Schlankes   Wollgras) | 4 | 1
Filipendula vulgaris Moench (Knollige   Spierstaude) | 146 | 1
Gagea pratensis (Pers.) Dumort.   (Wiesen-Gelbstern) | 120 | 1
Gagea pratensis (Pers.) Dumort.   (Wiesen-Gelbstern) | 120 | 2
Gagea pratensis (Pers.) Dumort.   (Wiesen-Gelbstern) | 121 | 1
Gagea pratensis (Pers.) Dumort.   (Wiesen-Gelbstern) | 121 | 2
Gagea villosa (M. Bieb.) Sweet   (Acker-Gelbstern) | 4 | 115
Gagea villosa (M. Bieb.) Sweet   (Acker-Gelbstern) | 4 | 116
Gladiolus palustris Gaudin   (Sumpf-Gladiole) | 19 | 1
Gratiola officinalis L. (Gnadenkraut) | 23 | 2
Gratiola officinalis L. (Gnadenkraut) | 73 | 1
Gratiola officinalis L. (Gnadenkraut) | 73 | 2
Hypochaeris maculata L. (Geflecktes   Ferkelkraut) | 1 | 2
Hypochaeris maculata L. (Geflecktes   Ferkelkraut) | 1 | 3
Hypochaeris maculata L. (Geflecktes   Ferkelkraut) | 8 | 4
Hypochaeris maculata L. (Geflecktes   Ferkelkraut) | 15 | 2
Hypochaeris maculata L. (Geflecktes   Ferkelkraut) | 19 | 10
Hypochaeris maculata L. (Geflecktes   Ferkelkraut) | 27 | 2
Hypochaeris maculata L. (Geflecktes   Ferkelkraut) | 28 | 1
Inula helvetica Weber (Schweizerischer   Alant) | 85 | 1
Inula helvetica Weber (Schweizerischer   Alant) | 87 | 1
Inula hirta L. (Rauher Alant) | 1 | 1
Inula hirta L. (Rauher Alant) | 1 | 3
Inula hirta L. (Rauher Alant) | 1 | 5
Inula hirta L. (Rauher Alant) | 1 | 11
Inula hirta L. (Rauher Alant) | 11 | 8
Inula hirta L. (Rauher Alant) | 11 | 9
Inula hirta L. (Rauher Alant) | 11 | 10
Inula hirta L. (Rauher Alant) | 25 | 1
Inula hirta L. (Rauher Alant) | 25 | 5
Inula hirta L. (Rauher Alant) | 53 | 2
Kickxia elatine (L.) Dumort.   (Pfeilblättriges Schlangenmaul) | 102 | 1
Littorella uniflora (L.) Asch.   (Strandling) | 106 | 5
Littorella uniflora (L.) Asch.   (Strandling) | 106 | 6
Littorella uniflora (L.) Asch.   (Strandling) | 106 | 7
Ophrys araneola Rchb. (Spinnen-Ragwurz) | 127 | 3
Ophrys araneola Rchb. (Spinnen-Ragwurz) | 127 | 4
Potamogeton coloratus Hornem. (Gefärbtes   Laichkraut) | 23 | 4
Potamogeton coloratus Hornem. (Gefärbtes   Laichkraut) | 28 | 26
Potamogeton coloratus Hornem. (Gefärbtes   Laichkraut) | 117 | 11
Potamogeton coloratus Hornem. (Gefärbtes   Laichkraut) | 127 | 2
Potentilla alba L. (Weisses Fingerkraut) | 7 | 2
Potentilla alba L. (Weisses Fingerkraut) | 7 | 3
Potentilla alba L. (Weisses Fingerkraut) | 7 | 4
Rosa gallica L. (Essig-Rose) | 121 | 1
Rosa gallica L. (Essig-Rose) | 121 | 6
Rosa gallica L. (Essig-Rose) | 121 | 7
Rosa gallica L. (Essig-Rose) | 128 | 1
Rosa gallica L. (Essig-Rose) | 128 | 2
Rosa gallica L. (Essig-Rose) | 141 | 2
Rosa gallica L. (Essig-Rose) | 142 | 7
Rosa gallica L. (Essig-Rose) | 155 | 1
Rosa gallica L. (Essig-Rose) | 155 | 3
Rosa gallica L. (Essig-Rose) | 155 | 4
Sagittaria sagittifolia L. (Gewöhnliches   Pfeilkraut) | 64 | 2
Stipa capillata L. (Haar-Pfriemengras) | 4 | 1
Teucrium scordium L. (Lauch-Gamander) | 32 | 3
Teucrium scordium L. (Lauch-Gamander) | 32 | 4
Teucrium scordium L. (Lauch-Gamander) | 32 | 5
Teucrium scordium L. (Lauch-Gamander) | 68 | 2
Teucrium scordium L. (Lauch-Gamander) | 68 | 3
Teucrium scordium L. (Lauch-Gamander) | 68 | 4
Teucrium scordium L. (Lauch-Gamander) | 92 | 3
Teucrium scordium L. (Lauch-Gamander) | 95 | 1
Teucrium scordium L. (Lauch-Gamander) | 95 | 2
Teucrium scordium L. (Lauch-Gamander) | 95 | 3
Thalictrum simplex L. subsp. galioides   (Pers.) Korsh. | 47 | 2
Thalictrum simplex L. subsp. galioides   (Pers.) Korsh. | 63 | 1
Thesium rostratum Mert. & W. D. J.   Koch (Schnabelfrüchtiger Bergflachs) | 21 | 3
Viola elatior Fr. (Hohes Veilchen) | 33 | 4
Viola elatior Fr. (Hohes Veilchen) | 39 | 1
Viola elatior Fr. (Hohes Veilchen) | 39 | 2
Viola persicifolia Schreb.   (Moor-Veilchen) | 20 | 22
Viola persicifolia Schreb.   (Moor-Veilchen) | 20 | 23
Viola persicifolia Schreb.   (Moor-Veilchen) | 52 | 1
