### ISSUE TITLE
Problem beim Kopieren und wieder einfügen

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#409]
Hoi Alex

Die AV haben gemeldet, dass wenn man eine TPop oder eine Massnahme kopiert und diese bei einer anderen Pop oder TPop wieder einfügen möchte, die kopierte TPop/Massnahme nicht angezeigt wird, aber da ist. 
Erst wenn man die ganze FloraDB schliesst und wieder aufmacht, wird die eingesetzte TPop wieder angezeigt. 
Ich habe dasselbe bei mir ebenfalls schon beobachtet, bei mir hat es dann aber gereicht, wenn ich die Seite aktualisiert habe. Es ist dann aber schon vorgekommen, dass ich dass die TPop/Massnahmen dreimal drinhatte, weil das Einsetzen an sich schon funktioniert hat, aber eben nicht angezeigt wurde...
Konntest du dir das bei Gelegenheit mal anschauen?

**Comment by rebeccakurz** [comment]
Nina Lohri meldet:
"Wenn ich Populationen inkl. Teilpopulationen kopiere, muss ich, wie bereits gesagt, immer mindestens aus der Art raus, meist aber sogar aus der Datenbank raus, bevor die kopierte Population bei der Neu-Öffnung angezeigt wird. Die Teilpopulation wird jeweils mitkopiert, aber leer! D. h. es sind keine Koordinaten oder Ähnliches vorhanden und sie muss neu verortet werden. Mühsam."

**Comment by barbalex** [comment]
Scheint nicht systematisch zu passieren, also schwierig zu provozieren.

Das ist übrigens etwas, dass mit der Offline-Struktur von vermehrung.ch einfacher zu lösen ist (ich erwähne das nur, weil Offline-Struktur eigentlich vieles beim Programmieren komplizierter macht - daher ist diese Ausnahme für mich interessant).

**Comment by barbalex** [comment]
Bitte sagt mir, wenn ihr eine Methode findet, diese systematisch zu provozieren. Dann behandle ich diesen Issue prioritär.

**Comment by rebeccakurz** [comment]
Hoi Alex
Also ich habe gerade nochmals etwas herumgepröbelt. Bei mir ist es so, dass wenn ich z.B. eine Massnahme kopiere und irgendwo wieder einfüge, dass ich dann zuerst die Seite aktualisieren muss, bevor mir die kopierte Massnahme angezeigt wird. Das ist bei jedem Kopieren so und auch bei Feldkontrollen, Teilpopulationen oder Populationen. 

Dann habe ich noch das Kopieren von Populationen probiert: Hier ist es immer so, dass die Pop erscheint, wenn ich aktualisiert habe, aber ohne Teilpopulationen, auch wenn ich auf "kopieren inklusive Teilpopulationen" klicke. 
Ich habe das jetzt mal bei Abies alba ausprobiert und vorher noch den Cache geleert...

**Comment by rebeccakurz** [comment]
Habe einen Teil jetzt noch bei Ophrys araneola ausprobiert. Auch hier muss ich zuerst die Seite aktualisieren, bevor mir eine kopierte Teilpopulation angezeigt wird. Wenn ich eine Teilpopulation kopiere, werden Massnahmen und Feld-Kontrollen nicht mitkopiert (bin mir aber nicht sicher, was alles mitkopiert werden soll).
Und auch hier ist es so, dass beim Kopieren einer Population die Teilpopulationen nicht mitkopiert werden.

**Comment by barbalex** [comment]
Ich habe jetzt den betreffenden Code nochmals genau angeschaut.

Und etwas gefunden, das Fehler provozieren könnte. 

Den Fehler konnte ich dann auch tatsächlich zuverlässig provozieren. Sehr komisch, dass das zuvor nicht gelang.

Der Fehler passierte _nachdem_ die Daten kopiert worden waren. Die neue Massnahme/TPop wurde also erzeugt. Der Fehler verhinderte aber, dass der Navigationsbaum aktualisiert wurde. Ausserdem verhinderte er, dass danach in den Fällen, in denen zusätzlich weitere Elemente kopiert werden sollten, dies passierte. Das erklärt das von euch beschriebene Verhalten.

Unverständlich ist ferner, warum dieser Fehler nicht in der Benutzeroberfläche erschien. Es scheint, dass das für die Kontext-Menü-Befehle verwendete Werkzeug Fehlermeldungen verschluckt.

Ist in Version 1.52.1 korrigiert.

**Comment by rebeccakurz** [comment]
super, vielen Dank!
