### ISSUE TITLE
Fehlermeldungen beim Öffnen der unteren Knoten

### ISSUE THREAD

**Issue by wunderli** [barbalex/apf2#41]
Lieber Alex

Seit einer Weile (ca. 2-4 Wochen) gibt es immer ein Rudel Fehlermeldungen auf der linken Seite.
Diese entstehen, wenn ich auf ein untergeordneter Knoten-Titel klicke oder auch Linksklick auf den Pfeil.
Die Fehlermeldungen bedecken den ganzen linken Bildschrimrand und verschwinden nach 10-15s wieder nach unten.  Allerdings kann man weiterarbeiten, wenn man am Rand der Meldungen den nächt unteren Titel anklicken kann.
Das ist sehr mühsam zum Arbeiten. :( Evtl. bessert das auch nach der Umstellung?

Wäre froh, wenn das bald endet, sonst ist es nicht sehr angenehm zum Arbeiten...

Liebe Grüsse 

Anna

![bildschirmfoto 2017-07-10 um 13 40 52](https://user-images.githubusercontent.com/26789445/28019066-e0a8b49e-657f-11e7-9322-6b12ed659027.png)
![bildschirmfoto 2017-07-10 um 11 44 35](https://user-images.githubusercontent.com/26789445/28019090-f5ea93e0-657f-11e7-9ec0-5d767c7ce3fe.png)

**Comment by barbalex** [comment]
Ja, das ist, weil ich Datenstrukturen verändert habe.

Die Meldungen bringt man weg, indem man für apflora.ch den cache löscht.

In Chrome geht das so:
- chrome://settings besuchen
- "Erweiterte Einstellungen anzeigen" klicken
- "Inhaltseinstellungen" klicken
- "Alle Cookies und Websitedaten" klicken
- oben rechts im Suchfeld, in dem steht "Cookies suchen" nach apflora suchen
- auf apflora klicken
- alle Daten entfernen, d.h. auf alle Einträge klicken und dann "Entfernen" wählen

Uff, ist das kompliziert...
