### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#411]
Nina Lohri meldet:
"Die DB hat sich generell mehrmals aufgehängt. Sobald der 2. Strukturbaum auch benutzt wird, ist alles instabil."

Vielleicht kann noch etwas optimiert werden? Jetzt ist ja die Zeit, wo die FloraDB am häufigsten genutzt wird, da wäre es schade, wenn sich die Benutzer ärgern.

**Comment by barbalex** [comment]
Ist das nachvollziehbar?
Kannst du es nachvollziehen?
Wie kann ich es nachvollziehen?

**Comment by barbalex** [comment]
Hat Nina Lohri Daten und Cache geleert?
Auf welchem Browser arbeitet sie, mit welcher Version?

**Comment by barbalex** [comment]
Schliesse wegen Inaktivität
