### ISSUE TITLE
Auf TPop zoomen funktioniert nicht

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#412]
Hoi Alex 

Wenn ich mithilfe des gelb leuchtenden Blümchens auf eine markierte Teilpopulation zoomen möchte, funktioniert das nicht (mehr).
Könntest du dir das mal anschauen?
Vielen Dank!
![Bildschirmfoto 2020-12-03 um 16 51 37](https://user-images.githubusercontent.com/30288503/101053469-1d664c80-3588-11eb-89bb-2373406cc3b2.png)

**Comment by barbalex** [comment]
Das kann ich nachvollziehen.

Die verwendete Karten-Software hat kürzlich eine völlig neue Version publiziert. Das Upgrade hat mich mehr als einen ganzen Tag Arbeit gekostet. Ich kann es daher nicht einfach rückgängig machen.

Das von dir beschriebene Verhalten scheint ein Fehler der neuen Version zu sein. Habe es beim Entwickler gemeldet (https://github.com/PaulLeCam/react-leaflet/issues/799).

Hoffen wir, dass er das bald beheben kann.

**Comment by rebeccakurz** [comment]
Hast du hier schon etwas gehört?

**Comment by barbalex** [comment]
Ja. Scheinbar habe ich die Dokumentation nicht aufmerksam genug gelesen und daher nicht gemerkt, dass die Art, wie das gemacht wird, verändert wurde 🙄 

Ist in Version 1.48.7 korrigiert.

**Comment by rebeccakurz** [comment]
Super, danke!!
