### ISSUE TITLE
Exporte vorab Filtern

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#413]
Hoi Alex

Wäre es möglich, dass die Exporte im Voraus gefiltert werden könnten, sodass nicht nachher die Excel-Tabellen bearbeitet werden müssten? Also dass z.B. nur die Massnahmen von 2020 exportiert werden würden?

**Comment by barbalex** [comment]
Prinzipiell schon. Aber:

- Der Aufwand für die Programmierung ist hoch
- Ein Teil der Exporte kombiniert Daten aus verschiedenen Tabellen. Wie sollten in der App gesetzte Filter in solchen Fällen greifen? Das Potential für Missverständnisse wäre hoch
- Die App würde auch für die Benutzerinnen komplexer. Man könnte z.B. aus Versehen gefilterte Daten exportieren, ohne sich dessen bewusst zu sein
- In der App kann man heute nicht nach einem bestimmten Jahr filtern, sondern nur nach Daten. Diese Fähigkeit müsste zuerst implementiert werden (Filterung nach von...bis)
- In Excel filtern ist einfach

Ich will damit nicht sagen, dass es eine schlechte Idee sei. Nur, dass es sich bloss lohnt, wenn die Sache gut durchdacht ist und vor allem dann, wenn es Fälle gibt, die nach dem Export in Excel nicht machbar sind.

**Comment by barbalex** [comment]
lol

Diese App kann schon so viel, dass ich schon lange nicht mehr weiss, _was_ sie alles kann.

Was du willst ist schon implementiert. Zumindest bei einigen der Exporten.

Ich habe oben geschrieben:

> Ein Teil der Exporte kombiniert Daten aus verschiedenen Tabellen. Wie sollten in der App gesetzte Filter in solchen Fällen greifen? Das Potential für Missverständnisse wäre hoch

Das wurde insofern berücksichtigt, dass nur der Filter der entsprechenden Tabelle gesetzt wird. Also bei Massnahmen der Massnahmen-Filter. Ohne Rücksicht auf allfällig gesetzte Filter auf Ebene TPop, Pop oder AP.

> Die App würde auch für die Benutzerinnen komplexer. Man könnte z.B. aus Versehen gefilterte Daten exportieren, ohne sich dessen bewusst zu sein

Das wurde insofern abgefangen, dass bei den Exporten, die filtern, ein entsprechender Hinweis erscheint

> In der App kann man heute nicht nach einem bestimmten Jahr filtern, sondern nur nach Daten. Diese Fähigkeit müsste zuerst implementiert werden (Filterung nach von...bis)

Diese Einschränkung bleibt. Bei Massnahmen und Kontrollen funktioniert es aber, weil es auch das Feld für das Jahr gibt, es immer automatisch ergänzt wird, wenn ein Datum gewählt wird und man somit dort nach Jahr filtern kann.

Ich schliess mal diesen Issue. Wenn du Ergänzungen zur Umsetzung wünscht, öffne bitte einen neuen.
