### ISSUE TITLE
Exporte letzte Zählungen

### ISSUE THREAD

**Issue by kmarti** [barbalex/apf2#414]
in den Exporten letzte Zählungen für Populationen und auch für Teilpopulationen mit und ohne noch nicht kontrollierter Anpflanzungen hat es bei Anagallis minima gar keine Zählungen drin. Auch bei anderen Arten sieht es nach grossen Lücken aus.

Da wir jetzt die Zielüberprüfungen für die Jahresberichte machen müssen, brauchen wir diese Exporte dringend!

**Comment by barbalex** [comment]
Der Grund liegt darin, dass die Abfragen so komplex sind, dass die Zähleinheiten nicht dynamisch einbezogen werden können, sondern statisch integriert werden mussten.

Mit anderen Worten: Die Abfragen enthalten eine Liste von Zähleinheiten, wie sie existierte, als die Abfragen erstellt wurden.

Mittlerweile habt ihr aber offenbar die Einheiten geändert oder umbenannt. Alle neuen oder umbenannten Einheiten werden daher von den Abfrage nicht erfasst.

Ich werde das anpassen.

**Comment by barbalex** [comment]
Ist in Version 1.45.1 korrigiert
