### ISSUE TITLE
EK-Planung: Filter blockiert Frequenz-Berechnung

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#415]
Hoi Alex
Ich habe gerade gemerkt, dass in der EK-Planung die EK-Frequenzen nicht mehr (richtig) berechnet werden können. Ich glaube, es ist, weil nur noch die letzten 5 Jahre angezeigt werden und daher eine Ansiedlung vor 2015 nicht mit einberechnet wird.
Also ich hatte den konkreten Fall, dass ich bei einer TPop den Status geändert habe und dann die Meldung kam, dass keine Planung gesetzt werden kann, da es keine Ansiedlung gab, die das Start-Jahr festsetzt. Ich bin dann im Strukturbaum nachschauen gegangen und es gab eine Ansaat im Jahr 2014. Dann habe ich in der EK-Planung die Jahre, die angezeigt werden sollen von 5 auf 10 erhöht und nochmals die EK-Frequenz gesetzt. Dann hat es mir die EK-Planung korrekt gesetzt. 

Ich habe es dann auch noch bei Abies alba ausprobiert und es war genau das selbe (siehe Screenshots, TPop 32.1)
![apflora v1 48 0 - Google Chrome 15 12 2020 08_44_43](https://user-images.githubusercontent.com/30288503/102186501-004c4a80-3eb3-11eb-92ab-b6c408b86d45.png)
![apflora v1 48 0 - Google Chrome 15 12 2020 08_49_47](https://user-images.githubusercontent.com/30288503/102186512-0510fe80-3eb3-11eb-8f35-b473dcfc46cc.png)

Könntest du dir das bitte anschauen?

**Comment by barbalex** [comment]
Du hast völlig recht. Ich habe auch bei der Abfrage die Jahre eingeschränkt, was zu diesem ungewollten Verhalten geführt hat 🙄 

Das wird mit Version 1.48.1 korrigiert. Nun wird also nur noch eingeschränkt, welche Spalten angezeigt werden - nicht mehr, welche bei der Berechnung berücksichtigt werden: bei der Berechnung werden immer alle Daten verwendet.

Einziges Problem: Das Werkzeug, um die Version live zu setzen spinnt seit heute. Keine Ahnung, wann ich es wieder zum Funktionieren bringe. Arbeite daran.

**Comment by rebeccakurz** [comment]
Okay, vielen Dank!

**Comment by barbalex** [comment]
Endlich hat es geklappt 🎉
