### ISSUE TITLE
Export "Kontrollen" mit EK-Plan-Jahr (ja/nein) und Abrechnungstyp ergänzen

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#416]
Wunsch von ChS: "Es wäre recht informativ, wenn im normalen EK-Export auch noch das EK-Plan-Jahr (ja/nein) und der Abrechnungstyp integriert wäre."

Würde das gehen?

**Comment by barbalex** [comment]
Bitte entschuldige meine lange Leitung: Was ist mit `EK-Plan-Jahr (ja/nein)` gemeint?

**Comment by rebeccakurz** [comment]
Hm ich glaube sie möchte, dass im Export angezeigt wird, ob eine EK geplant ist oder nicht... Werde aber nochmals nachfragen.

**Comment by barbalex** [comment]
Was heisst: `ob eine EK geplant ist`? Das wird ja bereits für jedes Jahr detailliert ausgewiesen. War ja der Sinn dieses Exports.

**Comment by barbalex** [comment]
Der Abrechnungstyp ist heute schon integriert. Man muss einfach nur das entsprechende Feld einblenden, dann kommen die Daten auch im Export mit.

**Comment by rebeccakurz** [comment]
Ich glaube sie meint eben nicht den Export bei der EK-Planung, sondern den "normalen" Export der Kontrollen
![Bildschirmfoto 2020-12-16 um 15 58 39](https://user-images.githubusercontent.com/30288503/102365295-ac775980-3fb7-11eb-8b95-3c5775489957.png)

Werde aber nochmals genauer nachfragen.

**Comment by barbalex** [comment]
Dort könnte Abrechnungstyp ergänzt werden. Ist aber nur eines von 8 Feldern aus der Tabelle ekfrequenz. Fragt sich, welche Felder genau informativ wären (z.B. Kürzel).

Die ganze EK-Planung hingegen: Das ist eine extrem komplexe Abfrage. Würde diesen Export auf diversen Ebenen völlig überladen:
- Komplexität für die Benutzer (offene Anzahl Spalten, es ist gar nicht möglich, wie im EK-Formular, die zu exportierenden Spalten zu wählen)
- Komplexität für die Programmierung der Abfrage
- Leistungsansprüche an den Server
- Menge der vom Server zu retournierenden Daten

**Comment by rebeccakurz** [comment]
Okay, dann lassen wir diese Erweiterung weg, da sie zu viel Aufwand und zu wenig Vorteile bringt.
