### ISSUE TITLE
Jahresbericht Grafiken

### ISSUE THREAD

**Issue by kmarti** [barbalex/apf2#417]
Im Jahresbericht von Eriophorum gracile werden in der Grafik (kontrollierte) Teilpopulationen im Jahr 2020  keine kontrollierten TP ausgewiesen, obwohl 17 TP kontrolliert worden sind.
Ist dies, weil keine zielrelevanten Einheiten gezählt worden sind?

**Comment by kmarti** [comment]
Bei Liparis loeselii sind im Jahresbericht 2020 in der Grundmenge 54 ursprünglich aktuelle Populationen angegeben. Im Export PopLetzteZaehlungeninklMassn sind es nur 48 ursprünglich aktuelle Populationen. in der Grafik Stati der Populationen werden hingegen 73 ursprünglich aktuelle Populationen angezeigt. Sind da vielleicht die ausserkantonalen Pop auch dabei? Den Unterschied zwischen Grundmenge im Jahresbericht und dem Export Zählungen kann ich  mir nicht erklären.

**Comment by barbalex** [comment]
> Im Jahresbericht von Eriophorum gracile werden in der Grafik (kontrollierte) Teilpopulationen im Jahr 2020 keine kontrollierten TP ausgewiesen, obwohl 17 TP kontrolliert worden sind.
> Ist dies, weil keine zielrelevanten Einheiten gezählt worden sind?

Ich kann die Daten selbst nicht beurteilen - ist mir zu aufwändig, alle einzeln zu prüfen. Du müsstest mir ev. konkrete Kontrollen auflisten, die nicht erscheinen.

Aber generell ist es richtig, dass die Abfrage nur Kontrollen auflistet, bei denen die zielrelevante Einheit erfasst wurde. Das sind die SQL-Bedingungen direkt auf den Kontrollen:
```sql
where
  -- Jahr muss existieren
  kontr2.jahr is not null
  -- nur aktuelle Stati
  and tpop2.status in (100, 200, 201)
  -- nur von berichts-relevanten tpop
  and tpop2.apber_relevant = true
  -- nur wenn eine Anzahl erfasst wurde
  and zaehl2.anzahl is not null
  -- nur wenn die Ziel-Einheit erfasst wurde
  and ze2.code = zaehl2.einheit
```

**Comment by kmarti** [comment]
Bei all diesen 17 TP wurden keine zielrelevanten Einheiten erfasst. Dann ist dies der Grund, weshalb sie nicht in der Grafik sind. Aber im Bericht selber "Anzahl kontrollierte TP" sind sie aufgeführt. Das ist dann schon ein Widerspruch, wenn die Grafik nicht mit den Zahlen im Bericht übereinstimmt.

**Comment by barbalex** [comment]
> Bei Liparis loeselii sind im Jahresbericht 2020 in der Grundmenge 54 ursprünglich aktuelle Populationen angegeben. Im Export PopLetzteZaehlungeninklMassn sind es nur 48 ursprünglich aktuelle Populationen. in der Grafik Stati der Populationen werden hingegen 73 ursprünglich aktuelle Populationen angezeigt. Sind da vielleicht die ausserkantonalen Pop auch dabei? Den Unterschied zwischen Grundmenge im Jahresbericht und dem Export Zählungen kann ich mir nicht erklären.

Richtig.

Bedingung in der Abfrage, welche der Grafik "Stati der Populationen" zugrunde liegt:
```sql
where status is not null
```

Im Export "Letzte Zählungen inklusive noch nicht kontrollierter Anpflanzungen" ist es komplizierter. Diese Abfrage basiert auf der entsprechenden Auswertung der Teilpopulationen. Diese Abfrage ist so selten (Crosstab) und schwierig, dass ich sie auf die Schnelle nicht verstehe, daher nicht sicher sagen kann, was genau gefiltert wird. Grundsätzlich geht es um Zählungen, daher werden vermutlich Teilpopulationen ohne Zählung nicht aufgeführt. Weshalb es gut möglich ist, dass hier einige der Populationen nicht enthalten sind.

Im Jahresbericht wird eine Population aufgelistet:
- wenn es apber-relevante Teilpopulationen gibt

Die Kriterien sind also nicht überall gleich. Je nach Ziel, welches der Darstellung zugrunde liegt.

**Comment by barbalex** [comment]
> Bei all diesen 17 TP wurden keine zielrelevanten Einheiten erfasst. Dann ist dies der Grund, weshalb sie nicht in der Grafik sind. Aber im Bericht selber "Anzahl kontrollierte TP" sind sie aufgeführt. Das ist dann schon ein Widerspruch, wenn die Grafik nicht mit den Zahlen im Bericht übereinstimmt.

Ja, das widerspricht sich, wenn man dieses Diagramm direkt unter die anderen Zahlen im Bereich A des Jahresberichts stellt.

Dort, wo diese Grafik zuerst eingefügt wurde, steht sie aber direkt unter derjenigen Grafik, die heisst: "Pflanzen total nach Populationen". Dort gäbe es eher Widersprüche, wenn Kontrollen gezeigt würden, welche nicht der zielrelevanten Einheit entsprechen. Aber das ist ev. weniger tragisch.

Ich kann recht einfach in der Grafik "kontrollierte Teil-Populationen" die angewendeten Filter ändern. Sag mir einfach, was du willst.

**Comment by kmarti** [comment]
Liparis: wäre es möglich, dass in der Grafik Status Populationen nur diejenigen Populationen aufgelistet werden, wie im Jahresbericht, die im Kanton Zürich vorkommen?

**Comment by kmarti** [comment]
Eriophorum gracile: Dann bitte in der Grafik "(kontrollierte) Teilpopulationen" bei den kontrollierten TP auch diejenigen aufführen, bei welchen nicht die zielrelevanten Einheiten gezählt wurden, also alle kontrollierten TP.

**Comment by barbalex** [comment]
"(kontrollierte) Teilpopulationen" wird recht komplex berechnet. Es werden nicht nur die Kontrollen geprüft, sondern auch Anpflanzungen, in denen die Anzahl gemäss Zieleinheit geprüft wurde. Es können hier also auch Populationen erscheinen, in denen bloss eine Anpflanzung erfolgte, nicht aber eine Kontrolle. Übrigens nicht in erloschenen Populationen (auch nicht in Potentialflächen).

Im Prinzip wird also dargestellt: Die Anzahl Teilpopulationen mit Kontrollen oder Anpflanzungen, bei denen die Anzahl gemäss zielrelevanter Einheit erhoben wurde.

Diese Abfrage baut mit viel Aufwand diese Zahlen auf. Das habe bestimmt nicht ich erfunden. Es muss so sein, dass ihr von mir genau das verlangt habt. Mir scheint, diese Statistik stellt dar, wie gut/vollständig die EK durchgeführt wurde.

Im Gegensatz dazu stellt die Zahl im Jahresbericht unter "B. Bestandesentwicklung" folgendes dar:
Anzahl TPop aller Stati ausser potentiell (also inkl. erloschen), die apber-relevant sind, _für die im Berichtjahr ein Teil-Populations-Bericht erstellt wurde_. Es werden also nicht echte Kontrollen gezählt, sondern die (in der Regel wohl darauf beruhenden) Berichte.

Wenn der Zweck des Diagramms im Jahresbericht ist, den Verlauf der unter "B. Bestandesentwicklung" dargestellten Zahl mit den Jahren darzustellen, müssen wir dafür ein neues Diagramm schaffen. Das genau das macht.

Was meinst du?

**Comment by barbalex** [comment]
> Eriophorum gracile: Dann bitte in der Grafik "(kontrollierte) Teilpopulationen" bei den kontrollierten TP auch diejenigen aufführen, bei welchen nicht die zielrelevanten Einheiten gezählt wurden, also alle kontrollierten TP.

Ist gemacht. Das Resultat siehst du ab sofort ohne die App zu aktualisieren.

**Comment by barbalex** [comment]
Um den Zweck von "kontrollierte Teil-Populationen" nochmals anders zu formulieren: Dieses Diagramm stellt dar, mit welchen Kontrollen das genau darüber befindliche namens "Pflanzen total nach Populationen" berechnet wurde. Bei der Art macht es also durchaus genau so Sinn, wie es gebaut wurde. Bloss im AP nicht.

**Comment by barbalex** [comment]
> Liparis: wäre es möglich, dass in der Grafik Status Populationen nur diejenigen Populationen aufgelistet werden, wie im Jahresbericht, die im Kanton Zürich vorkommen?

Das ist umgesetzt und ohne Update des App sichtbar.

**Comment by barbalex** [comment]
@kmarti 

Ich hab das Gefühl, dass in diesem komplizierten Issue, der mehrere Dinge betrifft, ein Punkt untergegangen ist, den ich noch gerne klären möchte. Nämlich:

> Wenn der Zweck des Diagramms im Jahresbericht ist, den Verlauf der unter "B. Bestandesentwicklung" dargestellten Zahl mit den Jahren darzustellen, müssen wir dafür ein neues Diagramm schaffen. Das genau das macht.
> 
> Was meinst du?

**Comment by kmarti** [comment]
Für mich ist in der Grafik  "Pflanzen total nach Populationen" auch die gesamte Bestandesentwicklung dargestellt. Ich würde also keine weitere Grafik brauchen.

ich hätte aber noch folgende zwei Wünsche:
- Die Grafik "Stati der Populationen" umbenennen in "Populationen nach Status"
- in der gleichen Grafik nicht "ursprünglich erloschen" aufzeigen, sondern "ursprünglich erloschen (nach 1950)" wie in den Grundmengen im Bericht

**Comment by barbalex** [comment]
Die Wünsche sind in Version 1.48.8 umgesetzt

**Comment by barbalex** [comment]
Sorry, hab die Verpackung vergessen: 🎁

**Comment by kmarti** [comment]
Danke!!

**Comment by kmarti** [comment]
Kaum ist Weihnachten vorbei, habe ich schon neue Wünsche:
- In der Grafik "(kontrollierte) Teil-Populationen" sollten alle kontrollierten TP erscheinen, nicht nur diejenigen, in welchen die zielrelevanten Einheiten gezählt wurden. Dies ist nach meiner Einschätzung noch nicht so umgesetzt. Die Grafik sollte dann mit den Zahlen im Bericht (Bestandesentwicklung) übereinstimmen.
- Den Titel der Grafik "(kontrollierte) Teil-Populationen" ändern in: "(kontrollierte) aktuelle Teil-Populationen inkl. Ansaaten". Wenn ich das richtig nachvollzogen habe, dann sind die kontrollierten erloschenen TP nicht dabei.
-  Wäre es möglich, in der Grafik "Pflanzen total nach Populationen", die ursprünglichen und die angesiedelten Populationen mit unterschiedlichen Farben anzuzeigen?

**Comment by barbalex** [comment]
> In der Grafik "(kontrollierte) Teil-Populationen" sollten alle kontrollierten TP erscheinen, nicht nur diejenigen, in welchen die zielrelevanten Einheiten gezählt wurden. Dies ist nach meiner Einschätzung noch nicht so umgesetzt. Die Grafik sollte dann mit den Zahlen im Bericht (Bestandesentwicklung) übereinstimmen

Bitte lies meinen Kommentar weiter oben dazu: https://github.com/barbalex/apf2/issues/417#issuecomment-746941189
Darin hatte ich genau das angesprochen. Die Zahlen können nämlich nur dann übereinstimmen, wenn sie vollständig anders berechnet werden bzw. neu eben genau gleich wie für den Jahresbericht. Womit sich die Frage stellt, wieso sie denn in eurem Auftrag mit so viel Aufwand anders berechnet wurden. Und ob das alles verworfen werden soll oder ob es etwas doch für etwas anderes verwendet werden soll.

Mir stellt sich mittlerweile die Grundsatzfragen:

- wozu werden die Grafiken Beim Aktionsplan im Bereich "Auswertung" benötigt?
- wozu werden sie im Jahresbericht benötigt?

Ich vermute im Jahresbericht sollen sie die Zahlen des Jahresberichts grafisch erläutern und einen Vergleich mit den Vorjahren ermöglichen.

Beim Aktionsplan hingegen haben wir mit sehr viel Aufwand Zahlen berechnet, welche viel mehr mit den eigentlichen Kontrollen und Massnahmen zu tun haben. Vermutlich im Zusammenhang mit der EK und ihrer Organisation bzw. ihrem Management.

Der Zweck muss klar sein. Mir ist ehrlich gesagt momentan gar nicht klar, wieso es die Grafiken beim AP überhaupt gibt, da die von euch beauftragte komplexe Berechnung offenbar gar nicht (mehr) von Interesse ist. Vielleicht hab ich auch nicht verstanden, dass du völlig neue, unabhängige Grafiken wünscht.

> Den Titel der Grafik "(kontrollierte) Teil-Populationen" ändern in: "(kontrollierte) aktuelle Teil-Populationen inkl. Ansaaten"

Wie oben erwähnt (https://github.com/barbalex/apf2/issues/417#issuecomment-746941189) werden Ansaaten nicht berücksichtigt, hingegen Anpflanzungen, in denen die Anzahl gemäss Zieleinheit geprüft wurde. Damit dieser Titel stimmt, müssen wir die Zahlen ganz anders berechnen. Siehe meine Rückfrage im nächstoberen Absatz.

> Wäre es möglich, in der Grafik "Pflanzen total nach Populationen", die ursprünglichen und die angesiedelten Populationen mit unterschiedlichen Farben anzuzeigen?

Ja, das müsste gehen. Dann brauchen wir allerdings auch eine Legende, die den Unterschied erklärt.

**Comment by kmarti** [comment]
Die Grafiken waren von aller Anfang an für den Jahresbericht vorgesehen und nicht als separate Auswertung in der APFlora-Datenbank, obwohl das natürlich auch gut ist, wenn das dort angeschaut werden kann.
Kaspar war es ein Anliegen, dass im Jahresbericht die Entwicklung der Populationen, Teilpopulationen und der Individuen pro Art in einer Grafik dargestellt wird. Für die Entwicklung der Populationen (Populationen nach Status) und der Teilpopulationen ((kontr.) Teilpopulationen) sind deshalb die Zahlen, wie sie im Jahresbericht aufgeführt sind relevant. 

Wenn bei (kontr.) Teilpopulationen die Ansaaten nicht berücksichtigt werden, ist das auch ok resp. noch besser. Ich dachte rein aufgrund der Zahlen, dass diese auch drin sind. Dann muss ich das nochmals prüfen.

Für die Darstellung der Individuenzahl  (Pflanzen total nach Populationen) braucht es aber die neue Berechnung mit den relevanten Zieleinheiten, da dies anders gar nicht möglich ist. Diese Grafik ist also genau so, wie sie sein sollte. Mit der Farbunterscheidung ursprünglich/angesiedelt wäre sie dann perfekt.

**Comment by barbalex** [comment]
> Wäre es möglich, in der Grafik "Pflanzen total nach Populationen", die ursprünglichen und die angesiedelten Populationen mit unterschiedlichen Farben anzuzeigen?

Nachtrag, nachdem ich das genauer angeschaut habe: Es ist nicht ganz so einfach. Die Daten zeigen ja die Anzahlen pro Jahr und Population. Nichts im Datenmodel verhindert, dass irgendwann ein Status geändert wird. Mit anderen Worten: Der Status kann _prinzipiell_ genauso mit den Jahren ändern, wie die Anzahlen.

Ich bin mir bewusst bzw. glaube, dass eine Änderung von ursprünglich zu angesiedelt oder umgekehrt eigentlich nie stattfinden sollte. Kannst du das bitte bestätigen? Wenn das so ist, kann ich den Status aus einem einzelnen Jahr verwenden, um die Farbe der  Fläche zu bestimmen. Was natürlich ein falsches Bild gäbe, wenn der Status ändern würde.

**Comment by barbalex** [comment]
> Die Grafiken waren von aller Anfang an für den Jahresbericht vorgesehen und nicht als separate Auswertung in der APFlora-Datenbank, obwohl das natürlich auch gut ist, wenn das dort angeschaut werden kann.

Schade. Wir bzw. ich haben daher mehrere Tage Arbeit vergebens geleistet. Und ich muss es jetzt also neu aufbauen.

**Comment by barbalex** [comment]
O.k., ich muss also die folgenden Grafiken neu aufbauen:

- Populationen nach Status (genau gleich wie im Bericht)
- kontrollierte Teilpopulationen (beruhend auf Berichten statt Zählungen, genau gleich wie im Jahresbericht)

Bist du dir bewusst, dass so wie es heute berechnet wird, die Grafik "<zielrelevante Einheit> nach Populationen" der Grafik "kontrollierte Teilpopulationen" prinzipiell widersprechen kann, weil sie auf anderen Daten beruht? Unter anderem werden dort Anpflanzungen, die mit der zielrelevanten Einheit erfasst wurden gezeigt. Dabei gibt es nicht zwingend eine Kontrolle bzw. einen Populations-Bericht. Ich gehe davon aus, dass das kein Problem ist, weil ja eh nur diejenigen Daten ausgewertet werden können, welche mit der zielrelevanten Einheit erfasst wurden.

**Comment by kmarti** [comment]
Es tut mir leid, wenn ich die ursprüngliche Absicht nicht deutlich genug vermittelt habe.

Grafik "Pflanzen total nach Populationen": Es sollte definitionsgemäss keinen Wechsel des Status von ursprünglichen zu angesiedelten Populationen geben und umgekehrt auch nicht. Einen Wechsel gibt es ganz selten einmal, wenn eine Status-Einschätzung einer älteren Population revidiert wird.

Widerspruch zwischen "zielrelevante Einheit nach Populationen" und "kontrolliert TP": Das sollte kein Problem sein.

**Comment by barbalex** [comment]
> Einen Wechsel gibt es ganz selten einmal, wenn eine Status-Einschätzung einer älteren Population revidiert wird.

Das kann ich aber in der Grafik nicht darstellen - mindestens sehe ich nicht, wie. Ist es also i.O., wenn in diesen Fällen ein falscher Status angezeigt werden kann?

**Comment by kmarti** [comment]
Ja, das ist i.O.

**Comment by barbalex** [comment]
Ich hab jetzt grad gemerkt: Es werden z.T. auch Populationen gezeichnet, die es gar nicht mehr gibt. Das heisst: ich kann nicht einfach den aktuellen Status verwenden - das führt zu einem Absturz, weil es den nicht gibt.

**Comment by barbalex** [comment]
Ich müsste also eine zusätzliche Abfrage ausführen, welche für alle dargestellten Populationen das letzte Jahr sucht, in dem es die Population noch gab (bzw. wo die zielrelevante Einheit gezählt wurde), und daraus den Status liest.

Nicht simpel.

**Comment by barbalex** [comment]
Gezählt wird natürlich nicht in Populationen sondern in Teilpopulationen. Ich muss also für jede dargestellte Population das letzte Jahr finden, in dem in irgend einer Teilpopulation die zielrelevante Menge gezählt wurde. Und dann in diesem Jahr den Status nachschauen. Denn es kann sein, dass die Population gar nicht mehr existiert.

**Comment by barbalex** [comment]
Kann ich stattdessen in Fällen, in denen die Population nicht mehr existiert, eine neutrale Farbe verwenden? Z.B. Grau?

**Comment by barbalex** [comment]
> Wäre es möglich, in der Grafik "Pflanzen total nach Populationen", die ursprünglichen und die angesiedelten Populationen mit unterschiedlichen Farben anzuzeigen?

Ist in Version 1.48.9 implementiert. Die Farbe (grün für ursprünglich, orange für angesiedelt, wie bei "Populationen nach Status") wird von der aktuellen Populationen gelesen. Graue Populationen (gibt es nicht mehr, daher kein Status verfügbar) sind sehr selten.

Leider kann ich mit der verwendeten Technologie keine Legende für diesen Fall bauen. Die Farben lehnen sich aber an der Grafik "Populationen nach Status" an.

Um die anderen Grafiken neu aufzubauen, brauche ich etwas länger. Sollte aber in den nächsten Tagen folgen.

**Comment by barbalex** [comment]
Rückfrage zur Grafik "Populationen nach Status": Aktuell unterscheidet sie nicht die  genau gleichen Stati, wie der Bericht im Bereich A.

Die Grafik unterscheidet aktuell:

- ursprünglich, aktuell 
- ursprünglich, erloschen (nach 1950)
- angesiedelt, aktuell
- Ansaatversuch
- angesiedelt, erloschen/nicht etabliert
- potentieller Wuchs-/Ansiedlungsort

Der Bereich A unterscheidet:

- ursprünglich, aktuell 
- angesiedelt (vor Beginn AP)
- angesiedelt (nach Beginn AP) 
- erloschen (nach 1950): zuvor autochthon oder vor AP angesiedelt
- erloschen (nach 1950): nach Beginn Aktionsplan angesiedelt 
- Ansaatversuch
- potentieller Wuchs-/Ansiedlungsort

Wenn das Ziel dieser Grafik ist, die Daten aus dem Bereich A im zeitlichen Verlauf darzustellen, müssten dann nicht dieselben Kategorien verwendet werden?

Ich gehe davon aus, dass die Antwort ja ist. Aber bitte bestätige mir das.

**Comment by barbalex** [comment]
Die Grafik "Populationen nach Status" wurde in Version 1.48.10 angepasst:

- Genau die gleichen Kategorien wie im Bereich A des Jahresberichts
- Genau gleich berechnet
- Vorsicht: Die Berechnung beruht auf den historisierten Daten. Im Jahresbericht hingegen werden die aktuellen Daten abgefragt. Mit anderen Worten: Für das aktuelle Jahr kann es Unterschiede geben, wenn du nicht kurz vor dem Druck des Jahresberichts historisierst

Ev. hast du Verbesserungs-Vorschläge für die Legende, d.h. welche Farben für welche Kategorie verwendet werden.  Ich kann das einfach anpassen.

**Comment by barbalex** [comment]
Ach ja: Die Abfrage ist jetzt für die App aufwändiger, weil mehr App-Seitig berechnet wird. Das führt leider dazu, dass der Jahresbericht deutlich länger braucht, um sich aufzubauen 😞

**Comment by barbalex** [comment]
Vielleicht sollte ja der Jahresbericht auch besser auf die historisierten Daten greifen? Muss ich mir mal überlegen.

**Comment by barbalex** [comment]
Die Grafik "(kontrollierte) Teil-Populationen" wurde in Version 1.48.11 aktualisiert:

- Es sollten die genau gleichen Zahlen verwendet werden, wie für die Bereiche A (Anzahl TPop) und B (Anzahl Tpop kontrolliert) im Jahresbericht
- Wie in der Grafik "Populationen nach Status" werden die Daten des aktuellen Jahrs aber im Gegensatz zum Jahresbericht nicht aus den aktuellen Daten gelesen, sondern aus den historisierten. Daher können Unterschiede auftreten, wenn nicht kurz vor dem Berichtsdruck historisiert wurde

> Den Titel der Grafik "(kontrollierte) Teil-Populationen" ändern in: "(kontrollierte) aktuelle Teil-Populationen inkl. Ansaaten"

"inkl. Ansaaten" ist korrekt. Nicht aber "aktuelle". Wie im Jahresbericht sind Berichte zu allen Teil-Populationen berücksichtigt, die nicht ein "potentieller Wuchs-/Ansiedlungsort" sind. Wird also eine erloschene Teil-Population kontrolliert, erscheint das hier.

Daher hab ich den Titel vorläufig gelassen, wie er ist.

Jetzt arbeite ich noch daran, die Abfrage für "Populationen nach Status" effizienter zu machen, damit der Jahresbericht etwas weniger langsam lädt.

**Comment by kmarti** [comment]
Ich bin sehr froh, dass im Jahresbericht die aktuellen Zahlen verwendet werden und nicht die historisierten. So kann ich über einen längeren Zeitraum die Kontrollen machen und allfällige Korrekturen veranlassen. Bei einer einmaligen Historisierung bleibt mir keine Zeit für die Kontrolle, die Anpassung und die Schlusskontrolle.
Wann hat denn nun die letzte Historisierung stattgefunden? In den letzten Tagen haben die Daten bei vielen Arten gar nicht mehr geändert. Deshalb kann ich mir Unterschiede zwischen Grafik "Populationen nach Status" und den Zahlen im Jahresbericht nicht wirklich erklären.

**Comment by barbalex** [comment]
Die letzte Historisierung siehst du im AP-Bericht, hier: https://apflora.ch/Daten/Projekte/e57f56f4-4376-11e8-ab21-4314b6749d13/AP-Berichte/d0df6ad6-3b22-11eb-812b-3f3f968533ee?apTab=auswertung&feldkontrTab=entwicklung&idealbiotopTab=idealbiotop&popTab=pop&projekteTabs=tree&projekteTabs=daten&qkTab=qk&tpopTab=tpop&tpopmassnTab=tpopmassn. Hat offenbar am 10.12.2020 stattgefunden.

Klick einfach auf die Schaltfläche und warte, bis die Rückmeldung kommt, dass die Daten neu historisiert wurden.

Nur Manager sehen diese Schaltfläche.

Wichtig ist, dass die letzte Historisierung gleichzeitig mit dem endgültigen Druck des Jahresberichts passiert. Und danach nicht mehr. Die Schaltfläche wird ab März des Folgejahrs nicht mehr angezeigt.

**Comment by barbalex** [comment]
Ach ja: der Bericht, für den ich dir geschickt hatte, hatte ich bei mir lokal frisch historisiert - darum sind dort Bericht und Grafiken auf demselben Stand.

**Comment by barbalex** [comment]
Wichtig zu wissen: Ich habe ja kürzlich geändert: Man kann jetzt bis Ende Februar so oft historisieren, wie man will. Sollte aber natürlich nach Druck des endgültigen Jahresberichts nicht mehr, damit die Historisierten Daten denjenigen im endgültigen Bericht entsprechen.

**Comment by barbalex** [comment]
> Ich bin sehr froh, dass im Jahresbericht die aktuellen Zahlen verwendet werden und nicht die historisierten. So kann ich über einen längeren Zeitraum die Kontrollen machen und allfällige Korrekturen veranlassen. Bei einer einmaligen Historisierung bleibt mir keine Zeit für die Kontrolle, die Anpassung und die Schlusskontrolle.

Da du jetzt bis Ende Februar beliebig oft historisieren kannst, wäre das auch möglich, wenn der Jahresbericht die historisierten Daten benutzen würde.

Vorteile wären: 
- es gäbe keine Differenzen zwischen Jahresbericht und Grafiken
- es könnten jederzeit Jahresberichte für frühere Jahre wieder erzeugt werden

Nachteile:
- Art-Verantwortliche, welche den aktuellen Jahresbericht einzelner Arten anschauen, sehen keine bzw. nicht immer aktuelle Daten. Das ist schlecht, wenn sie den Bericht nutzen, um ihre eigenen Eingaben zu kontrollieren

Ich werde das Thema nicht weiter verfolgen, ausser du wünscht es.

**Comment by barbalex** [comment]
Ich schliess das mal in der Annahmen, das die Grafiken für dieses Jahr i.O. sind.
Ansonsten: Bitte neuen Issue öffnen. Hier kann man mittlerweile recht einfach die Übersicht verlieren.
