### ISSUE TITLE
Frequenz-Setzung EK-Planung: neu gegründete und "neu" erloschene TPops

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#418]
**siehe Issue #402** 
Nachdem die Artverantwortlichen alle Massnahmen eingegeben haben, müssen ja für die neu entstandenen Teilpopulationen die EK-Frequenzen gesetzt werden. Dies geschieht ja im Moment halbautomatisch, also du setzt provisorisch die passenden EK-Frequenzen, wir kontrollieren die Vorschläge und geben das Okay.
Wäre es möglich, dass gleichzeitig auch bei den dieses Jahr neu erloschenen Teilpopulationen die EK-Frequenz "nie" gesetzt wird?

**Antwort Alex:** Ja, beruhend auf der Version der Daten, die historisiert wurde: Was damals noch nicht den Status erloschen hatte, aber jetzt schon, wird auf nie gesetzt.

**Comment by barbalex** [comment]
Wann rechnet ihr, dass dies geschehen soll?

**Comment by rebeccakurz** [comment]
Die Artverantwortlichen haben Zeit bis zum 10. Januar um ihre Massnahmen einzugeben. 
Es wäre gut, wenn die Frequenz-Setzung möglichst bald danach geschehen würde. Also ab dem 11. Januar.

**Comment by kmarti** [comment]
Möglichst gerade am 11. Januar!

**Comment by barbalex** [comment]
Habe den Termin reserviert
