### ISSUE TITLE
Neue Art erstellen

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#42]
Funktioniert nicht, oder ich weiss einfach nicht wie ?

**Comment by barbalex** [comment]
richtig, das ist noch pendent

**Comment by barbalex** [comment]
Ist implementiert. Funktioniert momentan erst im Projekt apflora zh. Wird später erweitert, um auch in neuen Projekten zu funktionieren. Ich warte aber damit, bis ich eine neue Server-Kommunikations-Technologie einführe
