### ISSUE TITLE
QK: Pop-Bericht in Pop mit ursprünglichen TPops

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#420]
Uns ist aufgefallen, dass es in der Qualitätskontrolle zwar diese Kontrolle zu den Populationsberichten gibt:
"Population mit angesiedelten Teilpopulationen (vor dem Berichtjahr), die (im Berichtjahr) kontrolliert wurden, aber ohne Populations-Bericht (im Berichtjahr)"
Aber mit dieser QK werden Populationen mit ursprünglichen TPops nicht abgedeckt. 
Könntest du eine solche Kontrolle noch ergänzen? Oder die bestehende Kontrolle auf alle Populationen anwenden?
Vielen Dank!

**Comment by barbalex** [comment]
> Aber mit dieser QK werden Populationen mit ursprünglichen TPops nicht abgedeckt

Wie kommst du darauf? Die Qualitätskontrolle prüft nicht den Status. Sondern ob es Teilpopulationen gibt, in denen Ansiedlungen stattfanden (https://github.com/barbalex/apf2/blob/master/sql/apflora/functions/qPopOhnePopber.sql#L51-L53). Der Status ist in der Abfrage kein Kriterium.

Die Qualitätskontrolle sollte wohl besser so heissen:
"Populationen mit Ansiedlung (vor dem Berichtjahr), die (im Berichtjahr) kontrolliert wurden, aber ohne Populations-Bericht (im Berichtjahr)".

Kannst du mir bitte nochmals erklären, was du meinst?
Ist es für euch i.O., wenn ich die Kontrolle wie erwähnt umbenenne, damit die Beschreibung besser zutrifft?

**Comment by barbalex** [comment]
Jetzt habe ich verstanden: Du meinst diese Qualitätskontrolle aus den Aufgaben für 2020:

> Population mit Kontrolle (im Berichtjahr), aber ohne Populations-Bericht (im  Berichtjahr)    
> analog zu Tpop

Habe soeben die ursprüngliche QK "Population mit angesiedelten Teilpopulationen (vor dem Berichtjahr), die (im Berichtjahr) kontrolliert wurden, aber ohne Populations-Bericht (im Berichtjahr)" erweitert. Sie heisst nun: "Population mit Teilpopulationen, die (im Berichtjahr) kontrolliert wurden. Aber ohne Populations-Bericht (im Berichtjahr)"
