### ISSUE TITLE
failed to fetch

### ISSUE THREAD

**Issue by kmarti** [barbalex/apf2#422]
Wenn ich eine Qualitätskontrolle bei Rosa gallica, Scorzonera humilis oder Seseli libanotis machen möchte, kommt die Meldung: apolle client Network error: TypeError: Failed to fetch. 
Diese Meldung ist auch bei anderen Eingaben (Bericht erstellen bei Zielüberprüfung) gekommen.

**Comment by barbalex** [comment]
Da hat offenbar die Verbindung von dir zum Server nicht funktioniert. Das kann am Server selbst liegen, falls er gerade nicht verfügbar war, oder an deiner Internetverbindung.

Ich habe keine Hinweise darauf, dass der Server in den letzten 14 Tagen jemals zu einem wesentlichen Ausfall gekommen wäre. Allerdings habe ich ungefähr dann, als du dieses Problem hattest, den Server aktualisiert und daher auch neu gestartet. Ich weiss nicht mehr genau, wann das war. Aber ev. hast du genau diesen kurzen Moment erwischt. Das dauert in aller Regel höchstens ein paar Dutzend Sekunden. Während dieser Zeit wird jede Datenanfrage scheitern. Danach funktioniert aber wieder alles.

Normalerweise mache ich das Nachts. Es ist wichtig, um die Sicherheit der App zu gewährleisten. Ausnahmsweise habe ich das tagsüber gemacht. In der Annahme, dass ihr Ferien macht. Sorry!
