### ISSUE TITLE
Export Populationen inkl letzter PopBericht - falscher Eintrag

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#423]
Hoi Alex
Ich bin gerade dabei die Karten für den Jahresbericht zu erstellen. Diesen zugrunde liegt der Export "Populationen mit dem letzten Populationsbericht". 
Dabei ist mir aufgefallen, dass bei Thesium rostratum die Population 21 mit Status "angesiedelt, aktuell" drin ist (im Gegensatz zu letztem Jahr, als sie noch "ursprünglich, erloschen" war. Ich habe darum in der FloraDB nachgeschaut, dort ist die Population korrekt mit Status "ursprünglich, erloschen" drin. Ich habe dann noch den Export "Populationen" gemacht, dort ist die Population ebenfalls korrekt mit "ursprünglich, erloschen" drin. 
Der Fehler scheint also nur im Export "Populationen mit dem letzten Populationsbericht" zu sein. Und es scheint auch nur diese Population einen falschen Status zu haben, sonst ist mir bis jetzt noch nicht aufgefallen. 

Könntest du dir das bitte mal anschauen?
Vielen Dank!

[Populationen_2021-01-07_16-47-19.xlsx](https://github.com/barbalex/apf2/files/5782617/Populationen_2021-01-07_16-47-19.xlsx)
[PopulationenMitLetzemPopBericht_2021-01-07_16-46-02.xlsx](https://github.com/barbalex/apf2/files/5782618/PopulationenMitLetzemPopBericht_2021-01-07_16-46-02.xlsx)

**Comment by barbalex** [comment]
Das ist nicht schön.

Ich hab jetzt gerade auch diesen Export gemacht. Und der Status stimmt: 
[PopulationenMitLetzemPopBericht_2021-01-07_17-11-05.xlsx](https://github.com/barbalex/apf2/files/5782729/PopulationenMitLetzemPopBericht_2021-01-07_17-11-05.xlsx)

Es gibt folgende Möglichkeiten, dass es bei deinem Export nicht stimmt:
- Systematischer Fehler der Abfrage. Ist nicht der Fall
- Der Wert hat in der Datenbank geändert: ist nicht passiert. Die Population wurde zuletzt 2018-04-18 von René Bertiller verändert
- Der Wert wurde beim Export-Vorgang verändert: Das müsste ein sehr unwahrscheinliches, nicht zu erklärendes Ereignis gewesen sein, ausgelöst durch irgend einen eher zufälligen Vorgang (z.B. kurzfristige Überlastung des PC's). Ist nicht besonders wahrscheinlich aber vermutlich möglich
- der Wert wurde von Excel beim erstmaligen Öffnen verändert. Excel interpretiert beim Öffnen einer Datei die Daten. Wieso? Microsoft hat das nicht dokumentiert. Aber ich vermute, weil Excel die Daten formatiert, vor allem Daten ("Datümer"). Excel hat mir schon extrem oft Daten verändert. Darum ist Excel ein brandgefährliches Werkzeug, um .csv-Dateien zu öffnen, weil das dort besonders oft zu passieren scheint. Da dies keine .csv-Datei war, ist dieser Vorgang vermutlich weniger wahrscheinlich, aber ich kann nicht beurteilen, wie oft so was beim Öffnen von xlsx-Dateien passieren kann
- der Wert wurde nach dem Öffnen verändert. Jedes Mal, wenn du den Fokus aus einem Feld herausnimmst, interpretiert Excel wieder den Wert im Feld. Kann ja sein, dass der Wert neu Formatiert werden muss. Ähnliches Problem wie beim Erstmaligen Öffnen von .csv-Dateien. Excel hat auch die Eigenschaft, innerhalb von Listen einem beim Tippen zu helfen, indem es Werte aus der Liste vorschlägt. Und je nach deiner Aktion gleich einfügt

Persönlich habe ich das Gefühl das eine der letzten zwei Möglichkeiten am ehesten zutreffen sollte. Aber ich kann es natürlich nicht sicher sagen.

Vielleicht musst du anfangen, systematisch zu kontrollieren, ob solche Dinge öfter vorkommen. Persönlich finde ich Excel extrem vertrauensunwürdig. Wenn solche Sachen öfter vorkommen, sollte man meiner Ansicht nach auf andere Werkzeuge wechseln. Welche garantiert nie Daten verändern. Excel gehört definitiv nicht dazu.

Was wäre eine Alternative? .csv-Dateien kombiniert mit einer Datenbank oder vermutlich auch Libre-Office.

**Comment by rebeccakurz** [comment]
Danke, dass du es dir angeschaut hast. Ich denke auch nicht, dass es ein systematischer Fehler ist. Aber ich hatte schon am Dienstag den Export gemacht gehabt, mit dem ich dann gearbeitet habe und den Fehler entdeckt habe. Dann habe ich extra nochmals einen aktuellen Export gemacht (den, den ich angefügt hatte) und da war der Fehler ja auch noch drin, das hat mich dann verunsichert...

Nun habe ich mich ausgeloggt aus der FloraDB (was ja automatisch den Cache leert) und wieder neu angemeldet und jetzt ist der Export auch wieder richtig...

Hoffen wir, dass es ein einmaliger Fehler war.

**Comment by barbalex** [comment]
Diese Daten werden direkt vom Server geladen. Der Cache sollte keinen Einfluss haben

**Comment by kmarti** [comment]
Sorry, dass ich mich erst jetzt dazu melde. Ich habe Rene Bertiller gebeten eine Korrektur vorzunehmen und die Pop. 21 von Thesium rostratum auf ursprünglich erloschen zu setzen und mit der neuen Ansiedlung eine neue Population zu machen. Das hat zu dieser Differenz geführt.
