### ISSUE TITLE
Erste Zählung von aktuellen ursprünglichen Populationen, aber nur von den ursprünglichen Teilpopulationen (ohne die angesiedelten TP): Total der zielrelevanten Einheiten aller ursprünglichen TP.

### ISSUE THREAD

**Issue by barbalex** [barbalex/apf2#424]
@rebeccakurz @kmarti 

Ich komme nach genauerer Prüfung wieder mal mit aufwendigen Nachfragen.

In den "Aufgaben 2020" scheint nachträglich (da dafür der Aufwand nicht geschätzt wurde) diese Aufgabe hinein gekommen zu sein:

> Export "Letzte Zählungen inklusive noch nicht kontrollierter Anpflanzungen" ergänzen .  RK: Diesen Export ergänzen mit den ersten Zählungen zusammengezählt pro Pop.

### Vorbemerkung: 

Es handelt sich hier um eine besonders schwierige und aufwändig zu codierende Abfrage (nicht aber überaus leistungs-hungrige). Und die Abfrage für Populationen baut auf der analogen für Teilpopulationen auf. Daher sind diese Abfragen besonders fragil und aufwändig zu unterhalten.

App-seitig gibt es dann nochmals recht viel Code, der auf diesen SQL-Abfragen aufbaut. Denn die Daten müssen abgefragt und in Excel-Tabellen überführt werden.

Die speziellen Probleme sind: 
1. Zähleinheiten werden dynamisch definiert. Es kann beliebig viele geben und sie können prinzipiell jederzeit ändern. Darum ändern bei dieser Abfrage nicht nur die Zeilen, sondern auch die Spalten dynamisch. Der Fachbegriff ist "crosstab". Lieder ist es praktisch nicht möglich, dass die Abfrage sich wirklich dynamisch an veränderte Zähleinheiten anpasst, wie wir kürzlich schmerzhaft erfahren haben (weil die Einheiten umbenannt wurden)
2. Neben den Zähleinheiten aus Kontrollen müssen auch Zählungen in verschiedenen Einheiten aus Massnahmen berücksichtigt werden

Der SQL-Code für die Teilpopulationen allein ist 233 Zeilen lang.

Natürlich _kann_ ich das machen. Aber es braucht ein paar Stunden Arbeit. Und erhöht die Komplexität des Codes beträchtlich.

Ich schätze den Aufwand auf eine vollen Arbeitstag. Für die Erst-Erstellung. Im Unterhalt werden künftig bestimmt noch einige Stunden dazu kommen.

### Meine Fragen dazu:

> Diesen Export ergänzen mit den ersten Zählungen zusammengezählt pro Pop

1. Wie soll das dargestellt werden? 

Heute werden für die letzte Zählung 27 Spalten benötigt, plus diejenige für das Jahr. Ist gemeint, dass vor oder nach diesen 28 Spalten nochmals 28 Spalten folgen, welche  für das erste Jahr, in dem eine Zählung oder Anpflanzung erfolgte, die analogen Daten aufgelistet werden?

2. Wie nutzt ihr das sinnvoll?

Ich frage, weil nicht nur die Anzahl Spalten verdoppelt wird. Sondern auch der Code für die beiden aufeinander aufbauenden Abfragen. Und den Code App-Seitig, um die Daten abzufragen und für Excel aufzubauen. Ich kann es nur grob schätzen, aber insgesamt dürfte diese Änderung dazu führen, dass wir von ca. 700 Zeilen Code auf rund 1300 Zeilen kommen. **Für eine einzige Abfrage**

3. Gibt es weniger aufwändige oder nützlichere Alternativen?

Wenn ihr versucht, aus diesen über 60 Spalten eine Übersicht zu gewinnen, so gibt es vermutlich bessere Darstellungsmöglichkeiten. Z.B. ein Diagramm pro Teilpopulation/Population/AP, dass die Änderung der Summen pro Zähleinheit mit den Jahren darstellt. Bzw. einfach in zwei Balkendiagrammen, wenn es zwei Jahre sind. Falls das sich dann wirklich als nützlich beweisen sollte (die Symbolisierung ist bei so vielen Einheiten nicht ganz einfach - aber vermutlich sind bei einer einzelnen Art nur selten sehr viele Zähleinheiten verwendet worden).

Das wäre dann so ungefähr, wie die Darstellung für die zielrelevante Einheit. Bloss mit viel mehr Einheiten und ev. weniger Jahren.

Wenn es nicht exportiert werden muss, wäre der Aufwand vermutlich nicht viel höher, als für den beschriebenen Export. Aber ev. ist der Nutzen höher?

**Comment by rebeccakurz** [comment]
Hoi Alex
Also diesen Export braucht man ja für die Zielüberprüfung und bei einigen Zielen muss man vergleichen, wie sich eine Population im Vergleich zum Ausgangszustand verändert hat (also ob zb eine ursprüngliche Population erhalten werden konnte oder zb verdoppelt etc.)
Daher wäre es praktisch gewesen, wenn die erste Zählung ebenfalls in diesem Export enthalten wäre. Aber wenn das so aufwändig umzusetzen ist, lohnt es sich vielleicht doch nicht. 
Jetzt habe ich dieses Jahr die Zielüberprüfung nicht gemacht, sondern Karin. @kmarti: Veilleicht kannst du noch sagen, wie du das siehst? Hätte dir ein solcher Export geholfen oder ist es gut ohne gegangen?

**Comment by kmarti** [comment]
Folgender separater Export wäre hilfreich: Erste Zählung von aktuellen ursprünglichen Populationen, aber nur von den ursprünglichen Teilpopulationen (ohne die angesiedelten TP): Total der zielrelevanten Einheiten aller ursprünglichen TP.

**Comment by barbalex** [comment]
@kmarti 

Wie soll auf Ebene Population die "erste Zählung" gewählt werden?

Hier ein paar mögliche Varianten:
1. Bei jeder aktuell ursprünglichen TPop einer aktuell ursprünglichen Pop wird separat ermittelt, welches die erste Zählung ist, welche für die zielrelevante Einheit erfolgte. Diese wird verwendet (auch wenn das theoretisch heissen könnte, dass Zahlen aus im Extremfall stark unterschiedlichen Jahren summiert werden). In diesem Fall kann aber kein eindeutiges Jahr für die erste Zählung ausgewiesen werden. Nur eine Liste von Jahren
2. Es wird das Total gerechnet, für das erste Jahr, in dem in mindestens einer Teil-Population die zielrelevante Einheit erfasst wurde
3. Es wird das Total gerechnet, für das erste Jahr, in dem in allen Teil-Populationen die zielrelevante Einheit erfasst wurde (ich nehme an, du meinst das?)
4. Es wird das Total gerechnet, für das erste Jahr, in dem in allen Teil-Populationen die zielrelevante Einheit erfasst wurde _und für das es auch historisierte Populationen und Teilpopulationen gibt_

Letzteres mag erstaunen, aber es ist die einzige Variante, die _theoretisch_ zuverlässige Werte liefert. Weil der Status als Kriterium genommen wird. Zählungen gibt es bis weit in die Vergangenheit zurück:

Jahr | anz Kontrollen
-- | --
2020 | 1349
2019 | 1271
2018 | 1355
2017 | 1247
2016 | 1210
2015 | 884
2014 | 890
2013 | 951
2012 | 837
2011 | 722
2010 | 582
2009 | 571
2008 | 549
2007 | 344
2006 | 276
2005 | 538
2004 | 361
2003 | 331
2002 | 174
2001 | 224
2000 | 20
1999 | 31
1998 | 11
1997 | 21
1996 | 20
1994 | 2
1993 | 1
1990 | 1
1980 | 1
1972 | 1
1971 | 1
1970 | 1
1945 | 1

Aber historisierte Pop und TPop nur bis 2014.

Bloss sollte eigentlich der Status "ursprünglich, aktuell" nie geändert haben.

Also meinst du vermutlich Variante 3? Das heisst, wir gehen davon aus, dass eine Population oder Teil-Population mit Status "ursprünglich, aktuell" diesen Status schon immer hatte? Und müssen daher nicht mit den historisierten Daten vergleichen?

(letzteres ist von Bedeutung, weil wir sonst Massnahmen ergreifen müssten, um die Leistungs-Anforderungen der Abfrage zu minimieren)

**Comment by rebeccakurz** [comment]
Momentan nicht nötig/anders gelöst
