### ISSUE TITLE
Zählungen erstellen funktioniert nicht

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#425]
Hoi Alex

Eine der AV wollte gestern noch eine Zählung in einer Feldkontrolle ergänzen, die vergessen gegangen war. Aber es hat nicht geklappt zum eine neue Zählung erstellen. Das war bei Aristolochia TPop 10.3 und 10.5.

Ich habe es nun auch noch ausprobiert und auch bei mir hat es nicht geklappt. Habe es bei Abies alba probiert und bei Thalictrum galioides. Eine neue Feldkontrolle erstellen geht, aber es kann keine neue Zählung gemacht werden (auch nicht in bereits erstellten Feldkontrollen oder in Feldkontrollen, die bereits eine Zählung haben).

Könntest du dir das bitte anschauen?

**Comment by barbalex** [comment]
Ihr habt gewünscht, dass in Freiwilligen-Kontrollen Zählungen ohne Anzahlen nicht mehr angezeigt werden. Bzw. erst, wenn die Anzahl erfasst wurde.

Das habe ich kürzlich umgesetzt. Und dabei übersehen, dass dieselbe Abfrage für die Feldkontrollen verwendet wird. Neue Feldkontrollen haben noch keine Anzahl, daher wurden sie auch nicht mehr angezeigt... 🙄 

Die neuen Zählungen wurden übrigens schon geschaffen, bloss nicht angezeigt. D.h. es gibt dort wo ihr das probiert habt wohl jetzt eine ganze Reihe davon...

Ist in Version 1.49.4 korrigiert. Sorry!

**Comment by rebeccakurz** [comment]
Okay, danke, jetzt geht es wieder einwandfrei.
