### ISSUE TITLE
neue QK: nicht automatisch angezeichnet

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#426]
Mir ist bei den Qualitätskontrollen noch aufgefallen, dass die neu erstellte QK "Teilpopulation mit Anpflanzungen im aktuellen Jahr. Aber die zielrelevante Einheit wurde nicht erfasst" nicht automatisch "angehäkelt" wurde. Siehe Screenshot, nur 100 von 101 QK aktiv.
![Bildschirmfoto 2021-01-12 um 11 41 14](https://user-images.githubusercontent.com/30288503/104304332-8a47fd00-54cb-11eb-9b9a-a84230539f92.png)

**Comment by barbalex** [comment]
Danke für den Hinweis. Habe soeben eine Abfrage ausgeführt, die diese Qualitätskontrolle überall einschaltet

**Comment by rebeccakurz** [comment]
Das scheint nicht geklappt zu haben mit dieser Abfrage, die neueste Qualitätskontrolle ist wieder nicht eingeschaltet worden.
![Bildschirmfoto 2021-01-18 um 08 36 49](https://user-images.githubusercontent.com/30288503/104886114-7b4cc900-5969-11eb-8948-a80a2d69cc45.png)

**Comment by barbalex** [comment]
Offenbar habe ich die Abfrage, welche die Qualitätskontrolle einschaltet, bloss lokal ausgeführt 🙄 

Danke für den Hinweis.
