### ISSUE TITLE
bestehende QK: Ansaatversuch fehlt

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#427]
Könntest du in der bestehenden Qualitätskontrolle: "Population: Status ist aktuell (ursprünglich oder angesiedelt) oder potentieller Wuchsort; der letzte Populations-Bericht meldet aber erloschen und es gab seither keine Ansiedlung"

Bei den anderen QK dieser Art ist der Ansaatversuch enthalten, bei dieser fehlt er jedoch.
![Bildschirmfoto 2021-01-12 um 18 04 10](https://user-images.githubusercontent.com/30288503/104348242-c5fdb980-5501-11eb-8ede-712f9099eee4.png)
Danke!

**Comment by barbalex** [comment]
Sorry, ich verstehe nicht, was du willst. Kannst du es bitte nochmals erklären?

**Comment by rebeccakurz** [comment]
Die Qualitätskontrolle sollte heissen: "Population: Status ist aktuell (ursprünglich oder angesiedelt), **Ansaatversuch** oder potentieller Wuchsort; der letzte Populations-Bericht meldet aber erloschen und es gab seither keine Ansiedlung"

Also gerne den Status "Ansaatversuch" in der QK ergänzen. (Sorry, ich habe oben ja einfach  den Satz unbeendet gelassen!)

**Comment by barbalex** [comment]
Es gibt vier entsprechende Abfragen. Bei allen wurde die Abfrage explizit so designt, dass Ansaatversuche nicht enthalten sind:

name | titel | view | Ansaatversuche enthalten?
-- | -- | -- | --
popStatusAktuellLetzterPopberErloschen | Population: Status ist aktuell (ursprünglich oder angesiedelt) oder   potentieller Wuchsort; der letzte Populations-Bericht meldet aber erloschen   und es gab seither keine Ansiedlung | v_q_pop_statusaktuellletzterpopbererloschen | nein
popStatusErloschenLetzterPopberUnsicher | Population: Status ist erloschen (ursprünglich oder angesiedelt) oder   potentieller Wuchsort; der letzte Populations-Bericht meldet aber unsicher   und es gab seither keine Ansiedlung | v_q_pop_statuserloschenletzterpopberunsicher | nein
tpopStatusAktuellLetzterTpopberErloschen | Teilpopulation: Status ist aktuell (ursprünglich oder angesiedelt) oder   potentieller Wuchsort; der letzte Teilpopulations-Bericht meldet aber   erloschen und es gab seither keine Ansiedlung | v_q_tpop_statusaktuellletztertpopbererloschen | nein
tpopStatusErloschenLetzterTpopberUnsicher | Teilpopulation: Status ist erloschen (ursprünglich oder angesiedelt) oder   potentieller Wuchsort; der letzte Teilpopulations-Bericht meldet aber   unsicher und es gab seither keine Ansiedlung | v_q_tpop_statuserloschenletztertpopberunsicher | nein

Ich müsste also nicht nur den Titel anpassen sondern die Abfrage selbst.

**Comment by rebeccakurz** [comment]
Hoi Alex
Ich habe mir das nochmals angesehen und versucht durchzudenken. 
Bei zwei dieser Qualitätskontrollen ist es richtig, dass der Status Ansaatversuch nicht enthalten ist, nämlich bei der, wo der Pop Status erloschen ist und der letzte Pop-Bericht unsicher, respektive bei, wo der TPop Status erloschen ist und der letzte TPop-Bericht unsicher. 

Bei den anderen zwei, wo der Pop-Status (resp. TPop) aktuell ist und der letzte Pop-Bericht (resp. TPop) erloschen ist, sollte der Status "Ansaatversuch" enthalten sein. 
Diese Zusammenhänge ist auch in der folgenden Matrix nochmals festgehalten: Wenn der Status einer Pop (TPop) Ansaatversuch ist, dann darf der letzte Pop- (TPop-) Bericht unsicher sein, aber er darf nicht erloschen sein. 
![Matrix_mögl_Komb_Status_Bericht](https://user-images.githubusercontent.com/30288503/104453842-52ad8380-55a5-11eb-8042-dd54e46d38d8.jpg)

Könntest du also in den Qualitätskontrollen "Population: Status ist aktuell (ursprünglich oder angesiedelt) oder potentieller Wuchsort; der letzte Populations-Bericht meldet aber erloschen und es gab seither keine Ansiedlung" und "Teilpopulation: Status ist aktuell (ursprünglich oder angesiedelt) oder potentieller Wuchsort; der letzte Teilpopulations-Bericht meldet aber erloschen und es gab seither keine Ansiedlung" die Abfrage und den Titel ändern?
Vielen Dank!

**Comment by barbalex** [comment]
Gefällt mir, dass du die damals von Charlotte für diesen Zweck benutzte Darstellung weiterführst!

Ist gemacht (sollte ohne Update wirken).
