### ISSUE TITLE
Grafik (kontrollierte) Teilpopulationen im Jahresbericht / in Auswertung

### ISSUE THREAD

**Issue by kmarti** [barbalex/apf2#429]
Bei einzelnen Arten reicht die Kurve der Teilpopulationen in der Grafik "(kontrollierte) Teilpopulationen" in den darüberstehenden Text (im Ausdruck des Jahresberichtes) resp. wird dort abgeschnitten (in der Auswertung zur Art und im digitalen Jahresbericht-pdf).
Dies bei Gentiana cruciata, Gratiola officinalis, Ophrys araneola und besonders extrem bei Litorella uniflora und Orchis palustris.

**Comment by barbalex** [comment]
Bei den kontrollierten TPop und bei den Pop nach Status waren die Werte statt als Zahlen als Text übergeben worden. Irgendwie geht in diesen zwei Fällen das Format auf dem Weg vom Server über die Schnittstelle und das Abfragetool zur Komponente verloren 🤔. 

Das hat wohl zu diesem Verhalten geführt. Hab das jetzt korrigiert und hoffe, dass es in Version 1.49.5 nicht mehr auftritt.
