### ISSUE TITLE
Neue Bearbeiter nicht in V2 sichtbar, V1 aber schon

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#43]
Obwohl neu eingeloggt usw

**Comment by barbalex** [comment]
richtig, das muss ich noch anpassen. Momentan sind die Adressen eine derjenigen Tabellen (wie Status etc.), die nicht automatisch aktualisiert werden.

Bis ich es angepasst habe, kannst du oben rechts im Menu "Stammdaten aktualisieren" wählen

**Comment by barbalex** [comment]
Ist in der Entwicklungsversion behoben. Wegen eines anderen Problems kann ich es aber momentan nicht testen. Also bitte diesen issue wieder öffnen, falls es nach dem nächsten Update nicht funktionieren sollte
