### ISSUE TITLE
Darstellung FloraDB nach neu laden

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#430]
Mir ist es jetzt schon öfters passiert, dass wenn ich die FloraDB neu geladen habe (z.B. wenn eine neue Version verfügbar ist) oder wenn ich z.B. bei der Qualitätskontrolle eine Population in einem neuen Tab öffnen möchte, dass dann die FloraDB nicht korrekt angezeigt wird, sondern dass sie dann so am unteren Bildschirmrand klebt (siehe Screenshot). Ich muss dann die Seite nochmals neu laden und dann wird sie meist korrekt dargestellt. 
Ich habe auch schon von den Artverantwortlichen gehört, dass das bei ihnen ebenfalls passiert ist.

Vielleicht könnte man da irgendetwas machen?

![Screenshot (6)](https://user-images.githubusercontent.com/30288503/104421766-16b1f880-557c-11eb-9e8c-4553d527cf7d.png)

**Comment by barbalex** [comment]
Ja, das ärgert mich auch 😠

**Comment by barbalex** [comment]
Ich kann es in der Entwicklungs-Umgebung nicht provozieren, darum brauche ich irgend eine göttliche Eingebung, um den Fehler zu finden 🤔

**Comment by barbalex** [comment]
Das war früher nicht. Und an den Grundlagen des Layouts habe ich schon lange nichts mehr geändert. Im Prinzip müsste es daher an einem Update von etwas liegen, das das Layout beeinflusst.

**Comment by barbalex** [comment]
Ich habe nun beobachten können, wie im HTML Elemente, die hierarchisch ineinander lagen, bei der Ausgabe NEBEN-einander platziert wurden.

Das darf nicht sein. Es muss wohl ein Fehler von Chromium sein. Vermutlich irgend eine Optimierung im Cache des Browsers.

Ich habe jetzt in Version 1.51.4 versucht, das Layout mit anderen Methoden aufzubauen. Mal schauen, ob es noch passiert. Oder dafür andere Fehler...

**Comment by barbalex** [comment]
Ist mir nun beim nächsten Update nicht mehr passiert. Ich schliesse mal diesen Issue. Da dieser Effekt aber nicht immer auftrat, ist es gut möglich, dass wir den Issue später wieder öffnen müssen.
