### ISSUE TITLE
EK-Frequenz-Setzung: "neu" erloschene TPop: EK-Planung nicht gelöscht?

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#431]
Hoi Alex

Kann es sein, dass zwar die EK-Frequenz-Setzung bei den "neu" erloschenen TPops im 2020 funktioniert hat, aber dass die EK-Planung, also die Häuschen, nicht gelöscht wurden? Eventuell weil das Startjahr nicht angepasst wurde?
Im Screenshot das Beispiel von Aldrovanda vesiculosa, hier gab es 2020 noch eine EK bei der 0 Pflanzen gefunden wurden und danach wurden die TPops auf erloschen gestellt. EK-Frequenz stimmt zwar, aber es gibt noch immer eine EK-Planung und das Startjahr stimmt auch nicht.
![Bildschirmfoto 2021-01-14 um 09 19 16](https://user-images.githubusercontent.com/30288503/104563359-d6b94700-5649-11eb-996f-5ecb9d9d0441.png)

Habe mir gerade nochmals den ursprünglichen Issue angesehen: Wir haben da immer nur von der EK-Frequenz gesprochen, aber eigentlich auch die EK-Planung gemeint. Wieder ein Beispiel für unklare Kommunikation :-( 

Könntest du dir das nochmals ansehen?

**Comment by barbalex** [comment]
Du hast recht. Da haben weder Karin noch ich dran gedacht.

Hab jetzt für alle TPop mit ekfrequenz.code = 'nie (EK)' die EK-Pläne ab 2021 gelöscht.

**Comment by rebeccakurz** [comment]
Super, danke!
