### ISSUE TITLE
Historien für AP, Pop und TPop anzeigen

### ISSUE THREAD

**Issue by barbalex** [barbalex/apf2#433]
Es gibt mittlerweile Qualitätskontrollen, welche auf Änderungen des Status zwischen Jahren hinweisen. Und Grafiken, welche Daten aus früheren Jahren anzeigen.

Daher wäre es vermutlich gelegentlich praktisch, wenn die historisierten Datensätze angezeigt bzw. überprüft werden könnten. Natürlich ohne Schreibrechte.

Möglicher Ort: In einem neuen Register des jeweiligen Formulars. Oder direkt am ursprünglichen Ort.

Gestaltung: Vermutlich als "Karussell": Es gibt links und rechts Pfeile, mit denen man durch die Jahre navigieren kann.

Varianten:

- einfache Darstellung der Daten des betreffenden Jahres
- Gegenüberstellung der Daten dieses Jahrs mit den aktuellen, wobei die Unterschiede hervorgehoben werden (wie in vermehrung.ch)

**Comment by kmarti** [comment]
das wäre schon praktisch....

**Comment by barbalex** [comment]
Für die AP ist es in Version 1.56.0 umgesetzt

**Comment by barbalex** [comment]
Ist in Version 1.57.0 auch für Pop und TPop umgesetzt
