### ISSUE TITLE
Karte: Orthophotos werden nicht angezeigt

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#437]
Wenn man bei der Karte das ZH Orthofoto als Hintergrund nehmen will, wird dieses nicht angezeigt. Das einzige Orthofoto, das zu funktionieren scheint, ist das von Sommer 2014/15 RGB. Die anderen Karten scheinen zu funktionieren, ausser das Bing Luftbild: Wenn man darauf klickt, stürzt das Kartentool ab mit folgender Fehlermeldung und man muss sich nochmals neu einloggen, damit die Karte wieder funktioniert.
![Bildschirmfoto 2021-01-18 um 09 19 54](https://user-images.githubusercontent.com/30288503/104890522-fc0ec380-596f-11eb-8421-896b749b4c58.png)

**Comment by barbalex** [comment]
Das verwendete Werkzeug hat einen Fehler. Keine Ahnung, wieso das nicht schon immer passierte. Ich muss dieses Layer leider ausblenden - die Folgen des Fehlers sind ziemlich katastrophal, weil die Speicherung des Zustands dazu führt, dass man ohne Neu-Anmeldung nicht mehr rein kommt.

Ist in Version 1.51.2 gemacht

**Comment by barbalex** [comment]
Habe jetzt herausgefunden, das der Kanton ZH wieder mal seine Layer umbenannt hat. Darum kamen keine Daten mehr. Das ist leider nicht das erste Mal. Und wird offensichtlich auch kaum das letzte Mal sein 😢 

In Version 1.51.3 sollten die Zürcher Luftbilder wieder funktionieren. 2018 ist immer noch das aktuellste angebotene Datum.

**Comment by rebeccakurz** [comment]
Danke, es klappt wieder!
