### ISSUE TITLE
Import von durch AV's gesammelten Beobachtungen direkt über die Benutzeroberfläche

### ISSUE THREAD

**Issue by barbalex** [barbalex/apf2#439]
@kmarti @rebeccakurz : bitte schaut euch dieses Konzept für euren Wunsch an. Und sagt mir, ob ich mit der Umsetzung beginnen kann. Die vorbereitenden Schritte habe ich schon ausgeführt, sie sind ohnehin empfehlenswert.

### Ziel
AV's sind zuständig, Beobachtungen aus Inventaren, Herbaren etc. zu sammeln und zu importieren. Es wäre darum praktisch, wenn sie eine einfache Methode hätten, diese Listen selber in apflora zu importieren.

### Vorbereitung: Quellen-Angabe flexibilisieren
- [x] neues Feld beob.quelle
- [x] Daten von beob_quelle_werte.name nach beob.quelle importieren
- [x] Alle Bezüge zum alten Feld zum neuen migrieren
- [x] Tabelle beob_quelle_werte und Feld beob.quelle_id entfernen

### Voraussetzung
Was ist, wenn die von den AV's direkt in apflora importierten Beobachtungen via dem nationalen Kreislauf bzw. SISF-Import wieder kommen? 

**Es ist nötig, dass AV's ihren Beobachtungen eigene ID's geben (GUID). Und diese mitliefern, wenn sie die Daten in den nationalen Kreislauf schicken** (siehe unten). Apflora muss das Vorhandensein beim Import prüfen und den Import verweigern, wenn diese ID's nicht existieren oder nicht eindeutig sind. Apflora muss natürlich den AV's auch erklären, wie sie möglichst einfach solche ID's erstellen können (wenn sie die Beobachtungen in EvAB erfassen und dessen Export hier importieren, gibt es sie automatisch).

Und: Wir sind darauf angewiesen, dass Info Flora diese ID wieder liefert, damit wir verhindern können, dass diese Beobachtungen mehrfach in apflora importiert werden.

Das wird heute mit den Beobachtungen aus EvAB schon so gehandhabt. Sollte also grundsätzlich funktionieren können.

### Benutzerführung
- [ ] Bei den nicht beurteilten Beobachtungen gibt es ein Menü "Beobachtungen importieren"
- [ ] Das Menü öffnet ein Formular
- [ ] Es erklärt (Voraussetzungen, wie es geht...) 
- [ ] Benutzer wählt eine der AP-Arten.
      Importiert wird immer pro AP-Art bzw. -Synonym, damit Benutzer nicht selber die arteigenschaften-ID ergänzen müssen.
      Will heissen: Fehlt das zu importierende Synonym, muss es zuvor als AP-Art ergänzt werden
- [ ] Benutzer wählt einen prägnanten, kurzen Namen für die Quelle, ähnlich einer Literaturangabe, z.B. "Info Flora 2017". Er sieht dabei die Liste der bisher importierten Quellen.
      Importiert wird immer pro Quelle und der Benutzer sieht eine Liste der bisher importierten Quellen. Zweck: Gute, aussagekräftige Quellen-Angaben und Vermeidung von Mehrfach-Importen
- [ ] Benutzer wählt das in den Daten verwendete Koordinatensystem. Zur Auswahl stehen: LV03, LV95, ev. WGS84 (voreingestellt ist LV95)
- [ ] Benutzer wählt eine Excel- oder csv-Datei. Sie enthält:
  - Spaltentitel  in der ersten Reihe
  - Beobachtungen ab der zweiten Reihe 
- [ ] Die Daten werden geprüft. Wenn ein Teil davon nicht importiert werden kann, werden diese Daten aufgelistet und erklärt, warum. Geprüft wird:
  - Die Wahl der korrekten arteigenschaften-ID ist gegeben, da sie vom Benutzer zuvor gewählt wurde und von apflora beim Import angefügt wird
  - Die Quellen-Angabe ist gewährt, weil sie zuvor geschah und von apflora beim Import angefügt wird 
  - [ ] Existiert eine Beobachtungs-ID, ist sie eine GUID und ist sie eindeutig?
  - [ ] Existiert ein Beobachtungs-Datum und ist es als Datum importierbar?
  - [ ] Existieren x- und y-Koordinaten und entsprechen sie dem gewählten Format?
  - [ ] Existiert ein Autor?
- [ ] Bestehen die Daten die Prüfung, werden sie importiert

### Noch zu bestimmen
Sollten AV's die von ihnen importierten Daten auch nach dem Import noch bearbeiten/löschen können? Diese Funktionalität existiert noch nicht. Falls ja: Wer darf diese Daten anpassen?

### Was nicht implementiert ist
Beobachtungen haben in apflora ein freies Format (damit sie als allen möglichen Quellen vereinigt werden können). **Sie können daher nicht nach EvAB oder Info Flora exportiert werden**. Ich gehe davon aus, dass die FNS den AV's vorgibt, wie sie ihre Beobachtungen in den nationalen/kantonalen Kreislauf bringen. 

Müsste ein Export von apflora zur Info Flora möglich sein, müssten wir:
- Die Daten in genau dem Format verlangen, wie sie Info Flora oder die FNS verlangt
  (das gibt viel mehr Aufwand und die heute für Beobachtungen verwendete Datenstruktur ist im Prinzip nicht dafür geeignet)
- Diese Funktionalität regelmässig überprüfen. Falls das von Info Flora oder der FNS verlangte Format ändert:
  - unseren Import anpassen
  - alle zuvor importierten Daten anpassen?????
- Sicher stellen, dass die Daten nicht auf anderem Weg zur Info Flora gelangen
- Im Prinzip müsste apflora fast alles können, was EvAB bzw. dessen Nachfolger kann bzw. können soll. Und das kann nicht die Aufgabe von apflora sein

Ich bin ziemlich sicher, dass es nicht sinnvoll ist, in apflora importierte Beobachtungen an Info Flora oder einen Nachfolger von EvAB zu exportieren. Sinnvoller ist vermutlich, wenn die AV's diese Daten selber separat an die FNS bzw. Info Flora liefern. Und dabei gewährleistet wird, dass eine ID sie bei Wieder-Import von Info Flora oder der FNS erkenntlich macht.

### Aufwandschätzung

Ca. fünf Arbeitstage (mehr, wenn die importierten Daten bearbeitet werden können sollten).

Das ist viel. Aber: dieser Vorgang ist komplex. Viel Verantwortung liegt bei den AV's. Die grösste Herausforderung ist, sicherzustellen, dass die von den AV's importierten Beobachtungen Mindestanforderungen erfüllen. Und das wäre ohne ein so aufwändig produziertes Formular noch viel aufwändiger, weil: 
1. AV schickt mir Daten
2. Ich schaue sie an. Teile mit, was fehlt
3. AV schickt ergänzte Daten
4. Ich versuche zu importieren. Sage, wieso es nicht geklappt hat
5. AV schickt korrigierte Daten
6. Ich importiere oder erkläre, wieso es nicht geklappt hat
7. Wenn der Import geklappt hat, entscheidet sich beim Re-Import der Info Flora Daten, ob (mit viel Aufwand) die zugehörigen Beobachtungen erkannt werden können (weil die Artverantwortliche die apflora-ID in der Meldung an Info Flora mit geliefert hat), oder ob die ganze Übung vergebens war und nur Verwirrung stiftet

Es ist also bestimmt viel effizienter, wenn wir die nötige Arbeit in diese neue Funktion stecken, um sie möglichst selbsterklärend zu machen. Dann kann nämlich die AV das in einem einzigen Arbeitsgang direkt selber erledigen.

**Comment by rebeccakurz** [comment]
Hoi Alex
Für mich tönt dieses Konzept überzeugend. Ich denke nicht, dass die Daten nach einem Export noch bearbeitet werden sollten. 
Ich werde es noch mit Karin besprechen und wir sagen dir dann, wann du loslegen kannst.

**Comment by barbalex** [comment]
Das macht nun keinen Sinn mehr, weil Beobachtungen nur noch von Info Flora importiert werden.
