### ISSUE TITLE
Massnahmen kopieren

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#44]
funktioniert nicht, verschieben aber schon
![bildschirmfoto 2017-07-12 um 14 15 39](https://user-images.githubusercontent.com/6047564/28119324-c0e5103a-6714-11e7-889a-d76cb5538310.png)

**Comment by barbalex** [comment]
es reicht mir jetzt nicht mehr, das vor den Ferien anzugehen - mache es danach

**Comment by barbalex** [comment]
ha ha: das neue Feld, das den alten GUID enthält, wurde mit kopiert. Und zwei gleiche GUIDS werden von der Datenbank nicht goutiert
