### ISSUE TITLE
mehrere, mit "oder" verbundene Filter setzen

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#445]
Das hatten wir auf unserer Wunschliste, aber nicht geplant für 2020. Gerne würde ich das hier deshalb nochmals aufnehmen, auch weil das als Anregung von den Artverantwortlichen gekommen ist. 
In der Wunschliste hast du geschrieben:

"Konkretes Anliegen: Aus Status können mehrere Einträge gewählt werden.

Idee: Filtern wie in FileMaker:
- Im Titel des Filter-Formulars gibt es Register
- erstes Register ist der Filter, wie er heute gesetzt wird. Erfasst man darin in mehreren Feldern (a und b) einen Filter-Wert, werden Datensätze gefiltert, welche a und b erfüllen
- sobald im ersten Register ein Wert gesetzt wird, erscheint ein neues Register mit Namen "oder"
- erfasst man darin kriterien, wird so gefiltert: Datensätze, welche: die Kriterien aus Register 1 erfüllen ODER diejenigen aus Register 2.
- will man also TPop, die angesiedelt sind (aktuell oder angesät), wählt man im ersten Register "angesiedelt, aktuell" und im zweiten "angesiedelt, Ansaatversuch"
- will man z.B. alle aktuellen sehen, wählt man im ersten Register "ursprünglich, aktuell" und im zweiten Register "angesiedelt, aktuell". Und wenn man will, kann man auch noch die angesäten in einem dritten Register dazu nehmen

Das liesse sich dann auch in anderen Feldern anwenden, z.B. bei den Begründungen, wieso TPop für den AP-Bericht nicht relevant sind. "

**Comment by barbalex** [comment]
Das wird relativ aufwändig. Aber definitiv nützlich, wenn oft gefiltert wird. 

Es gibt einen anderen, noch aufwändigeren Issue: mobile-first (https://github.com/barbalex/apf2/issues/435).

Ich bin nicht sicher, ob ich dieses Jahr beide umsetzen kann. Selbst wenn ich beide schaffe, würde das andere zeitlich nach hinten verschoben.

Welches wäre euch wichtiger?

**Comment by barbalex** [comment]
Rückmeldung aus Feedbackrunde 2.2022 (weiss nicht von wem): 

> Antrag APFlora DB : im Filter, mehrere Kästchen anwählbar machen, zb aktuelle autochthon und aktuell angesiedelte

**Comment by barbalex** [comment]
Ist für die Art ab Version 1.73.0 umgesetzt. Bitte testen und Anregungen/Ideen melden. Werde in den nächsten Wochen dann die übrigen Filter entsprechend erweitern

**Comment by barbalex** [comment]
AP und Pop sind realisiert

**Comment by barbalex** [comment]
TPop ist realisiert

**Comment by barbalex** [comment]
Ich arbeite gleichzeitig daran, alle **vier Arten zu Filtern** zu vereinigen:
- Der vielleicht am wenigsten bewusste: Position im Navigationsbaum (Hiearchie). Benutzer erwarten, dass wenn sie eine Art wählen, auch deren Teile (z.B. Populationen) angezeigt und gefiltert werden. Oder: Wenn keine Art gewählt ist, werden alle Arten des Projekts gefiltert. Das war mindestens teilweise schon bisher so, z.B. wenn in der Karte Pop/TPop angezeigt wurden. Gäbe es diesen Filter nicht, gäbe es keine eindeutige Möglichkeit, z.B. nach allen TPop/Massnahmen/EK einer Population zu filtern. Ich nenne diesen Filter intern den **hierarchischen Filter**
- **(Label-)Filter** im Navigationsbaum
- **Formular-Filter** (oranges Formular mit rot hinterlegtem Titel)
- **Karten-Filter**

Diese vier Methoden waren bisher nicht klar vereinigt/getrennt worden - sie sind nacheinander entstanden. Ich denke, es ist am besten, sie möglichst klar zu deklarieren und immer einheitlich anzuwenden, das heisst: immer alle.
