### ISSUE TITLE
Export Beobachtungen nicht beurteilt

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#449]
Hoi Alex
Von den Artverantwortlichen wurde ein Export der Beobachtungen gewünscht, die noch nicht zugeordnet resp. noch nicht beurteilt wurde. Jetzt habe ich gesehen, dass es einen solchen Export noch gar nicht gibt. 

Wie aufwändig wäre es, einen solchen Export zu generieren?

**Comment by barbalex** [comment]
Einerseits recht aufwändig, weil wir aktuell von einer halben Million Datensätze sprechen. Das dürfte einige Überraschungen bergen, die zu exportieren. Wie gross der Aufwand ist, wissen wir erst, wenn ich es probiert habe. Die Frage ist auch, ob Excel oder was immer die AB's dafür benutzen wollen, damit zurecht kommt.

Anderseits - und das wurde schon wiederholt diskutiert - ist es heikel wegen der Rechte. Wenn das möglich sein soll, muss es explizit von der FNS verlangt bzw. genehmigt werden.

**Comment by rebeccakurz** [comment]
Vielen Dank für deine Antwort, es lässt sich anders lösen.
