### ISSUE TITLE
Karten - Anzeige Koord bei Abständen

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#45]
Sind nicht Schweizer Koord.

Im Prinzip nicht wichtig, aber so für uns auch nicht brauchbar

![bildschirmfoto 2017-07-14 um 17 13 57](https://user-images.githubusercontent.com/6047564/28218140-e8270690-68b7-11e7-8c87-63a16bac673e.png)

**Comment by barbalex** [comment]
ich kann schauen, ob das veränderbar ist - ich verwende hier ein externes Tool
lasse den issue mal stehen, hat aber nicht oberste Prio

**Comment by barbalex** [comment]
Schliesse diesen Issue, weil das Verhalten ohne grösseren Aufwand nicht veränderbar ist
