### ISSUE TITLE
Beobachtungen zuordnen über Karte funktioniert nicht

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#450]
Hoi Alex
Für die neuen Aktionsplan-Arten sind einige der AV bereits am zuordnen der Beobachtungen. Dabei sind leider ein paar Fehler aufgetaucht. Ich werde sie in einzelnen Issues beschreiben

Das Zuordnen der Beobachtungen über die Karte funktioniert leider nicht. Wenn ich das Zuordnen in der Karte aktiviert habe, kann ich die Beobachtung zwar zu der entsprechenden TPop ziehen, aber sie wird ihr nicht zugeordnet, auch nicht wenn ich die Seite aktualisiere.

Könntest du dir das mal anschauen? Danke!

**Comment by barbalex** [comment]
Die verwendete Karten-Software hat offenbar wieder einmal bei einem Update ihr Verhalten undokumentiert verändert. Das Ereignis wird gar nicht mehr erzeugt 😢 

Ich brauche noch etwas Vorarbeit, weil die Entwicklungsversion gerade blockiert ist, weil eine andere verwendete Software beim kürzlichen Update ihr Verhalten geändert hat, worauf sich die Karte gar nicht mehr einblenden lässt 🙄

**Comment by barbalex** [comment]
Es war wirklich eine Änderung am verwendeten Werkzeug.

Ist in Version 1.63.2 korrigiert.

**Comment by rebeccakurz** [comment]
Auch dafür vielen Dank!
