### ISSUE TITLE
Beobachtungen: Befehl "neue Teil-Population in bestehender Population gründen und Beobachtung der Teil-Population zuordnen" funktioniert nicht

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#451]
Wenn ich in einer bestehenden Population eine neue Teilpopulation gründen und die Beobachtung dieser Teilpopulation zuordnen will, funktioniert das nicht (siehe Screenshots). Auch wenn ich eine Beobachtung im Strukturbaum 2 geöffnet habe, funktioniert dieser Befehl nicht.
Befehl: 
![Bildschirmfoto 2021-03-02 um 17 27 32](https://user-images.githubusercontent.com/30288503/109680693-0b8f4800-7b7d-11eb-9223-50911e9771b2.png)
Fehlermeldung wenn in Strukturbaum 1:
![Bildschirmfoto 2021-03-02 um 17 20 55](https://user-images.githubusercontent.com/30288503/109680792-23ff6280-7b7d-11eb-96ba-e5d0989d2ac4.png)
Fehlermeldung wenn im Strukturbaum 2:
![Bildschirmfoto 2021-03-02 um 17 25 19](https://user-images.githubusercontent.com/30288503/109680805-25c92600-7b7d-11eb-819a-e3962356b3a7.png)

**Comment by barbalex** [comment]
Danke für die gute Dokumentation.

Ist in der Entwicklungsversion behoben. Aber da ich dort noch andere Probleme hab, dauert es ev. noch etwas, bis die korrigierte Version live geschaltet wird.

**Comment by barbalex** [comment]
Die korrigierte Version 1.63.1 ist jetzt live

**Comment by rebeccakurz** [comment]
Super, vielen Dank!
