### ISSUE TITLE
Beobachtungen werden, wenn in neuem Fenster geöffnet, nicht richtig angezeigt

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#452]
Wenn ich eine Beobachtung auf der Karte anklicke, kann ich sie ja entweder im Strukturbaum 2 oder in einem neuen Fenster öffnen. 
Wenn ich die Beobachtung im Strukturbaum 2 öffne und die Beobachtung dann einer Teilpopulation zuordnen möchte, werden mir die Daten korrekt angezeigt und auch die Abstände zu den Teilpopulationen:
![Bildschirmfoto 2021-03-02 um 17 17 09](https://user-images.githubusercontent.com/30288503/109681554-e0f1bf00-7b7d-11eb-84b1-279930b00787.png)
Wenn ich die Beobachtung aber in einem neuen Fenster öffne, wird mir die Beobachtung nicht korrekt angezeigt (keine Daten) und auch die Angaben der Abstände zu den Teilpopulationen werden nicht richtig angezeigt:
![Bildschirmfoto 2021-03-02 um 17 18 00](https://user-images.githubusercontent.com/30288503/109681697-08e12280-7b7e-11eb-8ada-bc7bd9e641c6.png)

**Comment by barbalex** [comment]
Ja, da hab ich irgend etwas verknorkst

**Comment by barbalex** [comment]
Hm. Schwierige Sache, Maloney...

**Comment by barbalex** [comment]
Bei mir passierte es nur manchmal.

Zuerst habe ich eine "race condition" vermutet, d.h. dass etwas zu spät passiert. Darum habe ich die Abfragen optimiert, damit die Daten früher ankommen.

Aber dann habe ich gemerkt, dass die Daten z.T. kurzfristig angezeigt werden und danach wieder verschwinden. Und gesehen, dass beim Vorgang die Karte z.T. Fehler generiert. Es scheint, dass der Klick in der Karten-Software auch andere Ereignisse auslöste, und zwar gleich mehrfach. Das habe ich nun verhindern können.

Zusätzlich gab es noch eine dritte mögliche Ursache, die nun behoben sein sollte.

In meinen Tests ist es nun nicht mehr passiert. Hoffen wir, dass das so bleibt.

**Comment by rebeccakurz** [comment]
Bei den ersten Versuchen scheint es bei mir auch zu klappen, danke!
