### ISSUE TITLE
Karten-Filter resp. Beobachtungen in Karte anwählen

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#453]
Dann haben die AV noch gefragt, ob es möglich wäre, dass Beobachtungen in der Karte angewählt werden könnten und danach würde man im Strukturbaum sehen, um welche Beobachtung es sich handelt. Also dass dann die entsprechende Beobachtung im Strukturbaum z.B. gelb hinterlegt wird, wie wir es ja bereits kennen. Wäre das möglich oder gibt es allenfalls bereits eine entsprechende Funktion?
Es gibt ja noch diesen Karten-Filter, mit dem man in der Karte ein Polygon oder ein Rechteck zeichnen kann, um zu filtern. Wäre das genau für diese Funktion gedacht? Leider scheint es (noch) nicht zu funktionieren.
![Bildschirmfoto 2021-03-02 um 17 43 16](https://user-images.githubusercontent.com/30288503/109683115-55792d80-7b7f-11eb-99a9-97884ba75f50.png)

**Comment by barbalex** [comment]
> ob es möglich wäre, dass Beobachtungen in der Karte angewählt werden könnten und danach würde man im Strukturbaum sehen, um welche Beobachtung es sich handelt. Also dass dann die entsprechende Beobachtung im Strukturbaum z.B. gelb hinterlegt wird, wie wir es ja bereits kennen

Das wäre möglich. Es würde direkt die entsprechende Beobachtung geöffnet. Ist vermutlich ca. 1.5 Stunden Aufwand.

> Es gibt ja noch diesen Karten-Filter, mit dem man in der Karte ein Polygon oder ein Rechteck zeichnen kann, um zu filtern. Wäre das genau für diese Funktion gedacht?

Nein. Das ginge gar nicht, weil mehrere Beobachtungen gleichzeitig gewählt werden (können), aber nur eine im Navigationsbaum und Formular aktiv sein kann.

**Comment by rebeccakurz** [comment]
Wäre es denn einfacher, wenn nicht die entsprechende Beobachtung direkt geöffnet würde, sondern nur im Strukturbaum gelb angeleuchtet werden würde? 
Und wenn die entsprechende Beobachtung direkt geöffnet werden würde wäre das im Strukturbaum 2? Oder in einem separaten Fenster? Oder im Strukturbaum 1?

Okay, aber für was ist denn dieser Karten-Filter? Ich habe noch nie damit gearbeitet und es scheint auch keine Auswirkungen zu haben, wenn er angewendet wird?

**Comment by rebeccakurz** [comment]
Gerne würde ich diese Erweiterung (also Beobachtung in Karte anwählen können, so dass sie danach im Strukturbaum aktiv ist) bei der Planungs-Sitzung im Januar besprechen. 
Das wäre eine sehr nützliche Zusatzfunktion. Ich deponiere das hier, damit es hoffentlich nicht vergessen geht.

**Comment by barbalex** [comment]
Ist in Version 1.68.0 implementiert. Bei den Beobachtungen ist die Sache relativ leistungshungrig, weil es 500'000 davon gibt. Bin nicht sicher, dass sich das bewährt.
