### ISSUE TITLE
Beobachtungen: Farb-Unterschied noch nicht zugeordnete und zugeordnete Beobachtungen zu wenig gross

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#454]
Wenn man in der Karte mit den Beobachtungen arbeitet, werden ja noch nicht zugeordnete Beobachtungen in violett und bereits zugeordnete in pink dargestellt. Leider ist dieser Unterschied auf dem z.T. dunklen Kartenhintergrund etwas schlecht zu erkennen. Wäre es möglich z.B. die bereits zugeordneten Beobachtungen in einem anderen Farbton darzustellen oder noch etwas heller, damit man den Unterschied auch auf z.B. alten Bildschirmen gut sieht?
![Bildschirmfoto 2021-03-02 um 17 51 54](https://user-images.githubusercontent.com/30288503/109684141-45ae1900-7b80-11eb-8fbb-7a8661aafdd9.png)

**Comment by barbalex** [comment]
Du hast recht. Bloss:
- Gibt es drei Versionen (nicht zuzuordnen, nicht beurteilt, zugeordnet) und es ist nicht ganz einfach, dass alle drei gut unterscheidbar sind. Will heissen: Die Kontrastverbesserung zwischen diesen zwei wird zu einer Verminderung zwischen den anderen zwei führen
- Hat es jetzt ein paar Jahre so funktioniert und es ist auch kein Fehler. Ich werde es daher nicht prioritär behandeln

**Comment by barbalex** [comment]
Hab jetzt doch in der Entwicklungsversion die Kontraste vergrössert.

**Comment by rebeccakurz** [comment]
Danke!
