### ISSUE TITLE
Legende zu Daten aus EVAB

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#455]
Und noch etwas letztes: Hast du allenfalls eine Erklärung oder Legende zu den Abkürzungen, die in den EVAB-Daten verwendet werden?

**Comment by barbalex** [comment]
Nein. Da müsstest du Andreas Lienhard fragen. Es sind die Feldnamen, die EvAB in ihrem Zentralstellen-Export verwendet. Zu einem erheblichen Anteil sind es glaube ich Feldnamen, wie sie Info Flora vor ein paar Jahren erwartete. D.h. du könntest ev. etwas auf ihrer Seite finden. Ich habe dort rasch gesucht aber nichts gefunden.

**Comment by rebeccakurz** [comment]
Okay, danke! Die Legende von InfoFlora haben wir, aber diese scheint nicht alles zu erklären...
