### ISSUE TITLE
EKF-Protokollblätter drucken: leere Seiten

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#456]
Vielleicht ist das etwas leichter zu lösen: Wenn ich die Protokollblätter für die Freiwilligen drucken möchte, wird immer noch eine leere Seite nach den Protokollblättern eingefügt. (siehe Beispiel PDF).
[EKF_Protokollblätter.pdf](https://github.com/barbalex/apf2/files/6084786/EKF_Protokollblatter.pdf)

Könntest du dir das bei Gelegenheit mal anschauen?

**Comment by barbalex** [comment]
Sollte in Version 1.63.4 korrigiert sein

**Comment by rebeccakurz** [comment]
Danke!
