### ISSUE TITLE
EKF-Protokollblätter einzeln drucken funktioniert nicht

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#457]
Und der Befehl, mit dem man einzelne Protokollblätter drucken kann, funktioniert leider gar nicht. 
![Bildschirmfoto 2021-03-04 um 16 37 38](https://user-images.githubusercontent.com/30288503/109988651-09a5c000-7d08-11eb-9e7c-5f6482c8446b.png)

**Comment by barbalex** [comment]
Sollte in Version 1.63.4 korrigiert sein

**Comment by rebeccakurz** [comment]
Danke!
