### ISSUE TITLE
Fehlermeldung bei Erstellen neue Feldkontrolle

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#458]
Wenn man eine neue Feldkontrolle erstellt, enthält diese automatisch auch eine Zählung. Das funktioniert tiptop. Wenn ich nun aber eine zusätliche Zählung erstellen möchte, erscheint folgende Fehlermeldung und es wird keine Zählung erstellt:
![Bildschirmfoto 2021-03-16 um 12 37 12](https://user-images.githubusercontent.com/30288503/111304257-cfb4b200-8655-11eb-8ebc-e80638bb5e23.png)
Wenn ich die Datenbank aber neu lade, erscheint die zuvor erstellte Zählung dann doch im Strukturbaum, dass heisst sie wird zwar angelegt, aber nicht sofort im Strukturbaum angezeigt. 
Könntest du dir das mal noch ansehen?
Danke!

**Comment by barbalex** [comment]
Da habe ich bei der Umsetzung von https://github.com/barbalex/apf2/issues/293 zu wenig überlegt.

Ist in Version 1.63.5 korrigiert.

**Comment by rebeccakurz** [comment]
Super, danke!
