### ISSUE TITLE
PDF von Jahresbericht kann nicht geöffnet werden

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#459]
Hoi Alex 
Wenn man das PDF des Jahresberichts einer einzelnen Art öffnen möchte, kommt folgende Fehlermeldung:
![Bildschirmfoto 2021-03-17 um 07 11 18](https://user-images.githubusercontent.com/30288503/111423196-38506d00-86f0-11eb-81d9-207c10655eed.png)
Neu starten oder Cache leeren bringt leider auch nichts. Der Jahresbericht über alle Arten funktioniert aber. 

Könntest du dir das mal anschauen? Vielen Dank!

**Comment by barbalex** [comment]
Das passierte, wenn die Abfrage kein Resultat lieferte.

Ich habe den Code korrigiert: Statt dem Fehler erscheint jetzt eine Meldung.

Dass kein Resultat existiert ist möglich, wenn der AP nicht gültig ist. Ich musste die Abfrage auch noch dahingehend ändern, dass sie den Cache ignorierte. Sonst wäre nach Änderung des AP-Bearbeitungsstands immer noch kein Resultat erschienen.

Schlussendlich gibt es noch einen ganz komischen Effekt, wobei der Server bei Ausführen der Abfrage durchdreht. Will heissen: 100% CPU  belegt, und dass während längerer Zeit - meist ca. 50 Sekunden. Sehr ärgerlich. Komischerweise ist die Abfrage, welche dieselben Daten für 52 Aktionspläne abfragt, ca. 15 mal schneller und weniger CPU-intensiv als die genau gleiche, welche die Daten nur für einen einzigen Aktionsplan abfragt!?

Danke für die Meldung.

Ich lasse den Issue noch offen, weil die Abfrage durchdreht.

**Comment by rebeccakurz** [comment]
Hoi Alex
Gerade hat mir Regula Dickenmann gemeldet, dass die PDFs der Jahresberichte der einzelnen Arten nicht geöffnet werden können. Das hatten wir ja bereits im Frühling. Hat sich hier irgendetwas geändert?

**Comment by barbalex** [comment]
Da war etwas falsch benannt. 

Aber schon seit 8 Monaten. Das heisst: Es hätte schon seit 8 Monaten nicht funktionieren sollen. Offenbar hat das so lange niemand bemerkt...

Ist korrigiert und die korrigierte Version ist live.

Was mich stört: Es dauert lange, bis das Ergebnis erscheint. 

Ich werde in einer der nächsten Nächte / Wochenenden den Server neu aufbauen. Damit werden das Betriebssystem und die Datenbank aktualisiert. V.a. die Datenbank könnte zu einer Beschleunigung führen.

Aber eigentlich sollte es nicht so lange dauern.
