### ISSUE TITLE
Probleme bei Befehl "neue Population und Teil-Population gründen und Beobachtung der Teil-Population zuordnen"

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#460]
Die Artverantwortlichen haben noch gemeldet, dass wenn man bei den Beobachtungen den Befehl "neue Population und Teil-Population gründen und Beobachtung der Teil-Population zuordnen" wählt, dass der Befehl an sich klappt, aber nachher folgendes geschieht:

_-> bekannt seit wird bei TPop bei der 1. Eingabe nicht gespeichert. Mann muss die Info bekannt seit und Status immer 2x eingeben, Status auch 2-3 mal wiederholen, bis er gespeichert wird (wenn man auf neue Pop geht und wieder zurück Status oft wieder leer)_  --> ich habe das ausprobiert, bei mir hat es aber immer geklappt, daher liegt es vielleicht an der Verbindung der Artverantwortlichen? Oder kannst du dir noch etwas anderes denken?

_-> wenn man etwas in der Pop/TPop einfüllt und zurück zur Beobachtung geht, ist diese anschliessend leer, rsp. Inhalt wird nicht angezeigt _ --> als ich es das erste Mal probiert habe, hat es bei mir auch nicht geklappt. Jetzt habe ich es nochmals probiert und jetzt hat es die Beobachtung von Anfang an richtig angezeigt. Es scheint also auch hier nicht konstant zu sein. Vielleicht könntest du dir das mal anschauen?

**Comment by barbalex** [comment]
Es sind beides sehr komplizierte Vorgänge. Daher ist es nicht einfach bzw. aufwändig, ohne klare Hinweise einen Fehler zu finden.

Zweiteres habe ich auch schon gesehen. Ich weiss aber nicht, wie es provoziert werden kann. Wenn ihr herausfindet, wie diese Fehler reproduzierbar provoziert werden können, werde ich mich sofort darum kümmern.

**Comment by barbalex** [comment]
Schliesse, weil lange nicht mehr gemeldet
