### ISSUE TITLE
EKF-Formular: Datum eingeben funktioniert nur über Kalendermaske

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#462]
Hoi Alex
Bei der Eingabe der Freiwilligen-Kontrollen ist mir aufgefallen, dass das Eingeben des Datums nur über die Kalendermaske funktioniert. Wenn man das Datum von Hand eingeben will, dann wird einfach ein anderes Datum eingegeben, meist der 1. des Monats in dem man sich gerade befindet. 
Könntest du dir das mal anschauen?
Vielen Dank und liebe Grüsse

**Comment by rebeccakurz** [comment]
Hoi Alex
Ich habe schon lange nichts mehr von dir gehört und wollte mal nachfragen, ob du dir diesen Issue anschauen konntest?
LG

**Comment by barbalex** [comment]
Ja, aber wie gehen bald drei Wochen in die Ferien - muss schauen, wozu es vorher noch reicht

**Comment by barbalex** [comment]
Ich arbeite nun schon > 3 Stunden daran. Und bin immer noch daran, die Entwicklungsumgebung und alle Abhängigkeiten von apflora zu aktualisieren 🙄. 

Das ist der Grund, wieso ich so lange nicht reagiert habe: Ich wollte warten, bis mehr zu machen ist.

**Comment by barbalex** [comment]
Mittlerweile lässt sich das Projekt nicht mehr bauen 😢. Ich brauche vermutlich noch ein paar Stunden (open end) und das reicht nun definitiv nicht mehr vor den Ferien.

Normalerweise löse ich diese Dinge fortlaufend, weil ich jede Woche daran arbeite. Nun habe ich ein paar Monate nicht mehr daran gearbeitet und prompt wird das sehr aufwändig.

**Comment by barbalex** [comment]
> Wenn man das Datum von Hand eingeben will, dann wird einfach ein anderes Datum eingegeben, meist der 1. des Monats in dem man sich gerade befindet

Der Grund war derselbe wie für https://github.com/barbalex/apf2/issues/463. Ist behoben.

**Comment by rebeccakurz** [comment]
Danke, dass du es dir angeschaut hast. Es scheint jetzt wieder zu funktionieren.
