### ISSUE TITLE
EKF-Formular: Formular wird nach jeder Eingabe neu geladen

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#463]
Ausserdem wird das EKF-Formular praktisch nach jeder Eingabe in ein Feld (also sobald man in das nächste Feld klickt) neu geladen. Das ist für die Eingaben ziemlich mühsam. Könntest du dir das auch mal anschauen?
Vielen Dank!

**Comment by barbalex** [comment]
Ja, aber wie gehen bald drei Wochen in die Ferien - muss schauen, wozu es vorher noch reicht

**Comment by barbalex** [comment]
Die Probleme mit dem Bauen des Projekts konnte ich endlich lösen.

Du hast recht, das Neu-Laden ist extrem mühsam.

Der Grund ärgert mich: nach langem Suchen habe ich gemerkt, dass ein benutztes Werkzeug sein Verhalten bei einem Update undeklariert verändert hat.

Ich kann nicht ausschliessen, dass Ähnliches auch andernorts passieren kann. Wenigstens sollte ich es künftig schneller lösen können.

Das Update mit der Korrektur ist jetzt live.
