### ISSUE TITLE
Karte: aktuellstes Luftbild verfügbar?

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#465]
Wäre es möglich, dass in der Karte das neueste Luftbild verfügbar ist?
LG

**Comment by barbalex** [comment]
Welches ist denn das Neuste? Bzw. von welchem Jahr?
Meinst du CH oder ZH?

**Comment by barbalex** [comment]
Zürcher Luftbilder habe ich glaube ich kurz vor den Ferien kontrolliert und keine neueren gefunden. CH-Luftbilder haben wir bisher nie benutzt.

**Comment by barbalex** [comment]
O.k., es gibt jetzt auch Bilder von 2020.

Ist es wirklich nützlich, wenn ihr Luftbilder vieler Jahre und Bildtypen habt? Oder sollen einfach die neusten verfügbar sein?

**Comment by barbalex** [comment]
In Version 1.64.0 ist das aktuellste (2020) Luftbild in RGB ergänzt

**Comment by rebeccakurz** [comment]
Vielen Dank! Ich denke die aktuellsten Luftbilder sollten jeweils genügen.

**Comment by barbalex** [comment]
Übrigens: Die Beschriftung gibt jetzt 2020 für das aktuellste Luftbild an. Das kann aber ändern: Das GIS-Zentrum hängt jeweils das aktuellste verfügbare in diesen Dienst. Daher kann es sein, dass die Angabe "2020" künftig nicht mehr stimmt (auf Hinweise hin oder wenn ich es selber merke werde ich das nachführen). Das Luftbild sollte aber immer das aktuellste sein.
