### ISSUE TITLE
Karte: Anzahl TPops werden beim Zoomen verändert

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#466]
Seit ich auf die neueste Version aktualisiert habe, scheint etwas mit der Darstellung der TPops und Pops auf der Karte nicht zu stimmen. Zuerst werden sie normal angezeigt, aber wenn man dann in die Karte reinzoomt mittels scrollen werden die "Blüemli" plötzlich vervielfacht. Das passiert sowohl bei den Teilpopulationen als auch bei den Populationen. 

Könntest du dir das mal anschauen?

**Comment by barbalex** [comment]
Ja, das kann ich nachvollziehen

**Comment by barbalex** [comment]
Sollte in Version 1.63.14 behoben sein. 

Den betreffenden Code hatte ich seit Jahren nicht mehr angetastet. Die Ursache muss in einer undeklarierten Änderung einer verwendeten Software liegen. 

Danke für die Meldung.

**Comment by rebeccakurz** [comment]
Super, vielen Dank!
