### ISSUE TITLE
Beobachtungen an InfoFlora melden: Fehler beim Datum eintragen

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#468]
Von Regula Dickenmann gemeldet:

"Ich bin dabei,  diverse neu in der Datenbank aufgelistete Beobachtungen durchzusehen/zuzuordnen. 

Dabei stosse ich auf Fehler, die ich mit dem Anklicken auf Email an Infoflora melde. 
Ich kann aber leider das Meldedatum nicht eintragen. Vgl. screenshot.
Das ist bei verschiedenen Arten und bei Firefox und Google Chrome so."
![grafik](https://user-images.githubusercontent.com/30288503/130617303-553aa49f-9901-4f4f-8204-8235a6a82a09.png)

**Comment by barbalex** [comment]
Das sollte in Version 1.64.1 repariert sein
