### ISSUE TITLE
Karte: von iOS zugreifen funktioniert nicht

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#469]
Von Karin Sartori gemeldet:

"von unterwegs wollte ich in der APFlora DB auf die Karte zugreifen. Funktioniert nicht. Siehe Screenshot."
![IMG-20210826-WA0000](https://user-images.githubusercontent.com/30288503/130934648-ebee1f7e-e2a5-4d2b-b289-3ac98e28b70f.jpg)
Cache hat sie geleert, Neustart, neu anmelden. 

Habe es auch noch über mein Handy ausprobiert, bei mir hat es geklappt. Kann es in solchen Fällen an der Internetverbindung liegen?

**Comment by barbalex** [comment]
Habe die fullscreen-Funktionalität vor ein paar Wochen entfernt. Die Karte sollte daher auf iOS-Geräten wieder funktionieren

**Comment by rebeccakurz** [comment]
Super, wir haben es gerade ausprobiert, das scheint zu klappen :-)
