### ISSUE TITLE
Drucken

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#47]
Ist nur ein kleiner Kartenausschnitt, rsp. füllt Ausdruck nur wenig. Irgendwas ist da noch schief.
![bildschirmfoto 2017-07-14 um 17 17 18](https://user-images.githubusercontent.com/6047564/28218307-6b8d21fe-68b8-11e7-9b9f-b55c40a72d8e.png)

**Comment by barbalex** [comment]
mit den Druck-Lösungen bin ich generell nicht zufrieden :-(

**Comment by barbalex** [comment]
Ich arbeite an den Druck-Lösungen. Es kommt besser, aber es kann noch ein paar Tage dauern.

**Comment by csalzmann** [comment]
wunderbar, Danke!

---------------------------------------------------------------
Charlotte Salzmann
Dr.sc.ETH
topos Marti & Müller AG
Idastr. 24
8003 Zürich
Tel. 044 451 52 55
salzmann@toposmm.ch

Di - Fr

**Comment by barbalex** [comment]
Lösung umgesetzt. Man kann nicht mehr direkt drucken. Dafür wieder wie früher png-Dateien erstellen, welche anschliessend wie auch immer gewünscht verwendet werden können.
