### ISSUE TITLE
Fehler beim Koordinaten anpassen 

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#470]
Hoi Alex

Anna hat noch gemeldet: 
"Im Laufe der Digitalisierung musste ich einige Koordinaten in der FloraDB anpassen.
Dabei sind folgende Probleme aufgetreten:
Koordinaten wurden nicht «geschluckt» immer wieder zurück auf die alte Koordinate gefallen.
Koordinaten wurden angepasst, aber der Punkt der Tpop. auf der Karte hat sich nicht veschoben. (Beispiel im Anhang). Auch Neuladen hat nicht geholfen, aber wenigstens ist der Eintrag geblieben..."

Könntest du dir das mal anschauen?

**Comment by barbalex** [comment]
> Koordinaten wurden nicht «geschluckt» immer wieder zurück auf die alte Koordinate gefallen
Was wurde zuvor gemacht? Bzw. wie wurden die Koordinaten erfasst?
- durch Doppelklick auf der Karte
- durch Anpassen der Längen-/Breiten-Grade
- durch Anpassen der X-/Y-Koordinaten

Generell ist diese Beschreibung für mich nicht nachvollziehbar. Alles was mir bleibt, ist selber verschiedene Sachen zu probieren und dabei zu schauen, ob alles wie erwartet funktioniert. Was ich auch mache. Trotzdem wäre es hilfreich, wenn ihr das unerwartete Verhalten genau und nachvollziehbar beschreiben könntet.

**Comment by barbalex** [comment]
Ich habe einen Fehler gefunden: Wenn man mittels Doppelklick auf der Karte verortet, erscheint die Teilpopulation nicht am neuen Ort.

Der Grund war (wieder einmal), dass die für's Laden der Daten verantwortliche Software bei einem Update ihr Verhalten verändert hat 😢 

Sollte in Version 1.64.3 korrigiert sein.

Danke für die Meldung.

Falls beim Verorten noch ein anderer Fehler existiert: bitte eröffnet einen neuen Issue dafür.
