### ISSUE TITLE
Neue Art, nicht sichtbar wenn in V1 erstellt

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#48]
Da Feature noch nicht in V2 implementiert, wollte ich Umweg über V1 machen. Die neue Art ist aber nicht sichtbar in V2, es nützt auch nichts, wenn man Stammdaten aktualisiert oder sich neu anmeldet.

**Comment by barbalex** [comment]
Ja, weil das Projekt fehlt (was es in der alten Version nicht gab)

**Comment by barbalex** [comment]
o.k., wenn man jetzt in der alten Version eine Art schafft, erscheint sie auch in der neuen. Weil das Projekt immer gesetzt wird.
