### ISSUE TITLE
Berechtigung AV Zähleinheiten festlegen

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#483]
Hoi Alex

Karin Sartori hat mir soeben gemeldet, dass sie keine Berechtigung hat um EK-Zähleinheiten bei ihren Arten festzulegen. Also zum Beispiel bei den Orobanche-AP-Arten ist sie ja Artverantwortlich und hat "ap_writer"-Rechte. Damit müsste es doch eigentlich möglich sein, die EK-Zähleinheiten festzulegen?
Die EK-Zähleinheiten müssen ja z.B. definiert werden, damit man Erfolgskontrollen durch Freiwillige festhalten kann oder für die EK-Planung sind diese ja auch wichtig. 
Ich habe nun bei den Orobanche-Arten die Zähleinheiten festgelegt, aber könntest du mal schauen, wie das mit den Berechtigungen aussieht?
Falls man als "ap_writer" die Rechte nicht hat, um die Zähleinheiten festzulegen, könnte das dann geändert werden?

Vielen Dank und liebe Grüsse
Rebecca

**Comment by barbalex** [comment]
Die Zähleinheiten können aktuell nur von managern verändert werden: https://github.com/barbalex/apf2/blob/ecc194d459ba774b6a5a6ec014c3232ee1c90f7f/sql/apflora/createTables.sql#L2713

Wollte man den jeweiligen AP-Verantwortlichen die Rechte geben, müsste das so angepasst werden, wie es heute z.B. für die EK-Pläne geregelt ist: https://github.com/barbalex/apf2/blob/ecc194d459ba774b6a5a6ec014c3232ee1c90f7f/sql/apflora/createTables.sql#L2807-L2825

Die Änderung ist relativ schnell gemacht. Kann ich also machen, wenn ihr wollt.

Es ist eure Sache zu bestimmen, wer was machen können soll. Wer immer es macht, sollte einfach wissen, was alles durch solche Änderungen beeinflusst wird, damit man danach nicht überrascht ist. 

Und das ist einfacher gesagt als gewusst. Ich bin selber nicht mehr sicher, was alles dadurch beeinflusst wird. Z.B.: Was wo erfasst werden kann, wie Summen berechnet werden, Auflistung in Qualitätskontrollen...

Darum sollten Änderungen sorgfältig durchgeführt werden.

Immerhin dürfte es etwas weniger heikel sein, als die EK-Frequenzen. Welche auch nur von managern verändert werden können.

**Comment by rebeccakurz** [comment]
Vielen Dank für deine Rückmeldung!
Dann werde ich mit Karin besprechen, welches das bessere Vorgehen ist und werde mich wieder melden.

**Comment by rebeccakurz** [comment]
Hoi Alex
Karin und ich haben das noch besprochen und sind auch der Meinung, dass es besser ist, wenn die EK-Zähleinheiten weiterhin nur durch Manager verändert werden können. 
Wir werden also, wenn die neuen Aktionspläne (hier müssen die AV ja die Ziele definieren) fertig sind, die Ziele in der FloraDB ergänzen.
