### ISSUE TITLE
EK-Frequenzen im Strukturbaum ergänzen

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#484]
Noch eine Frage zu den EK-Frequenzen, welche im Strukturbaum ja bei jeder Art aufgeführt sind.
![Bildschirmfoto 2021-11-10 um 11 12 12](https://user-images.githubusercontent.com/30288503/141094209-cc9443f1-b8f9-43c5-8188-707852cfabde.png)
Diese sind ja für alle Arten die gleichen, also hier im Strukturbaum ist ja eigentlich nur die Definition, was welche EK-Frequenz bedeutet, ist das richtig?
Bei den neuen AP-Arten sind diese ja jetzt noch nicht drin. Könnten die von dir ergänzt werden? Oder hätte das auch Auswirkungen auf verschiedene Sachen?

Dieselbe Frage habe ich mir bei den AP-Erfolgskriterien gestellt. Aber diese sind glaube ich pro Art verschieden, dann müssten sie wohl manuell durch uns hinzugefügt werden.
![Bildschirmfoto 2021-11-10 um 11 15 36](https://user-images.githubusercontent.com/30288503/141094888-4e37e98c-cc42-4f73-9d1b-415edfc13c33.png)

**Comment by barbalex** [comment]
> Diese sind ja für alle Arten die gleichen, also hier im Strukturbaum ist ja eigentlich nur die Definition, was welche EK-Frequenz bedeutet, ist das richtig?

Richtig

> Bei den neuen AP-Arten sind diese ja jetzt noch nicht drin. Könnten die von dir ergänzt werden? 

Klar. Bloss: Das wäre wohl auch für mich ein paar Stunden Arbeit. Vermutlich ca. 4 bis 5. Und ihr müsstet auflisten, welche Arten genau ergänzt werden müssen und welche Art als Vorlage dienen soll (falls es doch Unterschiede geben sollte...).

Diese Arbeit müsste ich der FNS verrechnen. Denn sie ist nicht budgetiert. Die Finanzierung lässt sich vermutlich regeln. Eher fragt es sich, ob es sich wirklich lohnt, wenn ich es mache. Kommt wohl drauf an, wieviele Arten es wirklich sind und wie viel Aufwand ihr hättet, um die Daten von Hand zu erfassen. Und wieviele Fehler passieren, wenn man es von Hand macht.

Zur Änderung von EK-Frequenzen sind momentan nur manager berechtigt. AP-Verantwortliche können das nicht. Das liesse sich relativ schnell ändern. Aber Änderungen an EK-Frequenzen sollten wohl nur durch euch erfolgen, weil das ja auch Auswirkungen auf die Finanzierung der AV's hat. Und Nebenwirkungen haben kann, die ohne ein gutes Verständnis, wie sie wirken, vom AV allenfalls nicht bemerkt werden.

Was meinst du, wer es machen sollte?

> Oder hätte das auch Auswirkungen auf verschiedene Sachen?

Ja klar. Und ein Teil davon ist programmiert, d.h. der Code reagiert auf bestimmte EK-Frequenzen. Was heisst, dass gewisse Änderungen bei gewissen EK-Frequenzen Folgen hätten, die nur ich korrigieren kann. Aber wenn die EK-Frequenzen bei allen Arten bisher gleich sind und die neuen Arten dieselben EK-Frequenzen erhalten, ist das kein Problem.

> Dieselbe Frage habe ich mir bei den AP-Erfolgskriterien gestellt. Aber diese sind glaube ich pro Art verschieden, dann müssten sie wohl manuell durch uns hinzugefügt werden.

So sehe ich das auch. Gleich wie die AP-Ziele.

**Comment by rebeccakurz** [comment]
Danke für die Rückmeldung, ich werde auch das noch mit Karin besprechen. 
Liebe Grüsse
Rebecca

**Comment by rebeccakurz** [comment]
Hoi Alex
Karin und ich haben auch das besprochen und uns gefragt, ob die EK-Frequenzen bei allen Arten einzeln aufgeführt sein müssen oder ob es denn nicht reichen würde, wenn sie zb. ganz unten im Strukturbaum ergänzt werden würden und dann von dort aus "verknüpft" werden können (zb. für die EK-Planung)?

Denn es wäre wirklich ein ganzes Stück Arbeit, diese 18 EK-Frequenzen bei allen neuen Arten hinzufügen zu müssen...

**Comment by barbalex** [comment]
Das habe ich bei der Erst-Implementation explizit gefragt.

Die Variante, bei der es nur eine einzige Liste von EK-Frequenzen gibt, hiesse dann aber explizit auch: Sie gilt für ALLE Arten und es wird nie eine Ausnahme geben.

Darum habt ihr euch glaube ich damals dafür entschieden, dass es pro Art sein soll.

Das System ändern wäre jetzt wiederum sehr viel Programmier-Arbeit.

Was man machen könnte: Eine Funktion, um die EK-Frequenzen einer anderen Art zu kopieren. Der Befehl wäre wohl im Kontextmenu. Er würde nur erscheinen, wenn bei einer Art noch keine EK-Frequenz erfasst worden wäre.

Also:
- Im Kontextmenu der EK-Frequenzen "aus anderer Art kopieren" wählen
- Im aufpoppenden Fenster eine Art wählen
- Die von apflora kopierten EK-Frequenzen inkl. Kontrolljahre sehen

Die Implementation wäre ein bisschen aufwändiger, als wenn ihr von mir die EK-Frequenzen kopieren lässt. Also 7 statt ca. 4 bis 5 Stunden. Dafür habt ihr dieses Problem nie mehr.

Ich kann das in die Offerte für den Import von Blaualgen integrieren. Womit es auch finanziert wäre.

**Comment by rebeccakurz** [comment]
Hoi Alex

Das ist natürlich aus der jetzigen Sicht ziemlich ärgerlich! Aber wahrscheinlich war es genau so, wie du gesagt hast, und wir wollten für jede Eventualität gewappnet sein...

Karin und ich haben das noch besprochen und gerne würden wir deinen Vorschlag mit der Funktion, dass man die EK-Frequenzen einer anderen Art kopieren kann, annehmen. 
Gerne kannst du das in deine Offerte mit reinnehmen. Das sollte sich als Erstimplementierung für die neuen Arten gut begründen lassen. 

Das führt mich zu einer weiteren Frage: Wäre eine solche Funktion auch bei den AP-Erfolgskriterien möglich? Also dass es auch hier möglich wäre, die AP-Erfolgskriterien einer anderen Art zu kopieren? Denn es sollte eigentlich nur zwei Varianten dieser Kriterien geben, je nachdem ob drei oder vier Ziele für die Art definiert wurden. Dann würde es hier nachher auch schneller gehen, diese bei den neuen Arten einzufügen. 
Vielleicht geht das ja "gad im Gliche"?

**Comment by barbalex** [comment]
> Gerne kannst du das in deine Offerte mit reinnehmen

Mache ich. Vermutlich noch diese Woche.

> Wäre eine solche Funktion auch bei den AP-Erfolgskriterien möglich? 

Ja, aber kostet mich auch etwas 2 Stunden Implementation.

**Comment by barbalex** [comment]
Offerte ist verschickt

**Comment by rebeccakurz** [comment]
Super, danke!
