### ISSUE TITLE
Frage Beobachtungen zuordnen

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#486]
Hoi Alex
Regula Dickenmann hat mir gemeldet:
"Wenn man eine neue TPop gründen will, werden die Koordinaten von der Beobachtung nicht in die TPop übertragen. Auch von Hand kann man sie nicht eingeben, sie verschwinden wieder."

Ich habe es bei Abies alba ausprobiert und zuerst hat es bei mir ebenfalls nicht geklappt. Nach ein, zwei Versuchen ging es dann wieder...
Könntest du vielleicht trotzdem mal sehen, ob du irgendetwas herausfindest? Allgemein scheint die FloraDB momentan etwas Mühe zu haben, häufig verschwinden Eingaben wieder, die man erst gerade eingegeben hatte... Vielleicht weil momentan relativ viel mit der Datenbank gearbeitet wird?

**Comment by barbalex** [comment]
Ich habe den Eindruck, dass die CPU des Servers überraschend hoch ausgelastet wird. Und zwar durch die Datenbank.
Soweit ich das beurteilen kann, ist das seit letztem Dienstag (9.11.) recht oft der Fall.

Mir ist schon aufgefallen, dass Jahresberichte für eine einzelne Art anzeigen, auf dem Server um Grössenordnungen länger dauert, als bei mir lokal (wo es sofort passiert).

Ich werde daher versuchen, eine zusätzliche CPU dazu zu schalten.
Dafür muss ich kurzzeitig den Server ausschalten. Daher kann ich das euch zuliebe nicht jetzt machen. Werde es heute nach 20 Uhr machen.

Was ich auch machen kann: einen völlig neuen Server aufbauen. Der dann die neuste Version der Datenbank verwendet. Welche leistungsfähiger sein sollte. Mal schauen, ob das heute auch reicht.

**Comment by rebeccakurz** [comment]
Okay, vielen Dank!
Ja jetzt gegen Ende Jahr wird die FloraDatenbank auch viel öfter benutzt, weil alle noch ihre Daten eintragen müssen und ihre Berichte verfassen. 
Sicher gut, wenn die FloraDB dafür gewappnet ist.

**Comment by barbalex** [comment]
Ich probier's und hoffe, es nützt 🙏

**Comment by barbalex** [comment]
apflora wurde nun migriert auf einen neuen Server, mit:

- zwei CPU statt einer, und erst noch modernere
- einer leistungsstärkeren SSD (die DB kann schneller lesen und schreiben)
- dem aktuellen Betriebssystem 
- vor allem der aktuellen Version der Datenbank

Und siehe da: das pdf für eine Art wird nun wieder schön schnell erzeugt 😄 

Uff, das war mehrere Stunden Arbeit.
Sogar das für alle Arten wird innert Sekunden erzeugt 💪 

Ich gehe also davon aus, dass auch das mit den Beobachtungen wieder zuverlässig klappt 🙏
