### ISSUE TITLE
fehlende Daten wegen Migration??

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#487]
Hoi Alex
Vielen Dank für deine viele Arbeit mit der Migration der apflora auf den neuen Server. 
Ich wollte nun testen, ob das mit den Beobachtungen einer Teilpopulation zuordnen und das Setzen der Koordinaten nun einwandfrei klappt. 
Dabei ist mir aufgefallen, dass die Population von Abies alba, die ich für das Testen benutzt habe, nicht mehr da ist! Das war Population 900: Test Beobachtungen. Diese haben Seraina gestern erstellt und ich habe dann im Laufe des Tages mehrere Teilpopulationen hinzugefügt, um den Befehl zu testen. 
Dann habe ich gestern noch eine neue Art der FloraDB hinzugefügt, weil Charlotte bei dieser eine Massnahme gemacht hat und sie sie gerne in die FloraDB eintragen wollte. Es handelt sich um Ranunculus lingua. Charlotte hat dann auch noch eine neue Teilpopulation gegründet und ihre Massnahme eingetragen. Diese Art ist nun aber nicht mehr in der FloraDB!

Kannst du mal schauen, ob vielleicht bei der Migration auf den neuen Server die ganz aktuellsten Änderungen irgendwie nicht mitgekommen sind?
Am Dienstag habe ich noch bei Ophrys araneola Feldkontrollen eingetragen und Berichte erstellt, diese scheinen noch da zu sein...
Vielen Dank fürs Nachprüfen!

**Comment by barbalex** [comment]
Wie es scheint, habe ich am Ende die falsche Version für die Wiederherstellung auf dem neuen Server benutzt. Das heisst: diejenige vom Vorabend, 24.00. Was heisst: Alle Änderungen, die gestern stattfanden, sind nicht drin.

Das konnte wohl passieren, weil die Wiederherstellung etwa 7 mal misslang, bis ich sie mit völlig neuen Methoden machen musste. Wobei dann wohl dieser Fehler passierte.

Es gibt nun drei Varianten, das zu korrigieren:
- Ich ersetze die Daten auf den neuen Server mit den richtigen von gestern Abend, 22 Uhr. Dabei geht alles verloren, was heute erfasst wurde
- Ihr sagt mir, was angepasst wurde. Und ich versuche, das aus der Sicherung von gestern Abend, 22 Uhr mit Abfragen einzufügen. Wenn es viel ist und v.a. falls ein Teil davon heute korrigiert wurde, wird das schwierig / aufwändig. Oder ich mache das manuell
- Die Benutzer:innen ergänzen selber nochmals, was sie gestern gemacht haben
- Eine Kombination aus letzteren zwei

Ich kann dir nicht sagen, wie leid mir das tut.

**Comment by barbalex** [comment]
Ich teste jetzt mit Abfragen, was alles gestern geändert wurde

**Comment by rebeccakurz** [comment]
Hmm ja, das ist natürlich blöd, aber Fehler passieren...
Sagst du mir, falls ich etwas tun kann?
Es ist wahrscheinlich noch schwierig nachzuvollziehen, was alles gestern gemacht wurde. Da ist es mit Abfragen wahrscheinlich am besten...

**Comment by barbalex** [comment]
O.k., ist nun alles korrigiert. Hier die Zusammenfassung:

# Problem

Bei Wiederherstellung auf neuem Server offenbar die Version der Vornacht erwischt. Anpassungen mit Datum 2021-11-17 daher nicht enthalten.

# Analyse

ap: one change
ap_file, idealbiotop_file, pop_file: has no changed field > mittelfristig zu verbessern
ap_user has no changed field > mittelfristig zu verbessern
ap_art: changed field is not populated > mittelfristig zu verbessern
apber: no changes
apberuebersicht: no changes
assozart: no changes
ekfrequenz: no changes
ekplan: no changes
ekzaehleinheit: no changes
erfkrit: no changes
idealbiotop: no changes
pop: 9 changes
popber: no changes
tpop: 26 changes
tpopber: 14 changes
tpopkontr: no changes
tpopkontrzaehl: no changes
tpopmassn: 16 changes
tpopmassnber: 14 changes
ziel: no changes

# Behebung

Alle Änderung mit Datum vom 17.11.2021 aus der Sicherung exportiert und in die Datenbank des neuen Servers importiert

# Mögliche verbleibende Probleme

Alle Dateien werden bisher ohne Änderungsdatum gespeichert. Daher war es nicht möglich, zu eruieren, ob Dateien verändert wurden. Es ist daher möglich, dass gestern jemand eine Datei (z.B. ein Bild) einem AP, Pop oder Idealbiotop angefügt hat und diese Datei bzw. der Bezug dazu nun verloren ging.

**Comment by barbalex** [comment]
Wenn ihr wissen wollt, welche Datensätze importiert wurden, kann ich sie euch schicken

**Comment by rebeccakurz** [comment]
Okay, danke. 
Ich habe gerade nochmals nachgeschaut. Die Art Ranunculus lingua ist nun wieder drin und auch die Population 900 bei Abies alba. Allerdings sind die Beobachtungen, die ich gestern den Teilpopulationen von Pop 900 zugeordnet hatte, wieder zurück zu "Beobachtungen nicht beurteilt" gerutscht. Sie sind also nicht mehr den Teilpopulationen zugeordnet... Kann das sein, dass die Zuordnung verloren ging?1

**Comment by barbalex** [comment]
Ich habe vergessen, dass es in der Tabelle beob auch Felder gibt, die ihr nachführt 🙄 

Blöder ist: Wie es scheint, wird das Feld "changed" in der Tabelle beob nur bei Importen bzw. bei der erstellung neuer Datensätze nachgeführt. Nicht wenn ihr etwas ändert, d.h. zuordnet.

Ich werde das korrigieren. Aber ich kann darum nicht ermitteln, ob gestern Datensätze geändert wurden 😢

**Comment by rebeccakurz** [comment]
Könnte man allenfalls einen Vergleich machen zwischen dem Backup von gestern Abend und dem Stand von heute? Dann würde man ja sehen, welche Beobachtungen gestern zugeordnet waren und welche heute wieder "nicht beurteilt" sind. 
Bin mir ziemlich sicher, dass gestern Zuordnungen gemacht wurden, da mir Regula Dickenmann ja die Fehlermeldung dazu geschickt hatte...

**Comment by barbalex** [comment]
Diese Tabelle hat ca. 500'000 Datensätze und wiegt 1.3 Gigabyte wenn man sie herunterlädt. Da etwas vernünftig zu vergleichen wird schwierig. Ich arbeite daran.

**Comment by barbalex** [comment]
O.k., habe nun die 28 veränderten Beobachtungen auch noch ergänzt. Danke für den Hinweis!!!

**Comment by barbalex** [comment]
Bei zwei veränderten Beobachtungen gab es übrigens die zugehörige TPop nicht mehr - da scheint schon jemand korrigiert zu haben?

**Comment by rebeccakurz** [comment]
Super konntest du das noch heraustüfteln!
Um welche Arten handelt es sich denn?

**Comment by barbalex** [comment]
Es waren alles Carex hartmanii Cajander (Hartmans Segge)

**Comment by rebeccakurz** [comment]
Okay, ja das könnte in dem Fall gut sein, dass Regula Dickenmann heute bereits wieder daran gearbeitet hat. 
Allenfalls würde es Sinn machen, wenn wir sie noch informieren würden, dass sie die geänderten Daten nochmals anschauen sollte...
@kmarti : Was meinst du, soll ich Regula noch informieren?

**Comment by barbalex** [comment]
Es scheint immer Regula zu treffen 😢

**Comment by rebeccakurz** [comment]
Also ich habe Regula jetzt heute noch informiert, dass es ein Problem gegeben hat und sie doch bitte die Beobachtungen bei Carex hartmanii nochmals anschauen soll.

**Comment by rebeccakurz** [comment]
Dann hat Anna noch bemerkt, dass bei Potentilla inclinata, welche sie auch letzten Mittwoch bearbeitet hatte, nicht mehr drin war, wenn sie eine Teilpopulation auf erloschen gesetzt hatte. 
Und sie hatte einige Fälle, wo sowohl eine Feldkontrolle als auch eine Freiwilligen-Kontrolle durchgeführt wurde und da muss man ja sagen, welche der Kontrollen man nicht im Jahresbericht berücksichtigen möchte und das war auch nicht mehr festgehalten...
Sie hat es jetzt aber bei Potentilla inclinata nochmals nachgeführt, da es nicht so viel war...

**Comment by barbalex** [comment]
Seit diesem Vorfall habe ich ja die Art und Weise, wie Änderungen dokumentiert werden, überprüft und verbessert. Dabei ist aufgefallen, dass zuvor nur neue Datensätze dokumentiert wurden. Nicht Änderungen an bestehenden.

Was du beschreibst bestägt: Ich habe (ausser bei den Beobachtungen) nur korrigiert, was an jenem Tag neu erfasst wurde. Änderungen an bestehenden Datensätzen wurden nicht wiederhergestellt.

Das nachträglich durchzuführen, ähnlich wie bei den Beobachtungen, ist prinzipiell möglich. Aber sehr aufwändig, v.a. in den Tabellen mit sehr vielen Feldern. Aber auch, weil ca.50 Tabellen betroffen sein können.

Wenn es bestimmte Tabellen gibt, bei denen ihr Änderungen, z.B. auch von bestimmten Feldern prüfen lassen möchtet: Sag mir das bitte.

**Comment by rebeccakurz** [comment]
Okay, wir haben jetzt noch die Artverantwortlichen informiert und ihnen gesagt, dass sie sich melden sollen, falls Änderungen von ihnen nicht mehr da sind. Vielleicht ergibt sich aus ihren Rückmeldungen, ob es sinnvoll ist, noch einige Tabellen zu überprüfen...
