### ISSUE TITLE
neue TPop erfassen: "bekannt seit" fällt wieder raus

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#488]
Hoi Alex
Wir haben festgestellt, dass beim Erstellen von neuen Teilpopulationen in letzter Zeit häufig das "bekannt seit" rausfällt, nachdem es eingegeben wurde. Meist kann man noch den Status der Teilpopulation eingeben, danach fällt das "bekannt seit" wieder raus (den Status der TPop kann man ja nur eingeben, wenn ein bekannt seit angegeben ist; siehe Screenshot).
![Bildschirmfoto 2021-11-22 um 15 28 11](https://user-images.githubusercontent.com/30288503/142880894-e473fd29-5bad-4696-b866-4124e3d822b9.png)
 
So geschehen gerade bei Anna bei Potentilla inclinata 151.4.
Bei der TPop 151.3 hat es aber auf Anhieb geklappt. 
Bei TPop 151.1 ist es dafür erneut rausgefallen...

Bei mir ist es auch schon geschehen, habe mir aber leider nicht notiert bei welchem Beispiel... es war aber sicher vor der Migration auf den neuen Server und bei Anna ist es jetzt heute wieder passiert (und davor auch schon).

Könntest du dir das mal anschauen?

**Comment by barbalex** [comment]
Jetzt kann ich das nachvollziehen.

Es lässt sich folgendermassen provozieren:
1. fokussiere ein Textfeld
2. ändere dessen Wert
3. ohne zuvor etwas anderes zu machen: klicke mit der Maus direkt auf eine Option eines Felds, dass Optionen zur Wahl bietet
4. siehe wie nur einer von beiden Werten gesetzt wird

Das Problem ist:

Die Speicherung wird in einem Textfeld ausgelöst, sobald der Fokus daraus verschwindet. 
In einem Optionen-Feld wird die Speicherung ausgelöst, sobald auf eine Option geklickt wird. 
Klickt man aber nach einer Änderung in einem Textfeld direkt auf eine Option eines Optionen-Feldes, **lösen beide Felder ihren jeweiligen Speichervorgang zum genau gleichen Zeitpunkt aus**.

Das ist erst die Analyse. Eine Lösung muss ich noch finden.

**Comment by barbalex** [comment]
Ich habe eine Lösung gefunden. Arbeite daran. Das dauert ein bisschen, weil ich in allen Formularen die Speicherung umbauen muss. Werde vermutlich nach und nach die Zwischenschritte live stellen.

**Comment by barbalex** [comment]
Die folgenden Formulare speichern ab Version 1.66.1 anders und daher sollte dies dort nicht mehr passieren:
- Teil-Population
- Teil-Populations-Berichte

Ich lass das jetzt ein paar Tage so. Damit wir herausfinden:
- ob das Problem in diesen Formularen wirklich nicht mehr auftritt
- ob in diesen Formularen andere Probleme auftreten

Falls wir nach ein paar Tagen zufrieden sind, werde ich nach und nach die übrigen Formulare anpassen. Zuerst natürlich diejenigen mit Status bzw. Optionen.

**Comment by rebeccakurz** [comment]
Okay, vielen Dank!

**Comment by barbalex** [comment]
Ich bin jetzt daran, die ca. 50 Formulare anzupassen. Wird wohl eine Weile dauern, bis alle angepasst sind

**Comment by barbalex** [comment]
In Version 1.66.10 sind alle 50 Formulare angepasst und das sollte nicht mehr passieren.

**Comment by rebeccakurz** [comment]
Super, danke!
