### ISSUE TITLE
Jahresbericht PDF - Grafiken gehen nur bis zum Jahr 2020

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#489]
Hoi Alex
Das PDF des Jahresbericht lässt sich nun ja wieder erzeugen (obwohl es relativ lange braucht), aber leider umfassen die angezeigten Grafiken nur das Jahr 2020. 2021 fehlt in den Grafiken. 

Könntest du dir das noch ansehen? Danke!
![Bildschirmfoto 2021-12-06 um 08 11 46](https://user-images.githubusercontent.com/30288503/144803448-8f2a1abf-c3df-4443-b244-7aaafb46c11f.png)

**Comment by barbalex** [comment]
Ihr müsst zuerst einen Bericht für 2021 erfassen: https://apflora.ch/Daten/Projekte/e57f56f4-4376-11e8-ab21-4314b6749d13/AP-Berichte

**Comment by rebeccakurz** [comment]
Ah und erst wenn die Daten historisiert sind, werden die Grafiken erstellt?
Das Historisieren der Daten macht aber erst Sinn, wenn alle Angaben eingegeben sind oder? Oder können die Daten mehrmals historisiert werden?
Die Ergebnisse der Erfolgskontrollen müssen bis 15. Dezember eingetragen werden, die Massnahmen bis am 5. Januar...

**Comment by rebeccakurz** [comment]
Okay, vielen Dank!
