### ISSUE TITLE
Jahresbericht: PDF lässt sich nicht drucken

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#490]
Und noch eine Meldung zum Jahresbericht: Das erstellte PDF lässt sich nicht drucken, respektive es wird nicht richtig dargestellt. Ich nehme an es hängt damit zusammen, dass der Bericht zu langsam geladen wird...
[JB_Oara_20211206.pdf](https://github.com/barbalex/apf2/files/7658720/JB_Oara_20211206.pdf)

Könntest du dir das auch noch anschauen? Vielen Dank!

**Comment by barbalex** [comment]
Gemäss meinem ersten Eindruck passiert das komischerweise nur, wenn man den Jahresbericht für einen einzelnen AP druckt. Der Jahresbericht für alle AP's klappt bei mir gut. Kannst du das bestätigen?

**Comment by rebeccakurz** [comment]
Ja, das kann ich bestätigen!

**Comment by barbalex** [comment]
O.k., das war schlecht programmiert 😢 
Wird in ein paar Minuten mit Version 1.66.3 korrigiert sein.

**Comment by rebeccakurz** [comment]
Klappt wieder, vielen Dank!
