### ISSUE TITLE
AP Flora DB abgestürzt!!

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#491]
Hoi Alex
Die FloraDB scheint gerade abgestürzt zu sein!! Auf Google Chrome und Firefox!
Kannst du mal schauen?

**Comment by barbalex** [comment]
Richtig. Seit ein paar Minuten arbeite ich daran. 

Momentan kann ich nur raten. Und zwar, dass das Problem beim Hosting-Provider liegt. Die Daten-API ist nicht erreichbar und ich kann nicht in den Server einloggen. Ohne das kann ich absolut nichts machen 😢. Habe beim Hosting-Provider ein Ticket geöffnet und hoffe, sie reagieren rasch.

**Comment by barbalex** [comment]
Da ich den Server gar nicht erreichen kann, kann ich auch nicht die aktuellen Daten absaugen, um einen neuen zu bauen und live zu schalten. Das könnte ich nur mit den Daten von gestern Nacht. Macht also keinen Sinn. Ich warte also auf die Reaktion des Server-Hostings.

**Comment by barbalex** [comment]
Habe jetzt gemerkt, dass beim Hosting zwar sonst nichts mehr funktioniert. Aber man konnte den Server ab- und wieder neu anschalten. Worauf er wieder funktioniert. Mache jetzt rasch eine Sicherheitskopie der Daten aber ihr könnt wieder arbeiten.

**Comment by rebeccakurz** [comment]
Okay, super, danke!

**Comment by barbalex** [comment]
Gemäss Mitteilung des Hosting-Providers gab es eine Überlastung des Servers. Die Überlastung war nicht von apflora verursacht. Ich kann also keinen Einfluss nehmen. Ausser, wenn es wieder passieren sollte: den Hosting-Provider ändern. Oder ein viel teureres (und weniger anpassungsfühiges) Hosting benutzten, in dem ein physischer Server nur von apflora verwendet wird und nicht mit anderen geteilt wird.

Denn der Kern eines virtuellen Servers ist eben, dass die dahinter stehenden physischen Ressourcen geteilt werden. Das ermöglicht, einer App dynamisch die von ihr benötigten Ressourcen zuzuteilen. Womit diese bei Bedarf einfach erhöht werden können (wie kürzlich gemacht). Und es heisst auch: Weil eine Anwendung meistens viel weniger Ressourcen benötigt als in Spitzen-Beanspruchungs-Zeiten, ist ein solches Hosting viel günstiger. Denn die in den übrigen Zeiten nicht beanspruchten Ressourcen stehen dann anderen Apps zur Verfügung.

Das heisst aber auch, dass es prinzipiell möglich ist, dass eine fremde App plötzlich physische Ressourcen überbeanspruchen kann und damit auch unsere apflora beeinflussen kann.

Es ist die Kernkompetenz der Hosting-Provider, dies so zu managen, dass letzteres sozusagen nie passiert und wir nur die Vorteile spüren.

In diesem Fall ist es offensichtlich passiert.
