### ISSUE TITLE
Beobachtungen in neuem Fenster öffnen -> Inhalt leer

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#492]
Von den AV gemeldet: 
"Wenn man in der Karte eine Beobachtung anklickt und in einem neuen Fenster oder Strukturbaum 2 anzeigen lassen möchte, ist der Inhalt leer. Bei beiden Verfahren."

![image002](https://user-images.githubusercontent.com/30288503/145351669-2a7d6193-2549-40a3-99ae-c1678e0caa68.png)

Ich habe es auch noch ausprobiert. Manchmal funktioniert es, manchmal nicht. Ich sehe aber keinen Unterschied, wann es funktioniert und wann nicht. Charlotte hat geschrieben, bei ihr habe es etwa 15x nicht geklappt, dann 1x geklappt und dann wieder nicht. 

Kannst du da etwas machen?

**Comment by rebeccakurz** [comment]
Für mich ist wirklich nicht ersichtlich, an was es liegen könnte... Man kann dieselbe Beobachtung 5 mal hintereinander in einem neuen Fenster anzeigen lassen, davon kann es dann 4 mal nicht funktionieren, beim 5. Mal aber schon. Und ich habe nichts anders gemacht. Es scheint auch kein Unterschied zu sein, ob die Beobachtung aus InfoFlora oder aus dem EVAB kommen (wäre ja auch zu schön gewesen, wenn es so einfach gewesen wäre). Manchmal werden die Informationen im neuen Fenster wie noch eine Sekunde angezeigt und dann fallen sie raus. 
Bei einigen Beobachtungen scheint es gar nie zu funktionieren. Ich habe die Beobachtung (von Abies alba) im Screenshot jetzt gefühlt 50mal in einem neuen Fenster anzeigen lassen, aber die Informationen wurden nicht korrekt dargestellt, auch nach neu laden und abmelden und Cache leeren nicht. Ich sehe aber auch hier kein Indiz, warum gerade diese Beobachtung nicht funktioniert...
![Bildschirmfoto 2021-12-09 um 09 57 43](https://user-images.githubusercontent.com/30288503/145366213-613e842e-ba3f-4177-8f42-2aefd5d1922a.png)

**Comment by barbalex** [comment]
Das scheint ein generelles Problem dieses (Unter-)Formulars zu sein. Derselbe Effekt tritt auf, wenn man eine Beobachtung direkt öffnet und dann F5 drückt bzw. den Browser-Inhalt neu lädt

**Comment by barbalex** [comment]
Das war ein nicht sehr offensichtlicher Effekt des Werkzeugs, dass für die lokale Zwischenspeicherung der vom Server abgefragten Daten verwendet wird.

Der Vorgang geht so:
1. Das Werkzeug holt die Daten vom Server
2. Es speichert sie intern
3. Nun werden sie für die App verfügbar und - wenn vorhanden - angezeigt

Dieses Werkzeug hat die Ergebnisse zweier unterschiedlicher Abfragen am selben Ort zwischengespeichert.

Die zuletzt abgefragte Version war daher verfügbar. Die andere nicht.

Je nachdem in welcher Reihenfolge diese Abfagen ausgeführt wurden, waren die Daten also verfügbar oder nicht.

Ich habe nun dem Werkzeug beigebracht, die Ergebnisse der zwei Abfragen unterschiedlich zu speichern, damit beide Varianten auch immer verfügbar werden.

Sollte also ab Version 1.66.5 funktionieren.

**Comment by rebeccakurz** [comment]
Vielen Dank!
Die ersten Tests sehen vielversprechend aus.

**Comment by barbalex** [comment]
lol

gut formuliert, du bist schon ein richtiger IT-Profi
