### ISSUE TITLE
Teil der neuen AP-Arten: QK sind nicht automatisch ausgewählt

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#494]
Hoi Alex

Bei einigen der neuen Aktionsplan-Arten sind die Qualitätskontrollen nicht automatisch ausgewählt. Somit wird natürlich auch keine QK ausgeführt, wenn man darauf klickt und es meldet keine Fehler. 

![Bildschirmfoto 2021-12-13 um 08 14 43](https://user-images.githubusercontent.com/30288503/145768708-bc22d18c-7a83-45c2-86d4-2f7e64f4d1a2.png)

Dies ist bei folgenden Arten der Fall: 

- Chara filiformis
- Chara intermedia
- Hottonia palustris
- Lycopodiella inundata
- Nitella confervacea
- Nitella gracilis 
- Orobanche alsatica
- Pyrola chlorantha
- Utricularia bremii
- Utricularia minor
- Utricularia stygia
- Utrucularia vulgaris

Komischerweise sind das ja nicht alle neuen Arten, bei den anderen ist die QK aber "eingeschaltet".

Könntest du also bei diesen Arten die QK "einschalten" und vielleicht kannst du auch eruieren, warum es bei diesen Arten nicht von Anfang an geklappt hat?

Danke!

**Comment by barbalex** [comment]
Vermutlich hat es ab einem unbekannten Zeitpunkt nicht geklappt. Grund: Der benötigte Trigger war nicht aktiv. Wieso ist mir nicht klar. Habe ihn jedenfalls wieder aktiviert.

Das heisst: Ab sofort werden die QK wieder eingeschaltet, wenn ein neuer AP gegründet wird. Das wirkt aber nicht rückwirkend.

Mehr folgt später.

**Comment by barbalex** [comment]
Die Liste von Arten ohne eingeschalteten QK ist gemäss Abfrage etwas grösser:

- Ranunculus lingua L.
- Chara filiformis H. Hertzsch
- Chara intermedia A. Braun
- Dianthus carthusianorum L. subsp. vaginatus (Chaix) Schinz & R. Keller (Scheidige Kartäuser-Nelke)
- Hottonia palustris L. (Wasserfeder)
- Kickxia spuria (L.) Dumort. (Eiblättriges Schlangenmaul)
- Lycopodiella inundata (L.) Holub (Moorbärlapp)
- Nitella confervacea (Bréb.) Leonh.
- Nitella gracilis (Sm.) C. Agardh
- Orobanche alsatica Kirschl. s.str. (Elsässische Sommerwurz)
- Pyrola chlorantha Sw. (Grünliches Wintergrün)
- Utricularia bremii Heer (Bremis Wasserschlauch)
- Utricularia minor L. (Kleiner Wasserschlauch)
- Utricularia stygia G. Thor
- Utricularia vulgaris L. (Gewöhnlicher Wasserschlauch)

Werde allen per Abfrage die QK einschalten.

**Comment by barbalex** [comment]
Gemacht.

**Comment by rebeccakurz** [comment]
Super, vielen Dank!
Komisch, dass der Trigger nicht mehr aktiv war...
