### ISSUE TITLE
Qualitätskontrolle: nicht verständlich

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#495]
Hoi Alex

Gestern Abend hatte ich bei Ophrys araneola TPop 152.2 folgende zwei Fehlermeldungen (siehe Screenshot):
![Bildschirmfoto 2021-12-13 um 17 55 07](https://user-images.githubusercontent.com/30288503/145976426-df835f2e-7f27-48d7-9511-cefd240fddf9.png)
Bei der Massnahme eingegeben hatte ich das:
![Bildschirmfoto 2021-12-13 um 17 55 26](https://user-images.githubusercontent.com/30288503/145976515-c27b4d3e-e6e8-4567-aa09-e90b8d2a7024.png)
 Meines Erachtens ist das doch korrekt ausgefüllt und die Anzahl der Ziel-Einheit müsste automatisch gesetzt werden? Ich habe es dann noch mit anderen Zahlen ausprobiert, das hat aber keinen Unterschied gemacht. 

Nun hat mir Karin Sartori gemeldet, dass sie die gleiche Meldung bei Scorzonera humilis hat (siehe Screenshots):
![Bildschirmfoto 2021-12-14 um 10 29 18](https://user-images.githubusercontent.com/30288503/145977178-7deabd32-7c72-4f0b-a209-29def0219562.png)
Auch hier noch die Massnahme dazu:
![Bildschirmfoto 2021-12-14 um 10 30 33](https://user-images.githubusercontent.com/30288503/145977258-15681e49-d2ed-4894-b08f-e2060a996579.png)

Kannst du uns hier weiterhelfen?

**Comment by barbalex** [comment]
Das liegt an der kürzlichen Änderung aller 50 Formulare. Weil in diesem Fall aufgrund komplizierter Abhängigkeiten bei der Speicherung Werte verändert werden, hat wurde Verhalten verändert. Und die von den Mengen abhängigen Werte (Zieleinheit und deren Anzahl) wurden nicht mehr automatisch nachgeführt.

Habe ich nun korrigiert.

Dieser Fehler sollte bei allen entsprechenden Änderungen in den letzen drei oder vier Tagen passiert sein. Gut, dass die Qualitätskontrolle ihn aufdeckt. Zumindest bei neu erfassten Massnahmen. Hätte man in einer bestehenden Massnahme lediglich die Anzahl Pflanzen verändert, hätte man die Änderung nicht gemerkt.

Habe noch kontrolliert, ob dieser Effekt in einem anderen Formular auftreten könnte. Scheint nicht der Fall zu sein.

Ist in Version 1.66.14 korrigiert.

**Comment by rebeccakurz** [comment]
Habe gerade nachgeschaut, aber bei Ophrys araneola TPop 152.2 erscheint diese Fehlermeldung noch immer (siehe Screenshot). Ich habe auf die Version 1.66.14 aktualisiert. 
Muss ich noch irgendetwas machen, damit es wie ausgelöst wird? Muss z.B. die Anzahl Pflanzen nochmals eingegeben werden?
![Bildschirmfoto 2021-12-16 um 17 59 40](https://user-images.githubusercontent.com/30288503/146415880-79e3aacd-864a-4579-81f1-0c6bc6b666cb.png)

**Comment by barbalex** [comment]
Ja. Denn es funktioniert so:

Der Datensatz wird geändert. Nun wird kontrolliert:
1. Wurde der Typ geändert? Wenn ja: War das eine Anpflanzung? Wenn ja: Wird die Einheit der Zieleinheit gesetzt
2. Wurde die Anzahl Triebe geändert? Wenn ja: Entspricht der Typ einer Anpflanzung? Wenn ja: Entspricht die EK-Zieleinheit der Anzahl Triebe? Wenn ja: Wird die Anzahl der Zieleinheit = Anzahl Triebe gesetzt
3. Wurde die Anzahl Pflanzen geändert? Wenn ja: Entspricht der Typ einer Anpflanzung? Wenn ja: Entspricht die EK-Zieleinheit der Anzahl Pflanzen? Wenn ja: Wird die Anzahl der Zieleinheit = Anzahl Pflanzen gesetzt

Mit anderen Worten: Es gibt keine allgemeine Beziehung, da die Regeln kompliziert sind und abhängig von der Definition der EK-Zähleinheiten. Einheit und Anzahl der Zieleinheit werden nur nach Änderungen an den drei relevanten Feldern verändert. Einzige systematische Kontrolle sind die Qualitätskontrollen.

Was wiederum heisst: Um es zu korrigieren müsst ihr jetzt:
- entweder von Hand ändern (direkt in den Feldern der Zieleinheiten)
- oder Typ ändern damit dieser nachgeführt wird (falls ihr einen Fall findet, wo er nicht stimmt) 
- oder Anzahlen ändern (z.B. +1 und danach -1), um die Anzahl der Zieleinheit zu korrigieren

**Comment by barbalex** [comment]
Übrigens: Sorry, dass ich nicht daran gedacht habe, dir zu sagen dass sich das nicht von selber korrigiert...

**Comment by rebeccakurz** [comment]
Jetzt hat es geklappt, danke!
Und kein Problem!
