### ISSUE TITLE
Beobachtungen zuordnen: Koordinaten werden nicht automatisch gesetzt

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#496]
Hoi Alex
Bei dem Befehl "neue Teil-Population in bestehender Population gründen und Beobachtung der Teil-Population zuordnen" werden die Koordinaten der Beobachtung ja automatisch in die Teilpopulation übertragen. 
Nun hat Seraina aber zwei Beispiele, wo das nicht funktioniert hat und danach eine Fehlermeldung in der Qualitätskontrolle gekommen ist, da die Koordinaten in der TPop fehlen. 
Dies bei Dactylorrhiza incarnata subsp. ochroleuca TPop 107.2 und 109.2. Sie hat diesen Befehl noch mehr gebraucht, in den restlichen Fällen hat es aber geklappt mit dem Setzen der Koordinaten. 

Könntest du dir das mal anschauen?

**Comment by barbalex** [comment]
Wenn ich die Programmierung dieser Routine anschaue kann ich mir dieses Resultat nicht erklären, denn:
Wenn die neue TPop gegründet wird und das Setzen der Koordinaten misslingt, sollte das Gründen der neuen TPop grundsätzlich scheitern, die Beobachtung wird ihr nicht zugeordnet und die Benutzerin sieht eine entsprechende Meldung.

Es gibt im code allerdings ein Ort, in dem in zwei aufeinanderfolgenden Programmierzeilen dieselbe Variable neu zugeordnet wird. _Theoretisch_ könnte ich mir vorstellen, dass es nicht unmöglich ist, dass dieser Vorgang unter ganz besonderen Umständen scheitern könnte - wenn der PC gerade einen kurzen "Aussetzer" hatte, d.h. in einer Programmierzeile "schläft". Was nicht passieren sollte aber bekanntlich gibt es ja nichts was es nicht gibt.

Habe darum die Programmierung angepasst. Und noch ein paar weitere ähnliche Stellen in anderen Routinen korrigiert. Ist in Version 1.66.12 aktiv.

Aber wie gesagt: So was sollte nicht passieren. Wenn der PC solche Aussetzer hätte, könnte manch Anderes schief laufen.

**Comment by rebeccakurz** [comment]
Okay, danke. Dann werden wir das weiter im Auge behalten...
Aber wie du sagst, mich verwundert gar nichts mehr... Gibt nichts, was es nicht gibt.

**Comment by barbalex** [comment]
Ach ja: Um die aktuellen Fälle zu korrigieren: 
1. "nicht zuordnen" klicken > beob is nicht zuzuordnen
2. "nicht zuordnen" klicken > beob is nicht beurteilt
3. neu zuordnen > die Koordinaten sind drin

**Comment by rebeccakurz** [comment]
Super, danke. Werde ich weiterleiten.
