### ISSUE TITLE
Beobachtungen zuordnen: Cypripedium calceolus

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#499]
Hoi Alex

Beim Frauenschuh hat es sehr viele Beobachtungen (über 2500), die noch zugeordnet werden müssen. 
Wenn man die Zuordnung über die Karte machen will, kommt aber immer die Meldung, dass es zuviele Beobachtungen sind und sie daher nicht angezeigt werden können und man den Ausschnitt kleiner wählen soll. Diese Meldung kommt aber auch, wenn man nur einen kleinen Ausschnitt der Karte gewählt hat. Und die Meldung erscheint auch erst, wenn man die Zuordnung in der Karte "aktiviert" indem man auf das Play-Zeichen bei den nicht zugeordneten Beobachtungen drückt.
![Bildschirmfoto 2021-12-20 um 11 55 04](https://user-images.githubusercontent.com/30288503/146757165-5e9ff844-8e37-4fe4-8017-de32e18039bb.png)
Solange man die Zuordnung nicht aktiviert, werden die Beobachtungen angezeigt:
![Bildschirmfoto 2021-12-20 um 11 55 17](https://user-images.githubusercontent.com/30288503/146757188-b2a04dbe-c8a0-437a-b910-2cb14a26c6f3.png)
Das Problem scheint auch nur bei Cypripedium zu bestehen, wahrscheinlich, weil hier so viele Beobachtungen vorhanden sind? Kann man da etwas machen, damit die Zuordnung über die Karte möglich ist?
Danke fürs Anschauen!

**Comment by barbalex** [comment]
Früher war die Karte weniger leistungsfähig. Daher musste ich eine Methode finden, um zu verhindern, dass zuviele Objekte gleichzeitig darauf gezeichnet werden müssen. Ich habe sehr aufwändig ein System gebaut. Es beruhte darauf, zu kontrollieren, wieviele Objekte gezeichnet werden müssen, bevor die Karte gezeichnet wird. Und euch aufzufordern, mehr zu zoomen, wenn es zuviele waren. 

Jahre später hat dieses System (nach einem Update der Karten-Software) Probleme bereitet. Da die Karte in der Zwischenzeit leistungsfähiger geworden war, habe ich das System wieder entfernt.

Der Code, der die Anzahl Objekte prüfte, blieb dabei unglücklicherweise erhalten. Habe ihn jetzt entfernt.

Ist in Version 1.66.21 korrigiert. Diese Version sollte jeden Moment live kommen.

**Comment by rebeccakurz** [comment]
Super, das hat geklappt, vielen Dank!
