### ISSUE TITLE
Kartenlayer

### ISSUE THREAD

**Issue by wunderli** [barbalex/apf2#5]
Für EK-Pläne verwende ich meist Orthofoto unter ("durchsichtigem"/Transparentem) UP.
In der neuen Version verschwindet das Ortho hinter dem UP, da verschiedene Ebenen.

**Comment by barbalex** [comment]
Das war so geplant und funktionierte. Dann hab ich was geändert, und du hast mich nun darauf hingewiesen, dass es nicht mehr funktioniert :-(

Habe das repariert: Du kannst nun den Uep als "überlangernd" Layer über das Luftbild legen und es ist transparent.
