### ISSUE TITLE
Exporte download - Prozess wird nicht angezeigt

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#50]
Man hat das Gefühl, der Befehl funktioniere nicht und drückt dann gleich mehrmals (die ungeduldigen..) mit dem Resultat von mehreren Downloads

**Comment by barbalex** [comment]
Jetzt erscheint eine Meldung.

Aber so, dass man - falls der Vorgang _sehr_ lange dauert - weiter arbeiten kann.
