### ISSUE TITLE
Fehlermeldung bei Eingabe Zähleinheiten durch AV (Benutzerrechte)

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#502]
Hoi Alex
René Bertiller wollte bei Thesium linophyllon die zielrelevante Zähleinheit hinzufügen. Das hat aber nicht geklappt, es erschien folgende Fehlermeldung: 
new row violates row-level security policy for table "ekzaehleinheit"
[GraphQL error]: Message: new row violates row-level security policy for table "ekzaehleinheit", Location: [{"line":2,"column":3}], Path: createEkzaehleinheit
 
Dies bedeutet, dass er nicht die nötigen Berechtigungen zum Erfassen der Zähleinheiten hat, nicht wahr?
Finde ich etwas komisch, denn es haben auch schon andere Artverantwortliche bei ihren Arten Zähleinheiten erfasst. Hat sich bei diesen Berechtigungen etwas geändert? Oder bedeutet die Fehlermeldung etwas anderes?
Vielen Dank für deine Hilfe!

**Comment by barbalex** [comment]
Nein, EK-Zähleinheiten konnten schon immer nur von Benutzern mit der Rolle "apflora_manager" verändert werden.

Der Text "new row violates row-level security policy for table "ekzaehleinheit"" weist, wie du gemerkt hast (und leider sehr technisch denn es ist die Datenbank, die das sagt) darauf hin, dass René nicht die benötigten Rechte hat.

Der Grund dafür wird folgender sein: Wie und wo sich zielrelevante Zähleinheiten auswirken ist über längere Zeit gewachsen. Die Regeln dahinter habt ihr aufgrund der Anforderungen im Projekt gesetzt. Aber sie sind kompliziert bzw. deren Anwendung in der App ist es. Es ist nicht einfach, zu wissen, wo überall sich eine Änderung auswirken wird (EK-Planung, Zeitliche Auwertungen, andere Auswertungen, Qualitäts-Kontrollen, EKF-Formular...). Darum ist es besser, wenn solche Änderungen besonders bewusst passieren und von Personen, die das auch bewusst machen, weil sie um die Komplexität wissen.

Ich will damit nicht sagen, dass René das nicht gut machen würde. Nur dass wir deshalb die Rechte nicht allen AV's freigeben wollten.

**Comment by rebeccakurz** [comment]
Okay, wie kann es dann aber sein, dass andere Artverantwortliche mit dem Status "ap-writer" Zähleinheiten erfassen konnten?
Z.B. Selina Fäh bei Cirsium tuberosum
Christoph Käsermann bei Rhynchospora fusca
Charlotte Salzmann bei Laserpitium prutenicum
So weit ich weiss, konnten diese AV die Zähleinheiten problemlos ändern...

**Comment by barbalex** [comment]
Ich habe jetzt extra nochmals alles durchkontrolliert und an einem Beispiel getestet:

- lokal das Backup von gestern Abend hergestellt
- Das Passwort des Benutzers a verändert, damit ich als a einloggen kann
- Benutzer a als reader gesetzt: konnte nicht ändern oder neu schaffen
- Benutzer a als ap_writer: konnte nicht ändern oder neu schaffen
- Benutzer a als manager: konnte ändern und neu schaffen

Das entspricht genau dem Verhalten, das seit Jahren programmiert und für diesen Code von PostgreSQL so dokumentiert ist. Die Rechte werden (ausser bei ap_reader, welche z.B. das Menü um neue Datensätze zu erzeugen gar nie sehen) auf Ebene Datenbank durchgesetzt. Wenn es einen Fehler gibt, dürfte er eigentlich nicht dort passieren. Dann wäre es eher so, dass die App nach einer Änderung etwas anzeigte, was die Datenbank gar nie akzeptiert hatte (wenn z.B. die Kommunikation zwischen Datenbank (auf dem Server) und App (im Browser, auf eurem PC) nicht richtig funktioniert hätte). Und das daher beim nächsten Aufruf dieser Daten nicht mehr so wäre, weil die App dann wieder die Daten von der Datenbank bezieht. Welche Änderungen nur von managern akzeptiert.

Kann es sein, dass hier Missverständnisse bestehen? Und Selina/Christoph nicht das meinten? Charlotte war früher manager, das könnte dort der Grund gewesen sein (heute ist sie ap_writer und sollte daher keine EK-Zähleinheiten ändern können).

Wenn ihr eindeutig ein falsches Verhalten provozieren könnt, gehe ich dem selbstverständlich weiter auf den Grund. Ansonsten möchte ich diese aufwändigen Tests lieber nicht zu oft durchführen müssen (es hat mich eine gute Stunde gekostet).

**Comment by barbalex** [comment]
Schliesse, da seit 21 Monaten inaktiv
