### ISSUE TITLE
Qualitätskontrolle Fehlermeldung EK-Planung

### ISSUE THREAD

**Issue by kmarti** [barbalex/apf2#505]
Bei Typha shuttleworthii gibt es in der Qualitätskontrolle die Meldung, dass Pop 66.1 erloschen ist, dass aber EK geplant sei. Effektiv ist noch eine EK vorgesehen in der EK-Planung.

Auch bei Potentilla leucopolitana ist in der Qualitätskontrolle die Meldung enthalten, dass die Pop 8.3 erloschen sei und dass eine EK geplant sei. In der EK-Planung sind aber keine EK vorgesehen. Dasselbe trifft auf die Pop 18.13, 18.14 und 18.20 von Potentilla praecox zu. 

Ansonsten sind die (überprüften) früheren Fehlermeldungen wegen geplanten EK bei erloschenen TP in der Qualitätskontrollen nun verschwunden.

**Comment by barbalex** [comment]
> Bei Typha shuttleworthii gibt es in der Qualitätskontrolle die Meldung, dass Pop 66.1 erloschen ist, dass aber EK geplant sei. Effektiv ist noch eine EK vorgesehen in der EK-Planung

Was meinst du mit "Effektiv ist noch eine EK vorgesehen in der EK-Planung"? Bestätigt das nicht folgendes:

In 2028 ist eine EK geplant, obwohl die TPop gemäss Kontroll-Bericht von 2020 erloschen ist. Das heisst doch, dass diese Qualitätskontrolle hier genau das aufdeckt, was sie soll. Verstehe ich etwas falsch?

> Auch bei Potentilla leucopolitana ist in der Qualitätskontrolle die Meldung enthalten, dass die Pop 8.3 erloschen sei und dass eine EK geplant sei. In der EK-Planung sind aber keine EK vorgesehen. 

Tja. Die Qualitätskontrolle funktioniert genau so wie sie formuliert ist. Nur ist das in diesem Fall eventuell nicht, was ihr wollt: 

Sie heisst "Teilpopulation: Status ist erloschen (ursprünglich oder angesiedelt). Nach dem letzten Teil-Populations-Bericht sind aber Kontrollen geplant".

Und In TPop 8.3 wurde 2011 und 2012 erloschen gemeldet. Für 2016 ist (war) aber eine Kontrolle geplant.

> Dasselbe trifft auf die Pop 18.13, 18.14 und 18.20 von Potentilla praecox zu.

- 18.13: 2009 und 2010 erloschen berichtet. 2018 Kontrolle geplant.
- 18.14: 2009 und 2010 erloschen berichtet. 2018 Kontrolle geplant.
- 18.20: 2009 erloschen berichtet. 2012 Kontrolle geplant.


Falls ihr solche Ungereimtheiten nicht aufdecken wollt, müssten wie die Qualitätskontrolle so an passen, dass sie nur Kontrollen in der Zukunft berücksichtigt.

Ich glaube, was passiert ist: du hast im Formular für die EK-Planung geschaut. Dort werden in der Standard-Einstellung nur die vergangenen 5 Jahre angezeigt. Dann sieht man obige Fälle nicht, weil sie weiter zurück liegen. Ich habe im TPop-Formular im Register "EK" nachgeschaut. Dort sieht man es. Natürlich sähte man es auch im EK-Planungs-Formular, wenn man im Feld "vergangene Jahre" oben rechts einen höheren Wert setzt.

**Comment by rebeccakurz** [comment]
> > Bei Typha shuttleworthii gibt es in der Qualitätskontrolle die Meldung, dass Pop 66.1 erloschen ist, dass aber EK geplant sei. Effektiv ist noch eine EK vorgesehen in der EK-Planung
> 
> Was meinst du mit "Effektiv ist noch eine EK vorgesehen in der EK-Planung"? Bestätigt das nicht folgendes:
> 
> In 2028 ist eine EK geplant, obwohl die TPop gemäss Kontroll-Bericht von 2020 erloschen ist. Das heisst doch, dass diese Qualitätskontrolle hier genau das aufdeckt, was sie soll. Verstehe ich etwas falsch?
Genau, die QK arbeitet korrekt. Die Frage ist eigentlich, warum wurde bei dieser TPop die EK-Frequenz nicht auf "nie" gesetzt letzten Donnerstag? Die TPop ist ja erloschen und der letzte TPop-Bericht ist auch erloschen/nicht etabliert. Dann hätte doch hier die EK-Frequenz auf "nie" gesetzt werden sollen?

> > Auch bei Potentilla leucopolitana ist in der Qualitätskontrolle die Meldung enthalten, dass die Pop 8.3 erloschen sei und dass eine EK geplant sei. In der EK-Planung sind aber keine EK vorgesehen.
> 
> Tja. Die Qualitätskontrolle funktioniert genau so wie sie formuliert ist. Nur ist das in diesem Fall eventuell nicht, was ihr wollt:
> 
> Sie heisst "Teilpopulation: Status ist erloschen (ursprünglich oder angesiedelt). Nach dem letzten Teil-Populations-Bericht sind aber Kontrollen geplant".
> 
> Und In TPop 8.3 wurde 2011 und 2012 erloschen gemeldet. Für 2016 ist (war) aber eine Kontrolle geplant.
> 
> > Dasselbe trifft auf die Pop 18.13, 18.14 und 18.20 von Potentilla praecox zu.
> 
>     * 18.13: 2009 und 2010 erloschen berichtet. 2018 Kontrolle geplant.
> 
>     * 18.14: 2009 und 2010 erloschen berichtet. 2018 Kontrolle geplant.
> 
>     * 18.20: 2009 erloschen berichtet. 2012 Kontrolle geplant.
> 
> 
> Falls ihr solche Ungereimtheiten nicht aufdecken wollt, müssten wie die Qualitätskontrolle so anpassen, dass sie nur Kontrollen in der Zukunft berücksichtigt.

Eigentlich ist es ja schon gut, dass solche Fälle aufgedeckt werden. Bei diesen Fällen müsste das Startjahr der EK-Frequenz "nie" angepasst werden, ist das richtig?
> 
> Ich glaube, was passiert ist: du hast im Formular für die EK-Planung geschaut. Dort werden in der Standard-Einstellung nur die vergangenen 5 Jahre angezeigt. Dann sieht man obige Fälle nicht, weil sie weiter zurück liegen. Ich habe im TPop-Formular im Register "EK" nachgeschaut. Dort sieht man es. Natürlich sähe man es auch im EK-Planungs-Formular, wenn man im Feld "vergangene Jahre" oben rechts einen höheren Wert setzt.

Ich glaube das eigentliche Problem war, dass wir davon ausgegangen sind, dass es sich um "neu" erloschene TPops aus dem Jahr 2021 handelt und daher nicht auf die vorhergehenden Jahre geschaut haben...

**Comment by barbalex** [comment]
>
> Bei diesen Fällen müsste das Startjahr der EK-Frequenz "nie" angepasst
> werden, ist das richtig?


Korrekterweise ja. Aber ich _glaube_ (Irrtum vorbehalten) es hat keine
Wirkung: Das Startjahr dient dazu, die EK-Pläne ausgehend davon zu setzen.
Und wenn es keine EK-Pläne gibt, ist das Startjahr nicht wirklich nötig.

Ich glaube das eigentliche Problem war, dass wir davon ausgegangen sind,
> dass es sich um "neu" erloschene TPops aus dem Jahr 2021 handelt und daher
> nicht auf die vorhergehenden Jahre geschaut haben...


O.k., sie waren jedenfalls nicht Teil der Liste derjenigen TPops, deren
EK-Frequenz von mir auf nie gesetzt wurden.

LG, Alex

***********************************************************



Alexander Gabriel
Wiesenstrasse 22
8800 Thalwil
079/ 372 51 64
***@***.***
https://gabriel-software.ch

**Comment by barbalex** [comment]
schliesse, da lange keine Aktivität mehr
