### ISSUE TITLE
Grüne Bälkli erscheinen im Strukturbaum

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#506]
Hoi Alex
Charlotte hat mir noch gemeldet: "Seit ca. 1. Stunde hab ich so kleine grüne Bälkli bei jeder Zeile. Die stören beim Scrollen. Und sie beunruhigen mich auch etwas. Ich hab schon neu gestartet und Cache geleert, bleibt alles gleich."
Sie hat das gestern Abend etwa um 9 Uhr gemeldet, siehe Screenshot. 
Ich habe jetzt heute nachgeschaut, habe die selben Dinge eingeschaltet wie sie (Strukturbaum, Daten, Karte, Strukturbaum 2, gleiche Art), aber bei mir ist nichts auffälliges zu entdecken.
Könnte die FloraDB gestern Abend etwas am Anschlag gewesen sein? Kannst du dir sonst einen Grund vorstellen?
Vielen Dank für deine Hilfe und liebe Grüsse
![image004](https://user-images.githubusercontent.com/30288503/149284824-9f02f74b-1f2a-46d4-bcf9-f95b7f7c0c6e.png)

**Comment by barbalex** [comment]
Wie es scheint, erscheinen diese Balken, wenn man auf > 125% ctrl+scrollt. D.h., wenn man die Schriften so weit vergrössert. Werde dem nachgehen.

**Comment by barbalex** [comment]
Ist in Version 1.66.30 korrigiert. Danke für die Meldung

**Comment by rebeccakurz** [comment]
Super, dass du das herausgefunden hast! Vielen Dank!
