### ISSUE TITLE
Qualitätskontrolle 

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#507]
Bei Gagea pratensis kommt in der Qualitätskontrolle zu der Teilpopulation 28.5 die Meldung "Bekannt seit ist jünger als die älteste zugeordnete Beobachtung". 
Wenn man dann bei der TPop nachschaut, hat sie bei "bekannt seit" 1889 angegeben. Die älteste zugeordnete Beobachtung stammt auch von 1889. Damit wäre das ja korrekt oder? 
Es hat aber auch noch eine zugeordnete Beobachtung ohne Datum. Könnte die Fehlermeldung von dieser stammen? Was kann man da machen, um die Meldung aufzuheben?
![Bildschirmfoto 2022-01-19 um 08 54 09](https://user-images.githubusercontent.com/30288503/150087944-8ef976a4-36df-43bf-8b12-62d1cce53cb4.png)

**Comment by barbalex** [comment]
Tja, die Beobachtung ohne Datum hat in den Rohdaten das Datum 5.4.0000. Das ist nicht kein Datum (was von der Qualitätskontrolle ausgeschlossen wurde).

Ich habe jetzt die Qualitätskontrolle so angepasst, dass sie auch solche Daten ausschliesst.

Danke für den Hinweis.

**Comment by rebeccakurz** [comment]
Okay, vielen Dank!
