### ISSUE TITLE
Export: Populationen, Letzte Zählungen inklusive noch nicht kontrollierter Anpflanzungen

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#508]
Hoi Alex
Bei dem oben erwähnten Export, den wir ja für die Zielüberprüfung benutzen, ist uns aufgefallen, dass die noch nicht kontrollierten Anpflanzungen leider ignoriert werden, wenn es sich um eine Ergänzungspflanzung handelt. Also immer dann, wenn in einer Teilpopulation, in der es bereits einmal eine Anpflanzung gab, erneut ausgepflanzt wird. Diese neuen Pflanzen werden im Export dann nicht zu der totalen Anzahl hinzugezählt. 
Beispiele von Populationen mit Ergänzungspflanzungen in diesem Jahr: 

- Pulsatilla vulgaris Pop. 117
- Potentilla praecox Pop. 22
- Thalictrum galioides Pop. 47

Jetzt weiss ich nicht, ob das schon immer so war in diesem Export, es uns einfach nicht aufgefallen ist, da es nicht so viele Ergänzungspflanzungen gibt. Vielleicht haben wir das auch gar nicht berücksichtigt, als wir diesen Export gewünscht haben (der wirklich super ist für die Zielüberprüfung!). 

Auf jeden Fall wäre es super, wenn der Export auch diese Ergänzungspflanzungen berücksichtigen könnte. Ist das möglich? Könntest du dir das mal anschauen?

Vielen Dank!

**Comment by rebeccakurz** [comment]
Und gleich noch eine Ergänzung: 
Auch bei den Grafiken im Jahresbericht scheinen diese Ergänzungspflanzungen nicht berücksichtigt zu werden. Im folgenden Screenshot das Beispiel von Potentilla praecox, Pop. 22 Weiach, SBB-Böschung. Hier müssten zu den 23 Pflanzen der letzten Zählung eigentlich noch 10 Pflanzen aus der Ergänzungsansiedlung von 2021 hinzukommen. 
![Bildschirmfoto 2022-01-20 um 08 35 45](https://user-images.githubusercontent.com/30288503/150294164-845a9fa5-10a8-4640-b582-d138cb761bcc.png)

**Comment by rebeccakurz** [comment]
Im Gegensatz dazu scheint es bei Thalictrum Pop 47, Eglisau/Glattfelden, Eglisgrund in der Grafik nicht die Anzahl der letzten Zählung (35 Triebe), sondern nur die Anzahl aus der Ergänzungspflanzung (66 Triebe) in der Grafik vom Jahresbericht anzuzeigen...
![Bildschirmfoto 2022-01-20 um 08 41 40](https://user-images.githubusercontent.com/30288503/150294884-308ec6cb-0b7f-4dda-b9e2-66261be9a87c.png)

Bei dem Beispiel von Pulsatilla, Pop 117, scheint es hingegen in der Grafik wiederum nur die letzte Zählung anzugeben.

**Comment by rebeccakurz** [comment]
Soll ich daraus zwei Issues machen, einmal für den Export und einmal für die Grafiken im Jahresbericht?

**Comment by barbalex** [comment]
> Soll ich daraus zwei Issues machen, einmal für den Export und einmal für die Grafiken im Jahresbericht?

Ja gerne, dahinter stehen völlig unterschiedliche Abfragen.

**Comment by barbalex** [comment]
Zum Export eine Vorbemerkung: Es gilt, was ich in eurem [andern Anliegen](https://github.com/barbalex/apf2/issues/424#issue-783558500) in der Vorbemerkung erwähnt habe. Kurze Zusammenfassung:

> Es handelt sich hier um eine besonders schwierige und aufwändig zu codierende Abfrage (nicht aber überaus leistungs-hungrige). Und die Abfrage für Populationen baut auf der analogen für Teilpopulationen auf. Daher sind diese Abfragen besonders fragil und aufwändig zu unterhalten.

Daher ist es auch recht aufwändig, die Abfrage neu zu beurteilen. Es kann daher ein Weile dauern, bis ich eine Antwort habe.

**Comment by rebeccakurz** [comment]
Auch von unserer Seite her noch eine Bemerkung: Es würde uns reichen, wenn dieser Export auf nächstes Jahr/auf die nächste Zielüberprüfung angepasst wird. Da es sich ja um eine Erweiterung (?) handelt. 
Vielleicht auch ein Thema für unsere Planungssitzung? Dann könnten wir auch das andere Anliegen nochmals aufgreifen. Da sind wir glaube ich sowieso noch eine Antwort schuldig...

**Comment by barbalex** [comment]
Erste Erkenntnis: Die Abfrage ist so designt, dass Massnahmen nur berücksichtigt werden, wenn es keine Kontrollen gibt.
Darum heisst es auch: 

> inklusive noch nicht kontrollierter Anpflanzungen

Das sind also angepflanzte Teilpopulationen, die noch nicht kontrolliert wurden.

Es geht also nicht darum, ob es schon mal eine Anpflanzung gab. Sondern: Ob die TPop schon einmal kontrolliert wurde.

Ich glaube ihr möchtet jetzt lieber: **Populationen, aktuellste Zählung inklusive seither erfolgter Anpflanzungen**

Stimmt das?

**Comment by rebeccakurz** [comment]
Hm ich glaube das stimmt. Aber würden dann, wie auch im jetzigen Export, immer noch die Massnahmen auch berücksichtigt, wenn es noch keine Kontrolle gegeben hat? Also eine Kombination daraus. Folgende Kombinationen müssten berücksichtigt werden (ich hoffe ich vergesse nichts): 

- Auspflanzung (bei ursprünglichen Populationen entfällt die Auspflanzung)--> Zählung --> letzte Zählung wird berücksichtigt
- Auspflanzung --> noch keine Zählung erfolgt --> Massnahme (Auspflanzung) wird berücksichtigt)
- Auspflanzung --> Zählung --> Ergänzungspflanzung --> letzte Zählung UND seither erfolgte Anpflanzung werden berücksichtigt

**Comment by barbalex** [comment]
Richtig.

Hast du ein Beispiel eine TPop ohne Zählung aber mit Anpflanzung? Dann kann ich meine Abfrage kontrollieren.

**Comment by barbalex** [comment]
O.k., habe die Abfrage angepasst. Sie berücksichtigt jetzt die jeweils aktuellste Zählung inklusive seither erfolgter Anpflanzungen. Und wenn keine Zählung existiert, nur die Anpflanzungen.

Eine Bemerkung noch dazu: Verglichen wird das Jahr, nicht das Datum.

Das heisst: Gab es eine Kontrolle, gilt die Anpflanzung als neuer, wenn sie **frühestens im Jahr nach der letzen Kontrolle** stattfand.

Und zwei deiner Beispiele könnten genau dieses Problem betreffen:

### Pulsatilla vulgaris Pop. 117, TPop 1
Die Kontrolle fand am 28.3.2021 statt, die Anpflanzung am 18.11.2021.

### Potentilla praecox Pop. 22
Die Kontrolle fand am 21.6.2021 statt, die Anpflanzung am 4.11.2021.

Wenn ihr wollt, dass das genaue Datum verglichen wird, muss ich in den Abfragen statt nur die Jahre vergleichen: 

1. prüfen ob Kontrolle und Massnahme ein genaues Datum haben 
2. die genauen Daten vergleichen, wenn beide eines haben 
3. wie bisher die Jahre vergleichen, wenn sie nicht beide genaue Daten haben

**Comment by barbalex** [comment]
Bisher drei Stunden Aufwand. Müssen wir budgetieren. Wird das Budget abgelehnt, ist es mein eigenes Problem. Ich wollte es einfach machen, solange wir es frisch haben, weil es so kompliziert ist.

**Comment by rebeccakurz** [comment]
Sorry, ich hatte noch eine Besprechung, darum konnte ich dir das Beispiel nicht liefern. 
Ich denke es wäre schon gut, wenn das genaue Datum berücksichtigt werden würde. Weil häufig finden Ergänzungspflanzungen im gleichen Jahr wie die Erfolgskontrolle statt, weil man dann zum Beispiel sieht, dass die Teilpopulation noch Potential für eine Ergänzung hätte.

Ja dann werde ich mir das noch notieren, dass es noch budgetiert werden muss. Sollte hoffentlich aber ja kein Problem sein, da dieser Export die Zielüberprüfung wirklich um einiges vereinfacht!

**Comment by barbalex** [comment]
> Ich denke es wäre schon gut, wenn das genaue Datum berücksichtigt werden würde. Weil häufig finden Ergänzungspflanzungen im gleichen Jahr wie die Erfolgskontrolle statt, weil man dann zum Beispiel sieht, dass die Teilpopulation noch Potential für eine Ergänzung hätte.

Leuchtet ein. Ist umgesetzt.

**Comment by barbalex** [comment]
Übrigens: Tip top wie du die zwei Issues getrennt hast. Danke. So behalten wir die Übersicht.
