### ISSUE TITLE
Grafik "Pflanzen/Triebe total nach Populationen" im PDF Jahresbericht

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#509]
Bei diesen Grafiken im PDF des Jahresberichts werden die Ergänzungspflanzungen bei den Zählungen nicht berücksichtigt. Also immer dann, wenn in der gleichen Teilpopulation nochmals eine Auspflanzung als Ergänzung einer früheren Ausbringung stattgefunden hat, werden diese Zahlen nicht zusammengezählt. 
Beispiel Potentilla praecox, Population 22, Weiach, SBB-Böschung. Hier müssten zu den 23 Pflanzen in der letzten Zählung eigentlich noch 10 Pflanzen aus der Ergänzungspflanzung von 2021 hinzukommen. Siehe Screenshot:
![Bildschirmfoto 2022-01-20 um 08 35 45](https://user-images.githubusercontent.com/30288503/150339683-3acde7c5-62cb-4760-a4e4-d268f768c787.png)
Oder auch beim Beispiel Pulsatilla vulgaris, Population 117. Auch hier gibt es in der Grafik nur die letzte Zählung an und die Ergänzungspflanzung von 2021 fehlt.

**Comment by rebeccakurz** [comment]
Hingegen beim Beispiel Thalictrum galioides, Population 47, Eglisau/Glattfelden, Eglisgrund wird in der Grafik nicht die Anzahl der letzten Zählung (35 Triebe), sondern nur die Anzahl aus der Ergänzungspflanzung von 2021 (66 Triebe) angezeigt. Aber auch hier werden die Anzahlen nicht zusammengezählt.
![Bildschirmfoto 2022-01-20 um 08 41 40](https://user-images.githubusercontent.com/30288503/150340149-82f15067-a85a-4bbb-bc05-6e9d66b321bd.png)

**Comment by barbalex** [comment]
Ich habe das heute in 2 Stunden Arbeit angepasst. Bitte prüfe, ob es für dich so stimmt. Ich bin ziemlich sicher, aber die Abfragen sind doch recht anspruchsvoll.

**Comment by rebeccakurz** [comment]
Das sieht soweit gut aus, vielen Dank!
