### ISSUE TITLE
Zahlen/Grafiken im JB: angesiedelte Pop fehlen

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#510]
Hoi Alex
Wir haben bereits die nächste Meldung zu den PDFs der Jahresberichte. Und zwar bei den (neuen) Arten Dianthus gratianopolitanus und Schoenoplectus triqueter. Hier scheinen in den PDFs der Jahresberichte die angesiedelten aktuellen Populationen in den Zahlen und Grafiken nicht berücksichtigt zu werden. 
Beispiel Dianthus gratianopolitanus:
![Bildschirmfoto 2022-01-24 um 12 08 47](https://user-images.githubusercontent.com/30288503/150772223-5a12a0ea-3448-4b70-b6d3-0ee2662fd175.png)
![Bildschirmfoto 2022-01-24 um 12 09 03](https://user-images.githubusercontent.com/30288503/150772238-8f06e439-f2ec-4747-8fb7-9e8707740ba5.png)
Hier müsste es 12 angesiedelte aktuelle Populationen geben, im JB werden aber nur die ursprüglich aktuellen Populationen aufgeführt. 

Beispiel Schoenoplectus triqueter: 
![Bildschirmfoto 2022-01-24 um 12 12 55](https://user-images.githubusercontent.com/30288503/150772765-512cc4ba-505e-48f2-8c9e-7b87fdd9dfeb.png)
Hier müssten eigentlich 4 angesiedelte erloschene Populationen aufgeführt sein. 

Oder übersehen wir hier etwas? Bei anderen (auch neuen) Arten scheint es aber zu stimmen.
Könntest du dir das mal ansehen?

**Comment by barbalex** [comment]
### Beispiel Dianthus gratianopolitanus
Ihr müsst das Startjahr erfassen. Ohne dieses kann apflora nicht zwischen den beiden Typen von `angesiedelt` unterscheiden. 

### Beispiel Schoenoplectus triqueter
Wenn ich das Formular aufrufe, erscheinen 3/4 erloschene. Auch hier fehlt aber das Startjahr.

### Idee

Vielleicht sollten wir das Fehlen eines Startjahrs mit einer Qualitätskontrolle fassen.

**Comment by rebeccakurz** [comment]
Achso, daran hat das gelegen... Vielen Dank fürs Herausfinden, jetzt passt es mit den Zahlen im Jahresbericht. 
Das wäre wahrscheinlich nicht schlecht, wenn das mit der Qualitätskontrolle abgefangen werden würde, was meinst du, Karin?
Eigentlich hatte ich beim Erfassen der neuen AP-Arten das Startjahr jeweils gesetzt gehabt, aber scheinbar nicht immer.
