### ISSUE TITLE
PDF Jahresbericht: Jahreszahl falsch

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#511]
In der Kopfzeile des PDFs des Jahresberichts wird anstatt dem aktuellen Jahr, aus dem der JB stammt, das Jahr des Starts des jeweiligen Aktionsplans aufgeführt (siehe Screenshot, Bsp. Saxifraga granulata). 
Könntest du das noch anpassen?
![Bildschirmfoto 2022-01-24 um 12 15 22](https://user-images.githubusercontent.com/30288503/150773253-73930064-4c83-4df2-bb3c-ee30b066a437.png)

**Comment by barbalex** [comment]
Ist in Version 1.67.2 angepasst. Sollte in ein paar Minuten bereit sein.

**Comment by rebeccakurz** [comment]
Super, danke!
