### ISSUE TITLE
FloraDB stürzt ab bei Klick auf EK-Frequenzen im Strukturbaum

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#514]
Ich wollte nachschauen, wie die Kontrolljahre bei einer EK-Frequenz sind und habe dazu im Strukturbaum bei irgendeiner Art bei den EK-Frequenzen im Strukturbaum draufgeklickt. Bei einigen hat es mir dann ohne Probleme die Definition und die Kontrolljahre bei den Daten angezeigt, bei anderen Frequenzen (zb Spez EK S) ist aber die Datenbank abgestürzt.
![Bildschirmfoto 2022-01-25 um 11 55 01](https://user-images.githubusercontent.com/30288503/150964555-3feb6bbc-55f7-4bf2-99c5-7685bde522c8.png)
Habe es dann noch bei einer anderen Art und dann noch bei Abies alba versucht, aber auch hier ist die Datenbank abgestürzt. 

Passiert das bei dir auch? Auch wenn ich mich dann neu angemeldet habe, ist die ganze Datenbank wieder abgestürzt und momentan komme ich auch nicht mehr hinein...

**Comment by barbalex** [comment]
> momentan komme ich auch nicht mehr hinein

Das liegt wohl daran, dass der Fehler passiert, wenn du eine ek-frequenz anzeigst. Und wenn du wieder rein gehst, navigiert apflora zum letzten Ort, d.h. zur ek-frequenz.

Lösche den Cache und versuch's nochmal.

Ich schau mir den Fehler an.

**Comment by barbalex** [comment]
Sollte in Version 1.67.3 repariert sein. Die neue Version sollte in wenigen Minuten verfügbar sein.

**Comment by rebeccakurz** [comment]
Super, danke! Klappt wieder.
