### ISSUE TITLE
Karten-Tool: Karten-Filter

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#515]
In der Karte gibt es das Tool "Karten-Filter". Wenn das aktiviert ist, kann man ein Polygon oder ein Rechteck auf der Karte zeichnen. Aber dann passiert irgendwie nichts weiter. Wozu wäre dieses Tool gedacht?
![Bildschirmfoto 2022-01-25 um 12 03 39](https://user-images.githubusercontent.com/30288503/150973283-53e76c49-b6d0-45ca-a900-53e4db35c82d.png)

**Comment by barbalex** [comment]
Bisher: Einzig bei denjenigen Exporten, bei denen es möglich ist (da sie Objekte mit Koordinaten enthalten)

**Comment by rebeccakurz** [comment]
Ah okay, also dann kann ich eigentlich in der Karte ein Gebiet einzeichnen und dann zb einen Export der Teilpopulationen machen, die in diesem Gebiet vorhanden sind? Oder wie ist das gemeint?

**Comment by barbalex** [comment]
Richtig.

Aber weil der Filter sonst rausfliegt ist leider die Reihenfolge wichtig:

1. Exporte öffnen
2. Karte öffnen und Filter zeichnen
3. Die Option wählen, um den Karten-Filter anzuwenden
4. Exportieren

**Comment by rebeccakurz** [comment]
Hmm das scheint bei mir leider nicht zu funktionieren, der Export enthält immer noch alle Teilpopulationen... Aber ist sicher nichts dringendes. 
Eine der Artverantwortlichen hat mich eben gefragt, für was der Karten-Filter gut ist, daher habe ich nachgefragt.

"Kurze Frage zur FloraDB: Ein Anliegen von mir wäre, dass man/frau in einem Gebiet nach (Teil-)Populationen aller AP-Arten filtern kann. Bisher geht das, indem man in ein Gebiet scrollt und dann im Strukturbaum auf «Aktionspläne» klickt. Danach werden meist alle Teilpopulationen in diesem Gebiet angezeigt. Trotzdem ist die Übersicht nicht ideal, da die Teilpopulationen einzeln angeklickt werden müssen, damit sichtbar wird, um welche AP-Art es sich handelt. Wäre es möglich, anhand eines Polygons nach Teilpopulationen in einem bestimmten Gebiet zu filtern und dann als Excel-Tabelle zu exportieren? Ist das Tool «Karten-Filter» für diesen Zweck nutzbar oder wozu kann ich diesen brauchen?"

Der Karten-Filter wäre demnach genau das, was sie sucht, richtig?

**Comment by barbalex** [comment]
Richtig.

Und wenn es nicht funktioniert, ist das ein Fehler. Ich probiere es Morgen.

**Comment by barbalex** [comment]
O.k., scheint nicht zu funktionieren 😢

**Comment by barbalex** [comment]
Ist in Version 1.67.4 korrigiert. Viel eleganter als bisher 😄

**Comment by rebeccakurz** [comment]
Super, jetzt hat es bei mir auch funktioniert 👍 Danke!
