### ISSUE TITLE
FloraDB startet nicht richtig

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#516]
Hoi Alex
Jetzt will die FloraDB bei mir nicht mehr richtig aufstarten. Es lädt die Daten nicht und folgende Fehlermeldung erscheint:
![Bildschirmfoto 2022-01-25 um 14 57 16](https://user-images.githubusercontent.com/30288503/150990333-3c5c0f15-5155-4dff-8794-ec837174be60.png)
Jetzt habe ich noch im Team nachgefragt, ob bei ihnen das Problem auch besteht. Auch bei Seraina sieht es folgendermassen aus und auch bei Evelyn funktioniert es nich: 
<img width="789" alt="image001" src="https://user-images.githubusercontent.com/30288503/150990463-a9a80188-fb1c-4be5-a6a2-e02955bbc081.png">
 Könntest du dir das mal  anschauen? Ich hoffe ich habe nichts "kaputt" gemacht...

**Comment by barbalex** [comment]
War ein Ausfall der Server bei digitalocean.com von 2022-01-25 14:19:13 bis ca. 15.03 Uhr. Üble Sache.
