### ISSUE TITLE
Wechsel "EK-Planung" zu "Aktionspläne bearbeiten" 

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#521]
Beim Wechsel von der EK-Planung wieder zur Ansicht Aktionspläne bearbeiten, kommt es vor, dass die FloraDB wie hängen bleibt und nichts mehr anwählbar ist (siehe Screenshot). Nach ein paar mal aktualisieren, geht es dann irgendwann wieder. 
Es passiert aber nicht immer und ich habe noch nicht herausgefunden, in welchen Fällen es passiert. 
Charlotte hat mir aber gemeldet, dass es bei ihr auch schon vorgekommen ist. 
![Bildschirmfoto 2022-02-14 um 16 05 56](https://user-images.githubusercontent.com/30288503/154020083-03b1a3f3-e546-4955-9fd9-48db92a0e50b.png)

**Comment by barbalex** [comment]
Sollte in v1.68.5 behoben sein. Die neue Version sollte in ein paar Minuten live sein.
Danke für die Meldung!

**Comment by barbalex** [comment]
Jetzt ist es endlich live.

Ich habe kürzlich den Navigationsbaum modernisiert. Das war eine Nebenwirkung davon 🙄

**Comment by rebeccakurz** [comment]
Danke!
