### ISSUE TITLE
neue Zieleinheit Deckung x Fläche

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#522]
Bei der Erstellung der neuen Aktionspläne ist noch der Wunsch nach einer neuen zielrelevanten Zähleinheit aufgekommen. 
Diese wäre eine Kombination aus Deckung und Fläche, also DeckungxFläche. 
Die Artverantwortlichen würden dann die Fläche, wo die AP-Art vorkommt, in m2 aufnehmen und die Deckung der AP-Art auf dieser Fläche in % (diese Einheiten gibt es ja beide schon und könnten dann auch angegeben werden, aber nicht als zielrelevant). 
Dann könnten sie in der neuen Einheit DeckungxFläche die beiden aufgenommenen Einheiten miteinander verrechnen (evt könnte das sogar die FloraDB selbst?) und man hätte dann eine Angabe, auf wievielen Quadratmetern die Deckung der AP-Art 100% ist (wenn ich das richtig verstanden habe). Diese Angabe wäre dann vergleichbar (z.B. für Entwicklung der Populationen, Zielüberprüfung) und könnte so auch in den Aktionsplänen bei der Ziel-Definierung verwendet werden. 
Beispiel: Fläche 20 m2, Deckung 50% -> DeckungxFläche: 10 (m2 mit einer Deckung von 100%)
Eventuell müsste es möglich sein, dass dann auch Dezimalstellen bei den Zählungen eingegeben werden können. Das ist ja bis jetzt nicht möglich (nur ganze Zahlen). 
Wäre das umsetzbar? Oder nur ein Teil davon? Es wäre auf jeden Fall eine Erweiterung.

**Comment by barbalex** [comment]
Spannend. Ich brauch ein bisschen Zeit, um mir das zu überlegen

**Comment by barbalex** [comment]
Wenn man es sehr simpel halten würde und nur das Ergebnis von DeckungXFläche bzw DeckungXM2 erfasst, wäre keine Erweiterung nötig. 

Ev. kommt hier wieder die Frage, wo das Bemerkungsfeld sein soll, falls man die Details (Deckung und Fläche) im Bemerkungsfeld erfassen will.

Das wäre aus folgender Argumentation schlüssig:

Fläche und Deckung werden vermutlich nie ausgewertet. Ausgewertet wird nur das Resultat von Fläche x Deckung. Daher braucht es auch keine zusätzlichen Felder, um sie zu erfassen?

Ist ja ganz grundsätzlich so, dass es begründet sein sollte, wenn mehr als das Minimum an Daten erfasst wird. Was wäre in diesem Fall also die Begründung, m2 und Deckung separat zu erfassen?
- Rechenfehler nachvollziehen können: Ist das wirklich so wichtig?
- Qualitative Entwicklungen erkennen, z.B. mehr Fläche bei abnehmender Deckung: Ist das nicht etwas, wofür man extra Fachleute hat (die AV's), welche das in die Diskussion einbringen können, wenn es wichtig sein sollte?

Mir scheint auch nicht wichtig, dafür Dezimalstellen zu ermöglichen. Quadratmeter ist doch im Grossen und Ganzen eine sehr feine Masseinheit. Und die Deckung kann man gar nicht genauer schätzen - sie ist sogar immer eine Schätzung. Das Resultat aus m2 x Deckung muss somit kaum in Dezimalstellen erfasst werden können.

Ich frage extra so pingelig, weil die Antworten auch einen Einfluss darauf haben, wie ich es umsetzen würde.

**Comment by rebeccakurz** [comment]
Hmm also ich könnte mir vorstellen, dass die separate Erfassung von m2 und Deckung schon noch wichtig wäre und zwar genau wie du sagst um die qualitative Entwicklung zu erkennen. 
Aber ja, vielleicht wäre das gut, wenn das mit den entsprechenden Artverantwortlichen nochmals besprochen werden würde. Was meinst du, Karin?
Vielleicht könnte man bei dieser Gelegenheit auch noch Fragen, ob Dezimalstellen nötig sind. (Ich könnte mir noch vorstellen, dass es vielleicht zum Teil kleine Flächen sind, dann wäre das vielleicht schon nötig. Andererseits könnte man auf so kleinen Flächen wohl auch die Anzahl Pflanzen oder Triebe erfassen und bräuchte gar nicht so eine abgeschätzte Zieleinheit...)

**Comment by barbalex** [comment]
Bitte denkt auch an die EKF. Wenn Daten für diese Einheit anders erfasst werden sollen, geht das bei der EKF kaum.

**Comment by barbalex** [comment]
Grundsätzlich aber ist es durchaus möglich, einen solchen Spezialfall vorzusehen. 

Und da ein Spezialfall oft weitere nach sich zieht, würde ich es so machen, wie bei den Beobachtungen/Detailplänen/Massnahmenplänen: Platz schaffen, für individuelle Differenzen indem JSON verwendet wird. Das funktioniert gut und effizient, solange die speziell erfassten Daten nicht (intensiv) für Auswertungen verwendet werden.

Was aber bleibt ist eine hohe Komplexität in der Programmierung und auch für die Erfassung. In diesem Fall denke ich, dass die Erfassung weniger das Problem ist, weil das Prinzip fachlich gesehen schlüssig ist.

Die Komplexität führt allerdings auch dazu, dass - wie bei den EKF - der Spielraum, um Zählungen künftig effizienter erfassen zu können, sinkt. Ein Formular, dass diverse Spezialfälle mit unterschiedlichen Eingabemasken auffangen können soll, kann z.B. nicht einfach als Liste dargestellt werden. Da müssten wir dann wohl kreativ werden.

**Comment by barbalex** [comment]
Aus biologisch-fachlicher Sicht: DeckungXFläche macht für eine Art bei sehr kleinen Beständen Sinn, z.B. zu Beginn nach Neu-Etablierung. Ist der AP aber erfolgreich und die Art wächst auf grösseren Flächen in wechselnder Dichte, wird diese Einheit sehr mühsam zu erfassen. Irgendwann wäre es vermutlich viel einfacher, einfach den Bestand schätzen zu können.

Wird eine Einheit als zielrelevante Einheit für einen AP verwendet, wäre ein solcher Wechsel aber verheerend: Die Zahlen davor und danach können nicht mehr verglichen werden.

**Comment by rebeccakurz** [comment]
Also damit wir alle vom gleichen sprechen: Es gibt ja bereits die Zähleinheit "Deckung (%)" und Fläche (m2). 
Neu wäre die Zähleinheit "DeckungXFläche". Diese würde man ergänzend zu "Deckung" und "Fläche" angeben und sie wäre dann zielrelevant, weil vergleichbar. Wir denken nun, dass man es selber ausrechnen kann, und dann bei DeckungXFläche einfach einen Wert eingibt, dann müsste die Datenbank nichts rechnen. 

Bei den EKF wird diese Zähleinheit wohl nicht gebraucht werden, da es sich eher um Spezialfälle, bzw. schwierig zu erfasssende Arten handelt, die nicht von Freiwilligen kontrolliert werden. 

Die Frage nach dieser neuen Einheit kam explizit bei der Erstellung eines neuen Aktionsplans auf. Der Artverantwortliche ist sich also bewusst (hoffentlich), dass dann immer mit dieser Einheit gearbeitet werden muss. Auch die Ziele werden explizit mit dieser Einheit ausgearbeitet. 

Aus Sicht des Artverantwortlichen wäre es wichtig, dass auch kleine Einheiten in der FloraDB erfassbar sind, also z.B. 0.1 (m2) oder 0.03 (m2). Damit wären wir wieder bei der Frage der Dezimalzahlen. Ist das (als Erweiterung) umsetzbar oder wird das eher schwierig?

**Comment by barbalex** [comment]
> Wir denken nun, dass man es selber ausrechnen kann, und dann bei DeckungXFläche einfach einen Wert eingibt, dann müsste die Datenbank nichts rechnen

Dann braucht es keine Erweiterung und kann (wenn nötig) auch in den EKF-Formularen benutzt werden.

**Comment by barbalex** [comment]
Nur damit ihr euch bewusst seid:

Wenn in einem AP DeckungXFläche als zielrelevante Einheit gewählt wird, kann bei Massnahmen die zielrelevante Einheit nicht automatisch gesetzt werden. Sie muss dann manuell gesetzt werden. Grund: Fläche gibt es in der Massnahme. Aber die Deckung nicht.

Und es gibt (bisher) keine Qualitätskontrolle, die prüft, ob die zielrelevante Einheit in Massnahmen gesetzt wurde.

**Comment by rebeccakurz** [comment]
Das ist uns jetzt, nach deinem Hinweis, bewusst.
Eine Qualitätskontrolle scheint uns zum jetzigen Zeitpunkt noch mehr Nachteile als Vorteile zu haben. (Bei einer Art ist die zielrelevante Zähleinheit "blühende Triebe". Das ist ja ebenfalls keine Massnahmenzähleinheit und kann bei den Auspflanzungen nicht aufgenommen werden. Hier gäbe es dann jedes Mal eine Fehlermeldung; und bei den allermeisten Arten wird die zielrelevante Einheit ja automatisch aufgenommen)

**Comment by rebeccakurz** [comment]
gemacht
