### ISSUE TITLE
Server-Ausfall

### ISSUE THREAD

**Issue by barbalex** [barbalex/apf2#523]
@kmarti @rebeccakurz 

Wir hatten wieder einen Hosting-bedingten Server-Ausfall von 17.30 bis 17.45. Wenn ich nicht (in den Ferien) manuell eingegriffen wäre würde jetzt noch nichts gehen.

Diesmal hat es 5 von 6 Projekten, die ich auf DigitalOcean hoste getroffen!

Ich fühle mich bei DigitalOcean nicht mehr wohl. Wir müssen unbedingt so bald wie möglich migrieren.

**Comment by rebeccakurz** [comment]
Hoi Alex
Das ist wirklich gar nicht gut... So viel ich weiss, ist Karin nun fertig mit dem Jahresbericht, vielleicht könnte die Migration daher schon früher stattfinden? Allerdings wirst du das ja nicht in deinen Ferien machen wollen... Daher würde es bei Anfangs März bleiben?

**Comment by barbalex** [comment]
Ja, ich denke auch

**Comment by rebeccakurz** [comment]
Also aus Sicht von Karin wäre eine Migration ab jetzt möglich, die Jahresberichte sind abgegeben. 
Also kannst du eigentlich bestimmen, wann es für dich am besten passt und mir dann gerne Bescheid geben, damit ich die Artverantwortlichen über den Unterbruch informieren kann.

**Comment by barbalex** [comment]
@kmarti @rebeccakurz
Habe soeben auf einen neuen Server bei einem anderen Hosting-Provider migriert. Scheint alles zu klappen. Hoffen wir auf weniger Ausfälle 🙏
