### ISSUE TITLE
Dezimalstellen für Anzahl in Zählungen

### ISSUE THREAD

**Issue by barbalex** [barbalex/apf2#524]
@rebeccakurz schrieb [hier](https://github.com/barbalex/apf2/issues/522#issuecomment-1042798424):

> Aus Sicht des Artverantwortlichen wäre es wichtig, dass auch kleine Einheiten in der FloraDB erfassbar sind, also z.B. 0.1 (m2) oder 0.03 (m2). Damit wären wir wieder bei der Frage der Dezimalzahlen. Ist das (als Erweiterung) umsetzbar oder wird das eher schwierig?

**Comment by barbalex** [comment]
Das ist möglich. Allerdings wird der Feldtyp von der Datenbank über die Schnittstelle an die App weitergegeben, d.h. er muss an drei Orten gleichzeitig verändert und koordiniert live gesetzt werden. Sonst meldet die App beim Aufstarten nur Fehler.

Und das Feld wird App-seitig in einigen Formularen, Views, Abfragen und Exporten verwendet. An all diesen Stellen muss der Typ angepasst werden. Da es keine automatische Methode gibt, diese Orte alle zu finden, braucht es einige Recherche und Tests. Es ist auch gut möglich, dass einzelne dieser Orte erst nach live-Schaltung der Änderung gefunden werden, d.h. es kann für die Benutzter Fehler geben, welche nachträgliche kurzfristige Korrekturen erfordern.

Das gibt also Anpassungen an einigen Dutzend Stellen im Code.

Müssten auch andere Felder von Integer (Ganzzahl) auf Dezimal angepasst werden?
- z.B.: Massnahme: Fläche
- gibt es mehr?

Der Aufwand ist nur grob schätzbar. Liegt wohl in der Grössenordnung von 5 bis 6 Stunden.

**Comment by rebeccakurz** [comment]
Uns ist jetzt auch nur die Fläche (bei den Massnahmen und den Zählungen) und die neue Zähleinheit FlächeXDeckung eingefallen, wo Dezimalstellen möglich sein sollten. 
Gerne kannst du das als Erweiterung budgetieren und dann können wir es an der Sitzung mit Lieni und Anna (hoffentlich) absegnen lassen.

**Comment by barbalex** [comment]
Angepasst würden also diese zwei Felder:
- Zählung: Anzahl
- Massnahme: Fläche

Du hast "die Fläche bei den Zählungen" geschrieben. Das Feld "Anzahl" wird aber von allen Zähleinheiten benutzt. Daher könnten künftig alle mit Dezimalstellen erfasst werden, nicht nur die Fläche.

Das heisst nicht, dass künftig alle Anzahlen mit Dezimalstellen erfasst werden _müssen_.

Allerdings heisst es auch: Überall, wo das Feld angezeigt wird, kann es potentiell als Dezimalzahl angezeigt werden (weil es eine ist). Und wenn das nicht erwünscht ist, könnte das zusätzlichen Aufwand geben. Beispiel: 1 könnte je nach Abfrage/Formular/Export künftig auch als 1.0 erscheinen.

**Comment by barbalex** [comment]
Ist implementiert
