### ISSUE TITLE
Meldung: Seite reagiert nicht mehr. Wenn alle TPop aller Arten gleichzeitig in der Karte angezeigt werden

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#525]
Hoi Alex
Ich hatte nun schon ein paar mal das Problem, dass die APFlora-Seite nicht mehr reagiert hat, wenn ich alle Teilpopulationen aller Arten in einem bestimmten Gebiet anzeigen lassen wollte. 
Es kommt dann folgende Meldung:
![Bildschirmfoto 2022-02-23 um 08 24 41](https://user-images.githubusercontent.com/30288503/155282853-c209e55e-46e0-4fdc-abae-0162f10a1f3d.png)
Wenn man dann auf "Warten" klickt, passiert nichts. Wenn ich auf Verlassen drücke, kommt diese Meldung:
![Bildschirmfoto 2022-02-23 um 08 49 14](https://user-images.githubusercontent.com/30288503/155283085-9e4dbba6-cce3-42ff-acea-516ccdcf5ff0.png)

Könntest du dir das vielleicht mal anschauen? Eilt aber nicht.

**Comment by barbalex** [comment]
Ja, das ist leider zu erwarten. Ich habe gestaunt, dass es bei mir im Prinzip recht gut funktioniert, wenn auch sehr langsam. Was logisch ist, weil zehntausende Datensätze beim Server abgeholt, lokal aufbereitet und in der Karte dargestellt werden müssen.

Diese Funktion könnte auch ein ausgereiftes GIS-System fordern.

Vermutlich klappt es bei dir schlechter, weil dein PC weniger leistungsfähig ist als meiner.

Aber wie gesagt: Das würde vermutlich auch passieren, wenn du so viele Daten im GIS aufrufen würdest.

Was ich machen könnte:
1. Die Darstellung auf ein Maximum von Datensätzen begrenzen
2. Bei der Darstellung geografisch filtern, auf den gewählten Ausschnitt
3. Damit würden Pop und TPop aller Arten nur dargestellt, wenn man einen kleineren Ausschnitt wählt
4. Dieses Verhalten ist nicht besonders intuitiv und muss dem Benutzer auf geeignete Weise kommuniziert werden

Das ist recht komplex. Ähnliches passiert beim Export. Dort funktioniert es aber besser, weil:
1. Die Benutzerin zuvor selber den geografischen Filter bewusst gesetzt hat
2. Die Daten nicht alle in der Karte dargestellt werden müssen

Das Einzige, das wirklich super funktionieren würde, wäre, wenn die Aufbereitung für die Karte (geografische Gruppierung) schon auf dem Server passieren würde. Und daher nur noch die Gruppen übermittelt werden müssten. Das fordert dann dafür den Server. Und weil es dafür keine Werkzeuge gibt, müsste ich es aufwändig selber programmieren. Das ginge in die Dutzenden von Stunden Aufwand. Ist daher nicht realistisch.

**Comment by barbalex** [comment]
Was auch noch nützen könnte: Eine Benutzerführung, die versucht, die Daten nur zu laden, wenn ganz bewusst gewollt:

1. Navigiert eine Benutzerin aus einer Art heraus, würden normalerweise automatisch alle Arten geladen, wenn die Karte offen und die Darstellung von Pop oder TPop eintschaltet ist. Neues Verhalten: Die Arten werden nicht geladen. Stattdessen erscheint in der Layer-Auswahl ein Hinweis, wo man mit einem Klick das Laden auslösen kann.
2. Ist keine Art aktiv und die Benutzerin aktiviert einen Pop oder TPop Layer in der Karte, würden normalerweise die Daten aller Arten geladen. Neues Verhalten: Wie oben, d.h. gleich darunter kommt die Nachfrage, ob die Benutzerin das wirklich will. Erst nach Bestätigung dieser Nachfrage, werden die Daten geladen

**Comment by rebeccakurz** [comment]
Das wäre sicher eine Überlegung wert. Ich habe mir nun angewöhnt, entweder die Karte auszuschalten, wenn ich sie nicht brauche oder dann die Arten im Strukturbaum jeweils nicht zu schliessen, wenn ich zu einer anderen Art wechseln will. 
Aber manchmal vergesse ich es wieder und dann ärgere ich mich, dass ich warten muss, bis alle Daten geladen sind. Daher wäre das vielleicht gar nicht so schlecht.

**Comment by barbalex** [comment]
Das sollten wir auf die Liste für dieses Jahr setzen.

**Comment by barbalex** [comment]
Ziele:

1. Navigiert eine Benutzerin aus einer Art heraus, würden normalerweise automatisch alle Arten geladen, wenn die Karte offen und die Darstellung von Pop, TPop oder Beob eintschaltet ist. Neues Verhalten: Die Arten werden standardmässig nicht geladen. Stattdessen erscheint in der Layer-Auswahl ein Hinweis, wo man mit einem Klick das Laden auslösen kann.
2. Ist keine Art aktiv und die Benutzerin aktiviert einen Pop oder TPop Layer in der Karte, würden normalerweise die Daten aller Arten geladen. Neues Verhalten: Wie oben, d.h. gleich darunter kommt die Nachfrage, ob die Benutzerin das wirklich will. Erst nach Bestätigung dieser Nachfrage werden die Daten geladen

Rahmenbedingung: Funktioniert kaum gut, wenn auf das Verlassen einer Art reagiert wird - weil dann das Laden der Daten bereits ausgelöst wurde. Es muss also zuvor schon verhindert werden, dass beim Verlassen einer Art die Daten geladen werden.

Umsetzung:

- Neuer state `showApfLayersForMultipleAps`: Standardwert `false`
- In der Karte werden die apflora-eigenen Layer (Pop, TPop, Beob) nur eingeblendet, wenn:
  - das Layer aktiv ist (wie bisher)
  - nur eine Art aktiv ist (neu) oder `showApfLayersForMultipleAps` den Wert `true` hat
- Im Layertool gibt es bei den apflora-eigenen Layer neu eine Option, die Layer auch dann anzuzeigen, wenn mehrere Arte aktiv sind. Diese Option steuert den Wert von `showApfLayersForMultipleAps`
- Diese Option ist auffällig hinterlegt, wenn ein Layer aktiv ist und  `showApfLayersForMultipleAps` den Wert `true` hat, noch auffälliger, wenn über eine Art hinaus navigiert wurde. Oder einfach anzeigen, wieviele Arten aktiv sind?
- Navigiert man mit eingeschalteten apflora-Layern und `showApfLayersForMultipleAps` `false` über eine Art hinaus, erscheint ein Hinweis, dass die Layer ausgeblendet wurden, man sie aber mit der Option im Layertool einschalten kann
- Navigiert man mit eingeschalteten apflora-Layern und `showApfLayersForMultipleAps` `true` über eine Art hinaus, erscheint ein Hinweis, dass alle Layer geladen werden, das eine Weile dauern kann und man das mit der Option im Layertool ausschalten kann

**Comment by barbalex** [comment]
Ist in v1.83.0 implementiert
