### ISSUE TITLE
Gemeinde automatisch ausfüllen: wird immer "Zürich" eingesetzt

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#526]
Hoi Alex

Die AV haben mir gerade noch gemeldet, dass wenn man bei einer Teilpopulation die Gemeinde automatisch ausfüllen lässt, indem man auf das Fadenkreuz klickt, dass dann immer "Zürich" eingefüllt wird, egal in welcher Gemeinde man sich befindet. 
Habe das gerade auch noch bei Abies alba ausprobiert und dort dasselbe festgestellt. 
Könntest du dir das mal anschauen?
Noch ein paar Screenshots dazu:
![Bildschirmfoto 2022-02-23 um 14 12 55](https://user-images.githubusercontent.com/30288503/155327438-7fa20dba-5f21-44e9-a33b-e1280003543b.png)
![Bildschirmfoto 2022-02-23 um 14 13 41](https://user-images.githubusercontent.com/30288503/155327486-7dd732e6-1b88-4727-8d8b-b5302f433cd6.png)
![Bildschirmfoto 2022-02-23 um 14 16 39](https://user-images.githubusercontent.com/30288503/155327536-ed7589dc-147c-49ee-bfa1-903fc437a831.png)

**Comment by barbalex** [comment]
Ist in Version 1.68.6 korrigiert. Danke für die Meldung. Sorry für meinen Fehler

**Comment by rebeccakurz** [comment]
Danke!
