### ISSUE TITLE
Import von Info Flora Beob: Schon früher importierte: aktuelle Daten verwenden

### ISSUE THREAD

**Issue by barbalex** [barbalex/apf2#527]
Bisher haben wir jeweils nur diejenigen Daten importiert, die wir noch nie erhalten hatten. Ich bin der Meinung wir sollten einen Schritt weiter gehen:

1. Beobachtungen importieren, die wir noch nie erhalten haben (wie bisher)
2. Bei Beobachtungen, die wir schon erhalten haben die Daten von Info Flora mit den aktuellen ersetzen

Damit sind alle Daten im aktuellen Format, mit den jetzt verfügbaren Feldern (d.h. inklusive neu gelieferten). Und falls Info-Flora-seitig Anpassungen vorgenommen wurden, würden diese auch bei uns sichtbar.

Aber das ist eine Erweiterung bzw. einmaliger Mehraufwand (für die Implementierung) von ca. 4 Stunden. Später kann der einmal aufgebaute SQL-Code wiederverwendet werden, d.h. der Mehraufwand ist dann klein.

**Comment by rebeccakurz** [comment]
Hoi Alex
Wenn wir bereits erhaltene Beobachtungen mit den aktuellen von InfoFlora ersetzen würden, würden dann nicht die bereits zugeordneten Beobachtungen "überschrieben" werden? Oder würden sie zugeordnet bleiben, aber einfach aktualisiert werden?

**Comment by barbalex** [comment]
Sie würden zugeordnet bleiben, aber aktualisiert werden.

**Comment by barbalex** [comment]
Ist umgesetzt
