### ISSUE TITLE
Sonderzeichen

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#53]
Ich fände es wichtig, dass es z.B. eine Liste gäbe mit Sonderzeichen, die nicht als Eingaben akzeptiert werden (/, %, ;). Es kommt zwar jeweils eine Fehlermeldung, doch die Einträge werden nicht gleich wieder gelöscht, sondern sind einfach beim nächsten Mal aufrufen verschwunden. Und es werden nicht nur die Sonderzeichen gelöscht, sondern die gesamte Eingabe.

**Comment by rebeccakurz** [comment]
Fehlermeldung bei Eingabe von Prozentzeichen in Feld "Gefährdung". 

![bildschirmfoto 2017-09-01 um 08 55 23](https://user-images.githubusercontent.com/30288503/29958498-5bdd7dec-8ef3-11e7-8d81-d6c83dc7aac5.png)

**Comment by rebeccakurz** [comment]
Auch bei der Eingabe eines Schrägstriches (/) im Feld "Flurname" gibt es eine Fehlermeldung.
(Neu erstellte Teilpopulation)
![bildschirmfoto 2017-09-01 um 11 00 40](https://user-images.githubusercontent.com/30288503/29962872-0bb24390-8f05-11e7-8ea9-5c9f82cbc068.png)

**Comment by barbalex** [comment]
Ich glaube, das Problem mit den Sonderzeichen ist gelöst :-)
