### ISSUE TITLE
neue QK: nicht relevant für AP-Bericht, Grund: Historisch und ausserkantonal

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#530]
Hoi Alex

Beim Erstellen des Exports für das WebGISBun ist mir aufgefallen, dass es sehr viele Teilpopulationen gibt, welche ausserhalb des Kantons Zürich liegen, aber nicht als ausserkantonal bezeichnet sind. (Eigentlich werden die ausserkantonalen bei diesem Export rausgefiltert, aber wenn sie nicht als ausserkantonal bezeichnet sind, geht das natürlich nicht.)
Der Grund dafür ist wahrscheinlich folgender: Es handelt sich um Teilpopulationen, die ausserkantonal _und_ historisch sind. In unserer Anleitung steht eigentlich: 
_Bei historischen, ausserkantonalen Populationen ist der Status ausserkantonal zu verwenden._
Das scheint aber leider nicht immer befolgt zu werden. 

Daher wollten wir fragen, ob es möglich ist, eine neue Qualitätskontrolle zu erstellen, die genau das abfängt. Also die aufzeigt, wenn es Teilpopulationen gibt, die nicht für den AP-Bericht relevant sind, weil historisch, aber auch ausserhalb des Kt. ZH liegen. 
Parallel dazu würde ich gerne in der FloraDB beim Info-Text beim Grund für AP-Bericht (Nicht-)Relevanz das auch noch einfügen. Also das hier zusätzlich stehen würde: _Bei historischen, ausserkantonalen Populationen ist der Status ausserkantonal zu verwenden.
<img width="1119" alt="Bildschirmfoto 2022-04-06 um 09 43 58" src="https://user-images.githubusercontent.com/30288503/161922786-62ac6bbb-0ec1-4a5e-b3b5-9753274fce82.png">
_

**Comment by barbalex** [comment]
> Parallel dazu würde ich gerne in der FloraDB beim Info-Text beim Grund für AP-Bericht (Nicht-)Relevanz das auch noch einfügen. Also das hier zusätzlich stehen würde: _Bei historischen, ausserkantonalen Populationen ist der Status ausserkantonal zu verwenden.

Ist in Version 1.68.14 implementiert.

**Comment by rebeccakurz** [comment]
Hoi Alex
Vielen Dank für das Implementieren des Info-Textes. 
Ich glaube ein separates Feld für die Tatsache "ausserkantonal" wäre gar nicht schlecht. Könnte dieses dann in allen Exporten eingeführt werden? Manchmal wäre es sehr praktisch, wenn die ausserkantonalen Populationen/Teilpopulationen rausgefiltert werden könnten. 

Dann wäre eine solche Qualitätskontrolle wahrscheinlich nicht mehr nötig.

**Comment by barbalex** [comment]
> Könnte dieses dann in allen Exporten eingeführt werden?

Ja

**Comment by rebeccakurz** [comment]
Reihenfolge geändert; momentan keine weiteren Massnahmen nötig
