### ISSUE TITLE
Beobachtung in EK umwandeln?

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#531]
Beim Zuordnen der Beobachtungen kam noch die Frage auf, ob es möglich wäre, dass aus einer Beobachtung direkt eine Feldkontrolle oder eine Erfolgskontrolle Freiwillige erstellt werden könnte? Also dass man mit einem Befehl bei der entsprechenden Teilpopulation eine Kontrolle erstellen könnte, bei der dann gleich Datum, Beobachter, Anzahl etc. eingefüllt werden würde?

**Comment by barbalex** [comment]
Macht das Sinn?

Feldkontrollen sind nicht dasselbe. Sie dienen der Berichterstattung im Projekt. Und genau deshalb gäbe es auch Probleme. Z.B. werden Feldkontrollen als Beobachtungen exportiert. Was dann bei Info Flora zur Vervielfachung gleicher Beobachtungen führen würde.

Wieso möchte man das?

Ich frage, weil: Den Nutzen sollten wir auf anderem Weg erreichen, ohne Beobachtungen zu vervielfachen. Ich kann mir vorstellen, dass das eine relativ grosse Sache ist. Was nicht heisst, dass sich der Aufwand nicht lohnt. Darum die Frage wieso.

**Comment by rebeccakurz** [comment]
ähnlich wie #585 
Aufwand grösser als Nutzen
