### ISSUE TITLE
Taxonomie ändern: Leerer Eintrag entsteht bei AP-Arten

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#532]
Hoi Alex
Wir wollten mit dem Ändern der Taxonomie der Nicht-Aktionsplanarten in der FloraDB beginnen. Dabei ist uns aufgefallen, dass wenn man den Namen einer Art von der Quelle "InfoFlora 2005" auf "DB-TAXREF 2017" ändert, das neue Taxon auch gleich bei "AP-Arten" im Strukturbaum eingesetzt wird (was super ist!). Leider wird dabei aber auch ein zusätzlicher, leerer Datensatz bei "AP-Arten" erzeugt (siehe Screenshot). 
Könntest du dir das mal anschauen?
![Bildschirmfoto 2022-04-14 um 15 24 40](https://user-images.githubusercontent.com/30288503/163401604-cdb7a4de-dd6d-4482-86cd-5f5f16bc4a5e.png)

**Comment by barbalex** [comment]
Danke für die Meldung. Habe den entsprechenden Trigger korrigiert. Sollte nun korrigiert sein.

**Comment by rebeccakurz** [comment]
Danke!
