### ISSUE TITLE
Qualitätskontrolle ändern: Populationen mit Bericht abnehmend ohne Teil-Population mit Bericht abnehmend

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#533]
Hoi Alex

Aufgrund von einem Hinweis von Karin Sartori haben wir die QK: Populationen mit Bericht abnehmend ohne Teil-Population mit Bericht abnehmend nochmals durchgedacht und sind zu dem Schluss gekommen, dass der Populations-Bericht auch dann abnehmend sein kann, wenn keine der Teilpopulationen den Bericht abnehmend hat, nämlich dann, wenn einer der Teilpopulationsberichte "erloschen/nicht etabliert" oder "unsicher" ist. 

Bei Karin wäre das der Fall bei folgender Situation:
2 Tpop: 
- 1 Tpop dieses kontrolliert: als erloschen deklariert
- 1 Tpop letztes Jahr kontrolliert: noch aktuell
deshalb ist bei der erloschenen Tpop der Bericht „erloschen“
die ganze Pop jedoch einfach abnehmend, da es ja noch eine Tpop gibt (aber durch die erloschene Teilpopulation nun weniger Pflanzen vorhanden sind).

Die Qualitätskontrolle basiert ja auf folgender Matrix: 
<img width="368" alt="grafik" src="https://user-images.githubusercontent.com/30288503/165084032-1e3a7baa-041a-479d-af45-0b481bf66e4f.png">
Wir würden die QK nun aber gern anpassen, dass sie wie folgt lautet: 
"Populationen mit Bericht abnehmend ohne Teil-Population mit Bericht abnehmend oder erloschen/nicht etabliert oder unsicher". Also das mindestens eine der Teilpopulationen einen abnehmenden oder erloschenen/nicht etablierten oder unsicheren Bericht hat. 

Stimmst du unseren Überlegungen zu? Könntest du die QK entsprechend anpassen?

**Comment by barbalex** [comment]
Ja, scheint Sinn zu machen. Ist 1 bis 1.5 Stunden Arbeit. 

Erweiterungen sind aktuell nicht finanziert. Bezüglich der Aufträge ist nichts mehr gelaufen. Ich bin nicht gewillt, noch mehr voraus zu arbeiten, solange ich von der FNS keine klaren Signale erhalte.

Diese dauernde Verschiebung der Auftäge führt zu weiterem Mehraufwand: Man muss alles mehrmals diskutieren und sich eindenken. Darum muss ich diese Erweiterung auch auf 2 Stunden veranschlagen statt die 1 bis 1.5, die es sonst gäbe.

**Comment by rebeccakurz** [comment]
Hoi Alex
Bei den Qualitätskontrollen bin ich jetzt noch ein paar mal über diese Fehlermeldung gestolpert. 
Kannst du nun abschätzen, ob diese zwei Stunden im Auftrag dieses Jahres noch drinliegen?

**Comment by barbalex** [comment]
Das haben wir nicht in die Offerte vom Mai oder diejenige vom September aufgenommen

**Comment by rebeccakurz** [comment]
Dann nehmen wir das als Erweiterung für die nächste Offerte, okay?

**Comment by barbalex** [comment]
👍

**Comment by barbalex** [comment]
Toll, wie du die Labels setzt

**Comment by barbalex** [comment]
Ist implementiert (braucht keine neue Version der App)
