### ISSUE TITLE
Qualitätskontrolle: Teilpopulation: Die Nummer ist mehrdeutig

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#534]
Hoi Alex
Bei dieser QK ist mir aufgefallen, dass irgendetwas komisch ist. Beispiel Falcaria vulgaris, Population 21. In der QK erscheint diese Meldung:
![Bildschirmfoto 2022-04-27 um 08 36 23](https://user-images.githubusercontent.com/30288503/165456716-de39b13a-2adc-42f3-a696-4e998929fce2.png)
Nun wurde zwar die Nummer 21.4 zweimal vergeben, bei den restlichen Teilpopulationen stimmt es aber. Wiese erscheinen diese dann auch in der Fehlermeldung?
Könntest du dir das mal anschauen?
Danke!

**Comment by barbalex** [comment]
Danke für die Meldung. Die entsprechende Abfrage habe ich korrigiert. Sollte ab sofort wirksam sein.

**Comment by rebeccakurz** [comment]
Danke!
