### ISSUE TITLE
Export Beobachtungen: Alle zugeordneten Beobachtungen

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#535]
Hoi Alex
Wenn ich den Export aller zugeordneter Beobachtungen mache, fehlen leider einige der Beobachtungen. 
Beispiel Cypripedium calceolus, Teilpopulation 8.1: In der FloraDB hat es hier 5 zugeordnete Beobachtungen. Im Export erscheint aber nur eine davon. Oder bei TPop 17.4 erscheinen nur zwei der drei zugeordneten Beobachtungen. Oder TPop 27.2: nur drei von fünf Beobachtungen. 
Könntest du dir das mal anschauen?

**Comment by barbalex** [comment]
Das hatte mit den AP-Arten zu tun.
Ist in Version 1.68.18 korrigiert.
Danke für die Meldung.
