### ISSUE TITLE
Diskrepanz zugeordnete Beobachtungen Strukturbaum - Karte

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#536]
Hoi Alex
Habe von den Artverantwortlichen eine Meldung bekommen, dass es z. T. eine Diskrepanz der Anzahl der zugeordneten Beobachtungen zwischen dem Strukturbaum und der Karte (ersichtlich durch die Zuordnungs-Linien) gibt. 
Beispiel: Pulsatilla vulgaris, TPop 108.1 (siehe Screenshot)
Strukturbaum: 1 Beobachtung zugeordnet
Karte: mindestens 4 Beobachtungen zugeordnet
![FloraDB Beobachtungen](https://user-images.githubusercontent.com/30288503/166692689-3e5db019-c69f-4fe6-a061-4868d8ce1bc3.JPG)
Könntest du dir das mal anschauen?

**Comment by barbalex** [comment]
Zoomt man ganz rein, sieht man, dass die Zuordnungslinien knapp neben die TPop 108 führen:
<img width="298" alt="2022-05-06_14h44_12" src="https://user-images.githubusercontent.com/669783/167140457-346c8ec4-110a-4cd7-a58d-6769a5aade25.png">

Daher bin ich einer einzelnen Zuordnung nachgegangen.

Das ist - ehm - etwas kurios:
<img width="793" alt="2022-05-06_15h03_22" src="https://user-images.githubusercontent.com/669783/167137037-79a7c579-6428-4933-8eec-90b631c8cdf9.png">

Ist leider sehr aufwändig, dieser Sache nachzugehen. Ich muss wohl eine komplexe Abfrage schreiben, welche filtert, wo Beobachtungen an TPops in AP's zugewiesen wurden, deren AP-Arten nicht die zugewiesene Art enthalten.

Wie konnte das passieren?

Damit eine Beob der falschen Art zugewiesen werden konnte, musste sie bei den nicht beurteilten Beobachtungen erscheinen. Oder eine TPop von Seseli "erschien" als Ziel der Zuweisung. 

Möglichkeiten, wie das passieren konnte:
- Ein technischer bzw. Programmier-Fehler
- Pulsatilla vulgaris war zwischenzeitlich (aus Versehen?) als AP-Art von Seseli annuum. Aber da Seseli annuum keine AP-Art ist wurden dort wohl nie Beobachtungen zugeordnet? Ist also unwahrscheinlich

Ich gehe möglichen Programmierfehlern nach.

**Comment by barbalex** [comment]
Hier die Liste der 330 Beobachtungen, die einem AP zugeordnet wurden, deren AP-Arten die Art gemäss Beobachtung nicht enthalten:
[beob_zugeordnet_art_falsch.xlsx](https://github.com/barbalex/apf2/files/8641530/beob_zugeordnet_art_falsch.xlsx)
(musst du von github.com herunterladen, kommt im email, dass dich über meinen Kommentar informiert nicht mit)

Kann es sein, dass mindestens ein Teil dieser Fälle irgend einen Zusammenhang mit falsch bestimmten Beobachtungen haben? Mir fällt auf, dass ein überraschend grosser Teil Lycopodiella inundata bzw. Rhynchospora fusca betrifft.

**Comment by barbalex** [comment]
Ich habe jetzt allen Code kontrolliert, wo:
- TPop für die Zuordnung ausgewählt werden
- Die nächste TPop gewählt wird (nach Ziehen auf der Karte)
- Anschliessend die Daten aktualisiert werden

Sieht alles gut aus. Ich kann mir nicht vorstellen, was hier zu einer Zuordnung in einem ungewollten AP führen könnte.

**Comment by barbalex** [comment]
Habe den Code geprüft, der bestimmt, welche Beobachtungen im Navigationsbaum erscheinen. Scheint auch in Ordnung.

Etwas ist mir aber aufgefallen. Eigentlich ein anderes Problem, aber es kann solche Phänomene verursachen:
3 Arten, welche AP-Art eines AP sind, wurden _zusätzlich_ als eigener AP erfasst:

apart_artname | ap_artname
-- | --
Info Flora 2005: Cardamine palustris   (Wimm. & Grab.) Peterm. | DB-TAXREF (2017): Cardamine dentata Schult.
Info Flora 2005: Cardamine palustris   (Wimm. & Grab.) Peterm. | Info Flora 2005: Cardamine palustris (Wimm. & Grab.) Peterm.
Info Flora 2005: Crassula rubens (L.) L. | DB-TAXREF (2017): Sedum rubens L.
Info Flora 2005: Crassula rubens (L.) L. | Info Flora 2005: Crassula rubens (L.) L.
Info Flora 2005: Orobanche alsatica   Kirschl. s.l. | DB-TAXREF (2017): Orobanche alsatica Kirschl. subsp. alsatica
Info Flora 2005: Orobanche alsatica   Kirschl. s.l. | Info Flora 2005: Orobanche alsatica Kirschl. s.l.

[art_ist_mehrfach_ap_art.xlsx](https://github.com/barbalex/apf2/files/8643473/art_ist_mehrfach_ap_art.xlsx)

Das macht keinen Sinn. Oder?

In diesen Fällen werden die Beobachtungen der jeweiligen AP-Art in beiden AP's aufgelistet. Und können auch in beiden einer TPop zugeordnet werden. Sind sie einmal zugeordnet, verschwinden sie dann aus dem anderen AP.

Ich wollte ursprünglich verhindern, dass das möglich ist (einen eindeutigen Index auf die art_id der Tabelle apart setzen). Konnte aber Anfangs nicht, wegen des Wechsels der Taxonomien. Und jetzt kann ich es nicht, bevor diese drei Fälle von euch bereinigt wurden.

Diese drei Fälle sind aber nicht Ursache der 330 einem falschen AP zugewiesenen. Dort muss es andere Gründe geben.

**Comment by rebeccakurz** [comment]
Hoi Alex
Vielen Dank, dass du dem nachgehst.
Was ich noch dazu sagen kann: Der Artverantwortliche von Rhynchospora und Lycopodiella hatte in seiner Beobachtungstabelle durch einen Kopierfehler bei einigen Beobachtungen zu Lycopodiella die SISF-Nummer von Rhynchospora drin (oder umgekehrt). Wir haben dann abgemacht, dass er diese falsch zugeordneten Beobachtungen der anderen Art zuteilen soll und das auch so vermerkt hat bei der jeweiligen Beobachtung (bei: Bemerkung zur Zuordnung). In diesen Fällen wurde die Beobachtung also aktiv einer anderen Art zugeteilt. 
Die anderen Fälle kann ich mir aber nicht erklären. 
Das mit den drei Arten, welche AP-Art eines AP sind und zusätzlich als eigener AP erfasst wurden, muss ich mit Karin besprechen, wie wir da vorgehen wollen.

**Comment by rebeccakurz** [comment]
Also ich habe mir die Beobachtungen von Saxifraga granulata angeschaut, welche einer falschen Art zugeordnet sind. Es handelt sich, wenn ich mich recht erinnere, tatsächlich um Beobachtungen, die ich am 27.4. zugeordnet habe. 
Die Art, bei der die Beobachtungen fälschlicherweise zugeordnet wurde, hat auch immer eine Teilpopulation in unmittelbarer Nähe zu einer Teilpopulation von Saxifraga granulata. 
Also für mich schaut es wirklich so aus, dass ich die Beobachtung einer Teilpopulation von Saxifraga zuordnen wollte und die Beobachtung dann aber einer anderen Art mit einer Teilpopulation etwa am gleichen Ort zugeordnet wurde. 
Die meisten Zuordnungen habe ich über die Karte gemacht. 
Beispiel Gebiet Glattfelden, Nadelbändli: Theoretisch hätte ich alle Beobachtungen von Saxifraga der Teilpopulation 112.1 zuordnen wollen. Nun befindet sich aber eine der Beobachtungen bei der TPop 134.1 von Ophrys araneola, deren Teilpopulation nahe an der Saxifraga-Teilpopulation liegt.
Oder Beispiel Gebiet Glattfelden, Schneggen: Hier wurden zwei Beobachtungen von Saxifraga der Teilpopulation 27.27 von Potentilla leucopolitana zugeordnet und zwei Beobachtungen von Saxifraga der TPop 201.1 von Pulsatilla vulgaris. Diese drei TPops liegen sehr nahe beieinander (Pulvul: 2679583/1268770; Potleu: 2679583/1268769; Saxgra: 2679583/1268769). 
Könnte es vielleicht damit etwas zu tun haben?
![Bildschirmfoto 2022-05-11 um 11 11 53](https://user-images.githubusercontent.com/30288503/167815007-753be141-a1c9-42c1-8493-dd279aac35cd.png)
Ich habe auch noch am 5. Mai Beobachtungen von Saxifraga zugeordnet (hauptsächlich im Kt. SH) und auch da ist es anscheinend wieder passiert, dass eine Beobachtung von Saxifraga bei einer anderen Art (Rosa gallica) gelandet ist. Hier befinden sich die Teilpopulationen allerdings etwas weiter auseinander. An einer sehr ähnlichen Koordinate kann es daher wohl doch nicht liegen. 
Es gibt auch Fälle, wo Beobachtungen von Saxifraga einer Nicht-AP-Art zugeordnet wurden. Es scheint für mich schon an der räumlichen Nähe der Teilpopulationen zu liegen. 
Soweit mal meine Beobachtungen...

**Comment by rebeccakurz** [comment]
Was mir gerade auch noch aufgefallen ist: Unser Praktikant hat (vor allem im März glaube ich) sehr viele Beobachtungen von Cypripedium calceolus zugeordnet. Von dieser Art hat es aber in der Liste mit den falsch zugeordneten Beobachtungen keine Beobachtungen drin...

**Comment by barbalex** [comment]
Zwei Fragen:

1. Wenn du die Liste der falsch zugeordneten anschaust: Kannst du feststellen, ob sich das bei gewissen Personen (AV's) häuft? Das könnte uns einen Hinweis geben, ob es einen Zusammenhang mit deren PC's gibt.
2. Wenn die Beobachtungen ev. einer anderen Art zugewiesen wurden: Sind das Arten, mit denen die betreffende Person bzw. AV auch arbeitet? (dann hätten deren Beobachtungen immerhin kurz zuvor im Arbeitsspeicher sein können). Oder sind das z.T. Arten, mit denen diese Person gar nie arbeitet, d.h deren Beobachtungen auf ihrem PC gar nie in den Arbeitsspeicher geladen wurden? (du kannst das wohl am besten bei dir selbst beurteilen)

**Comment by rebeccakurz** [comment]
1. Es sind am meisten Arten von Regula Dickenmann (6), aber auch je drei von Anna Wunderli und Karin Sartori, je zwei von Evelyn Terzer und Christoph Käsermann und noch je eine von Tobias Liechti, Agnes Schärer, Charlotte Salzmann und mir. 
2. Also bei mir wurden die Beobachtungen zum Teil Arten zugeordnet, die ich glaube ich vorher noch nie gebraucht hatte, z.B. die Nicht-AP-Arten Aster amellus oder Viola canina subsp. schultzii. Aber auch AP-Arten, mit denen ich nichts zu tun habe wie Rosa gallica oder Orobanche gracilis. 
Auch bei den anderen Artverantwortlichen sind es z.T. Arten, wo ich sagen würde, dass sie nichts mit diesen zu tun haben, da sie z.B. aus einem anderen Set stammen.

**Comment by barbalex** [comment]
Du musst nicht mehr hirnen, ich habe den Fehler gefunden

**Comment by barbalex** [comment]
Ich habe am 3. Februar die Funktion, welche die nächste Teilpopulation ermittelt, wenn man auf der Karte zuordnet, stark optimiert. Sie benutzt jetzt PostGIS-Funktionen.

Dabei wurde ich wohl vom Werkzeug, dass die Daten abfragt überlistet (Apollo). Es speichert die Abfragen im Hintergrund zwischen. Und dazu verwendet es einfach eine ID, die sie in den Daten der Abfrage findet. 

Die hier verwendete Funktion retourniert die ID der TPop. Worauf Apollo die zwischengespeicherten Werte für die entsprechende Teil-Population ersetzt.

Wie genau sich das auswirkt und wie das dazu führen konnte, dass die Beobachtungen einer völlig falschen TPop zugeordnet werden konnte, kann ich nicht direkt nachvollziehen. Aber es ist klar, dass dieser Vorgang zu willkürlichen nicht nachvollziehbaren Resultaten führen _kann_.

Ich habe Apollo nun beigebracht, dass es die Daten aus der PostGIS-Funktion anders zwischenspeichern soll. Womit ich davon ausgehe, dass das nicht mehr passiert.

**Comment by rebeccakurz** [comment]
Okay, super hast du das herausgefunden. 
Das heisst wir können die falsch zugeordneten Beobachtungen in der Liste richtig zuordnen und dann sollte es wieder in Ordnung sein, richtig?

**Comment by barbalex** [comment]
Ja. Theoretisch könnte ich vermutlich eine Abfrage schreiben, welche sie automatisch der nächst-gelegenen TPop des richtigen AP's zuordnet. Aber ich bin nicht sehr zuversichtlich, dass das nicht recht häufig wieder falsch wäre...

**Comment by barbalex** [comment]
Hier noch eine Auswertung, die mich zu diesem Ergebnis gebracht hat und recht interessant ist:

Datum | Anzahl abweichende Arten | Bemerkungen
-- | -- | --
01.01.2021 | 9 |  
01.01.2022 | 9 |  
25.01.2022 | 9 |  
01.02.2022 | 9 |  
03.02.2022 |   | letzte Anpassung von nearest search: apById zur function!
07.02.2022 | 9 |  
10.02.2022 | 9 |  
11.02.2022 | 76 |  
12.02.2022 | 76 |  
13.02.2022 | 76 |  
28.03.2022 | 116 |  
29.03.2022 | 116 |  
30.03.2022 | 116 |  
01.04.2022 | 179 | Aktualisierung von Info Flora
04.04.2022 | 192 |  
13.04.2022 | 262 |  
06.05.2022 | 330 |  

Ich schau noch mal an, ob ich mehr herausfinde, was sich beim Aktualisieren der Info Flora Daten geändert hat.

**Comment by barbalex** [comment]
Hier die aktuelle Version von jetzt gerade (nur auf GitHub sichtbar, nicht im Email):
[2022 05 11.xlsx](https://github.com/barbalex/apf2/files/8669855/2022.05.11.xlsx)

**Comment by rebeccakurz** [comment]
Danke!

**Comment by barbalex** [comment]
Wenn du noch Fragen hast, nur zu. Ansonsten entschuldige ich mich für meinen Fehler und schliesse diesen Issue

**Comment by barbalex** [comment]
Seid ihr immer noch heftig am Zuordnen? ich werde jedenfalls in den nächsten Tagen die Abfrage wiederholen um kontrollieren zu können, dass das Problem wirklich behoben wurde. Die Anzahl einer fremden Art zugeordneten Beobachtungen sollte ja mit euren Korrekturen abnehmen. Sobald sie zunehmen sollte, melde ich mich.

**Comment by rebeccakurz** [comment]
Hm kann ich so gar nicht sagen, da es je nach Artverantwortlichem unterschiedlich ist. Denke aber, dass momentan eher weniger am zuordnen sind, auch da wahrscheinlich viel Feldarbeit ansteht.

**Comment by barbalex** [comment]
Hm. Zur Wiedergutmachung könnte ich noch eine Qualitätskontrolle spendieren, die meldet, wenn Beobachtungen einer der AP-Arten einem anderen AP zugeordnet wurden.

Oder stört das, weil es Fälle gibt, wo diese QK Ergebnisse liefert, bei denen der Fehler bei Info Flora liegt, bekannt ist und erst beim nächsten Import von apflora korrigiert wird? Falsch positive Qualitätskontrollen sind kaum gut.

**Comment by barbalex** [comment]
Ich werde in den nächsten Tagen und danach wöchentlich kontrollieren, ob die Anzahl ab- und nicht zunimmt. Habe Termine gesetzt.

**Comment by barbalex** [comment]
> Es sind am meisten Arten von Regula Dickenmann 

Sie wird mich wieder mal auf den Mond schiessen 😢

**Comment by rebeccakurz** [comment]
Bin mir nicht ganz sicher, ob eine solche Qualitätskontrolle viel bringen würde. 
Aber ist sicher gut, wenn du es noch eine Zeit lang beobachtest.

**Comment by barbalex** [comment]
Heute sind es noch 255 (von zuletzt 330)

**Comment by rebeccakurz** [comment]
Hoi Alex
Danke für das Update. Ich habe letzte Woche angefangen, die Zuordnungen zu bereinigen.

**Comment by barbalex** [comment]
Heute sind es 252

**Comment by barbalex** [comment]
Heute sind es 88

**Comment by rebeccakurz** [comment]
Also ich bin jetzt fast fertig mit dem Korrigieren der falsch zugeordneten Beobachtungen. Könntest du mir nochmals eine Excel-Tabelle schicken, mit den Beobachtungen, die jetzt noch einer anderen Art zugeordnet sind? 
Bei Pulsatilla hat nämlich die verantwortliche Person heute morgen die Populationsnummern geändert und jetzt weiss ich nicht, bei welcher Teilpopulation die falschen Beobachtungen zugeordnet sind. Und vielleicht habe ich auch noch ein paar verpasst. 
Was auch immer noch drin sein sollte sind Beobachtungen von Gladiolus communis, welche Gladiolus palustris zugeordnet wurden. Das wurde absichtlich so gemacht, da die Arten oft verwechselt werden.

**Comment by barbalex** [comment]
Voilà: [20022 05 19.xlsx](https://github.com/barbalex/apf2/files/8729669/20022.05.19.xlsx)

**Comment by rebeccakurz** [comment]
Vielen Dank!
Dann sind nun alle falsch zugeordneten Beobachtungen bereinigt. 
In der Liste sollten jetzt nur noch die von Gladiolus palustris/communis und eine von Lycopodiella inundata/Rhynchospora fusca sein, bei der Christoph Käsermann vermerkt hat, dass es sich hier um Rhynchospora handelt. 
Hoffe damit hat sich das erledigt 👍

**Comment by barbalex** [comment]
Jawohl, 10 Stück

**Comment by barbalex** [comment]
Immer noch diese 10

**Comment by barbalex** [comment]
Immer noch diese 10

**Comment by barbalex** [comment]
Immer noch diese 10

**Comment by barbalex** [comment]
Immer noch diese 10

**Comment by barbalex** [comment]
Es gibt jetzt eine Neue:
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/alexa/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/alexa/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
</head>

<body link="#0563C1" vlink="#954F72">



beob_artname | ap_art_artname | pop_nr | tpop_nr | beob_quelle
-- | -- | -- | -- | --
Info Flora 2005: Spiranthes aestivalis   (Poir.) Rich. (Sommer-Wendelähre) | Info Flora 2005: Cardamine palustris (Wimm. & Grab.) Peterm. | 10 | 3 | FloZ 2017



</body>

</html>

**Comment by barbalex** [comment]
In ein paar Minuten ist Version 1.76.4 live. Dort habe ich sichergestellt, dass die Abfrage, welche die nächste TPop sucht, überhaupt keinen cache verwendet.

Und: werde die Entwicklung weiter beobachten.

**Comment by barbalex** [comment]
Das ist absolut zum Haare raufen. Es gibt wieder mehr falsche Zuordnungen. Tauche wieder in dieses Problem ein.

**Comment by rebeccakurz** [comment]
Okay, das ist nicht gut. 
Kannst du mir die Liste mit den falsch zugeordneten Beobachtungen noch schicken? Vielleicht kann ich ein Muster erkennen.

**Comment by barbalex** [comment]
In v1.78.2 ist die alte Version wieder implementiert. Sie ist viel weniger elegant, lässt apollo aber keine Gelegenheit, alte Werte zu retournieren, Zwischenspeicher hin oder her.

Die oben gelieferte Liste der falschen Zuordnungen ist noch aktuell.

**Comment by rebeccakurz** [comment]
Also es betrifft ja hauptsächlich Potentilla inclinata und Spiranthes aestivalis. Anna hat am Freitag, 29.7. Beobachtungen von Potentilla zugeordnet und Evelyn am Donnerstag, 28.7. Beobachtungen von Spiranthes. 
Vielleicht hilft das weiter?

**Comment by barbalex** [comment]
Danke für die Info. Irgendwas von Apollo hat zu diesem wirren Verhalten geführt. Die neue Version nimmt Apollo diese Gelegenheit. Ich beobachte aber weiter, wie sich die Daten entwickeln.
