### ISSUE TITLE
Beobachtungen, die einer falschen Art zugeordnet wurden

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#537]
Hoi Alex
Auch wurde mir von den Artverantwortlichen gemeldet, dass es z.T. Beobachtungen gibt, die einer falschen Art zugeordnet sind/wurden. 
Beispiel Ophrys araneola, Teilpopulation 115.1, eine Beobachtung zugeordnet. Die zugeordnete Beobachtung gehört aber zu Pulsatilla vulgaris. (siehe Screenshot). 
![Bildschirmfoto 2022-05-04 um 15 41 12](https://user-images.githubusercontent.com/30288503/166695389-9ffd42a8-8c53-48f3-b2cf-07dd1b05cccd.png)

Hier kann ja nicht beim Import etwas schief gegangen sein oder? Diese Beobachtung müsste ja fast aktiv zugeordnet worden sein. Oder kannst du dir einen anderen Grund vorstellen? Wir haben nun schon zwei, drei solcher Fälle angetroffen, wo zugeordnete Beobachtungen einer anderen Art angehörten. 
Die bereits in der FloraDB vorhandenen (und z.T. zugeordneten Beobachtungen) wurden ja beim letzten Import aktualisiert. Könnte es sein, dass da etwas passiert ist?

**Comment by barbalex** [comment]
Duplikat von https://github.com/barbalex/apf2/issues/536#issuecomment-1119704190
