### ISSUE TITLE
Fehler bei Eingabe Datum

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#54]
Datum kann zwar eingegeben werden, verschwindet allerdings nachher einfach wieder. Das Jahr bleibt ausgefüllt. Bei der Eingabe des ersten Datums kam noch eine Fehlermeldung, nachher nicht mehr. Zum Teil ist das Datum bei einer neu erstellten Kontrolle auch einfach schon ausgefüllt mit dem zuletzt eingegebenen Datum!

**Comment by barbalex** [comment]
> Zum Teil ist das Datum bei einer neu erstellten Kontrolle auch einfach schon ausgefüllt mit dem zuletzt eingegebenen Datum!

Dieser Teil der Meldung ist sicher behoben.

Was den ersten Teil betrifft ("_Datum kann zwar eingegeben werden, verschwindet allerdings nachher einfach wieder_"), bin ich nicht sicher. Bitte testen und falls es immer noch passiert, neu melden. Mein Problem war, dass ich es nicht nachvollziehen konnte.
