### ISSUE TITLE
Export Populationen Letzte Zählungen und andere funktionieren nicht

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#540]
Hoi Alex
Ich wollte in der FloraDB den Export "Populationen Letzte Zählungen" machen. Dabei erschien folgende Fehlermeldung:
![Bildschirmfoto 2022-06-28 um 11 14 03](https://user-images.githubusercontent.com/30288503/176143129-0a56f26a-05d4-4e6e-ba5b-a94e9d8a23ab.png)
Der Export "Populationen" und "Teilpopulationen" funktioniert ohne Fehlermeldung. Aber beim Export "Populationen Aktuellste Zählung inkl. seither erfolgter Auspflanzungen" und beim Export "Teilpopulationen Letzte Zählung" erscheint die gleiche Fehlermeldung. 
Beim Export "Teilpopulationen Aktuellste Zählung inkl. seither erfolgter Auspflanzungen erscheint folgende Fehlermeldung: 
![Bildschirmfoto 2022-06-28 um 11 17 02](https://user-images.githubusercontent.com/30288503/176143826-b449dcce-f136-47d3-b01d-f4a3e22469b0.png)
Könntest du dir das mal anschauen?
Vielen Dank und liebe Grüsse
Rebecca

**Comment by barbalex** [comment]
Das war eine übersehene Folge der Umstellung des Formats der Anzahlen (neu mit Kommastelle). Ist korrigiert

**Comment by rebeccakurz** [comment]
Super, vielen Dank!

**Comment by rebeccakurz** [comment]
Hoi Alex

Es scheint bei den meisten Exporten wieder zu gehen, aber beim Export "Teilpopulationen Letzte Zählungen" scheint es immer noch ein Problem zu geben. Es erscheint folgende Fehlermeldung: 
![Bildschirmfoto 2022-06-28 um 12 55 56](https://user-images.githubusercontent.com/30288503/176162728-20374504-0160-4b5c-a5de-4071e49db78e.png)

**Comment by barbalex** [comment]
Das war komisch. Der Graphql-Server hat offenbar Streicheleinheiten gewünscht - habe ihn neu gestartet und jetzt klappt es wieder

**Comment by rebeccakurz** [comment]
Okay, ja komisch... Aber danke fürs anschauen.
