### ISSUE TITLE
Auswahl im Stammbaum, 2. Klick keine De-Selektion

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#55]
Es ist sehr verwirrend, dass ein 2. Klick auf ein Thema (z.B. Pop., oder Art) dieses nicht de-selektiert sondern dass dann das übergeordnete Thema selektiert und aktiv wird. Ich habe mich nach vielen Klicks halbwegs daran gewöhnt, falle aber doch immer wieder rein. Dieses Verhalten ist sehr ungewohnt, und wir denken, es könnte die Akzeptanz der Anwendung ziemlich herabsetzen. Könntest Du da irgendetwas tun das Abhilfe schaffen könnte?

**Comment by barbalex** [comment]
Versuchen wir mal, das Verhalten genau zu beschreiben:

1. Benutzer Navigiert von der Art über Populationen-Ordner, Population, Teilpopulationen-Ordner zu einer Teilpopulation
1. Benutzer deselektioniert jetzt die unterste aktive Ebene, also die Teilpopulation
1. Die Anwendung navigiert zur Population, d.h. eine Ebene höher, als wohin der Benutzer geklickt hat. Das ist wohl auch das, was der Benutzer erwartet

Das ist das, woran ich bei der Programmierung gedacht habe.

Aber ich glaube, ich habe jetzt verstanden, was du meinst:

1. Benutzer Navigiert von der Art über Populationen-Ordner, Population, Teilpopulationen-Ordner zu einer Teilpopulation
1. Benutzer klickt jetzt **mehr als eine Ebene weiter hoch**, z.B. in die Population
1. Die Anwendung navigiert zur Art. **Der Benutzer wollte aber die Population aktivieren**

Klickt ein Benutzer also auf einen bereits aktiven Knoten, sollte nicht immer wie heute der nächst höhere aktiviert werden. Ist der Knoten nicht der unterste in der aktiven Reihe, sollte eben der geklickte Knoten aktiviert werden.

Ist es das, was du meinst?

**Comment by barbalex** [comment]
uhm, viel besser

habe die Anpassung live geschaltet

vielen Dank für den super Input!!!!

**Comment by csalzmann** [comment]
Ich bin nicht ganz sicher, ob wir das gleiche verstehen.


Wenn ich auf ein Thema klicke (z.B. Populationen), dann möchte ich in diesem Thema bleiben. Oder - wenn ich ein 2. Mal drauf klicke, dass dieses Thema dann halt nicht mehr selektioniert ist rsp ich auf diesem Thema eine neue Selektion (Filter) eingeben möchte. Für uns ist es ein sehr ungewohntes Verhalten, dass das Programm automatisch checken soll, dass wenn ich ein zweites Mal auf ein Thema klicke (z.B. Populationen) auf einmal ein Thema höher in der Selektion aktiv ist (z.B. Arten).

Oder anders: Ich möchte nur, das ein Thema aktiv ist, wenn ich auf dessen Ebene klicke, und nicht weil ich eine Ebene darunter klicke.

Zuerst hatte ich das Gefühl, Du würdest das nun auch so verstehen. Aber die Datenbank reagiert immer noch anders:

OK ist es jetzt, wenn ich auf eine einzelne Pop klicke.
Nicht OK (eine höher springt es), wenn ich auf Teil-Populationen (springt zu Populationen filtern), Populationen (springt zu Arten filtern), Arten (springt zu Projekte filtern) klicke.





---------------------------------------------------------------
Charlotte Salzmann
Dr.sc.ETH
topos Marti & Müller AG
Idastr. 24
8003 Zürich
Tel. 044 451 52 55
salzmann@toposmm.ch

Di - Fr

**Comment by barbalex** [comment]
Hm. Manchmal bin ich wirklich sehr begriffsstutzig.

Also: Klickt man auf einen Knoten, ist dieser danach **immer** aktiv.

Ich hab das eher so wie eine Checkbox verstanden. Ist es aber eben nicht...

Ist es jetzt besser?

**Comment by csalzmann** [comment]
Ja!!!

Danke vielmals!


---------------------------------------------------------------
Charlotte Salzmann
Dr.sc.ETH
topos Marti & Müller AG
Idastr. 24
8003 Zürich
Tel. 044 451 52 55
salzmann@toposmm.ch

Di - Fr
