### ISSUE TITLE
Jahresbericht, BearbeiterIn wird in Maske abgeschnitten

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#56]
Beim Jahresbericht wird unterster Teil des Fensters mit der BearbeiterIn abgeschnitten (man kann auch nicht mehr weiterscrollen). Man kann die BearbeiterIn zwar noch im Halb-Blindflug eingeben, ist aber nicht schön. Siehe Vergleich V1/V2
![bildschirmfoto 2017-08-30 um 08 12 48](https://user-images.githubusercontent.com/6047564/29857901-46a3586e-8d5b-11e7-90ca-db85c738c9d1.png)
![bildschirmfoto 2017-08-30 um 08 13 58](https://user-images.githubusercontent.com/6047564/29857917-597db3c6-8d5b-11e7-8718-6f15bf7cb51f.png)

**Comment by barbalex** [comment]
Ich nehme an, du meinst, dass die Auswahlliste nicht sichtbar ist.

Das ist behoben und live geschaltet.
