### ISSUE TITLE
Export Massnahmen funktioniert nicht

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#560]
Der Massnahmen-Export funktioniert leider nicht, es erscheinen folgende Fehlermeldungen (siehe Screenshot):
![Bildschirmfoto 2022-07-20 um 15 18 11](https://user-images.githubusercontent.com/30288503/180026514-2d414176-035f-442d-bcef-1864a96074b9.png)

**Comment by barbalex** [comment]
Ist in Version 1.77.2 korrigiert
