### ISSUE TITLE
Strukturbaum: Massnahmen, Feldkontrollen, EKFs werden nicht immer angezeigt

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#561]
Wenn ich im Strukturbaum z.B. in einer Population mit mehreren Teilpopulationen bin und die eine TPop aktiv ist, dann werden im Strukturbaum bei der anderen TPop keine Massnahmen, Feldkontrollen oder EKFs angezeigt. Wenn ich dann auf diese andere TPop klicke, werden sie aber korrekt angezeigt.
![Bildschirmfoto 2022-07-20 um 10 38 36](https://user-images.githubusercontent.com/30288503/180028026-8230f7bf-0985-4093-a062-35f43275c508.png)
![Bildschirmfoto 2022-07-20 um 10 38 17](https://user-images.githubusercontent.com/30288503/180028093-6a69849b-1063-4244-8c47-5eaa7e90175e.png)

**Comment by barbalex** [comment]
Das ist die Wirkung des hierarchischen Filters. Wurde auf Ebene Art auf euren Wunsch hin eingeführt. Wenn ihr das auf Ebene Pop/TPop nicht wollt, entferne ich es dort wieder.

Ist dann allerdings nicht klar, was wo wie und wieso funktioniert?

**Comment by rebeccakurz** [comment]
Hm ich muss mir das nach meinen Ferien nochmals anschauen, jetzt ist es gerade viel zu heiss um noch zu überlegen...
Aber danke schon mal für die Rückmeldung, ich muss mich auch noch mit den neuen Filtern befassen.

**Comment by barbalex** [comment]
Dann sag ich jetzt lieber nicht, dass ich im Engadin bin...

**Comment by rebeccakurz** [comment]
Hoi Alex

Bist du noch im Engadin? Ist es dort wenigstens etwas kühler, als es im Mittelland für diese Woche angesagt ist?

Leider weiss ich nicht mehr genau, warum wir den hierarchischen Filter auf Ebene Art wollten. Auf dieser Ebene scheint er aber auch keine ungewollten Nebenwirkungen zu haben. 

Im Gegensatz dazu der hierarchische Filter auf Ebene Pop/TPop. Der ist sehr irritierend bei der Arbeit mit der FloraDB und hat glaube ich auch schon zu Problemen geführt. Ich mache noch einen neuen Issue mit einem Dokument von Anna Wunderli, das sie zusammengestellt hat mit Problemen, die beim Zuordnen von Beobachtungen aufgetreten sind. Ich denke, das hat ebenfalls mit dem hierarchischen Filter zu tun, was meinst du?
Ich würde also gerne diesen hierarchischen Filter auf Ebene Pop/TPop wieder entfernen.

**Comment by barbalex** [comment]
Bin noch in den Ferien aber schaue mir das wenn möglich nächste Woche an

**Comment by barbalex** [comment]
In Version 1.78.0 wurde der Hierarchiefilter auf Ebene Pop und TPop entfernt. Sollte in ein paar Minuten live sein
