### ISSUE TITLE
Karte: es werden nur die TPops der aktiven Population angezeigt

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#562]
Wenn ich im Strukturbaum eine Population oder Teilpopulation anwähle, dann wird in der Karte nur noch diese dargestellt und alle anderen Populationen/Teilpopulationen werden ausgeblendet.
![Bildschirmfoto 2022-07-20 um 18 01 19](https://user-images.githubusercontent.com/30288503/180029371-f18886bc-9240-406b-8c4e-7179d83847c9.png)
![Bildschirmfoto 2022-07-20 um 18 01 00](https://user-images.githubusercontent.com/30288503/180029407-c10ebed8-61be-4289-990f-ae93ee44f2d4.png)

**Comment by barbalex** [comment]
Das ist die Wirkung des Hierarchischen Filters. Siehe: https://apflora.ch/Dokumentation/Benutzer/Filter/

**Comment by barbalex** [comment]
Filter wurde entfernt
