### ISSUE TITLE
QK Ranunculus reptans

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#565]
Hoi Alex
Wenn man die Qualitätskontrolle bei Ranunculus reptans durchlaufen lässt, kommt die Meldung, dass bei einer TPop das bekannt seit jünger ist als die älteste Beobachtung (siehe Screenshot). 
<img width="1615" alt="Bildschirmfoto 2022-08-11 um 12 19 24" src="https://user-images.githubusercontent.com/30288503/184113441-092ebb61-c916-49d4-a7cf-4e7ef90be70b.png">
Wenn ich dann in der entsprechenden Teilpopulation nachschaue, ist die älteste Beobachtung von 1996 und auch das bekannt seit ist 1996...  (siehe Screenshot) Übersehe ich hier etwas?
<img width="1200" alt="Bildschirmfoto 2022-08-11 um 12 19 40" src="https://user-images.githubusercontent.com/30288503/184113607-bbe5596d-4162-42da-b675-fd0262f1c875.png">

**Comment by barbalex** [comment]
Bin in den Ferien und werde übernächste Woche reagieren

**Comment by rebeccakurz** [comment]
Bei mir jetzt auch nicht mehr....
