### ISSUE TITLE
Sortierung bei den Beobachtungen

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#566]
Hoi Alex
Seit kurzem sind die Beobachtungen, die noch nicht beurteilt wurden, ja nicht mehr nach dem Datum/Beobachtungszeitpunkt, sondern nach Import-Datum sortiert. Das ist grundsätzlich nicht schlecht, aber wäre es noch möglich, dass die Beobachtungen, die gleichzeitig importiert wurden, dann auch noch nach Datum sortiert werden würden?
So ist es momentan:
![Bildschirmfoto 2022-08-22 um 09 14 49](https://user-images.githubusercontent.com/30288503/185862498-ab600016-1b7f-4231-843c-703cbf75fcbe.png)
?

**Comment by barbalex** [comment]
Da ist wohl ein Unfall passiert. Wie sollten sie idealerweise sortiert werden?

**Comment by barbalex** [comment]
Ist in Version 1.78.4 wieder nach Datum absteigend sortiert. Sag mir, wenn ihr Anderes wünscht

**Comment by rebeccakurz** [comment]
Super, danke. Diese Sortierung ist für uns gut.
