### ISSUE TITLE
Feldkontrolle relevant für Jahresbericht

### ISSUE THREAD

**Issue by kmarti** [barbalex/apf2#568]
Wenn man eine Feldkontrolle ausfüllt, kommt man zur Frage:

Im Jahresbericht nicht berücksichtigen
- Ja
- Nein

Es wäre besser, das "nicht" aus der Frage zu entfernen, dann ist die Frage klarer und besser zu beantworten.

**Comment by barbalex** [comment]
Was du sagst, macht absolut Sinn. Und ich finde es toll, dass du dir die Mühe nimmst, Unklarheiten zu finden und zu reduzieren.

Historisch ist es aber anders entstanden. Was die Änderung nicht ganz simpel macht.

Die Information baut auf dem Feld `apber_nicht_relevant` auf. Das Feld existierte ursprünglich nicht, es wurde nachträglich eingeführt. Es war damals die Absicht, dass es nicht immer nachgeführt werden muss. Sondern nur, wenn eine Kontrolle wirklich nicht zu berücksichtigen ist. Darum wurde auch absichtlich das kompliziertere `apber_nicht_relevant` gewählt und nicht wie bei der Teil-Population `apber_relevant`.

Daher enthält das Feld auch keinen Standardwert bzw der Standardwert is null (will heissen: kein Wert).

Würde man das Feld umbenennen zu `Im Jahresbericht berücksichtigen`, ist es ganz klar einfacher zu verstehen und zu beantworten. Man erhält aber auch den Eindruck - bzw. es schiene dann logisch -, dass eine Kontrolle nur berücksichtigt wird, wenn hier `Ja` gewählt ist.

Und wenn das nicht der Fall wäre, d.h. null würde als `Ja` interpretiert, dann wäre das wohl missverständlicher als die heutige Situation.

Man kann also nicht wie heute dieses Feld in weit über 99.7% aller Fälle ignorieren (45 nein, 263 ja, 18'112 null). Sondern müsste es immer ausfüllen. Ansonsten würde die Kontrolle keine Wirkung entfalten.

Möchten wir also den Text verständlicher formulieren, müsste wohl folgendes geändert werden:
- Feld wird umbenannt in `apber_relevant` (mit Folgen in Datenbank, Schnittstelle und Code)
- Standardwert wird `Ja`
- Alle existierenden Kontrollen mit Null-Eintrag werden auf `Ja` gesetzt
- Es wird im Code geprüft, wo überall dieses Feld verwendet wird. Und wie mit den drei möglichen Werten umgegangen wird. Um sicherzustellen, dass das Verhalten nicht ungewollt ändert

Ich schätze, das gibt einen Tag Aufwand.

Ich glaube, es wäre so wirklich logischer und besser verständlich. Und so würde ich es auch designen, wenn wir die Datenbank von Null auf neu aufbauen würden.

Aber lohnt sich die Änderung?

**Comment by rebeccakurz** [comment]
Hoi Alex
Habe das noch mit Karin besprochen. Ich glaube die Verwirrung bei dieser Frage besteht hauptsächlich darin, dass egal ob man die Frage mit ja oder nein beantwortet, man das gleiche Ergebnis hat. Also: "Ja, nicht im Jahresbericht berücksichtigen" oder "Nein, nicht im Jahresbericht berücksichtigen". 
Bis jetzt wurde es allerdings meist richtig gemacht, also wenn die Feldkontrollen im JB berücksichtigt werden sollten, dann wurde einfach nichts angekreuzt (Standardfall) und wenn die Feldkontrolle nicht im JB berücksichtigt werden sollte, wurde "ja" angekreuzt und eine Begründung angegeben (z.B. gleichzeitige Freiwilligenkontrolle etc.).

Unser Vorschlag wäre nun, dass wir es bei der Feldkontrolle gleich wie bei den Freiwilligenkontrollen machen könnten. Dort sieht es nämlich so aus: 
![Bildschirmfoto 2022-09-19 um 14 12 27](https://user-images.githubusercontent.com/30288503/191014501-b9cbd281-f7e3-42e4-b472-1efeebd45132.png)
Dann sollte es unserer Meinung nach klarer sein. Wäre das möglich?

**Comment by barbalex** [comment]
Wäre das schon gut genug?
<img width="255" alt="2022-09-19_14h57_23" src="https://user-images.githubusercontent.com/669783/191022534-4137e727-0e13-4ac4-9c1b-ddde58723318.png">

**Comment by rebeccakurz** [comment]
Ja, das sieht gut aus!

**Comment by barbalex** [comment]
Ist in Version 1.78.9 implementiert. Wird in ca. 6 Minuten online sein

**Comment by rebeccakurz** [comment]
Super, vielen Dank!

**Comment by barbalex** [comment]
Vor lauter ?? habe ich die falsche Version des Felds gelöscht 😢 
In Version 1.78.10 kommt es nun doch noch richtig.

**Comment by rebeccakurz** [comment]
Jetzt hat es geklappt!
