### ISSUE TITLE
Dateien hochladen für Freiwilligen nicht möglich

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#569]
Hoi Alex
Einer der Freiwilligen, die ihre Eingaben direkt in der FloraDB machen, hat mir noch gemeldet, dass es ihm leider nicht möglich war, eine Datei bei den Freiwilligenkontrollen hochzuladen. 
Ich habe nun in der FloraDB ausprobiert, ob es bei mir klappt, aber es geht ebenfalls nicht. 
Ich bin dazu unter Mehr -> EKF sehen als -> Tony Disler und habe dann direkt bei seinen Kontrollen versucht eine Datei hochzuladen. Dann kam diese Fehlermeldung: 
![Bildschirmfoto 2022-09-19 um 16 31 05](https://user-images.githubusercontent.com/30288503/191042476-9c5555fb-488f-4c19-835f-ed833df98796.png)
Könntest du dir das mal anschauen bei Gelegenheit?

**Comment by barbalex** [comment]
Bei mir funktioniert es. Auch bei diesem Beispiel.

Offenbar kann die Anmeldung beim Datei-Server ablaufen ("Expired Signature"). 

Wenn ihr herausfindet, wie das provoziert werden kann, kann ich eher etwas machen.

Was in einem solchen Fall ziemlich sicher funktionieren sollte: Ab- und wieder Anmelden. Danach holt sich apflora für euch eine neue Anmeldung beim Datei-Server.

**Comment by barbalex** [comment]
Schliesse, da ein Jahr inaktiv
