### ISSUE TITLE
Karte: nur aktuelle Populationen anzeigen (Filtern)

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#57]
Das wäre eine grandiose Funktion, ist das möglich?

**Comment by barbalex** [comment]
Klar.

Was genau ist gemeint?

- im Layer Populationen nur die aktuelle anzeigen
- im Layer Teilpopulationen nur diejenigen der aktuellen Population anzeigen

Ähnliche Funktionen gibt es schon:

- im Layer Populationen ist die aktuelle (= im Strukturbaum gewählte) Population gelb hinterlegt
- im Layertool gibt es eine Schaltfläche, um auf die aktive Population (Layer Populationen) bzw. Teilpopulation (Layer Teilpopulationen) zu zoomen. Es ist nur aktiv, wenn es eine aktive Population bzw. Teilpopulation gibt

Jede zusätzliche Funktion

- kostet Aufwand, um sie bereitzustellen
- macht die Benutzung von apflora.ch komplexer

daher würde ich persönlich wirklich nur die "grandiosen" implementieren ;-)

**Comment by csalzmann** [comment]
Wegen der ähnlichen Funktion bin ich auch drauf gekommen. Es gab ja diesen Wunsch von uns schon lange, dass man in der Karte aktuelle/erloschene und ursprüngliche/angesiedelte unterscheiden kann. Das hilft natürlich auch beim Zuordnen von Beobachtungen und gibt einfach ganz einen andere Eindruck vom Zustand der Art.

Ich finde, das sind wichtige Funktionen, die sich lohnen zu implementieren.

In Priorität:
Populationen, dann TPop
Aktuelle ursprünglich
Aktuelle (alle)

**Comment by barbalex** [comment]
Oh, jetzt habe ich erst richtig verstanden: "aktuell" bezieht sich auf den Status der Population/Teilpopulation. Nicht darauf, welcher Datensatz gerade angezeigt wird...

Eine Filter-Funktion haben wir ja eigentlich schon: Du kannst oben am Strukturbaum z.B. die Populationen filtern. Das wirkt sich unmittelbar auf die Karte aus.

Wäre es nicht am sinnvollsten, wenn diese Funktion dort eingebaut würde?

Dann würden auch im Strukturbaum nur die dem Kriterium entsprechenden Populationen / Teilpopulationen angezeigt. Und der Strukturbaum zeigt dann dieselben Pop/TPop an, wie die Karte daneben.

Schwierig wird es, diese Funktionen sinnvoll zu platzieren. Vermutlich müssen sie nur erscheinen, wenn im Strukturbaum gerade Pop/TPop bzw. deren Ordner aktiv sind (man kann auch nur dann Pop/TPop filtern).

Schwierig ist v.a., dass die vollständige und den Benutzern bekannte Darstellung, um den Status auszuwählen, sehr viel Platz benötigt. Siehe das Feld im Formular.
![2017-08-30_12h22_32](https://user-images.githubusercontent.com/669783/29868135-16a0e14a-8d7e-11e7-9fbc-e50c799bc815.png)

Und in der bekannten Darstellung sollte es möglich sein, mehrere Auswahlen zu treffen. Damit man zum beispiel alle aktuellen wählen kann.

Daher müsste man wohl eine Schaltfläche schaffen, die rechts des Filter-Felds liegt (wie heute "nur Ap"). Die dann die bekannte Darstellung öffnet, wenn man darauf klickt. Und nach der Wahl nur noch den gewählten Text anzeigt.

Damit diese Schaltfläche genug Platz hat, müsste man wohl die heutige "nur Ap"-Schaltfläche nur noch anzeigen, wenn im Strukturbaum ein AP aktiv ist.

Im Prinzip könnte man das noch weiter denken: Man könnte neben dem Filterfeld (das ja einfach nach dem Text filtert, der im Strukturbaum angezeigt wird) eine Schaltfläche schaffen, die es ermöglicht, in der jeweiligen Struktur nach ALLEN Feldern zu filtern. Es würde also genau das gleiche Formular öffnen, wie wenn man die Daten anzeigt/bearbeitet. Nur würde es dem Filtern dienen. Das wäre wohl sehr benutzerfreundlich und umfassend. Aber noch aufwändiger zu machen.

**Comment by csalzmann** [comment]
Spannend!
Wenn man den Filter mit den Stati als Pop Up - Feld machen würde?

**Comment by barbalex** [comment]
Ja, das müsste es sein. Oder es erscheint unter der Filterzeile, während der Strukturbaum vorübergehend nach unten geschoben wird.

Wenn man gleich alle Felder anbieten würde, könnte man sie wohl anstelle des normalen Formulars an dessen Ort öffnen, also rechts des Strukturbaums. Zur klaren Unterscheidung würde das Formular aber anders gefärbt.

**Comment by barbalex** [comment]
> Wenn man gleich alle Felder anbieten würde, könnte man sie wohl anstelle des normalen Formulars an dessen Ort öffnen, also rechts des Strukturbaums. Zur klaren Unterscheidung würde das Formular aber anders gefärbt.

Ist in der Entwicklungsversion für AP, Pop und Tpop umgesetzt. Und wirkt sich auf die Karte aus.

**Comment by rebeccakurz** [comment]
Lieber Alex

Ich finde der Filter ist super umgesetzt, allerdings hat es etwas gedauert bis wir diese Funktion gefunden haben. Erst mit deiner Anleitung haben wir sie dann entdeckt. 
Zurzeit funktioniert der Filter auf Ebene Aktionsplan.
Vor 5 Minuten hat er auch noch auf Ebene Populationen funktioniert, jetzt kommt allerdings eine Fehlermeldung.
![bildschirmfoto 2018-11-22 um 14 34 45](https://user-images.githubusercontent.com/30288503/48906145-e2db5c80-ee63-11e8-91eb-2557eb516cd0.png)
Auf Ebene Teil-Population, Massnahmen und Feld-Kontrollen funktioniert die Filterfunktion ebenfalls nicht, es kommt dieselbe Fehlermeldung.

Auf Ebene Aktionspläne habe ich mal versucht zu filtern und es funktioniert auch das Meiste. Allerdings hat es vorher nicht funktioniert nach dem Verantwortlichen zu filtern. Jetzt habe ich es nochmals versucht und zuerst hat es geklappt, aber als ich den Filter ändern wollte, konnte ich die Filterfunktion nicht mehr aufrufen und jetzt funktioniert auch das Filtern im Strukturbaum nicht mehr. 
![bildschirmfoto 2018-11-22 um 14 39 55](https://user-images.githubusercontent.com/30288503/48906363-7f056380-ee64-11e8-8c83-812800775edd.png)

Bei den Freiwilligen-Kontrollen hat es ebenfalls nicht funktioniert nach dem Namen des Kontrolleurs zu filtern (was wirklich super wäre, wenn das möglich wäre!).

LG

**Comment by rebeccakurz** [comment]
Wäre es dann auch möglich auf Ebene der Pop/TPop zwei Auswahlkriterien für den Filter wählen könnte? Also dass man z.B. nach allen **aktuellen** Pop/TPop (ursprüngliche und aktuelle) filtern könnte. Dazu müsste man beim Filter "ursprünglich aktuell" und "angesiedelt aktuell" anklicken können.
![grafik](https://user-images.githubusercontent.com/30288503/48906520-fcc96f00-ee64-11e8-9884-0b7254658969.png)

LG

**Comment by csalzmann** [comment]
Jetzt wollte ich Dir grad schreiben, wie mega cool es ist, die TPops zu filtern, weil ich das jetzt grad wirklich gut gebrauchen kann. Also grundsätzlich: grandios! Und wenn man es noch ausbauen könnte, wie Rebecca oben vorgeschlagen hat, wäre es noch viel genialer.

Im Moment hat es aber noch einen kleinen Bug drin. 

Hat zuerst funktioniert (heute und auch schon die letzten Tage). Und ausgerechnet jetzt, wo ich weiter damit arbeiten will, streikts. Gehe ich auf Daten filtern, hab ich auf einmal ein leeres Mittelfeld. 
![bildschirmfoto 2019-01-25 um 11 00 52](https://user-images.githubusercontent.com/6047564/51739071-e3c18200-2090-11e9-89f1-241e9461f6d7.png)

Ich "reload", nochmals probiert. Kaum auf TPop "urspr aktuell" geklickt, wieder gleiches Verhalten (obwohl es mir vorher bei dieser Auswahl die Karte angezeigt hatte, der  Grund, weshalb ich ein positives Feedback schreiben wollte:).

Das wird sicher nicht nur mir passieren. Werd jetzt dann Cache leeren und nochmals probieren.

**Comment by csalzmann** [comment]
Also, jetzt tuts wieder. Wirklich lässig!

Unser Wunsch wäre, diese Funktion noch weiter auszubauen.

**Comment by barbalex** [comment]
Nach mehreren Stati filtern, mit "oder" verbunden, wie von euch gewünscht: Ja, das ist möglich. Aber ein bisschen Arbeit

**Comment by rebeccakurz** [comment]
Ich habe auch versucht über den Teilpopulations-Filter nach den ausserkantonalen Teilpopulationen zu filtern. Das hat allerdings nicht funktioniert, es ist gar nichts passiert. Es kam auch keine Fehlermeldung oder eine Meldung, dass der Filter nicht funktioniert. 
Allgemein fände ich es noch hilfreich, wenn man irgendeine Rückmeldung beim Filtern bekäme, z.B. dass der Filter angewendet wurde oder dass es z.B. eine nicht gültige Abfrage wäre oder etwas in diese Richtung. @csalzmann fändest du das auch sinnvoll?
<img width="1401" alt="bildschirmfoto 2019-01-31 um 07 33 28" src="https://user-images.githubusercontent.com/30288503/52035681-40a6b780-252b-11e9-9268-96fc7af4e6d3.png">
LG

**Comment by rebeccakurz** [comment]
Allgemein funktionieren mehrere Filter-Möglichkeiten (noch) nicht. Zum Beispiel auf Ebene Teilpopulationen die Möglichkeiten "Für AP-Bericht relevant": Ja, Nein (historisch), Nein (ausserkantonal), Nein (kein Vorkommen). Oder bei den Feld-Kontrollen und den Freiwilligen-Kontrollen das Filtern nach "Bearbeitern". 
Funktionieren diese bei dir, Alex?

**Comment by barbalex** [comment]
> Ebenfalls in diesem Pop-up-Fenster gibt es die Möglichkeit auf "Formular in neuem Tab öffnen". Wenn man darauf klickt, geht zwar ein neues Fenster auf, aber es gibt nur eine Fehlermeldung

Auch das funktioniert, dort wo ich es probiere.

Wie kann ich den Fehler nachvollziehen?

**Comment by barbalex** [comment]
> Ich habe auch versucht über den Teilpopulations-Filter nach den ausserkantonalen Teilpopulationen zu filtern. Das hat allerdings nicht funktioniert, es ist gar nichts passiert

Auch das funktioniert, dort wo ich es probiere.

Wie kann ich es nachvollziehen?

**Comment by barbalex** [comment]
> Allgemein fände ich es noch hilfreich, wenn man irgendeine Rückmeldung beim Filtern bekäme, z.B. dass der Filter angewendet wurde oder dass es z.B. eine nicht gültige Abfrage wäre oder etwas in diese Richtung

Ja, gute Idee. Es sollte wohl die Gesamtzahl der Datensätze der gefilterten Tabelle der Anzahl gefilterten entgegensetzen. Ich denke, das bau ich ein, wenn ich die Filter dieses Jahr ausbaue,.

**Comment by csalzmann** [comment]
Ja das ist unbedingt nötig. Das Filtern funktioniert manchmal nicht oder verzögert, man weiss nicht woran man ist.

**Comment by csalzmann** [comment]
Nach ein paar Filter-Gepröbel hat sich der Filter auf "weiss" gestellt - ?

![bildschirmfoto 2019-02-07 um 13 27 58](https://user-images.githubusercontent.com/6047564/52411467-4af12480-2adc-11e9-832e-a73717e2e54e.png)

**Comment by barbalex** [comment]
Der Filter zeigt jetzt an:

- wie viele Datensätze (AP, Pop, TPop, EK oder EKF) es total gibt
- wie viele die Bedingungen des Filters erfüllen

Das Problem, dass das Filter-Formular manchmal verschwindet, ist noch nicht behoben.

**Comment by rebeccakurz** [comment]
Sollte es jetzt schon möglich sein, nach mehreren verschiedenen Kriterien zu filtern? Also zum Beispiel nach angesiedelt, aktuellen TPops und nach Ansaatversuchen?

**Comment by barbalex** [comment]
Nein, eine "oder" Filterung ist nicht implementiert

**Comment by barbalex** [comment]
Schliesse weil der Filter neu implementiert wurde
