### ISSUE TITLE
Blüemli erscheint erst nach neuladen der Karte

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#570]
Von den AV gemeldet: 
Wenn eine neue Teilpopulation erstellt wird und diese durch Doppelklick auf der Karte verortet wird, dann erscheint das Blüemli nicht direkt, sondern erst, wenn die Seite neu geladen wird. Durch das Neuladen wird dann die Karte wieder auf den Ausgangszustand gesetzt (Orthofoto und Übersichtsplan müssen neu eingestellt werden und auch der Ausschnitt der Karte wird verschoben, so dass dann die neue TPop wieder gesucht werden muss. Auch im Strukturbaum muss wieder zu der neuen TPop navigiert werden und die eingestellten Breiten von Strukturbaum, Daten und Karten müssen wieder neu eingestellt werden, weil sie auf den Ausgangszustand zurückgehen. 
Könntest du dir das mal anschauen, ob sich hier etwas optimieren lässt?

**Comment by barbalex** [comment]
Das sollte in Version 1.78.12 korrigiert sein
