### ISSUE TITLE
Bei kopieren von Teilpopulation Feldkontrollen etc. ebenfalls mitnehmen

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#571]
Wunsch AV: 
Wenn eine Teilpopulation kopiert wird, wäre es dann möglich, dass auch die Inhalte wie Feldkontrollen etc. mitkopiert werden würden? Momentan wird ja wirklich nur die TPop mit dem zugehörigen Formular kopiert. Bin mir nicht ganz sicher, ob es einen Grund hat, dass das so ist.
Ausserdem wäre es nützlich, wenn die kopierte TPop mit "Kopie" angeschrieben werden würde, damit sie von der Original-TPop unterschieden werden könnte.

**Comment by barbalex** [comment]
> Wenn eine Teilpopulation kopiert wird, wäre es dann möglich, dass auch die Inhalte wie Feldkontrollen etc. mitkopiert werden würden?

Ja, das ist möglich. Allerdings etwas aufwändig. Folgende Daten sind mit der Teilpopulation verknüpft und könnten somit mit kopiert werden:
- Massnahmen
- Massnahmen-Berichte
- Feld-Kontrollen
- Zählungen der Feld-Kontrollen
- Freiwilligen-Kontrollen
- Zählungen der Freiwilligen-Kontrollen
- Kontroll-Berichte
- Zugeordnete Beobachtungen: diese können natürlich nicht mitkopiert werden. Sie müssten von der AV bei Bedarf neu zugeordnet werden

Wenn ein Benutzer nicht will, dass alles mitkopiert wird, muss er/sie danach alles Löschen. Das kann ganz schön Arbeit geben. Oder Verwirrung geben, wenn sich die Benutzerin nicht bewusst war, dass alles mitkopiert wird.

> Bin mir nicht ganz sicher, ob es einen Grund hat, dass das so ist.
Es wurde bisher nicht gewünscht, ist relativ aufwändig zu programmieren und könnte wie oben erwähnt auch mal nicht erwünscht sein bzw. zu Arbeit oder Verwirrung führen.

Ich habe auch den Eindruck, dass es Dinge gibt, bei denen das standardmässige Kopieren keinen Sinn macht (Berichte?). Und wenn nicht alles Kopiert wird, ist es wiederum unklar, was passiert.

Die Sache ist beim Verschieben technisch und inhaltlich viel klarer (dort kommt alles mit).

> Ausserdem wäre es nützlich, wenn die kopierte TPop mit "Kopie" angeschrieben werden würde, damit sie von der Original-TPop unterschieden werden könnte.

Das geht auch. Bloss ist zu beachten, dass die kopierte TPop auch weder Nr. noch Flurname haben kann, d.h. nicht als Kopie angeschrieben werden kann, weil die Kopie von nichts keinen Sinn macht.

**Comment by rebeccakurz** [comment]
Aufwand grösser als Nutzen
