### ISSUE TITLE
TPop in der Karte kopieren

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#572]
Wunsch AV: 
Wäre es möglich, dass eine Teilpopulation auch über die Karte kopiert werden könnte? Also dass man eigentlich das Blüemli auf der Karte anklicken könnte und mittels einer Tastenkombination (z.B. Shift-Taste) diese kopieren könnte?

**Comment by barbalex** [comment]
Ja, das ist möglich.

Ich würde den Befehl aber expliziter machen. Z.B. als zusätzliche Schaltfläche im Popup, das beim Klicken erscheint.

Es gibt ein Problem: Kopiert man auf der Karte, kann man nur TPop kopieren, die Koordinaten haben (die übrigen erscheinen nicht auf der Karte). Die Kopie wird nun natürlich genau dieselben Koordinaten haben. Somit genau am selben Ort angezeigt werden. Das ist für die Benutzerin wahrscheinlich nicht besonders praktisch. Besser wäre wohl, dass der Befehl ein Kopieren aktiviert, das erst beim Doppelklick auf einen Position in der Karte ausgeführt wird. Wobei dann die Koordinaten dieser Position gesetzt werden.

Bin nicht ganz sicher, wie einfach das für uneingeweihte Benutzer zu verstehen ist. Wir müssten uns eine möglichst klare Benutzerführung ausdenken.

Somit würde der Aufwand für die Umsetzung ev. etwas gross.

**Comment by rebeccakurz** [comment]
Vielen Dank noch für deine Rückmeldung und deine Überlegungen dazu. Eine klare Benutzerführung wäre sicher unerlässlich. 
Dann würde ich das gerne mal als Idee so stehenlassen. Wenn wir merken, dass das viele Vorteile bringen würden, dann könnten wir dies dann wieder aufgreifen.

**Comment by rebeccakurz** [comment]
Aufwand grösser als Nutzen

**Comment by rebeccakurz** [comment]
Aufwand grösser als Nutzen
