### ISSUE TITLE
Performance Strukturbaum

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#575]
Hoi Alex
Ich habe heute bei der Arbeit mit der FloraDB viel zwischen den verschiedenen AP-Arten wechseln müssen und dabei festgestellt, dass die Webseite viel mehr Mühe hat, wenn ich die Arten im Strukturbaum wieder schliesse, bevor ich zur nächsten Art gehe, als wenn ich sie einfach offen lasse. Ich hatte nur den Strukturbaum 1 und die Daten offen. 
Also wenn ich die eine Art im Strukturbaum wie wieder eingeklappt habe, dann hat die FloraDB viel länger gebraucht, bis ich die nächste Art anklicken konnte und zum Teil ist sie dann wie hangengeblieben. 

Kannst du das nachvollziehen? Könnte man hier etwas optimieren?

**Comment by barbalex** [comment]
> Also wenn ich die eine Art im Strukturbaum wie wieder eingeklappt habe, dann hat die FloraDB viel länger gebraucht, bis ich die nächste Art anklicken konnte und zum Teil ist sie dann wie hangengeblieben

Was ist hier die Grössenordnung in Sekunden?

**Comment by barbalex** [comment]
Was mir auf dem Server auffällt: In den letzten drei Monaten war die CPU-Belastung nie über 7%. Heute war sie um 15.20 Uhr auf 35%.

**Comment by rebeccakurz** [comment]
Manchmal dauert es bis zu 10 Sekunden, bis die Art geschlossen wird...

**Comment by barbalex** [comment]
Das ist zu viel. Ich weiss aber aktuell nicht, wieso das passiert und kann daher (noch) nichts machen. Wir müssen das aber beobachten und ich muss ein Auge darauf haben, wieso das passieren könnte

**Comment by rebeccakurz** [comment]
Das es so lange dauert ist vor allem dann der Fall (aber nicht nur!) wenn die Karte auch offen ist. Dann werden ja, wenn man eine Art schliesst, in der Karte alle Teilpopulationen aller Arten angezeigt, weil eben in diesem Moment ja keine Art ausgewählt ist. Das führt ja dann dazu, dass die FloraDB so langsam ist und zum Teil fast abstürzt. 
Vielleicht könnte dafür im nächsten Budget ein Posten eingerechnet werden, damit das optimiert werden kann?

**Comment by barbalex** [comment]
> Das es so lange dauert ist vor allem dann der Fall (aber nicht nur!) wenn die Karte auch offen ist. Dann werden ja, wenn man eine Art schliesst, in der Karte alle Teilpopulationen aller Arten angezeigt, weil eben in diesem Moment ja keine Art ausgewählt ist. Das führt ja dann dazu, dass die FloraDB so langsam ist und zum Teil fast abstürzt. Vielleicht könnte dafür im nächsten Budget ein Posten eingerechnet werden, damit das optimiert werden kann?

Das wäre dann: https://github.com/barbalex/apf2/issues/525

**Comment by barbalex** [comment]
Ich habe heute ein paar Stunden lang den Navigationsbaum studiert.

Zwei Massnahmen habe ich ergriffen:
1. Die Menge zu ladender Daten so weit wie möglich reduziert
2. Eine Eigenschaft eliminiert, die wohl genau zum Effekt geführt hat, dass die Leistung je länger desto schlechter wurde

Wurde bisher ein Knoten durch klicken auf das > geschlossen, blieben die hierarchisch tiefer gelegenen Knoten (unsichtbar) offen (ausser, man öffnete diesen Knoten wieder - dann war sichtbar, dass sie offen geblieben waren).

Somit waren je länger man navigierte, desto mehr Knoten offen.

Offene Knoten beeinflussen das Laden der Daten. Es gab Situationen, in denen 7MB Daten geladen wurden, um den Baum anzuzeigen! Das konnte sogar passieren, wenn nur noch die obersten paar Knoten zu sehen waren, womit eigentlich nur 1.3KB zu holen gewesen wären.

Ich habe die Programmierung jetzt so angepasst, dass das Schliessen eines Knotens immer automatisch alle darunter liegenden mit schliesst.

Es kommt trotzdem noch vor, dass viele Daten geladen werden. Ich sehe noch drei weitere Probleme:
- Das Laden aller ca. 500 Arten. Das konnte ich zwar jetzt verbessern, aber es sind einfach viele Daten
- Das Laden der Daten für Beobachtungen. Beobachtungen sind aufwändig mit Arten zu verbinden, weil es sich auch um Synonyme handeln kann. Daher müssen recht viele Daten geladen werden, um sie richtig anzuzeigen - oder nur schon, um ihre Anzahl zu berechnen. Auch das habe ich etwas optimiert. Aber bei Arten wie Abies alba, mit > 500 Beobachtungen, werden viele Daten geladen
- Es gibt noch Situationen, in denen ich nicht genau verstehe, wieso so viele Daten geladen werden oder wieso apflora mehrmals Daten geladen hat. Dort kann ich hoffentlich noch mehr optimieren

Die aktuellen Anpassungen sind auf einer Version von apflora erfolgt, die ich in den letzten Wochen stark modernisiert habe. Vor allem wurde die Unterhaltbarkeit verbessert. Ich werde diese neue Version in den nächsten Tagen live schalten.

Die Verlangsamung hat mit der Zeit zugenommen. Das lag zum Einen daran, dass die Anzahl AP-Arten zugenommen hat.

Zum Anderen wirken die Menge von Beobachtungen, welche je länger je mehr importiert werden. Beobachtungen haben auch darum zugenommen, weil sie für mehr Arten importiert werden.

Zum Dritten lag das an der neuen, zusätzlichen Taxonomie von Info Flora, welche dazu führt, dass Beobachtungen via Taxa mit den Aktionsplänen verbunden werden müssen, was die Abfragen zusätzlich strapaziert und v.a. zu viel mehr übertragenen Daten führt. Hier kann ev. noch optimiert werden, aber das wird aufwändig.

Daher wäre ich geneigt, einen grossen Teil der Arbeit, um die Navigation zu beschleunigen, nicht unter dem reinen Unterhalt abzubuchen. Dass ihr plötzlich so viel mehr AP's bearbeitet, war beim Offerieren des Unterhalts schlicht nicht bekannt.

Daher sollten wir https://github.com/barbalex/apf2/issues/525 plus ca. 2 Tage für die hier beschriebenen Sachen für 2023 finanzieren.

**Comment by barbalex** [comment]
Zusatz: Der Navigationsbaum könnte viel effizienter geladen werden, wenn immer nur ein Ast aufs Mal geöffnet werden könnte.
Die meisten Navigationsbäume werden so gebaut.

Aber ich vermute, dass ihr diese Möglichkeit nicht aufgeben wollt.

Daher gibt die Optimierung recht viel Aufwand.

**Comment by barbalex** [comment]
Ich sehe, dass aktuell in der Entwicklungsversion rund ein Sechsten der Daten geladen werden, verglichen mit der live Version. Und das ist, bevor das Offenbleiben vieler Knoten die Leistung bremst.

**Comment by barbalex** [comment]
Version 1.81.0 ist jetzt live (nach neu laden).

**Comment by barbalex** [comment]
In Version 1.81.0 brauchen die Knoten, die zuvor 7MB luden noch ca. 250 KB.
Ich könnte nach demselben Prinzip weiter optimieren, aber es bringt kaum mehr gleich viel.
Lasse es mal bleiben und warte auf eure Rückmeldungen.

**Comment by rebeccakurz** [comment]
Es scheint mir schon ein rechtes Stück besser zu sein, danke!

**Comment by barbalex** [comment]
Ich habe glaube ich endlich die beste Lösung für apflora gefunden. Sieht sehr vielversprechend aus: lädt verglichen mit der aktuellen Version nur noch ca. 33% der Daten. Und ist massiv einfacher zu unterhalten.

Hoffe, dass ich das in ein paar Tagen live schalten kann.

**Comment by barbalex** [comment]
Die neue Version ist jetzt in der Entwicklungsversion implementiert.

Hier der Vergleich mit der bisherigen: Die Werte sind KB, welche vom Server geladen werden. Der Vergleich ist mit der jetzt aktiven Version, nicht mit der bis vor einigen Tagen aktiven, welche z.T. nochmals um einen Faktor 30 mehr Daten lud.

Das folgende Bild wird wohl im Email nicht angezeigt, du musst den Issue auf GitHub anschauen.

<img width="570" alt="2023-02-05_22h56_24" src="https://user-images.githubusercontent.com/669783/216848265-dac2825f-e0a0-42bd-812d-0d0ba4b68e2d.png">

Wenn man die App neu lädt, wird sie künftig je nachdem, wo man beginnt, zwischen 1 und 50% weniger Daten laden.

Wo die neue Architektur viel mehr nützt, ist danach, d.h. wenn man sich innerhalb des weitgehend geladenen Navigationsbaums bewegt.

Bisher wurde jedes mal der ganze Baum geladen. Neu nur noch die neuen Äste. Wechselt man z.B. zwischen zwei Populationen oder Teilpopulationen, wird künftig nur noch rund 1% der bisherigen Datenmengen geladen!

Der grosse Aufwand lohnt sich (ich hab jetzt ein paar Tage durchgearbeitet...).

Die neue Architektur ist in dieser Art erst seit wenigen Monaten möglich. Die neuste Version von React kann VIEL besser mit tausenden von Knoten im Navigationsbaum umgehen. Es ist daher gar nicht mehr nötig, deren Anzahl mit speziellen Werkzeugen zu reduzieren. Und diese Werkzeuge führten eben dazu, dass die Daten viel aufwändiger geladen werden mussten.

Ich werde diese neue Version noch etwas zurückbehalten. Womit sie bei mir in der Entwicklungsversion mehr getestet wird. Es wurde sehr viel geändert, daher ist mit Nebenwirkungen zu rechnen. Aber dank der einfacheren Architektur sollten Korrekturen einfacher sein als bisher. Wenn ihr also nach der Publikation Fehler findet, kann ich hoffentlich rasch reagieren.

**Comment by kmarti** [comment]
Lieber Alex

Super, das ist ja sehr vielversprechend!

Herzliche Grüsse

Karin

-----------------------------------
Karin Marti
Dr.sc.nat.ETH
topos Marti & Müller AG
Idastrasse 24
8003 Zürich
***@***.******@***.***>
Tel. 044 451 52 55
                  ***@***.***
-----------------------------------



Von: Alexander Gabriel ***@***.***>
Antworten an: barbalex/apf2 ***@***.***>
Datum: Sonntag, 5. Februar 2023 um 23:07
An: barbalex/apf2 ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: Re: [barbalex/apf2] Performance Strukturbaum (Issue #575)


Die neue Version ist jetzt in der Entwicklungsversion implementiert.

Hier der Vergleich mit der bisherigen: Die Werte sind KB, welche vom Server geladen werden. Der Vergleich ist mit der jetzt aktiven Version, nicht mit der bis vor einigen Tagen aktiven, welche z.T. nochmals um einen Faktor 30 mehr Daten lud.

Das folgende Bild wird wohl im Email nicht angezeigt, du musst den Issue auf GitHub anschauen.

[Das Bild wurde vom Absender entfernt. 2023-02-05_22h56_24]<https://user-images.githubusercontent.com/669783/216848265-dac2825f-e0a0-42bd-812d-0d0ba4b68e2d.png>

Wenn man die App neu lädt, wird sie künftig je nachdem, wo man beginnt, zwischen 1 und 50% weniger Daten laden.

Wo die neue Architektur viel mehr nützt, ist danach, d.h. wenn man sich innerhalb des weitgehend geladenen Navigationsbaums bewegt.

Bisher wurde jedes mal der ganze Baum geladen. Neu nur noch die neuen Äste. Wechselt man z.B. zwischen zwei Populationen oder Teilpopulationen, wird künftig nur noch rund 1% der bisherigen Datenmengen geladen!

Der grosse Aufwand lohnt sich (ich hab jetzt ein paar Tage durchgearbeitet...).

Die neue Architektur ist in dieser Art erst seit wenigen Monaten möglich. Die neuste Version von React kann VIEL besser mit tausenden von Knoten im Navigationsbaum umgehen. Es ist daher gar nicht mehr nötig, deren Anzahl mit speziellen Werkzeugen zu reduzieren. Und diese Werkzeuge führten eben dazu, dass die Daten viel aufwändiger geladen werden mussten.

Ich werde diese neue Version noch etwas zurückbehalten. Womit sie bei mir in der Entwicklungsversion mehr getestet wird. Es wurde sehr viel geändert, daher ist mit Nebenwirkungen zu rechnen. Aber dank der einfacheren Architektur sollten Korrekturen einfacher sein als bisher. Wenn ihr also nach der Publikation Fehler findet, kann ich hoffentlich rasch reagieren.

**Comment by barbalex** [comment]
Die neue Version ist jetzt in Version 1.81.3 live
