### ISSUE TITLE
Navigationsbalken verschwindet

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#577]
Hoi Alex

Wenn ich in der FloraDB zur EK-Planung wechsle, dort eine Art eingebe und dann bei einem bestimmten Jahr nach TPops mit EK-Plan in diesem Jahr filtere, dann verschwindet der Navigationsbalken oben (grün) mit dem ich zum Beispiel wieder zum Bearbeiten der Arten wechseln kann. 
Wenn ich die Seite aktualisiere, erscheint der Balken wieder, wenn ich aber wieder etwas mit den Filtern mache, fliegt er raus. 
Könntest du dir das mal anschauen?
![Bildschirmfoto 2022-12-14 um 16 42 55](https://user-images.githubusercontent.com/30288503/207642291-80584351-59ec-4533-a0a9-0eaba299f07d.png)

**Comment by barbalex** [comment]
Wow. Kann man sich kaum vorstellen, dass das möglich ist 😮 
Schwierige Sache, Maloney...

**Comment by barbalex** [comment]
Das wird verursacht, weil eine zentrale verwendete Software (gatsby) eine andere lädt (reach-router), die den dom-tree verändert, obwohl in der App selbst reach-router gar nicht benutzt wird.

Extrem frustrierend. Extrem komplex zu lösen. Genau genommen gibt es nur eine Lösung: In ca. 4 bis 6 Wochen Arbeit gatsby durch etwas anderes zu ersetzen, das den dom-tree nicht manipuliert.

Wie es scheint, kann ich dieses Problem nicht schnell lösen. Bleibe aber dran.

**Comment by barbalex** [comment]
Ich habe einen riskanten Hack gefunden. Ist in Version 1.80.11 umgesetzt. Hoffentlich gibt das keine Nebenwirkungen.

Danke für die Meldung.

**Comment by barbalex** [comment]
Hm. Wie es scheint, hat diese Lösung Probleme.

**Comment by barbalex** [comment]
O.k., sollte gelöst sein

**Comment by rebeccakurz** [comment]
Uii, das tönt ja wirklich sehr kompliziert... 
Jetzt scheint es wieder zu funktionieren, danke!
