### ISSUE TITLE
Benutzerdokumentation funktioniert nicht

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#578]
Wenn man die Menüpunkte anklickt, kommt nur "nothing".
![Bildschirmfoto 2022-12-19 um 08 25 39](https://user-images.githubusercontent.com/30288503/208370535-51de3a0c-fb9e-4e0b-b17c-3e930cde0b6a.png)

**Comment by barbalex** [comment]
Eine verwendete Software hat bei einem Update ihr Verhalten verändert, ohne das zu dokumentieren. 

Hat mich heute ca. 5 Stunden gekostet, das neu aufzubauen. Denn das Verhalten wurde massiv verändert, womit die Dokumentation umgebaut werden musste.

Ist in Version 1.80.7 korrigiert.

Das gleiche Problem gibt es in vermehrung.ch. Wird nächstens korrigiert.

Ich hätte ja gerne reklamiert aber es gibt Schlimmeres...

Danke für die Meldung!
