### ISSUE TITLE
Datum verschwindet

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#58]
Leider habe ich immer noch das Problem mit den verschwindenden Datumseingaben. Ich kann ein Datum normal eingeben und auch den Rest der Eingabe machen, alles okay. Wenn ich dann aber zum nächsten Datensatz gehe und dann wieder zurück auf den soeben eingegebenen, ist das Datum verschwunden. Allerdings nicht bei allen eingegebenen Datensätzen (obwohl kein Unterschied dazwischen). Ich glaube es speichert das Datum schon, aber es wird im Moment einfach nicht angezeigt. Wenn man die Datenbank verlässt und später wieder zurückkehrt ist das Datum glaube ich immer eingetragen. Aber wenn man etwas kontrollieren will und das Datum ist einfach weg, verunsichert das sehr.

**Comment by barbalex** [comment]
Ich kann das (bisher) nicht nachvollziehen.

Ziel ist immer, dass man einen Fehler nachvollziehbar beschreiben kann: Mach das, dann das, und dann passiert dieser Fehler.

Das scheint hier aber nicht zu klappen.

Du könntest aber beschreiben:

- in welchen Datums-Feldern es passiert (nicht alle sind gleich programmiert)
- ob es (nur) in soeben neu erstellten Datensätzen passiert
- ob du das Datum per Tastatur oder Auswahl aus dem Kalender-Widget gesetzt hast

Sobald ich etwas nachvollziehen kann, kann ich beginnen, das Problem anzupacken.

**Comment by rebeccakurz** [comment]
Heute morgen habe ich mit neu erstellten Freiwilligenkontrollen gearbeitet. Ich habe das Datum per Tastatur eingegeben. Ob es auch in alten Datensätzen passiert, weiss ich nicht, da ich da ja keine Änderungen mache. 
Ich habe zum Beispiel diesen Datensatz (siehe Bild) heute morgen erstellt. Dabei habe ich das Datum per Tastatur eingetragen. Jetzt wenn ich diesen Datensatz erneut aufrufe, wird das Datum nicht mehr angezeigt! Das Jahr bleibt aber. 
![bildschirmfoto 2017-09-01 um 08 55 23](https://user-images.githubusercontent.com/30288503/29962448-9588bc36-8f03-11e7-84d9-e3e9c19ebb79.png)

**Comment by barbalex** [comment]
Ich hab jetzt rund ein Dutzend mal versucht, es nachzuvollziehen. Leider klappt es nicht. Also mach ich etwas falsch.

Fragen:

- Wenn du eine neue Freiwilligen-Kontrolle erstellst, wie oft passiert es bei dir?
- Welchen Browser verwendest du?
- Bist du auf macOS > parallels > Windows ?? > welcher Browser?
- Oder auf macOS > welcher Browser?

**Comment by rebeccakurz** [comment]
Ich verwende den Browser Chrome und arbeite auf macOS.
Es passiert vielleicht bei 1 von 3 mal. (weiss es aber nicht so genau...)
Ich habe heute nun die Einträge, die ich am Freitag gemacht habe, nochmals angeschaut. Es zeigt jetzt alle Datumseingaben korrekt an (also auch die, die es am Freitag nicht angezeigt hat).

**Comment by barbalex** [comment]
o.k., werde das später auf meinem mac ausprobieren

**Comment by barbalex** [comment]
Leider kann ich es auch nicht auf macOS (neueste Version) und Chrome nachvollziehen.

Habe den Status auf "möglicher Fehler" gesetzt, damit ich in der Liste die Übersicht habe, welche Fehler ich noch testen muss.

@csalzmann Passiert dir dieser Fehler auch?

**Comment by csalzmann** [comment]
Ist mir gerade passiert, nachdem ich TPop gewechselt hab und zurückgesprungen bin. Das müssen wir unbedingt korrigiert haben!

**Comment by barbalex** [comment]
Bloss kann ich das selber immer noch nicht provozieren :-(

**Comment by barbalex** [comment]
Zur Erklärung: "Möglicher Fehler" heisst nicht, dass ich euch nicht glaube. Es heisst nur, dass ich es selber nicht nachvollziehen kann

**Comment by csalzmann** [comment]
Ich habe jetzt gerade nochmals getestet. Zuhause auf PC, Firefox 55.0.3 (32-Bit).

Das erste Mal konnte ich den Fehler bei der 4. EK - Eingabe provozieren, wobei 3 EKs ohne Datum resultierten (die 1., 2. und 4. EK haben ihr Datum verloren). Ich hab das bei Abies alba 1000.1 gemacht und bin nach den EK-Eingaben jeweils auf ein anderes Feld im Baum gesprungen (ich glaube, es war die Pop oberhalb, also 504 (bin aber nicht mehr ganz sicher).

Beim nächsten Test konnte ich den Fehler "erst" beim 16. Versuch produzieren, habe aber genauer protokolliert: 
von den 16 EKs waren dann auf einen Schlag 12 EKs ohne Datum, das Datum behalten haben nur 3, und zwar die 5., 11. und die 14. Eingabe. Bis zu Versuch 15 bin ich nach der Eingabe einer EK bei Abies alba TPop 1000.2 auf TPop 1000.1 gesprungen und wieder zurück und hab die Daten in den EKs angeschaut. Beim Versuch 16 bin ich dann auf die TPop 1000.3 gesprungen mit dem obigen Resultat. Als EK-Datum bin ich vom 1.9.2017 aufwärts gegangen, drum seh ich, welche der Eingaben jeweils fehlt.

Es tut mir leid, aber dieser Fehler existiert wirklich - auch ausserhalb der topos-Umgebung.

**Comment by barbalex** [comment]
Das hat mich ca. 10 Stunden Arbeit gekostet.

Der Fehler liegt irgendwo in der benutzerseitigen Datenbank, welche der Browser bereitstellt, bzw. in dem Werkzeug, das mit ihr interagiert. Alle Werte wurden hier (wie erwartet) beim Speichern direkt gespeichert. Alle, ausser Zeit- bzw. Datums-Daten.

Die Folge war, dass diese Werte erst nach dem nächsten Laden aus der serverseitigen Datenbank aktualisiert wurden.

Und weil es sich bei allen unseren Datums-Feldern um ein komplexes System zweier Felder handelt, die bei jeder Änderung interagieren (Jahr und Datum), war der Fehler viel schwieriger zu isolieren.

Da ich keinen Weg sah, das Problem zu lösen, habe ich zur grossen Keule gegriffen: Die benutzerseitige Datenbank wurde im Wesentlichen abgeschafft. Sie wird nur noch verwendet, um die Anmeldung zu registrieren (damit Benutzer beim Öffnen von Daten aus apflora in neuen Fenstern nicht jedes mal anmelden müssen).

Das hat zwar die Anwendung vereinfacht. Sie ist jetzt aber auch langsamer.
Ausserdem war die benutzerseitige Datenbank das Instrument, welche es künftig hätte erlauben können, im Feld netzunabhängig zu arbeiten.

Im Hinterkopf habe ich für beide Probleme zwar eine alternative Lösung: Die neue, revolutionäre Technologie, mit der ich die neue Version von arteigenschaften.ch aufbaue: graphQL (http://graphql.org).

Trotzdem. Dieser Rückschritt ist enttäuschend :-(

Ihr müsst also vorläufig mit einer langsameren Anwendung leben. Ich gehe davon aus, dass ich irgendwann nächstes Jahr versuchen werde, apflora.ch auf graphQL umzubauen. Aber das ist eine grössere Sache.
