### ISSUE TITLE
Karte: Blüemli/Symbole werden nicht dargestellt

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#580]
In der Karte werden nur die Nummern der Teilpopulationen dargestellt, die Symbole aber nicht. 
![Bildschirmfoto 2022-12-21 um 11 05 31](https://user-images.githubusercontent.com/30288503/208879264-183a9d36-498b-4f66-be6d-c049909a4bda.png)

**Comment by barbalex** [comment]
Nebenwirkung meiner letzten Änderung 🙄 

Ist in Version 1.80.14 behoben. Die sollte 11.49 Uhr live sein.

Danke für die Meldung und Sorry für das Versehen!

**Comment by rebeccakurz** [comment]
Die Blüemli sind wieder da, vielen Dank!

**Comment by rebeccakurz** [comment]
So ist es!
