### ISSUE TITLE
Karte: mehrere Layer gleichzeitig abfragbar

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#582]
Aus Mail von Alex: 
"Wenn ihr mehrere Layer mit Informationen gleichzeitig anzeigen und abfragen können wollt, muss ich die Abfrage-Methodik neu programmieren. Ausserdem muss dann im Informationsfenster bei jedem Objekt der Name des Layers ergänzt werden, weil Objekte aus verschiedenen Layern erscheinen können. Das ist möglich und ev. hilfreich (das müsst ihr beurteilen) aber ein paar Stunden Aufwand."

**Comment by barbalex** [comment]
Ist in Version 1.91.0 implementiert.
Die NS-Gebiete Betreuung werden viel schneller geladen (weil neu direkt aus dem apflora-eigenen GIS)
