### ISSUE TITLE
Möglichkeit im Strukturbaum erloschen oder aktuell anzuzeigen

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#583]
Gäbe es eine Möglichkeit auch im Strukturbaum die Teilpopulationen mit einem Symbol ob erloschen oder aktuell anzeigen zu lassen? Also anstatt das Blüemli, wenn die Karte aktiv ist. Die Symbolik könnte die gleiche wie auf der Karte sein. 
![Bildschirmfoto 2023-01-10 um 10 34 59](https://user-images.githubusercontent.com/30288503/211515331-a1196b17-ec99-44ef-a2fe-ee2918289aee.png)

**Comment by barbalex** [comment]
Klar. Kostet ein paar Stunden Arbeit.
Und: Zu viele Symbole verwirren. Ev. müssen wir die bisherigen anpassen oder reduzieren.

**Comment by rebeccakurz** [comment]
Gerne können wir die Details noch besprechen (an der Planungssitzung?).
Die Umsetzung würde sicher eine bessere Übersicht liefern.

**Comment by barbalex** [comment]
Rebecca: Sollen die Symbole einfach immer erscheinen? Das ist simpel.

Oder eher: Es gibt eine Option, sie anzuzeigen? Das ist in Implementation und für die Benutzer anspruchsvoller. 
Ich denke es bräuchte ein neues Symbol im Navigationsbaum, mit dem man Optionen wählen könnte, ähnlich wie im Layertool der Karte.

**Comment by barbalex** [comment]
(Das Optionen-Symbol im Navigationsbaum könnte auch dazu dienen, nur die aktuelle Art bzw. nur den aktuellen Pfad anzuzeigen, https://github.com/barbalex/apf2/issues/84)

**Comment by barbalex** [comment]
Ich habe oben gesagt: 

> Zu viele Symbole verwirren. Ev. müssen wir die bisherigen anpassen oder reduzieren

Folgende Idee kam mir beim Implementierren:

In der Karte wählt man eine von drei Darstellungen für die Symbole.
Wieso nicht einfach die dort gewählte Version verwenden?
Dann gibt es keine verwirrende Vielfalt von Symbolen, die nebeneinander stehen. Und die Symbole entsprechen immer demjenigen in der Karte.

Du hast ja oben auch gesagt:

> Die Symbolik könnte die gleiche wie auf der Karte sein

Falls wir mal im Strukturbaum ein Optionen-Menü schaffen, könnte man dort (auch) das für TPop zu verwendende Symbol wählen, genau gleich wie im Layertool der Karte. Die zwei Menüs wäre gekoppelt, d.h. die Symbole sind in Karte und Navigationsbaum immer gleich.

Was meinst du?

**Comment by barbalex** [comment]
Ergänzung zu obiger Idee: Die von dir gewünschte Version der Darstellung könnte als neuer Standard gesetzt werden (anstatt der aktuellen Blumen).

Was meinst du?

**Comment by barbalex** [comment]
In folgendem Branch (https://apflora-git-583-gabrielsoftware.vercel.app) habe ich implementiert:

- [x] Symbole für Tpop in Navigationsbaum entsprechen den im Layertool der Karte gewählten
- [x] Die Symbole wurden optimiert (besserer Kontrast)
- [x] Im Navigationsbaum gibt es ein neues Menu. Hier können die gewünschten Symbole gewählt werden (genau gleich wie im Layertool)

Weil der Branch eine andere URL hat:
- Siehst nur du ihn. Ich merge den Branch mit dem Hauptprojekt, wenn er fertig ist
- Musst du separat anmelden, denn dein Cookie für apflora ist hier nicht gültig

**Comment by rebeccakurz** [comment]
_Symbole für Tpop in Navigationsbaum entsprechen den im Layertool der Karte gewählten:_ Finde ich gut, auch dass die Symbole als neuer Standard gesetzt werden (anstatt die Blumen).
_Im Navigationsbaum gibt es ein neues Menu. Hier können die gewünschten Symbole gewählt werden (genau gleich wie im Layertool)_: Finde ich auch gut. 
Das sieht so sehr gut aus und macht es schon viel übersichtlicher, vor allem auch, wenn es viele Teilpopulationen sind. Wenn dann auch noch bei den Populationen die Symbole gewählt werden können, ist die Übersicht noch besser. 
Gerne kannst du das also so umsetzen.

**Comment by barbalex** [comment]
In Version 1.85.0 implementiert
