### ISSUE TITLE
Pop-up Fenster der Beobachtungen: mehr Infos anzeigen lassen?

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#584]
Könnten im Pop-up-Fenster der Beobachtungen in der Karte noch weitere Infos angezeigt werden?

- presence/absence
- Genauigkeit (xy-Radius)
- locality-descript

**Comment by barbalex** [comment]
Folgende Felder existieren in der definierten Tabellenstruktur und können daher zuverlässig aufgerufen und beliebig dargestellt werden (bzw. damit verknüpfte Informationen):
- **datum**
- **autor**
- id
- **art_id**
- **tpop_id**
- nicht_zuordnen
- bemerkungen
- art_id_original
- infoflora_informiert_datum
- **quelle**
- obs_id
- **geom_point**

**Fett hervorgehoben**: Was heute angezeigt wird.

Die Daten, welche von der Quelle geliefert wurden, liegen als JSON vor. Hier können beliebige Felder existieren und in jeder Beobachtung andere (offene Datenstruktur). Sie könnten genau gleich gezeigt werden wie z.B. die Daten, welche bei den Massnahmen vom WMS mitgeliefert werden.

Man könnte die Anzeige so gestalten, dass diese Infos erst sichtbar werden, wenn der entsprechende Bereich im Popup geklickt wird, damit sie beim ersten Öffnen des Popups nicht den ganzen Bildschirm füllen.

Würde ein paar Stunden Arbeit geben.

**Comment by rebeccakurz** [comment]
Bin mir nicht sicher ob ich alles richtig verstanden habe, aber wenn das möglich wäre, dann wäre es für das Zuordnen der Beobachtungen sehr hilfreich.

**Comment by rebeccakurz** [comment]
Gerne können wir eine solche Besprechung machen. Möchtest du einen Termin vorschlagen?

**Comment by barbalex** [comment]
Diese Woche zu Bürozeiten ausser Morgen 10-12

**Comment by rebeccakurz** [comment]
Damit ich es nicht vergesse: Es wäre auch noch gut, wenn bei den zugeordneten Beobachtungen auch die zugehörige Population im Popup angezeigt werden könnte (nicht nur die Teilpopulation).

**Comment by rebeccakurz** [comment]
Also gerne folgende Infos im Pop-up zusätzlich anzeigen lassen: 

- Zugeordnete Population
-  presence/absence (falls Feld vorhanden)
-  Genauigkeit (xy-Radius) (falls Feld vorhanden)
-  locality-descript (falls Feld vorhanden)

**Comment by barbalex** [comment]
Namen der Felder:
- presence/absence: PRESENCE, presence
- Genauigkeit (xy-Radius): XY_PRECISION, xy_radius
- locality-descript: locality_descript

**Comment by barbalex** [comment]
In Version 1.90.0 implementiert
