### ISSUE TITLE
Problem Beobachtungen von Elias Landolt

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#587]
Bei der Zuordnung der Beobachtungen ist aufgefallen, dass es mit einigen Beobachtungen im Raum Zürich ein Problem mit den Koordinaten und dem Datum gibt. 
In der Beobachtung im Strukturbaum sind 500er-Koordinaten (xxx500/xxx500) angegeben. Auf der Karte liegen die Beobachtungen aber nicht in der Mitte eines Koordinatenquadrats, sondern auf einem Eckpunkt (xxx000/xxx000). Und wenn man die Beobachtung in der Karte anklickt, dann werden als Koordinaten auch 000er-Koordinaten (xxx000/xxx000) angezeigt. 
Auch komisch ist, das im Strukturbaum diese Beobachtungen mit Beobachtungsjahr 1950 angezeigt werden, wenn man aber in den Daten der Beobachtungen schaut, ist dort als obs_year 1998 angegeben. 
Soweit wir gesehen haben, handelt es sich immer um Beobachtungen von Elias Landolt (Angaben aus der Flora der Stadt Zürich) und auch immer um Beobachtungen aus dem Import Info Flora 2017. Es gibt auch immer zusätzlich eine gleiche Beobachtung aus dem Import Info Flora 2021.05. Bei dieser später importierten Beobachtung stimmt aber das Datum im Strukturbaum und den Daten der Beobachtung überein (1950) und die Koordinaten werden hier in den Daten und der Karte mit 500er-Koordinaten angegeben. 
Ich habe nun noch gemerkt dass sich die "falsch verortete" Beobachtung in der Karte mit dem Karten-Filter auch nicht markieren lässt, vielleicht gehört das zum selben Problem?

Nachfolgend ein paar Beispiele bei Cypripedium calceolus: 
![Bildschirmfoto 2023-01-11 um 16 35 34](https://user-images.githubusercontent.com/30288503/212008457-373beae1-39e2-422d-a150-e40dff608918.png)
 
![Bildschirmfoto 2023-01-11 um 16 36 06](https://user-images.githubusercontent.com/30288503/212008595-b61cea18-3323-43cc-8b34-731b8a0139e9.png)

und Spiranthes aestivalis: 
![Bildschirmfoto 2023-01-11 um 16 38 52](https://user-images.githubusercontent.com/30288503/212008777-ab20b576-9e2c-4665-b9a3-8970b2ef671b.png)
gleiche Beobachtung, andere Karte als Hintergrund:
![Bildschirmfoto 2023-01-11 um 16 40 43](https://user-images.githubusercontent.com/30288503/212008894-1c4931e4-509e-4ad1-91ee-d760bebc72f2.png)

Könntest du dir das mal anschauen?

**Comment by rebeccakurz** [comment]
> Ich habe nun noch gemerkt dass sich die "falsch verortete" Beobachtung in der Karte mit dem Karten-Filter auch nicht markieren lässt, vielleicht gehört das zum selben Problem?
Ich habe gerade noch festgestellt, dass das nicht Teil dieses Problems ist. Bereits zugeordnete Beobachtungen lassen sich generell mit dem Karten-Filter nicht erfassen, ausser die zugehörige Teilpopulation wird ebenfalls markiert.

**Comment by barbalex** [comment]
> In der Beobachtung im Strukturbaum sind 500er-Koordinaten (xxx500/xxx500) angegeben. Auf der Karte liegen die Beobachtungen aber nicht in der Mitte eines Koordinatenquadrats, sondern auf einem Eckpunkt (xxx000/xxx000). Und wenn man die Beobachtung in der Karte anklickt, dann werden als Koordinaten auch 000er-Koordinaten (xxx000/xxx000) angezeigt

Dafür gibt es eine einzige mögliche, daher wahrscheinliche Erklärung. Ich kann sie nicht prüfen, weil die Daten des Imports von 2017 mir nicht verfügbar sind:

Das sind Beobachtungen, deren Daten in einer späteren Lieferung von Info Flora verändert geliefert wurden. Der Import aktualisiert die "Informationen aus...". Nicht aber die daraus abgeleiteten Daten, die von apflora für die effiziente Verarbeitung genutzt werden, wie z.B. das Geometrie-Feld, das Datum, der Autor oder die Quelle.

Gerade bei diesen bei der Lokalisation generalisierten Daten von Landolt ist das gut möglich. Sie haben wohl ursprünglich die obere linke Ecke des Quadrats geliefert. Das letzte Mal aber das Zentrum.

Ich könnte mir auch vorstellen, das Landolt in deinem ersten Beispiel im Jahr 1998 eine Beobachtung aus dem Jahr 1950 kontrolliert hat. Und Info Flora bei der ersten Lieferung 1950 als Datum lieferte. Später dann 1998.

**Comment by rebeccakurz** [comment]
Danke für deine Rückmeldungen. Ich muss mir das nächste Woche nochmals genau anschauen. 
Aber eine Bereinigung der Differenzen wäre dann sicher erst für die nächste Budgetperiode vorzusehen.

**Comment by barbalex** [comment]
Ist implementiert.

Ergebnis (es gibt ca. 500'000 Beobachtungen):
- Bei 209 Beobachtungen hat der Name des Autors geändert
- Bei 519 Beobachtungen hat das Datum geändert. Hier die Datei mit diesen Beobachtungen:
[datum.csv](https://github.com/barbalex/apf2/files/11240394/datum.csv). Achtung: Wenn du sie in Excel öffnest, verändert Excel die Datümer!!!!! Darum habe ich sie im csv Format gelassen und in LibreOffice geöffnet.

- Bei 443'184 gab es Abweichungen des Orts. Bei allen ausser 2 aber unter 5 Metern. Hier die Datei mit den zwei mit 25 Metern Abweichung: [geomPoint.csv](https://github.com/barbalex/apf2/files/11240395/geomPoint.csv)

- Bei 202'346 gab es Abweichungen des Namens. Es schien aber, dass in all diesen Fällen die Taxonomie SISF (2005) existierte und neu DB-Taxref (2017) gewählt wird. Also kein anderes Taxon, bloss die aktuelle Taxonomie

**Comment by barbalex** [comment]
Ergänzung: ich habe die entsprechenden Funktionen, die ich dafür gebaut habe, jetzt ausgeführt. Und werde es künftig bei jedem Import machen. Damit ist künftig gewährleistet, dass die Rohdaten von der Originalquelle und die für die Darstellung in apflora abgeleiteten, immer übereinstimmen sollten.
