### ISSUE TITLE
Karten-Filter entfernen: nur letzter gesetzter Filter entfernen möglich?

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#588]
Wenn ich in der Karte mit dem Karten-Filter z.B. eine Beobachtung markiert habe, damit ich sie im Strukturbaum schneller finde und dann den Karten-Filter wieder entfernen will, damit mir wieder alle Daten angezeigt werden, habe ich ja nur die Option "Clear all". Wenn ich aber diese nutze, dann fallen ja alle Filter raus, sprich auch der Filter mit dem ich nur die AP-Arten im Strukturbaum anzeigen lasse. 
Gäbe es hier die Möglichkeit, dass zum Beispiel auch nur der zuletzt gesetzte Filter entfernt werden könnte oder etwas ähnliches?
Zum Beispiel gibt es ja beim anderen Filter in der Menuleiste die Option nur das aktuelle Filter-Kriterium zu entfernen. 
![Bildschirmfoto 2023-01-12 um 08 59 56](https://user-images.githubusercontent.com/30288503/212010623-4914bbb1-2172-4eb3-9df8-46a96d683068.png)

**Comment by barbalex** [comment]
Wenn du nur den Kartenfilter entfernen willst, machst du das am besten in der Karte (das gif must du wohl auf github anschauen, wird im email nicht klappen):
![karten-filter-entfernen](https://user-images.githubusercontent.com/669783/212108353-f3a1d56f-e10f-414a-9594-de0f6ecb4ab9.gif)

Habe soeben die Anleitung ergänzt, aber ist noch nicht live.

**Comment by rebeccakurz** [comment]
Okay, vielen Dank. Bei mir ist es ein paar mal passiert, dass mit diesem Befehl auch der Arten-Filter im Strukturbaum rausgefallen ist. Aber jetzt scheint es wieder zu funktionieren.
