### ISSUE TITLE
Export "Population: Aktuellste Zählung inkl. seither erfolgter Anpflanzungen" anpassen

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#589]
Für die Überprüfung der Zielerreichung arbeiten wir mit dem Export "Population: Aktuellste Zählung inkl. seither erfolgter Anpflanzungen". 
Nun werden in diesem Export aber nur diejenigen Populationen aufgeführt, bei denen es bereits eine Zählung oder eine Massnahme gegeben hat. Aktuelle oder erloschene Populationen ohne Zählung werden hier nicht aufgeführt. Daher haben wir für die Zielüberprüfung immer auch zusätzlich den Export "Populationen" gemacht. Mit diesen zwei Exporten kombiniert kann die Zielüberprüfung gut durchgeführt werden. 
Aber es wäre angenehmer, wenn man alles kombiniert in einem Export hätte. Daher wollten wir fragen, ob der Export "Population: Aktuellste Zählung inkl. seither erfolgter Anpflanzungen" mit allen (für den AP-Bericht relevanten) Populationen ergänzt werden könnte?

**Comment by barbalex** [comment]
Ist noch genau zu definieren (offenbar auch erloschene?). Aber: Klar, das ist machbar. Die Abfrage ist aber anspruchsvoll und nur schon sie genau anschauen kostet viel Zeit, daher eine Erweiterung.

**Comment by rebeccakurz** [comment]
Genau, also der Export müsste dann alle Populationen (aktuell und erloschen) mit "für AP-Bericht relevant" enthalten

**Comment by rebeccakurz** [comment]
auch erloschene

**Comment by rebeccakurz** [comment]
Danke!
