### ISSUE TITLE
Feld: Gefährdung

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#59]
Auf dem aktuellen Protokollblatt für die Freiwilligen ist das Feld Gefährdungen aufgeteilt in: 

- Problemarten

- andere Gefährdung

Wäre super, wenn das in der Datenbank auch so wäre, würde die Eingaben erleichtern.=)

**Comment by barbalex** [comment]
@csalzmann diese mögliche Erweiterung übergebe ich dir - zur Triage
Wenn nichts passiert, nehme ich sie auf die Liste für nächstes Jahr.

**Comment by csalzmann** [comment]
OK, wäre schön aber ist nicht superdringend.

**Comment by barbalex** [comment]
Ich schliesse diesen Issue weil schon lange nicht mehr aktiv. Falls das Problem wieder auftaucht, bitte wieder öffnen
