### ISSUE TITLE
neue QK: Pop. angesiedelt, aktuell, aber Massnahme eine Ansaat und noch keine Anzahl

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#590]
Wir hatten den Fall einer Population, die den Status angesiedelt, aktuell hatte. Als Massnahme war nur eine Ansaat eingetragen, die aber noch nicht kontrolliert wurde. Eigentlich müsste der Status also "Ansaatversuch" lauten. Das würde auch dann gelten, wenn die TPop kontrolliert wurde, aber noch keine Individuen festgestellt wurden (Anzahl=0). Hingegen wenn bereits einmal Pflanzen/Individuen entdeckt wurden, aber bei einer neuen Kontrolle keine mehr, dann würde der Status angesiedelt, aktuell gelten. 
Das würden wir gerne mit einer neuen Qualitätskontrolle abfangen. Wäre das möglich?

**Comment by barbalex** [comment]
Ja, aber etwas aufwändiger als andere Qualitätskontrollen

**Comment by rebeccakurz** [comment]
und auch vorher ist keine Anpflanzung erfolgt --> neue Ansaatversuche/neue Teilpopulationen
Teilpopulation, in der die erste Massnahme eine Ansaat ist

**Comment by rebeccakurz** [comment]
QK nur auf Teilpopulations-Ebene nötig

**Comment by barbalex** [comment]
In Version 1.100.0 implementiert
