### ISSUE TITLE
mehr als drei Zähleinheiten erfassbar machen

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#593]
#522 
Wenn die neue Zähleinheit Fläche x Deckung geschaffen wird, wäre es bei einigen Arten sinnvoll, wenn mehr als drei Zähleinheiten erfasst werden könnten. 
Es müssten dann nämlich folgende Einheiten erfasst werden können: 

- Fläche in m2 (braucht es um FlächexDeckung zu berechnen)
- Deckung in Prozent (braucht es um FlächexDeckung zu berechnen)
- Fläche x Deckung (Index)
- Anzahl Triebe/Pflanzen (wird meist für Ziele/Zielüberprüfung gebraucht)

**Comment by barbalex** [comment]
Es kommt drauf an, was ihr wollt.

Bei Feldkontrollen können heute schon beliebig viele Zähleinheiten erfasst werden.

Bei Freiwilligen-Kontrollen ist das nicht der Fall. Wegen des Formulars, in dem genau drei vorgesehen sind. Das wäre natürlich veränderbar, wenn das Formular anders gestaltet wird. Eine solche Anpassung würde App-seitig allerdings einen relativ grossen Aufwand verursachen, weil die Erfassung sehr kompliziert zu programmieren ist.

Bei den EK-Zähleinheiten tritt das Problem vermutlich nicht auf. Denn wenn Fläche x Deckung als EK-Zähleinheit deklariert wird, werden die zwei Einheiten, welche zusätzlich zu dessen Berechnung bzw. Dokumentation erfasst werden, wohl kaum auch noch als EK-Zähleinheiten definiert. (Natürlich können sie problemlos zusätzlich als Zählungen in Feldkontrollen erfasst werden.)

**Comment by rebeccakurz** [comment]
Stimmt, so weit habe ich gar nicht studiert. Ich kann ja bei einer Feldkontrolle Zähleinheiten erfassen, ohne dass sie im Strukturbaum als "EK-Zähleinheiten" aufgezählt sind. 
Ich denke eher nicht, dass solche kompliziert aufzunehmende Arten für die EKF in Frage kommen, daher sollte es dort auch kein Problem sein.
Damit hat sich das "Problem" gleich wieder erledigt und ich schliesse diesen Issue.
