### ISSUE TITLE
Entwicklung einzelner Populationen darstellen

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#594]
Im PDF der Jahresberichte gibt es ja die Grafik, wo die Entwicklung der Zähleinheit (z.B. Anzahl Pflanzen) pro Population dargestellt wird. Dabei werden die verschiedenen Populationen übereinander gestapelt. 
Nun kam die Frage, ob es möglich wäre, das auch für einzelne Populationen darzustellen. Dies aber vielleicht nicht im Jahresbericht, sondern dass man eine solche Grafik selbst erstellen könnte.
Dafür würde es einen neuen Export brauchen, wo für jede Population alle Zählungen erfasst sind. Wäre das möglich?

**Comment by barbalex** [comment]
Generell scheint es mir sehr sinnvoll, alle Auswertungen zu ermöglichen, welche für die AV's, euch und die FNS nützlich sind. Dafür hat man ja so eine Anwendung und all diese Daten.

Es geht also einfach darum, dass das verständlich ist und mehr Nutzen als Aufwand gibt. Bzw. wie es am meisten nützt.

Klar kann man einen Export anbieten. Weil pro Pop/TPop, am ehesten dort, statt bei den allgemeinen Exporten.

Eine andere Variante, wäre: Wie im AP und im Jahresbericht könnte man bei jeder Pop und TPop eine entsprechende Grafik ergänzen.

Beides ist mit ein paar Stunden Aufwand umsetzbar.

**Comment by rebeccakurz** [comment]
Gerne würden wir auch dieses Issue umsetzen (beide Varianten).

**Comment by barbalex** [comment]
Heisst das Grafiken bei Pop und TPop?

**Comment by barbalex** [comment]
Export auch für Pop und TPop?
Welche Felder?

**Comment by rebeccakurz** [comment]
Hoi Alex
Ich habe das nochmals mit Karin angeschaut. Wenn der Export aufwändiger ist als die Grafik, dann würden wir doch lieber die Grafiken (bei Pop und TPop) zuerst umsetzen. Aber immer noch mit zweiter Priorität.

**Comment by barbalex** [comment]
In deiner Liste steht nur für Populationen.
Ich stelle mir vor: die Darstellung zeigt die Linien gestapelt nach TPop.
Ähnlich wie im Jahresbericht. Dort sind sie aber gestapelt nach Pop.

Richtig?

**Comment by barbalex** [comment]
In Version 1.84.0 implementiert
