### ISSUE TITLE
Ausgangszustand: Verzicht auf TPop- und Pop-Berichte --> QK anpassen

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#595]
Von den Artverantwortlichen kam die Anfrage, ob es nicht möglich wäre, dass bei der Erhebung des Ausgangszustands einer Teilpopulation auf das Ausfüllen eines Teilpopulationsberichts und Populationsberichts verzichtet werden könnte? Dies da in so einem Fall sowieso noch keine Aussage zur Entwicklung einer Population gemacht werden kann und der Bericht daher immer unsicher lautet.
--> Ich muss das zuerst noch mit Karin besprechen, ob das für uns in allen Fällen sinnvoll wäre und wir das so wollen, aber somit ist es hier mal deponiert :-)

**Comment by barbalex** [comment]
Gegenfrage, ev. eine blöde: Wo werden die Kontroll-Berichte überhaupt noch verwendet? 

Mir scheint, sie wurden aus dem AP-Bericht entfernt. Dort wird ja heute direkt die Bestandesentwicklung dargestellt und nicht die Beurteilung mittels Kontroll-Bericht.

Im Gegensatz dazu werden die Massnahmenberichte im AP-Bericht direkt dargestellt.

Gibt es andere Orte, wo die Kontroll-Berichte ausgewertet werden?

Wenn nicht oder wenn das nicht so wichtig ist, könnte man sich überlegen, ob der Aufwand, sie zu erfassen, sich lohnt. Und ob man sie nicht besser entfernen sollte.

**Comment by rebeccakurz** [comment]
Wir brauchen die Populationsberichte, die ja auf den Teilpopulationsberichten aufbauen, bei der Darstellung der Arten für den Jahresbericht. Also wir erstellen für jede Art eine Karte, wo die Populationen dargestellt sind und nach Status und Entwicklung (zunehmend, stabil, abnehmend, unsicher) dargestellt sind. Siehe nachfolgendes Beispiel von Saxifraga granulata
[Saxifraga granulata L._20230118.pdf](https://github.com/barbalex/apf2/files/10445180/Saxifraga.granulata.L._20230118.pdf)

**Comment by barbalex** [comment]
O.k., dann werden diese Infos offenbar doch noch genutzt.

Wie fliesst diese Darstellung in den Jahresbericht ein? Ich frage bloss, weil sie prinzipiell auch direkt in apflora erzeugt werden könnte.

**Comment by rebeccakurz** [comment]
Wir müssen diese Karten für alle Arten erstellen und geben sie zusammen mit dem Jahresbericht aus der FloraDB der FNS ab.

**Comment by barbalex** [comment]
Dann könnt ihr euch selber überlegen, ob ihr sie weiterhin wo machen wollt, oder ob sie in apflora entweder separat oder in den Bericht integriert erstellt werden sollten.

Wäre einmalig ein paar Stunden Aufwand.

**Comment by rebeccakurz** [comment]
Hoi Alex
Dieses Issue haben wir gestern noch vergessen zu besprechen, aber wir möchten das gerne umsetzen, also dass bei Teilpopulationen/Populationen, bei denen erst der Ausgangszustand erfasst wurde, keine Teilpopulations- und Populationsberichte mehr verfasst werden müssen.

**Comment by barbalex** [comment]
So wie ich die Sache verstehe verlangt apflora nicht, dass man Berichte erfasst. Das ist eine Sache eurer Anleitung. Ev. gibt es eine Qualitätskontrolle, die eingeschränkt werden muss?

**Comment by barbalex** [comment]
In Version 1.95.0 implementiert.

Betrifft QK's:
- popOhnePopber
- tpopOhneTpopber

**Comment by rebeccakurz** [comment]
Danke!
