### ISSUE TITLE
Daten bei Laserpitium prutenicum

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#596]
Der Artverantwortliche von Laserpitium prutenicum (Fabio Flick) hat heute gemeldet, dass bei Laserpitium Daten (vor allem Teilpopulations- und Populationsberichte) scheinbar verschwunden sind. 
Er ist sich eigentlich fast sicher, dass er fast alle Berichte erstellt hatte, nun sind sie aber nicht mehr vorhanden und werden in der Qualitätskontrolle aufgelistet. Er meinte, er erinnere sich noch, dass er sich eben so geärgert hatte, dass er bei allen Ausgangszuständen, die er dieses Jahr erfasst hatte, einen Teilpopulationsbericht erstellen musste, obwohl ja eigentlich noch keine Aussage machbar ist. Er meinte er habe die Berichte irgendwann im Dezember verfasst gehabt. 
Nun habe ich leider nicht wirklich eine Möglichkeit, um nachzuprüfen, ob die Berichte mal in der FloraDB vorhanden waren und wieder rausgefallen sind oder vielleicht nicht richtig eingegeben wurden... 
Fällt dir eine Möglichkeit ein, wie wir das überprüfen könnten, ob hier ein Fehler datenbankseitig vorliegt oder ob es sich vielleicht doch um einen Anwendungsfehler handelt? 
Im Fall von Laserpitium sind wir nun so verblieben, dass wir (topos) die Berichte nochmals erstellen, damit die Daten wieder vollständig sind. 
Aber es wäre doch gut, wenn wir ausschliessen könnten, dass es hier zu einem Fehler der Datenbank gekommen ist. 
Diese Probleme scheinen nur bei Laserpitium prutenicum aufgetreten zu sein, ich habe jedenfalls von niemand anderem etwas vergleichbares gehört...

**Comment by barbalex** [comment]
Grundsätzlich gehe ich nicht davon aus, dass Daten verschwinden. Die Anwendung ist ja gebaut, damit das nicht passiert. Und ich kann mich nicht erinnern, in den letzten zwei Monaten etwas gemacht zu haben, dass zu Datenverlust hätte führen können (wie z.B. eine Migration der Datenbank, was zuletzt am 17.11.2021 geschah).

Aber hier mal ein paar Varianten, wie das vielleicht passieren könnte:

## Referenz verloren
Theoretisch ist es denkbar, dass ein TPop-Bericht den Bezug zur TPop verliert. Dann wäre er zwar noch da aber nicht mehr sichtbar. Praktisch kann ich mir nicht vorstellen, wie das passieren soll. Es gibt aktuell auch wirklich 0 TPop-Berichte, die keinen Bezug zu einer TPop haben. Dito für Pop-Berichte. Also ist das nicht passiert (genau genommen: Nicht in den letzen ca. 10 Jahren, jedenfalls seit es Kontroll-Berichte gibt).

## Datensätze wurden gelöscht
Wie auch immer das passieren sollte (ich kann mir nicht vorstellen, wie das anders als durch die Menübefehle passieren soll).

Eine Methode, um das nachzuprüfen wäre:
1. Wir bekommen ein (oder mehrere) konkretes Beispiel, das wir prüfen sollen (Pop bzw. Tpop mit Bericht)
2. Wir kontrollieren in den Sicherungskopien, ob das Beispiel dort existiert

Das heisst konkret: Sicherungskopien erfolgen täglich um Mitternacht. Ich prüfe also in allen Tagen des Dezembers folgendermassen:
1. In der lokalen Entwicklungsumgebung die Datenbank aus der Sicherungskopie wiederherstellen
2. Nachschauen

Das gibt pro Sicherung ca. 5 Minuten Aufwand. Macht rund 3 Stunden Aufwand.

## Datensätze wurde nie gespeichert
In der App gibt es einen Fehler, der dazu führt, dass die Daten gar nie in die Datenbank geschrieben wurden.

Dass das systematisch passiert ist extrem unwahrscheinlich. Sonst würde es ja nie funktionieren. Prinzipiell kann nie ausgeschlossen werden, dass ein einzelner Speichervorgang einmal scheitert. Dafür sind einige Gründe denkbar:
- Der lokale PC hat irgend einen Aussetzer
- Die Internetverbindung hat einen Aussetzer
- Der Server hat einen Aussetzer

Nur: Sowas sollte apflora direkt mit einer Fehlermeldung anzeigen. Ausserdem werden alle Daten sehr häufig neu geladen (apflora ist nicht offline-fähig). Wenn also eine Speicherung gescheitert wäre und keine Fehlermeldung gesehen wurde, müsste das trotzdem recht schnell auffallen, wenn das Formular neu geladen wird oder wenn der Navigationsbaum neu geladen wird (was bei jeder Speicherung von Daten, die darin angezeigt werden, erfolgt - z.B. auch wenn man den nächsten Kontroll-Bericht erfasst).

Na ja. Wenn im Formular ein Datensatz erfasst wird, dieser aber gar nie gespeichert wird, würde er im Navigationsbaum gar nie angezeigt werden.

Und ausserdem: Bis man im Formular einen Datensatz erfassen kann, wurde er zuvor mittels Befehl neu geschaffen. Wäre dies nie in der Datenbank angekommen, würde der Datensatz nicht einmal im Formular angezeigt. Erst wenn er in der Datenbank existiert, kann er im Formular geladen werden.

Jede Änderung am Datensatz wird sofort in die Datenbank übertragen (d.h. für jedes Feld einzeln). 

Somit glaube ich:
- Man kann einen Datensatz nicht erfassen, ohne dass er in der Datenbank existiert
- Es wäre höchstens möglich, dass eine einzelne Änderung an einem Datensatz nicht beim Server ankam
- Somit wäre der Datensatz noch sichtbar aber nicht vollständig beschrieben



## Datensätze wurden gar nie erfasst
Ich will Fabio Flick nichts unterstellen. Aber wenn das ich selbst wäre, wäre für mich die wahrscheinlichste Variante, dass mich mein Gedächtnis täuscht 🙄.

**Comment by rebeccakurz** [comment]
Danke für deine Überlegungen. Dann würde ich vorschlagen, dass ich bei Fabio nochmals nachfrage, ob er den Zeitraum, in dem er die Berichte verfasst hat, noch weiter eingrenzen kann. Und dass wir dann vielleicht doch einen Blick in die Sicherungen werfen und anhand von konkreten Beispielen nachprüfen, ob die Berichte verfasst wurden oder nicht.

**Comment by barbalex** [comment]
O.k.

**Comment by barbalex** [comment]
Schliesse, weil seither 9 Monate vergangen sind
