### ISSUE TITLE
Beobachtungen bei Nicht-AP-Arten entfernen?

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#598]
Wir haben glaube ich mal darüber gesprochen, dass bei den Nicht-AP-Arten auch viele Beobachtungen vorhanden sind, die eigentlich gar nicht gebraucht werden. Würde es etwas für die Performance bringen, wenn diese entfernt werden würden?
Bei Abies alba könnte man einfach ein paar Beobachtungen behalten, wenn das möglich ist, damit man bei dieser Test-Art ausprobieren kann. Aber es müssten nicht über 500 sein...
Und es gäbe noch ein paar Arten, die die Beobachtungen behalten müssten, wie z.B. Gladiolus communis (und allenfalls die Ackerbegleitflora-Arten?).

**Comment by barbalex** [comment]
Ich glaube, es hat aktuell keine praktische Relevanz
