### ISSUE TITLE
Bekannt seit vs. Name (Pop) bzw. Flurname (Tpop)

### ISSUE THREAD

**Issue by wunderli** [barbalex/apf2#6]
Neu hat das "Ortsfeld" den Hinweis "Dieses Feld möglichst immer ausfüllen" statt das Jahresfeld. Vermutlich sollte der Hinweis immer noch bei "bekannt seit" sein?

**Comment by barbalex** [comment]
jein

Feld "Name" (Pop) bzw. "Flurname" (TPop) haben nach wie vor diesen Hinweis.

Allerdings hast du recht, das der Hinweis, dieses Feld immer auszufüllen, bei "bekannt seit" fehlt.

Hab ich nun ergänzt.
Danke für den Hinweis!
