### ISSUE TITLE
Angabe junge Pflanzen ja oder nein

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#60]
Auf dem Protokollblatt für die Freiwilligen können sie ankreuzen ob junge Pflanzen neben den alten beobachtet werden: "ja" oder "nein".
In der Datenbank ist es aber nur möglich "ja" anzukreuzen (oder gar nichts). Es ist aber ein Unterschied, ob jemand keine jungen Pflanzen beobachtet hat oder einfach keine Angabe dazu macht.
Daher wäre es sinnvoll bei der Angabe von jungen Pflanzen auch ein "nein" Feld zum Ankreuzen zu haben.=)

**Comment by barbalex** [comment]
uups, das war bisher so - hab ich vergessen

danke für die Erinnerung

ist umgesetzt

**Comment by rebeccakurz** [comment]
Wieso ist es wieder nur möglich "ja" anzukreuzen bei der Angabe von jungen Pflanzen??? war doch vorher "keine Angabe" "ja" "nein"?
![bildschirmfoto 2017-10-05 um 14 22 55](https://user-images.githubusercontent.com/30288503/31227226-624e074a-a9d9-11e7-897d-a6e7accb0112.png)

**Comment by barbalex** [comment]
gute Frage

ich hab wohl wieder mal einen Aussetzer gehabt :-(

ist repariert
