### ISSUE TITLE
Beobachtungen auch Populationen zuordnen können

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#600]
Momentan Zuordnung von Beobachtung nur auf TPop-Ebene möglich. Auch für Populationen zulassen?
Problem möglicherweise Darstellung in Karte?

**Comment by barbalex** [comment]
Fragt sich, ob das den Aufwand lohnt. Und die zusätzliche Komplexität.

Es ginge so:
- In der Tabelle für die Beobachtungen gibt es ein neues Feld "popId". Heute gibt es dazu das Feld "tpopId"
- Im Formular der Beobachtungen gibt es ein neues Feld "Einer Population zuordnen" (neben: "Einer Teil-Population zuordnen", mit entsprechender Funktionalität)
- Im Layertool der Karte muss es eine neue Möglichkeit zur Zuordnung geben. Nicht ganz einfach, den Unterschied zwischen "einer Pop zuordnen" und "einer TPop zuordnen" klar sichtbar machen. Das heute verwendete Symbol drückt den Unterschied nicht aus. Ev. muss neu beim Klick auf dieses Symbol ein Menü öffnen, in dem man wählt, ob man einer Pop oder einer TPop zuordnen will. Mir ist auch nicht klar, wie die Benutzeroberfläche danach den Unterschied ausdrücken soll
- Bei den Zuordnungslinien gibt es zwei Varianten:
  - sie unterscheiden nicht zwischen Pop oder TPop - führen einfach zum geografischen Punkt (man sieht den Unterschied wenn man auf die Linie klickt im entsprechend anzupassenden Popup)
  - es gibt neu zwei Layer: Zuordnung zu Pop / Zuordnung zu TPop
- Ich weiss nicht auswendig, ob es Qualitätskontrollen oder Anderes gibt, an das wir bei dieser Anpassung denken müssen. Gefunden habe ich diese QK: "Teilpopulation: Bekannt seit ist jünger als die älteste zugeordnete Beobachtung". Die müsste nicht verändert werden. Ev. gibt es irgendwo Auswertungen, welche prüfen, ob eine Beobachtung zugeordnet ist. Solches müsste wohl angepasst werden

Das gibt einige Stunden Aufwand.

**Comment by rebeccakurz** [comment]
Fragt sich wirklich, ob sich da der Aufwand lohnt. Bis jetzt haben wir solche Beobachtungen als "nich zuordbar" gekennzeichnet, mit zb dem Grund "zu ungenau".
Vielleicht wäre es besser, dabei zu bleiben...

**Comment by rebeccakurz** [comment]
momentan nicht umsetzen, da zu kompliziert
