### ISSUE TITLE
PDF Jahresbericht: kein Pop-up bei den Grafiken

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#603]
Mir ist aufgefallen, dass im PDF der Jahresberichte bei den Grafiken kein Pop-up mehr erscheint, wo man die Zahlen herauslesen kann. 
![Bildschirmfoto 2023-02-07 um 12 19 58](https://user-images.githubusercontent.com/30288503/217231351-2b7e69f8-e4d6-463e-9824-0e24a3b3677d.png)
Bei den Grafiken bei den Arten unter "Auswertung" funktioniert es aber noch:
![Bildschirmfoto 2023-02-07 um 12 20 21](https://user-images.githubusercontent.com/30288503/217231533-3f434aa2-2d50-41f4-8063-2057eb6bd5df.png)
Könntest du dir das mal anschauen?

**Comment by barbalex** [comment]
Das ist by design.

Grund: Der Jahresbericht ist ein Buch mit über 300 Seiten und zig hundert Grafiken. Wenn jetzt auch noch alle Grafiken interaktiv sein sollen, kann das den Druck verlangsamen und eure PC's stressen.

Daher gibt es die Interaktivität nur in den Formularen.

**Comment by barbalex** [comment]
Hab's jetzt aber so angepasst, dass es bei der einzelnen Art interaktiv ist, bloss im vollständigen Jahresbericht nicht.
Danke für die Anregung.

Version 1.81.4 sollte in zwei Minuten live sein.

**Comment by rebeccakurz** [comment]
Super, vielen Dank! Das ist für die Kontrolle der Jahresberichte eine Hilfe, so kann ich die Zahlen in den Grafiken gleich mit den Grundmengen überprüfen
