### ISSUE TITLE
Auswertung Chara filiformis

### ISSUE THREAD

**Issue by kmarti** [barbalex/apf2#604]
Im Jahresbericht und bei der Auswertung von Chara filiformis wird in der Grafik "Triebe total nach Populationen" im Jahr 2022 die Population 4 mit 5000 Trieben angezeigt (wie Pop 2), obwohl in der Pop 4 keine Kontrolle stattgefunden hat.

**Comment by barbalex** [comment]
Auf die Schnelle angeschaut: Es gibt bei Pop 4 zwei Ansiedlungen bzw. Anpflanzungen mit je 2'500 Pflanzen. Ist deren Darstellung nicht korrekt?

**Comment by kmarti** [comment]
Ok, alles klar, das habe ich übersehen. Die Darstellung ist somit korrekt!
