### ISSUE TITLE
Formular EK-Planung: nach neu laden alles wieder auf Ausgangszustand

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#605]
Das Formular der EK-Planung muss ja jeweils neu geladen werden, damit die gemachten Änderungen auch erscheinen, wenn man z.B. einen Filter setzt. Also zum Beispiel wenn ich jetzt eine zusätzliche Feldkontrolle im Jahr 2023 plane und danach nach allen TPop mit EK-Plan im 2023 filtere, dann erscheint die zusätzliche Feldkontrolle erst, wenn ich das Formular aktualisiert habe. 
An sich ist das nicht so ein Problem, man muss einfach drandenken. 
Aber seit neuestem (ich glaube das war nicht immer so) muss ich nach dem neu laden wieder die Art eingeben und dann auch wieder die Felder wählen, die ich gerne angezeigt hätte etc. Das braucht jedes Mal wieder Zeit...
Kann das vielleicht noch optimiert werden? (Entweder so, dass ein neu laden gar nicht nötig ist oder falls das nicht möglich ist, dass nicht die Art wieder eingegeben werden muss und alle gemachten Einstellungen).
So sind zb die Einstellungen bevor ich die Seite neu lade:
![Bildschirmfoto 2023-02-08 um 15 53 32](https://user-images.githubusercontent.com/30288503/217565192-cd95960e-893c-454a-9974-3b9f7afe2dce.png)

Nach dem neu laden und eingeben der Art springen die Einstellungen wieder zurück:
![Bildschirmfoto 2023-02-08 um 15 53 57](https://user-images.githubusercontent.com/30288503/217565231-56f33b17-cb08-4e8d-ae75-7eb337ec2255.png)

**Comment by barbalex** [comment]
> Also zum Beispiel wenn ich jetzt eine zusätzliche Feldkontrolle im Jahr 2023 plane und danach nach allen TPop mit EK-Plan im 2023 filtere, dann erscheint die zusätzliche Feldkontrolle erst, wenn ich das Formular aktualisiert habe.

Ist nicht das das eigentliche Problem?

**Comment by barbalex** [comment]
Tja. Apflora hatte das "Gedächtnis" verloren (https://apflora.ch/Dokumentation/gedaechtnis). 

Ist in Version 1.81.5 repariert.

Damit öffnet es das EK-Planungs-Formular auch wieder mit den zuvor gewählten Arten.

**Comment by barbalex** [comment]
In zwei Minuten sollte Version 1.81.7 live sein. Darin ist das "eigentliche Problem" gelöst

**Comment by rebeccakurz** [comment]
Auch dafür danke!
