### ISSUE TITLE
neue QK: Status ist Ansaatversuch, Massnahme aber eine Anpflanzung

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#606]
Hoi Alex
Falls du die Kostenschätzung noch nicht gemacht hast, wir hätten noch eine weitere Qualitätskontrolle, die wir gerne erstellen würden. 
Status ist Ansaatversuch, als Massnahme wurde aber eine Anpflanzung durchgeführt.

**Comment by barbalex** [comment]
o.k., fliesst ein
