### ISSUE TITLE
EK-Planung: Filter ignoriert soeben erfasste Kontrollen

### ISSUE THREAD

**Issue by barbalex** [barbalex/apf2#607]
@rebeccakurz 
Rebecca schrieb:

> wenn ich eine zusätzliche Feldkontrolle im Jahr 2023 plane und danach nach allen TPop mit EK-Plan im 2023 filtere, dann erscheint die zusätzliche Feldkontrolle erst, wenn ich das Formular aktualisiert habe.

**Comment by barbalex** [comment]
In zwei Minuten sollte Version 1.81.7 live sein. Darin ist dieser Issue gelöst

**Comment by rebeccakurz** [comment]
Super, danke!
