### ISSUE TITLE
EK-Planung: Filter bei Gemeinde: "F" 

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#609]
Meldung von ChS:
Lieber Alex
 
Bei der EK-Planung habe ich ein ganz merkwürdiges Problem. Ich filtere gerne nach Gemeinden. Da funktionieren aber einzelne Buchstaben nicht. Z.B. «F» wie Fällanden geht nicht, bei «W» kann ich aber getrost Winkel tippen. Sehr schräg! Habe externe und Laptop-Tastatur probiert, beides Mal genau gleich.
 
Ich glaube, es geht fast alle Buchstaben ausser «F». Habe grad noch ein biz probiert.
 
Lieber Gruss, Charlotte

**Comment by barbalex** [comment]
Meine Antwort an Charlotte, in einem Email:

Das ist ziemlich schräg. Ich habe gemerkt, dass das genau dann passiert, wenn man den ersten Buchstaben des Labels des Felds tippt. In diesem Fall heisst das Feld "Filter", daher beim "f". 

Im Mittelalter hätte ich vermutet, dass du die App verhext hättest.

Da ich ein bisschen moderner bin, habe ich weitergesucht. Und herausgefunden, dass das ein Fehler im verwendeten Werkzeug ist.
Habe es bei den Entwicklern platziert: https://github.com/mui/material-ui/issues/36133

Mal schauen, was sie meinen.

Ich kann das Verhalten stoppen, wenn ich den Label entferne. Warte aber noch auf die Antwort der Entwickler.

Danke für die Meldung.

**Comment by barbalex** [comment]
Die Entwickler haben bestätigt, dass es sich vermutlich um einen Fehler im verwendeten Werkzeug handelt: https://github.com/mui/material-ui/issues/36133#issuecomment-1427546197

**Comment by barbalex** [comment]
Problem mit Hilfe der Entwickler gelöst in Version 1.81.13
