### ISSUE TITLE
Fenster springt nicht immer zu 2 Kolonnen 

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#61]
Zeigst Du ja auch im Filmli. Unklar, wann es springt und wann nicht. Sollte immer.

**Comment by csalzmann** [comment]
Ich meine bei Feldkontrollen und Massnahmen

**Comment by barbalex** [comment]
Ich glaube du meinst: Die einspaltige Darstellung wechselt nicht immer zuverlässig in die zweispaltige

**Comment by barbalex** [comment]
Ich habe etwas probiert. Da ich aber vorher das Verhalten nur selten provozieren konnte, bin ich nicht sicher, ob es genützt hat. Öffnet einfach diesen Issue wieder, wenn es nach wie vor passiert.

**Comment by csalzmann** [comment]
Bei mir ist es umgekehrt, die Darstellung wechselt bei Massnahmen nie in 2 Spalten, obwohl das eigentlich recht hübsch wäre (man muss ja sonst sehr viel scrollen, bis man sieht, wieviele Pflanzen ausgebracht wurden).

Ich wollte den Issue eigentlich wieder öffnen, aber bei uns gibt es nur "Comment" und nicht "Reopen and comment" - ich denke, da haben wir keine Rechte dafür?
![screenshot 15](https://user-images.githubusercontent.com/6047564/30951823-47117818-a425-11e7-911b-4af84b606db6.png)

**Comment by barbalex** [comment]
> Ich wollte den Issue eigentlich wieder öffnen, aber bei uns gibt es nur "Comment" und nicht "Reopen and comment" - ich denke, da haben wir keine Rechte dafür?

@csalzmann @rebeccakurz @wunderli
Tatsächlich. Daher habe ich euch zu den Mitarbeitern (collaborators) hinzugefügt. Ihr bekommt wohl ein mail von GitHub.

**Comment by barbalex** [comment]
> Bei mir ist es umgekehrt, die Darstellung wechselt bei Massnahmen nie in 2 Spalten, obwohl das eigentlich recht hübsch wäre (man muss ja sonst sehr viel scrollen, bis man sieht, wieviele Pflanzen ausgebracht wurden).

:-(

**Comment by barbalex** [comment]
@csalzmann 

Die verwendete Funktion sollte bei allen meines Wissens von euch benutzten Browsern funktionieren: https://caniuse.com/#search=column-width

Kannst du bitte sagen:

- Betriebssystem
- Browser inkl. Version

(ich hab mir deine Angaben nie gemerkt, es scheint aber auch, dass du auf verschiedenen Konfigurationen arbeitest)

**Comment by csalzmann** [comment]
Ich habs grad per Zufall rausgefunden. Es lag an meinen Bildschirmeinstellungen zu Hause (first level support, sorry!!).
