### ISSUE TITLE
EK-Planung: Horizontal scrollen

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#610]
Eingebracht von ChS (Mail vom 13.2.2023):
Ich habe noch ein Anliegen wegen der EK-Planung. Ich denke, es ist eigentlich ein ziemlich altes Anliegen, das den meisten bekannt ist.
 
In der EK-Planung kann man meist nicht nach rechts scrollen. Nach oben/unten erscheint der Scroll-Balken, aber unten für Horizontal eben nicht. Da ich zwei Bildschirme habe, kann ich es tolerieren, ich ziehe das Fenster einfach immer über 2 Bildschirme. Aber das haben ja nicht alle. (Habe gerade mit Rolf Hangartner telefoniert, und er war dann etwas aufgeschmissen).
 
Könntest Du da bitte nochmals schauen?

**Comment by rebeccakurz** [comment]
Rückmeldung von Alex: 
So wie du es beschreibst, ist mir noch nicht ganz klar, was du meinst. Denn: Die Jahresspalten sind horizontal scrollbar.
Ich vermute, du meinst die linken Spalten, die Eigenschaften der Teil-Population bzw. dazu gehörige Daten enthalten.

Wie gesagt, dieses Formular hat 4 Wochen Arbeit gekostet. Die Schwierigkeit kam mit ein paar Rahmenbedingungen, die nicht einfach zu ändern sind. Eine davon ist, dass die TPop-Spalten nicht scrollbar sind, im Gegensatz zu den Jahresspalten.
Das kann dazu führen, dass wenn die TPop-Spalten breiter sind als der Bildschirm, man nicht mehr horizontal scrollen kann.
 
Darum habe ich ganz bewusst versucht, die Breite der TPop-Spalten klein zu halten.
Darum sind standardmässig wenige Spalten enthalten. Zwar kann man mehr spalten einblenden ("Felder wählen"), man muss das aber explizit machen.
 
Ich bin davon ausgegangen, dass niemand soviele TPop-Spalten einblendet, dass die Jahresspalten gar nicht mehr sichtbart sind und man daher nicht mehr horizontal scrollen kann. Wieso? Weil die eigentliche Arbeit (EK planen) dort passiert und dort sichtbar wird.
 
Wenn es also stimmen sollte, dass du dieses Problem hat, weil du viele TPop-Spalten einblendest, dann kann ich dir aktuell nur raten, weniger Spalten einzublenden. Oder nur von Fall zu Fall zusätzliche, wenn du sie gerade benötigst.
 
Ach ja, was auch geht: Zoomen (mit denselben Werkzeugen wie auf jeder Webseite, hängt von deinem Mac/PC/Browser ab). Je kleiner du zoomst, desto mehr siehst du.
 
Ein dritter Bildschirm könnte auch helfen 😂. Wie es scheint, haben Biologinnen ähnliche Ansprüche wie Aktion-Händler (das sind die, welche z.T. 6 Bildschirme anordnen).
 
Prinzipiell wäre es vermutlich schon machbar, die heutige Einschränkung loszuwerden und vollständiges Scrollen zu ermöglichen. Ich kann aber schlecht schätzen, wie aufwendig das wird und ob es dann wirklich zufriedenstellend klappt. Und ich kann mir auch nicht wirklich vorstellen, dass es effizient ist, soooooo viele Daten gleichzeitig anzuzeigen. Und dass dauerndes Scrollen in einer Riesentabelle produktiv ist. Aber ihr seid die Benutzer und es liegt an euch, das zu beurteilen.
 
Man darf nicht vergessen: Auf diesem Formular können gleichzeitig zig-tausend Datensätze angezeigt werden:
Je nach Anzahl gewählter Arten, einige hundert bis tausend TPop
Multipliziert mit der Anzahl eigeblendeter Jahre (auch die kann man steuern: "vergangene Jahre")
Multipliziert mit der pro Jahr und TPop existierenden EK, EKF und Massnahmen
Da können recht schnell über 100'000 Datensätze geladen und dargestellt werden. Was der Hauptgrund ist, dass das Bauen dieses Formulars so aufwändig war.
 
Hab's grad mal probiert: Wenn ich Pulsatilla vulgaris lade, lädt dieses Formular 12MB Daten!!!! Das ist eine riesige Menge. Trotzdem geht es bei mir über ein schwaches (Ferien-)Mobilnetz recht schnell und die App zeichnet die Daten (auf einem recht modernen Notebook) problemlos.
 
Es gibt so viele Anforderungen an dieses Formular, dass es ausschliesslich auf verhältnismässig grossen Bildschirmen vernünftig nutzbar ist. Auf meinem (tollen) MacBook reicht es aber (für mich) schon.
 
Sorry, dass ich dir bloss erklären kann, wieso die aktuelle Einschränkung besteht. Und keine (rasche) Verbesserung in Aussicht stellen kann.
 
Nach etwas mehr Nachdenken kommt mir folgende Idee:
 
Kürzlich konnte ich ja die Geschwindigkeit des Navigationsbaums stark erhöhen. Das war möglich, weil React seit wenigen Monaten viel besser mit grossen Mengen an Komponenten umgehen kann. Im Navigationsbaum ist nun jeder Ast eine solche Komponente. React ist übrigens das Werkzeug, dass die Benutzeroberfläche baut.
 
Es wäre denkbar (aber mit mehreren Tagen Arbeit zu prüfen), dass das mit diesem Formular auch möglich ist. Das würde die Architektur dieses Formulars DRASTISCH vereinfachen. Denn heute ist es aus vier separaten Teilen zusammengesetzt. Zwei davon sind sogenannte virtuelle Listen, welche verhindern, dass React zuviele Komponenten gleichzeitig zeichnen muss, indem sie nur diejenigen zeichnen lassen, welche sich gerade im gescrollten Ausschnitt befinden. Früher wurde auch der Navigationsbaum mit eine virtuellen Liste gebaut.
 
Vielleicht könnten wir dieser Eier legenden Wollmilchsau auch noch das Stricken beibringen. Aber nachdem ich mir das erste Mal für die offerierten 3 Tage deren 20 aufgehalst habe, habe ich keine Lust, das von mir aus ohne Auftrag zu probieren.
 
@Rebecca: Vielleicht müssen wir den AV's besser kommunizieren, dass sie mit dem Einblenden zusätzlicher Felder Gefahr laufen, nicht mehr horizontal scrollen zu können.
 
@Charlotte: Danke für den Input.

**Comment by rebeccakurz** [comment]
Ergänzung von RK: 
Ich glaube was Charlotte meint ist das:
![Bildschirmfoto 2023-02-14 um 15 43 43](https://user-images.githubusercontent.com/30288503/218999773-cf73f1b8-fa0c-4f07-929a-49d1a265c2e1.png)
Also dass man zwar bei den Jahreszahlen von oben nach unten scrollen kann, aber nicht von links nach rechts, obwohl dort noch mehr Jahre wären, aber der Scrollbalken wird wie nicht angezeigt.
 
Wenn ich nun das Fenster mehrmals grösser und kleiner ziehe, dann erscheint der Scrollbalken manchmal wieder:
 
![Bildschirmfoto 2023-02-14 um 15 48 16](https://user-images.githubusercontent.com/30288503/218999876-3f4ba9e0-c5c9-4888-8e9f-c73abb086052.png)
Ich glaube wir hatten das tatsächlich auch schon früher einmal angeschaut, weiss jetzt aber nicht mehr, ob wir zu einer Lösung gekommen sind.
Aber vielleicht gäbe es hier noch Verbesserungspotential?

**Comment by rebeccakurz** [comment]
Antwort von Alex: 
Das Erscheinen eines Scrollbalkens ist nicht dasselbe wie Scrollen können.
 
In den Jahren kann man immer horizontal scrollen. Wenn sie breiter sind, als die verfügbare Breite. 
Ich z.B. kippe das Mausrad nach rechts um horizontal nach rechts zu scrollen. Auf dem Notebook ziehe ich zwei Finger auf dem Trackpad.
 
Ob der Scrollbalken sichtbar ist, bestimmen normalerweise Betriebssystem und Browser. In Apple z.B. sind Scrollbalken normalerweise ausgeblendet und werden erst bein Scrollen oder Neu-Zeichnung des Fensters sichtbar.
 
Apple gibt einem somit nicht immer die Gelegenheit, den Scrollbalken zu greifen und zu ziehen. Ich glaube, auf Windows sieht man den Scrollbalken grundsätzlich immer, wenn ein Formular scrollbar ist. Ich habe hier aber nur einen Mac, kann das daher nicht sicher sagen.
 
In der Web-Programmierung ist es üblich, die Darstellung des Scrollbalkens dem Browser und Betriebssystem zu überlassen. In diesem Formular mache ich das auch, unter anderem, weil es anders viel zu kompliziert wäre. Apflora übernimmt in anderen Formularen mit Hilfe eines Werkzeugs selbst die Kontrolle über die Scrollbalken. Das ist grundsätzlich eher heikel, hat aber bisher recht gut funktioniert. In anderen Apps habe ich darauf ganz verzichtet, weil es immer wieder mal spezielle Situationen geben kann, bei denen es nicht befriedigt.
 
Der langen Rede kurzer Sinn: Wenn euch das Betriebssystem keinen Scrollbalken anzeigen will, könnt ihr ihn nicht mit der Maus ziehen. Dann müsst ihr eine andere Methode verwenden. Apflora kann theoretisch Einfluss nehmen, aber das ist grundsätzlich eher heikel und in diesem Fall viel zu aufwändig. Dass kein Scrollbalken sichtbar ist, heisst nicht, dass nicht gescrollt werden kann.

**Comment by rebeccakurz** [comment]
Antwort von ChS:
Ich habe einen PC (Windows 10), und wie gesagt, der Scrollbalken wird nicht angezeigt. Dass ich mit dem Mausrad kippen kann, wusste ich nicht. Hab es gerade ausprobiert. Danke Alex! Für mich soweit gelöst.

**Comment by barbalex** [comment]
Schliesse, da 8 Monate alt
