### ISSUE TITLE
Export "Populationen mit dem letzten Populations-Bericht" ergänzen?

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#611]
Wir müssen ja jeweils einen Jahresbericht für alle AP-Arten erstellen und abgeben. Dazu gehört auch eine Karte mit den Populationen einer Art, wo die Entwicklung dargestellt ist, also ob eine Populaiton zunehmend, abnehmend, etc. ist. 
Für die Erstellung dieser Karten benutze ich den Export "Populationen mit dem letzten Populations-Bericht". Auf der Karte dargestellt werden alle Populationen, auch historische und ausserkantonale, sofern sie auf dem Kartenausschnitt drauf sind. Was wir aber auf diesen Karten nicht angezeigt haben möchten, sind Populationen, bei denen es sich um Gartenpflanzen handelt. Davon hat es z.B. bei Pulsatilla gleich einige. Oder es kann auch einen anderen Grund dafür geben, dass eine Population nicht angezeigt werden sollte, z.B. weil noch nicht sicher ist, ob es sich um die richtige Art handelt etc. 
Diese Gründe geben die Artverantwortlichen ja damit an, dass eine solche Population nicht relevant für den Jahresbericht ist mit Begründung "Gartenpflanzen" oder "anderer Grund". 

Momentan habe ich mit dem Export, den ich benutze, aber keine Möglichkeit diese Populationen zu identifizieren und so kommt es immer mal wieder zu Diskrepanzen zwischen den Zahlen im Jahresbericht und der Anzahl Populationen auf den Karten. 

Gäbe es eine Möglichkeit, den Export "Populationen mit dem letzten Populations-Bericht" damit zu ergänzen ob eine Population für den Jahresbericht relevant ist und mit dem Grund für eine Nicht-Relevanz? Dann könnte ich diejenigen Populationen herausfiltern, die nicht relevant für den JB sind mit Begründung "Gartenpflanzen" und "anderer Grund". 
Da die Angabe, ob ein Vorkommen relevant für den Jahresbericht ist oder nicht, nur auf Ebene Teilpopulation angegeben werden muss, ist es jeweils etwas mühsam herauszufinden, um welche Populationen es sich handelt. Vielleicht erschwert das auch eine Ergänzung des Exports, aber es wäre super, wenn das möglich wäre. 

Falls es nicht mehr ins Budget 2023 reinpasst, müsste man halt mit einer Umsetzung bis 2024 warten...
Beispiel einer Karte:  
[Aldrovanda vesiculosa L..pdf](https://github.com/barbalex/apf2/files/10742012/Aldrovanda.vesiculosa.L.pdf)

**Comment by rebeccakurz** [comment]
Ja, ich denke das würde schon mal viel helfen. Dann kann ich nach all denjenigen Pop filtern, die beim Grund nur Gartenpflanzen angegeben haben, etc.
Vielen Dank!

**Comment by barbalex** [comment]
Ist in Version 1.97.0 implementiert
