### ISSUE TITLE
Fehlermeldung beim Versuch Dateien hochzuladen

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#613]
Hoi Alex
Wir haben heute versucht Dateien in die FloraDB hochzuladen. Wenn man aber auf "neue Datei hochladen" klickt
![Bildschirmfoto 2023-02-22 um 11 41 43](https://user-images.githubusercontent.com/30288503/220597003-13e563a0-45ba-4dba-a9cb-fbca5974ef55.png)
dann kommt folgende Fehlermeldung:
![Bildschirmfoto 2023-02-22 um 11 40 20](https://user-images.githubusercontent.com/30288503/220596789-22dafa30-de1e-41da-ba2a-5bf4eb137c90.png)
Wir haben es bei den Populationen, Teilpopulationen und Feldkontrollen versucht mit dem gleichen Ergebnis.
Könntest du dir das mal anschauen?

**Comment by barbalex** [comment]
Ist in Version 1.81.30 gelöst

**Comment by rebeccakurz** [comment]
Super, vielen Dank, das klappt wieder!

Gibt es hier eigentlich eine Begrenzung wieviele Dateien hochgeladen werden können? Oder führen zu viele Dateien irgendwann zu einer Verlangsamung der FloraDB oder etwas ähnliches?

**Comment by barbalex** [comment]
Verlangsamung nicht. 

Ich benutze einen Dienst (uploadcare.com). Die Dateien liegen auf dessen Server. Darum beeinflusst es apflora nicht. 

Aktuell gibt es 640 MB Dateien in apflora und vermehrung. Wenn es über 15GB geht, kostet es einfach mehr. Ich melde mich dann schon, bevor es so weit kommt, dass es das Budget sprengt.

**Comment by rebeccakurz** [comment]
Super, danke für diese Infos. 
Das ist eine Funktion der Datenbank, die bei den Artverantwortlichen wohl auch eher noch etwas unbekannt ist oder zumindest weniger genutzt wird. Und eigentlich ja eine super Funktion. 
Vielleicht muss ich sie mal etwas bewerben.

**Comment by barbalex** [comment]
Die Bilder werden übrigens auf maximal 2045*2045 px verkleinert, um ihre Grösse zu begrenzen.

**Comment by barbalex** [comment]
Will heissen: Wenn sie grösser sind, werden sie beim Upload verkleinert

**Comment by rebeccakurz** [comment]
gut zu wissen, danke!
