### ISSUE TITLE
"Bilder in Galerie öffnen" nicht möglich

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#614]
Das gehört vielleicht zum gleichen Problem wie Issue #613 
Bei Thalictrum simplex subsp. galioides habe ich bei der Art früher mal Bilder hochgeladen: 
![Bildschirmfoto 2023-02-22 um 11 44 40](https://user-images.githubusercontent.com/30288503/220598142-33f9992e-0a00-4fe7-84f6-7b305223c0d9.png)
Wenn ich diese nun öffnen möchte mit dem Befehl "Bilder in Galerie öffnen", dann kommt folgende Fehlermeldung: 
![Bildschirmfoto 2023-02-22 um 11 44 08](https://user-images.githubusercontent.com/30288503/220598289-8d54059b-856b-4709-a28c-24b798cfe92c.png)

**Comment by barbalex** [comment]
Ist in Version 1.81.31 repariert (= neues Werkzeug verwendet)

**Comment by rebeccakurz** [comment]
Vielen Dank, das klappt wieder. Noch ein kleiner Schönheitsfehler, vielleicht ja einfach zu beheben... "Galerie" schreibt man nur mit einem L...

**Comment by barbalex** [comment]
> "Galerie" schreibt man nur mit einem L...

korrigiert. Danke!
