### ISSUE TITLE
EKF-Formulare ohne Bild, wenn einzeln drucken

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#617]
Wir können die Protokolle für die Freiwilligen-Kontrollen ja direkt in der FloraDB erzeugen und dann drucken. Nun ist mir aufgefallen, dass wenn ich ein einzelnes Protokollblatt drucken möchte, das zugehörige Bild der Art nicht angezeigt wird. Wenn ich aber alle Formulare gleichzeitig drucken möchte, dann werden die Bilder der Arten korrekt angezeigt. 
![Bildschirmfoto 2023-03-07 um 10 16 42](https://user-images.githubusercontent.com/30288503/223377861-460137da-39f3-4019-aff4-5da4fb88faa6.png)
![Bildschirmfoto 2023-03-07 um 10 17 30](https://user-images.githubusercontent.com/30288503/223377891-8fdfefca-7955-41a0-966d-3494356a2606.png)
Könntest du dir das bei Gelegenheit mal anschauen?

**Comment by barbalex** [comment]
Wie es scheint, beeinflusst etwas (server-seitig) die Ladezeit der Bilder.

Sollte in Version 1.81.46 behoben sein.

**Comment by rebeccakurz** [comment]
Leider konnte ich in der neuen Version noch keine Änderung feststellen...

**Comment by barbalex** [comment]
Auch in Version 1.81.47?

**Comment by rebeccakurz** [comment]
Leider nein...
![Bildschirmfoto 2023-03-07 um 14 08 18](https://user-images.githubusercontent.com/30288503/223431252-cb27d367-bb1f-4a0c-bbcd-e71336aa7eb0.png)

**Comment by barbalex** [comment]
O.k., nehme den nächsten Pfeil aus dem Köcher. Aber das dauert länger

**Comment by barbalex** [comment]
So, habe diesen Teil völlig neu gebaut. Wie geht es in Version 1.81.48?

**Comment by rebeccakurz** [comment]
Jetzt funktioniert es, vielen Dank!
