### ISSUE TITLE
Darstellung Beobachtungen

### ISSUE THREAD

**Issue by barbalex** [barbalex/apf2#618]
Input von Charlotte Salzmann per email:

Du, der Punkt von der Feedbackrunde wegen den Beobachtungen. Ich bin ja auch schon betriebsblind und nehme manche Dinge einfach mittlerweile als gegeben. Ich fände es auch super, wenn man mehr Info aufs Mal sieht. Du glaubst es nicht, wenn ich viele Beobachtungen zuordnen muss, muss ich eine Schiene am Mittelfinger tragen, weil mir vom Scrollen mit dem Mausrädli jedes Mal die Sehne kaputt geht. Ich habe die Schiene schon bei meinen Bürosachen parat. Wenn es geht, müssen wir da unbedingt etwas ändern. Es braucht doch z.B. gar nicht immer so grosse Abstände zwischen den Zeilen. Da wäre schon mal viel geholfen. Und Sortierung von Attributen. Z.B. SISF-Nr., oder User_ID müssen vielleicht nicht zuoberst sein?

**Comment by barbalex** [comment]
Input von Rebecca Kurz:

Danke für diese Inputs und ich denke, das wäre gut, wenn wir das so umsetzen könnten. Also beide Punkte, die dichtere Darstellung und die Sortierung. Dann könnte man in einer Wunschreihenfolge für die Zuordnung unwichtigere Infos wie die obs_id, country, deutscher, französischer und italienischer Name etc. eher ans Ende der Liste verschieben und für die Zuordnung wichtige Infos nach oben.

**Comment by barbalex** [comment]
@rebeccakurz 
Kannst du mir bitte eine Komma-getrennte Liste der Felder erstellen, in der Reihenfolge, wie sie erscheinen sollen?
Beispiel: `ESPECE, A_NOTE, M_NOTE, J_NOTE`.

**Comment by barbalex** [comment]
Habe jetzt eine Luxus-Lösung gewählt. Ev. erübrigt sich das Vorgeben einer Reihenfolge. Du kannst mir aber gerne trotzdem eine geben.

**Comment by barbalex** [comment]
In Version 1.88.0 implementiert

**Comment by rebeccakurz** [comment]
Wow, das ist wirklich viel übersichtlicher und auch das Drag&Drop funktioniert super! Ich habe auch gesehen, dass es, wenn mal in einer Beobachtung angepasst, auch bei den anderen Beobachtungen übernommen wird, das ist auch sehr gut! 
Jetzt wäre noch die Frage, wie lange die gewählte Reihenfolge bestehen bleibt? Ich nehme an, bis ich mich abmelde oder es ein Update gibt etc.? Dann würde ich vorschlagen, dass ich dir doch noch die Liste schicke und dass wir die Voreinstellung nach dieser Liste machen würden und dann können die AV immer noch per Drag&Drop in der jeweiligen Sitzung ihre bevorzugte Ansicht wählen, was meinst du?

**Comment by barbalex** [comment]
> Ich habe auch gesehen, dass es, wenn mal in einer Beobachtung angepasst, auch bei den anderen Beobachtungen übernommen wird, das ist auch sehr gut!

Die Schwierigkeit ist, dass nicht alle Beobachtungen dieselben Felder haben. Hat mich Zeit gekostet, dass es damit gut umgehen kann.

> Jetzt wäre noch die Frage, wie lange die gewählte Reihenfolge bestehen bleibt?

Die Reihenfolge wird gleich gespeichert, wie der übrige lokale Status. Also: Pro Gerät und Browser. Solange, bis der Cache (= lokaler Status) geleert wird.

> Dann würde ich vorschlagen, dass ich dir doch noch die Liste schicke und dass wir die Voreinstellung nach dieser Liste machen würden und dann können die AV immer noch per Drag&Drop in der jeweiligen Sitzung ihre bevorzugte Ansicht wählen, was meinst du?

Finde ich gut.

Das hier sind glaube ich alle oder die meisten Felder, die es gibt:

```json
[
    "ESPECE",
    "A_NOTE",
    "M_NOTE",
    "J_NOTE",
    "ALTITUDE_SUP",
    "CAT_ABONDANCE_1",
    "COORDONNEE_FED_E",
    "COORDONNEE_FED_N",
    "CUSTOM_TEXT_5_",
    "DESC_LOCALITE_",
    "DETERMINAVIT_CF_",
    "ESTIMATION_DATE",
    "EXPERTISE_INTRODUIT_",
    "INTRODUIT_",
    "NO_ISFS",
    "NO_NOTE_PROJET",
    "NOM_COMMUNE",
    "NOM_PERSONNE_OBS",
    "PRECISION_ALT",
    "PRECISION_MAILLE",
    "PRENOM_PERSONNE_OBS",
    "Projekt_ZH",
    "Raum_ZH",
    "TY_NOTE",
    "CO_CANTON",
    "DETERMINAVIT_CF",
    "EXPERTISE_DATE",
    "EXPERTISE_GEO",
    "EXPERTISE_INTRODUIT",
    "EXPERTISE_NOM",
    "EXPERTISE_WS",
    "FAMILLE",
    "FNS_FN",
    "FNS_GISLAYER",
    "FNS_ISFS",
    "FNS_JAHR",
    "FNS_VK",
    "FNS_WFN",
    "FNS_XGIS",
    "FNS_YGIS",
    "ID",
    "INDIGENAT",
    "INTRODUIT",
    "NO_NOTE",
    "NO_SURFACE_WELTEN",
    "NOM_COMPLET",
    "OBJECTID",
    "PRESENCE",
    "PROJET",
    "STATUT_NOTE",
    "TYPE_RELEVE",
    "XY_FORME",
    "XY_PRECISION",
    "ZDSF_KATEGORIE",
    "NOM_ORIGINAL",
    "ALTITUDE_INF",
    "DESC_LOCALITE",
    "EXPERTISE_ALTITUDE",
    "EXPERTISE_COMMUNE",
    "SOURCE_BIBLIO",
    "DeckKlasse",
    "REM_COUVERTURE",
    "STRATE_RELEVE",
    "STATION"
]
```

Du kannst das:
1. in eine Text-Datei kopieren
2. Die Reihenfolge ändern (oben = im Formular oben)
3. In einen Issue-Kommentar einfügen, um es mir zu schicken

Alternativ kannst du die Reihenfolgen auch direkt im Issue-Kommentar verschieben.

**Comment by barbalex** [comment]
Ergänzung: Es gibt noch mehr Felder 🙄 

```json
[
    "ESPECE",
    "A_NOTE",
    "M_NOTE",
    "J_NOTE",
    "ALTITUDE_SUP",
    "CAT_ABONDANCE_1",
    "COORDONNEE_FED_E",
    "COORDONNEE_FED_N",
    "CUSTOM_TEXT_5_",
    "DESC_LOCALITE_",
    "DETERMINAVIT_CF_",
    "ESTIMATION_DATE",
    "EXPERTISE_INTRODUIT_",
    "INTRODUIT_",
    "NO_ISFS",
    "NO_NOTE_PROJET",
    "NOM_COMMUNE",
    "NOM_PERSONNE_OBS",
    "PRECISION_ALT",
    "PRECISION_MAILLE",
    "PRENOM_PERSONNE_OBS",
    "Projekt_ZH",
    "Raum_ZH",
    "TY_NOTE",
    "CO_CANTON",
    "DETERMINAVIT_CF",
    "EXPERTISE_DATE",
    "EXPERTISE_GEO",
    "EXPERTISE_INTRODUIT",
    "EXPERTISE_NOM",
    "EXPERTISE_WS",
    "FAMILLE",
    "FNS_FN",
    "FNS_GISLAYER",
    "FNS_ISFS",
    "FNS_JAHR",
    "FNS_VK",
    "FNS_WFN",
    "FNS_XGIS",
    "FNS_YGIS",
    "ID",
    "INDIGENAT",
    "INTRODUIT",
    "NO_NOTE",
    "NO_SURFACE_WELTEN",
    "NOM_COMPLET",
    "OBJECTID",
    "PRESENCE",
    "PROJET",
    "STATUT_NOTE",
    "TYPE_RELEVE",
    "XY_FORME",
    "XY_PRECISION",
    "ZDSF_KATEGORIE",
    "NOM_ORIGINAL",
    "ALTITUDE_INF",
    "DESC_LOCALITE",
    "EXPERTISE_ALTITUDE",
    "EXPERTISE_COMMUNE",
    "SOURCE_BIBLIO",
    "DeckKlasse",
    "REM_COUVERTURE",
    "STRATE_RELEVE",
    "STATION",
    "altitude_expert",
    "altitude_min",
    "canton",
    "ch_protection",
    "copyright",
    "country",
    "date_expert",
    "determinavit_cf",
    "doubt_status",
    "family",
    "geo_expert",
    "introduction",
    "measures",
    "monitoring",
    "municipality",
    "name_de",
    "name_fr",
    "name_it",
    "native_status",
    "no_isfs",
    "obs_day",
    "obs_id",
    "obs_month",
    "obs_type",
    "obs_year",
    "observers",
    "original_taxon",
    "presence",
    "priority",
    "redlist",
    "region_biogeo",
    "regional_redlist",
    "releve_type",
    "spatial_resolution",
    "specimen_type",
    "tax_id_intern",
    "taxon",
    "taxon_expert",
    "taxon_link",
    "x_swiss",
    "xy_radius",
    "xy_type",
    "y_swiss",
    "remarks",
    "abundance_cat",
    "count_unit",
    "altitude_max",
    "cover_code",
    "locality_descript",
    "guid",
    "locality_id",
    "interpretation_note",
    "uzl",
    "abundance",
    "phenology_code",
    "cantonal_protection"
]
```

**Comment by barbalex** [comment]
Ist übrigens egal, wenn die Liste, welche zur Sortierung gesetzt wird, nicht vollständig ist: Die nicht enthaltenen Felder werden einfach nach den enthaltenen sortiert. Nach Alphabet.

**Comment by rebeccakurz** [comment]
Endlich habe ich die Liste für die Voreinstellung der Beobachtungsinformationen gemacht: 
[Beobachtungen_Reihenfolge_Angaben_20231012.xlsx](https://github.com/barbalex/apf2/files/12913065/Beobachtungen_Reihenfolge_Angaben_20231012.xlsx)
Geht das so oder wäre es besser in einer Textdatei?
Wichtig sind vor allem die Einträge bis und mit "STATION".  Alle darunterliegenden habe ich nicht sortiert.

**Comment by barbalex** [comment]
Danke.

Werde das ab dem 24.10. anschauen. Bin bis dahin in den Ferien.

**Comment by rebeccakurz** [comment]
Super, pressiert ja nicht. 
Wünsche dir weiterhin schöne Ferien!

**Comment by barbalex** [comment]
Habe soeben einen bisher nicht gemeldeten Fehler entdeckt. Er passiert aber nur sporadisch. Und wird von abhängiger Software verursacht. Habe ca. 4 Stunden damit verbracht, die Funktionalität mit einer anderen abhängigen Software zu bauen, bin aber an anderen Fehlern gescheitert...

Jedenfalls: In Version 1.103.0 implementiert.
