### ISSUE TITLE
Datenstruktur grafisch dargestellt ergibt Fehler

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#62]
![bildschirmfoto 2017-09-08 um 17 26 32](https://user-images.githubusercontent.com/6047564/30218987-ecbe565c-94ba-11e7-9d39-053d34098aa5.png)

**Comment by barbalex** [comment]
Das ist eine der Sachen, die nicht funktionieren, solange die top domain (apflora.ch) von der alten Version kontrolliert wird. Es wird funktionieren, sobald wir die neue Version als top domain einrichten.
