### ISSUE TITLE
Artwerte aktualisieren

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#621]
Wir haben von den Artverantwortlichen den Hinweis erhalten, dass die Artwerte in der FloraDB nicht auf dem neuesten Stand sind. Nun wollten wir diese anhand der neu berechneten Artwerte auf arteigenschaften.ch aktualisieren. 
Die Felder mit den Artwerten sind aber nicht veränderbar.
Gibt es eine Möglichkeit, dass wir die Artwerte trotzdem anpassen können?
Oder müsstest du das machen?
Wir könnten eine Liste mit den aktuellen Artwerten zusammenstellen, falls dir das etwas bringen würde?

**Comment by barbalex** [comment]
Ihr könnt es nicht machen. Die Daten wurden von arteigenschaften.ch importiert, aktualisieren sich aber (bisher) nicht automatisch.

Ich muss das mal genauer anschauen. Stelle es aber vorläufig zurück, da gerade mit anderem beschäftigt.

Schade, dass das nicht (mehr) in die Offerte für 2023 einfliessen kann.

**Comment by barbalex** [comment]
Habe jetzt nachgeschaut. Die Verknüpfung zu arteigenschaften funktioniert noch. Ich habe die Aktualisierungsabfrage laufen lassen. Schau doch mal nach, ob es jetzt stimmt (ich kenne keine Beispiele).

**Comment by rebeccakurz** [comment]
Super, dass das geklappt hat! Bei den Stichprobenkontrollen, die ich gemacht habe, sieht es gut aus.
