### ISSUE TITLE
Pflegeplan nicht richtig dargestellt

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#63]
Alle Pflegeplanflächen haben gleiche Farbe

**Comment by barbalex** [comment]
Wirklich? Bei mir nicht, siehe Bild unten: Es gibt Schnittzeitpunkte 1.8. und 15.8. plus nicht jährlich gemähte Flächen.
![2017-09-08_17h51_43](https://user-images.githubusercontent.com/669783/30220112-7f1699bc-94be-11e7-9de2-d70286739c8b.png)

**Comment by barbalex** [comment]
Hm. Gehe der Sache noch mehr nach

**Comment by barbalex** [comment]
o.k., jetzt werden alle Farben angezeigt
Danke für den Hinweis
