### ISSUE TITLE
Auswahl-Listen-Felder: rechts davon Link, um den gewählten Eintrag in einem neuen Fenster zu öffnen

### ISSUE THREAD

**Issue by barbalex** [barbalex/apf2#639]
Ist seit heute (Version 1.7.0) in vermehrung.ch implementiert.

Wird in apflora ein bisschen aufwändiger, weil die Datenstruktur tief verschachtelt ist. Umgekehrt gibt es in apflora viel weniger Felder, wo aus anderen Tabellen (mit Formular) ein Datensatz gewählt wird. Also insgesamt weniger nützlich.

Praktisch, wenn man den Datensatz anschauen oder editieren will, ohne den aktuellen zu verlassen.

Zusätzlich möglich: Link, der direkt zum Datensatz navigiert.

**Comment by rebeccakurz** [comment]
31.1.2024: In FloraDB momentan nicht nötig
