### ISSUE TITLE
Karte - Maustext zum Zoom nicht immer dargestellt

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#64]

**Comment by barbalex** [comment]
Ist das der Text, der erscheint bzw. erscheinen sollte, wenn man mit der Maus über eine der zwei Zoom-Schaltflächen "hovert" bzw. schwebt? "Zoom in" und "Zoom out"?

**Comment by barbalex** [comment]
Ich schliesse diesen Issue weil schon lange nicht mehr aktiv. Falls das Problem wieder auftaucht, bitte wieder öffnen
