### ISSUE TITLE
Fehlermeldung EK-Planung

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#641]
Hoi Alex
Wenn man in der FloraDB zur EK-Planung wechseln will, erscheint folgende Fehlermeldung: 

![Bildschirmfoto 2023-08-07 um 09 22 26](https://github.com/barbalex/apf2/assets/30288503/1aa5cd8e-9a08-4804-9bc7-a76530f58e3c)

Könntest du dir das bei Gelegenheit mal anschauen?
Vielen Dank und liebe Grüsse
Rebecca

**Comment by barbalex** [comment]
Hoi Rebecca
Bin noch in den Ferien aber Morgen komme ich hoffentlich dazu.
LG, Alex

**Comment by barbalex** [comment]
Das war überraschend knifflig.

Erstaunlich, dass dieser suboptimale Code erst Jahre nach der Programmierung als Fehler zutage trat.

Sollte in Version 1.102.2 gelöst sein.

**Comment by rebeccakurz** [comment]
Das scheint wieder zu funktionieren, vielen Dank!
