### ISSUE TITLE
Zahlenfelder: Änderungen mit den Pfeiltasten, die Firefox bereitstellt, werden nicht gespeichert

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#642]
Einer der Freiwilligen, der seine Daten selbst in das Online-Formular eingibt, hat mir folgendes gemeldet: 

"Ich vermute, dass die Software Apflora nicht mehr richtig funktioniert mit dem Browser Firefox, sowohl auf dem Mac wie auch unter Windows, aber auch nicht mehr mit dem Browser Safari auf dem Mac. Im vergangenen Jahr (resp. bei einer früheren Version) hat nämlich alles noch funktioniert. Das Problem ist: Die Applikation verliert die eingegebenen Zahlen, wenn man zu den Dokumenten wechselt oder wenn man sich abmeldet. Die eingegebenen Texte gehen hingegen interessanterweise nicht verloren.

Ich frage mich nun, ob das ein allgemeines Problem ist oder ein lokales Problem bei mir. Ich verwende einen älteren Mac mit High Sierra, bei dem ich zB. nicht mehr die aktuellste Version von Safari installieren kann, aber die neueste Firefox Version schon. 

Ich habe nun auf meinem Windows-PC Google Chrome installiert und damit die Daten erfolgreich eingetragen. Das heisst also, dass die Apflora unter Chrome und wahrscheinlich auch Edge korrekt funktioniert.

Was meinst du dazu? Du kannst ja mal bei den Entwicklern nachfragen, was die dazu sagen."

**Comment by barbalex** [comment]
Leider fehlt eine Beschreibung, wie man den Fehler reproduzieren kann. Mir ist nicht klar, wie ich das provozieren soll, ausser mit Firefox ganz Generell Eingaben zu testen. Werde das aber in den nächsten Tagen mal ausprobieren.

**Comment by barbalex** [comment]
Habe soeben auf Firefox getestet. Mit der "sehen als" Funktion, da ich kein Login für einen Benutzer habe, der dafür konfiguriert ist.

Funktioniert.

Ev. hast du eine Benutzerin (muss keine echte sein, einfach mit ein paar EKF), die für EK konfiguriert ist, als die ich (auf einer lokalen Kopie der Daten) einloggen könnte? Das Login könntest du mir per whatsapp übermitteln.

**Comment by rebeccakurz** [comment]
Habe dir das Login geschickt.

**Comment by barbalex** [comment]
Ein nicht aktuelles MacOS wird ziemlich sicher die darauf aufbauenden Browser beeinflussen. Sie erfinden nämlich nicht alles selber, sondern bauen auf Fähigkeiten des Betriebssystems zurück. 

Ob das ein bestimmtes Verhalten beeinflusst, ist nur sehr schwer zu wissen. Ich kann das Funktionieren auf alten Betriebssystemen/Browsersn nicht gewährleisten und es macht sicher keinen Sinn, das Budget von apflora mit solchen Anforderungen zu belasten. Denn: Das Unterstützen von alten Versionen kann ein Zigfaches der eigentlichen Entwicklung kosten. Traurig aber wahr.

Wenn man alte Versionen unterstützen will, müsste das über installierbare Versionen von apflora laufen. Was das problem mit vertretbarem Mehraufwand vermindern _kann_, aber wiederum: Vermutlich in einem Teil der Fälle und kaum in allen.

Wie weiter:
Wenn es eine Anleitung gibt, mit der Ich den Fehler auf aktuellen Versionen von Firefox und Safari provozieren kann, werde ich versuchen, das Problem zu lösen. Ansonsten müssen wir auf die Verwendung von aktuellen Versionen der Betriebssysteme und Browser verweisen. 

Falls einmal zu besonders schwierige Probleme auftauchen sollten, wäre es Aufgabe des Auftraggebers zu bestimmen, welche Browser auf welchen Betriebssystemen priorisiert werden und wieviel das kosten darf.

Aktuell ist aktuelles Chrome/Edge auf aktuellem Windows oder MacOS das Minimum, dass funktionieren sollte. Darauf wird entwickelt und (vorwiegend auf Windows) getestet.

Bei den Berichten bin ich nicht ganz sicher, ob alles auf Firefox und Safari funktioniert. Ansonsten sollte hoffentlich alles funktionieren. Und die Speicherung von eingegebenen Daten ist natürlich besonders wichtig.

**Comment by barbalex** [comment]
Hm. Er hat das Problem nur bei Zahlen? Kann das auch davon abhängen, wie sie erfasst werden? Z.B. über die Tastatur oder via irgendwelche Dinge, welche das Betriebssystem einblendet und deren Verhalten es steuert?

Bei den zahlen gibt es auf Desktop-Browsern diese (recht problematischen) Pfeile, die auf- und ab- ermöglichen (wir haben da schon das Problem des Scrollens mit der Maus, dass Eingaben ändern kann und per WEB-Standards auch soll).

Hab das jetzt probiert und tatsächlich: Auf Firefox wird die Änderung einer Zahl via den Pfeil offenbar nicht registiert :-(

Da hab ich zunächst mal den Eindruck, dass sich Firefox nicht an die WEB-Standards hält (sollte ein change-Ereignis auslösen).

Auf Safari auf Mac funktioniert's. Zumindest auf meiner aktuellen Version.

Nicht den Standards entsprechendes Verhalten eines Browsers zu patchen ist sehr aufwändig herauszufinden, zu korrigieren, zu testen. Und das Verhalten kann jederzeit (mit jedem Update des Browsers) ändern, vor allem weil es sich nicht an die Standards hält.

Was möglich wäre, wäre die Pfeile zu verstecken. Das geht aber nicht direkt und die Änderung könnte unerwartete Nebenwirkungen haben. Wäre also keine kleine Anpassung sondern aufwändig zu machen und testen.

**Comment by barbalex** [comment]
Um es nochmals klar zu machen: Dass die Änderung einer Zahl via den Pfeil im Zahlenfeld nicht gespeichert wird, liegt nicht an apflora sondern am betreffenden Browser (z.B. dem aktuellen Firefox).

Das gleiche würde passieren, wenn anderen Zahlenfelder anderer Apps oder Webseiten bearbeitet würden (welche die Pfeile nicht ausblenden und somit nicht dem WEB-Standard entsprechen).

**Comment by barbalex** [comment]
Hier noch der Bug report von Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1012818
Wir sind nicht die ersten, die darunter leiden.

**Comment by rebeccakurz** [comment]
Hoi Alex
Vielen Dank, dass du das alles getestet hast!
Dann werde ich dem Freiwilligen zurückmelden, dass wir darauf angewiesen sind, dass ein aktueller Browser für die Eingaben genutzt wird, da sonst Fehler passieren können, die wir nicht beeinflussen können.
Und dass bei der Eingabe der Zahlen diese direkt in das Feld eingegeben werden sollten und nicht mittels den Pfeiltasten verändert werden sollten, da dies bei Firefox nicht gespeichert wird. 
(Allerdings sind bei ihm die Zahlen ja ganz verschwunden, wenn der Fehler so passiert wäre, dann hätten ja noch Werte in den Feldern stehen müssen?)

**Comment by barbalex** [comment]
> Allerdings sind bei ihm die Zahlen ja ganz verschwunden, wenn der Fehler so passiert wäre, dann hätten ja noch Werte in den Feldern stehen müssen?

Das Verhalten von Firefox führt dazu, dass, wenn man mit den Pfeiltasten Zahlen erfasst/ändert keine Änderung gespeichert wird. Es bleibt also der Wert, der zuvor existierte. Gab es zuvor keinen, bleibt der Wert undefiniert.

**Comment by barbalex** [comment]
Wie weiter oben erwähnt: Ich könnte versuchen, dieses Verhalten von Firefox zu umgehen, indem ich das Feld nicht als Zahlenfeld deklariere. 

Folge: Browser zeigen keine Pfeiltasten an, Mobilgeräte bieten für die Eingabe keine Zahlen-Tastatur an. Das wäre wohl negativ zu bewerte, falls relevant.

Die zweite Folge ist schon mal nicht wirklich erwünscht (fals von Belang).

Nebeneffekt: Scrollen mit der Maus verändert keine Werte. Das wird zwar aktuell auch unterdrückt, sollte dann aber eher zuverlässiger funktionierern.

Das wäre eine Erweiterung. Mit nicht zu unterschätzendem Risiko von Nebenwirkungen, weil wir uns dann nicht an WEB-Standars halten würden.

**Comment by rebeccakurz** [comment]
Vielen Dank für deine Abklärungen. 
Dann denke ich auch, dass wir eher versuchen sollten direkt den Fehler abzufangen, als WEB-Standards zu umgehen. 
Dann würden wir das mal als Erweiterung planen für den nächsten Budgetentwurf und können dann ja nochmals diskutieren, ob wir es definitiv umsetzen wollen.

**Comment by rebeccakurz** [comment]
31.1.2024: Momentan keine Anpassung nötig, sollte nicht passieren, wenn in einem aktuellen Chrome-Browser gearbeitet wird.
