### ISSUE TITLE
QK: Status angesiedelt, aktuell; Massnahme Ansaatversuch ohne Kontrolle

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#643]
Wir haben ja ein paar Qualitätskontrollen neu geschaffen, damit man unter anderem falsch gesetzte Stati aufgezeigt bekommt. Nun hat mir Karin Sartori folgendes gemeldet: 

"Nach den Eingaben einiger Beobachtungen habe ich auch die Q-Kontrolle gemacht.
Folgende Fehlermeldung habe ich erhalten, die ich nicht auflösen kann (Orobanche lutea).
![grafik](https://github.com/barbalex/apf2/assets/30288503/5de2acb1-bebc-4741-a45c-f14a222fe143)

Es gibt zu diesen TPops zwar keine Kontrollen, jedoch Beobachtungen, daher ist der Status aktuell."

Wir haben bei dieser QK also nicht bedacht, dass eine TPop auch wegen den zugeordneten Beobachtungen aktuell sein kann. Nun ist die Frage, ob wir diese QK nochmals umformulieren können, so dass ein solcher Fall nicht als Fehler gemeldet wird? Also z.B. Status ist aktuell, Massnahme eine Ansaat, die noch nicht kontrolliert wurde, aber es gibt zugeordnete aktuelle Beobachtungen oder so ähnlich? Wäre das möglich?
Oder soll man die Meldung ignorieren, bis tatsächlich eine Feldkontrolle stattgefunden hat?
Theoretisch könnte man aus den Beobachtungen auch eine Freiwilligen-Kontrolle machen, aber dann wären wir wieder beim Kreislauf der Daten, die dann doppelt sind... (und die AV hätten mehr Aufwand). 
Habt ihr noch eine Idee, wie wir das lösen können?

**Comment by barbalex** [comment]
> Wir haben bei dieser QK also nicht bedacht, dass eine TPop auch wegen den zugeordneten Beobachtungen aktuell sein kann

Das kann ergänzt werden. Die Anpassung ist eine Erweiterung mit ein bisschen Aufwand, weil statt mit Graphql mit einer Funktion gearbeitet werden muss.

> Oder soll man die Meldung ignorieren, bis tatsächlich eine Feldkontrolle stattgefunden hat?

Falsche Qualitätskontrollen sollten wenn immer möglich vermieden werden.

> Theoretisch könnte man aus den Beobachtungen auch eine Freiwilligen-Kontrolle machen, aber dann wären wir wieder beim Kreislauf der Daten, die dann doppelt sind... (und die AV hätten mehr Aufwand).

Richtig und wichtig.

> Habt ihr noch eine Idee, wie wir das lösen können?

QK anpassen scheint mir der richtige Weg. Der Titel muss nicht geändert werden. Die QK soll einfach nicht anspringen, wenn es keine Beobachtungen gibt.

Oder wäre die Bedingung enger zu fassen? Z.B. keine Beobachtung in den letzten X Jahren?

**Comment by rebeccakurz** [comment]
Also wir haben das nochmals besprochen und würden gerne die QK anpassen, so dass sie nicht anspringt, wenn es eine zugeordnete Beobachtung gibt. 
Eine Einschränkung der Beobachtugen ist aus unserer Sicht nicht nötig (hoffentlich ;-))
Könntest du das bei Gelegenheit umsetzen?
Liegt das überhaupt noch im Budget?

**Comment by barbalex** [comment]
> Liegt das überhaupt noch im Budget?

Nein, das ist nicht offeriert. Müssten wir das nächste Mal einschliessen.

**Comment by barbalex** [comment]
In Version 1.112.0 implementiert
