### ISSUE TITLE
AP Flora DB Absturz/Fehlermeldung

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#644]
Hoi Alex 
Heute scheint die FloraDB nicht richtig zu laden bzw. abzustürzen.
Es erscheint folgende Fehlermeldung: 
![Bildschirmfoto 2023-10-09 um 16 05 02](https://github.com/barbalex/apf2/assets/30288503/8b26c975-4d30-40c4-b9be-3744e7667efd)
Cache leeren und neu anmelden hat nichts gebracht. 

Könntest du dir das bei Gelegenheit einmal anschauen?

**Comment by barbalex** [comment]
Sorry

Bin in Dahab am Tauchen. Und wegen Schnecken Internet eingeschränkt

Habe die vorherige Version live gestellt.

Sollte also wieder klappen.

LG
Alex

rebeccakurz ***@***.***> schrieb am Mo., 9. Okt. 2023, 17:07:

**Comment by rebeccakurz** [comment]
Okay, scheint wieder zu klappen!

Dann viel Spass noch beim Tauchen!! =) 
Liebe Grüsse
Rebecca

**Comment by barbalex** [comment]
In der neuen Version 1.102.8 habe ich den Code so angepasst, dass svg's mit den neuen Versionen der zuständigen Abhängigkeiten wieder korrekt laden sollten.

Unschön ist, dass beim erstmaligen Laden Fehler gemeldet werden, weil die svg's vom Browser gecached werden und die alten Pfade nicht mehr existieren. Daher muss man den Cache leeren und neu anmelden.

**Comment by barbalex** [comment]
Habe jetzt eine Mitteilung formuliert, die alle sehen
