### ISSUE TITLE
FloraDB auf Handy/Tablet: Menü verdeckt

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#645]
Bei dem Gebrauch der FloraDB auf dem Handy oder dem Tablet (Zugriff über Internetbrowser) habe ich immer wieder das Problem, dass der Menübalken oben verschwindet, mit dem man zwischen Strukturbaum, Daten, Karte, etc. hin und her wechseln kann. Da man auf dem Handy/Tablet ja jeweils nur entweder den Strukturbaum oder die Daten/Karte sehen kann, braucht es diesen Menübalken unbedingt. 
Wenn ich dann das Handy bzw. den Bildschirm drehe, dann taucht der Balken wieder auf, aber es macht das Ganze recht mühsam. 
Könntest du dir das bei Gelegenheit mal anschauen? (Bzw. für die nächste Budgetperiode vorsehen). 
Menüband ganz oder teilweise verschwunden:
![Unbenannt](https://github.com/barbalex/apf2/assets/30288503/0c59272f-996c-44a0-a29b-593a863e665c)
![Unbenannt2](https://github.com/barbalex/apf2/assets/30288503/7ee15138-bd64-41dc-a31a-ccffcc0f000c)
Beim Drehen des Bildschirms erscheint das Menüband wieder:
![Unbenannt3](https://github.com/barbalex/apf2/assets/30288503/2ead40d4-b914-44f2-9359-66de9aff3827)

**Comment by barbalex** [comment]
Mobilfähigkeit war nie eine offizielle (finanzierte) Anforderung.

Daher kann es sein, dass ich das nicht ohne Auftrag mache.

Werde aber übernächste Woche rein schauen. Vielleicht ist es bloss eine kleine Sache.

**Comment by rebeccakurz** [comment]
Ja falls es nur etwas kleines ist, wäre das super!
Sonst müssen wir das für die nächste Budgetperiode vorsehen, ich denke es wäre schon gut, wenn die FloraDB auch auf Tablets und Handys benutzerfreundlicher wird, da immer mehr damit gearbeitet wird. 

Ich denke nicht, dass eine Offline-fähige Version nötig ist, aber dass man zumindest über die mobilen Daten damit arbeiten kann, wäre super!

**Comment by barbalex** [comment]
Was hast du für ein Handy und Browser? Auf meinem (Android mit aktuellem Chrome) konnte ich es bisher nicht nachvollziehen

**Comment by rebeccakurz** [comment]
Samsung Galaxy S20 respektive Samsung Tab Active. Aber ich benutze jeweils den Samsung Internet Browser. Ich werde es auch mal mit Google Chrome versuchen, vielleicht liegt ja schon da der Fehler...

**Comment by barbalex** [comment]
Habe eine Einstellung gefunden, die allenfalls Einfluss haben könnte, und sie in Version 1.103.1 verändert. Schau mal, ob es noch gleich ist.

**Comment by rebeccakurz** [comment]
Ich habe es jetzt mal noch mit dem Chrome-Browser ausprobiert und leider scheint das Problem bei mir auch dort zu bestehen. 
Auch mit der neuen Version passiert es immer noch...

**Comment by barbalex** [comment]
In Version 1.103.3 habe ich das Styling nochmals etwas angepasst. Beeinflusst das die Darstellung des Menus auf deinem Phone?

**Comment by rebeccakurz** [comment]
Hm, ich glaube leider nicht. 
Ist aber sehr unterschiedlich, zwischendurch geht es und dann ist der Menübalken wieder weg...

**Comment by barbalex** [comment]
Aktuell fällt mir gerade nichts anderes ein und provozieren/testen kann ich es bisher selber nicht, daher lasse ich es jetzt sein 😞

**Comment by rebeccakurz** [comment]
Ja das ist okay, ich werde es beobachten, vielleicht fällt mir noch etwas auf, was hilfreich ist.

**Comment by barbalex** [comment]
Sobald neue Hinweise vorliegen, schaue ich mir das wieder an

**Comment by barbalex** [comment]
Gewünschte Informationen:

- Kurzer Beschrieb, wie sie in diesen Zustand geraten (was muss man vorher machen, bis es passiert)
- Alter und Typ des Geräts
- Version des Betriebssystems
- Benutzter Browser und seine Version

**Comment by jasminmenzi** [comment]
![Screenshot_20240201-143908](https://github.com/barbalex/apf2/assets/158478739/3db17ca4-a021-4257-ba59-ee7fcb06bb77)

Ich habe dieses Problem sehr häufig. Ich kann das Problem auslösen indem ich einige Male zwischen Karte, Daten und Strukturbaum wechsle. Nach einigen Wechseln zwischen den Reitern tritt das Problem fast immer auf. 

Gerät Fairphone 4G, Alter Gerät 2022, Betriebssystem: Android 13, FP4 Build 
Über Browser: Chrome App-Version 121.0.6167.143

**Comment by barbalex** [comment]
@jasminmenzi  Danke. Das gibt mir zu denken. Dein Browser ist aktuell, dein Betriebssystem aktuell genug und das Gerät auch.
Umso erstaunlicher, dass ich das bisher nicht selber provozieren konnte 😢

**Comment by barbalex** [comment]
@jasminmenzi dreht apflora auf deinem Handy manchmal ins Querformat? (das wäre extrem wenig hoch, könnte ev. dinge auslösen, an die ich nicht denke)

**Comment by barbalex** [comment]
Ich kann es jetzt provozieren. Es geht so: Im Navigationsbaum einen Ast öffnen, der sehr hoch ist (im Verhältnis zur Fensterhöhe).
Mal schauen, ob ich was machen kann.

**Comment by barbalex** [comment]
Es geht bei mir nur auf den Handy. Komisch.

**Comment by barbalex** [comment]
O.k., habe den Grund gefunden: Auf mobilen Geräten kann sich die Bildschirmhöhe jederzeit ändern. Wegen drehens oder weil das Betriebssystem um die Anzeige zu optimieren, eigene Leisten/Elemente dynamisch ein- und ausblendet, z.B. beim Scrollen.

Das ist der Auslöser (vermutlich). Mal schauen, ob ich die Beeinflussung der Darstellung in apflora verhindern kann.

**Comment by barbalex** [comment]
Ist in Version 1.104.7 gelöst - zumindest auf meinem Handy. Danke  @jasminmenzi

**Comment by barbalex** [comment]
Die neue Eigenschaft, die geschaffen wurde, weil ALLE Projekte unter diesem Problem litten, ist (erst) seit Herbst 2022 auf allen Browsern verbreitet. Wer ältere Browser verwendet, bekommt jetzt wohl Probleme. Aber wir gehen ja grundsätzlich von einem aktuellen Browser aus.
