### ISSUE TITLE
FloraDB als App

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#646]
In Zusammenhang mit dem verschwindenden Menübalken (#645) sind wir darauf gekommen, dass das Problem nicht besteht, wenn man die App von FloraDB verwendet (Jordan hat diese ca. im März dieses Jahr heruntergeladen). 
Nun haben wir aber auch nach längerem Suchen nicht mehr gefunden, wo er diese App heruntergeladen hat… Ist diese nicht mehr verfügbar?
Ich habe nur noch die Desktop-Version für Windows gefunden...

**Comment by barbalex** [comment]
Ist Android gemeint? Kann sein, dass ich das mal was probiert habe. War aber nie offiziell. Und daher auch nicht aktuell. Interessant, dass das jemand gefunden hat.

Auch das Windows App ist nicht offiziell bzw. finanziert. Und daher nicht mehr aktuell. Wobei in diesem Fall apflora selbst jeweils automatisch aktualisiert wird. Bloss der in der App enthaltene Chromium Browser nicht. Kann aber auch Folgen haben.

**Comment by rebeccakurz** [comment]
Ja genau, für Android. 
Aber dann ist es wohl besser, wenn Jordan nicht damit arbeitet, da es vielleicht nicht synchronisiert oder so?

**Comment by barbalex** [comment]
Wenn die aktuelle Version angezeigt wird, sollte wohl alles i.O. sein.

Vielleicht ist es wie bei der Windows App und apflora wird automatisch aktualisiert.

Falls nicht: deinstallieren und die Web-App benutzen.

**Comment by rebeccakurz** [comment]
Übrigens: Als ich die FloraDB-Webseite mit GoogleChrome aufgerufen habe, wurde ich gefragt, ob ich die FloraDB als App installieren möchte:
![Screenshot_20231026_174725_Chrome](https://github.com/barbalex/apf2/assets/30288503/56b47ddf-b9bf-4260-b620-e8f0c4f894a0)
Das habe ich dann gemacht und es zeigt auch die aktuelle Version an. Leider habe ich das Problem mit dem Menübalken auch hier... 
![Screenshot_20231027_085257_Chrome](https://github.com/barbalex/apf2/assets/30288503/2ad42a0d-a670-4ab1-94bc-848c77d88a3d)

**Comment by barbalex** [comment]
App ist ein weiter Begriff.

Es gibt die (klassischen) Apps, gebaut spezifisch für Windows, MacOS, iOS oder Android. Davon habe ich oben gesprochen.
Sie sind nicht über eine URL erreichbar (aber Links können unter Umständen mit ihnen geöffnet werden). Sie sind meist nicht mit JavaScript entwickelt. Ihren Code immer aktuell zu halten ist viel aufwändiger (auch für die Benutzerin) als bei Web-Apps. Sie funktionieren nur auf dem Betriebssystem, für das sie entwickelt wurden und dort auch meist nur auf bestimmten Versionen desselben.

Es gibt moderne Web-Apps oder PWA (progressive web app). Sie werden mit JavaScript geschrieben. Apflora ist eine solche. Ich habe das dokumentiert: https://apflora.ch/Dokumentation/pwa. Sie verwenden den Standard-Browser des jeweiligen Betriebssystems, aber das ist für die Benutzerin nach einer "installation" kaum mehr erkenntlich.

PWA kann man sogar (nach dem ersten Start bzw. "Installation) vollständig Netz-unabhängig bzw. offline-fähig bauen. vermehrung.ch ist ein solches Beispiel. Es synchronisiert Daten und aktualisiert den Code wenn eine Verbindung besteht, funktioniert aber auch ohne gut.

Die oben erwähnte Windows-App von apflora ist eine in C++ gepackte Version, die Browser und apflora-Code enthält. Die oben erwähnte Android-Version wurde wohl in Java verpackt.

Die Grenze zwischen den beiden App-Typen wird von Google und Microsoft mittlerweile sehr bewusst verwischt, will heissen: Als Benutzer kann man sie je länger desto weniger unterscheiden (Windows bietet glaube ich sogar schon die Möglichkeit, Web-Apps im App-Store anzubieten).

Das hast du soeben erlebt.

Wenn du bei der Installations-Frage "ja" sagst:
- Speicherst du ein Symbol für apflora auf den Home-Bildschirm
- Wenn du apflora von dort aus öffnest, siehst du kaum mehr, dass es im Browser läuft. Es ähnelt jeder anderen, aus dem App-Store installierten App
- Auf Windows (und ich glaube auch auf Android) kannst du die App auch wieder wie andere Apps im entsprechenden App-System-Menü deinstallieren

Es bleibt aber eine Web-App mit deren Vorteilen, wie z.B. automatische Aktualisierung.

**Comment by rebeccakurz** [comment]
Okay, super, danke für diese Infos!

**Comment by barbalex** [comment]
In Version 1.103.2 habe ich das Styling nochmals etwas angepasst. Beeinflusst das die Darstellung des Menus auf deinem Phone?

**Comment by barbalex** [comment]
In Version 1.103.3 noch ein letztes Detail verändert
