### ISSUE TITLE
Koordinaten ausserhalb Bezugssystem

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#648]
Hoi Alex
René Bertiller hat mir noch untenstehendes Mail betreffend Koordinaten einer süddeutschen Population geschrieben. Ich weiss, dass wir dieses Problem bereits schon hatten, kann mich aber nicht mehr erinnern, wie wir es gelöst hatten. In den Issues habe ich nur etwas gefunden, dass wir bereits einmal eine Ausweitung der Koordinaten vorgenommen hatten (#167). Ich bin mir aber nicht ganz sicher, ob damit eigentlich das Problem gelöst sein sollte... Kannst du mir da weiterhelfen?
Vielen Dank und liebe Grüsse
Rebecca

"Liebe Rebecca
 
In der Flora-Datenbank gibt es eine Beschränkung bei den Koordinaten, die es mir nicht erlauben einer süddeutschen Population von Thesium linophyllon (2700799 / 1302856) Koordinaten zu geben. Limitiert ist hier die Y-Koordinate, die X-Koordinate wird tolerieret. Dies ist insofern unschön, als es bei der Qualitätskontrolle dann heisst, dass bei dieser Population die Koordinaten fehlen…
 
Soll man das Limit bei der Koordinate anpassen, damit die Angaben toleriert werden, oder lohnt sich das nicht? Bitte entscheide du und leite den Wunsch allenfalls Alex weiter, falls du das sinnvoll findest.
 
Danke, herzliche Grüsse
René"

**Comment by barbalex** [comment]
Das Problem ist: Das Schweizer Referenzsystem LV95 wurde explizit für die Schweiz gebaut. Es ist nicht vorgesehen, um Koordinaten ausserhalb zu beschreiben. Es ist auch aufgrund seines planen Bezugssystems nicht für grosse Flächen geeignet. Je weiter weg, desto weniger genau würde es.

Um weltweite Koordinaten bzw. solche ausserhalb eines Rechtecks, das eng an die Schweizer Grenzen anliegt, zu erfassen, muss ein sphärisches Koordinatensystem benutzt werden.

Und genau das haben wir vor ein paar Jahren für apflora implementiert: WGS84, das mit Längen- und Breitengraden funktioniert. 
Koordinaten in apflora werden immer in WGS84 gespeichert. Gibt jemand im Formular Schweizer LV95 ein, werden sie sofort in WGS84 umgerechnet. Bei der Anzeige und in Exporten werden sie wieder in LV95 umgerechnet.

In den Formularen wird es in der Dezimalschreibweise dargestellt und kann auch so erfasst werden. Beispiel:
- Längengrad: 8.781013395
- Breitengrad: 47.919103167
- URL für die Teilpopulation, die ich so verortet habe: https://apflora.ch/Daten/Projekte/e57f56f4-4376-11e8-ab21-4314b6749d13/Arten/6c52d174-4f62-11e7-aebe-67a303eb0640/Populationen/70d2b98f-4f62-11e7-aebe-d3b09a4611dd/Teil-Populationen/76c7fe44-4f62-11e7-aebe-6b56ab796555?projekteTabs=tree&projekteTabs=daten&projekteTabs=karte

Obiges Beispiel liegt ausserhalb des akzeptierten Bereichs für LV95. Aber diese Koordinate kann in apflora auf zwei Arten generiert werden:
1. Die Längen- und Breitengrade in der Dezimalschreibweise einfügen. Diese Schreibweise gibt mir z.B. Google Maps bei einem Klick auf einen Punkt. Jedes GPS und GPS-App sollte das können.
2. Kontextmenu "verorte auf Karte" im Navigationsbaum bei der Teilpopulation wählen, dann die entsprechende Stelle auf der Karte Doppelklicken

In beiden Fällen wird zwar ein Wert für LV95 gerechnet und im Formular dargestellt. Und dieses ist im Grunde genommen unzulässig (korrekter wäre, wenn apflora bei solchen Koordinaten bei den Feldern für die LV95 X bzw Y-Koordinaten anzeigen würde, dass sie nicht korrekt berechnet werden können). Aber: apflora speichert alle Geometrien als WGS84, daher ist der gespeicherte Punkt korrekt.

Mir ist nicht 100% klar, wie René für einen Punkt ausserhalb der offiziellen Grenzen von LV95 LV95-Koordinaten generieren konnte. Ev. arbeitet sein GPS bzw. Handy-App etwas grosszügig... Korrekt wäre gewesen, wenn sein App die Benutzung von LV95 an diesem Ort abgelehnt hätte.

Nicht dass es im konkreten Fall so viel ausmacht (wohl nur ein paar Zentimeter). Aber wenn man mit LV95 z.B. den Nordpol verorten wollte, gäbe es total widersinnige Werte.

**Comment by barbalex** [comment]
Das mit den WGS84 ist übrigens dokumentiert: https://apflora.ch/Dokumentation/koordinaten/?projekteTabs=tree&projekteTabs=daten&projekteTabs=karte

**Comment by rebeccakurz** [comment]
Vielen Dank für deine ausführliche Antwort!!
