### ISSUE TITLE
Ansicht "EKF sehen als": Scrollen nicht möglich

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#649]
In der Ansicht "EKF sehen als", wo man die Kontrollen der Freiwilligen aufrufen kann, ist das Scrollen beim Protokollblatt nicht möglich. Haben es auf Chrome und Firefox ausprobiert. Scrollen in der Auflistung der Kontrollen links funktioniert hingegen.

Könntest du dir das bei Gelegenheit mal ansehen?

**Comment by barbalex** [comment]
Danke für den Hinweis.

Sollte in Version 1.103.6 korrigiert sein.
