### ISSUE TITLE
Karte hängt sich auf nach neu laden

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#652]
Zudem hängt sich jedesmal, wenn ich die DB aktualisiere, die Karte auf (siehe Screenshot).
Wenn ich die Karte aus- und wieder einblende, geht es nachher wieder.

![Bildschirmfoto 2023-11-28 um 08 26 41](https://github.com/barbalex/apf2/assets/30288503/ba12c34c-96f6-49b7-a44d-195052a71862)

**Comment by barbalex** [comment]
Hast du eine Ahnung, seit wann das so ist?

**Comment by rebeccakurz** [comment]
Hm ich hätte jetzt gesagt, mir ist es in den letzten 1, 2 Wochen aufgefallen, aber Evelyn meinte gerade es sei bei ihr schon etwa vor einem Monat aufgetaucht...

**Comment by barbalex** [comment]
In Version 1.103.11 habe ich angepasst:

## 1. Anderen Fehler
Wenn man die Grösse der Karte veränderte, wurde diese nicht nachgezeichnet. Das ist ein Fehler der verwendeten abhängigen Software, aber es gibt eine Möglichkeit, das nachzubessern. Habe ich gemacht.

## 2. Diesen Fehler
Das ist vermutlich auch ein Fehler der verwendeten abhängigen Software. Ich konnte es nicht befriedigend lösen. Neu ist es so, dass der Kt. ZH gezoomt wird, wenn man neu lädt. Der zuvor existierende Zoom level geht leider verloren.

Mehr kann ich glaube ich zur Zeit nicht machen :shrug:

**Comment by barbalex** [comment]
Hm. Die Lösung, um den hier von dir beschriebenen Fehler weniger schlimm zu machen, könnte Nebenwirkungen haben.
Sag mir, wie es für euch funktioniert. Ev. muss ich das wieder ausschalten.

**Comment by rebeccakurz** [comment]
Es ist dahingehend besser, dass die Karte nicht mehr abstürzt. 
Was aber ist (und wahrscheinlich mit dem Zoom zu tun hat?) ist, dass die Karte nicht mehr den zuvor gezeigten Ausschnitt zeigt, sondern auf einen "früheren" Ausschnitt zurückfällt.

**Comment by barbalex** [comment]
Genau. Solange nichts nerviges passiert, lasse ich es so
