### ISSUE TITLE
"QK: nur aktiven Pfad im neuen Fenster anzeigen": nicht so übersichtlich 

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#653]
Hoi Alex
Du hast dieses Jahr ja den Issue #84 umgesetzt, so dass wenn man aus der Qualitätskontrolle ein neues Fenster öffnet, nur noch der aktive Pfad angezeigt wird. Grundsätzlich ist das eine hilfreiche Neuerung, beim effektiven Arbeiten hat sich jetzt aber herauskristallisiert, dass es unterhalb der Ebene der Teilpopulation leider etwas unübersichtlich wird. Also wenn ich zum Beispiel einen Teilpopulationsbericht erstellen muss, dann muss ich immer wieder auf eine Ebene oder zwei höher wechseln, um die aktuelle Feldkontrolle mit der vorherigen zu vergleichen, was ich ja für die Beurteilung des Berichts machen muss. 
Daher haben wir uns überlegt, ob es vielleicht möglich ist, zukünftig nur bis auf die Ebene der Teilpopulation den aktiven Pfad anzuzeigen und die darunterliegenden Ebenen aber immer sichtbar zu lassen?
Also dass so wie im Screenshot diese Ebene wie fixiert wird: 
<img width="419" alt="Unknown" src="https://github.com/barbalex/apf2/assets/30288503/a567ef95-b29d-4985-a1da-665a719a813a">

**Comment by barbalex** [comment]
## 1. Variante: Objekt öffnen auf Stufe Teilpopulationen beenden

Zuerst habe ich dich so verstanden, dass nur noch bis zur Ebenen Teilpopulationen geöffnet wird. Hier meine ursprüngliche Antwort darauf:

Machbar sollte das schon sein.

Ist es auch nachvollziehbar und verständlich?

Im Moment ist es so realisiert, dass immer direkt das Objekt geöffnet wird, das Anstoss für die QK war. Das macht sehr viel Sinn, oder nicht?

Je nach QK kann dieses Objekt oberhalb der von dir jetzt erwähnten Stufe (TPop) liegen, oder darunter. Künftig würde also manchmal das Objekt direkt geöffnet, manchmal aber nicht. Die Benutzerin muss das dann begreifen und selber weiter navigieren, bzw. zuerst nachschauen, wohin sie navigieren muss. Macht das Sinn?

Die Funktion kann ja mit einem Menu ein- und ausgeschaltet werden:
<img width="792" alt="2023-12-18_10h20_38" src="https://github.com/barbalex/apf2/assets/669783/ad6fb869-bef4-4aa4-b1e6-26007b3fb5e8">

Dieses Menu müsste künftig heissen: "nur den aktiven Pfad anzeigen (maximal bis zur Ebene Teilpopulationen)".

Ich finde das nicht besonders klar.

Es würde mich nicht überraschen, wenn bei einer Abschaffung plötzlich einige Benutzerinnen meinen, vorher sei es besser gewesen. Daher würde ich eher ein zusätzliches Menu dafür schaffen um zu testen, was die BenutzerInnen lieber machen. Und man müsste bei den QK einen zusätzlichen Link anbieten, um so zu öffnen.

Im Prinzip kann eine Benutzerin heute jederzeit die übrigen Ebenen wieder einblenden, um auf Ebene der Teilpopulationen sich eine Übersicht zu verschaffen.

## 2. Variante: Auch andere Pfade laden

Heute wird ja im Navigationsbaum NUR der aktive Pfad geladen. Wenn ich deine Frage nochmals genau lese, könnte sie auch heissen: Zwar wird das Objekt der QK direkt geöffnet. Im Unterschied zu heute, werden aber auch andere Objekte im Baum geladen, damit man dorthin navigieren kann.

Das ist natürlich auch möglich. Fragt sich nur, welche anderen Objekte geladen werden sollen, wieso, und ob das für die Benutzerin nachvollziehbar ist.

Wenn ich dich richtig verstehe, schlägst du vor, bis auf die Stufe Teilpopulationen hinauf alle Objekte zu laden (was natürlich nur zutrifft, wenn ein Objekt unter dieser Stufe angezeigt wird).

Das ist eine willkürlich gewählte Grenze. Sie bedeutet, dass die Benutzerin nun bis auf die Stufe Teilpopulationen hinauf navigieren und andere Teilpopulationen sowie die Daten darunter vergleichen kann. Das zugehörige Menu müsste korrekt heissen: "den aktiven Pfad anzeigen und alle Daten bis hinauf auf Stufe Teilpopulationen laden".

Wenn die Benutzerin auf Stufe Populationen vergleichen will, ist das nicht möglich.

Damit sie das machen kann, muss sie auf "nur den aktiven Pfad" klicken um dieses Menu zu deaktivieren. Dann wird wieder der vollständige Navigationsbaum gebaut, der aktive Pfad bleibt aktiv.

Bei dieser Variante kann es sein, dass die 597 Arten die Sache unübersichtlicher machen, als praktisch wäre.

Dann wäre also eine Darstellung vielleicht nützlich, welche nur die Daten der gerade aktiven Art lädt.

Dazu könnten wir ein zusätzliches Menu schaffen: "Nur Daten der aktiven Art anzeigen".
Navigiert man mit dieser Option im Navigationsbaum oberhalb der Ebene Art, würden alle Arten angezeigt. Sobald man in eine Art navigiert, werden nur noch ihre Daten geladen.

Das ist dann sehr ähnlich, wie wenn man auf diese Art gefiltert hätte.

Ich weiss nicht, ob das im Alltag wirklich nützlich wäre und gebraucht würde. Und ob einen Filter setzen nicht auch funktionieren würde. Das müsst ihr beurteilen.

**Comment by rebeccakurz** [comment]
Hm jetzt bin ich auch nicht ganz sicher, ob ich dich richtig verstanden habe.... Also ich glaube Variante 1 habe ich nicht gemeint. Variante 2 ist glaube ich das, was ich gemeint habe. 
Allerdings ist für mich die Stufe, bis zu der navigiert werden muss, nicht ganz so willkürlich gewählt, da ich die meisten Probleme auf dieser Stufe beheben muss. Also die Stufe, die im Screenshot im obersten Issue gezeigt wird, wäre das vielleicht aber eher die Stufe Population anstatt Teilpopulation?
Vielleicht wäre dann auch eine gute Umschreibung für unseren Wunsch: "Filtern nach der Population, die ein Problem hat".

Meistens geht es bei der QK ja darum, das ein Bericht auf TPop-Ebene oder Pop-Ebene vergessen wurde oder ein Bearbeiter oder eine Koordinate oder..., dann würde mir eine Darstellung der Population reichen. 
Mir fällt kein Fall ein, wo ich mehrere Populationen miteinander vergleichen müsste. 
Wenn man jetzt "nur Daten der aktiven Art anzeigen" schaffen würde, hätte man bei einigen Arten wieder das "Problem", dass sie so viele Populationen haben, dass es unübersichtlich wird. 

Was meinst du?

**Comment by barbalex** [comment]
Also vermutlich diese Lösung:  "Den aktiven Pfad anzeigen und alle Daten bis hinauf auf Stufe Population laden, falls die QK eine tiefere Stufe betrifft".

Das müsste geändert werden:
- In der Liste der QK wird neben der QK ein zusätzlicher (?) Link angeboten. Nur bei Objekten unter der Stufe Population
- Dieser Link öffnet wie bisher das Objekt der QK in einem neuen Fenster (?)
- Er setzt aber auch einen Filter auf die Population (damit die übrigen Populationen nicht angezeigt werden)
- Er setzt zusätzlich einen Filter auf die Art (damit nicht alle übrigen Arten angezeigt werden)
- Die Eigenschaft "nur den aktiven Pfad anzeigen" wird nicht aktiviert
- Will jemand im neu geöffneten Fenster weiter arbeiten, kann sie die Filter im Navigationsbaum entfernen

Hier zur Erläuterung ein Beispiel, wie das neue Fenster geöffnet würde, wenn die QK ein Problem in der Anpflanzung im Jahr 2000 gefunden hätte:
<img width="657" alt="2023-12-19_10h26_41" src="https://github.com/barbalex/apf2/assets/669783/f1c851dc-a264-4e35-8904-34e9fbec23d5">

Was meinst du?

**Comment by barbalex** [comment]
Bemerkung: Wenn alle übrigen Ordner (z.B. AP-Ziele, Benutzer, Werte-Listen etc.) nicht sichtbar sein sollten, müsste das anders programmiert werden und gäbe mehr Aufwand.

Das wäre dann ähnlich wie die aktuelle Funktion "nur den aktiven Pfad anzeigen" und würde dort als neues Menu erscheinen.

**Comment by barbalex** [comment]
Offenbar werdet ihr vom Navigationsbaum teilweise überwältigt.

Ich arbeite an einem neuen Projekt an einer Form der Navigation, die genau dieses Problem verringern soll. Dein Anliegen bestätigt diese Idee 😀.

Ich könnte sie dir dann mal bei Gelegenheit demonstrieren. Würde mich interessieren, was du denkst.

**Comment by rebeccakurz** [comment]
"Also vermutlich diese Lösung: "Den aktiven Pfad anzeigen und alle Daten bis hinauf auf Stufe Population laden, falls die QK eine tiefere Stufe betrifft". "--> Ja, ich glaube das wäre hilfreich, so könnten zb bei der Beurteilung der Populationsberichte die Teilpopulationen miteinander verglichen werden. 
"Bemerkung: Wenn alle übrigen Ordner (z.B. AP-Ziele, Benutzer, Werte-Listen etc.) nicht sichtbar sein sollten, müsste das anders programmiert werden und gäbe mehr Aufwand." --> Ich denke, die übrigen Ordner würden nicht gross stören, da sie sich ja darunter befinden. Ich werde aber noch ein paar andere aus dem Büro fragen, was sie dazu meinen. 

"Ich könnte sie dir dann mal bei Gelegenheit demonstrieren. Würde mich interessieren, was du denkst." --> werde ich mir gerne anschauen! :-)

**Comment by rebeccakurz** [comment]
31.1.2024: Gibt bereits Möglichkeit, bei den Einstellungen wieder auf die gesamte Ansicht umzuschalten (und nicht mehr nur den aktiven Pfad anzuzeigen). Diese Möglichkeit nutzen und auch den AV nochmals demonstrieren.
