### ISSUE TITLE
Massnahme: evt. weitere Einheit "Knollen" 

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#654]
noch zu diskutieren: 
evt. bei den Massnahmen eine weitere Einheit "Anzahl Knollen" oder Weiteres (neben Anzahl Pflanzen und Anzahl Trieben) schaffen, damit solche Spezialfälle berücksichtigt werden können.

**Comment by barbalex** [comment]
Dass eine Einheit nur bei den Massnahmen erscheinen würde ist meines Wissens neu und würde die Sache aufwändiger machen

**Comment by barbalex** [comment]
Na ja, bei den Massnahmen ist das mit den Einheiten mittlerweile schon recht kompliziert geworden ☹️

**Comment by rebeccakurz** [comment]
31.1.2024: momentan nicht nötig, für Anzahl Knollen hat ChS eine andere Lösung gefunden.
