### ISSUE TITLE
Bemerkungsfeld bei TPop weiter nach oben 

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#655]
Noch eine letzte Meldung bevors ab in die Weihnachtsferien geht ;-)
Wäre es möglich, das Bemerkungsfeld (siehe Screenshot) bei den Teilpopulationen weiter nach oben zu schieben?
<img width="1048" alt="Bildschirmfoto 2023-12-21 um 16 26 51" src="https://github.com/barbalex/apf2/assets/30288503/8c41a280-2ed6-498a-9942-f66b750c910e">
Zum Beispiel gleich unter die Gemeinde?
<img width="1043" alt="Bildschirmfoto 2023-12-21 um 16 32 17" src="https://github.com/barbalex/apf2/assets/30288503/576101ac-cf16-462f-8ac5-b778c9bfa95b">

**Comment by barbalex** [comment]
Klar.

Hat du noch andere Felder zum schieben?
Ginge im gleichen.

**Comment by rebeccakurz** [comment]
Nein, ich glaube sonst ist es in Ordnung. Danke!

**Comment by barbalex** [comment]
In Version 1.104.0 implementiert

**Comment by rebeccakurz** [comment]
Super, danke!
