### ISSUE TITLE
Grafiken im PDF Jahresbericht

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#656]
Hoi Alex

Ich bin gerade von einer Artverantwortlichen darauf hingewiesen worden, dass in den PDFs der Jahresberichte der einzelnen Pflanzen die Grafiken keinen Verlauf darstellen, sondern nur die Daten von 2023 zeigen
![Bildschirmfoto 2024-01-08 um 14 31 21](https://github.com/barbalex/apf2/assets/30288503/23f8867c-dbee-4ee1-85f6-c028ec5b8cc8)
Das sollte nicht so sein oder?

**Comment by barbalex** [comment]
Ja, das sollte nicht sein.

Wie es aussieht, fehlen die histories von Pop und TPop.

Das erklärt auch, warum es keine letztes Jahr neu erlosche TPop gibt: die Abfrage fand keine früheren Werte...

Ich muss da mal etwas graben. Die Daten sollten in den Sicherungen existieren.

**Comment by barbalex** [comment]
Die Datenbank sichert immer, wenn am Tag Daten geändert wurden.
Die letzte Sicherung stammt vom 4.1.2024, 23 Uhr.
Darin sind die histories noch enthalten > Ich kann sie also daraus wiederherstellen.

Ich schliesse daraus, dass sie heute verschwunden sind.

Hast du eine Ahnung, ob heute etwas spezielles passiert ist bzw. gemacht wurde?

**Comment by rebeccakurz** [comment]
Ich habe heute morgen die Daten historisiert, könnte das etwas ausgelöst haben?
![Bildschirmfoto 2024-01-08 um 15 10 42](https://github.com/barbalex/apf2/assets/30288503/9a2e52cd-46d3-4ffe-b868-8159d5cd77be)

Sonst wüsste ich nicht, ob noch etwas spezielles gemacht wurde.

**Comment by barbalex** [comment]
Ja, da scheint ein Wurm drin zu stecken.

Ich habe soeben die histories wiederhergestellt. Dann neu historisiert. Und siehe da, die früheren sind wieder weg.

Ich gehe dem auf den Grund.

**Comment by barbalex** [comment]
Wenn bei einer einzelnen Art der Bericht angezeigt wird, werden keine alten histories gelöscht.
Das passiert nur, wenn man den Bericht für alle Arten anzeigt.

Aktuell habe ich die Daten wiederhergestellt. Solange ihr einzelne Arten anzeigt, seht ihr alle Jahre.

In der Zwischenzeit suche ich das Problem.

**Comment by rebeccakurz** [comment]
Okay, danke. Dann hoffe ich du findest das Problem.

**Comment by barbalex** [comment]
Problem gefunden und gelöst.

SQL kann ehrlich gesagt manchmal total unlogisch sein 😢

**Comment by rebeccakurz** [comment]
Super konntest du das Problem lösen, danke!
