### ISSUE TITLE
Scrollen innerhalb Text JB

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#659]
Eine AV hat auch noch folgendes gemeldet:

Noch mehr Probleme mit Scrollen.

Innerhalb der Abschnitte, wenn sie lang sind, sollte man auch scrollen können. Geht aber auch nicht. Ich kann im langen Text zur Analyse also nicht nach unten scrollen und der fortlaufende Text erscheint aber auch nicht in der zweiten Spalte.

Ich habe den Inhalt von 2022 kopiert (mit Ctrl A und Ctrl C, allein mit der Maus hätte ich gar nicht den ganzen Text erfassen können). Nun eben, aber abändern kann ich den Text so nicht.
![Unknown-2](https://github.com/barbalex/apf2/assets/30288503/4752f4ef-0f30-4ca8-a901-1cbc9f1fcc77)

(Da ich nicht weiss, ob es sich um das selbe Problem handelt wie das Scrollen allgemein, mache ich einen neuen Issue.)

**Comment by barbalex** [comment]
Ja, das betrifft das Scrollen in einem anderen Formular, daher musste ich es separat korrigieren. Sollte in Version 1.104.3 korrigiert sein. Falls ich das Problem richtig verstanden habe.

**Comment by rebeccakurz** [comment]
Das scheint auch wieder zu funktionieren. 
Respektive ich muss gar nicht Scrollen, weil der gesamte Text angezeigt wird. Allerdings muss ich manchmal zweimal in den Text reinklicken, bevor es richtig angezeigt wird, kann aber nicht sagen, wann das der Fall ist.
