### ISSUE TITLE
Feldkontrollen/Massnahmen - Scroll nach unten funktioniert nicht immer

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#66]
Wie auch beim Springen geht das Scrollen nach Unten auch nicht immer, es gibt dann einfach keine Scroll-Leiste rechts

**Comment by barbalex** [comment]
Hm. Gibt es irgend eine Art, wie man das zuverlässig provozieren bzw. nachvollziehen kann? Bisher ist mir das noch nicht passiert.

**Comment by csalzmann** [comment]
Ist mir jetzt auch nicht mehr passiert
![screenshot 7](https://user-images.githubusercontent.com/6047564/30849649-5227f016-a2a3-11e7-8403-74aa460d7dd3.png)
. Was aber ist: bei der Feldkontrolle wird Fenster mitten durch den GUID und den Kopier-Button des GUIDs abgeschnitten (bei Massnahmen ist das nicht so). Ist einfach eine kleine Unschönheit.

**Comment by barbalex** [comment]
richtig, das habe ich auch gemerkt - und in der Entwicklungsversion behoben

Ich schliesse diesen Issue. Falls Scrollen wieder ausfällt, einfach wieder öffnen

**Comment by rebeccakurz** [comment]
Das Scrollen funktioniert nicht immer zuverlässig. Es passiert häufig, wenn ich z.B. eine neue Massnahme eingebe und in ein Feld klicke, es ausfülle und dann weiter nach unten scrollen will. Dann muss ich zuerst irgendwo anders hinklicken, dann geht es wieder.

**Comment by barbalex** [comment]
Richtig.

Das ist geplant und nicht anders zu lösen.

Ich gehe nämlich nicht davon aus, dass bei dir die Scroll-Balken vorhanden sind. Der oben beschriebene Fehler war, dass das Formular grundsätzlich nicht scrollbar war, weil die Scroll-Balken fehlten.
Aber da du das nicht erwähnst: korrigiere mich, wenn bei dir die Scroll-Balken fehlen sollten.

Das geplante Verhalten geht so:

- Wenn man scrollt, sollte das Formular scrollen, wenn es höher als der Bildschirm ist (das ist, was du erwartest)
- **Aber: Wenn man in einem Zahlenfeld scrollt, sollte die Zahl nicht verändert werden**. Siehe https://github.com/barbalex/apf2/issues/25
- Das ist aber das Standard-Verhalten von Zahlenfeldern: Lässt man darin Scrollen zu, werden Zahlen verändert.
- Folglich muss ich in Zahlenfeldern das Scrollen unterdrücken
- Folglich scrollt auch das Formular nicht, wenn sich der Fokus in einem Zahlenfeld befindet

Probier es aus: Das von dir beschriebene Verhalten tritt nur ein, wenn du es in einem Feld probierst, in dem nur Zahlen aktzeptiert werden, z.B. Massnahmen > Fläche in m2. Scrollst du in einem anderen Feld, funktioniert es.

**Comment by rebeccakurz** [comment]
Okay, alles klar. Vielen Dank!
