### ISSUE TITLE
Scrollen EK-Planung

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#660]
Da scheint der Wurm drin zu sein bei der Scrollfunktion...
Meldung von AV: 
Ich habe gerade festgestellt, dass auch bei der EK-Planung das Scrollen nur bedingt funktioniert.

Immerhin hat es einen Scrollbaklen rechts. Im Screenshot unten sieht es ja so aus, als wäre der Scrollbalken bereits unten angelangt. Wenn ich das Fenster nach unten grösser mache, dann erscheinen aber noch mehr EKs. Es kommen nach Cardamine ja noch Sagittaria, Sparg und Typha shut. De facto hat es also einen Scrollbalken, aber man kann nicht damit scrollen.

Ich kann nur arbeiten, in dem ich Vergrösserung immer kleiner mache. Ich kanns jetzt dann aber nicht mehr lesen, trotz Lesebrille..
![Unknown](https://github.com/barbalex/apf2/assets/30288503/8c7b0e13-dbfb-4a8d-b8a3-258004a3be62)

**Comment by rebeccakurz** [comment]
Wenn nur jeweils eine Art angezeigt wird, dann scheint es zu funktionieren.

**Comment by barbalex** [comment]
Aha Wenn man genug Arten gleichzeitig listet, wird Scrollen auf einer höheren Ebene ausgelöst, was das Scrollen der darunter liegenden Ebene verhindert.

Mal schauen, was ich machen kann.

**Comment by barbalex** [comment]
> Ich weiss gar nicht ob es vorgesehen war, dass mehrere Arten untereinander angezeigt werden können? 

Das war keine Vorgabe, aber es sollte gehen. Letztlich kann es die Leistungsfähigkeit beeinflussen, wenn tausende Datensätze verarbeitet und angezeigt werden müssen.

Das betrifft einerseits den eigenen PC. Andererseits aber auch den Server. Wenn wir also merken sollten, dass der ausgebremst wird, müssten wir das ev. einschränken.

Das Scrollen sollte in Version 1.104.4 möglich sein.

**Comment by barbalex** [comment]
Zur Server-Auslastung: Das Maximum der CPU-Auslastung in den letzten 24 Stunden war 7%.
Wir haben also noch Reserven.

**Comment by rebeccakurz** [comment]
Okay, danke!
