### ISSUE TITLE
Kontrollen in potentiellen Wuchsorten aus Export für InfoFlora ausschliessen

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#661]
In dem Export mit allen durchgeführten Kontrollen, den du jeweils im Frühjahr machst und den wir an InfoFlora abgeben, möchten wir gerne alle Kontrollen, welche in Teil- oder Populationen mit Status "potentieller Wuchsort" durchgeführt wurden, vom Export ausschliessen. 

Wäre das möglich?

**Comment by barbalex** [comment]
Gemacht: https://github.com/barbalex/apf2/blob/1ce083c777afac6e3acb62a1467df3c270990f23/sql/apflora/export_info_flora/2024.sql#L206
