### ISSUE TITLE
Strukturbaum "springt" ungewollt

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#662]
Hoi Alex
Beim Arbeiten in der FloraDB ist uns aufgefallen, dass der Strukturbaum manchmal ungewollt nach oben springt. So wie wir das eruieren konnten, passiert es immer dann, wenn bei einer Art die Populationen ausgeklappt sind und ich bei der selben Art einen weiteren Ast der gleichen Ebene auf- oder zuklappe (also z.B. Beobachtungen nicht beurteilt, EK-Zähleinheiten, etc.)
Könntest du dir das mal anschauen? Reicht dir diese Beschreibung?

**Comment by barbalex** [comment]
Ich kann das nachvollziehen. Habe auch eine Lösung gefunden. Die gibt aber ziemlich viel Arbeit. Mal schauen, wie ich vorwärts komme.

**Comment by barbalex** [comment]
Habe eine bessere Lösung gefunden. Und die war schon grösstenteils implementiert, weil für andere Zwecke genutzt 😆 
Sollte in Version 1.104.6 behoben sein.

**Comment by rebeccakurz** [comment]
Super, das scheint geklappt zu haben, danke!
