### ISSUE TITLE
neue QK: Bekannt seit ist jünger als die erste durchgeführte Massnahme

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#663]
Wir würden gerne noch eine neue QK einführen: "Bekannt seit ist jünger als die erste durchgeführte Massnahme". 
Wäre das möglich? Es gibt wohl nicht so viele Fälle, wo das der Fall ist, aber dann würden diese auch noch aufgezeigt werden.

**Comment by barbalex** [comment]
Ja, das ist möglich

**Comment by barbalex** [comment]
Ist implementiert. Bin aber nicht ganz sicher, ob das in jedem Fall sinnvoll ist: https://apflora.ch/Daten/Projekte/e57f56f4-4376-11e8-ab21-4314b6749d13/Arten/6c52d173-4f62-11e7-aebe-2bd3a2ea4576/Populationen/92e6522e-7cc7-11ed-b5c8-27f6fa34bb44/Teil-Populationen/aea0f3e4-1410-11e9-97a0-1f41e1f5afc9/Massnahmen/923b3b32-1e3e-11e9-97bf-4b4234162e4e?onlyShowActivePath=true
