### ISSUE TITLE
Hochgeladene Dateien (pdfs) direkt in FloraDB anzeigen

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#668]
Wäre es möglich/machbar, dass man alle hochgeladenen Dateien gleich direkt in der FloraDB anzeigen lassen bzw. ansehen könnte? So wie man ja die Bilder direkt in einer Galerie anschauen kann. 
Momentan muss man die Dateien, z.B. pdfs ja zuerst herunterladen. 
Beispiel: 
![Bildschirmfoto 2024-02-14 um 14 30 36](https://github.com/barbalex/apf2/assets/30288503/23193242-eea7-4216-93bc-ad32c01e7f0e)

**Comment by rebeccakurz** [comment]
und es evt. auch noch in die Offerte 24 aufnehmen

**Comment by barbalex** [comment]
Dass es die Möglichkeit gibt, Bilder in einer Galerie anzuzeigen, hast du ja offenbar gesehen.

Für andere Dateitypen müsste das für jeden Dateityp einzeln programmiert werden.

Was ich bauen könnte, wäre eine eigene, erweiterte Galerie:

- oben eine Titelzeile, die den Dateinamen zeigt und Navigations-Buttons (rechts, links, schliessen, Vollbild-Ansicht bzw. zurück)
- man öffnet die Galerie wie bisher über einen Button der nur erscheint, wenn mindestens eine Datei existiert, die darin angezeigt werden kann
- die ganze Fläche unten: versucht, in Abhängigkeit des Dateityps, die Datei darzustellen. Wenn sie das nicht kann, zeigt sie das an
- Bilder darstellen ist einfach
- pdf darstellen ist etwas komplexer, aber möglich. Machen wir schon bei der Anleitung: https://apflora.ch/Dokumentation/anleitung-eingabe/?apTab=dateien. Bin leider nicht 100% sicher, ob das auf allen Browsern und Geräten zuverlässig funktioniert. Möglicherweise schon
- Wenn es andere Dateitypen gibt, die angezeigt werden können sollten, wäre dies mit etwas Mehraufwand z.T. vermutlich auch möglich (xlsx, docx, txt...). 

Für einfache Fälle wie Bilder und pdf sollte es in der Regel ziemlich gut klappen. Grundsätzlich aber ist die Vorschau von Dateien nicht simpel. Auch Betriebssysteme haben damit teilweise ihre Mühe.

Ich denke, der grundsätzliche Umbau und die Erweiterung auf pdf wäre ca. 8 Stunden Aufwand.

**Comment by rebeccakurz** [comment]
Das beschreibt genau das, was wir wünschen. Eine Anzeige von PDF und Bildern reicht völlig aus, mehr brauchen wir nicht. Wir gehen davon aus, dass im Vollbildmodus das PDF in einer leserlichen Grösse angezeigt wird. Wenn das so ist, ist es so, wie wir es wollen.

Da es ja doch eine grössere Erweiterung wäre, würde ich noch bei Anna Gruber und Lieni nachfragen, ob wir das noch zusätzlich offerieren dürfen oder was meinst du?

**Comment by barbalex** [comment]
Ja, scheint mir sinnvoll

**Comment by barbalex** [comment]
Ich habe das jetzt für eine andere App ausprobiert. Ich kann neben Bildern und pdf auch recht einfach Dateien aus zwölf anderen Typen anzeigeb, u.a. word, excel, powerpoint

**Comment by rebeccakurz** [comment]
Okay, ja das wäre doch nicht schlecht, falls man auch noch andere Dateien hochladen möchte. Z.B. ein Word mit einem kleinen Bericht oder so.

**Comment by barbalex** [comment]
Bei der Implementierung sind mir zwei begrenzende Rahmenbedingungen aufgefallen:
1. Vollbildmodus: Das kann ich recht einfach implementieren. ABER: Wie bei der Karte gesehen, wird das von iPhones nicht unterstützt. Ich kann verhindern, dass die App beim Versuch abstürzt. Aber ich kann nicht zaubern, d.h. bei iPhones wird man die Dateien nicht im Vollbildmodus anzeigen können
2. Word, Excel, weitere Dateitypen (über Bilder und pdf's hinaus): Deren Anzeige wird implementiert. Sie basiert aber auf einer eingebundenen Software, für die ich keine Garantie übernehmen kann. Ich kann daher nicht völlig ausschliessen, dass das irgendwann in der Zukunft nicht mehr funktioniert oder dann anders implementiert werden müsste (vielleicht gibt es bis dann andere Methoden)

**Comment by rebeccakurz** [comment]
1. Ich denke, es ist schon hilfreich, wenn die Dateien in einem kleinen Format angezeigt werden, so dass man sie nicht herunterladen muss. Daher ist es sicher okay, wenn sie auf iPhones nicht im Vollbildmodus angezeigt werden können. 
2. Wenn es für den Moment funktioniert, dann ist das ja schon mal gut :-)

**Comment by barbalex** [comment]
Ich habe den Aufwand völlig unterschätzt. Habe übersehen, dass es sich hier nicht um ein gewöhnliches Formular handelt, sondern um eine Liste.

Es braucht also eine neue Menuzeile oben (unter den Tabs: Art, Auswertung, Dateien, Historien), in dem man folgendes kann:
- Neue Datei (hochladen)
- Vorschau ein-/ausschalten

Die Vorschau-Ansicht zeigt jeweils eine einzelne Datei, im Gegensatz zum (heutigen und künftigen) Formular, dass alle Dateien auflistet. Daher braucht es in der Vorschau-Ansicht diese zusätzlichen Menus:
- Datei löschen
- Nächste Datei (navigieren)
- Vorherige Datei (navigieren)
- Vorschau maximieren/schliessen

Und die Menuzeile für die Vorschau-Ansicht sollte beim maximieren mit maximiert werden, damit man auch in dieser Ansicht navigieren kann bzw. eine Datei nach der anderen anschauen kann (wie in der aktuellen Bilder-Gallerie).

Eine solche Menuzeile muss sich an den verfügbaren Platz anpassen können (Mobil-Freundlichkeit). D.h. wenn nicht für alle Symbole genug Platz existiert, müssen die überzähligen in einem Mehr-Menu zusammengefasst werden.

Diese Funktionalität ersetzt dann die aktuelle Bilder-Gallerie.

Die neue Menuzeile wird zunächst etwas fremd wirken. Sobald aber die Mobil-Freundlichkeit umgesetzt wird, wird jedes Formular eine solche erhalten. Wenn ich also schlau baue, muss ich die Grund-Funktionalität hoffentlich nur ein mal bauen.

Spannen. Ran an die Arbeit 🤣.

**Comment by barbalex** [comment]
Die neue Version ist unter folgender URL erreichbar: https://apflora-zdi88lv47-gabrielsoftware.vercel.app

Es handelt sich um:
- die neue Software (die künftige Version)
- mit den live-Daten, die du auch unter apflora.ch siehst und bearbeitest

Wenn du also hier Daten änderst, ändern sie auch auf apflora.ch.

Kannst du bitte die neue Version unter obiger url testen?

Es hat ziemlich viel geändert. Daher will ich sie erst dann auf apflora.ch hochladen, wenn du getestet hast.

**Comment by barbalex** [comment]
Neuere Version: https://apflora-3oj6ico4d-gabrielsoftware.vercel.app

Hier kann man in der Vorschau die Datei auch herunterladen.

**Comment by barbalex** [comment]
Übrigens habe ich im Entwicklungsmodus gesehen, wie nun auch bei mir eine Datei offensichtlich zwei mal nacheinander als heraufgeladen gemeldet wurde. Habe das bei den Entwicklern des Werkzeugs gemeldet.

Und ich habe Code geschrieben, der das abfangen können sollte. Dieser Code existiert nur in der oben verlinkten Vorschau. Auf apflora.ch kann das wohl immer noch passieren.

**Comment by barbalex** [comment]
Neue Version, enthält in der Menuzeile den Dateinamen und wenn man darüber hovert weitere Infos: https://apflora-4fwt4a7xe-gabrielsoftware.vercel.app/Daten/

**Comment by rebeccakurz** [comment]
Hoi Alex
Vielen Dank für deine Arbeit. Wir haben die neue Version getestet und das scheint gut zu funktionieren, auch mit PDFs und Excel-Tabellen. Es ist super, wenn man die Dateien gleich so anschauen kann!
Wir haben noch einen kleinen Verbesserungsvorschlag: Wenn es mehrere Dokumente sind, die man in der Galerie-Funktion anschaut, wäre es gut zu sehen, bei welchem man sich gerade befindet und/oder ob man bereits beim letzten Dokument angekommen ist. Dies zum Beispiel mit einer Anzeige 2/5 oder dass z.B. die Navigations-Pfeile grau werden, wenn man beim letzten Dokument ist. 
Wäre das machbar?

**Comment by barbalex** [comment]
> Wenn es mehrere Dokumente sind, die man in der Galerie-Funktion anschaut, wäre es gut zu sehen, bei welchem man sich gerade befindet und/oder ob man bereits beim letzten Dokument angekommen ist. Dies zum Beispiel mit einer Anzeige 2/5 oder dass z.B. die Navigations-Pfeile grau werden, wenn man beim letzten Dokument ist.

Gute Idee. Danke!

**Comment by barbalex** [comment]
Neue Vorschau-Version mit eurer Idee implementiert: https://apflora-mo6u9vab2-gabrielsoftware.vercel.app/

**Comment by barbalex** [comment]
Ist in Version 1.107 publiziert

**Comment by rebeccakurz** [comment]
Super, vielen Dank!
