### ISSUE TITLE
Fehlermeldung bei Eingaben Dezimalzahlen

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#67]
Wenn ich eine Dezimalzahl bei einer Zählung als Anzahl eingebe, gibt es eine Fehlermeldung. Wenn aber die Zähleinheit zum Beispiel die Fläche in Quadratmetern ist, sollte es doch möglich sein, z.B. 8.5 m2 einzugeben?

![bildschirmfoto 2017-09-14 um 14 56 14](https://user-images.githubusercontent.com/30288503/30430961-59dee4e4-995d-11e7-8888-4d10bb8b9051.png)

**Comment by barbalex** [comment]
Das war bisher nicht möglich und nicht gewünscht.

Die alte Anwendung bringt in diesem Fall sogar eine hilfreiche Meldung:
![2017-09-14_15h10_32](https://user-images.githubusercontent.com/669783/30431481-f7844ca6-995e-11e7-92ff-2d29ef7efb70.png)

@csalzmann: Ich erfasse das als Erweiterung. Aufwand ca. 1 Stunde. Du musst entscheiden, wie wichtig es ist.

**Comment by rebeccakurz** [comment]
Wenn so eine Meldung kommen würde, wäre das schon hilfreich! Dann weiss man, dass die Zahl nicht gespeichert wurde.
Weiss halt nicht ob so eine Meldung einfach einzurichten wäre?

**Comment by csalzmann** [comment]
Und wenn Du im Formular hinter Anzahl in Klammern „nur ganze Zahlen“ noch hinzufügst?

---------------------------------------------------------------
Charlotte Salzmann
Dr.sc.ETH
topos Marti & Müller AG
Idastr. 24
8003 Zürich
Tel. 044 451 52 55
salzmann@toposmm.ch

Di - Fr

**Comment by barbalex** [comment]
gute Idee, gemacht

**Comment by barbalex** [comment]
Ich schliesse das, weil es offenbar nicht mehr passiert. Falls doch: einfach wieder öffnen.

**Comment by rebeccakurz** [comment]
Also die Fehlermeldung kommt immer noch bei der Eingabe einer Dezimalzahl, nur hast du ja jetzt einen Zusatz gemacht, dass nur ganze Zahlen eingegeben werden können, daher sollte es klar sein, dass das nicht möglich ist... nur zur Info...

**Comment by barbalex** [comment]
roger :-)
