### ISSUE TITLE
Link Mail Info Flora

### ISSUE THREAD

**Issue by wunderli** [barbalex/apf2#670]
Meldung an Info Flora-Botton

Geht bei mir nicht, da wir Outlook benützen und keines der auswählbaren Mail-Programme.
Könnte man evtl. einfach einen Mail-Link reinmachen, der dann in ein beliebiges Mail-Programm kopiert werden könnte?
Oder ist das problematisch wegen Spam-Mails?!
Evtl. gibt es auch noch andere Lösungen...

<img width="561" alt="Bildschirmfoto 2024-02-26 um 15 37 14" src="https://github.com/barbalex/apf2/assets/26789445/5e7500d4-d26d-4ad9-9857-001be01b2299">

**Comment by barbalex** [comment]
> Könnte man evtl. einfach einen Mail-Link reinmachen, der dann in ein beliebiges Mail-Programm kopiert werden könnte?

Ich weiss nicht, was damit gemeint ist. Es gibt ausser dem implementierten mailto:-Link-Format meines Wissens kein allgemein definiertes Link-Format, dass so benutzt werden könnte.

**Comment by wunderli** [comment]
Outlook ist Standart-Programm für Öffnen von Mail-Formaten (aber allenfalls nicht von Mail-to-Link-Formaten...)
![Bildschirmfoto 2024-02-26 um 16 11 49](https://github.com/barbalex/apf2/assets/26789445/8022804d-83ce-4b35-86cc-da768d6d638e)

**Comment by barbalex** [comment]
Dann passiert also dasselbe, wenn du diesen Link hier klickst? [mailto:someone@yoursite.com](mailto:someone@yoursite.com)

**Comment by barbalex** [comment]
Dein Bildschirmprint scheint nahezulegen, dass du .eml-Dateien öffnen willst. Das ist nicht dasselbe, wie einen mailto:link zu öffnen.

Du musst wohl in Outlook oder in deinem Betriebssystem suchen, wo du es richtig einstellen kannst. Auf dem Forum von Outlook scheinen Leute auf Einstellungen innerhalb von Outlook zu deuten.

**Comment by barbalex** [comment]
Auf dem Mac scheint es viel schwieriger zu sein, das einzustellen, als auf einem Windows PC.
Ev. hat es mit den vorinstallierten Apps zu tun. MacOS installiert für Email ein eigenes App, gemannt mail.

Es gibt leute, die Melden, dass wenn man aus versehen mail öffnet, es die Standardeinstellung ändert. Und dass man sie darin ändern kann.

Versuch also in Outlook und in mail, ob du das einstellen kannst.
