### ISSUE TITLE
Möglichkeit mehrere Dateien gleichzeitig in FloraDB hochzuladen?

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#671]
Hoi Alex

Von den Artverantwortlichen kam noch die Frage, ob es möglich ist, mehrere Bilder/Dateien gleichzeitig hochzuladen? 
Ich meinte bis jetzt sei das noch nicht möglich oder? Wäre das vielleicht auch noch eine Erweiterung?

**Comment by rebeccakurz** [comment]
Hast du die Offerte schon erstellt?
Sonst würde ich sagen, dass das noch drinliegen würde? Oder vielleicht besser als Option offerieren, so wie Lieni es für das andere vorgeschlagen hat?

**Comment by barbalex** [comment]
Ich habe immer noch keinen Auftrag. Daher auch keine Offerte erstellt...
Aber ja, nehmen wir das rein.

**Comment by barbalex** [comment]
Ist implementiert

**Comment by rebeccakurz** [comment]
Super, vielen Dank!
