### ISSUE TITLE
Kartendruck funktioniert nicht

### ISSUE THREAD

**Issue by barbalex** [barbalex/apf2#673]
Gemeldet per email von Charlotte Salzmann (@csalzmann)

**Comment by barbalex** [comment]
Ich bin in meine Zeitmaschine gestiegen und habe gefunden, seit wann dieser Fehler auftritt: https://github.com/barbalex/apf2/commit/d416fe1ac81316d90bb109678a3a02afc4899076

**Comment by barbalex** [comment]
Hm.

Ist noch komplexer als gedacht, weil:
- in der Karte url's benutzt werden für die Symbole (nicht die svg's selbst)
- die Symbole auch im Navigationsbaum benutzt werden

**Comment by barbalex** [comment]
Das war ziemlich aufwändig: https://github.com/barbalex/apf2/pull/674/files

**Comment by rebeccakurz** [comment]
Das sieht wahnsinnig komplex aus, ich verstehe nur Bahnhof... 
Schön, dass du es lösen konntest!
