### ISSUE TITLE
ZH Orthofoto aktuell funktioniert nicht

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#675]
Hoi Alex

In der FloraDB funktioniert bei der Karte das "ZH Orthofoto aktuell" nicht beim Hintergrund. 
Soviel ich weiss hat der Kanton Zürich vor kurzem ein neues Orthofoto aufgeschaltet aus 2022. Vielleicht ist bei diesem Wechsel etwas schiefgegangen?
<img width="1393" alt="Bildschirmfoto 2024-06-20 um 16 03 48" src="https://github.com/barbalex/apf2/assets/30288503/7db9e361-670d-4d0d-a059-e3cbaf1e67e4">
Könntest du dir das mal ansehen?

**Comment by barbalex** [comment]
Das aktuellste Orthofoto stammt aus 2021/22. Und es enthält hässliche Gitternetzlinien 😢 

Offiziell hat nichts geändert, faktisch hat der Kanton aber den Layer-Namen geändert, daher wurde die Karte nicht mehr angezeigt.

Ist in Version 1.105.2 aktualisiert.
