### ISSUE TITLE
Vervielfachung der hochgeladenen Dateien

### ISSUE THREAD

**Issue by barbalex** [barbalex/apf2#678]
Meldung von @rebeccakurz :

Das Hochladen von mehreren Dateien gleichzeitig scheint zu funktionieren (habe es heute mit PDFs ausprobiert). 
Es scheint aber teilweise eine Vervielfachung der hochgeladenen Dateien zu geben. Aber nicht immer und auch nicht nur, wenn man mehrere Dateien gleichzeitig hochlädt. 

Beispiel mit nur einer hochgeladenen Datei:
<img width="1279" alt="Bildschirmfoto 2024-10-29 um 12 55 44" src="https://github.com/user-attachments/assets/da8aac33-ac00-4f20-a8d8-6533472e0097">

Beispiel mit zwei gleichzeitig hochgeladenen Dateien: 
<img width="1277" alt="Bildschirmfoto 2024-10-29 um 12 54 57" src="https://github.com/user-attachments/assets/214ffdc5-7db7-4480-a8c8-108c5efc878f">

Vielleicht kannst du dir das mal anschauen?

_Originally posted by @rebeccakurz in https://github.com/barbalex/apf2/issues/671#issuecomment-2444807858_

**Comment by barbalex** [comment]
In Version 1.106.3 habe ich das Heraufladen mehrere Datein deaktiviert. Werde es erst wieder aktivieren, wenn ich den Fehler gefunden habe.

Es handelt sich hier um ein neues, von uploadcare.com bereitgestelltes Werkzeug. Ich habe den Verdacht, das es noch Fehler enthält.

**Comment by rebeccakurz** [comment]
Okay, schade! Dann hofe ich, das Werkzeug ist bald fertig.

**Comment by rebeccakurz** [comment]
In der Version 1.106.3 kann man zwar nicht mehr mehrere Dateien gleichzeitig hochladen, die einzeln hochgeladenen Dateien werden jedoch immer noch vervielfacht...

![Bildschirmfoto 2024-10-30 um 14 25 32](https://github.com/user-attachments/assets/96b829ea-cda5-46df-ba46-c524d0e8d9da)

![Bildschirmfoto 2024-10-30 um 14 23 41](https://github.com/user-attachments/assets/52bdf784-a4ca-4f46-a41a-cadbe1dfce25)

**Comment by barbalex** [comment]
Das ist ein bisschen frustrierend. Und bisher kann ich es nicht nachvollziehen.

**Comment by barbalex** [comment]
Hm.

Ich glaube, es gibt ein Problem mit dem Timing der Events.
Habe nun in Version 1.106.4 einen Trick angewandt. Und das Hochladen von bis zu 10 Dateien wieder freigeschaltet.

Bin gespannt auf deine Rückmeldung.

LG, Alex

**Comment by rebeccakurz** [comment]
Super, vielen Dank! Werde es bei Gelegenheit gerne testen.

**Comment by barbalex** [comment]
Ich schliesse das, da es nicht mehr aufzutreten scheint?

**Comment by rebeccakurz** [comment]
Bis jetzt scheint es nicht mehr vorgekommen zu sein. Falls es nochmals auftreten würde, werden wir uns melden.
