### ISSUE TITLE
Freiwilligen-Erfolgskontrollen: Besser kontrollieren, wie oft kontrolliert wird

### ISSUE THREAD

**Issue by barbalex** [barbalex/apf2#68]
Im Auftrag ist es so formuliert:

- Eine Möglichkeit einbauen, dass Kontrollen gekennzeichnet werden, die in Zukunft nicht mehr an Freiwillige gehen sollen (weil zu schwierig, erloschen oder sonstige Gründe).
- Auch: Welche immer oder nur zu bestimmten Abständen kontrolliert werden sollen.

In https://github.com/FNSKtZH/apflora/issues/13 habe ich zum ersten Punkt notiert:

> Neues Feld in TPop: keine_freiwilligenkontrollen. Ausweisen in Exporten: Kontrollen, TPop inkl. letzte Kontrolle

Wenn man nun aber den zweiten Punkt berücksichtigt, wäre ev. dieser Vorschlag besser:

Neues Feld in TPop: FrequenzFreiwilligenkontrollen.
Mögliche Einträge aus Auswahlliste wählen. Darunter: "nie", "jährlich".
Vorteil: einfach und unmittelbar verständlich.

Alternative Möglichkeit: Mögliche Einträge sind Zahlen:
- 0: nie
- 1: jährlich
- 2: alle zwei Jahre
- etc.

Vorteil: Man könnte auswerten (=auflisten), wo zu oft kontrolliert wurde.
Nachteil: Ohne Anleitung nicht verständlich.

In beiden Fällen könnte - wenn es nötig ist - im allgemeinen Bemerkungsfeld erklärt werden, wieso diese Frequenz sinnvoll ist.

@csalzmann: was meinst du?

**Comment by csalzmann** [comment]
Finde ich grundsätzlich super.
In Zukunft sollten wir aber wahrscheinlich sowieso, unabhängig ob Freiwillig kontrolliert oder nicht, eine Frequenz der Kontrolle in der DB eingeben.
Dann müsste es fast ein Feld geben für die allgemeine Kontrollfrequenz, und dann auch noch ob von Freiwilligen oder nicht.
Dann müsste man vielleicht 2 Felder haben? Es kann eben sein, dass eine TPop durchaus kontrolliert werden muss, man diese Kontrolle aber nicht Freiwillige machen lassen will.

**Comment by barbalex** [comment]
Also so:

- neues Feld `kontrollfrequenz`: Einträge aus Tabelle `tpopkontr_frequenz_werte`
- neues Feld `kontrolle_durch_freiwillige`: ja/nein
- neue Tabelle `tpopkontr_frequenz_werte`
  - Felder: id, code, text, sort, changed, changed_by
  - Werte (code: text):
    - 0: nie
    - 1: jährlich
    - 2: alle 2 Jahre
    - 3: alle 3 Jahre
    - ev. mehr
  - Mit dieser Struktur könnte berechnet werden, wann die nächste Kontrolle ansteht

@csalzmann was meinst du?

**Comment by csalzmann** [comment]
Finde ich grundsätzlich sehr gut. Werteliste müssten wir noch mehr anpassen können, das wäre aber Detail, oder? 

Es müsste auch möglich sein, dass Frequenz  für Feldkontrollen und EKF separat vermerkt wird. 

Karin hat vielleicht noch mehr Ergänzungen, es geht ja auch um das EK Konzept.


---------------------------------------------------------------
von unterwegs gesendet

Charlotte Salzmann
Dr.sc.ETH
topos Marti & Müller AG
Idastr. 24
8003 Zürich
Tel. 044 451 52 55
salzmann@toposmm.ch

Di - Fr

**Comment by barbalex** [comment]
Also so:

- neues Feld `kontrollfrequenz`: Einträge aus Tabelle `tpopkontr_frequenz_werte`
- neues Feld `kontrollfrequenz_freiwillige`: Einträge aus Tabelle `tpopkontr_frequenz_werte`
- neue Tabelle `tpopkontr_frequenz_werte`
  - Felder: id, code, text, sort, changed, changed_by
  - Werte (code: text):
    - 0: nie
    - 1: jährlich
    - 2: alle 2 Jahre
    - 3: alle 3 Jahre
    - ev. mehr (Werte sind erweiterbar)
  - Mit dieser Struktur könnte berechnet werden, wann die nächste Kontrolle ansteht

**Comment by barbalex** [comment]
Ist in der Entwicklungsversion umgesetzt

**Comment by barbalex** [comment]
Ist live

**Comment by rebeccakurz** [comment]
Hallo Alex

Kannst du mir/uns erklären, wo wir das finden? Ich kann auf der Website nichts Entsprechendes finden.

**Comment by barbalex** [comment]
unten in der Teilpopulation:
<img width="514" alt="2018-11-22_12h16_55" src="https://user-images.githubusercontent.com/669783/48899708-99cddd00-ee50-11e8-890e-66bc047739a8.png">

**Comment by rebeccakurz** [comment]
Okay, vielen Dank. Ich weiss jetzt auch wieso ich nichts gefunden habe: 
Ich habe die Website so eingestellt, dass sie die Informationen in zwei Spalten darstellt (übersichtlicher) und da es mit den Kolltroll-Frequenzen mehr Platz braucht, werden diese in einer dritten Spalte dargestellt und man muss mit dem Balken nach rechts fahren.
![bildschirmfoto 2018-11-22 um 12 35 52](https://user-images.githubusercontent.com/30288503/48900626-2bd6e500-ee53-11e8-8aeb-ce22cc05e8b8.png)

**Comment by barbalex** [comment]
Das sollte eigentlich nicht passieren, denn die Spalten richten sich nach der _verfügbaren_ breite, ohne dass Scrollen nötig ist. Das hat vermutlich damit zu tun, dass ihr Windows auf Mac betreibt.
