### ISSUE TITLE
Galerieansicht - es werden nur die ersten beiden Dateien angezeigt

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#688]
Gerade wurde mir von den Artverantwortlichen gemeldet, dass wenn mehrere Fotos hochgeladen wurden (was übrigens eine tolle Funktion sei ;-) ) mit der Galerieansicht nur die ersten zwei Bilder angeschaut werden können. 
Ich habe das gerade auch noch ausprobiert und bei mir ist es das gleiche. 
Getestet z.B. bei Saxifraga granulata TPop 125.1, Massnahme 2024: https://apflora.ch/Daten/Projekte/e57f56f4-4376-11e8-ab21-4314b6749d13/Arten/6c52d250-4f62-11e7-aebe-a71b014ac715/Populationen/70c3bcba-4f62-11e7-aebe-4f44863549e1/Teil-Populationen/76c7fc9d-4f62-11e7-aebe-2b2b1cb20fc4/Massnahmen/abd6b172-a752-11ef-a618-ffc3c05ee55f/Dateien/7b22cbb4-78b6-49d9-a6dc-8fbc483e38b9/Vorschau

Könntest du dir das mal anschauen?

**Comment by rebeccakurz** [comment]
Bin mir nicht ganz sicher, aber ich glaube, letzte Woche hat es noch fehlerfrei funktioniert.

**Comment by barbalex** [comment]
Ist in Version 1.114.5 behoben.

War kompliziert zu bauen. Ich habe nun gemerkt, dass es einfacher geht. Und siehe da, der Fehler war weg...

Danke für die Meldung.

**Comment by rebeccakurz** [comment]
Super, vielen Dank!
