### ISSUE TITLE
Mobile View: Funktion "Ordner im Navigationsbaum öffnen" hat auf Handy/Tablet keine Auswirkungen (am Computer schon)

### ISSUE THREAD

**Issue by barbalex** [barbalex/apf2#689]
Meldung von @rebeccakurz

**Comment by barbalex** [comment]
@rebeccakurz 

Wenn ich in der mobilen Ansicht den Befehlt zum Schliessen aller Ordner klicke, dann in den Navigationsbaum wechsle, sind sie zu. Wechsle ich zurück zu Daten und klicke den Befehl, die Ordner zu öffnen und wechsle dann zurück zum Navigationsbaum, sind sie offen. Wechsle ich zurück zu Daten und klicke auf Schliessen, sind sie danach im Navigationsbaum wieder geschlossen.

Mit "hat keine Auswirkungen" meinst du also nicht, dass es wie bisher und angeschrieben funktioniert?
Meinst du etwa, dass sich dieser Befehl in den neuen Bookmarks auswirken sollte? Und wenn ja, wie?

Ich hatte eigentlich vor, die Befehle zur Manipulation des Navigationsbaums in der Mobil-Ansicht ganz zu entfernen. Sie haben da keine nützliche Funktion, oder?

**Comment by rebeccakurz** [comment]
Uns ist einfach aufgefallen, dass nichts passiert/ sich nichts an der Anzeige ändert, wenn man diesen Knopf drückt. 
Aber ich glaube auch, dass er in der Mobil-Ansicht keine nützliche Funktion hat. 

Was bedeutet denn dieses Stop-Symbol, dass neu aufgetaucht ist, nachdem ich die Funktion "Ordner im Navigationsbaum öffnen" gedrückt hatte?
![Screenshot_20241205_131125_Samsung Internet](https://github.com/user-attachments/assets/981ce917-1510-432f-830c-3f30b832e8a0)

**Comment by barbalex** [comment]
> Uns ist einfach aufgefallen, dass nichts passiert/ sich nichts an der Anzeige ändert, wenn man diesen Knopf drückt.
> Aber ich glaube auch, dass er in der Mobil-Ansicht keine nützliche Funktion hat.

Das bestätigt, dass ich diese Navigationsbaum-bezogenen Befehlt in der Mobil-Ansicht verstecken sollte. Werde ich machen

**Comment by rebeccakurz** [comment]
Ah okay, da bin vermutlich versehentlich drauf gekommen. 

Ich denke, die Befehle sind eigentlich schon genug gross. Es fehlt vermutlich noch etwas am Verständnis, was die einzelnen Schaltflächen bedeuten/auslösen.

**Comment by barbalex** [comment]
> Es fehlt vermutlich noch etwas am Verständnis, was die einzelnen Schaltflächen bedeuten/auslösen.

Man kann sich informieren:
- auf dem PC: mit dem Cursor darüber hovern
- auf Touch-Screen: die Schaltflläche lange drücken

dann erscheint ein Hinweis

**Comment by barbalex** [comment]
Um das Verhalten am Touch-Screen klar zu machen:
- kurzer Klick löst den Befehlt aus
- langer Druck öffnet Kontextmenu, wenn es eines gibt (z.B. bei Links) oder einen Hinweis, wenn es den gibt. Langer Druck sollte den Befehlt nicht ausführen

**Comment by rebeccakurz** [comment]
Okay, super. Ja auf dem PC war es schnell klar. Auf dem Touch-Screen wollte ich nicht zuviel ausprobieren, um nicht noch versehentlich etwas zu verändern. 
Aber das ist schon mal hilfreich.

**Comment by barbalex** [comment]
Neue Version in der Vorschau verfügbar: https://apflora-izvl33zse-gabrielsoftware.vercel.app

Unter anderem angepasst: Navigationsbaum bezogene Menüs sind nur verfügbar, wenn man im Mehr-Befehlt explizit gewählt hat, sie immer verfügbar zu haben.
