### ISSUE TITLE
Auswahlliste, Drop down Menü

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#69]
Wenn ich eine neue Freiwilligenkontrolle erstelle und den Bearbeiter eingeben will, kann ich ja den ersten Buchstaben des Namens schreiben und die Auswahlliste hüpft dann zu diesem Anfangsbuchstaben. Heute aber erscheint die Liste ab dem eingegebenen Anfangsbuchstaben leer (alle vorhergehenden Namen werden angezeigt, alle darunter nicht). Wenn ich die ganze Liste durchscrolle, erscheinen alle Namen. 
![bildschirmfoto 2017-09-20 um 10 45 10](https://user-images.githubusercontent.com/30288503/30635141-d02cb0a2-9df1-11e7-877a-83ff4af47576.png)
Vielleicht könnte man bei dieser Gelegenheit auch noch anpassen, dass man nicht nur den ersten Buchstaben eines Namens eingeben kann, sondern weiterschreiben kann, bis nur noch der richtige Name ausgewählt wird (wenn man bis anhin mehr als einen Buchstaben eingegeben hat, dann hat die Liste alle Buchstaben als Anfangsbuchstaben bewertet und ist zum nächsten gehüpft.

Vielleicht in das gleiche Thema gehört: Wenn ich bei den Zählungen eine Zähleinheit eingeben will, ist die Auswahlliste manchmal einfach leer, dann muss ich nochmals draufklicken und dann geht es (auch heute passiert, vorher noch nie).
Vielleicht ein Problem mit dem dem Dropdown Menü im Moment?

**Comment by barbalex** [comment]
>  Heute aber erscheint die Liste ab dem eingegebenen Anfangsbuchstaben leer (alle vorhergehenden Namen werden angezeigt, alle darunter nicht). Wenn ich die ganze Liste durchscrolle, erscheinen alle Namen.

Leider kann ich das nicht nachvollziehen. Fragen:

- Passiert das bei dir heute immer? Oder nur manchmal? Meist oder selten?
- Welchen Browser verwendest du?
- auf welchem Betriebssystem?

**Comment by rebeccakurz** [comment]
Ja, es passiert heute immer.
Ich verwende Chrome auf MacOS

**Comment by barbalex** [comment]
> Vielleicht könnte man bei dieser Gelegenheit auch noch anpassen, dass man nicht nur den ersten Buchstaben eines Namens eingeben kann, sondern weiterschreiben kann, bis nur noch der richtige Name ausgewählt wird (wenn man bis anhin mehr als einen Buchstaben eingegeben hat, dann hat die Liste alle Buchstaben als Anfangsbuchstaben bewertet und ist zum nächsten gehüpft.

Ja, dieses Verhalten ist nicht ideal. Leider ist es das für HTML definierte Standard-Verhalten für sogenannte "Select-Field" bzw. was mann vielleicht als "Dropdown-Liste" kennt.

Eine Alternative wäre, statt dem Select-Field ein "Autocomplete" zu benutzen. Beispiele dafür findet ihr:

- um die Art zu wählen, wenn ihr einen neuen AP erzeugt
- um die Art zu wählen, wenn ihr eine neue assoziierte Art erzeugt

@rebeccakurz , @csalzmann:
Soll ich grundsätzlich alle Select-Fields zu Autocompletes ändern?

Probiert doch mal das Verhalten dieser Felder aus und sagt mir, ob das für euch ideal ist.
Man _kann_ sie so konfigurieren, dass die Liste öffnet, sobald man in das Feld klickt. Ich hab's bei den Artlisten nicht gemacht, weil sie eh viel zu lang sind.

**Comment by barbalex** [comment]
> Ja, es passiert heute immer.

@rebeccakurz 
Passiert es auch, wenn du die Anwendung neu lädst?

**Comment by rebeccakurz** [comment]
Ja, passiert auch noch nachdem ich neu geladen habe...

**Comment by barbalex** [comment]
Mein schickes MacBook Pro ist soeben kaputt gegangen (Wasserschaden). Ich weiss momentan nicht, wie ich das testen soll.

@rebeccakurz Kannst du andere bitten, das auszuprobieren um zu sehen, ob das mit macOS und Chrome (oder auch anderen Konfigurationen) regelmässig passiert?

**Comment by rebeccakurz** [comment]
Anna hat es gerade ausprobiert, mit macOS und Chrome, bei ihr hat es funktioniert...
Liegt in dem Fall eher an meinem Computer als an der Datenbank.

**Comment by barbalex** [comment]
Na ja: Bei meinem Mac funktionieren nicht mehr alle Anschlüsse. Aber einige schon noch. Daher konnte ich ihn nochmals starten. Leider hat der Bildschirm auch einen Wasserschaden und zeigt daher die Maus nicht an (neben Wasser, das die Hintergrundbeleuchtung zu moderner Kunst umwandelt).

Jedenfalls kann ich mit der Tabulatortaste in ein Feld, die Liste öffnen, durch Drücken einer Taste zum Eintrag springen - und sehe die ganze Liste.

@rebeccakurz Kannst du bitte folgendes probieren:

- deinen mac neu starten
- den Cache deines Browsers leeren:
  - chrome://settings/
  - erweitert
  - Browserdaten löschen
![2017-09-20_12h00_20](https://user-images.githubusercontent.com/669783/30638334-60ecb3a4-9dfb-11e7-97fb-86a6b62526d1.png)

**Comment by rebeccakurz** [comment]
Okay, habe ich alles gemacht. Passiert aber immer noch...=(
![bildschirmfoto 2017-09-20 um 13 27 26](https://user-images.githubusercontent.com/30288503/30641549-df315718-9e07-11e7-8495-e7333733a7d6.png)
Vielleicht wirklich ein Problem mit diesem Gerät, ist eines der älteren...

**Comment by barbalex** [comment]
**Wenn (falls) ich von euch das o.k. bekomme, diese Felder in Autocompletes umzuwandeln**, kann ich das bis morgen machen. Erst morgen, weil ich andere grössere Änderungen mache, welche eine Neukonfiguration des Servers bedingen. Um nicht während eurer Arbeitszeit Ausfälle zu riskieren, möchte ich das nachts machen.

Aber dann solltest du morgen wieder arbeiten können.

**Comment by barbalex** [comment]
@rebeccakurz : funktionieren die Autocompletes für dich? Versuch's mal bei den assozziierten Arten.

**Comment by barbalex** [comment]
@rebeccakurz Hast du beim Cache leeren im Fenster oben (siehe Bild von mir weiter oben) den gesamten Zeitraum gewählt?

Der cache von apflora ist sicher älter als die Stunde, die in diesem Feld voreingestellt ist.

**Comment by barbalex** [comment]
O.k.: alle Listenfelder sind jetzt Autocompletes. Ich habe versucht, sie so benutzerfreundlich wie möglich zu machen.

**Comment by rebeccakurz** [comment]
Lieber Alex 
Also ich bin noch nicht ganz zufrieden mit diesen Autocompletes...
Wenn ich zum Beispiel bei einer neu erstellten Freiwilligenkontrolle den Bearbeiter eingeben will, kann ich zwar den Vornamen nun schreiben und es springt zum richtigen (Vor-) Namen, allerdings klappt es noch nicht mit dem Nachnamen! wenn ich nämlich einen Abstand eingeben will, wird automatisch der Name ausgewählt, der gerade selektiert ist. Da es doch einige Bearbeiter mit gleichem Vornamen gibt, bringt das noch nicht so viel. Kann man das noch besser anpassen?
Und übrigens, wenn ich zu langsam bin mit Schreiben, wird jeder neue Buchstaben als Anfangsbuchstaben gewertet und die Liste springt dann zu diesem Buchstaben...

**Comment by rebeccakurz** [comment]
Nebenbei: Wie können wir ein geschlossenes Issue wieder öffnen? Müssen wir ein neues machen?

**Comment by barbalex** [comment]
Ich muss etwas komisches geraucht haben, als ich das angepasst habe. Es wurden gar nicht alle Listen angepasst, sondern bisher nur:

- Gemeinden (TPop)
- Lebensraum nach Delarze (Feldkontr)
- Umgebung nach Delarze (Feldkontr)
- Wirtspflanze (TPopMassn)

Den Rest hole ich nach.

**Comment by barbalex** [comment]
> Nebenbei: Wie können wir ein geschlossenes Issue wieder öffnen? Müssen wir ein neues machen?

Zuunterst findest du "Reopen and comment". Aber nur, wenn der issue geschlossen ist - sonst heisst es "Close and comment".

**Comment by rebeccakurz** [comment]
Ich finde zwar bei den offenen Issues "close and comment", aber bei den geschlossenen sehe ich nur "comment"...

**Comment by barbalex** [comment]
![2017-09-25_12h05_28](https://user-images.githubusercontent.com/669783/30803428-dfb69be0-a1e9-11e7-956f-601974588fb3.png)

Die Listen sind nun alle AutoCompletes, daher schliesse ich dieses issue nun. Sie können aber erst live geschaltet werden, wenn andere Anpassungen abgeschlossen sind.
