### ISSUE TITLE
Mobile View: Galerieansicht von PDFs funktioniert nicht auf Handy/Tablet (Bilder hingegen schon). Am Computer funktioniert beides

### ISSUE THREAD

**Issue by barbalex** [barbalex/apf2#690]
Gemeldet von @rebeccakurz

**Comment by barbalex** [comment]
@rebeccakurz 

Getestet auf Android 15 in Chrome v131.0.6778.104: Keine Voransicht. Möglichkeit, die Datei mit einer anderen App zu öffnen.
Getestet auf Android 15 in Firefox v133.0: Voransicht funktioniert.

Die Antwort ist: Es kommt immer auf den Browser an. Es funktioniert nur, wenn vom Browser unterstützt. Da habe ich (ohne sehr viel Aufwand) keinen Einfluss.

**Comment by rebeccakurz** [comment]
Okay, ich habe es bei mir auf dem Handy und dem Tablet mit dem Standardbrowser (Samsung Internet) und mit Google Chrome ausprobiert und bei beiden kann ich die PDFs leider nur herunterladen.

**Comment by barbalex** [comment]
Hier sieht man, wo es möglich ist bzw. nicht: https://caniuse.com/?search=pdf

Demgemäss funktioniert es auf Mobilgeräten nur mit Android/Firefox und iOS.

**Comment by rebeccakurz** [comment]
Okay, habe es gerade noch mit Firefox ausprobiert, hier funktioniert es. Aber dann kann man das ja von Anfang an so mitteilen, dann kann man den entsprechenden Browser verwenden.

**Comment by rebeccakurz** [comment]
Laut dem von dir oben mitgeschickten Link, müsste es nicht auch auf Google Chrome funktionieren? Ich habe die Version Chrome 131 auf meinem Handy.
<img width="1378" alt="Bildschirmfoto 2024-12-05 um 17 18 34" src="https://github.com/user-attachments/assets/af5b6c6b-5ffd-43b9-9a65-fd82f301089f">

**Comment by barbalex** [comment]
Nein, du verwendest genau genommen (wie ich): Chrome for Android.

Die Mobilversionen der Browser haben oft Unterschiede zur Desktopversion.

**Comment by rebeccakurz** [comment]
Achso, ja genau lesen wäre wohl von Vorteil... Danke für die Erklärung.
