### ISSUE TITLE
Mobile View: Anzeige des Strukturbaums auch ab Ebene "Art" weiterführen

### ISSUE THREAD

**Issue by barbalex** [barbalex/apf2#691]
@rebeccakurz meldet:

> Anzeige des Strukturbaums auch ab Ebene "Art" weiterführen: Anstatt das jeweils die Infos der Art/Population/Teilpopulation angezeigt werden, könnte jeweils direkt der Strukturbaum angezeigt werden, in dem man weiternavigieren will. Jetzt muss man dann jeweils im Reiter oben auf die Art/Population/Teilpopulation klicken um zur nächsten Ebene des Strukturbaums zu gelangen. In den meisten Fällen möchte man ja eher etwas auf Teilpopulationsebene oder sogar auf noch tieferer Ebene ergänzen.

**Comment by rebeccakurz** [comment]
Hm nein, ich glaube das Gewöhnungsbedürftige ist, dass man sich durch die Bookmarks hangeln muss um weiterzukommen (sozusagen waagrecht durcharbeiten) man von der FloraDB aber gewohnt ist, dass man sich senkrecht durch den Strukturbaum klickt, um eine Ebene tiefer zu gelangen. Auf dem Handy/Tablet findet man ja zwar auch alle Arten untereinander aufgelistet, wenn man dann aber auf eine Art klickt, werden nur die Daten zur Art angezeigt und man gelangt nicht eine Ebene tiefer zu den Populationen. Diese muss man dann in den Bookmarks wieder ausklappen und antippen, dann erhält man wieder eine Liste mit allen Populationen. Wenn man eine Population anwählt, dann werden wiederum die Daten zur Pop angezeigt, man gelangt aber nicht (wie man es gewohnt ist von der FloraDB) eine Liste mit den TPops, diese muss man wiederum über die Bookmarks öffnen. 

Aber ich weiss nicht, ob das etwas ist, das man anpassen kann oder ob man sich einfach daran gewöhnen muss.

**Comment by barbalex** [comment]
Ich persönlich würde sogar in die gegenteilige Richtung gehen, um die Navigation zu vereinheitlichen bzw. die Nutzung des begrenzten Bildschirms auf Mobilgeräten zu verbessern.

Heute gibt es auf Ebene Art/Pop/TPop und andere "Tabs". Beispiel auf Ebene Art: Art, Auswertung, Dateien, Historien.

Das braucht Bildschirmhöhe. Die auf dem Mobilgerät knapp sein kann und dann bei der Arbeit fehlt. Vor allem, wenn man im Querformat arbeiten wollte.

Ausserdem ist nicht so klar, was hier in Tabs liegen soll und was eher als Ordner im Navigationsbaum erscheinen soll (beim Beispiel der Art z.B. Populationen, Qualitätskontrollen und viel mehr.

Darum würde ich diese Tabs abschaffen und in Ordner im Navigationsbaum bzw. Menüs in den Bookmarks umwandeln.

**Comment by barbalex** [comment]
> Vielleicht müssten wir uns dazu mal noch online austauschen

Gerne. Bin recht oft verfügbar, mach du einen Vorschlag

**Comment by rebeccakurz** [comment]
Wie wäre es mit nächste Woche Dienstag, 10.12., um 10 Uhr?

**Comment by barbalex** [comment]
Ja, das passt. Ist reserviert.

**Comment by barbalex** [comment]
Schliesse, um in https://github.com/barbalex/apf2/issues/435 weiterzumachen
