### ISSUE TITLE
Bei Erstellen einer neuen Feldkontrolle mittels + wird nicht automatisch eine Zählung generiert

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#692]
Wenn ich eine neue Feldkontrolle über die neue +-Schaltfläche erzeuge, dann wird nicht automatisch auch eine neue Zählung generiert, so wie das der Fall ist, wenn ich eine neue Feldkontrolle über den Rechtsklick im Strukturbaum erstelle.
![Bildschirmfoto 2024-12-11 um 13 42 20](https://github.com/user-attachments/assets/acfbfbff-f4b2-4cba-a23f-aded3793cfb1)

**Comment by barbalex** [comment]
Geht eine Weile, bis ich das repariere. Bin immer noch an der Neu-Installation meines PC's...

**Comment by rebeccakurz** [comment]
Okay, ja klar das hat natürlich Vorrang. Ich hoffe, die Neu-Installation funktioniert ohne Probleme.

**Comment by barbalex** [comment]
> Ich hoffe, die Neu-Installation funktioniert ohne Probleme 

Das nicht. Aber hochgrading interessant. Und langfristig produktivitätsfördernd. Ist wieder eine Investition in die Weiterentwicklung der Entwicklungsumgebung. Und die wird jährlich wichtiger.

**Comment by barbalex** [comment]
Ist in der Mobilversion behoben: apflora-r7zp8414h-gabrielsoftware.vercel.app

**Comment by rebeccakurz** [comment]
Danke! Hat in dem Fall die Neuinstallation deines Computers geklappt?

**Comment by barbalex** [comment]
Ja, voller Erfolg 😀
