### ISSUE TITLE
AP-Ziele – Ziel – Bericht hinzufügen --> Anpassung möglich?

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#693]
Die Erstellung eines neuen Berichts in einem AP-Ziel ist etwas knifflig. Bei folgender Darstellung,
<img width="252" alt="Unknown" src="https://github.com/user-attachments/assets/f43251fd-17cf-43c9-898e-0376d69216ec" />
 , passiert beim Anwählen des Ziels nichts bzw. kann ich nur den Zieleintrag ändern. Bin ich hingegen in dieser Darstellung,
<img width="198" alt="Unknown-1" src="https://github.com/user-attachments/assets/6fd81ac7-a433-49a3-b9f1-66c2904b1fb7" />
 dann kann ich «(kein Ziel)» anwählen und der Bericht erscheint.  
<img width="223" alt="Unknown-2" src="https://github.com/user-attachments/assets/eda057b0-928f-47d0-a7dc-26412a82c7fe" />

Kann man da etwas an der Auswahlfunktion anpassen?

**Comment by barbalex** [comment]
Ist das in der Vorschauversion oder in der live Version?
(in der Vorschauversion  wurde an diesen Strukturen gearbeitet)

**Comment by rebeccakurz** [comment]
In der Live-Version.

**Comment by barbalex** [comment]
Ich hab's probiert und _glaube_ es ist sinnvoll. Ist ab jetzt in der Mobilversion implementiert: apflora-g75xyl9e1-gabrielsoftware.vercel.app

Danke für die Meldung!
