### ISSUE TITLE
Dateidarstellung

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#694]
Immer wenn Dateien angewählt werden, ist nur noch die Darstellung von 2 Reitern (Strukturbaum und Daten) nebeneinander möglich. Wenn die Karte geöffnet ist zu dem Zeitpunkt, wenn man eine Datei ansehen möchte, dann wird sie automatisch geschlossen, sobald die Datei in der Galerieansicht angezeigt wird. Wenn man die Datei dann schliesst, dann wird die Karte aber nicht wieder automatisch geöffnet, man muss sie wieder im grünen Balken anwählen. 
Ist es möglich, dass der Strukturbaum, Daten-Dateien sowie z.B. Karten nebeneinander dargestellt werden können? 
Oder dann das die Karte wieder automatisch erscheint, wenn man die Datei wieder geschlossen hat?

**Comment by barbalex** [comment]
Ich hatte das korrigiert. Und danach ein Riesenpuff bekommen, weil die mobilfähige Version in allen veränderten Dateien eigene Änderungen hat.

Nach einiger Bereinigung ist das jetzt in der mobilfähigen Version repariert: https://apflora-2y0iv4ges-gabrielsoftware.vercel.app

Das Wechseln von Tabs  ist generell in der live Version afunktional (bei AP, Pop, TPop und mehr).

Wir sollten daher so rasch wie möglich die mobilfähige Version live schalten.

**Comment by rebeccakurz** [comment]
okay, dann ist auch gut, wenn dann das in der mobilfähigen Version klappt.

**Comment by barbalex** [comment]
Ich markier das mal als gelöst
