### ISSUE TITLE
Schnelligkeit AP-Flora DB

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#695]
Uns ist aufgefallen, dass seit der Umstellung auf die Mobilversion die Schnelligkeit der APFlora auf dem Desktop reduziert ist. (Es dauert zb. länger bis etwas geschieht, wenn ich etwas anklicke).
Vielleicht wird das ja wieder besser, sobald dann mal alles integriert ist? Oder kann man da jetzt schon etwas machen?

**Comment by barbalex** [comment]
Ich muss wohl den GraphQL-Server neu starten. Da die App kurzfristig nicht verfügbar ist, warte ich damit bis heute spät

**Comment by rebeccakurz** [comment]
Okay, danke

**Comment by barbalex** [comment]
Ich habe jetzt den Server neu gebootet. Damit sollten sich die Abfragen zurücksetzen. Inklusive ihre Caches. Da ich in der letzten Zeit viel an den Abfragen verändert und dann bereinigt habe, könnte das spürbar wirken.

Spürt ihr einen Unterschied?

**Comment by rebeccakurz** [comment]
Danke, jetzt ist es wieder angenehmer zum Arbeiten!
