### ISSUE TITLE
Feld Gemeinde automatisch ausfüllen?

### ISSUE THREAD

**Issue by wunderli** [barbalex/apf2#7]
Bei den Teilpopulationen folgt nun das Feld "Gemeinde" nach den Kooordinaten.
Wäre es möglich, dass dieses Feld automatisch aufgrund der geografischen Lage ausgefüllt wird?
Bisher haben wir in Zweifelsfällen die Koordinaten auf den Kantonskarte gesucht.
Evtl. kann das der Compi auch ohne unsere Hilfe?

**Comment by barbalex** [comment]
Das ist möglich:

- Datei oder API mit GeoJSON-Daten von Gemeindegrenzen finden
- Funktion schreiben, welche aufgrund einer Koordinate die Gemeinde findet
- diese Funktion aufrufen und den Wert ins Feld schreiben, wenn:
  - a: die Koordinaten geändert werden
  - b: die Benutzerin explizit den entsprechenden Befehl wählt

Es kostet mich ein bis zwei Stunden Aufwand. Und ist eine neue Funktion, daher Erweiterung.

Und ihr (@csalzmann) müsstet entscheiden, ob das automatisch passieren soll, was heisst, dass der bestehende Wert überschrieben wird. Oder ob es nur auf Befehl der Benutzerin passieren soll.

**Comment by barbalex** [comment]
Gemeinde war bisher extra nicht zwingend ein Eintrag aus der Liste der Gemeinden.

Als ich das mal gefragt habe, habt ihr geantwortet, dass manchmal mehr als eine Gemeinde betroffen ist. Und tatsächlich sind oft mehrere Gemeinden in diesem Feld gelistet.

Das kann die Anwendung aber ohne Umrisse nicht merken. Sie muss aufgrund der Koordinate rechnen und diese liegt immer nur in einer Gemeinde.

Daher sollte diese Funktion nur auf Knopfdruck erfolgen.

@csalzmann: einverstanden?

**Comment by csalzmann** [comment]
Einverstanden, Danke!

**Comment by barbalex** [comment]
Ist in der Entwicklungsversion umgesetzt
