### ISSUE TITLE
Beobachtungen auf Karte zuordnen funktioniert nicht - Request failed 400

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#71]
![screenshot-2017-9-26 ap flora 2](https://user-images.githubusercontent.com/6047564/30848085-32d26d22-a29e-11e7-89cb-ff4616fdecf1.png)

**Comment by barbalex** [comment]
komisch, all die Meldungen heute habe ich nicht bekommen

Leider ist heute Papitag. Ausgerechnet. Ich muss heute eine Nachtschicht einlegen - vorher komme ich nicht dazu.

Es ist schon immer wieder überraschend, wie etwas, das ich ausgiebig getestet habe, plötzlich wieder nicht funktioniert :-(

**Comment by csalzmann** [comment]
Vermutlich bin ich aktuell sowieso die einzige mit den Beobachtungen. Schau Dir das doch morgen an, es muss nicht heute sein!

**Comment by barbalex** [comment]
ist repariert
