### ISSUE TITLE
Es können überhaupt keine Beobachtungen zugeordnet werden 

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#72]
Weder FloZ- noch andere Beobachtungen, und weder auf Karte noch über die Fenster-Auswahl: immer Request failed
![screenshot 5](https://user-images.githubusercontent.com/6047564/30848524-a9c3c6be-a29f-11e7-9184-2bf78959a720.png)
 400.

**Comment by barbalex** [comment]
repariert
