### ISSUE TITLE
Qualitätskontrolle - Angabe TPop

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#74]
Könntest Du wieder TPop-Nr in der Qualitätskontrolle angeben? Sonst muss man gezwungenermassen immer auf Link klicken, worauf jedes Mal ein neues Fenster im Browser aufgeht. Wird mit der Zeit ein bisschen unübersichtlich..:).

**Comment by barbalex** [comment]
Gemacht.

Ich hoffe aber, dass ich dich richtig verstanden habe. Aus deinem Issue ist nicht klar, wo die TPop-Nr sichtbar war bzw. wo sie auftauchen soll.
