### ISSUE TITLE
Qualitätskontrolle - Pop-Bericht wird nicht erfragt bei Massnahme/EK 

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#75]
Nur TPop-Bericht.

**Comment by barbalex** [comment]
Ist das eine QK, die es schon gibt, die aber nicht erwartungsgemäss funktioniert?

Oder ist das eine QK, die neu ergänzt werden sollte?

**Comment by barbalex** [comment]
Falls es diese QK schon gibt: bitte sag, wie der Titel heisst, unter dem sie ihre Ergebnisse auflistet

**Comment by barbalex** [comment]
...es gibt bestimmt sehr viele QK, welche etwas mit Massnahmen oder EK zu tun haben...

**Comment by csalzmann** [comment]
Also diese QK gab es früher, jetzt funktioniert sie offenbar einfach nicht. Offizieller Name weiss ich nicht. Aber man muss ja bei einer EK oder eine Massnahme des laufenden Jahres nicht nur auf TPop-Ebene berichten, sondern eben auch auf Populationsebene. Diese Abfrage fehlt.

**Comment by barbalex** [comment]
Also bei den Massnahmen-Berichten lautet die Kontrolle:

Teilpopulation mit Ansiedlung (vor dem Berichtjahr) und Kontrolle (im Berichtjahr) aber ohne Massnahmen-Bericht (im Berichtjahr):

Und sie funktioniert, wie du bei Abies alba kontrollieren kannst.
Uups, die Kinder kommen.

**Comment by csalzmann** [comment]
Sie funktionierte auch bei O. palustris (hab da Berichte jetzt schon gemacht). Aber bei Cardamine dentata z.B. nicht. Da gibt es bei Pop 8  EKs, aber bis anhin noch keine Kontrollberichte und aber auch keine Fehlermeldung dazu.
![screenshot 10](https://user-images.githubusercontent.com/6047564/30863657-e6002370-a2d1-11e7-8cde-714debdf1bd3.png)

![screenshot 11](https://user-images.githubusercontent.com/6047564/30863686-f1ec6d10-a2d1-11e7-802e-3b3ec5728a54.png)

**Comment by barbalex** [comment]
Die Qualitätskontrolle heisst:

> Teilpopulation mit Ansiedlung (vor dem Berichtjahr) und Kontrolle (im Berichtjahr) aber ohne Massnahmen-Bericht (im Berichtjahr):

Das heisst: Ohne Ansiedlung keine Meldung.
Und wie es aussieht, gibt es in diesen Fällen keine Ansiedlung?

**Comment by barbalex** [comment]
Du hast irgendwo gefragt, wo die Liste der QK ist. Ich möchte möglichst nicht separate Listen nachführen müssen, die dann immer unvollständig oder gar falsch sein könnten. Daher hier der Link in den Code: https://github.com/barbalex/apf2/blob/master/src/modules/fetchQk.js#L20-L157

**Comment by csalzmann** [comment]
Beim Bsp oben geht es um einen fehlenden Populationsbericht (=Kontrollbericht), nicht um einen  Massnahmenbericht. Den muss es geben nach einer EK im selben Jahr, also 2017. Da müsste es eine Meldung geben.

**Comment by csalzmann** [comment]
Massnahmenbericht funktioniert aber, hast Du recht! Muss mit Karin noch besprechen, ob die Meldung sich tatsächlich nur auf Ansiedlungen beziehen soll oder weiter gefasst sein soll.

**Comment by barbalex** [comment]
Ich schliesse diesen Issue weil schon lange nicht mehr aktiv. Falls das Problem wieder auftaucht, bitte wieder öffnen
