### ISSUE TITLE
Qualitätskontrolle: nach Typ filtern ?

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#76]
Ich glaube, das funktioniert nicht? Wie wäre es gemeint?

**Comment by barbalex** [comment]
Doch. Aber vielleicht ist "Typ" nicht verständlich genug: gemeint ist der jeweilige Titel, under dem eine Gruppe von vermutlichen Fehlern aufgelistet wird (typ von Fehlern). Klappt das bei dir nicht?

**Comment by csalzmann** [comment]
Alles klar. Es filtert nach Typ. Ich hatte aber eben von Layout her den Eindruck, man könne eine Filterart wählen. Wenn man auf "Nach Typ Filtern" klickt, gibt es aber kein Auswahlfeld oder so. Ich war einfach ein bisschen verwirrt, wofür das Angebot sein sollte:)
![screenshot 8](https://user-images.githubusercontent.com/6047564/30854435-e5f632d6-a2b1-11e7-8bbc-8dfa5e50b615.png)

**Comment by barbalex** [comment]
Bin offen für Vorschläge, wie man das klarer machen kann

**Comment by csalzmann** [comment]
Man könnte auch nach Pop/TPop filtern rsp. ordnen. Aktuell hat man ja aber gar keine Wahl, das hat mich verwirrt.

**Comment by barbalex** [comment]
Ich habe es jetzt "nach Abschnitts-Titel filtern" benannt. Hoffentlich ist das weniger unklar :-|
