### ISSUE TITLE
Fehlermeldung

### ISSUE THREAD

**Issue by rebeccakurz** [barbalex/apf2#78]
Habe gerade eine neue Feldkontrolle erstellt und auf das Feld "Vitalität" geklickt. Dann erscheint diese Fehlermeldung:
![bildschirmfoto 2017-09-26 um 13 08 45](https://user-images.githubusercontent.com/30288503/30857471-1a63c1fa-a2bc-11e7-829a-1b0e65256509.png)
Habe also nichts eingegeben oder so, nur in das Feld hineingeklickt (wenn man mehrmals (hinaus- und wieder) hineinklickt erscheinen meherere Fehlermeldungen).
mit Chrome auf MacOS
passiert glaube ich nur bei diesem Feld (jedenfalls innerhalb der Feldkontrolle)...

**Comment by barbalex** [comment]
Ich kann das nicht nachvollziehen.
War vielleicht eine schwache Minute des Servers (die Meldung besagt, dass er die Anfrage nicht versteht).
Passiert das immer noch?

**Comment by csalzmann** [comment]
Ist mir auf die schnelle auch nicht passiert. Rebecca? Würde sonst den Issue schliessen und wieder öffnen, wenn es wieder passieren sollte.

**Comment by rebeccakurz** [comment]
Ist mir danach auch nicht mehr passiert. War vielleicht wirklich eine schwache Minute... war am Computer von Regula Müller, ist ja nicht mehr der Schnellste und dort hatte ich auch schon andere Probleme...

**Comment by barbalex** [comment]
Super, dass ihr euch um diese Sachen kümmert!
