### ISSUE TITLE
Feldkontrolle, Übereinstimmung mit Idealbiotop sehr gut?

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#79]
Ich bin mir nicht sicher, aber gab es da nicht auch noch die Stufe "sehr gut"? Aktuell ist mir unklar, ob diese letzte Stufe einfach abgeschnitten wurde oder ob es sie nicht gibt.
![screenshot 9](https://user-images.githubusercontent.com/6047564/30860919-47e9d1d4-a2c9-11e7-82b8-60bcd44c375c.png)

**Comment by barbalex** [comment]
richtig

das betrifft den in der Entwicklungsversion behobenen Fehler, bei dem in der Feldkontrolle nicht ganz nach unten gescrollt werden kann

genau genommen habt ihr den nicht gemeldet (na ja: das hier ist die Meldung), sondern mir ist es vorgestern aufgefallen, worauf ich es korrigiert habe
