### ISSUE TITLE
Layout allgemein

### ISSUE THREAD

**Issue by wunderli** [barbalex/apf2#8]
Layout sehr cool gemacht!
Der schwarze Hintergrund ist halt eher düster, wenn man den ganzen Tag Daten eingeben muss. 
Dafür ist der Kontrast gut.
Ich denke aber, dass die Schriftart im Strukturbaum noch etwas angepasst werden sollte, da die Leserlichkeit mit rot und fett stark sinkt (v.a. Buchstabe m).
Evtl. selbe Schriftart wie bei Eingabe verwenden?

Die Animation mit Farbe beim ins Feld klicken ist auch ein toller Effekt.
Ein Nachteil ist, dass die "Titel" über dem Eintrag dann klein weden.
Könnte mir vorstellen, dass dies für ältere Augen eher schwierig ist.

**Comment by barbalex** [comment]
Ursprünglich hatte ich die Einzüge im Strukturbaum mit Leerzeichen gebaut, daher musste ich dafür eine Schrift verwenden, bei der alle Buchstaben gleich breit sind.

Das ist nun nicht mehr nötig. Habe daher:

- die gleiche Schrift gewählt, wie (hoffentlich) überall
- bei dieser Schrift ist fett auch wirklich fett(er)
- 16px statt 14px Grösse
- die Farbe etwas angepasst

Wenn die Schriften zu klein sein sollten bzw. nach ein paar Stunden am Bildschirm die Augen entlastet werden sollen: Im Browser kann man die Schriften vergrössern:

- auf Windows CTRL und Plus-Taste gleichzeitig drücken, bzw. CTRL plus Minus
- auf Windows CTRL drücken und das Mausrad drehen

Du musst selber üben, wie das auf dem Mac geht.
Es gibt auch entsprechende Befehle in den Browser-Menüs (irgendwo...).

Ich schliesse mal dieses Issue, da es +- erledigt sein könnte. Öffne es einfach wieder, wenn du nicht dieser Meinung bist.

**Comment by barbalex** [comment]
Danke für den Input!
