### ISSUE TITLE
Statt Pop-Nr Abstand m zur Beobachtung

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#81]
Ähnlich Fehler #38 
Sobald ich in Stammbaum auf eine Beobachtung klicke, werden alle Pop- und TPop-Nr durch Abstand m zur gewählten Beobachtung angezeigt. Zuerst im Wechsel mit der Nr. (ca 2 Sekunden), dann bleibt es dauerhaft beim Abstand bis zu Reload.

**Comment by barbalex** [comment]
Ist in der Entwicklungsversion behoben

**Comment by csalzmann** [comment]
Jetzt ist es so, dass Pop/TPop-Nr zwar angezeigt werden (vielleicht schon vorher so?), aber Populations-Name rsp. TPop-Name durch Abstand in m ersetzt wird. Könntest Du da nochmals dahinter? Brauche diese Angabe um Beobachtungen zuzuordnen.

**Comment by csalzmann** [comment]
P.S. Funktioniert jetzt mit re-open, Danke :)!

**Comment by barbalex** [comment]
> Jetzt ist es so, dass Pop/TPop-Nr zwar angezeigt werden (vielleicht schon vorher so?), aber Populations-Name rsp. TPop-Name durch Abstand in m ersetzt wird

Wo meinst du das?

- Der Fehler war im Strukturbaum (dort hat es fälschlicherweise den Abstand angezeigt). Daher nehme ich an, du meinst auch diesen. Dort passiert das, was du jetzt beschreibst aber nicht, oder?
- Meinst du allenfalls die Liste im Formular im Feld "Einer Teilpopulation zuordnen"? Die Beschriftung dort war schon immer so wie sie jetzt ist.

Ich könnte im Feld "Einer Teilpopulation zuordnen" die Namen recht einfach ergänzen aber: Dann wird die Zeile sehr lang und weniger übersichtlich. Denn im Gegensatz zum Strukturbaum werden hier die Informationen von Population _und_ Teilpopulation angezeigt. _Plus_ Status.

Daher habe ich schon immer bewusst auf das Ergänzen der Namen verzichtet.

**Comment by barbalex** [comment]
Ergänzend zum letzen: Der Abstand in Metern scheint mir recht wichtig. Dein Text tönt aber, als ob die Namen wichtiger wären. Habe ich das falsch interpretiert?

**Comment by csalzmann** [comment]
Ich hatte das Gefühl (aber im Nachhinein ist es manchmal ja schwierig zu sagen wie es vorher war), dass die TPop auch mit Namen beschriftet war. Du hast aber recht, es ist nicht unbedingt nötig. Ich habe jetzt links Strukturbaum 1 mit  Daten 1, wo ich nicht zugeordnete Beobachtungen anklicke. Anschliessend Daten 2 (wo ich die Namen der TPops sehe) und ganz rechts die  Karte. 
Ganz wichtig ist tatsächlich der Status.
Schon ziemlich cool jetzt so, wirklich Alex! Danke vielmals!

![screenshot 16](https://user-images.githubusercontent.com/6047564/31043853-934e702e-a5c3-11e7-9966-91427846c699.png)

**Comment by barbalex** [comment]
o.k., dann schliesse ich den issue
danke für die Blumen

**Comment by csalzmann** [comment]
Jetzt wollt ich grad noch fragen wegen den Zuordnungslinien - aber die sind ja auch da, wenn man sie denn anklickt:). Perfekt.

**Comment by barbalex** [comment]
:-)
