### ISSUE TITLE
Qualitätskontrolle - Zählung ohne Anzahl, bei EKF und Feldkontrolle aufgeführt

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#82]
Bei Saxifraga wird der gleiche Fehler bei EKF und bei Feldkontrolle aufgeführt. Es ist aber ein Fehler in der EKF.
![screenshot 14](https://user-images.githubusercontent.com/6047564/30908470-ef40ec38-a37d-11e7-8cb2-0e0f6f501146.png)

**Comment by barbalex** [comment]
Danke für die Meldung.

Ist korrigiert. Auch auf der Datenbank des Servers. Nur: scheinbar wird die Abfrage vom Server hartnäckig zwischengespeichert. Es wird wohl eine Weile dauern, bis die neuen Ergebnisse geliefert werden :-)

**Comment by barbalex** [comment]
passiert nun auch wieder im Entwicklungsmodus

**Comment by barbalex** [comment]
o.k., nun endlich richtig korrigiert

funktioniert nun auch live
