### ISSUE TITLE
Qualitätskontrolle Populationsbericht verfeinern (falsche Fehlermeldung)

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#83]
Bsp Himantoglossum, Pop 100.
Bei letzter EK 2013 wurde angesiedelte TPop auf erloschen gesetzt -> Pop/TPop Status erloschen
2014: Ansaat -> TPop/Pop Status Ansaatversuch
2015 Ansiedlung in TPop 100.17 -> TPop und Pop 100 aktuell

Fehlermeldung Qualitätskontrolle wegen Populationsbericht 2013 (erloschen), obwohl alles richtig.

**Comment by barbalex** [comment]
Der Titel der Kontrolle lautet:

> Population: Status ist "aktuell", der letzte Populations-Bericht meldet aber "erloschen"

Und das ist in diesem Fall genau so. Denn der Status wurde geändert, es wurde aber nicht darüber berichtet.

Und daher macht die Kontrolle genau, was von ihr verlangt wird.

Falls es stimmt, dass man weiss, dass die TPop nun wieder existiert: Müsste man dann nicht darüber berichten? Sonst wird sie im Jahresbericht falsch ausgewiesen bzw. die Datenlage ist inkohärent.

Oder habe ich etwas falsch verstanden?

**Comment by csalzmann** [comment]
Es ist eben so, dass eine Ansiedlung automatisch bedeutet, dass eine TPop "aktuell" ist, weil es ja tatsächlich Pflanzen gibt - im Unterschied von Ansaaten, wo man nicht weiss, wann und ob diese keimen. Von daher ist die TPop/Pop in meinem Bsp. oben ab 2015 wieder aktuell, auch ohne EK.

**Comment by barbalex** [comment]
Dann müsste also die Qualitätskontrolle so lauten:

> Population:  Status ist "aktuell", der letzte Populations-Bericht meldet aber "erloschen" _und es gab seither keine Ansiedlung_

Kann ich machen, ist aber ca. 20 Minuten Arbeit.

**Comment by csalzmann** [comment]
Meinst Du als Kontrolle oder als Fehlermeldung?
Scheint mir so nicht richtig, dass es ja eine Ansiedlung seit dem letzten Populationsbericht "erloschen" gab.

**Comment by barbalex** [comment]
Ich meine, dass die Kontrolle diese Fall nicht angezeigt hätte, weil es seither eine Ansiedlung gab. Und dass sie das auch im Titel sagt, damit man auch nachvollziehen kann, wieso dieser Fall nicht angezeigt wurde.

Aber ich verstehe immer noch nicht, wieso über die Ansiedlung nicht berichtet wird. Im Jahresbericht erscheint diese Teilpopulation als erloschen. Ist das gewollt?

**Comment by csalzmann** [comment]
Ich glaube, wir reden immer noch aneinander vorbei.
Immer noch Himanto, Pop 100 und TPop 100.17
Status Pop 100 ist aktuell, weil TPop 100.17 aktuell ist (es gab eine Ansiedlung im 2015). Es gibt jetzt keine Fehlermeldung mehr wegen dem letzten PopBericht von 2013, der "erloschen" meldete. Das ist genau was ich will.

Ich verstehe jedoch Deine Abfrage und Deine Fragen oben nicht. Es gab doch eine Ansiedlung. Vielleicht ist es ja nur ein Tippfehler, in Deiner Abfrage solltest Du meiner Meinung nach schreiben "aber es gab seither eine Ansiedlung" (und nicht KEINE).

Was meinst Du mit "es wird nicht über die Ansiedlung berichtet"? Es gab leider seit der Ansiedlung keine EK, drum kein Bericht. 

Nun ist mir diesbezüglich aber was Neues aufgefallen:

Jetzt meldet die Qualitätskontrolle "keine TPop hat den Status der Pop". Das stimmt ja gar nicht (Pop 100 und TPop 100.17 sind aktuell). ? Könnte damit zusammenhängen, dass Du diese TPop im Jahresbericht als erloschen siehst? Aber dann würde der Jahresbericht vom tatsächlichen Status dieser TPop abweichen. ??

Bei Pop 105 taucht diese falsche Fehlermeldung auch auf, obwohl Pop 105 aktuell ist und TPop 105.13 auch.

**Comment by barbalex** [comment]
Schliesse weil alt und keine weiteren Meldungen
