### ISSUE TITLE
Exporte - manchmal Fehlermeldung

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#85]
Habe diverse Male versucht, Kontrollen und Kontrollen: Anzahl pro Zähleinheit herunterzuladen. Ich muss dazu noch vorausschicken: ich habe hier kein sehr schnelles Internet. Die ersten Male habe ich Fehlermeldungen gekriegt, da wurde dann gar nichts runtergeladen. Anschliessend dann doch mal noch. Danach hat es ewig und eine Ewigkeit gedauert, bis ich das Excel dann endlich öffnen konnte (habe es zuvor abgespeichert nach dem Download). Hier noch die Fehlermeldung. Ich meinte allerdings, ich hätte zuerst Fehlermeldung 502 und dann erst 503 bekommen (habe aber nur letztere speichern können, so bin ich nicht ganz sicher). Ich weiss nicht, wie das alles zusammenhängt. Aber wenn ich Dir nicht den Fehler hätte melden wollen, dann hätte ich beim ersten Mal wohl aufgegeben und gedacht, es funktioniere gar nicht.
![screenshot 17](https://user-images.githubusercontent.com/6047564/31071118-203fdc34-a763-11e7-8dbd-95875c3cd75e.png)

**Comment by barbalex** [comment]
503 heisst: Der Server war überlastet.

Das sehe ich zwar nicht so krass in der Statistik des Hosters. Laut diser war er zu ca. 30% ausgelastet. Jedenfalls gab es schon etwas Last.

> Habe diverse Male versucht

Wenn du einen Server in die Knie bringen willst:

- such dir eine Anfrage, die ihn belastet (wie z.B. diesen Export)
- schick sie mehrere male kurz nacheinander

So machen es die Internet-Ganoven, das nennt sich dann Denial-Of-Service-Attack und damit kann man sogar Amazon in die Knie zwingen ;-)
(Amazon hat die grösste Server-Farm der Welt)

> Danach hat es ewig und eine Ewigkeit gedauert, bis ich das Excel dann endlich öffnen konnte (habe es zuvor abgespeichert nach dem Download).

Dieser Vorgang ist rein lokal auf deiner Maschine. Das deutet auf eine sehr grosse Belastung deines PC's hin. Und diese könnte auch bewirken, dass der Browser die vom Server gelieferte Datenmenge gar nicht verarbeiten konnte.

In diesem Fall könnte also die langsame Internetverbindung zusammen mit einem schwachen oder ausgelasteten PC Einfluss gehabt haben.

Trotzdem: Der apflora-Server war bisher v.a. durch drei Sachen gelegentlich stark belastet:

- Wenn jemand in der alten Anwendung eine Art mit sehr vielen Daten öffnete (weil die alte Anwendung dann all diese Daten gleichzeitig abholte)
- Bei den Exporten, insbesondere diesem, der eierlegenden Wollmilchsau und ev. noch ein paar wenigen weiteren
- Wenn ich die Abfragen für den EvAB-Export laufen lasse (das mache ich daher nur noch auf lokalen Kopien)
- Ev. auch, wenn man Jahresberichte über alle Arten erstellt (ich bin nicht sicher, ob Access genügend langsam ist, dass es den Server nicht stresst)
- Vermutlich auch, wenn man Qualitätskontrollen laufen lässt. Jedenfalls bei Arten mit vielen Daten

Das alles war der Grund, warum ich mir schon überlegt habe, die Export- und QK-Abfragen an einen zusätzlichen Server zu leiten. Damit würden sie den Server, auf dem man arbeitet, nicht belasten. Dieser zusätzliche Server würde laufend mit dem Arbeitsserver synchronisieren, damit die Daten fast aktuell sind (höchstens wenige Sekunden hinter dem Arbeits-Server).

Falls wir:

- diese Probleme oft genug sehen
- auch auf schnellen Internetverbindungen und mit unbelasteten, leistungsstarken PC's
- Server-Abstürze erleben, die mit solchen Überlastungen zusammenhängen

müssten wir uns das einmal überlegen.

**Comment by barbalex** [comment]
Lieber Alex

Danke für Deine ausführlichen Erklärungen! Ich wollte also keine Ganovin sein;). Eigentlich ist mein PC ein nigelnagelneuer Lenovo, und ich hatte nur die FloraDB und das Excel mit den Abfragen am laufen.

Ich/wir werden es beobachten und wenn es wieder passieren sollte darauf zurückkommen.

Ich bin nun wieder zurück aus den Ferien. Heute aber im Feld. Ich arbeite Deine mails nun ab (im Moment im Zug). Entschuldige, wenn ich nicht so schnell damit bin! 

Herzliche Grüsse und vielen Dank für Deine grandiose Arbeit, Charlotte

Von meinem iPhone gesendet

**Comment by barbalex** [comment]
Ich schliesse diesen Issue weil Alt und nicht nachvollziehbar. Falls das Problem wieder auftaucht, bitte wieder öffnen
