### ISSUE TITLE
Öffnen/Schliessen von Teilpopulationen

### ISSUE THREAD

**Issue by wunderli** [barbalex/apf2#9]
Zurzeit kann nur eine Teilpopulation gleichzeitig im Baum angezeigt werden.
Wenn ich eine andere öffne, schliesst sie die erste wieder.
Dies ist ein Nachteil, da ja später Massnahmen, ect. von einer Tpop in eine andere kopiert werden sollen. Aber vielleicht folgt das sowieso noch?

**Comment by barbalex** [comment]
jein ;-)

Um Elemente zu Kopieren und Verschieben, ist geplant, einen zweiten Strukturbaum einzublenden. Zwischen diesen kann man dann hin und her kopieren/verschieben.

Dass nur ein Element aufs Mal geöffnet werden kann war ein bewusster Entscheid von mir, mit u.a. folgenden Gründen:

- in den meisten Fällen übersichtlicher
- viel einfacher zu programmieren

Zu letzterem folgende Erklärung:

In der letzten Version von apflora.ch war der Strukturbaum eine externe Software, die eingebunden wurde. Das hat Vor- und Nachteile. Nachteile waren u.a.:

- dass man Fehler nicht selber beheben kann. Z.B. musste ich die Möglichkeit, Elemente durch Drag & Drop zu verschieben, ausschalten (mal schauen, ob ich das mit der neuen Version hinkriege).
- Und vor allem: Das die externe Software von deren Entwicklern so weiterentwickelt werden kann, dass sie mit den früheren Versionen nicht mehr kompatibel ist.

Genau das ist passiert. Worauf wir jetzt mit einem Strukturbaum leben, der jeden Moment bei einem der Updates eines Browsers aufhören könnte, zu funktionieren...

Um das zu verhindern und weil es mit der verwendeten Technologie viel besser geht, habe ich den Strukturbaum nun selber programmiert. Und zwar so, dass er (Bonus) zig Tausend Elemente darstellen kann, ohne dass der Browser in die Knie geht (wie bei der letzten Version). Dafür mit dem Nachteil, dass ich die zusätzliche Komplexität, mehrere Ordner gleichzeitig offen haben zu können, vermieden habe.

Ich schliesse mal dieses Issue, weil der Grund den du genannt hast, mit dem zweiten Strukturbaum behoben werden soll. Öffne es wieder, wenn du andere Gründe findest, die mit dem zweiten Strukturbaum nicht abgedeckt werden können.
