### ISSUE TITLE
Beobachtungen synonyme Arten zuordnen - Arten für Beobachtungen?

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#90]
Ich verstehe den Punkt "Arten für Beobachtungen" nicht ganz. Wie kann ich eine neue Art hinzufügen? Z.B. P. plantagineus (Synonym) zu P. coloratus?

**Comment by csalzmann** [comment]
Ich glaube, ich verstehe jetzt, wie es funktionieren sollte. Aber für eine zusätzliche Art kann ich nur Arten auswählen, die nicht schon bearbeitet wurden. Es stehen also keine AP-Arten zur Verfügung. Ich bräuchte ja aber ganz gezielt die syn. AP-Beobachtungen. Müsste man da zuerst wieder die Art "löschen"? Was passiert aber, wenn in der syn. Art schon Beobachtungen zugeordnet wurden? Das war ja auch mal ein Punkt, den wir besprochen haben. Ich meine, die Quintessenz war, dass Beobachtungen nicht automatisch wieder "frei" werden, wenn man eine Art löscht. Ich will es deshalb nicht einfach probieren..
Ausserdem, ich hab versucht Arten hinzuzufügen, aber die Anzahl Beobachtungen (nicht zugeordnet) bleibt immer gleich. Habe ich ausgerechnet solche ohne Beobachtungen erwischt oder funktioniert es nicht? Oder vertehe ich es einfach nicht richtig, wie es gehen sollte?
Der Punkt ist für mich ziemlich prioritär.

**Comment by barbalex** [comment]
> Aber für eine zusätzliche Art kann ich nur Arten auswählen, die nicht schon bearbeitet wurden.

Das habe ich extra so programmiert, um sicher zu stellen, dass dieselbe Art nur ein mal erfasst werden kann. Das wäre ja sicher nicht sinnvoll. Ausser, wenn es früher passierte, weil man keine Synonyme erfassen konnte... das hatte ich vergessen.

Habe diese Funktion wieder ausgeschaltet. Ich kann sie später jederzeit wieder einschalten. Falls du willst, wenn ihr die vorhandenen Arten wieder gelöscht habt, weil man jetzt Beobachtungen in der richtigen Art zuordnen kann.

**Comment by barbalex** [comment]
> Ich meine, die Quintessenz war, dass Beobachtungen nicht automatisch wieder "frei" werden, wenn man eine Art löscht

Das ist nicht mehr so. Habe ich extra angepasst.

**Comment by barbalex** [comment]
> Habe ich ausgerechnet solche ohne Beobachtungen erwischt oder funktioniert es nicht?

Ja, vermutlich. Nachdem ich diese Funktion aufwändig programmiert hatte, tauchten bei den ersten Tests nach Einfügen einer Art keine Beobachtungen auf. Ich war extrem enttäuscht. Bis ich merkte, dass für diese Art keine Beobachtungen vorlagen...

**Comment by barbalex** [comment]
Ich _glaube_ es ist alles beantwortet oder so angepasst, dass es klappt. Schliesse daher.

**Comment by csalzmann** [comment]
Super, Danke vielmals!
