### ISSUE TITLE
Anzeige "Neues" - behalten zum Nachlesen

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#91]
Es gibt ja neu dieses Fenster, wo Du die Neuigkeiten der FloraDB auflistest. Manchmal geht es mir dann aber doch zu schnell, das zu erfassen - und nachher ist es weg.
Könnte man die letzten Neuigkeiten evtl. auch noch in dem Menü rechts oben (wo es auch die Video-Anleitungen hat) abspeichern zur späteren Ansicht?

**Comment by barbalex** [comment]
Schön, dass diese Nachrichten als nützlich empfunden werden :-)

Klar kann man das. Die Nachrichten waren aber schon gratis, ich habe einfach gedacht, es wäre nützlich und ich will das machen. Daher taxiere ich das als Erweiterung. Aufwand ca. 2 Stunden.

**Comment by barbalex** [comment]
ist umgesetzt
