### ISSUE TITLE
Beobachtungen: Serverleistung mit Linien

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#93]
Mir ist aufgefallen, dass das Kartentool extrem langsam wird, sobald man die Linien eingeschaltet hat. Ich hatte das Gefühl, das war bei meinen ersten Versuchen anders (und da hatte ich langsames Internet). Auf jeden Fall muss ich jetzt eigentlich die Zuordnungslinien ausschalten, die so extrem praktisch wären, um arbeiten zu können. 
Hättest Du da eine Lösung?

**Comment by barbalex** [comment]
Was genau wird langsamer? Mögliche Beispiele:
- Zuordnen
- Anzeigen der Teilpopulationen
- Anzeigen der Zuordnungs-Linien
- Generell Anzeigen der Daten aus apflora (TPop, Beobachtungen, Linien...)
- Zeichnen der Hintergrundkarten
- anderes?

Hast du Konkrete Beispiele?

Ich frage, weil es bei meinen Tests bisher nicht so schien.

**Comment by barbalex** [comment]
Ich schliesse diesen Issue weil schon alt und nicht nachvollziehbar. Falls das Problem wieder auftritt, bitte wieder öffnen
