### ISSUE TITLE
Beobachtungen zuordnen: Nach Zuordnung im Menü Beobachtungen bleiben

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#94]
Nachdem man eine Beobachtung zugeordnet hat, bleibt die Markierung bei der betreffenden Beobachtung, die sich aber jetzt natürlich in der zugeordneten TPop befindet. 
Vom Arbeitsablauf wäre es viel angenehmer, man würde im Menü "nicht zugeordnete Beobachtungen" bleiben, weil man will ja diese abarbeiten will. So muss man dann wieder durch alle Pops durchscrollen, bis man wieder bei den Beobachtungen ist.
Wäre das möglich?

**Comment by barbalex** [comment]
Hineinkopiert aus dem Mail an Karin Sartori, die denselben Wunsch meldete:

Der Grund für dieses Verhalten: 

Es gibt nicht nur die Zuordnung an sich, die man beschreiben kann. Es gibt auch das Feld "Bemerkungen zur Zuordnung". Und es ist denkbar, das künftig hier mehr Funktionen bereit stehen (z.B. im Zusammenhang mit Rückmeldungen an Info Flora).

Wenn man nun eine Zuordnung erstellt, scheint es recht natürlich zu sein, dass man zuerst zuordnet (oder auf nicht zuzuordnen setzt) und danach die Details weiter beschreibt.

Voraussetzung dafür ist aber, dass das Formular der Beobachtung nach der Zuordnung offen bleibt.

Und es würde bestimmt als Fehler der Anwendung wahrgenommen, wenn der Baum neben dem Formular nicht den richtigen Pfad für die im Formular angezeigte Beobachtung anzeigen würde.

Ausserdem wäre nun in der Programmierung nicht mehr eindeutig zu sagen, wann bei der Anzeige einer Beobachtung der richtige Pfad angezeigt wird und wann der Ordner für die noch nicht zugeordneten Beobachtungen. Bestimmt gäbe es Situationen, in denen man den richtigen Pfad zwingend anzeigen sollte, z.B. wenn später (nicht im Zusammenhang mit der Zuordnung) das Formular für eine zugeordnete (oder nicht zuzuordnende) Beobachtung geöffnet wird.

Ich bin also nicht so sicher, dass diese Änderung nicht Probleme bzw. neue Wünsche schaffen würde. Und die Programmierung wäre recht aufwändig bzw. unterhalts-gefährlich, weil dieses Verhalten vom normalen Verhalten abweicht.

**Comment by barbalex** [comment]
Hineinkopiert aus dem Mail von Charlotte:

Dieses Verhalten würde man als User nicht als Fehler interpretieren. Es lohnt sich auch nicht, nach jeder Zuordnung die TPop anzupassen, weil es manchmal div Beobachtungen für die gleiche TPop gibt. Ich habe das "bekannt seit" nun immer am Ende nochmals bei alle TPops und Pops kontrolliert und angepasst. Meist ist das Jahr die einzige Info die man anpassen muss, die TPop existiert ja schon.

Du hast in dem Falle recht, wo es sich nur um einige wenige Beobachtungen handelt, da würde man wohl sofort bekannt seit anpassen wollen. könnte man aber auch über den 2. baum.

Also geholfen wäre uns nur schon, wenn wenigstens der Menüpunkt Beobachtungen offen bliebe.

**Comment by barbalex** [comment]
Habe soeben gemerkt, dass bisher explizit gewünscht wurde, nach der Zuordnung zur Teilpopulation zu springen: https://github.com/FNSKtZH/apflora/issues/93.

Dieser Wunsch war auch in der Kostenschätzung für 2017 enthalten. Die Umsetzung wurde aus Budget-Gründen zwar nicht beschlossen. Trotzdem wurde es von mir so umgesetzt, weil es dem normalen Verhalten im Baum entspricht.

**Comment by barbalex** [comment]
Ich schliesse das, weil alt
