### ISSUE TITLE
Kartentool allgemein extrem langsam

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#95]
Ich kann mir nicht vorstellen, dass das nur an der Serverleistung der Kartenserver liegt. Beim GIS-Browser haben wir diese Probleme ja auch nicht. Es ist auch bei OpenStreetMap langsam, und nicht nur bei der Dufour-Karte (Danke!!!!), mit der ich jetzt gerne arbeiten würde.
Also es ist so langsam, dass ich im Moment eigentlich nicht damit arbeiten kann, weil ich so lange auf die Aktualisierung der Karte warten muss. Und blöd: Ich kann dann ja auch nicht in den anderen Fenstern warten.
Vorhin hatte ich gar eine Meldung auf meinem Compi (der PC), dass eine Website die Leistung mindere. Damit ist wohl diese hier gemeint, andere habe ich nicht offen.

**Comment by csalzmann** [comment]
OK, nach Neustart Browser etwas besser. Es liegt sicher nicht an den Karten. Aber irgendwie hängt sich das Kartentool manchmal auf. Wohl je nachdem, welche Funktionen man alle anklickt bei den Beobachtungen. Es ist mir eben auch nicht das erste Mal passiert. Es klemmt da noch was.

**Comment by csalzmann** [comment]
Die Karte macht immer noch Probleme. Zuerst dachte ich, es läge an den Beobachtungen. Ich hatte TPop und Beobachtungen nicht zugeordnet eingeblendet. Die Applikation ist nun so langsam, dass ich zuwarten muss, bis die Buchstaben geschrieben werden. Sobald ich die Karte ausschalte, alles wieder normal.
Es nützt aber nichts, im Nachhinein die Beobachtungen auszublenden und es so mit der Karte zu versuchen. Es bleibt so langsam.
Also ich alles neu geladen. Karte angeklickt. Noch alles OK. Sobald ich aber auf TPop einblenden gehe, wirds wieder langsam mit dem Schreiben in den Daten.
Es ist einfach komisch, am Anfang war das nicht so. Oder ich hatte einfach Glück? Da glaub ich irgendwie auch nicht recht dran. Hat es denn vielleicht etwas mit dem Zoom und den Neu-Alten Karten zu tun? Ich lass es auf jeden Fall jetzt für heute:).

**Comment by csalzmann** [comment]
Also es scheint so, als ob sich da was kumuliert. Am Anfang läuft es normal, dann nach ein paar Zuordnungen fängt das wieder an, dass ich kaum mehr Daten eingeben kann, solange die Karte offen ist.

**Comment by barbalex** [comment]
Was muss man machen, damit man dieses Verhalten nachvollziehen kann?

Reicht es, einfach nur das Kartentool zu öffnen?
Muss man es wiederholte öffnen?
Muss man Ebenen ein- und ausblenden?
Muss man zuordnen?

**Comment by csalzmann** [comment]
Ich bin da nun weiter am Testen. Problem ist wohl: zuhause auf meinem Compi kann ich praktisch nicht mit dem Kartentool arbeiten. Bei topos scheint sich die Applikation wirklich anders zu verhalten. Das hätte ich nicht erwartet!
Zuhause arbeite ich mit PC (habe einen relativ neuen schönen Lenovo) und favorisiert mit Firefox.
Da beginnen die Probleme nach 1, 2 Zuordnungen von Beobachtungen und/oder zoom auf eine TPop o.ä. Da ich zuhause die Beobachtungen zugeordnet habe, habe ich x-mal neu laden müssen, weil alles abgestürzt ist. Ich bin ja mega froh, ist das offenbar nicht überall so! Trotzdem nähme mich natürlich wunder, was los ist - das könnte ja auch jemand anders passieren.
Ich schaue jetzt aber zuerst mal, was mir bei topos auf dem Mac zu dieser Sache auffällt. 
Vielleicht finden wir beide in einem 2. Schritt dann doch mal noch raus, was bei mir auf dem PC los ist..

**Comment by barbalex** [comment]
Bei mir klappt es i.O.

Wirklich schnell ist es ja nicht, aber tolerabel.

**Comment by csalzmann** [comment]
Also, jetzt hab ich dieses Problem auch mal bei topos auf Mac und Chrome. Es liegt also nicht einfach nur an meinem schönen Lenovo. 
Wenn die Karte offen ist, ist die Applikation unerträglich langsam, va wenn ich Text eingeben will. Sobald ich die Karte ausstelle, gehts wieder. Als Karte hab ich sogar die einfachste von allen drin (Open Street Map). Und die Operationen waren bisher lediglich: Zoomen auf TPops, danach habe ich im Strukturbaum eine neue Pop erstellt und 2 TPops verschoben (in die neue Pop). Seit da ist es langsam. Nach Reload wieder gut. Sobald ich wieder auf TPop zoome, wirds langsam. Dieses Verhalten hat mich beim Zuordnen von Beobachtungen fast wahnsinnig gemacht.

**Comment by barbalex** [comment]
Hab jetzt 10 Minuten lang:

- wild umher gezoomt, z.T. auf TPop, Pop, alle TPops, alle Pops
- TPop kopiert, verschoben
- Neue Pop gemacht und TPops dorthin verschoben
- Hintergrundkarten gewechselt
- Daten erfasst

und dabei Geschwindigkeit und Ressourcenverbrauch beobachtet.

Natürlich habe ich nichts nachvollziehen können :-(

**Comment by csalzmann** [comment]
Der Klassiker.. Aber Danke vielmals fürs Probieren. Wenn mir wieder was auffällt, melde ich es halt. Vielleicht kommst Du dem doch irgendwann auf die Sprünge. Rebecca hat ja auch so komische Sachen mit dem kopieren, mal gehts eine Weile gut, dann wieder eine Weile schlecht.

**Comment by barbalex** [comment]
Ich schliesse diesen Issue weil schon alt und nicht nachvollziehbar. Falls das Problem wieder auftritt, bitte wieder öffnen
