### ISSUE TITLE
Kartentool - Massstab auch manuell

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#96]
Wäre noch cool, wenn man Massstab auch manuell eingeben könnte und dass man nicht nur mit der Maus zoomen kann

**Comment by barbalex** [comment]
Kennst du den Trick mit der Maus und der Shift-Taste? Das geht so:

Die Shift-Taste ist diejenige, die du drückst, um einen Grossbuchstaben zu schreiben.
Du kannst mit der Maus ein Rechteck aufziehen, auf das dann gezoomt wird, wenn du:
- die Shift-Taste drückst und gedrückt haltest
- mit der Maua zur oberen rechten Ecke des gewünschten Ausschnitt gehst
- die linke Maustaste drückst
- mit der Maus zur unteren rechten Ecke des gewünschten Ausschnitts fährst
- die linke Maustaste loslässt
- die Shift-Taste losläst

Ansonsten: Das mit dem Massstab ist möglich. Man müsste aber darüber reden, wie er gemessen wird. Das verwendete Tool benutzt 1 bis 24.

**Comment by csalzmann** [comment]
Danke für den Tipp! Das ist sicher besser als einfach ungerichtet reinzoomen.

1-24 verstehe ich nicht. Ich meinte sowas wie beim GIS-Browser:

![bildschirmfoto 2017-11-07 um 11 08 13](https://user-images.githubusercontent.com/6047564/32488148-faf6dfbc-c3ab-11e7-8628-b3a213f11e8b.png)

**Comment by barbalex** [comment]
Danke für die Ergänzung, jetzt ist ganz klar, was du meinst.

**Comment by barbalex** [comment]
Nach etwas Recherche bin ich verunsichert. Es gibt dafür keine vorbereiteten Werkzeuge. Und der Grund dafür wird klar, wenn man weiss, wie das funktionieren müsste. Denn: Der Massstab hängt ab von (nur die wichtigsten Einflüsse aufgezählt):

1. Anzahl Pixel eines Karten-Tiles (die Grundeinheiten, in die Web-Karten aufgeteilt werden)
2. Geographische Höhe: Karten sind eine flache Darstellung einer Kugel. Das verzerrt die Verhältnisse. Am Äquator ist der Massstab daher radikal anders als nahe an einem Pol
3. Auflösung des Bildschirms, auf dem die Karte dargestellt wird. Höhere Auflösung > dieselbe Distanz wird auf weniger cm dargestellt


2 (Geographische Höhe) könnte man für kleine Gebiete +- genau fix wählen. 

3 (Auflösung des Bildschirms) kann theoretisch via Javascript ermittelt werden - bin aber nicht ganz sicher, wie zuverlässig das klappt.

1 (Anzahl Pixel eines Karten-Tiles) ist das grösste Problem. Das kann bei jeder Hintergrund-Karte unterschiedlich sein.

Du nennst als Beispiel den GIS-Browser des Kantons Zürich. Die haben es einfach(er), weil sie als Hintergrund nur eigene Karten anbieten.

Ich such noch weiter, aber selbst wenn ich eine Lösung finden sollte: besonders genau und zuverlässig wird sie kaum sein. Im Gegensatz zu einer Papierkarte sollte man nie mit dem Massstab auf dem Bildschirm messen... (Abgesehen davon: Auch auf einer Papier-Karte kann der Massstab unmöglich überall genau gleich sein).

Das einzige genaue Mass liefern Messwerkzeuge, die ihr ja auf apflora.ch habt. Sie können die Bildschirmauflösung ignorieren. Und die Erdkrümmung berücksichtigen.

**Comment by barbalex** [comment]
ist umgesetzt :-)

https://github.com/barbalex/apf2/blob/master/etc/mapScaleControl.md
