### ISSUE TITLE
Beobachtungen - einer Zuordnung entfernen

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#97]
Wenn ich eine Beobachtung von einer TPop entferne und sie einer anderen zuordnen möchte, dann bleibt dafür im Strukurbaum nur die Funktion "nicht zuordnen". Das bewirkt aber, dass die Beobachtung zu den "nicht zuzuordnenden" verschoben wird, was nicht richtig ist.

**Comment by csalzmann** [comment]
Ich kann manchmal eben nicht direkt schon vom Strukturbaum her sagen, welche andere TPop es denn sein soll, deshalb möchte ich sie zuerst wieder im Pool der nicht zugeordnenten haben

**Comment by barbalex** [comment]
Du hast zwei Möglichkeiten:

- direkt der anderen TPop zuweisen. Es ist nicht nötig, die Beobachtung zuvor als "nicht beurteilt" zu deklarieren
- im Formular nochmals auf die markierte Zuordnung klicken. Die Zuordnung wird aufgehoben und die Beobachtung ist im Baum wieder unter "nicht beurteilt".

**Comment by csalzmann** [comment]
Danke! Das muss man aber wissen, sonst kommt man nicht drauf! (Bin gerade daran, die Zuordnungen der syn. Art C. palustris zu entfernen..). Vielleicht kann man ja noch eine Bemerkung dazu platzieren?

**Comment by barbalex** [comment]
Es ist das Standard-Verhalten für alle Options-Listen in apflora.ch (und vielen anderen Anwendungen).

Ich habe jetzt noch eine Info daneben platziert, welche es erklärt.
