### ISSUE TITLE
Nach Reload fällt Selektion raus

### ISSUE THREAD

**Issue by csalzmann** [barbalex/apf2#99]
Habe ja vorhin ein paar Mal reloaden müssen, und dann muss man jedes Mal Selektion (z.B. der Art) wieder machen. Könnte man diese speichern? Es wird ja auch gespeichert, welche Fenster (Strukturbaum 1 und 2, Daten 1 und 2 etc ) man offen hatte.

**Comment by barbalex** [comment]
Ja, das ist möglich. Aber ein paar Stunden Aufwand.

**Comment by csalzmann** [comment]
Machen wir es mal auf die "nice to have" - Liste..
